#ifndef Z2PARAM_H
#define Z2PARAM_H

#include "dolphin/types.h"

struct Z2Param {
    static f32 DISTANCE_MAX;
    static f32 MAX_VOLUME_DISTANCE;
    static f32 DOLBY_CENTER_VALUE;
    static f32 DOLBY_FLONT_DISTANCE_MAX;
    static f32 DOLBY_BEHIND_DISTANCE_MAX;
    static f32 DISTANCE_FX_PARAM;
    static f32 SONIC_SPEED;
    static f32 VOL_BGM_DEFAULT;
    static f32 VOL_SE_SYSTEM_DEFAULT;
    static f32 VOL_SE_LINK_VOICE_DEFAULT;
    static f32 VOL_SE_LINK_MOTION_DEFAULT;
    static f32 VOL_SE_LINK_FOOTNOTE_DEFAULT;
    static f32 VOL_SE_CHAR_VOICE_DEFAULT;
    static f32 VOL_SE_CHAR_MOVE_DEFAULT;
    static f32 VOL_SE_OBJECT_DEFAULT;
    static f32 VOL_SE_ATMOSPHERE_DEFAULT;
    static f32 VOL_BGM_TALKING;
    static f32 VOL_SE_SYSTEM_TALKING;
    static f32 VOL_SE_LINK_VOICE_TALKING;
    static f32 VOL_SE_LINK_MOTION_TALKING;
    static f32 VOL_SE_LINK_FOOTNOTE_TALKING;
    static f32 VOL_SE_CHAR_VOICE_TALKING;
    static f32 VOL_SE_CHAR_MOVE_TALKING;
    static f32 VOL_SE_OBJECT_TALKING;
    static f32 VOL_SE_ATMOSPHERE_TALKING;
    static f32 VOL_BGM_PAUSING;
    static f32 VOL_SE_SYSTEM_PAUSING;
    static f32 VOL_SE_LINK_VOICE_PAUSING;
    static f32 VOL_SE_LINK_MOTION_PAUSING;
    static f32 VOL_SE_LINK_FOOTNOTE_PAUSING;
    static f32 VOL_SE_CHAR_VOICE_PAUSING;
    static f32 VOL_SE_CHAR_MOVE_PAUSING;
    static f32 VOL_SE_OBJECT_PAUSING;
    static f32 VOL_SE_ATMOSPHERE_PAUSING;
    static f32 MIN_DISTANCE_VOLUME;
    static f32 ENEMY_LASTHIT_MUTE_VOLUME;

    // made up names based on HIO labels
    static u8 SCENE_CHANGE_BGM_FADEOUT_TIME;
    static u8 BGM_CROSS_FADEIN_TIME;
    static u8 BGM_CROSS_FADEOUT_TIME;
    static u8 BATTLE_BGM_WAIT_TIME;

    static u8 FOUND_TRACK_FI_TIME;
    static u8 FOUND_TRACK_FO_TIME;
    static u8 CLOSE_BATTLE_TRACK_FI_TIME;
    static u8 CLOSE_BATTLE_TRACK_FO_TIME;

    static u8 ENDING_BLOW_VOL_DOWN_TIME;
    static u8 ENDING_BLOW_VOL_LOWER_TIME;
    static u8 ENDING_BLOW_VOL_LOWER_RECOVER_TIME;
    static u8 ENDING_BLOW_MIN_FINISH_TIME;

    static u8 DARK_SE_FILTER_ON;
    static u8 DARK_SE_LOW_PASS_FILTER_SETTING;
    static u8 SYSTEM_SE_USE_DARK_SE_SETTING;
};

extern u8 data_8045086C;

#endif /* Z2PARAM_H */
