#
# Generate By: dol2asm
# Module: 443
#

# Libraries
LIBRARIES = [
	"d/a/obj/d_a_obj_fan",
]

# Translation Units
TRANSLATION_UNITS = [
	"executor",
	"unknown_translation_unit_ctors",
	"unknown_translation_unit_dtors",
	"d_a_obj_fan",
]

# Sections
SECTIONS = [
	".text",
	".ctors",
	".dtors",
	".rodata",
	".data",
]

# Symbols
SYMBOLS = [
	{'addr':0x80BE4BC0,'size':44,'pad':0,'label':"_prolog",'name':"_prolog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE4BEC,'size':44,'pad':0,'label':"_epilog",'name':"_epilog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE4C18,'size':32,'pad':0,'label':"_unresolved",'name':"_unresolved",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE4C38,'size':352,'pad':0,'label':"searchTornado2__FPvPv",'name':"searchTornado2__FPvPv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE4D98,'size':112,'pad':0,'label':"search_tornado__10daObjFan_cFv",'name':"search_tornado__10daObjFan_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE4E08,'size':60,'pad':0,'label':"initBaseMtx__10daObjFan_cFv",'name':"initBaseMtx__10daObjFan_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE4E44,'size':196,'pad':0,'label':"setBaseMtx__10daObjFan_cFv",'name':"setBaseMtx__10daObjFan_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE4F08,'size':204,'pad':0,'label':"Create__10daObjFan_cFv",'name':"Create__10daObjFan_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE4FD4,'size':280,'pad':0,'label':"CreateHeap__10daObjFan_cFv",'name':"CreateHeap__10daObjFan_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE50EC,'size':176,'pad':0,'label':"create1st__10daObjFan_cFv",'name':"create1st__10daObjFan_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE519C,'size':496,'pad':0,'label':"Execute__10daObjFan_cFPPA3_A4_f",'name':"Execute__10daObjFan_cFPPA3_A4_f",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE538C,'size':1200,'pad':0,'label':"action__10daObjFan_cFv",'name':"action__10daObjFan_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE583C,'size':292,'pad':0,'label':"setCollision__10daObjFan_cFv",'name':"setCollision__10daObjFan_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE5960,'size':164,'pad':0,'label':"Draw__10daObjFan_cFv",'name':"Draw__10daObjFan_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE5A04,'size':116,'pad':0,'label':"Delete__10daObjFan_cFv",'name':"Delete__10daObjFan_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE5A78,'size':180,'pad':0,'label':"daObjFan_create1st__FP10daObjFan_c",'name':"daObjFan_create1st__FP10daObjFan_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE5B2C,'size':204,'pad':0,'label':"__dt__8dCcD_SphFv",'name':"__dt__8dCcD_SphFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE5BF8,'size':132,'pad':0,'label':"__ct__8dCcD_SphFv",'name':"__ct__8dCcD_SphFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE5C7C,'size':72,'pad':0,'label':"__dt__8cM3dGSphFv",'name':"__dt__8cM3dGSphFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE5CC4,'size':72,'pad':0,'label':"__dt__8cM3dGAabFv",'name':"__dt__8cM3dGAabFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE5D0C,'size':32,'pad':0,'label':"daObjFan_MoveBGDelete__FP10daObjFan_c",'name':"daObjFan_MoveBGDelete__FP10daObjFan_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE5D2C,'size':32,'pad':0,'label':"daObjFan_MoveBGExecute__FP10daObjFan_c",'name':"daObjFan_MoveBGExecute__FP10daObjFan_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE5D4C,'size':44,'pad':0,'label':"daObjFan_MoveBGDraw__FP10daObjFan_c",'name':"daObjFan_MoveBGDraw__FP10daObjFan_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BE5D78,'size':4,'pad':0,'label':"_ctors",'name':"_ctors",'lib':-1,'tu':1,'section':1,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80BE5D7C,'size':4,'pad':0,'label':"_dtors",'name':"_dtors",'lib':-1,'tu':2,'section':2,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80BE5D80,'size':12,'pad':0,'label':"l_bmd",'name':"l_bmd",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80BE5D8C,'size':12,'pad':0,'label':"l_dzb2",'name':"l_dzb2",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80BE5D98,'size':12,'pad':0,'label':"l_dzb3",'name':"l_dzb3",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80BE5DA4,'size':12,'pad':0,'label':"l_se",'name':"l_se",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80BE5DB0,'size':12,'pad':0,'label':"l_wind_se",'name':"l_wind_se",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80BE5DBC,'size':6,'pad':2,'label':"l_max_rotspeed",'name':"l_max_rotspeed",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80BE5DC4,'size':12,'pad':0,'label':"l_heap_size",'name':"l_heap_size",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80BE5DD0,'size':64,'pad':0,'label':"l_sph_src",'name':"l_sph_src",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80BE5E10,'size':4,'pad':4,'label':"lit_3682",'name':"@3682",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80BE5E18,'size':8,'pad':0,'label':"lit_3683",'name':"@3683",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80BE5E20,'size':8,'pad':0,'label':"lit_3684",'name':"@3684",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80BE5E28,'size':8,'pad':0,'label':"lit_3685",'name':"@3685",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80BE5E30,'size':4,'pad':0,'label':"lit_3686",'name':"@3686",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80BE5E34,'size':4,'pad':0,'label':"lit_3813",'name':"@3813",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80BE5E38,'size':8,'pad':0,'label':"lit_3815",'name':"@3815",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80BE5E40,'size':4,'pad':0,'label':"lit_3929",'name':"@3929",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80BE5E44,'size':4,'pad':0,'label':"lit_3930",'name':"@3930",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80BE5E48,'size':4,'pad':0,'label':"lit_3931",'name':"@3931",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80BE5E4C,'size':4,'pad':0,'label':"lit_3932",'name':"@3932",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80BE5E50,'size':4,'pad':0,'label':"lit_3964",'name':"@3964",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80BE5E54,'size':4,'pad':0,'label':"lit_3965",'name':"@3965",'lib':-1,'tu':3,'section':3,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80BE5E58,'size':30,'pad':0,'label':"d_a_obj_fan__stringBase0",'name':"@stringBase0",'lib':-1,'tu':3,'section':3,'class_template':None,'static':False,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"StringBase"},
	{'addr':0x80BE5E78,'size':12,'pad':0,'label':"l_arcName",'name':"l_arcName",'lib':-1,'tu':3,'section':4,'class_template':None,'static':True,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80BE5E84,'size':48,'pad':0,'label':"l_offset_posM",'name':"l_offset_posM$3940",'lib':-1,'tu':3,'section':4,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80BE5EB4,'size':48,'pad':0,'label':"l_offset_posL",'name':"l_offset_posL$3941",'lib':-1,'tu':3,'section':4,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80BE5EE4,'size':32,'pad':0,'label':"daObjFan_METHODS",'name':"daObjFan_METHODS",'lib':-1,'tu':3,'section':4,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80BE5F04,'size':48,'pad':0,'label':"g_profile_Obj_Fan",'name':"g_profile_Obj_Fan",'lib':-1,'tu':3,'section':4,'class_template':None,'static':False,'is_reachable':False,'r':[0,0,1],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80BE5F34,'size':12,'pad':0,'label':"__vt__8cM3dGAab",'name':"__vt__8cM3dGAab",'lib':-1,'tu':3,'section':4,'class_template':None,'static':False,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80BE5F40,'size':12,'pad':0,'label':"__vt__8cM3dGSph",'name':"__vt__8cM3dGSph",'lib':-1,'tu':3,'section':4,'class_template':None,'static':False,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80BE5F4C,'size':40,'pad':0,'label':"__vt__10daObjFan_c",'name':"__vt__10daObjFan_c",'lib':-1,'tu':3,'section':4,'class_template':None,'static':False,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"VirtualTable"},
]

# Names
SYMBOL_NAMES = {
	"_prolog":0,
	"_epilog":1,
	"_unresolved":2,
	"searchTornado2__FPvPv":3,
	"search_tornado__10daObjFan_cFv":4,
	"initBaseMtx__10daObjFan_cFv":5,
	"setBaseMtx__10daObjFan_cFv":6,
	"Create__10daObjFan_cFv":7,
	"CreateHeap__10daObjFan_cFv":8,
	"create1st__10daObjFan_cFv":9,
	"Execute__10daObjFan_cFPPA3_A4_f":10,
	"action__10daObjFan_cFv":11,
	"setCollision__10daObjFan_cFv":12,
	"Draw__10daObjFan_cFv":13,
	"Delete__10daObjFan_cFv":14,
	"daObjFan_create1st__FP10daObjFan_c":15,
	"__dt__8dCcD_SphFv":16,
	"__ct__8dCcD_SphFv":17,
	"__dt__8cM3dGSphFv":18,
	"__dt__8cM3dGAabFv":19,
	"daObjFan_MoveBGDelete__FP10daObjFan_c":20,
	"daObjFan_MoveBGExecute__FP10daObjFan_c":21,
	"daObjFan_MoveBGDraw__FP10daObjFan_c":22,
	"_ctors":23,
	"_dtors":24,
	"l_bmd":25,
	"l_dzb2":26,
	"l_dzb3":27,
	"l_se":28,
	"l_wind_se":29,
	"l_max_rotspeed":30,
	"l_heap_size":31,
	"l_sph_src":32,
	"lit_3682":33,
	"lit_3683":34,
	"lit_3684":35,
	"lit_3685":36,
	"lit_3686":37,
	"lit_3813":38,
	"lit_3815":39,
	"lit_3929":40,
	"lit_3930":41,
	"lit_3931":42,
	"lit_3932":43,
	"lit_3964":44,
	"lit_3965":45,
	"d_a_obj_fan__stringBase0":46,
	"l_arcName":47,
	"l_offset_posM":48,
	"l_offset_posL":49,
	"daObjFan_METHODS":50,
	"g_profile_Obj_Fan":51,
	"__vt__8cM3dGAab":52,
	"__vt__8cM3dGSph":53,
	"__vt__10daObjFan_c":54,
}

