#
# Generate By: dol2asm
# Module: 681
#

# Libraries
LIBRARIES = [
	"d/a/obj/d_a_obj_waterfall",
]

# Translation Units
TRANSLATION_UNITS = [
	"executor",
	"unknown_translation_unit_ctors",
	"unknown_translation_unit_dtors",
	"d_a_obj_waterfall",
]

# Sections
SECTIONS = [
	".text",
	".ctors",
	".dtors",
	".rodata",
	".data",
	".bss",
]

# Symbols
SYMBOLS = [
	{'addr':0x80D2EBA0,'size':44,'pad':0,'label':"_prolog",'name':"_prolog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2EBCC,'size':44,'pad':0,'label':"_epilog",'name':"_epilog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2EBF8,'size':32,'pad':0,'label':"_unresolved",'name':"_unresolved",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2EC18,'size':140,'pad':0,'label':"s_b_sub__FPvPv",'name':"s_b_sub__FPvPv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2ECA4,'size':112,'pad':0,'label':"s_a_sub__FPvPv",'name':"s_a_sub__FPvPv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2ED14,'size':740,'pad':0,'label':"search_bomb__16daObjWaterFall_cFv",'name':"search_bomb__16daObjWaterFall_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2EFF8,'size':60,'pad':0,'label':"__dt__4cXyzFv",'name':"__dt__4cXyzFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2F034,'size':752,'pad':0,'label':"search_arrow__16daObjWaterFall_cFv",'name':"search_arrow__16daObjWaterFall_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2F324,'size':32,'pad':0,'label':"initBaseMtx__16daObjWaterFall_cFv",'name':"initBaseMtx__16daObjWaterFall_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2F344,'size':88,'pad':0,'label':"setBaseMtx__16daObjWaterFall_cFv",'name':"setBaseMtx__16daObjWaterFall_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2F39C,'size':516,'pad':0,'label':"Create__16daObjWaterFall_cFv",'name':"Create__16daObjWaterFall_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2F5A0,'size':316,'pad':0,'label':"create__16daObjWaterFall_cFv",'name':"create__16daObjWaterFall_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2F6DC,'size':4,'pad':0,'label':"__ct__4cXyzFv",'name':"__ct__4cXyzFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReturnFunction"},
	{'addr':0x80D2F6E0,'size':72,'pad':0,'label':"__dt__8cM3dGCylFv",'name':"__dt__8cM3dGCylFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2F728,'size':72,'pad':0,'label':"__dt__8cM3dGAabFv",'name':"__dt__8cM3dGAabFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2F770,'size':224,'pad':0,'label':"__dt__8dCcD_TriFv",'name':"__dt__8dCcD_TriFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2F850,'size':144,'pad':0,'label':"__ct__8dCcD_TriFv",'name':"__ct__8dCcD_TriFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2F8E0,'size':92,'pad':0,'label':"__dt__8cM3dGTriFv",'name':"__dt__8cM3dGTriFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2F93C,'size':72,'pad':0,'label':"__dt__8cM3dGPlaFv",'name':"__dt__8cM3dGPlaFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2F984,'size':232,'pad':0,'label':"execute__16daObjWaterFall_cFv",'name':"execute__16daObjWaterFall_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2FA6C,'size':552,'pad':0,'label':"push_player__16daObjWaterFall_cFv",'name':"push_player__16daObjWaterFall_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2FC94,'size':8,'pad':0,'label':"draw__16daObjWaterFall_cFv",'name':"draw__16daObjWaterFall_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReturnFunction"},
	{'addr':0x80D2FC9C,'size':52,'pad':0,'label':"_delete__16daObjWaterFall_cFv",'name':"_delete__16daObjWaterFall_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2FCD0,'size':32,'pad':0,'label':"daObjWaterFall_Draw__FP16daObjWaterFall_c",'name':"daObjWaterFall_Draw__FP16daObjWaterFall_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2FCF0,'size':32,'pad':0,'label':"daObjWaterFall_Execute__FP16daObjWaterFall_c",'name':"daObjWaterFall_Execute__FP16daObjWaterFall_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2FD10,'size':32,'pad':0,'label':"daObjWaterFall_Delete__FP16daObjWaterFall_c",'name':"daObjWaterFall_Delete__FP16daObjWaterFall_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2FD30,'size':32,'pad':0,'label':"daObjWaterFall_Create__FP10fopAc_ac_c",'name':"daObjWaterFall_Create__FP10fopAc_ac_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80D2FD50,'size':4,'pad':0,'label':"_ctors",'name':"_ctors",'lib':-1,'tu':1,'section':1,'class_template':False,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80D2FD54,'size':4,'pad':0,'label':"_dtors",'name':"_dtors",'lib':-1,'tu':2,'section':2,'class_template':False,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80D2FD58,'size':4,'pad':0,'label':"lit_3807",'name':"@3807",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[4,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80D2FD5C,'size':4,'pad':0,'label':"lit_3808",'name':"@3808",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80D2FD60,'size':4,'pad':0,'label':"lit_3809",'name':"@3809",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80D2FD64,'size':4,'pad':0,'label':"lit_3953",'name':"@3953",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80D2FD68,'size':4,'pad':0,'label':"lit_3954",'name':"@3954",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80D2FD6C,'size':4,'pad':0,'label':"lit_4203",'name':"@4203",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80D2FD70,'size':4,'pad':0,'label':"lit_4204",'name':"@4204",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80D2FD74,'size':4,'pad':0,'label':"lit_4205",'name':"@4205",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80D2FD78,'size':4,'pad':0,'label':"lit_4206",'name':"@4206",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80D2FD7C,'size':7,'pad':0,'label':"d_a_obj_waterfall__stringBase0",'name':"@stringBase0",'lib':-1,'tu':3,'section':3,'class_template':False,'static':False,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"StringBase"},
	{'addr':0x80D2FD84,'size':4,'pad':0,'label':"l_arcName",'name':"l_arcName",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80D2FD88,'size':68,'pad':0,'label':"l_cyl_src",'name':"l_cyl_src",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80D2FDCC,'size':32,'pad':0,'label':"l_daObjWaterFall_Method",'name':"l_daObjWaterFall_Method",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80D2FDEC,'size':48,'pad':0,'label':"g_profile_Obj_WaterFall",'name':"g_profile_Obj_WaterFall",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[0,0,1],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80D2FE1C,'size':12,'pad':0,'label':"__vt__8cM3dGPla",'name':"__vt__8cM3dGPla",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[4,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80D2FE28,'size':12,'pad':0,'label':"__vt__8cM3dGTri",'name':"__vt__8cM3dGTri",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80D2FE34,'size':12,'pad':0,'label':"__vt__8cM3dGCyl",'name':"__vt__8cM3dGCyl",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80D2FE40,'size':12,'pad':0,'label':"__vt__8cM3dGAab",'name':"__vt__8cM3dGAab",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[4,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80D2FE50,'size':40,'pad':0,'label':"target_info",'name':"target_info",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[4,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80D2FE78,'size':4,'pad':0,'label':"target_info_count",'name':"target_info_count",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[4,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
]

# Names
SYMBOL_NAMES = {
	"_prolog":0,
	"_epilog":1,
	"_unresolved":2,
	"s_b_sub__FPvPv":3,
	"s_a_sub__FPvPv":4,
	"search_bomb__16daObjWaterFall_cFv":5,
	"__dt__4cXyzFv":6,
	"search_arrow__16daObjWaterFall_cFv":7,
	"initBaseMtx__16daObjWaterFall_cFv":8,
	"setBaseMtx__16daObjWaterFall_cFv":9,
	"Create__16daObjWaterFall_cFv":10,
	"create__16daObjWaterFall_cFv":11,
	"__ct__4cXyzFv":12,
	"__dt__8cM3dGCylFv":13,
	"__dt__8cM3dGAabFv":14,
	"__dt__8dCcD_TriFv":15,
	"__ct__8dCcD_TriFv":16,
	"__dt__8cM3dGTriFv":17,
	"__dt__8cM3dGPlaFv":18,
	"execute__16daObjWaterFall_cFv":19,
	"push_player__16daObjWaterFall_cFv":20,
	"draw__16daObjWaterFall_cFv":21,
	"_delete__16daObjWaterFall_cFv":22,
	"daObjWaterFall_Draw__FP16daObjWaterFall_c":23,
	"daObjWaterFall_Execute__FP16daObjWaterFall_c":24,
	"daObjWaterFall_Delete__FP16daObjWaterFall_c":25,
	"daObjWaterFall_Create__FP10fopAc_ac_c":26,
	"_ctors":27,
	"_dtors":28,
	"lit_3807":29,
	"lit_3808":30,
	"lit_3809":31,
	"lit_3953":32,
	"lit_3954":33,
	"lit_4203":34,
	"lit_4204":35,
	"lit_4205":36,
	"lit_4206":37,
	"d_a_obj_waterfall__stringBase0":38,
	"l_arcName":39,
	"l_cyl_src":40,
	"l_daObjWaterFall_Method":41,
	"g_profile_Obj_WaterFall":42,
	"__vt__8cM3dGPla":43,
	"__vt__8cM3dGTri":44,
	"__vt__8cM3dGCyl":45,
	"__vt__8cM3dGAab":46,
	"target_info":47,
	"target_info_count":48,
}

