#
# Generate By: dol2asm
# Module: 437
#

# Libraries
LIBRARIES = [
	"d/a/obj/d_a_obj_digsnow",
]

# Translation Units
TRANSLATION_UNITS = [
	"executor",
	"unknown_translation_unit_ctors",
	"unknown_translation_unit_dtors",
	"unknown_translation_unit_bss",
	"d_a_obj_digsnow",
]

# Sections
SECTIONS = [
	".text",
	".ctors",
	".dtors",
	".bss",
	".rodata",
	".data",
]

# Symbols
SYMBOLS = [
	{'addr':0x80BDCBE0,'size':44,'pad':0,'label':"_prolog",'name':"_prolog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDCC0C,'size':44,'pad':0,'label':"_epilog",'name':"_epilog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDCC38,'size':32,'pad':0,'label':"_unresolved",'name':"_unresolved",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDCC58,'size':60,'pad':0,'label':"initBaseMtx__14daObjDigSnow_cFv",'name':"initBaseMtx__14daObjDigSnow_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDCC94,'size':116,'pad':0,'label':"setBaseMtx__14daObjDigSnow_cFv",'name':"setBaseMtx__14daObjDigSnow_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDCD08,'size':92,'pad':0,'label':"Create__14daObjDigSnow_cFv",'name':"Create__14daObjDigSnow_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDCD64,'size':112,'pad':0,'label':"CreateHeap__14daObjDigSnow_cFv",'name':"CreateHeap__14daObjDigSnow_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDCDD4,'size':176,'pad':0,'label':"create1st__14daObjDigSnow_cFv",'name':"create1st__14daObjDigSnow_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDCE84,'size':124,'pad':0,'label':"Execute__14daObjDigSnow_cFPPA3_A4_f",'name':"Execute__14daObjDigSnow_cFPPA3_A4_f",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDCF00,'size':164,'pad':0,'label':"action__14daObjDigSnow_cFv",'name':"action__14daObjDigSnow_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDCFA4,'size':12,'pad':0,'label':"mode_init_wait__14daObjDigSnow_cFv",'name':"mode_init_wait__14daObjDigSnow_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDCFB0,'size':44,'pad':0,'label':"mode_wait__14daObjDigSnow_cFv",'name':"mode_wait__14daObjDigSnow_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDCFDC,'size':208,'pad':0,'label':"mode_init_dig__14daObjDigSnow_cFv",'name':"mode_init_dig__14daObjDigSnow_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD0AC,'size':120,'pad':0,'label':"__dt__14dBgS_ObjGndChkFv",'name':"__dt__14dBgS_ObjGndChkFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[4,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD124,'size':152,'pad':0,'label':"mode_dig__14daObjDigSnow_cFv",'name':"mode_dig__14daObjDigSnow_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD1BC,'size':84,'pad':0,'label':"mode_init_end__14daObjDigSnow_cFv",'name':"mode_init_end__14daObjDigSnow_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD210,'size':4,'pad':0,'label':"mode_end__14daObjDigSnow_cFv",'name':"mode_end__14daObjDigSnow_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReturnFunction"},
	{'addr':0x80BDD214,'size':164,'pad':0,'label':"Draw__14daObjDigSnow_cFv",'name':"Draw__14daObjDigSnow_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD2B8,'size':52,'pad':0,'label':"Delete__14daObjDigSnow_cFv",'name':"Delete__14daObjDigSnow_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD2EC,'size':300,'pad':0,'label':"daObjDigSnow_create1st__FP14daObjDigSnow_c",'name':"daObjDigSnow_create1st__FP14daObjDigSnow_c",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD418,'size':72,'pad':0,'label':"__dt__8cM3dGCylFv",'name':"__dt__8cM3dGCylFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD460,'size':72,'pad':0,'label':"__dt__8cM3dGAabFv",'name':"__dt__8cM3dGAabFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD4A8,'size':92,'pad':0,'label':"__dt__10dCcD_GSttsFv",'name':"__dt__10dCcD_GSttsFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD504,'size':112,'pad':0,'label':"__dt__12dBgS_AcchCirFv",'name':"__dt__12dBgS_AcchCirFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD574,'size':112,'pad':0,'label':"__dt__12dBgS_ObjAcchFv",'name':"__dt__12dBgS_ObjAcchFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD5E4,'size':32,'pad':0,'label':"daObjDigSnow_MoveBGDelete__FP14daObjDigSnow_c",'name':"daObjDigSnow_MoveBGDelete__FP14daObjDigSnow_c",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD604,'size':32,'pad':0,'label':"daObjDigSnow_MoveBGExecute__FP14daObjDigSnow_c",'name':"daObjDigSnow_MoveBGExecute__FP14daObjDigSnow_c",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD624,'size':44,'pad':0,'label':"daObjDigSnow_MoveBGDraw__FP14daObjDigSnow_c",'name':"daObjDigSnow_MoveBGDraw__FP14daObjDigSnow_c",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD650,'size':72,'pad':0,'label':"__dt__10cCcD_GSttsFv",'name':"__dt__10cCcD_GSttsFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD698,'size':8,'pad':0,'label':"func_80BDD698",'name':"@20@__dt__14dBgS_ObjGndChkFv",'lib':-1,'tu':4,'section':0,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD6A0,'size':8,'pad':0,'label':"func_80BDD6A0",'name':"@76@__dt__14dBgS_ObjGndChkFv",'lib':-1,'tu':4,'section':0,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD6A8,'size':8,'pad':0,'label':"func_80BDD6A8",'name':"@60@__dt__14dBgS_ObjGndChkFv",'lib':-1,'tu':4,'section':0,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD6B0,'size':8,'pad':0,'label':"func_80BDD6B0",'name':"@36@__dt__12dBgS_ObjAcchFv",'lib':-1,'tu':4,'section':0,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD6B8,'size':8,'pad':0,'label':"func_80BDD6B8",'name':"@20@__dt__12dBgS_ObjAcchFv",'lib':-1,'tu':4,'section':0,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80BDD6C0,'size':4,'pad':0,'label':"_ctors",'name':"_ctors",'lib':-1,'tu':1,'section':1,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80BDD6C4,'size':4,'pad':0,'label':"_dtors",'name':"_dtors",'lib':-1,'tu':2,'section':2,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80BDD6C8,'size':4,'pad':0,'label':"lit_3744",'name':"@3744",'lib':-1,'tu':4,'section':4,'class_template':None,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80BDD6CC,'size':4,'pad':0,'label':"lit_3761",'name':"@3761",'lib':-1,'tu':4,'section':4,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80BDD6D0,'size':4,'pad':0,'label':"lit_3762",'name':"@3762",'lib':-1,'tu':4,'section':4,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80BDD6D4,'size':4,'pad':0,'label':"lit_3763",'name':"@3763",'lib':-1,'tu':4,'section':4,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80BDD6D8,'size':4,'pad':0,'label':"lit_3764",'name':"@3764",'lib':-1,'tu':4,'section':4,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80BDD6DC,'size':10,'pad':0,'label':"d_a_obj_digsnow__stringBase0",'name':"@stringBase0",'lib':-1,'tu':4,'section':4,'class_template':None,'static':False,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"StringBase"},
	{'addr':0x80BDD6E8,'size':12,'pad':0,'label':"cNullVec__6Z2Calc",'name':"cNullVec__6Z2Calc",'lib':-1,'tu':4,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80BDD6F4,'size':4,'pad':16,'label':"lit_1787",'name':"@1787",'lib':-1,'tu':4,'section':5,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80BDD708,'size':4,'pad':0,'label':"l_arcName",'name':"l_arcName",'lib':-1,'tu':4,'section':5,'class_template':None,'static':True,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80BDD70C,'size':12,'pad':0,'label':"lit_3713",'name':"@3713",'lib':-1,'tu':4,'section':5,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80BDD718,'size':12,'pad':0,'label':"lit_3714",'name':"@3714",'lib':-1,'tu':4,'section':5,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80BDD724,'size':12,'pad':0,'label':"lit_3715",'name':"@3715",'lib':-1,'tu':4,'section':5,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80BDD730,'size':36,'pad':0,'label':"l_func",'name':"l_func$3712",'lib':-1,'tu':4,'section':5,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80BDD754,'size':32,'pad':0,'label':"daObjDigSnow_METHODS",'name':"daObjDigSnow_METHODS",'lib':-1,'tu':4,'section':5,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80BDD774,'size':48,'pad':0,'label':"g_profile_Obj_DigSnow",'name':"g_profile_Obj_DigSnow",'lib':-1,'tu':4,'section':5,'class_template':None,'static':False,'is_reachable':False,'r':[0,0,1],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80BDD7A4,'size':12,'pad':0,'label':"__vt__12dBgS_AcchCir",'name':"__vt__12dBgS_AcchCir",'lib':-1,'tu':4,'section':5,'class_template':None,'static':False,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80BDD7B0,'size':12,'pad':0,'label':"__vt__10cCcD_GStts",'name':"__vt__10cCcD_GStts",'lib':-1,'tu':4,'section':5,'class_template':None,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80BDD7BC,'size':12,'pad':0,'label':"__vt__10dCcD_GStts",'name':"__vt__10dCcD_GStts",'lib':-1,'tu':4,'section':5,'class_template':None,'static':False,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80BDD7C8,'size':12,'pad':0,'label':"__vt__8cM3dGCyl",'name':"__vt__8cM3dGCyl",'lib':-1,'tu':4,'section':5,'class_template':None,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80BDD7D4,'size':12,'pad':0,'label':"__vt__8cM3dGAab",'name':"__vt__8cM3dGAab",'lib':-1,'tu':4,'section':5,'class_template':None,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80BDD7E0,'size':36,'pad':0,'label':"__vt__12dBgS_ObjAcch",'name':"__vt__12dBgS_ObjAcch",'lib':-1,'tu':4,'section':5,'class_template':None,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80BDD804,'size':48,'pad':0,'label':"__vt__14dBgS_ObjGndChk",'name':"__vt__14dBgS_ObjGndChk",'lib':-1,'tu':4,'section':5,'class_template':None,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80BDD834,'size':40,'pad':0,'label':"__vt__14daObjDigSnow_c",'name':"__vt__14daObjDigSnow_c",'lib':-1,'tu':4,'section':5,'class_template':None,'static':False,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80BDD860,'size':4,'pad':0,'label':"data_80BDD860",'name':None,'lib':-1,'tu':3,'section':3,'class_template':None,'static':False,'is_reachable':False,'r':[0,1,0],'sh':[0,0,0],'type':"ArbitraryData"},
]

# Names
SYMBOL_NAMES = {
	"_prolog":0,
	"_epilog":1,
	"_unresolved":2,
	"initBaseMtx__14daObjDigSnow_cFv":3,
	"setBaseMtx__14daObjDigSnow_cFv":4,
	"Create__14daObjDigSnow_cFv":5,
	"CreateHeap__14daObjDigSnow_cFv":6,
	"create1st__14daObjDigSnow_cFv":7,
	"Execute__14daObjDigSnow_cFPPA3_A4_f":8,
	"action__14daObjDigSnow_cFv":9,
	"mode_init_wait__14daObjDigSnow_cFv":10,
	"mode_wait__14daObjDigSnow_cFv":11,
	"mode_init_dig__14daObjDigSnow_cFv":12,
	"__dt__14dBgS_ObjGndChkFv":13,
	"mode_dig__14daObjDigSnow_cFv":14,
	"mode_init_end__14daObjDigSnow_cFv":15,
	"mode_end__14daObjDigSnow_cFv":16,
	"Draw__14daObjDigSnow_cFv":17,
	"Delete__14daObjDigSnow_cFv":18,
	"daObjDigSnow_create1st__FP14daObjDigSnow_c":19,
	"__dt__8cM3dGCylFv":20,
	"__dt__8cM3dGAabFv":21,
	"__dt__10dCcD_GSttsFv":22,
	"__dt__12dBgS_AcchCirFv":23,
	"__dt__12dBgS_ObjAcchFv":24,
	"daObjDigSnow_MoveBGDelete__FP14daObjDigSnow_c":25,
	"daObjDigSnow_MoveBGExecute__FP14daObjDigSnow_c":26,
	"daObjDigSnow_MoveBGDraw__FP14daObjDigSnow_c":27,
	"__dt__10cCcD_GSttsFv":28,
	"func_80BDD698":29,
	"func_80BDD6A0":30,
	"func_80BDD6A8":31,
	"func_80BDD6B0":32,
	"func_80BDD6B8":33,
	"_ctors":34,
	"_dtors":35,
	"lit_3744":36,
	"lit_3761":37,
	"lit_3762":38,
	"lit_3763":39,
	"lit_3764":40,
	"d_a_obj_digsnow__stringBase0":41,
	"cNullVec__6Z2Calc":42,
	"lit_1787":43,
	"l_arcName":44,
	"lit_3713":45,
	"lit_3714":46,
	"lit_3715":47,
	"l_func":48,
	"daObjDigSnow_METHODS":49,
	"g_profile_Obj_DigSnow":50,
	"__vt__12dBgS_AcchCir":51,
	"__vt__10cCcD_GStts":52,
	"__vt__10dCcD_GStts":53,
	"__vt__8cM3dGCyl":54,
	"__vt__8cM3dGAab":55,
	"__vt__12dBgS_ObjAcch":56,
	"__vt__14dBgS_ObjGndChk":57,
	"__vt__14daObjDigSnow_c":58,
	"data_80BDD860":59,
}

