#
# Generate By: dol2asm
# Module: 631
#

# Libraries
LIBRARIES = [
	"d/a/obj/d_a_obj_ss_item",
]

# Translation Units
TRANSLATION_UNITS = [
	"executor",
	"unknown_translation_unit_ctors",
	"unknown_translation_unit_dtors",
	"d_a_obj_ss_item",
]

# Sections
SECTIONS = [
	".text",
	".ctors",
	".dtors",
	".rodata",
	".data",
]

# Symbols
SYMBOLS = [
	{'addr':0x80CE6BA0,'size':44,'pad':0,'label':"_prolog",'name':"_prolog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE6BCC,'size':44,'pad':0,'label':"_epilog",'name':"_epilog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE6BF8,'size':32,'pad':0,'label':"_unresolved",'name':"_unresolved",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE6C18,'size':592,'pad':0,'label':"__dt__14daObj_SSItem_cFv",'name':"__dt__14daObj_SSItem_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE6E68,'size':612,'pad':0,'label':"create__14daObj_SSItem_cFv",'name':"create__14daObj_SSItem_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE70CC,'size':72,'pad':0,'label':"__dt__8cM3dGCylFv",'name':"__dt__8cM3dGCylFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7114,'size':72,'pad':0,'label':"__dt__8cM3dGAabFv",'name':"__dt__8cM3dGAabFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE715C,'size':112,'pad':0,'label':"__dt__12dBgS_AcchCirFv",'name':"__dt__12dBgS_AcchCirFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE71CC,'size':92,'pad':0,'label':"__dt__10dCcD_GSttsFv",'name':"__dt__10dCcD_GSttsFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7228,'size':112,'pad':0,'label':"__dt__12dBgS_ObjAcchFv",'name':"__dt__12dBgS_ObjAcchFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7298,'size':192,'pad':0,'label':"CreateHeap__14daObj_SSItem_cFv",'name':"CreateHeap__14daObj_SSItem_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7358,'size':52,'pad':0,'label':"Delete__14daObj_SSItem_cFv",'name':"Delete__14daObj_SSItem_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE738C,'size':644,'pad':0,'label':"Execute__14daObj_SSItem_cFv",'name':"Execute__14daObj_SSItem_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7610,'size':256,'pad':0,'label':"Draw__14daObj_SSItem_cFv",'name':"Draw__14daObj_SSItem_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7710,'size':72,'pad':0,'label':"__dt__8cM3dGPlaFv",'name':"__dt__8cM3dGPlaFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7758,'size':32,'pad':0,'label':"createHeapCallBack__14daObj_SSItem_cFP10fopAc_ac_c",'name':"createHeapCallBack__14daObj_SSItem_cFP10fopAc_ac_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7778,'size':84,'pad':0,'label':"setSoldOut__14daObj_SSItem_cFv",'name':"setSoldOut__14daObj_SSItem_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE77CC,'size':44,'pad':0,'label':"getProcessID__14daObj_SSItem_cFv",'name':"getProcessID__14daObj_SSItem_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE77F8,'size':64,'pad':0,'label':"getExchangeItemPtr__14daObj_SSItem_cFv",'name':"getExchangeItemPtr__14daObj_SSItem_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':False,'is_reachable':False,'r':[0,0,1],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7838,'size':24,'pad':0,'label':"getResName__14daObj_SSItem_cFv",'name':"getResName__14daObj_SSItem_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[4,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7850,'size':76,'pad':0,'label':"getTypeFromParam__14daObj_SSItem_cFv",'name':"getTypeFromParam__14daObj_SSItem_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE789C,'size':56,'pad':0,'label':"getFlowNodeNum__14daObj_SSItem_cFv",'name':"getFlowNodeNum__14daObj_SSItem_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE78D4,'size':12,'pad':0,'label':"getValue__14daObj_SSItem_cFv",'name':"getValue__14daObj_SSItem_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE78E0,'size':112,'pad':0,'label':"restart__14daObj_SSItem_cFv",'name':"restart__14daObj_SSItem_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7950,'size':436,'pad':0,'label':"initialize__14daObj_SSItem_cFv",'name':"initialize__14daObj_SSItem_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7B04,'size':176,'pad':0,'label':"setProcess__14daObj_SSItem_cFM14daObj_SSItem_cFPCvPvPv_i",'name':"setProcess__14daObj_SSItem_cFM14daObj_SSItem_cFPCvPvPv_i",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7BB4,'size':112,'pad':0,'label':"setParam__14daObj_SSItem_cFv",'name':"setParam__14daObj_SSItem_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7C24,'size':92,'pad':0,'label':"setEnvTevColor__14daObj_SSItem_cFv",'name':"setEnvTevColor__14daObj_SSItem_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7C80,'size':68,'pad':0,'label':"setRoomNo__14daObj_SSItem_cFv",'name':"setRoomNo__14daObj_SSItem_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7CC4,'size':100,'pad':0,'label':"setMtx__14daObj_SSItem_cFv",'name':"setMtx__14daObj_SSItem_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7D28,'size':52,'pad':0,'label':"setAttnPos__14daObj_SSItem_cFv",'name':"setAttnPos__14daObj_SSItem_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7D5C,'size':48,'pad':0,'label':"wait__14daObj_SSItem_cFPv",'name':"wait__14daObj_SSItem_cFPv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7D8C,'size':32,'pad':0,'label':"daObj_SSItem_Create__FPv",'name':"daObj_SSItem_Create__FPv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7DAC,'size':32,'pad':0,'label':"daObj_SSItem_Delete__FPv",'name':"daObj_SSItem_Delete__FPv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7DCC,'size':32,'pad':0,'label':"daObj_SSItem_Execute__FPv",'name':"daObj_SSItem_Execute__FPv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7DEC,'size':32,'pad':0,'label':"daObj_SSItem_Draw__FPv",'name':"daObj_SSItem_Draw__FPv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7E0C,'size':8,'pad':0,'label':"daObj_SSItem_IsDelete__FPv",'name':"daObj_SSItem_IsDelete__FPv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReturnFunction"},
	{'addr':0x80CE7E14,'size':72,'pad':0,'label':"__dt__10cCcD_GSttsFv",'name':"__dt__10cCcD_GSttsFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7E5C,'size':56,'pad':0,'label':"__sinit_d_a_obj_ss_item_cpp",'name':"__sinit_d_a_obj_ss_item_cpp",'lib':-1,'tu':3,'section':0,'class_template':None,'static':False,'is_reachable':False,'r':[0,1,0],'sh':[0,0,0],'type':"SInitFunction"},
	{'addr':0x80CE7E94,'size':8,'pad':0,'label':"func_80CE7E94",'name':"@36@__dt__12dBgS_ObjAcchFv",'lib':-1,'tu':3,'section':0,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7E9C,'size':8,'pad':0,'label':"func_80CE7E9C",'name':"@20@__dt__12dBgS_ObjAcchFv",'lib':-1,'tu':3,'section':0,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CE7EA4,'size':8,'pad':0,'label':"_ctors",'name':"_ctors",'lib':-1,'tu':1,'section':1,'class_template':False,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80CE7EAC,'size':4,'pad':0,'label':"_dtors",'name':"_dtors",'lib':-1,'tu':2,'section':2,'class_template':False,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80CE7EB0,'size':48,'pad':0,'label':"mCcDObjInfo__14daObj_SSItem_c",'name':"mCcDObjInfo__14daObj_SSItem_c",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':True,'r':[5,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CE7EE0,'size':4,'pad':0,'label':"lit_4205",'name':"@4205",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CE7EE4,'size':4,'pad':0,'label':"lit_4206",'name':"@4206",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CE7EE8,'size':4,'pad':0,'label':"lit_4207",'name':"@4207",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CE7EEC,'size':4,'pad':0,'label':"lit_4208",'name':"@4208",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CE7EF0,'size':4,'pad':0,'label':"lit_4234",'name':"@4234",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CE7EF4,'size':4,'pad':0,'label':"lit_4235",'name':"@4235",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CE7EF8,'size':4,'pad':0,'label':"lit_4347",'name':"@4347",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CE7EFC,'size':4,'pad':0,'label':"lit_4348",'name':"@4348",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CE7F00,'size':4,'pad':0,'label':"lit_4349",'name':"@4349",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CE7F04,'size':4,'pad':0,'label':"lit_4350",'name':"@4350",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CE7F08,'size':4,'pad':0,'label':"lit_4351",'name':"@4351",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CE7F0C,'size':4,'pad':0,'label':"lit_4352",'name':"@4352",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CE7F10,'size':4,'pad':0,'label':"lit_4377",'name':"@4377",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CE7F14,'size':4,'pad':0,'label':"lit_4378",'name':"@4378",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CE7F18,'size':28,'pad':0,'label':"d_a_obj_ss_item__stringBase0",'name':"@stringBase0",'lib':-1,'tu':3,'section':3,'class_template':False,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"StringBase"},
	{'addr':0x80CE7F34,'size':12,'pad':0,'label':"l_resFileName",'name':"l_resFileName",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CE7F40,'size':12,'pad':0,'label':"l_bmdIdxName",'name':"l_bmdIdxName",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CE7F4C,'size':12,'pad':0,'label':"l_bmdFileName",'name':"l_bmdFileName",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CE7F58,'size':68,'pad':0,'label':"mCcDCyl__14daObj_SSItem_c",'name':"mCcDCyl__14daObj_SSItem_c",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':True,'r':[2,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CE7F9C,'size':12,'pad':0,'label':"lit_4309",'name':"@4309",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CE7FA8,'size':32,'pad':0,'label':"daObj_SSItem_MethodTable",'name':"daObj_SSItem_MethodTable",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CE7FC8,'size':48,'pad':0,'label':"g_profile_OBJ_SSITEM",'name':"g_profile_OBJ_SSITEM",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[0,0,1],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CE7FF8,'size':12,'pad':0,'label':"__vt__8cM3dGPla",'name':"__vt__8cM3dGPla",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CE8004,'size':36,'pad':0,'label':"__vt__12dBgS_ObjAcch",'name':"__vt__12dBgS_ObjAcch",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CE8028,'size':12,'pad':0,'label':"__vt__10cCcD_GStts",'name':"__vt__10cCcD_GStts",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CE8034,'size':12,'pad':0,'label':"__vt__10dCcD_GStts",'name':"__vt__10dCcD_GStts",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CE8040,'size':12,'pad':0,'label':"__vt__12dBgS_AcchCir",'name':"__vt__12dBgS_AcchCir",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CE804C,'size':12,'pad':0,'label':"__vt__8cM3dGAab",'name':"__vt__8cM3dGAab",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CE8058,'size':12,'pad':0,'label':"__vt__8cM3dGCyl",'name':"__vt__8cM3dGCyl",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CE8064,'size':20,'pad':0,'label':"__vt__14daObj_SSItem_c",'name':"__vt__14daObj_SSItem_c",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
]

# Names
SYMBOL_NAMES = {
	"_prolog":0,
	"_epilog":1,
	"_unresolved":2,
	"__dt__14daObj_SSItem_cFv":3,
	"create__14daObj_SSItem_cFv":4,
	"__dt__8cM3dGCylFv":5,
	"__dt__8cM3dGAabFv":6,
	"__dt__12dBgS_AcchCirFv":7,
	"__dt__10dCcD_GSttsFv":8,
	"__dt__12dBgS_ObjAcchFv":9,
	"CreateHeap__14daObj_SSItem_cFv":10,
	"Delete__14daObj_SSItem_cFv":11,
	"Execute__14daObj_SSItem_cFv":12,
	"Draw__14daObj_SSItem_cFv":13,
	"__dt__8cM3dGPlaFv":14,
	"createHeapCallBack__14daObj_SSItem_cFP10fopAc_ac_c":15,
	"setSoldOut__14daObj_SSItem_cFv":16,
	"getProcessID__14daObj_SSItem_cFv":17,
	"getExchangeItemPtr__14daObj_SSItem_cFv":18,
	"getResName__14daObj_SSItem_cFv":19,
	"getTypeFromParam__14daObj_SSItem_cFv":20,
	"getFlowNodeNum__14daObj_SSItem_cFv":21,
	"getValue__14daObj_SSItem_cFv":22,
	"restart__14daObj_SSItem_cFv":23,
	"initialize__14daObj_SSItem_cFv":24,
	"setProcess__14daObj_SSItem_cFM14daObj_SSItem_cFPCvPvPv_i":25,
	"setParam__14daObj_SSItem_cFv":26,
	"setEnvTevColor__14daObj_SSItem_cFv":27,
	"setRoomNo__14daObj_SSItem_cFv":28,
	"setMtx__14daObj_SSItem_cFv":29,
	"setAttnPos__14daObj_SSItem_cFv":30,
	"wait__14daObj_SSItem_cFPv":31,
	"daObj_SSItem_Create__FPv":32,
	"daObj_SSItem_Delete__FPv":33,
	"daObj_SSItem_Execute__FPv":34,
	"daObj_SSItem_Draw__FPv":35,
	"daObj_SSItem_IsDelete__FPv":36,
	"__dt__10cCcD_GSttsFv":37,
	"__sinit_d_a_obj_ss_item_cpp":38,
	"func_80CE7E94":39,
	"func_80CE7E9C":40,
	"_ctors":41,
	"_dtors":42,
	"mCcDObjInfo__14daObj_SSItem_c":43,
	"lit_4205":44,
	"lit_4206":45,
	"lit_4207":46,
	"lit_4208":47,
	"lit_4234":48,
	"lit_4235":49,
	"lit_4347":50,
	"lit_4348":51,
	"lit_4349":52,
	"lit_4350":53,
	"lit_4351":54,
	"lit_4352":55,
	"lit_4377":56,
	"lit_4378":57,
	"d_a_obj_ss_item__stringBase0":58,
	"l_resFileName":59,
	"l_bmdIdxName":60,
	"l_bmdFileName":61,
	"mCcDCyl__14daObj_SSItem_c":62,
	"lit_4309":63,
	"daObj_SSItem_MethodTable":64,
	"g_profile_OBJ_SSITEM":65,
	"__vt__8cM3dGPla":66,
	"__vt__12dBgS_ObjAcch":67,
	"__vt__10cCcD_GStts":68,
	"__vt__10dCcD_GStts":69,
	"__vt__12dBgS_AcchCir":70,
	"__vt__8cM3dGAab":71,
	"__vt__8cM3dGCyl":72,
	"__vt__14daObj_SSItem_c":73,
}

