#
# Generate By: dol2asm
# Module: 585
#

# Libraries
LIBRARIES = [
	"d/a/obj/d_a_obj_oiltubo",
]

# Translation Units
TRANSLATION_UNITS = [
	"executor",
	"unknown_translation_unit_ctors",
	"unknown_translation_unit_dtors",
	"d_a_obj_oiltubo",
]

# Sections
SECTIONS = [
	".text",
	".ctors",
	".dtors",
	".rodata",
	".data",
]

# Symbols
SYMBOLS = [
	{'addr':0x80CA66A0,'size':44,'pad':0,'label':"_prolog",'name':"_prolog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA66CC,'size':44,'pad':0,'label':"_epilog",'name':"_epilog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA66F8,'size':32,'pad':0,'label':"_unresolved",'name':"_unresolved",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA6718,'size':508,'pad':0,'label':"create__15daObj_Oiltubo_cFv",'name':"create__15daObj_Oiltubo_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA6914,'size':72,'pad':0,'label':"__dt__8cM3dGCylFv",'name':"__dt__8cM3dGCylFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA695C,'size':72,'pad':0,'label':"__dt__8cM3dGAabFv",'name':"__dt__8cM3dGAabFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA69A4,'size':112,'pad':0,'label':"__dt__12dBgS_AcchCirFv",'name':"__dt__12dBgS_AcchCirFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA6A14,'size':92,'pad':0,'label':"__dt__10dCcD_GSttsFv",'name':"__dt__10dCcD_GSttsFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA6A70,'size':112,'pad':0,'label':"__dt__12dBgS_ObjAcchFv",'name':"__dt__12dBgS_ObjAcchFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA6AE0,'size':72,'pad':0,'label':"__dt__12J3DFrameCtrlFv",'name':"__dt__12J3DFrameCtrlFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA6B28,'size':308,'pad':0,'label':"CreateHeap__15daObj_Oiltubo_cFv",'name':"CreateHeap__15daObj_Oiltubo_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA6C5C,'size':68,'pad':0,'label':"Delete__15daObj_Oiltubo_cFv",'name':"Delete__15daObj_Oiltubo_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA6CA0,'size':572,'pad':0,'label':"Execute__15daObj_Oiltubo_cFv",'name':"Execute__15daObj_Oiltubo_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA6EDC,'size':236,'pad':0,'label':"Draw__15daObj_Oiltubo_cFv",'name':"Draw__15daObj_Oiltubo_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA6FC8,'size':32,'pad':0,'label':"createHeapCallBack__15daObj_Oiltubo_cFP10fopAc_ac_c",'name':"createHeapCallBack__15daObj_Oiltubo_cFP10fopAc_ac_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA6FE8,'size':16,'pad':0,'label':"getResName__15daObj_Oiltubo_cFv",'name':"getResName__15daObj_Oiltubo_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[4,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA6FF8,'size':112,'pad':0,'label':"restart__15daObj_Oiltubo_cFv",'name':"restart__15daObj_Oiltubo_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA7068,'size':420,'pad':0,'label':"initialize__15daObj_Oiltubo_cFv",'name':"initialize__15daObj_Oiltubo_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA720C,'size':176,'pad':0,'label':"setProcess__15daObj_Oiltubo_cFM15daObj_Oiltubo_cFPCvPvPv_i",'name':"setProcess__15daObj_Oiltubo_cFM15daObj_Oiltubo_cFPCvPvPv_i",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA72BC,'size':92,'pad':0,'label':"setParam__15daObj_Oiltubo_cFv",'name':"setParam__15daObj_Oiltubo_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA7318,'size':92,'pad':0,'label':"setEnvTevColor__15daObj_Oiltubo_cFv",'name':"setEnvTevColor__15daObj_Oiltubo_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA7374,'size':68,'pad':0,'label':"setRoomNo__15daObj_Oiltubo_cFv",'name':"setRoomNo__15daObj_Oiltubo_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA73B8,'size':120,'pad':0,'label':"setMtx__15daObj_Oiltubo_cFv",'name':"setMtx__15daObj_Oiltubo_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA7430,'size':72,'pad':0,'label':"setAttnPos__15daObj_Oiltubo_cFv",'name':"setAttnPos__15daObj_Oiltubo_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA7478,'size':80,'pad':0,'label':"chkEvent__15daObj_Oiltubo_cFv",'name':"chkEvent__15daObj_Oiltubo_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA74C8,'size':144,'pad':0,'label':"wait__15daObj_Oiltubo_cFPv",'name':"wait__15daObj_Oiltubo_cFPv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA7558,'size':32,'pad':0,'label':"daObj_Oiltubo_Create__FPv",'name':"daObj_Oiltubo_Create__FPv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA7578,'size':32,'pad':0,'label':"daObj_Oiltubo_Delete__FPv",'name':"daObj_Oiltubo_Delete__FPv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA7598,'size':32,'pad':0,'label':"daObj_Oiltubo_Execute__FPv",'name':"daObj_Oiltubo_Execute__FPv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA75B8,'size':32,'pad':0,'label':"daObj_Oiltubo_Draw__FPv",'name':"daObj_Oiltubo_Draw__FPv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA75D8,'size':8,'pad':0,'label':"daObj_Oiltubo_IsDelete__FPv",'name':"daObj_Oiltubo_IsDelete__FPv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReturnFunction"},
	{'addr':0x80CA75E0,'size':72,'pad':0,'label':"__dt__10cCcD_GSttsFv",'name':"__dt__10cCcD_GSttsFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA7628,'size':632,'pad':0,'label':"__dt__15daObj_Oiltubo_cFv",'name':"__dt__15daObj_Oiltubo_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA78A0,'size':56,'pad':0,'label':"__sinit_d_a_obj_oiltubo_cpp",'name':"__sinit_d_a_obj_oiltubo_cpp",'lib':-1,'tu':3,'section':0,'class_template':None,'static':False,'is_reachable':False,'r':[0,1,0],'sh':[0,0,0],'type':"SInitFunction"},
	{'addr':0x80CA78D8,'size':8,'pad':0,'label':"func_80CA78D8",'name':"@36@__dt__12dBgS_ObjAcchFv",'lib':-1,'tu':3,'section':0,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA78E0,'size':8,'pad':0,'label':"func_80CA78E0",'name':"@20@__dt__12dBgS_ObjAcchFv",'lib':-1,'tu':3,'section':0,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CA78E8,'size':8,'pad':0,'label':"_ctors",'name':"_ctors",'lib':-1,'tu':1,'section':1,'class_template':False,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80CA78F0,'size':4,'pad':0,'label':"_dtors",'name':"_dtors",'lib':-1,'tu':2,'section':2,'class_template':False,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80CA78F4,'size':48,'pad':0,'label':"mCcDObjInfo__15daObj_Oiltubo_c",'name':"mCcDObjInfo__15daObj_Oiltubo_c",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':True,'r':[5,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CA7924,'size':4,'pad':0,'label':"lit_3815",'name':"@3815",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80CA7928,'size':4,'pad':0,'label':"lit_3863",'name':"@3863",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80CA792C,'size':4,'pad':0,'label':"lit_3864",'name':"@3864",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80CA7930,'size':4,'pad':0,'label':"lit_3865",'name':"@3865",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80CA7934,'size':4,'pad':0,'label':"lit_3884",'name':"@3884",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80CA7938,'size':4,'pad':0,'label':"lit_3885",'name':"@3885",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80CA793C,'size':4,'pad':0,'label':"lit_3999",'name':"@3999",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80CA7940,'size':4,'pad':0,'label':"lit_4029",'name':"@4029",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80CA7944,'size':4,'pad':0,'label':"lit_4030",'name':"@4030",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80CA7948,'size':63,'pad':0,'label':"d_a_obj_oiltubo__stringBase0",'name':"@stringBase0",'lib':-1,'tu':3,'section':3,'class_template':False,'static':False,'is_reachable':False,'r':[4,0,0],'sh':[0,0,0],'type':"StringBase"},
	{'addr':0x80CA7988,'size':12,'pad':0,'label':"cNullVec__6Z2Calc",'name':"cNullVec__6Z2Calc",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CA7994,'size':4,'pad':16,'label':"lit_1787",'name':"@1787",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CA79A8,'size':4,'pad':0,'label':"l_resFileName",'name':"l_resFileName",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CA79AC,'size':4,'pad':0,'label':"l_bmdFileName",'name':"l_bmdFileName",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CA79B0,'size':4,'pad':0,'label':"l_bbmdFileName",'name':"l_bbmdFileName",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CA79B4,'size':4,'pad':0,'label':"l_bbtkFileName",'name':"l_bbtkFileName",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CA79B8,'size':68,'pad':0,'label':"mCcDCyl__15daObj_Oiltubo_c",'name':"mCcDCyl__15daObj_Oiltubo_c",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':True,'r':[2,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CA79FC,'size':12,'pad':0,'label':"lit_3897",'name':"@3897",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CA7A08,'size':32,'pad':0,'label':"daObj_Oiltubo_MethodTable",'name':"daObj_Oiltubo_MethodTable",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CA7A28,'size':48,'pad':0,'label':"g_profile_OBJ_OILTUBO",'name':"g_profile_OBJ_OILTUBO",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[0,0,1],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CA7A58,'size':12,'pad':0,'label':"__vt__10cCcD_GStts",'name':"__vt__10cCcD_GStts",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CA7A64,'size':12,'pad':0,'label':"__vt__10dCcD_GStts",'name':"__vt__10dCcD_GStts",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CA7A70,'size':12,'pad':0,'label':"__vt__12dBgS_AcchCir",'name':"__vt__12dBgS_AcchCir",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CA7A7C,'size':12,'pad':0,'label':"__vt__8cM3dGCyl",'name':"__vt__8cM3dGCyl",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CA7A88,'size':12,'pad':0,'label':"__vt__8cM3dGAab",'name':"__vt__8cM3dGAab",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CA7A94,'size':36,'pad':0,'label':"__vt__12dBgS_ObjAcch",'name':"__vt__12dBgS_ObjAcch",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CA7AB8,'size':12,'pad':0,'label':"__vt__12J3DFrameCtrl",'name':"__vt__12J3DFrameCtrl",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CA7AC4,'size':12,'pad':0,'label':"__vt__15daObj_Oiltubo_c",'name':"__vt__15daObj_Oiltubo_c",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
]

# Names
SYMBOL_NAMES = {
	"_prolog":0,
	"_epilog":1,
	"_unresolved":2,
	"create__15daObj_Oiltubo_cFv":3,
	"__dt__8cM3dGCylFv":4,
	"__dt__8cM3dGAabFv":5,
	"__dt__12dBgS_AcchCirFv":6,
	"__dt__10dCcD_GSttsFv":7,
	"__dt__12dBgS_ObjAcchFv":8,
	"__dt__12J3DFrameCtrlFv":9,
	"CreateHeap__15daObj_Oiltubo_cFv":10,
	"Delete__15daObj_Oiltubo_cFv":11,
	"Execute__15daObj_Oiltubo_cFv":12,
	"Draw__15daObj_Oiltubo_cFv":13,
	"createHeapCallBack__15daObj_Oiltubo_cFP10fopAc_ac_c":14,
	"getResName__15daObj_Oiltubo_cFv":15,
	"restart__15daObj_Oiltubo_cFv":16,
	"initialize__15daObj_Oiltubo_cFv":17,
	"setProcess__15daObj_Oiltubo_cFM15daObj_Oiltubo_cFPCvPvPv_i":18,
	"setParam__15daObj_Oiltubo_cFv":19,
	"setEnvTevColor__15daObj_Oiltubo_cFv":20,
	"setRoomNo__15daObj_Oiltubo_cFv":21,
	"setMtx__15daObj_Oiltubo_cFv":22,
	"setAttnPos__15daObj_Oiltubo_cFv":23,
	"chkEvent__15daObj_Oiltubo_cFv":24,
	"wait__15daObj_Oiltubo_cFPv":25,
	"daObj_Oiltubo_Create__FPv":26,
	"daObj_Oiltubo_Delete__FPv":27,
	"daObj_Oiltubo_Execute__FPv":28,
	"daObj_Oiltubo_Draw__FPv":29,
	"daObj_Oiltubo_IsDelete__FPv":30,
	"__dt__10cCcD_GSttsFv":31,
	"__dt__15daObj_Oiltubo_cFv":32,
	"__sinit_d_a_obj_oiltubo_cpp":33,
	"func_80CA78D8":34,
	"func_80CA78E0":35,
	"_ctors":36,
	"_dtors":37,
	"mCcDObjInfo__15daObj_Oiltubo_c":38,
	"lit_3815":39,
	"lit_3863":40,
	"lit_3864":41,
	"lit_3865":42,
	"lit_3884":43,
	"lit_3885":44,
	"lit_3999":45,
	"lit_4029":46,
	"lit_4030":47,
	"d_a_obj_oiltubo__stringBase0":48,
	"cNullVec__6Z2Calc":49,
	"lit_1787":50,
	"l_resFileName":51,
	"l_bmdFileName":52,
	"l_bbmdFileName":53,
	"l_bbtkFileName":54,
	"mCcDCyl__15daObj_Oiltubo_c":55,
	"lit_3897":56,
	"daObj_Oiltubo_MethodTable":57,
	"g_profile_OBJ_OILTUBO":58,
	"__vt__10cCcD_GStts":59,
	"__vt__10dCcD_GStts":60,
	"__vt__12dBgS_AcchCir":61,
	"__vt__8cM3dGCyl":62,
	"__vt__8cM3dGAab":63,
	"__vt__12dBgS_ObjAcch":64,
	"__vt__12J3DFrameCtrl":65,
	"__vt__15daObj_Oiltubo_c":66,
}

