#
# Generate By: dol2asm
# Module: 635
#

# Libraries
LIBRARIES = [
	"d/a/obj/d_a_obj_stopper2",
]

# Translation Units
TRANSLATION_UNITS = [
	"executor",
	"unknown_translation_unit_ctors",
	"unknown_translation_unit_dtors",
	"unknown_translation_unit_bss",
	"d_a_obj_stopper2",
]

# Sections
SECTIONS = [
	".text",
	".ctors",
	".dtors",
	".bss",
	".rodata",
	".data",
]

# Symbols
SYMBOLS = [
	{'addr':0x80CEF2C0,'size':44,'pad':0,'label':"_prolog",'name':"_prolog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEF2EC,'size':44,'pad':0,'label':"_epilog",'name':"_epilog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEF318,'size':32,'pad':0,'label':"_unresolved",'name':"_unresolved",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEF338,'size':32,'pad':0,'label':"CheckCreateHeap__FP10fopAc_ac_c",'name':"CheckCreateHeap__FP10fopAc_ac_c",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEF358,'size':16,'pad':0,'label':"getStopName__Fv",'name':"getStopName__Fv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEF368,'size':36,'pad':0,'label':"getStopModelData__15daObjStopper2_cFv",'name':"getStopModelData__15daObjStopper2_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEF38C,'size':60,'pad':0,'label':"initBaseMtx__15daObjStopper2_cFv",'name':"initBaseMtx__15daObjStopper2_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEF3C8,'size':108,'pad':0,'label':"setBaseMtx__15daObjStopper2_cFv",'name':"setBaseMtx__15daObjStopper2_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEF434,'size':24,'pad':0,'label':"getMaxOffsetY__15daObjStopper2_cFv",'name':"getMaxOffsetY__15daObjStopper2_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEF44C,'size':304,'pad':0,'label':"Create__15daObjStopper2_cFv",'name':"Create__15daObjStopper2_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEF57C,'size':76,'pad':0,'label':"CreateHeap__15daObjStopper2_cFv",'name':"CreateHeap__15daObjStopper2_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEF5C8,'size':164,'pad':0,'label':"create__15daObjStopper2_cFv",'name':"create__15daObjStopper2_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEF66C,'size':56,'pad':0,'label':"execute__15daObjStopper2_cFv",'name':"execute__15daObjStopper2_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEF6A4,'size':188,'pad':0,'label':"event_proc_call__15daObjStopper2_cFv",'name':"event_proc_call__15daObjStopper2_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEF760,'size':556,'pad':0,'label':"actionWait__15daObjStopper2_cFv",'name':"actionWait__15daObjStopper2_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEF98C,'size':212,'pad':0,'label':"actionOrderEvent__15daObjStopper2_cFv",'name':"actionOrderEvent__15daObjStopper2_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEFA60,'size':116,'pad':0,'label':"actionEvent__15daObjStopper2_cFv",'name':"actionEvent__15daObjStopper2_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEFAD4,'size':4,'pad':0,'label':"actionDead__15daObjStopper2_cFv",'name':"actionDead__15daObjStopper2_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReturnFunction"},
	{'addr':0x80CEFAD8,'size':616,'pad':0,'label':"demoProc__15daObjStopper2_cFv",'name':"demoProc__15daObjStopper2_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEFD40,'size':120,'pad':0,'label':"draw__15daObjStopper2_cFv",'name':"draw__15daObjStopper2_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEFDB8,'size':52,'pad':0,'label':"_delete__15daObjStopper2_cFv",'name':"_delete__15daObjStopper2_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEFDEC,'size':32,'pad':0,'label':"daObjStopper2_Draw__FP15daObjStopper2_c",'name':"daObjStopper2_Draw__FP15daObjStopper2_c",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEFE0C,'size':32,'pad':0,'label':"daObjStopper2_Execute__FP15daObjStopper2_c",'name':"daObjStopper2_Execute__FP15daObjStopper2_c",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEFE2C,'size':32,'pad':0,'label':"daObjStopper2_Delete__FP15daObjStopper2_c",'name':"daObjStopper2_Delete__FP15daObjStopper2_c",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEFE4C,'size':32,'pad':0,'label':"daObjStopper2_Create__FP15daObjStopper2_c",'name':"daObjStopper2_Create__FP15daObjStopper2_c",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEFE6C,'size':28,'pad':0,'label':"func_80CEFE6C",'name':"cLib_calcTimer<Uc>__FPUc",'lib':-1,'tu':4,'section':0,'class_template':True,'static':False,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CEFE88,'size':4,'pad':0,'label':"_ctors",'name':"_ctors",'lib':-1,'tu':1,'section':1,'class_template':False,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80CEFE8C,'size':4,'pad':0,'label':"_dtors",'name':"_dtors",'lib':-1,'tu':2,'section':2,'class_template':False,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80CEFE90,'size':4,'pad':0,'label':"lit_3722",'name':"@3722",'lib':-1,'tu':4,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CEFE94,'size':4,'pad':0,'label':"lit_3723",'name':"@3723",'lib':-1,'tu':4,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CEFE98,'size':4,'pad':0,'label':"lit_3921",'name':"@3921",'lib':-1,'tu':4,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CEFE9C,'size':4,'pad':0,'label':"lit_3922",'name':"@3922",'lib':-1,'tu':4,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CEFEA0,'size':4,'pad':0,'label':"lit_3923",'name':"@3923",'lib':-1,'tu':4,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CEFEA4,'size':4,'pad':0,'label':"lit_3924",'name':"@3924",'lib':-1,'tu':4,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CEFEA8,'size':4,'pad':0,'label':"lit_3925",'name':"@3925",'lib':-1,'tu':4,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CEFEAC,'size':4,'pad':0,'label':"lit_3926",'name':"@3926",'lib':-1,'tu':4,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CEFEB0,'size':82,'pad':0,'label':"d_a_obj_stopper2__stringBase0",'name':"@stringBase0",'lib':-1,'tu':4,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[6,0,0],'sh':[0,0,0],'type':"StringBase"},
	{'addr':0x80CEFF04,'size':12,'pad':0,'label':"cNullVec__6Z2Calc",'name':"cNullVec__6Z2Calc",'lib':-1,'tu':4,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CEFF10,'size':4,'pad':16,'label':"lit_1787",'name':"@1787",'lib':-1,'tu':4,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CEFF24,'size':4,'pad':0,'label':"l_arcName",'name':"l_arcName",'lib':-1,'tu':4,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CEFF28,'size':16,'pad':0,'label':"l_evName",'name':"l_evName",'lib':-1,'tu':4,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CEFF38,'size':4,'pad':0,'label':"l_staffName",'name':"l_staffName",'lib':-1,'tu':4,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CEFF3C,'size':12,'pad':0,'label':"lit_3769",'name':"@3769",'lib':-1,'tu':4,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CEFF48,'size':12,'pad':0,'label':"lit_3770",'name':"@3770",'lib':-1,'tu':4,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CEFF54,'size':12,'pad':0,'label':"lit_3771",'name':"@3771",'lib':-1,'tu':4,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CEFF60,'size':12,'pad':0,'label':"lit_3772",'name':"@3772",'lib':-1,'tu':4,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CEFF6C,'size':48,'pad':0,'label':"l_func",'name':"l_func$3768",'lib':-1,'tu':4,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CEFF9C,'size':12,'pad':0,'label':"action_table",'name':"action_table$3859",'lib':-1,'tu':4,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CEFFA8,'size':32,'pad':0,'label':"l_daObjStopper2_Method",'name':"l_daObjStopper2_Method",'lib':-1,'tu':4,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CEFFC8,'size':48,'pad':0,'label':"g_profile_Obj_Stopper2",'name':"g_profile_Obj_Stopper2",'lib':-1,'tu':4,'section':5,'class_template':False,'static':False,'is_reachable':False,'r':[0,0,1],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CEFFF8,'size':4,'pad':0,'label':"data_80CEFFF8",'name':None,'lib':-1,'tu':3,'section':3,'class_template':False,'static':False,'is_reachable':False,'r':[0,1,0],'sh':[0,0,0],'type':"ArbitraryData"},
]

# Names
SYMBOL_NAMES = {
	"_prolog":0,
	"_epilog":1,
	"_unresolved":2,
	"CheckCreateHeap__FP10fopAc_ac_c":3,
	"getStopName__Fv":4,
	"getStopModelData__15daObjStopper2_cFv":5,
	"initBaseMtx__15daObjStopper2_cFv":6,
	"setBaseMtx__15daObjStopper2_cFv":7,
	"getMaxOffsetY__15daObjStopper2_cFv":8,
	"Create__15daObjStopper2_cFv":9,
	"CreateHeap__15daObjStopper2_cFv":10,
	"create__15daObjStopper2_cFv":11,
	"execute__15daObjStopper2_cFv":12,
	"event_proc_call__15daObjStopper2_cFv":13,
	"actionWait__15daObjStopper2_cFv":14,
	"actionOrderEvent__15daObjStopper2_cFv":15,
	"actionEvent__15daObjStopper2_cFv":16,
	"actionDead__15daObjStopper2_cFv":17,
	"demoProc__15daObjStopper2_cFv":18,
	"draw__15daObjStopper2_cFv":19,
	"_delete__15daObjStopper2_cFv":20,
	"daObjStopper2_Draw__FP15daObjStopper2_c":21,
	"daObjStopper2_Execute__FP15daObjStopper2_c":22,
	"daObjStopper2_Delete__FP15daObjStopper2_c":23,
	"daObjStopper2_Create__FP15daObjStopper2_c":24,
	"func_80CEFE6C":25,
	"_ctors":26,
	"_dtors":27,
	"lit_3722":28,
	"lit_3723":29,
	"lit_3921":30,
	"lit_3922":31,
	"lit_3923":32,
	"lit_3924":33,
	"lit_3925":34,
	"lit_3926":35,
	"d_a_obj_stopper2__stringBase0":36,
	"cNullVec__6Z2Calc":37,
	"lit_1787":38,
	"l_arcName":39,
	"l_evName":40,
	"l_staffName":41,
	"lit_3769":42,
	"lit_3770":43,
	"lit_3771":44,
	"lit_3772":45,
	"l_func":46,
	"action_table":47,
	"l_daObjStopper2_Method":48,
	"g_profile_Obj_Stopper2":49,
	"data_80CEFFF8":50,
}

