#
# Generate By: dol2asm
# Module: 638
#

# Libraries
LIBRARIES = [
	"d/a/obj/d_a_obj_swBallA",
]

# Translation Units
TRANSLATION_UNITS = [
	"executor",
	"unknown_translation_unit_ctors",
	"unknown_translation_unit_dtors",
	"d_a_obj_swBallA",
]

# Sections
SECTIONS = [
	".text",
	".ctors",
	".dtors",
	".rodata",
	".data",
	".bss",
]

# Symbols
SYMBOLS = [
	{'addr':0x80CF3280,'size':44,'pad':0,'label':"_prolog",'name':"_prolog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF32AC,'size':44,'pad':0,'label':"_epilog",'name':"_epilog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF32D8,'size':32,'pad':0,'label':"_unresolved",'name':"_unresolved",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF32F8,'size':124,'pad':0,'label':"s_ball_sub__FPvPv",'name':"s_ball_sub__FPvPv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF3374,'size':32,'pad':0,'label':"CheckCreateHeap__FP10fopAc_ac_c",'name':"CheckCreateHeap__FP10fopAc_ac_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF3394,'size':336,'pad':0,'label':"checkArea_sub__14daObjSwBallA_cFP10fopAc_ac_c",'name':"checkArea_sub__14daObjSwBallA_cFP10fopAc_ac_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF34E4,'size':300,'pad':0,'label':"search_ball__14daObjSwBallA_cFv",'name':"search_ball__14daObjSwBallA_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF3610,'size':32,'pad':0,'label':"initBaseMtx__14daObjSwBallA_cFv",'name':"initBaseMtx__14daObjSwBallA_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF3630,'size':100,'pad':0,'label':"setBaseMtx__14daObjSwBallA_cFv",'name':"setBaseMtx__14daObjSwBallA_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF3694,'size':360,'pad':0,'label':"Create__14daObjSwBallA_cFv",'name':"Create__14daObjSwBallA_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF37FC,'size':300,'pad':0,'label':"CreateHeap__14daObjSwBallA_cFv",'name':"CreateHeap__14daObjSwBallA_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF3928,'size':72,'pad':0,'label':"__dt__12J3DFrameCtrlFv",'name':"__dt__12J3DFrameCtrlFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF3970,'size':288,'pad':0,'label':"create__14daObjSwBallA_cFv",'name':"create__14daObjSwBallA_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF3A90,'size':176,'pad':0,'label':"execute__14daObjSwBallA_cFv",'name':"execute__14daObjSwBallA_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF3B40,'size':576,'pad':0,'label':"actionRun__14daObjSwBallA_cFv",'name':"actionRun__14daObjSwBallA_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF3D80,'size':4,'pad':0,'label':"actionStop__14daObjSwBallA_cFv",'name':"actionStop__14daObjSwBallA_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReturnFunction"},
	{'addr':0x80CF3D84,'size':744,'pad':0,'label':"PutCrrPos__14daObjSwBallA_cFv",'name':"PutCrrPos__14daObjSwBallA_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF406C,'size':392,'pad':0,'label':"draw__14daObjSwBallA_cFv",'name':"draw__14daObjSwBallA_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF41F4,'size':128,'pad':0,'label':"_delete__14daObjSwBallA_cFv",'name':"_delete__14daObjSwBallA_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF4274,'size':32,'pad':0,'label':"daObjSwBallA_Draw__FP14daObjSwBallA_c",'name':"daObjSwBallA_Draw__FP14daObjSwBallA_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF4294,'size':32,'pad':0,'label':"daObjSwBallA_Execute__FP14daObjSwBallA_c",'name':"daObjSwBallA_Execute__FP14daObjSwBallA_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF42B4,'size':32,'pad':0,'label':"daObjSwBallA_Delete__FP14daObjSwBallA_c",'name':"daObjSwBallA_Delete__FP14daObjSwBallA_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF42D4,'size':32,'pad':0,'label':"daObjSwBallA_Create__FP10fopAc_ac_c",'name':"daObjSwBallA_Create__FP10fopAc_ac_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF42F4,'size':72,'pad':0,'label':"__dt__17dEvLib_callback_cFv",'name':"__dt__17dEvLib_callback_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF433C,'size':8,'pad':0,'label':"eventStart__17dEvLib_callback_cFv",'name':"eventStart__17dEvLib_callback_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ReturnFunction"},
	{'addr':0x80CF4344,'size':8,'pad':0,'label':"eventRun__17dEvLib_callback_cFv",'name':"eventRun__17dEvLib_callback_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ReturnFunction"},
	{'addr':0x80CF434C,'size':8,'pad':0,'label':"eventEnd__17dEvLib_callback_cFv",'name':"eventEnd__17dEvLib_callback_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ReturnFunction"},
	{'addr':0x80CF4354,'size':128,'pad':0,'label':"__dt__14daObjSwBallA_cFv",'name':"__dt__14daObjSwBallA_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF43D4,'size':8,'pad':0,'label':"func_80CF43D4",'name':"@1384@__dt__14daObjSwBallA_cFv",'lib':-1,'tu':3,'section':0,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF43DC,'size':4,'pad':0,'label':"_ctors",'name':"_ctors",'lib':-1,'tu':1,'section':1,'class_template':False,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80CF43E0,'size':4,'pad':0,'label':"_dtors",'name':"_dtors",'lib':-1,'tu':2,'section':2,'class_template':False,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80CF43E4,'size':4,'pad':0,'label':"l_color",'name':"l_color",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[4,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CF43E8,'size':4,'pad':0,'label':"lit_3730",'name':"@3730",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CF43EC,'size':4,'pad':0,'label':"lit_3731",'name':"@3731",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CF43F0,'size':4,'pad':0,'label':"lit_3732",'name':"@3732",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CF43F4,'size':4,'pad':4,'label':"lit_3733",'name':"@3733",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CF43FC,'size':8,'pad':0,'label':"lit_3884",'name':"@3884",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CF4404,'size':4,'pad':0,'label':"lit_3918",'name':"@3918",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CF4408,'size':4,'pad':0,'label':"lit_4032",'name':"@4032",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CF440C,'size':4,'pad':0,'label':"lit_4122",'name':"@4122",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CF4410,'size':8,'pad':0,'label':"d_a_obj_swBallA__stringBase0",'name':"@stringBase0",'lib':-1,'tu':3,'section':3,'class_template':False,'static':False,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"StringBase"},
	{'addr':0x80CF4418,'size':12,'pad':0,'label':"cNullVec__6Z2Calc",'name':"cNullVec__6Z2Calc",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CF4424,'size':4,'pad':16,'label':"lit_1787",'name':"@1787",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CF4438,'size':4,'pad':0,'label':"l_arcName",'name':"l_arcName",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CF443C,'size':12,'pad':0,'label':"lit_3956",'name':"@3956",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CF4448,'size':12,'pad':0,'label':"lit_3957",'name':"@3957",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CF4454,'size':24,'pad':0,'label':"l_func",'name':"l_func$3955",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CF446C,'size':32,'pad':0,'label':"l_daObjSwBallA_Method",'name':"l_daObjSwBallA_Method",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CF448C,'size':48,'pad':0,'label':"g_profile_Obj_SwBallA",'name':"g_profile_Obj_SwBallA",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[0,0,1],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CF44BC,'size':36,'pad':0,'label':"__vt__14daObjSwBallA_c",'name':"__vt__14daObjSwBallA_c",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CF44E0,'size':24,'pad':0,'label':"__vt__17dEvLib_callback_c",'name':"__vt__17dEvLib_callback_c",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CF44F8,'size':12,'pad':0,'label':"__vt__12J3DFrameCtrl",'name':"__vt__12J3DFrameCtrl",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CF4508,'size':32,'pad':0,'label':"l_target_info",'name':"l_target_info",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CF4528,'size':4,'pad':0,'label':"l_target_info_count",'name':"l_target_info_count",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CF452C,'size':4,'pad':0,'label':"data_80CF452C",'name':None,'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
]

# Names
SYMBOL_NAMES = {
	"_prolog":0,
	"_epilog":1,
	"_unresolved":2,
	"s_ball_sub__FPvPv":3,
	"CheckCreateHeap__FP10fopAc_ac_c":4,
	"checkArea_sub__14daObjSwBallA_cFP10fopAc_ac_c":5,
	"search_ball__14daObjSwBallA_cFv":6,
	"initBaseMtx__14daObjSwBallA_cFv":7,
	"setBaseMtx__14daObjSwBallA_cFv":8,
	"Create__14daObjSwBallA_cFv":9,
	"CreateHeap__14daObjSwBallA_cFv":10,
	"__dt__12J3DFrameCtrlFv":11,
	"create__14daObjSwBallA_cFv":12,
	"execute__14daObjSwBallA_cFv":13,
	"actionRun__14daObjSwBallA_cFv":14,
	"actionStop__14daObjSwBallA_cFv":15,
	"PutCrrPos__14daObjSwBallA_cFv":16,
	"draw__14daObjSwBallA_cFv":17,
	"_delete__14daObjSwBallA_cFv":18,
	"daObjSwBallA_Draw__FP14daObjSwBallA_c":19,
	"daObjSwBallA_Execute__FP14daObjSwBallA_c":20,
	"daObjSwBallA_Delete__FP14daObjSwBallA_c":21,
	"daObjSwBallA_Create__FP10fopAc_ac_c":22,
	"__dt__17dEvLib_callback_cFv":23,
	"eventStart__17dEvLib_callback_cFv":24,
	"eventRun__17dEvLib_callback_cFv":25,
	"eventEnd__17dEvLib_callback_cFv":26,
	"__dt__14daObjSwBallA_cFv":27,
	"func_80CF43D4":28,
	"_ctors":29,
	"_dtors":30,
	"l_color":31,
	"lit_3730":32,
	"lit_3731":33,
	"lit_3732":34,
	"lit_3733":35,
	"lit_3884":36,
	"lit_3918":37,
	"lit_4032":38,
	"lit_4122":39,
	"d_a_obj_swBallA__stringBase0":40,
	"cNullVec__6Z2Calc":41,
	"lit_1787":42,
	"l_arcName":43,
	"lit_3956":44,
	"lit_3957":45,
	"l_func":46,
	"l_daObjSwBallA_Method":47,
	"g_profile_Obj_SwBallA":48,
	"__vt__14daObjSwBallA_c":49,
	"__vt__17dEvLib_callback_c":50,
	"__vt__12J3DFrameCtrl":51,
	"l_target_info":52,
	"l_target_info_count":53,
	"data_80CF452C":54,
}

