#
# Generate By: dol2asm
# Module: 467
#

# Libraries
LIBRARIES = [
	"d/a/obj/d_a_obj_groundwater",
]

# Translation Units
TRANSLATION_UNITS = [
	"executor",
	"unknown_translation_unit_ctors",
	"global_destructor_chain",
	"d_a_obj_groundwater",
]

# Sections
SECTIONS = [
	".text",
	".ctors",
	".dtors",
	".bss",
	".rodata",
	".data",
]

# Symbols
SYMBOLS = [
	{'addr':0x80C133C0,'size':44,'pad':0,'label':"_prolog",'name':"_prolog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C133EC,'size':44,'pad':0,'label':"_epilog",'name':"_epilog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C13418,'size':32,'pad':0,'label':"_unresolved",'name':"_unresolved",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C13438,'size':28,'pad':0,'label':"__register_global_object",'name':"__register_global_object",'lib':-1,'tu':2,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C13454,'size':88,'pad':0,'label':"__destroy_global_chain",'name':"__destroy_global_chain",'lib':-1,'tu':2,'section':0,'class_template':None,'static':False,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C134AC,'size':76,'pad':0,'label':"__ct__16daGrdWater_HIO_cFv",'name':"__ct__16daGrdWater_HIO_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':True,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C134F8,'size':72,'pad':0,'label':"__dt__14mDoHIO_entry_cFv",'name':"__dt__14mDoHIO_entry_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':True,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C13540,'size':216,'pad':0,'label':"setBaseMtx__12daGrdWater_cFv",'name':"setBaseMtx__12daGrdWater_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C13618,'size':972,'pad':0,'label':"CreateHeap__12daGrdWater_cFv",'name':"CreateHeap__12daGrdWater_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C139E4,'size':972,'pad':0,'label':"create__12daGrdWater_cFv",'name':"create__12daGrdWater_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C13DB0,'size':500,'pad':0,'label':"__ct__12daGrdWater_cFv",'name':"__ct__12daGrdWater_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C13FA4,'size':72,'pad':0,'label':"__dt__12J3DFrameCtrlFv",'name':"__dt__12J3DFrameCtrlFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C13FEC,'size':424,'pad':0,'label':"Execute__12daGrdWater_cFPPA3_A4_f",'name':"Execute__12daGrdWater_cFPPA3_A4_f",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C14194,'size':12,'pad':0,'label':"init_modeWait__12daGrdWater_cFv",'name':"init_modeWait__12daGrdWater_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[5,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C141A0,'size':4,'pad':0,'label':"modeWait__12daGrdWater_cFv",'name':"modeWait__12daGrdWater_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReturnFunction"},
	{'addr':0x80C141A4,'size':152,'pad':0,'label':"init_modeLevelUpA__12daGrdWater_cFv",'name':"init_modeLevelUpA__12daGrdWater_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C1423C,'size':112,'pad':0,'label':"modeLevelUpA__12daGrdWater_cFv",'name':"modeLevelUpA__12daGrdWater_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C142AC,'size':116,'pad':0,'label':"init_modeLevelDownA__12daGrdWater_cFv",'name':"init_modeLevelDownA__12daGrdWater_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C14320,'size':92,'pad':0,'label':"modeLevelDownA__12daGrdWater_cFv",'name':"modeLevelDownA__12daGrdWater_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C1437C,'size':152,'pad':0,'label':"init_modeLevelUpB__12daGrdWater_cFv",'name':"init_modeLevelUpB__12daGrdWater_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C14414,'size':112,'pad':0,'label':"modeLevelUpB__12daGrdWater_cFv",'name':"modeLevelUpB__12daGrdWater_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C14484,'size':116,'pad':0,'label':"init_modeLevelDownB__12daGrdWater_cFv",'name':"init_modeLevelDownB__12daGrdWater_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C144F8,'size':92,'pad':0,'label':"modeLevelDownB__12daGrdWater_cFv",'name':"modeLevelDownB__12daGrdWater_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C14554,'size':664,'pad':0,'label':"Draw__12daGrdWater_cFv",'name':"Draw__12daGrdWater_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C147EC,'size':48,'pad':0,'label':"Delete__12daGrdWater_cFv",'name':"Delete__12daGrdWater_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C1481C,'size':44,'pad':0,'label':"daGrdWater_Draw__FP12daGrdWater_c",'name':"daGrdWater_Draw__FP12daGrdWater_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C14848,'size':32,'pad':0,'label':"daGrdWater_Execute__FP12daGrdWater_c",'name':"daGrdWater_Execute__FP12daGrdWater_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C14868,'size':32,'pad':0,'label':"daGrdWater_Delete__FP12daGrdWater_c",'name':"daGrdWater_Delete__FP12daGrdWater_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C14888,'size':32,'pad':0,'label':"daGrdWater_Create__FP10fopAc_ac_c",'name':"daGrdWater_Create__FP10fopAc_ac_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C148A8,'size':92,'pad':0,'label':"__dt__16daGrdWater_HIO_cFv",'name':"__dt__16daGrdWater_HIO_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':True,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C14904,'size':200,'pad':0,'label':"__sinit_d_a_obj_groundwater_cpp",'name':"__sinit_d_a_obj_groundwater_cpp",'lib':-1,'tu':3,'section':0,'class_template':None,'static':False,'is_reachable':False,'r':[0,1,0],'sh':[0,0,0],'type':"SInitFunction"},
	{'addr':0x80C149CC,'size':8,'pad':0,'label':"_ctors",'name':"_ctors",'lib':-1,'tu':1,'section':1,'class_template':False,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80C149D4,'size':12,'pad':0,'label':"_dtors",'name':"_dtors",'lib':-1,'tu':2,'section':2,'class_template':False,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80C149E0,'size':4,'pad':0,'label':"lit_3642",'name':"@3642",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':True,'r':[3,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80C149E4,'size':4,'pad':0,'label':"lit_3712",'name':"@3712",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[5,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80C149E8,'size':8,'pad':0,'label':"lit_3891",'name':"@3891",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[5,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80C149F0,'size':4,'pad':0,'label':"lit_4253",'name':"@4253",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80C149F4,'size':6,'pad':0,'label':"d_a_obj_groundwater__stringBase0",'name':"@stringBase0",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"StringBase"},
	{'addr':0x80C149FC,'size':12,'pad':0,'label':"cNullVec__6Z2Calc",'name':"cNullVec__6Z2Calc",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':True,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80C14A08,'size':4,'pad':16,'label':"lit_1787",'name':"@1787",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80C14A1C,'size':12,'pad':0,'label':"lit_3993",'name':"@3993",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80C14A28,'size':12,'pad':0,'label':"lit_3994",'name':"@3994",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80C14A34,'size':12,'pad':0,'label':"lit_3995",'name':"@3995",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80C14A40,'size':12,'pad':0,'label':"lit_3996",'name':"@3996",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80C14A4C,'size':12,'pad':0,'label':"lit_3997",'name':"@3997",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80C14A58,'size':60,'pad':0,'label':"l_mode_func",'name':"l_mode_func",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80C14A94,'size':32,'pad':0,'label':"l_daGrdWater_Method",'name':"l_daGrdWater_Method",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80C14AB4,'size':48,'pad':0,'label':"g_profile_GRDWATER",'name':"g_profile_GRDWATER",'lib':-1,'tu':3,'section':5,'class_template':False,'static':False,'is_reachable':False,'r':[0,0,1],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80C14AE4,'size':12,'pad':0,'label':"__vt__12J3DFrameCtrl",'name':"__vt__12J3DFrameCtrl",'lib':-1,'tu':3,'section':5,'class_template':False,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80C14AF0,'size':40,'pad':0,'label':"__vt__12daGrdWater_c",'name':"__vt__12daGrdWater_c",'lib':-1,'tu':3,'section':5,'class_template':False,'static':False,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80C14B18,'size':12,'pad':0,'label':"__vt__16daGrdWater_HIO_c",'name':"__vt__16daGrdWater_HIO_c",'lib':-1,'tu':3,'section':5,'class_template':False,'static':False,'is_reachable':True,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80C14B24,'size':12,'pad':0,'label':"__vt__14mDoHIO_entry_c",'name':"__vt__14mDoHIO_entry_c",'lib':-1,'tu':3,'section':5,'class_template':False,'static':False,'is_reachable':True,'r':[3,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80C14B30,'size':4,'pad':4,'label':"__global_destructor_chain",'name':"__global_destructor_chain",'lib':-1,'tu':2,'section':3,'class_template':False,'static':True,'is_reachable':True,'r':[2,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80C14B38,'size':12,'pad':0,'label':"lit_3636",'name':"@3636",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':True,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80C14B44,'size':20,'pad':0,'label':"l_HIO",'name':"l_HIO",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':True,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
]

# Names
SYMBOL_NAMES = {
	"_prolog":0,
	"_epilog":1,
	"_unresolved":2,
	"__register_global_object":3,
	"__destroy_global_chain":4,
	"__ct__16daGrdWater_HIO_cFv":5,
	"__dt__14mDoHIO_entry_cFv":6,
	"setBaseMtx__12daGrdWater_cFv":7,
	"CreateHeap__12daGrdWater_cFv":8,
	"create__12daGrdWater_cFv":9,
	"__ct__12daGrdWater_cFv":10,
	"__dt__12J3DFrameCtrlFv":11,
	"Execute__12daGrdWater_cFPPA3_A4_f":12,
	"init_modeWait__12daGrdWater_cFv":13,
	"modeWait__12daGrdWater_cFv":14,
	"init_modeLevelUpA__12daGrdWater_cFv":15,
	"modeLevelUpA__12daGrdWater_cFv":16,
	"init_modeLevelDownA__12daGrdWater_cFv":17,
	"modeLevelDownA__12daGrdWater_cFv":18,
	"init_modeLevelUpB__12daGrdWater_cFv":19,
	"modeLevelUpB__12daGrdWater_cFv":20,
	"init_modeLevelDownB__12daGrdWater_cFv":21,
	"modeLevelDownB__12daGrdWater_cFv":22,
	"Draw__12daGrdWater_cFv":23,
	"Delete__12daGrdWater_cFv":24,
	"daGrdWater_Draw__FP12daGrdWater_c":25,
	"daGrdWater_Execute__FP12daGrdWater_c":26,
	"daGrdWater_Delete__FP12daGrdWater_c":27,
	"daGrdWater_Create__FP10fopAc_ac_c":28,
	"__dt__16daGrdWater_HIO_cFv":29,
	"__sinit_d_a_obj_groundwater_cpp":30,
	"_ctors":31,
	"_dtors":32,
	"lit_3642":33,
	"lit_3712":34,
	"lit_3891":35,
	"lit_4253":36,
	"d_a_obj_groundwater__stringBase0":37,
	"cNullVec__6Z2Calc":38,
	"lit_1787":39,
	"lit_3993":40,
	"lit_3994":41,
	"lit_3995":42,
	"lit_3996":43,
	"lit_3997":44,
	"l_mode_func":45,
	"l_daGrdWater_Method":46,
	"g_profile_GRDWATER":47,
	"__vt__12J3DFrameCtrl":48,
	"__vt__12daGrdWater_c":49,
	"__vt__16daGrdWater_HIO_c":50,
	"__vt__14mDoHIO_entry_c":51,
	"__global_destructor_chain":52,
	"lit_3636":53,
	"l_HIO":54,
}

