#
# Generate By: dol2asm
# Module: 603
#

# Libraries
LIBRARIES = [
	"d/a/obj/d_a_obj_riverrock",
]

# Translation Units
TRANSLATION_UNITS = [
	"executor",
	"unknown_translation_unit_ctors",
	"global_destructor_chain",
	"d_a_obj_riverrock",
]

# Sections
SECTIONS = [
	".text",
	".ctors",
	".dtors",
	".bss",
	".rodata",
	".data",
]

# Symbols
SYMBOLS = [
	{'addr':0x80CBC5E0,'size':44,'pad':0,'label':"_prolog",'name':"_prolog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBC60C,'size':44,'pad':0,'label':"_epilog",'name':"_epilog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBC638,'size':32,'pad':0,'label':"_unresolved",'name':"_unresolved",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBC658,'size':28,'pad':0,'label':"__register_global_object",'name':"__register_global_object",'lib':-1,'tu':2,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBC674,'size':88,'pad':0,'label':"__destroy_global_chain",'name':"__destroy_global_chain",'lib':-1,'tu':2,'section':0,'class_template':None,'static':False,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBC6CC,'size':40,'pad':0,'label':"__ct__20daObjRIVERROCK_HIO_cFv",'name':"__ct__20daObjRIVERROCK_HIO_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':True,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBC6F4,'size':96,'pad':0,'label':"initCcCylinder__16daObjRIVERROCK_cFv",'name':"initCcCylinder__16daObjRIVERROCK_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBC754,'size':96,'pad':0,'label':"SetCcCyl__16daObjRIVERROCK_cFv",'name':"SetCcCyl__16daObjRIVERROCK_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBC7B4,'size':32,'pad':0,'label':"daObjRIVERROCK_Create__FP10fopAc_ac_c",'name':"daObjRIVERROCK_Create__FP10fopAc_ac_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBC7D4,'size':36,'pad':0,'label':"daObjRIVERROCK_Delete__FP16daObjRIVERROCK_c",'name':"daObjRIVERROCK_Delete__FP16daObjRIVERROCK_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBC7F8,'size':196,'pad':0,'label':"BreakWaitAction__16daObjRIVERROCK_cFv",'name':"BreakWaitAction__16daObjRIVERROCK_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBC8BC,'size':896,'pad':0,'label':"CheckBG__16daObjRIVERROCK_cFv",'name':"CheckBG__16daObjRIVERROCK_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBCC3C,'size':132,'pad':0,'label':"BreakMoveAction__16daObjRIVERROCK_cFv",'name':"BreakMoveAction__16daObjRIVERROCK_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBCCC0,'size':212,'pad':0,'label':"BrokenAction__16daObjRIVERROCK_cFv",'name':"BrokenAction__16daObjRIVERROCK_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBCD94,'size':84,'pad':0,'label':"BreakAction__16daObjRIVERROCK_cFv",'name':"BreakAction__16daObjRIVERROCK_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBCDE8,'size':68,'pad':0,'label':"Action__16daObjRIVERROCK_cFv",'name':"Action__16daObjRIVERROCK_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBCE2C,'size':920,'pad':0,'label':"BreakSet__16daObjRIVERROCK_cFv",'name':"BreakSet__16daObjRIVERROCK_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBD1C4,'size':64,'pad':0,'label':"WaitAction__16daObjRIVERROCK_cFv",'name':"WaitAction__16daObjRIVERROCK_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBD204,'size':248,'pad':0,'label':"setBaseMtx__16daObjRIVERROCK_cFv",'name':"setBaseMtx__16daObjRIVERROCK_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBD2FC,'size':44,'pad':0,'label':"daObjRIVERROCK_Draw__FP16daObjRIVERROCK_c",'name':"daObjRIVERROCK_Draw__FP16daObjRIVERROCK_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBD328,'size':32,'pad':0,'label':"daObjRIVERROCK_Execute__FP16daObjRIVERROCK_c",'name':"daObjRIVERROCK_Execute__FP16daObjRIVERROCK_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBD348,'size':120,'pad':0,'label':"CreateHeap__16daObjRIVERROCK_cFv",'name':"CreateHeap__16daObjRIVERROCK_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBD3C0,'size':860,'pad':0,'label':"create__16daObjRIVERROCK_cFv",'name':"create__16daObjRIVERROCK_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBD71C,'size':72,'pad':0,'label':"__dt__8cM3dGCylFv",'name':"__dt__8cM3dGCylFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBD764,'size':72,'pad':0,'label':"__dt__8cM3dGAabFv",'name':"__dt__8cM3dGAabFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBD7AC,'size':8,'pad':0,'label':"daObjRIVERROCK_IsDelete__FP16daObjRIVERROCK_c",'name':"daObjRIVERROCK_IsDelete__FP16daObjRIVERROCK_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReturnFunction"},
	{'addr':0x80CBD7B4,'size':96,'pad':0,'label':"Create__16daObjRIVERROCK_cFv",'name':"Create__16daObjRIVERROCK_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBD814,'size':204,'pad':0,'label':"Execute__16daObjRIVERROCK_cFPPA3_A4_f",'name':"Execute__16daObjRIVERROCK_cFPPA3_A4_f",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBD8E0,'size':132,'pad':0,'label':"Draw__16daObjRIVERROCK_cFv",'name':"Draw__16daObjRIVERROCK_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBD964,'size':96,'pad':0,'label':"Delete__16daObjRIVERROCK_cFv",'name':"Delete__16daObjRIVERROCK_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBD9C4,'size':72,'pad':0,'label':"__dt__20daObjRIVERROCK_HIO_cFv",'name':"__dt__20daObjRIVERROCK_HIO_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':True,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CBDA0C,'size':60,'pad':0,'label':"__sinit_d_a_obj_riverrock_cpp",'name':"__sinit_d_a_obj_riverrock_cpp",'lib':-1,'tu':3,'section':0,'class_template':None,'static':False,'is_reachable':False,'r':[0,1,0],'sh':[0,0,0],'type':"SInitFunction"},
	{'addr':0x80CBDA48,'size':8,'pad':0,'label':"_ctors",'name':"_ctors",'lib':-1,'tu':1,'section':1,'class_template':False,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80CBDA50,'size':12,'pad':0,'label':"_dtors",'name':"_dtors",'lib':-1,'tu':2,'section':2,'class_template':False,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80CBDA5C,'size':4,'pad':0,'label':"lit_3631",'name':"@3631",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':True,'r':[6,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CBDA60,'size':68,'pad':0,'label':"ccCylSrc",'name':"ccCylSrc$3635",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CBDAA4,'size':4,'pad':4,'label':"lit_3642",'name':"@3642",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDAAC,'size':8,'pad':0,'label':"lit_3669",'name':"@3669",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CBDAB4,'size':4,'pad':0,'label':"lit_3742",'name':"@3742",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDAB8,'size':4,'pad':0,'label':"lit_3743",'name':"@3743",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDABC,'size':4,'pad':0,'label':"lit_3744",'name':"@3744",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDAC0,'size':4,'pad':0,'label':"lit_3745",'name':"@3745",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDAC4,'size':4,'pad':0,'label':"lit_3746",'name':"@3746",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDAC8,'size':4,'pad':0,'label':"lit_3747",'name':"@3747",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDACC,'size':4,'pad':0,'label':"lit_3748",'name':"@3748",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDAD0,'size':4,'pad':0,'label':"lit_3749",'name':"@3749",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDAD4,'size':4,'pad':0,'label':"lit_3758",'name':"@3758",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDAD8,'size':4,'pad':0,'label':"lit_3861",'name':"@3861",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDADC,'size':4,'pad':0,'label':"lit_3862",'name':"@3862",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDAE0,'size':4,'pad':0,'label':"lit_3895",'name':"@3895",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDAE4,'size':4,'pad':0,'label':"lit_3896",'name':"@3896",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDAE8,'size':4,'pad':0,'label':"lit_4026",'name':"@4026",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDAEC,'size':4,'pad':0,'label':"lit_4027",'name':"@4027",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDAF0,'size':4,'pad':0,'label':"lit_4028",'name':"@4028",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDAF4,'size':4,'pad':0,'label':"lit_4029",'name':"@4029",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDAF8,'size':4,'pad':0,'label':"lit_4030",'name':"@4030",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDAFC,'size':4,'pad':0,'label':"lit_4031",'name':"@4031",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDB00,'size':4,'pad':0,'label':"lit_4032",'name':"@4032",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDB04,'size':8,'pad':0,'label':"lit_4034",'name':"@4034",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CBDB0C,'size':4,'pad':0,'label':"lit_4119",'name':"@4119",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDB10,'size':4,'pad':0,'label':"lit_4120",'name':"@4120",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CBDB14,'size':42,'pad':0,'label':"d_a_obj_riverrock__stringBase0",'name':"@stringBase0",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"StringBase"},
	{'addr':0x80CBDB40,'size':4,'pad':0,'label':"l_arcName",'name':"l_arcName",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CBDB44,'size':32,'pad':0,'label':"l_daObjRIVERROCK_Method",'name':"l_daObjRIVERROCK_Method",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CBDB64,'size':48,'pad':0,'label':"g_profile_Obj_RIVERROCK",'name':"g_profile_Obj_RIVERROCK",'lib':-1,'tu':3,'section':5,'class_template':False,'static':False,'is_reachable':False,'r':[0,0,1],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CBDB94,'size':12,'pad':0,'label':"__vt__8cM3dGCyl",'name':"__vt__8cM3dGCyl",'lib':-1,'tu':3,'section':5,'class_template':False,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CBDBA0,'size':12,'pad':0,'label':"__vt__8cM3dGAab",'name':"__vt__8cM3dGAab",'lib':-1,'tu':3,'section':5,'class_template':False,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CBDBAC,'size':40,'pad':0,'label':"__vt__16daObjRIVERROCK_c",'name':"__vt__16daObjRIVERROCK_c",'lib':-1,'tu':3,'section':5,'class_template':False,'static':False,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CBDBD4,'size':12,'pad':0,'label':"__vt__20daObjRIVERROCK_HIO_c",'name':"__vt__20daObjRIVERROCK_HIO_c",'lib':-1,'tu':3,'section':5,'class_template':False,'static':False,'is_reachable':True,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CBDBE0,'size':4,'pad':4,'label':"__global_destructor_chain",'name':"__global_destructor_chain",'lib':-1,'tu':2,'section':3,'class_template':False,'static':True,'is_reachable':True,'r':[2,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CBDBE8,'size':4,'pad':0,'label':"data_80CBDBE8",'name':None,'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CBDBEC,'size':12,'pad':0,'label':"lit_3626",'name':"@3626",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':True,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CBDBF8,'size':16,'pad':0,'label':"l_HIO",'name':"l_HIO",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':True,'r':[4,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
]

# Names
SYMBOL_NAMES = {
	"_prolog":0,
	"_epilog":1,
	"_unresolved":2,
	"__register_global_object":3,
	"__destroy_global_chain":4,
	"__ct__20daObjRIVERROCK_HIO_cFv":5,
	"initCcCylinder__16daObjRIVERROCK_cFv":6,
	"SetCcCyl__16daObjRIVERROCK_cFv":7,
	"daObjRIVERROCK_Create__FP10fopAc_ac_c":8,
	"daObjRIVERROCK_Delete__FP16daObjRIVERROCK_c":9,
	"BreakWaitAction__16daObjRIVERROCK_cFv":10,
	"CheckBG__16daObjRIVERROCK_cFv":11,
	"BreakMoveAction__16daObjRIVERROCK_cFv":12,
	"BrokenAction__16daObjRIVERROCK_cFv":13,
	"BreakAction__16daObjRIVERROCK_cFv":14,
	"Action__16daObjRIVERROCK_cFv":15,
	"BreakSet__16daObjRIVERROCK_cFv":16,
	"WaitAction__16daObjRIVERROCK_cFv":17,
	"setBaseMtx__16daObjRIVERROCK_cFv":18,
	"daObjRIVERROCK_Draw__FP16daObjRIVERROCK_c":19,
	"daObjRIVERROCK_Execute__FP16daObjRIVERROCK_c":20,
	"CreateHeap__16daObjRIVERROCK_cFv":21,
	"create__16daObjRIVERROCK_cFv":22,
	"__dt__8cM3dGCylFv":23,
	"__dt__8cM3dGAabFv":24,
	"daObjRIVERROCK_IsDelete__FP16daObjRIVERROCK_c":25,
	"Create__16daObjRIVERROCK_cFv":26,
	"Execute__16daObjRIVERROCK_cFPPA3_A4_f":27,
	"Draw__16daObjRIVERROCK_cFv":28,
	"Delete__16daObjRIVERROCK_cFv":29,
	"__dt__20daObjRIVERROCK_HIO_cFv":30,
	"__sinit_d_a_obj_riverrock_cpp":31,
	"_ctors":32,
	"_dtors":33,
	"lit_3631":34,
	"ccCylSrc":35,
	"lit_3642":36,
	"lit_3669":37,
	"lit_3742":38,
	"lit_3743":39,
	"lit_3744":40,
	"lit_3745":41,
	"lit_3746":42,
	"lit_3747":43,
	"lit_3748":44,
	"lit_3749":45,
	"lit_3758":46,
	"lit_3861":47,
	"lit_3862":48,
	"lit_3895":49,
	"lit_3896":50,
	"lit_4026":51,
	"lit_4027":52,
	"lit_4028":53,
	"lit_4029":54,
	"lit_4030":55,
	"lit_4031":56,
	"lit_4032":57,
	"lit_4034":58,
	"lit_4119":59,
	"lit_4120":60,
	"d_a_obj_riverrock__stringBase0":61,
	"l_arcName":62,
	"l_daObjRIVERROCK_Method":63,
	"g_profile_Obj_RIVERROCK":64,
	"__vt__8cM3dGCyl":65,
	"__vt__8cM3dGAab":66,
	"__vt__16daObjRIVERROCK_c":67,
	"__vt__20daObjRIVERROCK_HIO_c":68,
	"__global_destructor_chain":69,
	"data_80CBDBE8":70,
	"lit_3626":71,
	"l_HIO":72,
}

