#
# Generate By: dol2asm
# Module: 539
#

# Libraries
LIBRARIES = [
	"d/a/obj/d_a_obj_lv5FloorBoard",
]

# Translation Units
TRANSLATION_UNITS = [
	"executor",
	"unknown_translation_unit_ctors",
	"global_destructor_chain",
	"d_a_obj_lv5FloorBoard",
]

# Sections
SECTIONS = [
	".text",
	".ctors",
	".dtors",
	".bss",
	".rodata",
	".data",
]

# Symbols
SYMBOLS = [
	{'addr':0x80C6A520,'size':44,'pad':0,'label':"_prolog",'name':"_prolog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6A54C,'size':44,'pad':0,'label':"_epilog",'name':"_epilog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6A578,'size':32,'pad':0,'label':"_unresolved",'name':"_unresolved",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6A598,'size':28,'pad':0,'label':"__register_global_object",'name':"__register_global_object",'lib':-1,'tu':2,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6A5B4,'size':88,'pad':0,'label':"__destroy_global_chain",'name':"__destroy_global_chain",'lib':-1,'tu':2,'section':0,'class_template':None,'static':False,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6A60C,'size':76,'pad':0,'label':"__ct__16daFlorBoad_HIO_cFv",'name':"__ct__16daFlorBoad_HIO_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':True,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6A658,'size':92,'pad':0,'label':"__dt__18fOpAcm_HIO_entry_cFv",'name':"__dt__18fOpAcm_HIO_entry_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':True,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6A6B4,'size':72,'pad':0,'label':"__dt__14mDoHIO_entry_cFv",'name':"__dt__14mDoHIO_entry_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':True,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6A6FC,'size':136,'pad':0,'label':"setBaseMtx__12daFlorBoad_cFv",'name':"setBaseMtx__12daFlorBoad_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6A784,'size':108,'pad':0,'label':"CreateHeap__12daFlorBoad_cFv",'name':"CreateHeap__12daFlorBoad_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6A7F0,'size':464,'pad':0,'label':"create__12daFlorBoad_cFv",'name':"create__12daFlorBoad_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6A9C0,'size':72,'pad':0,'label':"__dt__8cM3dGCylFv",'name':"__dt__8cM3dGCylFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6AA08,'size':72,'pad':0,'label':"__dt__8cM3dGAabFv",'name':"__dt__8cM3dGAabFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6AA50,'size':92,'pad':0,'label':"__dt__10dCcD_GSttsFv",'name':"__dt__10dCcD_GSttsFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6AAAC,'size':88,'pad':0,'label':"Execute__12daFlorBoad_cFPPA3_A4_f",'name':"Execute__12daFlorBoad_cFPPA3_A4_f",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6AB04,'size':140,'pad':0,'label':"procMain__12daFlorBoad_cFv",'name':"procMain__12daFlorBoad_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6AB90,'size':28,'pad':0,'label':"init_modeWait__12daFlorBoad_cFv",'name':"init_modeWait__12daFlorBoad_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6ABAC,'size':240,'pad':0,'label':"modeWait__12daFlorBoad_cFv",'name':"modeWait__12daFlorBoad_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6AC9C,'size':164,'pad':0,'label':"init_modeBreak__12daFlorBoad_cFv",'name':"init_modeBreak__12daFlorBoad_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6AD40,'size':368,'pad':0,'label':"modeBreak__12daFlorBoad_cFv",'name':"modeBreak__12daFlorBoad_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6AEB0,'size':164,'pad':0,'label':"Draw__12daFlorBoad_cFv",'name':"Draw__12daFlorBoad_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6AF54,'size':48,'pad':0,'label':"Delete__12daFlorBoad_cFv",'name':"Delete__12daFlorBoad_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6AF84,'size':44,'pad':0,'label':"daFlorBoad_Draw__FP12daFlorBoad_c",'name':"daFlorBoad_Draw__FP12daFlorBoad_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6AFB0,'size':32,'pad':0,'label':"daFlorBoad_Execute__FP12daFlorBoad_c",'name':"daFlorBoad_Execute__FP12daFlorBoad_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6AFD0,'size':32,'pad':0,'label':"daFlorBoad_Delete__FP12daFlorBoad_c",'name':"daFlorBoad_Delete__FP12daFlorBoad_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6AFF0,'size':32,'pad':0,'label':"daFlorBoad_Create__FP10fopAc_ac_c",'name':"daFlorBoad_Create__FP10fopAc_ac_c",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6B010,'size':72,'pad':0,'label':"__dt__10cCcD_GSttsFv",'name':"__dt__10cCcD_GSttsFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6B058,'size':108,'pad':0,'label':"__dt__16daFlorBoad_HIO_cFv",'name':"__dt__16daFlorBoad_HIO_cFv",'lib':-1,'tu':3,'section':0,'class_template':False,'static':True,'is_reachable':True,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80C6B0C4,'size':112,'pad':0,'label':"__sinit_d_a_obj_lv5FloorBoard_cpp",'name':"__sinit_d_a_obj_lv5FloorBoard_cpp",'lib':-1,'tu':3,'section':0,'class_template':None,'static':False,'is_reachable':False,'r':[0,1,0],'sh':[0,0,0],'type':"SInitFunction"},
	{'addr':0x80C6B134,'size':8,'pad':0,'label':"_ctors",'name':"_ctors",'lib':-1,'tu':1,'section':1,'class_template':False,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80C6B13C,'size':12,'pad':0,'label':"_dtors",'name':"_dtors",'lib':-1,'tu':2,'section':2,'class_template':False,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80C6B148,'size':4,'pad':0,'label':"lit_3656",'name':"@3656",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':True,'r':[4,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80C6B14C,'size':48,'pad':0,'label':"mCcDObjInfo__12daFlorBoad_c",'name':"mCcDObjInfo__12daFlorBoad_c",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':True,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80C6B17C,'size':4,'pad':0,'label':"lit_3870",'name':"@3870",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80C6B180,'size':4,'pad':0,'label':"lit_3871",'name':"@3871",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80C6B184,'size':4,'pad':0,'label':"lit_3872",'name':"@3872",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80C6B188,'size':4,'pad':0,'label':"lit_3891",'name':"@3891",'lib':-1,'tu':3,'section':4,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80C6B18C,'size':9,'pad':0,'label':"d_a_obj_lv5FloorBoard__stringBase0",'name':"@stringBase0",'lib':-1,'tu':3,'section':4,'class_template':False,'static':False,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"StringBase"},
	{'addr':0x80C6B198,'size':12,'pad':0,'label':"cNullVec__6Z2Calc",'name':"cNullVec__6Z2Calc",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80C6B1A4,'size':4,'pad':16,'label':"lit_1787",'name':"@1787",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80C6B1B8,'size':68,'pad':0,'label':"mCcDCyl__12daFlorBoad_c",'name':"mCcDCyl__12daFlorBoad_c",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':True,'r':[2,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80C6B1FC,'size':12,'pad':0,'label':"lit_3839",'name':"@3839",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80C6B208,'size':12,'pad':0,'label':"lit_3840",'name':"@3840",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80C6B214,'size':24,'pad':0,'label':"mode_proc",'name':"mode_proc$3838",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80C6B22C,'size':32,'pad':0,'label':"l_daFlorBoad_Method",'name':"l_daFlorBoad_Method",'lib':-1,'tu':3,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80C6B24C,'size':48,'pad':0,'label':"g_profile_Obj_Lv5FBoard",'name':"g_profile_Obj_Lv5FBoard",'lib':-1,'tu':3,'section':5,'class_template':False,'static':False,'is_reachable':False,'r':[0,0,1],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80C6B27C,'size':12,'pad':0,'label':"__vt__10cCcD_GStts",'name':"__vt__10cCcD_GStts",'lib':-1,'tu':3,'section':5,'class_template':False,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80C6B288,'size':12,'pad':0,'label':"__vt__10dCcD_GStts",'name':"__vt__10dCcD_GStts",'lib':-1,'tu':3,'section':5,'class_template':False,'static':False,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80C6B294,'size':12,'pad':0,'label':"__vt__8cM3dGCyl",'name':"__vt__8cM3dGCyl",'lib':-1,'tu':3,'section':5,'class_template':False,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80C6B2A0,'size':12,'pad':0,'label':"__vt__8cM3dGAab",'name':"__vt__8cM3dGAab",'lib':-1,'tu':3,'section':5,'class_template':False,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80C6B2AC,'size':40,'pad':0,'label':"__vt__12daFlorBoad_c",'name':"__vt__12daFlorBoad_c",'lib':-1,'tu':3,'section':5,'class_template':False,'static':False,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80C6B2D4,'size':12,'pad':0,'label':"__vt__16daFlorBoad_HIO_c",'name':"__vt__16daFlorBoad_HIO_c",'lib':-1,'tu':3,'section':5,'class_template':False,'static':False,'is_reachable':True,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80C6B2E0,'size':12,'pad':0,'label':"__vt__18fOpAcm_HIO_entry_c",'name':"__vt__18fOpAcm_HIO_entry_c",'lib':-1,'tu':3,'section':5,'class_template':False,'static':False,'is_reachable':True,'r':[3,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80C6B2EC,'size':12,'pad':0,'label':"__vt__14mDoHIO_entry_c",'name':"__vt__14mDoHIO_entry_c",'lib':-1,'tu':3,'section':5,'class_template':False,'static':False,'is_reachable':True,'r':[4,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80C6B2F8,'size':4,'pad':4,'label':"__global_destructor_chain",'name':"__global_destructor_chain",'lib':-1,'tu':2,'section':3,'class_template':False,'static':True,'is_reachable':True,'r':[2,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80C6B300,'size':12,'pad':0,'label':"lit_3647",'name':"@3647",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':True,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80C6B30C,'size':20,'pad':0,'label':"l_HIO",'name':"l_HIO",'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':True,'r':[2,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80C6B320,'size':4,'pad':0,'label':"data_80C6B320",'name':None,'lib':-1,'tu':3,'section':3,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
]

# Names
SYMBOL_NAMES = {
	"_prolog":0,
	"_epilog":1,
	"_unresolved":2,
	"__register_global_object":3,
	"__destroy_global_chain":4,
	"__ct__16daFlorBoad_HIO_cFv":5,
	"__dt__18fOpAcm_HIO_entry_cFv":6,
	"__dt__14mDoHIO_entry_cFv":7,
	"setBaseMtx__12daFlorBoad_cFv":8,
	"CreateHeap__12daFlorBoad_cFv":9,
	"create__12daFlorBoad_cFv":10,
	"__dt__8cM3dGCylFv":11,
	"__dt__8cM3dGAabFv":12,
	"__dt__10dCcD_GSttsFv":13,
	"Execute__12daFlorBoad_cFPPA3_A4_f":14,
	"procMain__12daFlorBoad_cFv":15,
	"init_modeWait__12daFlorBoad_cFv":16,
	"modeWait__12daFlorBoad_cFv":17,
	"init_modeBreak__12daFlorBoad_cFv":18,
	"modeBreak__12daFlorBoad_cFv":19,
	"Draw__12daFlorBoad_cFv":20,
	"Delete__12daFlorBoad_cFv":21,
	"daFlorBoad_Draw__FP12daFlorBoad_c":22,
	"daFlorBoad_Execute__FP12daFlorBoad_c":23,
	"daFlorBoad_Delete__FP12daFlorBoad_c":24,
	"daFlorBoad_Create__FP10fopAc_ac_c":25,
	"__dt__10cCcD_GSttsFv":26,
	"__dt__16daFlorBoad_HIO_cFv":27,
	"__sinit_d_a_obj_lv5FloorBoard_cpp":28,
	"_ctors":29,
	"_dtors":30,
	"lit_3656":31,
	"mCcDObjInfo__12daFlorBoad_c":32,
	"lit_3870":33,
	"lit_3871":34,
	"lit_3872":35,
	"lit_3891":36,
	"d_a_obj_lv5FloorBoard__stringBase0":37,
	"cNullVec__6Z2Calc":38,
	"lit_1787":39,
	"mCcDCyl__12daFlorBoad_c":40,
	"lit_3839":41,
	"lit_3840":42,
	"mode_proc":43,
	"l_daFlorBoad_Method":44,
	"g_profile_Obj_Lv5FBoard":45,
	"__vt__10cCcD_GStts":46,
	"__vt__10dCcD_GStts":47,
	"__vt__8cM3dGCyl":48,
	"__vt__8cM3dGAab":49,
	"__vt__12daFlorBoad_c":50,
	"__vt__16daFlorBoad_HIO_c":51,
	"__vt__18fOpAcm_HIO_entry_c":52,
	"__vt__14mDoHIO_entry_c":53,
	"__global_destructor_chain":54,
	"lit_3647":55,
	"l_HIO":56,
	"data_80C6B320":57,
}

