#
# Generate By: dol2asm
# Module: 640
#

# Libraries
LIBRARIES = [
	"d/a/obj/d_a_obj_swBallC",
]

# Translation Units
TRANSLATION_UNITS = [
	"executor",
	"unknown_translation_unit_ctors",
	"unknown_translation_unit_dtors",
	"unknown_translation_unit_bss",
	"d_a_obj_swBallC",
]

# Sections
SECTIONS = [
	".text",
	".ctors",
	".dtors",
	".bss",
	".rodata",
	".data",
]

# Symbols
SYMBOLS = [
	{'addr':0x80CF5B20,'size':44,'pad':0,'label':"_prolog",'name':"_prolog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF5B4C,'size':44,'pad':0,'label':"_epilog",'name':"_epilog",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF5B78,'size':32,'pad':0,'label':"_unresolved",'name':"_unresolved",'lib':-1,'tu':0,'section':0,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF5B98,'size':32,'pad':0,'label':"CheckCreateHeap__FP10fopAc_ac_c",'name':"CheckCreateHeap__FP10fopAc_ac_c",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF5BB8,'size':108,'pad':0,'label':"s_swb_sub__FPvPv",'name':"s_swb_sub__FPvPv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF5C24,'size':88,'pad':0,'label':"s_ballA_sub__FPvPv",'name':"s_ballA_sub__FPvPv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF5C7C,'size':88,'pad':0,'label':"s_ballB_sub__FPvPv",'name':"s_ballB_sub__FPvPv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF5CD4,'size':32,'pad':0,'label':"initBaseMtx__14daObjSwBallC_cFv",'name':"initBaseMtx__14daObjSwBallC_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF5CF4,'size':100,'pad':0,'label':"setBaseMtx__14daObjSwBallC_cFv",'name':"setBaseMtx__14daObjSwBallC_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF5D58,'size':416,'pad':0,'label':"Create__14daObjSwBallC_cFv",'name':"Create__14daObjSwBallC_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF5EF8,'size':300,'pad':0,'label':"CreateHeap__14daObjSwBallC_cFv",'name':"CreateHeap__14daObjSwBallC_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF6024,'size':72,'pad':0,'label':"__dt__12J3DFrameCtrlFv",'name':"__dt__12J3DFrameCtrlFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF606C,'size':180,'pad':0,'label':"create__14daObjSwBallC_cFv",'name':"create__14daObjSwBallC_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF6120,'size':36,'pad':0,'label':"execute__14daObjSwBallC_cFv",'name':"execute__14daObjSwBallC_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF6144,'size':188,'pad':0,'label':"event_proc_call__14daObjSwBallC_cFv",'name':"event_proc_call__14daObjSwBallC_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF6200,'size':156,'pad':0,'label':"actionWait__14daObjSwBallC_cFv",'name':"actionWait__14daObjSwBallC_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF629C,'size':168,'pad':0,'label':"actionOrderEvent__14daObjSwBallC_cFv",'name':"actionOrderEvent__14daObjSwBallC_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF6344,'size':172,'pad':0,'label':"actionEvent__14daObjSwBallC_cFv",'name':"actionEvent__14daObjSwBallC_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF63F0,'size':4,'pad':0,'label':"actionDead__14daObjSwBallC_cFv",'name':"actionDead__14daObjSwBallC_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReturnFunction"},
	{'addr':0x80CF63F4,'size':1060,'pad':0,'label':"demoProc__14daObjSwBallC_cFv",'name':"demoProc__14daObjSwBallC_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[4,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF6818,'size':112,'pad':0,'label':"setLightOnSwB__14daObjSwBallC_cFv",'name':"setLightOnSwB__14daObjSwBallC_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF6888,'size':112,'pad':0,'label':"setLightOffSwB__14daObjSwBallC_cFv",'name':"setLightOffSwB__14daObjSwBallC_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF68F8,'size':52,'pad':0,'label':"deleteLightBall__14daObjSwBallC_cFv",'name':"deleteLightBall__14daObjSwBallC_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF692C,'size':56,'pad':0,'label':"deleteLightBallA__14daObjSwBallC_cFv",'name':"deleteLightBallA__14daObjSwBallC_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF6964,'size':56,'pad':0,'label':"deleteLightBallB__14daObjSwBallC_cFv",'name':"deleteLightBallB__14daObjSwBallC_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF699C,'size':216,'pad':0,'label':"calcLightBallScale__14daObjSwBallC_cFv",'name':"calcLightBallScale__14daObjSwBallC_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF6A74,'size':392,'pad':0,'label':"draw__14daObjSwBallC_cFv",'name':"draw__14daObjSwBallC_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF6BFC,'size':52,'pad':0,'label':"_delete__14daObjSwBallC_cFv",'name':"_delete__14daObjSwBallC_cFv",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF6C30,'size':32,'pad':0,'label':"daObjSwBallC_Draw__FP14daObjSwBallC_c",'name':"daObjSwBallC_Draw__FP14daObjSwBallC_c",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF6C50,'size':32,'pad':0,'label':"daObjSwBallC_Execute__FP14daObjSwBallC_c",'name':"daObjSwBallC_Execute__FP14daObjSwBallC_c",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF6C70,'size':32,'pad':0,'label':"daObjSwBallC_Delete__FP14daObjSwBallC_c",'name':"daObjSwBallC_Delete__FP14daObjSwBallC_c",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF6C90,'size':32,'pad':0,'label':"daObjSwBallC_Create__FP14daObjSwBallC_c",'name':"daObjSwBallC_Create__FP14daObjSwBallC_c",'lib':-1,'tu':4,'section':0,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF6CB0,'size':28,'pad':0,'label':"func_80CF6CB0",'name':"cLib_calcTimer<Uc>__FPUc",'lib':-1,'tu':4,'section':0,'class_template':True,'static':False,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ASMFunction"},
	{'addr':0x80CF6CCC,'size':4,'pad':0,'label':"_ctors",'name':"_ctors",'lib':-1,'tu':1,'section':1,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80CF6CD0,'size':4,'pad':0,'label':"_dtors",'name':"_dtors",'lib':-1,'tu':2,'section':2,'class_template':None,'static':False,'is_reachable':True,'r':[0,1,0],'sh':[0,0,0],'type':"LinkerGenerated"},
	{'addr':0x80CF6CD4,'size':4,'pad':0,'label':"l_color",'name':"l_color",'lib':-1,'tu':4,'section':4,'class_template':None,'static':True,'is_reachable':False,'r':[3,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CF6CD8,'size':4,'pad':0,'label':"lit_3697",'name':"@3697",'lib':-1,'tu':4,'section':4,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80CF6CDC,'size':4,'pad':4,'label':"lit_3814",'name':"@3814",'lib':-1,'tu':4,'section':4,'class_template':None,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80CF6CE4,'size':8,'pad':0,'label':"lit_3816",'name':"@3816",'lib':-1,'tu':4,'section':4,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CF6CEC,'size':4,'pad':0,'label':"lit_3850",'name':"@3850",'lib':-1,'tu':4,'section':4,'class_template':None,'static':True,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CF6CF0,'size':4,'pad':0,'label':"lit_4109",'name':"@4109",'lib':-1,'tu':4,'section':4,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80CF6CF4,'size':4,'pad':0,'label':"lit_4110",'name':"@4110",'lib':-1,'tu':4,'section':4,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80CF6CF8,'size':4,'pad':0,'label':"lit_4111",'name':"@4111",'lib':-1,'tu':4,'section':4,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80CF6CFC,'size':4,'pad':0,'label':"lit_4175",'name':"@4175",'lib':-1,'tu':4,'section':4,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80CF6D00,'size':4,'pad':0,'label':"lit_4252",'name':"@4252",'lib':-1,'tu':4,'section':4,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80CF6D04,'size':4,'pad':0,'label':"lit_4253",'name':"@4253",'lib':-1,'tu':4,'section':4,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"FloatingPoint"},
	{'addr':0x80CF6D08,'size':135,'pad':0,'label':"d_a_obj_swBallC__stringBase0",'name':"@stringBase0",'lib':-1,'tu':4,'section':4,'class_template':None,'static':False,'is_reachable':False,'r':[5,0,0],'sh':[0,0,0],'type':"StringBase"},
	{'addr':0x80CF6D90,'size':12,'pad':0,'label':"cNullVec__6Z2Calc",'name':"cNullVec__6Z2Calc",'lib':-1,'tu':4,'section':5,'class_template':False,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CF6D9C,'size':4,'pad':16,'label':"lit_1787",'name':"@1787",'lib':-1,'tu':4,'section':5,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"Integer"},
	{'addr':0x80CF6DB0,'size':4,'pad':0,'label':"l_arcName",'name':"l_arcName",'lib':-1,'tu':4,'section':5,'class_template':None,'static':True,'is_reachable':False,'r':[4,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CF6DB4,'size':4,'pad':0,'label':"l_evName",'name':"l_evName",'lib':-1,'tu':4,'section':5,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CF6DB8,'size':4,'pad':0,'label':"l_staffName",'name':"l_staffName",'lib':-1,'tu':4,'section':5,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CF6DBC,'size':12,'pad':0,'label':"lit_3896",'name':"@3896",'lib':-1,'tu':4,'section':5,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CF6DC8,'size':12,'pad':0,'label':"lit_3897",'name':"@3897",'lib':-1,'tu':4,'section':5,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CF6DD4,'size':12,'pad':0,'label':"lit_3898",'name':"@3898",'lib':-1,'tu':4,'section':5,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CF6DE0,'size':12,'pad':0,'label':"lit_3899",'name':"@3899",'lib':-1,'tu':4,'section':5,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CF6DEC,'size':48,'pad':0,'label':"l_func",'name':"l_func$3895",'lib':-1,'tu':4,'section':5,'class_template':None,'static':True,'is_reachable':False,'r':[0,0,0],'sh':[0,0,0],'type':"ArbitraryData"},
	{'addr':0x80CF6E1C,'size':52,'pad':0,'label':"action_table",'name':"action_table$3966",'lib':-1,'tu':4,'section':5,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CF6E50,'size':52,'pad':0,'label':"lit_4113",'name':"@4113",'lib':-1,'tu':4,'section':5,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CF6E84,'size':52,'pad':0,'label':"lit_4112",'name':"@4112",'lib':-1,'tu':4,'section':5,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CF6EB8,'size':32,'pad':0,'label':"l_daObjSwBallC_Method",'name':"l_daObjSwBallC_Method",'lib':-1,'tu':4,'section':5,'class_template':None,'static':True,'is_reachable':False,'r':[1,0,0],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CF6ED8,'size':48,'pad':0,'label':"g_profile_Obj_SwBallC",'name':"g_profile_Obj_SwBallC",'lib':-1,'tu':4,'section':5,'class_template':None,'static':False,'is_reachable':False,'r':[0,0,1],'sh':[0,0,0],'type':"ReferenceArray"},
	{'addr':0x80CF6F08,'size':12,'pad':0,'label':"__vt__12J3DFrameCtrl",'name':"__vt__12J3DFrameCtrl",'lib':-1,'tu':4,'section':5,'class_template':None,'static':False,'is_reachable':False,'r':[2,0,0],'sh':[0,0,0],'type':"VirtualTable"},
	{'addr':0x80CF6F18,'size':4,'pad':0,'label':"data_80CF6F18",'name':None,'lib':-1,'tu':3,'section':3,'class_template':None,'static':False,'is_reachable':False,'r':[0,1,0],'sh':[0,0,0],'type':"ArbitraryData"},
]

# Names
SYMBOL_NAMES = {
	"_prolog":0,
	"_epilog":1,
	"_unresolved":2,
	"CheckCreateHeap__FP10fopAc_ac_c":3,
	"s_swb_sub__FPvPv":4,
	"s_ballA_sub__FPvPv":5,
	"s_ballB_sub__FPvPv":6,
	"initBaseMtx__14daObjSwBallC_cFv":7,
	"setBaseMtx__14daObjSwBallC_cFv":8,
	"Create__14daObjSwBallC_cFv":9,
	"CreateHeap__14daObjSwBallC_cFv":10,
	"__dt__12J3DFrameCtrlFv":11,
	"create__14daObjSwBallC_cFv":12,
	"execute__14daObjSwBallC_cFv":13,
	"event_proc_call__14daObjSwBallC_cFv":14,
	"actionWait__14daObjSwBallC_cFv":15,
	"actionOrderEvent__14daObjSwBallC_cFv":16,
	"actionEvent__14daObjSwBallC_cFv":17,
	"actionDead__14daObjSwBallC_cFv":18,
	"demoProc__14daObjSwBallC_cFv":19,
	"setLightOnSwB__14daObjSwBallC_cFv":20,
	"setLightOffSwB__14daObjSwBallC_cFv":21,
	"deleteLightBall__14daObjSwBallC_cFv":22,
	"deleteLightBallA__14daObjSwBallC_cFv":23,
	"deleteLightBallB__14daObjSwBallC_cFv":24,
	"calcLightBallScale__14daObjSwBallC_cFv":25,
	"draw__14daObjSwBallC_cFv":26,
	"_delete__14daObjSwBallC_cFv":27,
	"daObjSwBallC_Draw__FP14daObjSwBallC_c":28,
	"daObjSwBallC_Execute__FP14daObjSwBallC_c":29,
	"daObjSwBallC_Delete__FP14daObjSwBallC_c":30,
	"daObjSwBallC_Create__FP14daObjSwBallC_c":31,
	"func_80CF6CB0":32,
	"_ctors":33,
	"_dtors":34,
	"l_color":35,
	"lit_3697":36,
	"lit_3814":37,
	"lit_3816":38,
	"lit_3850":39,
	"lit_4109":40,
	"lit_4110":41,
	"lit_4111":42,
	"lit_4175":43,
	"lit_4252":44,
	"lit_4253":45,
	"d_a_obj_swBallC__stringBase0":46,
	"cNullVec__6Z2Calc":47,
	"lit_1787":48,
	"l_arcName":49,
	"l_evName":50,
	"l_staffName":51,
	"lit_3896":52,
	"lit_3897":53,
	"lit_3898":54,
	"lit_3899":55,
	"l_func":56,
	"action_table":57,
	"lit_4113":58,
	"lit_4112":59,
	"l_daObjSwBallC_Method":60,
	"g_profile_Obj_SwBallC":61,
	"__vt__12J3DFrameCtrl":62,
	"data_80CF6F18":63,
}

