// 
// Generated By: dol2asm
// Translation Unit: unknown_translation_unit_dtors
// 

#include "dol2asm.h"
#include "dolphin/types.h"
#include "rel/d/a/kytag/d_a_kytag15/unknown_translation_unit_dtors.h"

// 
// Forward References:
// 


extern u8 const data_80860B3C[4];

// 
// External References:
// 



// 
// Declarations:
// 

/* ############################################################################################## */
/* 80860B3C-80860B40 0004+00 s=0 e=1 z=0  None .dtors     None                                                         */
u8 const data_80860B3C[4] = {
	0x00, 0x00, 0x00, 0x00,
};

