// 
// Generated By: dol2asm
// Translation Unit: executor
// 

#include "dol2asm.h"
#include "dolphin/types.h"
#include "rel/d/a/npc/d_a_npc_yamid/executor.h"

// 
// Forward References:
// 


// False False
extern "C" void _prolog();
// False False
extern "C" void _epilog();
// False False
extern "C" void _unresolved();

// 
// External References:
// 


// False False
//  void False
extern "C" void ModuleProlog();
// False False
//  void False
extern "C" void ModuleEpilog();
// False False
extern "C" void ModuleUnresolved();
// False False
extern "C" void ModuleConstructorsX();
// False False
extern "C" void ModuleDestructorsX();
extern void* const data_80B46038[2];
SECTION_DTORS10 extern void* const __destroy_global_chain_reference;

// 
// Declarations:
// 

/* 80B42E60-80B42E8C 002C+00 s=0 e=0 z=0  None .text      _prolog                                                      */
//	80B42E6C: 80B46038 (data_80B46038)
//	80B42E70: 80B46038 (data_80B46038)
//	80B42E74: 8026314C (ModuleConstructorsX)
//	80B42E78: 80263088 (ModuleProlog)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
// False False
extern "C" asm void _prolog() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_yamid/executor/_prolog.s"
}
#pragma pop


/* 80B42E8C-80B42EB8 002C+00 s=0 e=0 z=0  None .text      _epilog                                                      */
//	80B42E98: 8026308C (ModuleEpilog)
//	80B42E9C: 80B46040 (__destroy_global_chain_reference)
//	80B42EA0: 80B46040 (__destroy_global_chain_reference)
//	80B42EA4: 80263190 (ModuleDestructorsX)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
// False False
extern "C" asm void _epilog() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_yamid/executor/_epilog.s"
}
#pragma pop


/* 80B42EB8-80B42ED8 0020+00 s=0 e=0 z=0  None .text      _unresolved                                                  */
//	80B42EC4: 80263090 (ModuleUnresolved)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
// False False
extern "C" asm void _unresolved() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_yamid/executor/_unresolved.s"
}
#pragma pop


