#ifndef RES_BESU_TW_H
#define RES_BESU_TW_H

enum dRes_INDEX_BESU_TW {
    /* BCK  */
    dRes_INDEX_BESU_TW_BCK_BESU_DEMO_FEAR_e=0x5,
    dRes_INDEX_BESU_TW_BCK_BESU_DEMO_WAIT_e=0x6,
    dRes_INDEX_BESU_TW_BCK_BESU_F_DEMO_FEAR_e=0x7,
    dRes_INDEX_BESU_TW_BCK_BESU_F_DEMO_WAIT_e=0x8,
    /* BMDR */
    dRes_INDEX_BESU_TW_BMD_BESU_TW_e=0xB,
    /* BTP  */
    dRes_INDEX_BESU_TW_BTP_BESU_F_DEMO_FEAR_e=0xE,
    dRes_INDEX_BESU_TW_BTP_BESU_F_DEMO_WAIT_e=0xF,
};

enum dRes_ID_BESU_TW {
    /* BCK  */
    dRes_ID_BESU_TW_BCK_BESU_DEMO_FEAR_e=0x5,
    dRes_ID_BESU_TW_BCK_BESU_DEMO_WAIT_e=0x6,
    dRes_ID_BESU_TW_BCK_BESU_F_DEMO_FEAR_e=0x7,
    dRes_ID_BESU_TW_BCK_BESU_F_DEMO_WAIT_e=0x8,
    /* BMDR */
    dRes_ID_BESU_TW_BMD_BESU_TW_e=0xB,
    /* BTP  */
    dRes_ID_BESU_TW_BTP_BESU_F_DEMO_FEAR_e=0xE,
    dRes_ID_BESU_TW_BTP_BESU_F_DEMO_WAIT_e=0xF,
};

enum BESU_TW_JNT {
    BESU_TW_JNT_CENTER_e=0x0,
    BESU_TW_JNT_BACKBONE1_e=0x1,
    BESU_TW_JNT_BACKBONE2_e=0x2,
    BESU_TW_JNT_NECK_e=0x3,
    BESU_TW_JNT_HEAD_e=0x4,
    BESU_TW_JNT_CHIN_e=0x5,
    BESU_TW_JNT_MOUTH_e=0x6,
    BESU_TW_JNT_SHOULDERL_e=0x7,
    BESU_TW_JNT_ARML1_e=0x8,
    BESU_TW_JNT_ARML2_e=0x9,
    BESU_TW_JNT_HANDL_e=0xA,
    BESU_TW_JNT_SHOULDERR_e=0xB,
    BESU_TW_JNT_ARMR1_e=0xC,
    BESU_TW_JNT_ARMR2_e=0xD,
    BESU_TW_JNT_HANDR_e=0xE,
    BESU_TW_JNT_WAIST_e=0xF,
    BESU_TW_JNT_LEGL1_e=0x10,
    BESU_TW_JNT_LEGL2_e=0x11,
    BESU_TW_JNT_FOOTL_e=0x12,
    BESU_TW_JNT_LEGR1_e=0x13,
    BESU_TW_JNT_LEGR2_e=0x14,
    BESU_TW_JNT_FOOTR_e=0x15,
};

#endif /* !RES_BESU_TW_H */