#ifndef RES_BESU3_H
#define RES_BESU3_H

enum dRes_INDEX_BESU3 {
    /* BCK  */
    dRes_INDEX_BESU3_BCK_BESU3_F_WORRY_e=0x7,
    dRes_INDEX_BESU3_BCK_BESU3_FH_WORRY_e=0x8,
    dRes_INDEX_BESU3_BCK_BESU_F_SUPRISE_e=0x9,
    dRes_INDEX_BESU3_BCK_BESU_FH_SURPRISE_e=0xA,
    dRes_INDEX_BESU3_BCK_BESU_SURPRISE_e=0xB,
    /* BMDR */
    dRes_INDEX_BESU3_BMD_BESU3_e=0xE,
    /* BTK  */
    dRes_INDEX_BESU3_BTK_BESU_SURPRISE_e=0x11,
    /* BTP  */
    dRes_INDEX_BESU3_BTP_BESU3_e=0x14,
    dRes_INDEX_BESU3_BTP_BESU3_F_SURPRISE_e=0x15,
    dRes_INDEX_BESU3_BTP_BESU3_F_WORRY_e=0x16,
    dRes_INDEX_BESU3_BTP_BESU3_FH_SURPRISE_e=0x17,
    dRes_INDEX_BESU3_BTP_BESU3_FH_WORRY_e=0x18,
    /* EVT  */
    dRes_INDEX_BESU3_DAT_EVENT_LIST_e=0x1B,
};

enum dRes_ID_BESU3 {
    /* BCK  */
    dRes_ID_BESU3_BCK_BESU3_F_WORRY_e=0x7,
    dRes_ID_BESU3_BCK_BESU3_FH_WORRY_e=0x8,
    dRes_ID_BESU3_BCK_BESU_F_SUPRISE_e=0x9,
    dRes_ID_BESU3_BCK_BESU_FH_SURPRISE_e=0xA,
    dRes_ID_BESU3_BCK_BESU_SURPRISE_e=0xB,
    /* BMDR */
    dRes_ID_BESU3_BMD_BESU3_e=0xE,
    /* BTK  */
    dRes_ID_BESU3_BTK_BESU_SURPRISE_e=0x11,
    /* BTP  */
    dRes_ID_BESU3_BTP_BESU3_e=0x14,
    dRes_ID_BESU3_BTP_BESU3_F_SURPRISE_e=0x15,
    dRes_ID_BESU3_BTP_BESU3_F_WORRY_e=0x16,
    dRes_ID_BESU3_BTP_BESU3_FH_SURPRISE_e=0x17,
    dRes_ID_BESU3_BTP_BESU3_FH_WORRY_e=0x18,
    /* EVT  */
    dRes_ID_BESU3_DAT_EVENT_LIST_e=0x1B,
};

enum BESU3_JNT {
    BESU3_JNT_CENTER_e=0x0,
    BESU3_JNT_BACKBONE1_e=0x1,
    BESU3_JNT_BACKBONE2_e=0x2,
    BESU3_JNT_NECK_e=0x3,
    BESU3_JNT_HEAD_e=0x4,
    BESU3_JNT_CHIN_e=0x5,
    BESU3_JNT_MOUTH_e=0x6,
    BESU3_JNT_SHOULDERL_e=0x7,
    BESU3_JNT_ARML1_e=0x8,
    BESU3_JNT_ARML2_e=0x9,
    BESU3_JNT_HANDL_e=0xA,
    BESU3_JNT_SHOULDERR_e=0xB,
    BESU3_JNT_ARMR1_e=0xC,
    BESU3_JNT_ARMR2_e=0xD,
    BESU3_JNT_HANDR_e=0xE,
    BESU3_JNT_WAIST_e=0xF,
    BESU3_JNT_LEGL1_e=0x10,
    BESU3_JNT_LEGL2_e=0x11,
    BESU3_JNT_FOOTL_e=0x12,
    BESU3_JNT_LEGR1_e=0x13,
    BESU3_JNT_LEGR2_e=0x14,
    BESU3_JNT_FOOTR_e=0x15,
};

#endif /* !RES_BESU3_H */