#ifndef RES_COACH_H
#define RES_COACH_H

enum dRes_INDEX_COACH {
    /* BCK  */
    dRes_INDEX_COACH_BCK_HU_JUMP_END_e=0x9,
    dRes_INDEX_COACH_BCK_HU_JUMP_MIDDLE_e=0xA,
    dRes_INDEX_COACH_BCK_HU_JUMP_START_e=0xB,
    dRes_INDEX_COACH_BCK_HU_LASH_e=0xC,
    dRes_INDEX_COACH_BCK_HU_RUN_FAST_e=0xD,
    dRes_INDEX_COACH_BCK_HU_RUN_SLOW_e=0xE,
    dRes_INDEX_COACH_BCK_HU_WAIT_01_e=0xF,
    dRes_INDEX_COACH_BCK_HU_WALK_FAST_e=0x10,
    dRes_INDEX_COACH_BCK_HU_WALK_SLOW_e=0x11,
    dRes_INDEX_COACH_BCK_THEB_BEND_TURN_e=0x12,
    dRes_INDEX_COACH_BCK_THEB_BEND_WAIT_e=0x13,
    dRes_INDEX_COACH_BCK_THEB_F_BEND_TURN_e=0x14,
    dRes_INDEX_COACH_BCK_THEB_F_TALK_A_e=0x15,
    dRes_INDEX_COACH_BCK_THEB_F_TALK_B_e=0x16,
    dRes_INDEX_COACH_BCK_THEB_F_TALK_C_e=0x17,
    dRes_INDEX_COACH_BCK_THEB_FH_BEND_WAIT_e=0x18,
    dRes_INDEX_COACH_BCK_THEB_FH_TALK_B_e=0x19,
    dRes_INDEX_COACH_BCK_THEB_FH_TALK_C_e=0x1A,
    dRes_INDEX_COACH_BCK_THEB_SIT_e=0x1B,
    dRes_INDEX_COACH_BCK_THEB_SIT_B_e=0x1C,
    dRes_INDEX_COACH_BCK_THEB_WHIP_e=0x1D,
    dRes_INDEX_COACH_BCK_THEB_WHIP_B_e=0x1E,
    dRes_INDEX_COACH_BCK_YELIA_BEND_e=0x1F,
    dRes_INDEX_COACH_BCK_YELIA_WAIT_e=0x20,
    /* BMDR */
    dRes_INDEX_COACH_BMD_COACH_e=0x23,
    dRes_INDEX_COACH_BMD_HARNESS_e=0x24,
    dRes_INDEX_COACH_BMD_HORSE_e=0x25,
    dRes_INDEX_COACH_BMD_THEB_e=0x26,
    dRes_INDEX_COACH_BMD_YELIA_e=0x27,
    /* BTK  */
    dRes_INDEX_COACH_BTK_THEB_e=0x2A,
    /* BTP  */
    dRes_INDEX_COACH_BTP_HU_EYE_e=0x2D,
    dRes_INDEX_COACH_BTP_THEB_e=0x2E,
    dRes_INDEX_COACH_BTP_THEB_F_TALK_A_e=0x2F,
    /* DZB  */
    dRes_INDEX_COACH_DZB_COACH_e=0x32,
    dRes_INDEX_COACH_DZB_HARNESS_e=0x33,
    /* EVT  */
    dRes_INDEX_COACH_DAT_EVENT_LIST_e=0x36,
    /* TEX  */
    dRes_INDEX_COACH_BTI_TAZUNA_e=0x39,
};

enum dRes_ID_COACH {
    /* BCK  */
    dRes_ID_COACH_BCK_HU_JUMP_END_e=0x9,
    dRes_ID_COACH_BCK_HU_JUMP_MIDDLE_e=0xA,
    dRes_ID_COACH_BCK_HU_JUMP_START_e=0xB,
    dRes_ID_COACH_BCK_HU_LASH_e=0xC,
    dRes_ID_COACH_BCK_HU_RUN_FAST_e=0xD,
    dRes_ID_COACH_BCK_HU_RUN_SLOW_e=0xE,
    dRes_ID_COACH_BCK_HU_WAIT_01_e=0xF,
    dRes_ID_COACH_BCK_HU_WALK_FAST_e=0x10,
    dRes_ID_COACH_BCK_HU_WALK_SLOW_e=0x11,
    dRes_ID_COACH_BCK_THEB_BEND_TURN_e=0x12,
    dRes_ID_COACH_BCK_THEB_BEND_WAIT_e=0x13,
    dRes_ID_COACH_BCK_THEB_F_BEND_TURN_e=0x14,
    dRes_ID_COACH_BCK_THEB_F_TALK_A_e=0x15,
    dRes_ID_COACH_BCK_THEB_F_TALK_B_e=0x16,
    dRes_ID_COACH_BCK_THEB_F_TALK_C_e=0x17,
    dRes_ID_COACH_BCK_THEB_FH_BEND_WAIT_e=0x18,
    dRes_ID_COACH_BCK_THEB_FH_TALK_B_e=0x19,
    dRes_ID_COACH_BCK_THEB_FH_TALK_C_e=0x1A,
    dRes_ID_COACH_BCK_THEB_SIT_e=0x1B,
    dRes_ID_COACH_BCK_THEB_SIT_B_e=0x1C,
    dRes_ID_COACH_BCK_THEB_WHIP_e=0x1D,
    dRes_ID_COACH_BCK_THEB_WHIP_B_e=0x1E,
    dRes_ID_COACH_BCK_YELIA_BEND_e=0x1F,
    dRes_ID_COACH_BCK_YELIA_WAIT_e=0x20,
    /* BMDR */
    dRes_ID_COACH_BMD_COACH_e=0x23,
    dRes_ID_COACH_BMD_HARNESS_e=0x24,
    dRes_ID_COACH_BMD_HORSE_e=0x25,
    dRes_ID_COACH_BMD_THEB_e=0x26,
    dRes_ID_COACH_BMD_YELIA_e=0x27,
    /* BTK  */
    dRes_ID_COACH_BTK_THEB_e=0x2A,
    /* BTP  */
    dRes_ID_COACH_BTP_HU_EYE_e=0x2D,
    dRes_ID_COACH_BTP_THEB_e=0x2E,
    dRes_ID_COACH_BTP_THEB_F_TALK_A_e=0x2F,
    /* DZB  */
    dRes_ID_COACH_DZB_COACH_e=0x32,
    dRes_ID_COACH_DZB_HARNESS_e=0x33,
    /* EVT  */
    dRes_ID_COACH_DAT_EVENT_LIST_e=0x36,
    /* TEX  */
    dRes_ID_COACH_BTI_TAZUNA_e=0x39,
};

enum COACH_JNT {
    COACH_JNT_CENTER_e=0x0,
    COACH_JNT_B_L_WHEEL_e=0x1,
    COACH_JNT_B_R_WHEEL_e=0x2,
    COACH_JNT_BG_LOC_e=0x3,
    COACH_JNT_BODY_e=0x4,
    COACH_JNT_TERUMA_LOC_e=0x5,
    COACH_JNT_YELIA_LOC_e=0x6,
};

enum HARNESS_JNT {
    HARNESS_JNT_CENTER_e=0x0,
    HARNESS_JNT_AXLE_e=0x1,
    HARNESS_JNT_F_L_WHEEL_e=0x2,
    HARNESS_JNT_F_R_WHEEL_e=0x3,
    HARNESS_JNT_BS_LOC_e=0x4,
    HARNESS_JNT_HU_LOC_e=0x5,
};

enum HORSE_JNT {
    HORSE_JNT_CENTER_e=0x0,
    HORSE_JNT_BACKBONE2_e=0x1,
    HORSE_JNT_BACKBONE1_e=0x2,
    HORSE_JNT_F_L_LEG1_e=0x3,
    HORSE_JNT_F_L_LEG2_e=0x4,
    HORSE_JNT_F_L_LEG3_e=0x5,
    HORSE_JNT_F_L_LEG4_e=0x6,
    HORSE_JNT_F_R_LEG1_e=0x7,
    HORSE_JNT_F_R_LEG2_e=0x8,
    HORSE_JNT_F_R_LEG3_e=0x9,
    HORSE_JNT_F_R_LEG4_e=0xA,
    HORSE_JNT_BG_LOC_e=0xB,
    HORSE_JNT_NECK1_e=0xC,
    HORSE_JNT_NECK2_e=0xD,
    HORSE_JNT_HEAD_e=0xE,
    HORSE_JNT_MOUTH1_e=0xF,
    HORSE_JNT_MOUTH2_e=0x10,
    HORSE_JNT_WAIST_e=0x11,
    HORSE_JNT_B_L_LEG1_e=0x12,
    HORSE_JNT_B_L_LEG2_e=0x13,
    HORSE_JNT_B_L_LEG3_e=0x14,
    HORSE_JNT_B_L_LEG4_e=0x15,
    HORSE_JNT_B_R_LEG1_e=0x16,
    HORSE_JNT_B_R_LEG2_e=0x17,
    HORSE_JNT_B_R_LEG3_e=0x18,
    HORSE_JNT_B_R_LEG4_e=0x19,
    HORSE_JNT_TAIL1_e=0x1A,
    HORSE_JNT_TAIL2_e=0x1B,
    HORSE_JNT_TAIL3_e=0x1C,
};

enum THEB_JNT {
    THEB_JNT_CENTER_e=0x0,
    THEB_JNT_BACKBONE1_e=0x1,
    THEB_JNT_BACKBONE2_e=0x2,
    THEB_JNT_ARML1_e=0x3,
    THEB_JNT_ARML2_e=0x4,
    THEB_JNT_HANDL_e=0x5,
    THEB_JNT_ARMR1_e=0x6,
    THEB_JNT_ARMR2_e=0x7,
    THEB_JNT_HANDR_e=0x8,
    THEB_JNT_NECK_e=0x9,
    THEB_JNT_HEAD_e=0xA,
    THEB_JNT_CHIN_e=0xB,
    THEB_JNT_HAIR_e=0xC,
    THEB_JNT_MOUTH_e=0xD,
    THEB_JNT_WAIST_e=0xE,
    THEB_JNT_LEGL2_e=0xF,
    THEB_JNT_LEGR2_e=0x10,
};

enum YELIA_JNT {
    YELIA_JNT_CENTER_e=0x0,
    YELIA_JNT_WAIST_e=0x1,
    YELIA_JNT_BACKBONE_e=0x2,
    YELIA_JNT_NECK_e=0x3,
    YELIA_JNT_HEAD_e=0x4,
};

#endif /* !RES_COACH_H */