#ifndef RES_D_KGATE00_H
#define RES_D_KGATE00_H

enum dRes_INDEX_D_KGATE00 {
    /* BMDR */
    dRes_INDEX_D_KGATE00_BMD_D_KIKOGATE_A_e=0x5,
    dRes_INDEX_D_KGATE00_BMD_D_KIKOGATE_A_HOOK_e=0x6,
    dRes_INDEX_D_KGATE00_BMD_D_KIKOGATE_A_KEY_e=0x7,
    /* DZB  */
    dRes_INDEX_D_KGATE00_DZB_D_KIKOGATE_A_e=0xA,
    /* EVT  */
    dRes_INDEX_D_KGATE00_DAT_EVENT_LIST_e=0xD,
};

enum dRes_ID_D_KGATE00 {
    /* BMDR */
    dRes_ID_D_KGATE00_BMD_D_KIKOGATE_A_e=0x5,
    dRes_ID_D_KGATE00_BMD_D_KIKOGATE_A_HOOK_e=0x6,
    dRes_ID_D_KGATE00_BMD_D_KIKOGATE_A_KEY_e=0x7,
    /* DZB  */
    dRes_ID_D_KGATE00_DZB_D_KIKOGATE_A_e=0xA,
    /* EVT  */
    dRes_ID_D_KGATE00_DAT_EVENT_LIST_e=0xD,
};

enum D_KIKOGATE_A_JNT {
    D_KIKOGATE_A_JNT_WORLD_ROOT_e=0x0,
};

enum D_KIKOGATE_A_HOOK_JNT {
    D_KIKOGATE_A_HOOK_JNT_WORLD_ROOT_e=0x0,
};

enum D_KIKOGATE_A_KEY_JNT {
    D_KIKOGATE_A_KEY_JNT_WORLD_ROOT_e=0x0,
};

#endif /* !RES_D_KGATE00_H */