#ifndef RES_GRA_GATE_H
#define RES_GRA_GATE_H

enum dRes_INDEX_GRA_GATE {
    /* BCK  */
    dRes_INDEX_GRA_GATE_BCK_GRA_A_DRINK_e=0x5,
    dRes_INDEX_GRA_GATE_BCK_GRA_A_F_DRINK_e=0x6,
    dRes_INDEX_GRA_GATE_BCK_GRA_A_F_LOOKING_e=0x7,
    dRes_INDEX_GRA_GATE_BCK_GRA_A_F_SNIFF_e=0x8,
    dRes_INDEX_GRA_GATE_BCK_GRA_A_LOOKING_e=0x9,
    dRes_INDEX_GRA_GATE_BCK_GRA_A_SNIFF_e=0xA,
    /* BMDE */
    dRes_INDEX_GRA_GATE_BMD_GRA_BOTTLE_e=0xD,
    /* BTP  */
    dRes_INDEX_GRA_GATE_BTP_GRA_A_F_DRINK_e=0x10,
    dRes_INDEX_GRA_GATE_BTP_GRA_A_F_LOOKING_e=0x11,
    dRes_INDEX_GRA_GATE_BTP_GRA_A_F_SNIFF_e=0x12,
};

enum dRes_ID_GRA_GATE {
    /* BCK  */
    dRes_ID_GRA_GATE_BCK_GRA_A_DRINK_e=0x5,
    dRes_ID_GRA_GATE_BCK_GRA_A_F_DRINK_e=0x6,
    dRes_ID_GRA_GATE_BCK_GRA_A_F_LOOKING_e=0x7,
    dRes_ID_GRA_GATE_BCK_GRA_A_F_SNIFF_e=0x8,
    dRes_ID_GRA_GATE_BCK_GRA_A_LOOKING_e=0x9,
    dRes_ID_GRA_GATE_BCK_GRA_A_SNIFF_e=0xA,
    /* BMDE */
    dRes_ID_GRA_GATE_BMD_GRA_BOTTLE_e=0xD,
    /* BTP  */
    dRes_ID_GRA_GATE_BTP_GRA_A_F_DRINK_e=0x10,
    dRes_ID_GRA_GATE_BTP_GRA_A_F_LOOKING_e=0x11,
    dRes_ID_GRA_GATE_BTP_GRA_A_F_SNIFF_e=0x12,
};

enum GRA_BOTTLE_JNT {
    GRA_BOTTLE_JNT_GRA_BOTTLE_e=0x0,
};

#endif /* !RES_GRA_GATE_H */