#ifndef RES_H_KKANBAN_H
#define RES_H_KKANBAN_H

enum dRes_INDEX_H_KKANBAN {
    /* BMDR */
    dRes_INDEX_H_KKANBAN_BMD_H_KAKARIKOKANBAN_e=0x4,
    /* DZB  */
    dRes_INDEX_H_KKANBAN_DZB_H_KAKARIKOKANBAN_e=0x7,
};

enum dRes_ID_H_KKANBAN {
    /* BMDR */
    dRes_ID_H_KKANBAN_BMD_H_KAKARIKOKANBAN_e=0x4,
    /* DZB  */
    dRes_ID_H_KKANBAN_DZB_H_KAKARIKOKANBAN_e=0x7,
};

enum H_KAKARIKOKANBAN_JNT {
    H_KAKARIKOKANBAN_JNT_H_KAKARIKOKANBAN_e=0x0,
    H_KAKARIKOKANBAN_JNT_MOVE_e=0x1,
    H_KAKARIKOKANBAN_JNT_NO_MOVE_e=0x2,
};

#endif /* !RES_H_KKANBAN_H */