#ifndef RES_JAGAR_H
#define RES_JAGAR_H

enum dRes_INDEX_JAGAR {
    /* BCK  */
    dRes_INDEX_JAGAR_BCK_JAGA_F_TALK_A_e=0x6,
    dRes_INDEX_JAGAR_BCK_JAGA_FH_TALK_A_e=0x7,
    dRes_INDEX_JAGAR_BCK_JAGA_STEP_e=0x8,
    dRes_INDEX_JAGAR_BCK_JAGA_TALK_B_e=0x9,
    dRes_INDEX_JAGAR_BCK_JAGAR_WAIT_A_e=0xA,
    /* BMDR */
    dRes_INDEX_JAGAR_BMD_JAGAR_e=0xD,
    /* BTK  */
    dRes_INDEX_JAGAR_BTK_JAGA_e=0x10,
    /* BTP  */
    dRes_INDEX_JAGAR_BTP_JAGA_e=0x13,
    dRes_INDEX_JAGAR_BTP_JAGA_F_TALK_A_e=0x14,
    dRes_INDEX_JAGAR_BTP_JAGA_FH_TALK_A_e=0x15,
};

enum dRes_ID_JAGAR {
    /* BCK  */
    dRes_ID_JAGAR_BCK_JAGA_F_TALK_A_e=0x6,
    dRes_ID_JAGAR_BCK_JAGA_FH_TALK_A_e=0x7,
    dRes_ID_JAGAR_BCK_JAGA_STEP_e=0x8,
    dRes_ID_JAGAR_BCK_JAGA_TALK_B_e=0x9,
    dRes_ID_JAGAR_BCK_JAGAR_WAIT_A_e=0xA,
    /* BMDR */
    dRes_ID_JAGAR_BMD_JAGAR_e=0xD,
    /* BTK  */
    dRes_ID_JAGAR_BTK_JAGA_e=0x10,
    /* BTP  */
    dRes_ID_JAGAR_BTP_JAGA_e=0x13,
    dRes_ID_JAGAR_BTP_JAGA_F_TALK_A_e=0x14,
    dRes_ID_JAGAR_BTP_JAGA_FH_TALK_A_e=0x15,
};

enum JAGAR_JNT {
    JAGAR_JNT_CENTER_e=0x0,
    JAGAR_JNT_BACKBONE1_e=0x1,
    JAGAR_JNT_BACKBONE2_e=0x2,
    JAGAR_JNT_NECK_e=0x3,
    JAGAR_JNT_HEAD_e=0x4,
    JAGAR_JNT_CHIN_e=0x5,
    JAGAR_JNT_MAYU_L_e=0x6,
    JAGAR_JNT_MAYU_R_e=0x7,
    JAGAR_JNT_MOUTH_e=0x8,
    JAGAR_JNT_SHOULDERL_e=0x9,
    JAGAR_JNT_ARML1_e=0xA,
    JAGAR_JNT_ARML2_1_e=0xB,
    JAGAR_JNT_HANDL_1_e=0xC,
    JAGAR_JNT_FINGERL_e=0xD,
    JAGAR_JNT_SHOULDERR_e=0xE,
    JAGAR_JNT_ARMR1_e=0xF,
    JAGAR_JNT_ARMR2_1_e=0x10,
    JAGAR_JNT_HANDR_1_e=0x11,
    JAGAR_JNT_FINGERR_e=0x12,
    JAGAR_JNT_WAIST_e=0x13,
    JAGAR_JNT_LEGL1_e=0x14,
    JAGAR_JNT_LEGL2_e=0x15,
    JAGAR_JNT_FOOTL_e=0x16,
    JAGAR_JNT_SKIRTL_e=0x17,
    JAGAR_JNT_LEGR1_e=0x18,
    JAGAR_JNT_LEGR2_e=0x19,
    JAGAR_JNT_FOOTR_e=0x1A,
    JAGAR_JNT_SKIRTR_e=0x1B,
    JAGAR_JNT_SKIRT1_e=0x1C,
    JAGAR_JNT_SKIRT2_e=0x1D,
};

#endif /* !RES_JAGAR_H */