#ifndef RES_L4_N_SLPL_H
#define RES_L4_N_SLPL_H

enum dRes_INDEX_L4_N_SLPL {
    /* BMDR */
    dRes_INDEX_L4_N_SLPL_BMD_LV4_NORTHSLOPELOW_e=0x4,
    /* DZB  */
    dRes_INDEX_L4_N_SLPL_DZB_LV4_NORTHSLOPELOW_e=0x7,
};

enum dRes_ID_L4_N_SLPL {
    /* BMDR */
    dRes_ID_L4_N_SLPL_BMD_LV4_NORTHSLOPELOW_e=0x4,
    /* DZB  */
    dRes_ID_L4_N_SLPL_DZB_LV4_NORTHSLOPELOW_e=0x7,
};

enum LV4_NORTHSLOPELOW_JNT {
    LV4_NORTHSLOPELOW_JNT_WORLD_ROOT_e=0x0,
};

#endif /* !RES_L4_N_SLPL_H */