#ifndef RES_L4TOGETP_H
#define RES_L4TOGETP_H

enum dRes_INDEX_L4TOGETP {
    /* BMDR */
    dRes_INDEX_L4TOGETP_BMD_LV4_OBJ_TOGETRAP_e=0x4,
    /* DZB  */
    dRes_INDEX_L4TOGETP_DZB_LV4_OBJ_TOGETRAP_e=0x7,
};

enum dRes_ID_L4TOGETP {
    /* BMDR */
    dRes_ID_L4TOGETP_BMD_LV4_OBJ_TOGETRAP_e=0x4,
    /* DZB  */
    dRes_ID_L4TOGETP_DZB_LV4_OBJ_TOGETRAP_e=0x7,
};

enum LV4_OBJ_TOGETRAP_JNT {
    LV4_OBJ_TOGETRAP_JNT_WORLD_ROOT_e=0x0,
};

#endif /* !RES_L4TOGETP_H */