#ifndef RES_LOGOUS_H
#define RES_LOGOUS_H

enum dRes_INDEX_LOGOUS {
    /* DAT  */
    dRes_INDEX_LOGOUS_BTI_DOLBY_P2_232_112_e=0x3,
    dRes_INDEX_LOGOUS_BTI_NINTENDO_376X104_e=0x4,
    dRes_INDEX_LOGOUS_BTI_PROGRESSIVE_CHOICE_e=0x5,
    dRes_INDEX_LOGOUS_BTI_PROGRESSIVE_INTER_e=0x6,
    dRes_INDEX_LOGOUS_BTI_PROGRESSIVE_NO_e=0x7,
    dRes_INDEX_LOGOUS_BTI_PROGRESSIVE_PRO_e=0x8,
    dRes_INDEX_LOGOUS_BTI_PROGRESSIVE_YES_e=0x9,
    dRes_INDEX_LOGOUS_BTI_WARNING_e=0xA,
    dRes_INDEX_LOGOUS_BTI_WARNING_PSTART_e=0xB,
};

enum dRes_ID_LOGOUS {
    /* DAT  */
    dRes_ID_LOGOUS_BTI_DOLBY_P2_232_112_e=0x3,
    dRes_ID_LOGOUS_BTI_NINTENDO_376X104_e=0x4,
    dRes_ID_LOGOUS_BTI_PROGRESSIVE_CHOICE_e=0x5,
    dRes_ID_LOGOUS_BTI_PROGRESSIVE_INTER_e=0x6,
    dRes_ID_LOGOUS_BTI_PROGRESSIVE_NO_e=0x7,
    dRes_ID_LOGOUS_BTI_PROGRESSIVE_PRO_e=0x8,
    dRes_ID_LOGOUS_BTI_PROGRESSIVE_YES_e=0x9,
    dRes_ID_LOGOUS_BTI_WARNING_e=0xA,
    dRes_ID_LOGOUS_BTI_WARNING_PSTART_e=0xB,
};

#endif /* !RES_LOGOUS_H */