#ifndef RES_M_DRPROCK_H
#define RES_M_DRPROCK_H

enum dRes_INDEX_M_DRPROCK {
    /* BMDR */
    dRes_INDEX_M_DRPROCK_BMD_M_DROPROCK_e=0x4,
    dRes_INDEX_M_DRPROCK_BMD_M_DROPROCK_BASE_e=0x5,
    /* DZB  */
    dRes_INDEX_M_DRPROCK_DZB_M_DROPROCK_e=0x8,
    dRes_INDEX_M_DRPROCK_DZB_M_DROPROCK_BASE_e=0x9,
};

enum dRes_ID_M_DRPROCK {
    /* BMDR */
    dRes_ID_M_DRPROCK_BMD_M_DROPROCK_e=0x4,
    dRes_ID_M_DRPROCK_BMD_M_DROPROCK_BASE_e=0x5,
    /* DZB  */
    dRes_ID_M_DRPROCK_DZB_M_DROPROCK_e=0x8,
    dRes_ID_M_DRPROCK_DZB_M_DROPROCK_BASE_e=0x9,
};

enum M_DROPROCK_JNT {
    M_DROPROCK_JNT_WORLD_ROOT_e=0x0,
};

enum M_DROPROCK_BASE_JNT {
    M_DROPROCK_BASE_JNT_WORLD_ROOT_e=0x0,
};

#endif /* !RES_M_DRPROCK_H */