#ifndef RES_MMDL_H
#define RES_MMDL_H

enum dRes_INDEX_MMDL {
    /* BMDE */
    dRes_INDEX_MMDL_BMD_AL_KANTERA_e=0x7,
    /* BMDR */
    dRes_INDEX_MMDL_BMD_EF_KTGLOW_e=0xA,
    /* BMWR */
    dRes_INDEX_MMDL_BMD_AL_BOOTSH_e=0xD,
    dRes_INDEX_MMDL_BMD_AL_FACE_e=0xE,
    dRes_INDEX_MMDL_BMD_AL_HANDS_e=0xF,
    dRes_INDEX_MMDL_BMD_AL_SWB_e=0x10,
    dRes_INDEX_MMDL_BMD_ML_e=0x11,
    dRes_INDEX_MMDL_BMD_ML_HEAD_e=0x12,
    /* BRK  */
    dRes_INDEX_MMDL_BRK_ML_BODY_POWER_DOWN_e=0x15,
    dRes_INDEX_MMDL_BRK_ML_BODY_POWER_UP_A_e=0x16,
    dRes_INDEX_MMDL_BRK_ML_BODY_POWER_UP_B_e=0x17,
    dRes_INDEX_MMDL_BRK_ML_HEAD_POWER_DOWN_e=0x18,
    dRes_INDEX_MMDL_BRK_ML_HEAD_POWER_UP_A_e=0x19,
    dRes_INDEX_MMDL_BRK_ML_HEAD_POWER_UP_B_e=0x1A,
    /* BTK  */
    dRes_INDEX_MMDL_BTK_EF_KTGLOW_e=0x1D,
};

enum dRes_ID_MMDL {
    /* BMDE */
    dRes_ID_MMDL_BMD_AL_KANTERA_e=0x7,
    /* BMDR */
    dRes_ID_MMDL_BMD_EF_KTGLOW_e=0xA,
    /* BMWR */
    dRes_ID_MMDL_BMD_AL_BOOTSH_e=0xD,
    dRes_ID_MMDL_BMD_AL_FACE_e=0xE,
    dRes_ID_MMDL_BMD_AL_HANDS_e=0xF,
    dRes_ID_MMDL_BMD_AL_SWB_e=0x10,
    dRes_ID_MMDL_BMD_ML_e=0x11,
    dRes_ID_MMDL_BMD_ML_HEAD_e=0x12,
    /* BRK  */
    dRes_ID_MMDL_BRK_ML_BODY_POWER_DOWN_e=0x15,
    dRes_ID_MMDL_BRK_ML_BODY_POWER_UP_A_e=0x16,
    dRes_ID_MMDL_BRK_ML_BODY_POWER_UP_B_e=0x17,
    dRes_ID_MMDL_BRK_ML_HEAD_POWER_DOWN_e=0x18,
    dRes_ID_MMDL_BRK_ML_HEAD_POWER_UP_A_e=0x19,
    dRes_ID_MMDL_BRK_ML_HEAD_POWER_UP_B_e=0x1A,
    /* BTK  */
    dRes_ID_MMDL_BTK_EF_KTGLOW_e=0x1D,
};

enum AL_KANTERA_JNT {
    AL_KANTERA_JNT_TOTTE_e=0x0,
    AL_KANTERA_JNT_KANTERA_e=0x1,
};

enum EF_KTGLOW_JNT {
    EF_KTGLOW_JNT_PPLANE1_e=0x0,
};

enum AL_BOOTSH_JNT {
    AL_BOOTSH_JNT_WORLD_ROOT_e=0x0,
    AL_BOOTSH_JNT_AL_BOOTSHA_e=0x1,
    AL_BOOTSH_JNT_AL_BOOTSHB_e=0x2,
    AL_BOOTSH_JNT_AL_BOOTSHC_e=0x3,
};

enum AL_FACE_JNT {
    AL_FACE_JNT_FACE_ROOT_e=0x0,
    AL_FACE_JNT_CHIN_e=0x1,
    AL_FACE_JNT_MAYUL_e=0x2,
    AL_FACE_JNT_MAYUR_e=0x3,
    AL_FACE_JNT_MOUTH_e=0x4,
};

enum AL_HANDS_JNT {
    AL_HANDS_JNT_WORLD_ROOT_e=0x0,
    AL_HANDS_JNT_AL_HANDSL_e=0x1,
    AL_HANDS_JNT_AL_HANDSR_e=0x2,
};

enum AL_SWB_JNT {
    AL_SWB_JNT_AL_SWB_e=0x0,
};

enum ML_JNT {
    ML_JNT_CENTER_e=0x0,
    ML_JNT_BACKBONE1_e=0x1,
    ML_JNT_BACKBONE2_e=0x2,
    ML_JNT_NECK_e=0x3,
    ML_JNT_HEAD_e=0x4,
    ML_JNT_POD_e=0x5,
    ML_JNT_SHOULDERL_e=0x6,
    ML_JNT_ARML1_e=0x7,
    ML_JNT_ARML2_e=0x8,
    ML_JNT_HANDL_e=0x9,
    ML_JNT_WEAPONL_e=0xA,
    ML_JNT_SHOULDERR_e=0xB,
    ML_JNT_ARMR1_e=0xC,
    ML_JNT_ARMR2_e=0xD,
    ML_JNT_HANDR_e=0xE,
    ML_JNT_WEAPONR_e=0xF,
    ML_JNT_WAIST_e=0x10,
    ML_JNT_CLOTCHL_e=0x11,
    ML_JNT_LEGL1_e=0x12,
    ML_JNT_LEGL2_e=0x13,
    ML_JNT_FOOTL_e=0x14,
    ML_JNT_TOEL_e=0x15,
    ML_JNT_CLOTCHR_e=0x16,
    ML_JNT_LEGR1_e=0x17,
    ML_JNT_LEGR2_e=0x18,
    ML_JNT_FOOTR_e=0x19,
    ML_JNT_TOER_e=0x1A,
    ML_JNT_FSKIRTL1_e=0x1B,
    ML_JNT_FSKIRTL2_e=0x1C,
    ML_JNT_FSKIRTR1_e=0x1D,
    ML_JNT_FSKIRTR2_e=0x1E,
    ML_JNT_RSKIRTL1_e=0x1F,
    ML_JNT_RSKIRTL2_e=0x20,
    ML_JNT_RSKIRTR1_e=0x21,
    ML_JNT_RSKIRTR2_e=0x22,
};

enum ML_HEAD_JNT {
    ML_HEAD_JNT_HEAD_ROOT_e=0x0,
    ML_HEAD_JNT_HAIRL1_e=0x1,
    ML_HEAD_JNT_HAIRL2_e=0x2,
    ML_HEAD_JNT_HAIRR_e=0x3,
    ML_HEAD_JNT_MOMIL_e=0x4,
    ML_HEAD_JNT_MOMIR_e=0x5,
    ML_HEAD_JNT_Z_CAP1_e=0x6,
    ML_HEAD_JNT_Z_CAP2_e=0x7,
    ML_HEAD_JNT_Z_CAP3_e=0x8,
    ML_HEAD_JNT_Z_CAP4_e=0x9,
};

#endif /* !RES_MMDL_H */