#ifndef RES_MOIR1_H
#define RES_MOIR1_H

enum dRes_INDEX_MOIR1 {
    /* BCK  */
    dRes_INDEX_MOIR1_BCK_MOIR_SIT_e=0x3,
    dRes_INDEX_MOIR1_BCK_MOIR_SIT_TALK_e=0x4,
    dRes_INDEX_MOIR1_BCK_MOIR_TAKE_MET_SIT_e=0x5,
    dRes_INDEX_MOIR1_BCK_MOIR_TAKEOFF_SIT_e=0x6,
    dRes_INDEX_MOIR1_BCK_MOIR_TAKING_OFF_SIT_e=0x7,
    dRes_INDEX_MOIR1_BCK_MOIR_TAKING_OFF_SIT_TALK_e=0x8,
};

enum dRes_ID_MOIR1 {
    /* BCK  */
    dRes_ID_MOIR1_BCK_MOIR_SIT_e=0x3,
    dRes_ID_MOIR1_BCK_MOIR_SIT_TALK_e=0x4,
    dRes_ID_MOIR1_BCK_MOIR_TAKE_MET_SIT_e=0x5,
    dRes_ID_MOIR1_BCK_MOIR_TAKEOFF_SIT_e=0x6,
    dRes_ID_MOIR1_BCK_MOIR_TAKING_OFF_SIT_e=0x7,
    dRes_ID_MOIR1_BCK_MOIR_TAKING_OFF_SIT_TALK_e=0x8,
};

#endif /* !RES_MOIR1_H */