#ifndef RES_MOIR2_H
#define RES_MOIR2_H

enum dRes_INDEX_MOIR2 {
    /* BCK  */
    dRes_INDEX_MOIR2_BCK_MOIR_DRIVEAWAY_e=0x4,
    dRes_INDEX_MOIR2_BCK_MOIR_F_DRIVEAWAY_e=0x5,
    dRes_INDEX_MOIR2_BCK_MOIR_F_FUE_e=0x6,
    dRes_INDEX_MOIR2_BCK_MOIR_F_SURPRISED_e=0x7,
    dRes_INDEX_MOIR2_BCK_MOIR_FH_DRIVEAWAY_e=0x8,
    dRes_INDEX_MOIR2_BCK_MOIR_FUE_e=0x9,
    dRes_INDEX_MOIR2_BCK_MOIR_LOOK_AROUND_e=0xA,
    dRes_INDEX_MOIR2_BCK_MOIR_SQUAREUP_e=0xB,
    dRes_INDEX_MOIR2_BCK_MOIR_SQUAREUP_STEP_e=0xC,
    dRes_INDEX_MOIR2_BCK_MOIR_SURPRISED_e=0xD,
    dRes_INDEX_MOIR2_BCK_MOIR_TAKAJO_NI_e=0xE,
    dRes_INDEX_MOIR2_BCK_MOIR_TAKAJO_WAIT_NI_e=0xF,
    dRes_INDEX_MOIR2_BCK_MOIR_TAKE_MET_e=0x10,
    dRes_INDEX_MOIR2_BCK_MOIR_TAKEOFF_e=0x11,
    dRes_INDEX_MOIR2_BCK_MOIR_TAKING_OFF_e=0x12,
    dRes_INDEX_MOIR2_BCK_MOIR_TAKING_OFF_TALK_e=0x13,
    dRes_INDEX_MOIR2_BCK_MOIR_WAIT_B_e=0x14,
    dRes_INDEX_MOIR2_BCK_MOIR_WAIT_C_e=0x15,
    /* EVT  */
    dRes_INDEX_MOIR2_DAT_EVENT_LIST_e=0x18,
};

enum dRes_ID_MOIR2 {
    /* BCK  */
    dRes_ID_MOIR2_BCK_MOIR_DRIVEAWAY_e=0x4,
    dRes_ID_MOIR2_BCK_MOIR_F_DRIVEAWAY_e=0x5,
    dRes_ID_MOIR2_BCK_MOIR_F_FUE_e=0x6,
    dRes_ID_MOIR2_BCK_MOIR_F_SURPRISED_e=0x7,
    dRes_ID_MOIR2_BCK_MOIR_FH_DRIVEAWAY_e=0x8,
    dRes_ID_MOIR2_BCK_MOIR_FUE_e=0x9,
    dRes_ID_MOIR2_BCK_MOIR_LOOK_AROUND_e=0xA,
    dRes_ID_MOIR2_BCK_MOIR_SQUAREUP_e=0xB,
    dRes_ID_MOIR2_BCK_MOIR_SQUAREUP_STEP_e=0xC,
    dRes_ID_MOIR2_BCK_MOIR_SURPRISED_e=0xD,
    dRes_ID_MOIR2_BCK_MOIR_TAKAJO_NI_e=0xE,
    dRes_ID_MOIR2_BCK_MOIR_TAKAJO_WAIT_NI_e=0xF,
    dRes_ID_MOIR2_BCK_MOIR_TAKE_MET_e=0x10,
    dRes_ID_MOIR2_BCK_MOIR_TAKEOFF_e=0x11,
    dRes_ID_MOIR2_BCK_MOIR_TAKING_OFF_e=0x12,
    dRes_ID_MOIR2_BCK_MOIR_TAKING_OFF_TALK_e=0x13,
    dRes_ID_MOIR2_BCK_MOIR_WAIT_B_e=0x14,
    dRes_ID_MOIR2_BCK_MOIR_WAIT_C_e=0x15,
    /* EVT  */
    dRes_ID_MOIR2_DAT_EVENT_LIST_e=0x18,
};

#endif /* !RES_MOIR2_H */