#ifndef RES_MYNA_B_H
#define RES_MYNA_B_H

enum dRes_INDEX_MYNA_B {
    /* BCK  */
    dRes_INDEX_MYNA_B_BCK_MYNA_B_ATTACK_e=0x6,
    dRes_INDEX_MYNA_B_BCK_MYNA_B_HOVERING_e=0x7,
    dRes_INDEX_MYNA_B_BCK_MYNA_B_JUMP_e=0x8,
    dRes_INDEX_MYNA_B_BCK_MYNA_B_LIGHTUP_e=0x9,
    dRes_INDEX_MYNA_B_BCK_MYNA_B_PICK_A_e=0xA,
    dRes_INDEX_MYNA_B_BCK_MYNA_B_PICK_B_e=0xB,
    dRes_INDEX_MYNA_B_BCK_MYNA_B_SIDESTEPL_e=0xC,
    dRes_INDEX_MYNA_B_BCK_MYNA_B_SIDESTEPR_e=0xD,
    dRes_INDEX_MYNA_B_BCK_MYNA_B_TALK_A_e=0xE,
    dRes_INDEX_MYNA_B_BCK_MYNA_B_TALK_B_e=0xF,
    dRes_INDEX_MYNA_B_BCK_MYNA_B_TALK_C_e=0x10,
    dRes_INDEX_MYNA_B_BCK_MYNA_B_WAIT_A_e=0x11,
    dRes_INDEX_MYNA_B_BCK_MYNA_B_WAIT_B_e=0x12,
    dRes_INDEX_MYNA_B_BCK_MYNA_B_WAIT_C_e=0x13,
    dRes_INDEX_MYNA_B_BCK_MYNA_B_WAIT_D_e=0x14,
    /* BMDR */
    dRes_INDEX_MYNA_B_BMD_MYNA_B_e=0x17,
    /* BTP  */
    dRes_INDEX_MYNA_B_BTP_MYNA_B_e=0x1A,
    /* EVT  */
    dRes_INDEX_MYNA_B_DAT_EVENT_LIST_e=0x1D,
};

enum dRes_ID_MYNA_B {
    /* BCK  */
    dRes_ID_MYNA_B_BCK_MYNA_B_ATTACK_e=0x6,
    dRes_ID_MYNA_B_BCK_MYNA_B_HOVERING_e=0x7,
    dRes_ID_MYNA_B_BCK_MYNA_B_JUMP_e=0x8,
    dRes_ID_MYNA_B_BCK_MYNA_B_LIGHTUP_e=0x9,
    dRes_ID_MYNA_B_BCK_MYNA_B_PICK_A_e=0xA,
    dRes_ID_MYNA_B_BCK_MYNA_B_PICK_B_e=0xB,
    dRes_ID_MYNA_B_BCK_MYNA_B_SIDESTEPL_e=0xC,
    dRes_ID_MYNA_B_BCK_MYNA_B_SIDESTEPR_e=0xD,
    dRes_ID_MYNA_B_BCK_MYNA_B_TALK_A_e=0xE,
    dRes_ID_MYNA_B_BCK_MYNA_B_TALK_B_e=0xF,
    dRes_ID_MYNA_B_BCK_MYNA_B_TALK_C_e=0x10,
    dRes_ID_MYNA_B_BCK_MYNA_B_WAIT_A_e=0x11,
    dRes_ID_MYNA_B_BCK_MYNA_B_WAIT_B_e=0x12,
    dRes_ID_MYNA_B_BCK_MYNA_B_WAIT_C_e=0x13,
    dRes_ID_MYNA_B_BCK_MYNA_B_WAIT_D_e=0x14,
    /* BMDR */
    dRes_ID_MYNA_B_BMD_MYNA_B_e=0x17,
    /* BTP  */
    dRes_ID_MYNA_B_BTP_MYNA_B_e=0x1A,
    /* EVT  */
    dRes_ID_MYNA_B_DAT_EVENT_LIST_e=0x1D,
};

enum MYNA_B_JNT {
    MYNA_B_JNT_HARA_e=0x0,
    MYNA_B_JNT_MYNA_WING_e=0x1,
    MYNA_B_JNT_ASHI1L_e=0x2,
    MYNA_B_JNT_ASHI2L_e=0x3,
    MYNA_B_JNT_FOOTL_e=0x4,
    MYNA_B_JNT_ASHI1R_e=0x5,
    MYNA_B_JNT_ASHI2R_e=0x6,
    MYNA_B_JNT_FOOTR_e=0x7,
    MYNA_B_JNT_HAND1L_e=0x8,
    MYNA_B_JNT_HAND2L_e=0x9,
    MYNA_B_JNT_HAND3L_e=0xA,
    MYNA_B_JNT_HAND1R_e=0xB,
    MYNA_B_JNT_HAND2R_e=0xC,
    MYNA_B_JNT_HAND3R_e=0xD,
    MYNA_B_JNT_KUBI_e=0xE,
    MYNA_B_JNT_HEAD_e=0xF,
    MYNA_B_JNT_KUCHI_e=0x10,
    MYNA_B_JNT_TAIL_e=0x11,
};

#endif /* !RES_MYNA_B_H */