#ifndef RES_OBJ_KBRGS_H
#define RES_OBJ_KBRGS_H

enum dRes_INDEX_OBJ_KBRGS {
    /* BCK  */
    dRes_INDEX_OBJ_KBRGS_BCK_NI_KAKARIKOBRIDGE_EF_e=0x6,
    /* BMDR */
    dRes_INDEX_OBJ_KBRGS_BMD_NI_KAKARIKOBRIDGE_EF_e=0x9,
    /* BTK  */
    dRes_INDEX_OBJ_KBRGS_BTK_NI_KAKARIKOBRIDGE_EF_e=0xC,
    /* DZB  */
    dRes_INDEX_OBJ_KBRGS_DZB_NI_KAKARIKOBRIDGE_EF_e=0xF,
};

enum dRes_ID_OBJ_KBRGS {
    /* BCK  */
    dRes_ID_OBJ_KBRGS_BCK_NI_KAKARIKOBRIDGE_EF_e=0x6,
    /* BMDR */
    dRes_ID_OBJ_KBRGS_BMD_NI_KAKARIKOBRIDGE_EF_e=0x9,
    /* BTK  */
    dRes_ID_OBJ_KBRGS_BTK_NI_KAKARIKOBRIDGE_EF_e=0xC,
    /* DZB  */
    dRes_ID_OBJ_KBRGS_DZB_NI_KAKARIKOBRIDGE_EF_e=0xF,
};

enum NI_KAKARIKOBRIDGE_EF_JNT {
    NI_KAKARIKOBRIDGE_EF_JNT_NI_KAKARIKOBRIDGE_EF_e=0x0,
    NI_KAKARIKOBRIDGE_EF_JNT_EFFECT_P_e=0x1,
};

#endif /* !RES_OBJ_KBRGS_H */