#ifndef RES_SEIB_H
#define RES_SEIB_H

enum dRes_INDEX_SEIB {
    /* BCK  */
    dRes_INDEX_SEIB_BCK_SEIB_TALK_A_e=0x6,
    dRes_INDEX_SEIB_BCK_SEIB_TALKTURN_A_e=0x7,
    dRes_INDEX_SEIB_BCK_SEIB_TALKTURN_B_e=0x8,
    dRes_INDEX_SEIB_BCK_SEIB_WAIT_A_e=0x9,
    /* BMDE */
    dRes_INDEX_SEIB_BMD_SEIB_NOMAL_e=0xC,
    /* BRK  */
    dRes_INDEX_SEIB_BRK_SEIB_NOMAL_e=0xF,
    /* BTK  */
    dRes_INDEX_SEIB_BTK_SEIB_NOMAL_e=0x12,
};

enum dRes_ID_SEIB {
    /* BCK  */
    dRes_ID_SEIB_BCK_SEIB_TALK_A_e=0x6,
    dRes_ID_SEIB_BCK_SEIB_TALKTURN_A_e=0x7,
    dRes_ID_SEIB_BCK_SEIB_TALKTURN_B_e=0x8,
    dRes_ID_SEIB_BCK_SEIB_WAIT_A_e=0x9,
    /* BMDE */
    dRes_ID_SEIB_BMD_SEIB_NOMAL_e=0xC,
    /* BRK  */
    dRes_ID_SEIB_BRK_SEIB_NOMAL_e=0xF,
    /* BTK  */
    dRes_ID_SEIB_BTK_SEIB_NOMAL_e=0x12,
};

enum SEIB_NOMAL_JNT {
    SEIB_NOMAL_JNT_CENTER_e=0x0,
    SEIB_NOMAL_JNT_BACKBORN1_e=0x1,
    SEIB_NOMAL_JNT_BACKBORN2_e=0x2,
    SEIB_NOMAL_JNT_NECK_e=0x3,
    SEIB_NOMAL_JNT_HEAD_e=0x4,
    SEIB_NOMAL_JNT_CHIN_e=0x5,
    SEIB_NOMAL_JNT_MOUTH_e=0x6,
    SEIB_NOMAL_JNT_SHOULDER_L_e=0x7,
    SEIB_NOMAL_JNT_ARM1_L_e=0x8,
    SEIB_NOMAL_JNT_ARM2_L_e=0x9,
    SEIB_NOMAL_JNT_HAND_L_e=0xA,
    SEIB_NOMAL_JNT_FINGER_L_e=0xB,
    SEIB_NOMAL_JNT_THUMB_L_e=0xC,
    SEIB_NOMAL_JNT_SHOULDER_R_e=0xD,
    SEIB_NOMAL_JNT_ARM1_R_e=0xE,
    SEIB_NOMAL_JNT_ARM2_R_e=0xF,
    SEIB_NOMAL_JNT_HAND_R_e=0x10,
    SEIB_NOMAL_JNT_FINGER_R_e=0x11,
    SEIB_NOMAL_JNT_THUMB_R_e=0x12,
    SEIB_NOMAL_JNT_SIZUKU_e=0x13,
    SEIB_NOMAL_JNT_WAIST_e=0x14,
    SEIB_NOMAL_JNT_LEG1_L_e=0x15,
    SEIB_NOMAL_JNT_LEG2_L_e=0x16,
    SEIB_NOMAL_JNT_FOOT_L_e=0x17,
    SEIB_NOMAL_JNT_LEG1_R_e=0x18,
    SEIB_NOMAL_JNT_LEG2_R_e=0x19,
    SEIB_NOMAL_JNT_FOOT_R_e=0x1A,
    SEIB_NOMAL_JNT_TAIL1_e=0x1B,
    SEIB_NOMAL_JNT_TAIL2_e=0x1C,
    SEIB_NOMAL_JNT_TAIL3_e=0x1D,
    SEIB_NOMAL_JNT_TAIL4_e=0x1E,
    SEIB_NOMAL_JNT_TAIL5_e=0x1F,
    SEIB_NOMAL_JNT_TAIL6_e=0x20,
    SEIB_NOMAL_JNT_TAIL7_e=0x21,
    SEIB_NOMAL_JNT_TAIL8_e=0x22,
    SEIB_NOMAL_JNT_TAIL9_e=0x23,
    SEIB_NOMAL_JNT_TAIL10_e=0x24,
    SEIB_NOMAL_JNT_TAIL11_e=0x25,
    SEIB_NOMAL_JNT_TAIL12_e=0x26,
    SEIB_NOMAL_JNT_TAIL13_e=0x27,
};

#endif /* !RES_SEIB_H */