#ifndef RES_SERABTL_H
#define RES_SERABTL_H

enum dRes_INDEX_SERABTL {
    /* BCK  */
    dRes_INDEX_SERABTL_BCK_SERA_BOTTLE_HOZUE_BIN_e=0x4,
    dRes_INDEX_SERABTL_BCK_SERA_BOTTLE_LOOKCAT_e=0x5,
    dRes_INDEX_SERABTL_BCK_SERA_BOTTLE_SIT_e=0x6,
    dRes_INDEX_SERABTL_BCK_SERA_BOTTLE_SIT_GIVE_e=0x7,
    dRes_INDEX_SERABTL_BCK_SERA_BOTTLE_SIT_GIVING_e=0x8,
    dRes_INDEX_SERABTL_BCK_SERA_BOTTLE_SIT_LOOKUP_e=0x9,
    dRes_INDEX_SERABTL_BCK_SERA_BOTTLE_SIT_SIGH_e=0xA,
    dRes_INDEX_SERABTL_BCK_SERA_BOTTLE_SIT_TALK_e=0xB,
    dRes_INDEX_SERABTL_BCK_SERA_BOTTLE_SIT_UPBOTTLE_e=0xC,
    dRes_INDEX_SERABTL_BCK_SERA_FULL_BOTTLE_e=0xD,
    dRes_INDEX_SERABTL_BCK_SERA_HALF_BOTTLE_e=0xE,
    /* BMDV */
    dRes_INDEX_SERABTL_BMD_SERA_BOTTLE_e=0x11,
};

enum dRes_ID_SERABTL {
    /* BCK  */
    dRes_ID_SERABTL_BCK_SERA_BOTTLE_HOZUE_BIN_e=0x4,
    dRes_ID_SERABTL_BCK_SERA_BOTTLE_LOOKCAT_e=0x5,
    dRes_ID_SERABTL_BCK_SERA_BOTTLE_SIT_e=0x6,
    dRes_ID_SERABTL_BCK_SERA_BOTTLE_SIT_GIVE_e=0x7,
    dRes_ID_SERABTL_BCK_SERA_BOTTLE_SIT_GIVING_e=0x8,
    dRes_ID_SERABTL_BCK_SERA_BOTTLE_SIT_LOOKUP_e=0x9,
    dRes_ID_SERABTL_BCK_SERA_BOTTLE_SIT_SIGH_e=0xA,
    dRes_ID_SERABTL_BCK_SERA_BOTTLE_SIT_TALK_e=0xB,
    dRes_ID_SERABTL_BCK_SERA_BOTTLE_SIT_UPBOTTLE_e=0xC,
    dRes_ID_SERABTL_BCK_SERA_FULL_BOTTLE_e=0xD,
    dRes_ID_SERABTL_BCK_SERA_HALF_BOTTLE_e=0xE,
    /* BMDV */
    dRes_ID_SERABTL_BMD_SERA_BOTTLE_e=0x11,
};

enum SERA_BOTTLE_JNT {
    SERA_BOTTLE_JNT_CENTER_e=0x0,
    SERA_BOTTLE_JNT_BIN_e=0x1,
    SERA_BOTTLE_JNT_MILK_e=0x2,
};

#endif /* !RES_SERABTL_H */