#ifndef RES_SHAD1_H
#define RES_SHAD1_H

enum dRes_INDEX_SHAD1 {
    /* BCK  */
    dRes_INDEX_SHAD1_BCK_SHAD_BOOK_TALK_A_e=0x6,
    dRes_INDEX_SHAD1_BCK_SHAD_BOOK_WAIT_e=0x7,
    dRes_INDEX_SHAD1_BCK_SHAD_CHANT_e=0x8,
    dRes_INDEX_SHAD1_BCK_SHAD_DISCOURAGED_e=0x9,
    dRes_INDEX_SHAD1_BCK_SHAD_DISCOURAGED_WAIT_e=0xA,
    dRes_INDEX_SHAD1_BCK_SHAD_F_ANGER_e=0xB,
    dRes_INDEX_SHAD1_BCK_SHAD_F_CHANT_e=0xC,
    dRes_INDEX_SHAD1_BCK_SHAD_F_KOMON_e=0xD,
    dRes_INDEX_SHAD1_BCK_SHAD_F_SURPRISE_e=0xE,
    dRes_INDEX_SHAD1_BCK_SHAD_FH_ANGER_e=0xF,
    dRes_INDEX_SHAD1_BCK_SHAD_FH_KOMON_e=0x10,
    dRes_INDEX_SHAD1_BCK_SHAD_FH_SURPRISE_e=0x11,
    dRes_INDEX_SHAD1_BCK_SHAD_HI_e=0x12,
    dRes_INDEX_SHAD1_BCK_SHAD_LOOK_e=0x13,
    dRes_INDEX_SHAD1_BCK_SHAD_LOOK_WAIT_e=0x14,
    dRes_INDEX_SHAD1_BCK_SHAD_LOOKBACK_e=0x15,
    dRes_INDEX_SHAD1_BCK_SHAD_READ_KOMON_e=0x16,
    dRes_INDEX_SHAD1_BCK_SHAD_SAD_WALK_e=0x17,
    dRes_INDEX_SHAD1_BCK_SHAD_STEP_e=0x18,
    dRes_INDEX_SHAD1_BCK_SHAD_STEPB_e=0x19,
    dRes_INDEX_SHAD1_BCK_SHAD_SURPRISE_e=0x1A,
    dRes_INDEX_SHAD1_BCK_SHAD_SURPRISE_WAIT_e=0x1B,
    dRes_INDEX_SHAD1_BCK_SHAD_TAKE_KOMON_e=0x1C,
    dRes_INDEX_SHAD1_BCK_SHAD_TALK_A_e=0x1D,
    dRes_INDEX_SHAD1_BCK_SHAD_WAIT_A_e=0x1E,
    dRes_INDEX_SHAD1_BCK_SHAD_WALK_A_e=0x1F,
    /* BMDR */
    dRes_INDEX_SHAD1_BMD_SHAD_KOMONSHO_e=0x22,
    /* BTK  */
    dRes_INDEX_SHAD1_BTK_SHAD_DISCOURAGED_e=0x25,
    dRes_INDEX_SHAD1_BTK_SHAD_DISCOURAGED_WAIT_e=0x26,
    dRes_INDEX_SHAD1_BTK_SHAD_READ_KOMON_e=0x27,
    dRes_INDEX_SHAD1_BTK_SHAD_TAKE_KOMON_e=0x28,
    /* BTP  */
    dRes_INDEX_SHAD1_BTP_SHAD_F_ANGER_e=0x2B,
    dRes_INDEX_SHAD1_BTP_SHAD_F_CHANT_e=0x2C,
    dRes_INDEX_SHAD1_BTP_SHAD_F_KOMON_e=0x2D,
    dRes_INDEX_SHAD1_BTP_SHAD_F_SURPRISE_e=0x2E,
    dRes_INDEX_SHAD1_BTP_SHAD_FH_ANGER_e=0x2F,
    dRes_INDEX_SHAD1_BTP_SHAD_FH_KOMON_e=0x30,
    dRes_INDEX_SHAD1_BTP_SHAD_FH_SURPRISE_e=0x31,
};

enum dRes_ID_SHAD1 {
    /* BCK  */
    dRes_ID_SHAD1_BCK_SHAD_BOOK_TALK_A_e=0x6,
    dRes_ID_SHAD1_BCK_SHAD_BOOK_WAIT_e=0x7,
    dRes_ID_SHAD1_BCK_SHAD_CHANT_e=0x8,
    dRes_ID_SHAD1_BCK_SHAD_DISCOURAGED_e=0x9,
    dRes_ID_SHAD1_BCK_SHAD_DISCOURAGED_WAIT_e=0xA,
    dRes_ID_SHAD1_BCK_SHAD_F_ANGER_e=0xB,
    dRes_ID_SHAD1_BCK_SHAD_F_CHANT_e=0xC,
    dRes_ID_SHAD1_BCK_SHAD_F_KOMON_e=0xD,
    dRes_ID_SHAD1_BCK_SHAD_F_SURPRISE_e=0xE,
    dRes_ID_SHAD1_BCK_SHAD_FH_ANGER_e=0xF,
    dRes_ID_SHAD1_BCK_SHAD_FH_KOMON_e=0x10,
    dRes_ID_SHAD1_BCK_SHAD_FH_SURPRISE_e=0x11,
    dRes_ID_SHAD1_BCK_SHAD_HI_e=0x12,
    dRes_ID_SHAD1_BCK_SHAD_LOOK_e=0x13,
    dRes_ID_SHAD1_BCK_SHAD_LOOK_WAIT_e=0x14,
    dRes_ID_SHAD1_BCK_SHAD_LOOKBACK_e=0x15,
    dRes_ID_SHAD1_BCK_SHAD_READ_KOMON_e=0x16,
    dRes_ID_SHAD1_BCK_SHAD_SAD_WALK_e=0x17,
    dRes_ID_SHAD1_BCK_SHAD_STEP_e=0x18,
    dRes_ID_SHAD1_BCK_SHAD_STEPB_e=0x19,
    dRes_ID_SHAD1_BCK_SHAD_SURPRISE_e=0x1A,
    dRes_ID_SHAD1_BCK_SHAD_SURPRISE_WAIT_e=0x1B,
    dRes_ID_SHAD1_BCK_SHAD_TAKE_KOMON_e=0x1C,
    dRes_ID_SHAD1_BCK_SHAD_TALK_A_e=0x1D,
    dRes_ID_SHAD1_BCK_SHAD_WAIT_A_e=0x1E,
    dRes_ID_SHAD1_BCK_SHAD_WALK_A_e=0x1F,
    /* BMDR */
    dRes_ID_SHAD1_BMD_SHAD_KOMONSHO_e=0x22,
    /* BTK  */
    dRes_ID_SHAD1_BTK_SHAD_DISCOURAGED_e=0x25,
    dRes_ID_SHAD1_BTK_SHAD_DISCOURAGED_WAIT_e=0x26,
    dRes_ID_SHAD1_BTK_SHAD_READ_KOMON_e=0x27,
    dRes_ID_SHAD1_BTK_SHAD_TAKE_KOMON_e=0x28,
    /* BTP  */
    dRes_ID_SHAD1_BTP_SHAD_F_ANGER_e=0x2B,
    dRes_ID_SHAD1_BTP_SHAD_F_CHANT_e=0x2C,
    dRes_ID_SHAD1_BTP_SHAD_F_KOMON_e=0x2D,
    dRes_ID_SHAD1_BTP_SHAD_F_SURPRISE_e=0x2E,
    dRes_ID_SHAD1_BTP_SHAD_FH_ANGER_e=0x2F,
    dRes_ID_SHAD1_BTP_SHAD_FH_KOMON_e=0x30,
    dRes_ID_SHAD1_BTP_SHAD_FH_SURPRISE_e=0x31,
};

enum SHAD_KOMONSHO_JNT {
    SHAD_KOMONSHO_JNT_KOMONSHO_MODEL_e=0x0,
};

#endif /* !RES_SHAD1_H */