#ifndef RES_TARO1_H
#define RES_TARO1_H

enum dRes_INDEX_TARO1 {
    /* BCK  */
    dRes_INDEX_TARO1_BCK_TARO_CHOP_A_e=0x7,
    dRes_INDEX_TARO1_BCK_TARO_CHOP_B_e=0x8,
    dRes_INDEX_TARO1_BCK_TARO_F_PANIC_e=0x9,
    dRes_INDEX_TARO1_BCK_TARO_F_S_GET_e=0xA,
    dRes_INDEX_TARO1_BCK_TARO_F_SAD_e=0xB,
    dRes_INDEX_TARO1_BCK_TARO_F_SHOUT_e=0xC,
    dRes_INDEX_TARO1_BCK_TARO_F_SURPRISE_e=0xD,
    dRes_INDEX_TARO1_BCK_TARO_FH_PANIC_e=0xE,
    dRes_INDEX_TARO1_BCK_TARO_FH_SAD_e=0xF,
    dRes_INDEX_TARO1_BCK_TARO_FH_SURPRISE_e=0x10,
    dRes_INDEX_TARO1_BCK_TARO_RUN_e=0x11,
    dRes_INDEX_TARO1_BCK_TARO_S_CHOP_A_e=0x12,
    dRes_INDEX_TARO1_BCK_TARO_S_CHOP_B_e=0x13,
    dRes_INDEX_TARO1_BCK_TARO_S_GET_e=0x14,
    dRes_INDEX_TARO1_BCK_TARO_S_RUN_e=0x15,
    dRes_INDEX_TARO1_BCK_TARO_S_WAIT_e=0x16,
    dRes_INDEX_TARO1_BCK_TARO_TALK_A_e=0x17,
    dRes_INDEX_TARO1_BCK_TARO_TALK_B_e=0x18,
    dRes_INDEX_TARO1_BCK_TARO_WAIT_B_e=0x19,
    dRes_INDEX_TARO1_BCK_TARO_WAIT_D_e=0x1A,
    dRes_INDEX_TARO1_BCK_TARO_WAIT_E_e=0x1B,
    dRes_INDEX_TARO1_BCK_TARO_WAIT_F_e=0x1C,
    /* BMDR */
    dRes_INDEX_TARO1_BMD_TARO_STICK_A_e=0x1F,
    dRes_INDEX_TARO1_BMD_TARO_SWB_e=0x20,
    /* BTK  */
    dRes_INDEX_TARO1_BTK_TARO_S_GET_e=0x23,
    dRes_INDEX_TARO1_BTK_TARO_TALK_C_e=0x24,
    dRes_INDEX_TARO1_BTK_TARO_TALK_E_e=0x25,
    dRes_INDEX_TARO1_BTK_TARO_TARK_D_e=0x26,
    /* BTP  */
    dRes_INDEX_TARO1_BTP_TARO_F_PANIC_e=0x29,
    dRes_INDEX_TARO1_BTP_TARO_F_S_GET_e=0x2A,
    dRes_INDEX_TARO1_BTP_TARO_F_SAD_e=0x2B,
    dRes_INDEX_TARO1_BTP_TARO_F_SHOUT_e=0x2C,
    dRes_INDEX_TARO1_BTP_TARO_F_SURPRISE_e=0x2D,
    dRes_INDEX_TARO1_BTP_TARO_FH_PANIC_e=0x2E,
    dRes_INDEX_TARO1_BTP_TARO_FH_SAD_e=0x2F,
    dRes_INDEX_TARO1_BTP_TARO_FH_SURPRISE_e=0x30,
    /* EVT  */
    dRes_INDEX_TARO1_DAT_EVENT_LIST_e=0x33,
};

enum dRes_ID_TARO1 {
    /* BCK  */
    dRes_ID_TARO1_BCK_TARO_CHOP_A_e=0x7,
    dRes_ID_TARO1_BCK_TARO_CHOP_B_e=0x8,
    dRes_ID_TARO1_BCK_TARO_F_PANIC_e=0x9,
    dRes_ID_TARO1_BCK_TARO_F_S_GET_e=0xA,
    dRes_ID_TARO1_BCK_TARO_F_SAD_e=0xB,
    dRes_ID_TARO1_BCK_TARO_F_SHOUT_e=0xC,
    dRes_ID_TARO1_BCK_TARO_F_SURPRISE_e=0xD,
    dRes_ID_TARO1_BCK_TARO_FH_PANIC_e=0xE,
    dRes_ID_TARO1_BCK_TARO_FH_SAD_e=0xF,
    dRes_ID_TARO1_BCK_TARO_FH_SURPRISE_e=0x10,
    dRes_ID_TARO1_BCK_TARO_RUN_e=0x11,
    dRes_ID_TARO1_BCK_TARO_S_CHOP_A_e=0x12,
    dRes_ID_TARO1_BCK_TARO_S_CHOP_B_e=0x13,
    dRes_ID_TARO1_BCK_TARO_S_GET_e=0x14,
    dRes_ID_TARO1_BCK_TARO_S_RUN_e=0x15,
    dRes_ID_TARO1_BCK_TARO_S_WAIT_e=0x16,
    dRes_ID_TARO1_BCK_TARO_TALK_A_e=0x17,
    dRes_ID_TARO1_BCK_TARO_TALK_B_e=0x18,
    dRes_ID_TARO1_BCK_TARO_WAIT_B_e=0x19,
    dRes_ID_TARO1_BCK_TARO_WAIT_D_e=0x1A,
    dRes_ID_TARO1_BCK_TARO_WAIT_E_e=0x1B,
    dRes_ID_TARO1_BCK_TARO_WAIT_F_e=0x1C,
    /* BMDR */
    dRes_ID_TARO1_BMD_TARO_STICK_A_e=0x1F,
    dRes_ID_TARO1_BMD_TARO_SWB_e=0x20,
    /* BTK  */
    dRes_ID_TARO1_BTK_TARO_S_GET_e=0x23,
    dRes_ID_TARO1_BTK_TARO_TALK_C_e=0x24,
    dRes_ID_TARO1_BTK_TARO_TALK_E_e=0x25,
    dRes_ID_TARO1_BTK_TARO_TARK_D_e=0x26,
    /* BTP  */
    dRes_ID_TARO1_BTP_TARO_F_PANIC_e=0x29,
    dRes_ID_TARO1_BTP_TARO_F_S_GET_e=0x2A,
    dRes_ID_TARO1_BTP_TARO_F_SAD_e=0x2B,
    dRes_ID_TARO1_BTP_TARO_F_SHOUT_e=0x2C,
    dRes_ID_TARO1_BTP_TARO_F_SURPRISE_e=0x2D,
    dRes_ID_TARO1_BTP_TARO_FH_PANIC_e=0x2E,
    dRes_ID_TARO1_BTP_TARO_FH_SAD_e=0x2F,
    dRes_ID_TARO1_BTP_TARO_FH_SURPRISE_e=0x30,
    /* EVT  */
    dRes_ID_TARO1_DAT_EVENT_LIST_e=0x33,
};

enum TARO_STICK_A_JNT {
    TARO_STICK_A_JNT_TARO_STICK_e=0x0,
};

enum TARO_SWB_JNT {
    TARO_SWB_JNT_TARO_SWB_e=0x0,
};

#endif /* !RES_TARO1_H */