#ifndef RES_TOBY1_H
#define RES_TOBY1_H

enum dRes_INDEX_TOBY1 {
    /* BCK  */
    dRes_INDEX_TOBY1_BCK_ATMA_F_MOVE_A_e=0x6,
    dRes_INDEX_TOBY1_BCK_ATMA_FH_MOVE_B_e=0x7,
    dRes_INDEX_TOBY1_BCK_ATMA_FH_MOVE_C_e=0x8,
    dRes_INDEX_TOBY1_BCK_ATMA_MOVE_A_e=0x9,
    dRes_INDEX_TOBY1_BCK_ATMA_MOVE_B_e=0xA,
    dRes_INDEX_TOBY1_BCK_ATMA_MOVE_C_e=0xB,
    dRes_INDEX_TOBY1_BCK_TOBY_F_LAUGH_e=0xC,
    dRes_INDEX_TOBY1_BCK_TOBY_F_MOVE_X_e=0xD,
    dRes_INDEX_TOBY1_BCK_TOBY_FH_LAUGH_e=0xE,
    dRes_INDEX_TOBY1_BCK_TOBY_GIVEME_e=0xF,
    dRes_INDEX_TOBY1_BCK_TOBY_HI_e=0x10,
    dRes_INDEX_TOBY1_BCK_TOBY_LAUGH_e=0x11,
    dRes_INDEX_TOBY1_BCK_TOBY_MOVE_X_e=0x12,
    dRes_INDEX_TOBY1_BCK_TOBY_TALK_A_e=0x13,
    dRes_INDEX_TOBY1_BCK_TOBY_WALK_A_e=0x14,
    /* BTK  */
    dRes_INDEX_TOBY1_BTK_TOBY_MOVE_X_e=0x17,
    /* BTP  */
    dRes_INDEX_TOBY1_BTP_ATMA_F_MOVE_A_e=0x1A,
    dRes_INDEX_TOBY1_BTP_ATMA_FH_MOVE_B_e=0x1B,
    dRes_INDEX_TOBY1_BTP_ATMA_FH_MOVE_C_e=0x1C,
    dRes_INDEX_TOBY1_BTP_TOBY_F_LAUGH_e=0x1D,
    dRes_INDEX_TOBY1_BTP_TOBY_F_MOVE_X_e=0x1E,
    dRes_INDEX_TOBY1_BTP_TOBY_FH_LAUGH_e=0x1F,
    /* EVT  */
    dRes_INDEX_TOBY1_DAT_EVENT_LIST_e=0x22,
};

enum dRes_ID_TOBY1 {
    /* BCK  */
    dRes_ID_TOBY1_BCK_ATMA_F_MOVE_A_e=0x6,
    dRes_ID_TOBY1_BCK_ATMA_FH_MOVE_B_e=0x7,
    dRes_ID_TOBY1_BCK_ATMA_FH_MOVE_C_e=0x8,
    dRes_ID_TOBY1_BCK_ATMA_MOVE_A_e=0x9,
    dRes_ID_TOBY1_BCK_ATMA_MOVE_B_e=0xA,
    dRes_ID_TOBY1_BCK_ATMA_MOVE_C_e=0xB,
    dRes_ID_TOBY1_BCK_TOBY_F_LAUGH_e=0xC,
    dRes_ID_TOBY1_BCK_TOBY_F_MOVE_X_e=0xD,
    dRes_ID_TOBY1_BCK_TOBY_FH_LAUGH_e=0xE,
    dRes_ID_TOBY1_BCK_TOBY_GIVEME_e=0xF,
    dRes_ID_TOBY1_BCK_TOBY_HI_e=0x10,
    dRes_ID_TOBY1_BCK_TOBY_LAUGH_e=0x11,
    dRes_ID_TOBY1_BCK_TOBY_MOVE_X_e=0x12,
    dRes_ID_TOBY1_BCK_TOBY_TALK_A_e=0x13,
    dRes_ID_TOBY1_BCK_TOBY_WALK_A_e=0x14,
    /* BTK  */
    dRes_ID_TOBY1_BTK_TOBY_MOVE_X_e=0x17,
    /* BTP  */
    dRes_ID_TOBY1_BTP_ATMA_F_MOVE_A_e=0x1A,
    dRes_ID_TOBY1_BTP_ATMA_FH_MOVE_B_e=0x1B,
    dRes_ID_TOBY1_BTP_ATMA_FH_MOVE_C_e=0x1C,
    dRes_ID_TOBY1_BTP_TOBY_F_LAUGH_e=0x1D,
    dRes_ID_TOBY1_BTP_TOBY_F_MOVE_X_e=0x1E,
    dRes_ID_TOBY1_BTP_TOBY_FH_LAUGH_e=0x1F,
    /* EVT  */
    dRes_ID_TOBY1_DAT_EVENT_LIST_e=0x22,
};

#endif /* !RES_TOBY1_H */