#ifndef RES_YELIA0_H
#define RES_YELIA0_H

enum dRes_INDEX_YELIA0 {
    /* BCK  */
    dRes_INDEX_YELIA0_BCK_YELIA_F_HAPPY_TALK_e=0x5,
    dRes_INDEX_YELIA0_BCK_YELIA_F_LISTEN_e=0x6,
    dRes_INDEX_YELIA0_BCK_YELIA_F_TALK_A_e=0x7,
    dRes_INDEX_YELIA0_BCK_YELIA_FH_HAPPYTALK_e=0x8,
    dRes_INDEX_YELIA0_BCK_YELIA_FH_LISTEN_e=0x9,
    dRes_INDEX_YELIA0_BCK_YELIA_HAPPYTALK_e=0xA,
    dRes_INDEX_YELIA0_BCK_YELIA_LISTEN_e=0xB,
    dRes_INDEX_YELIA0_BCK_YELIA_STEP_e=0xC,
    dRes_INDEX_YELIA0_BCK_YELIA_WAIT_A_e=0xD,
    /* BTK  */
    dRes_INDEX_YELIA0_BTK_YELIA_e=0x10,
    /* BTP  */
    dRes_INDEX_YELIA0_BTP_YELIA_e=0x13,
    dRes_INDEX_YELIA0_BTP_YELIA_F_HAPPY_TALK_e=0x14,
    dRes_INDEX_YELIA0_BTP_YELIA_F_LISTEN_e=0x15,
    dRes_INDEX_YELIA0_BTP_YELIA_FH_HAPPYTALK_e=0x16,
    dRes_INDEX_YELIA0_BTP_YELIA_FH_LISTEN_e=0x17,
};

enum dRes_ID_YELIA0 {
    /* BCK  */
    dRes_ID_YELIA0_BCK_YELIA_F_HAPPY_TALK_e=0x5,
    dRes_ID_YELIA0_BCK_YELIA_F_LISTEN_e=0x6,
    dRes_ID_YELIA0_BCK_YELIA_F_TALK_A_e=0x7,
    dRes_ID_YELIA0_BCK_YELIA_FH_HAPPYTALK_e=0x8,
    dRes_ID_YELIA0_BCK_YELIA_FH_LISTEN_e=0x9,
    dRes_ID_YELIA0_BCK_YELIA_HAPPYTALK_e=0xA,
    dRes_ID_YELIA0_BCK_YELIA_LISTEN_e=0xB,
    dRes_ID_YELIA0_BCK_YELIA_STEP_e=0xC,
    dRes_ID_YELIA0_BCK_YELIA_WAIT_A_e=0xD,
    /* BTK  */
    dRes_ID_YELIA0_BTK_YELIA_e=0x10,
    /* BTP  */
    dRes_ID_YELIA0_BTP_YELIA_e=0x13,
    dRes_ID_YELIA0_BTP_YELIA_F_HAPPY_TALK_e=0x14,
    dRes_ID_YELIA0_BTP_YELIA_F_LISTEN_e=0x15,
    dRes_ID_YELIA0_BTP_YELIA_FH_HAPPYTALK_e=0x16,
    dRes_ID_YELIA0_BTP_YELIA_FH_LISTEN_e=0x17,
};

#endif /* !RES_YELIA0_H */