#ifndef RES_ZELRO_H
#define RES_ZELRO_H

enum dRes_INDEX_ZELRO {
    /* BCK  */
    dRes_INDEX_ZELRO_BCK_ZELRO_F_TALK_A_e=0x6,
    dRes_INDEX_ZELRO_BCK_ZELRO_WAIT_A_e=0x7,
    /* BMDR */
    dRes_INDEX_ZELRO_BMD_ZELRO_e=0xA,
    /* BTK  */
    dRes_INDEX_ZELRO_BTK_ZELRO_e=0xD,
    /* BTP  */
    dRes_INDEX_ZELRO_BTP_ZELRO_e=0x10,
};

enum dRes_ID_ZELRO {
    /* BCK  */
    dRes_ID_ZELRO_BCK_ZELRO_F_TALK_A_e=0x6,
    dRes_ID_ZELRO_BCK_ZELRO_WAIT_A_e=0x7,
    /* BMDR */
    dRes_ID_ZELRO_BMD_ZELRO_e=0xA,
    /* BTK  */
    dRes_ID_ZELRO_BTK_ZELRO_e=0xD,
    /* BTP  */
    dRes_ID_ZELRO_BTP_ZELRO_e=0x10,
};

enum ZELRO_JNT {
    ZELRO_JNT_CENTER_e=0x0,
    ZELRO_JNT_BACKBONE1_e=0x1,
    ZELRO_JNT_BACKBONE2_e=0x2,
    ZELRO_JNT_NECK_e=0x3,
    ZELRO_JNT_HEAD_e=0x4,
    ZELRO_JNT_CHIN_e=0x5,
    ZELRO_JNT_MANT_e=0x6,
    ZELRO_JNT_MAYUL_e=0x7,
    ZELRO_JNT_MAYUR_e=0x8,
    ZELRO_JNT_MOMIL1_e=0x9,
    ZELRO_JNT_MOMIL2_e=0xA,
    ZELRO_JNT_MOMIL3_e=0xB,
    ZELRO_JNT_MOMIR1_e=0xC,
    ZELRO_JNT_MOMIR2_e=0xD,
    ZELRO_JNT_MOMIR3_e=0xE,
    ZELRO_JNT_MOUTH_e=0xF,
    ZELRO_JNT_SHOULDERL_e=0x10,
    ZELRO_JNT_ARML1_e=0x11,
    ZELRO_JNT_ARML2_e=0x12,
    ZELRO_JNT_HANDL_e=0x13,
    ZELRO_JNT_FINGERL1_e=0x14,
    ZELRO_JNT_FINGERL2_e=0x15,
    ZELRO_JNT_THAMBL_e=0x16,
    ZELRO_JNT_SHOULDERR_e=0x17,
    ZELRO_JNT_ARMR1_e=0x18,
    ZELRO_JNT_ARMR2_e=0x19,
    ZELRO_JNT_HANDR_e=0x1A,
    ZELRO_JNT_FINGERR1_e=0x1B,
    ZELRO_JNT_FINGERR2_e=0x1C,
    ZELRO_JNT_THAMBR_e=0x1D,
    ZELRO_JNT_WAIST_e=0x1E,
    ZELRO_JNT_SKARTL_01_e=0x1F,
    ZELRO_JNT_SKARTL_02_e=0x20,
    ZELRO_JNT_SKARTL_03_e=0x21,
    ZELRO_JNT_SKARTR_01_e=0x22,
    ZELRO_JNT_SKARTR_02_e=0x23,
    ZELRO_JNT_SKARTR_03_e=0x24,
};

#endif /* !RES_ZELRO_H */