#ifndef RES_ZRA2_H
#define RES_ZRA2_H

enum dRes_INDEX_ZRA2 {
    /* BCK  */
    dRes_INDEX_ZRA2_BCK_ZRA_F_LOOKUP_e=0x4,
    dRes_INDEX_ZRA2_BCK_ZRA_F_SPA_TALK_A_e=0x5,
    dRes_INDEX_ZRA2_BCK_ZRA_F_SPA_TALK_B_e=0x6,
    dRes_INDEX_ZRA2_BCK_ZRA_FH_LOOKUP_e=0x7,
    dRes_INDEX_ZRA2_BCK_ZRA_FH_SPA_WAIT_A_e=0x8,
    dRes_INDEX_ZRA2_BCK_ZRA_FH_SPA_WAIT_B_e=0x9,
    dRes_INDEX_ZRA2_BCK_ZRA_LOOKUP_e=0xA,
    dRes_INDEX_ZRA2_BCK_ZRA_SPA_TALK_A_e=0xB,
    dRes_INDEX_ZRA2_BCK_ZRA_SPA_TALK_B_e=0xC,
    dRes_INDEX_ZRA2_BCK_ZRA_SPA_WAIT_A_e=0xD,
    dRes_INDEX_ZRA2_BCK_ZRA_SPA_WAIT_B_e=0xE,
    /* BTP  */
    dRes_INDEX_ZRA2_BTP_ZRA_F_SPA_TALK_B_e=0x11,
    dRes_INDEX_ZRA2_BTP_ZRA_FH_SPA_WAIT_B_e=0x12,
};

enum dRes_ID_ZRA2 {
    /* BCK  */
    dRes_ID_ZRA2_BCK_ZRA_F_LOOKUP_e=0x4,
    dRes_ID_ZRA2_BCK_ZRA_F_SPA_TALK_A_e=0x5,
    dRes_ID_ZRA2_BCK_ZRA_F_SPA_TALK_B_e=0x6,
    dRes_ID_ZRA2_BCK_ZRA_FH_LOOKUP_e=0x7,
    dRes_ID_ZRA2_BCK_ZRA_FH_SPA_WAIT_A_e=0x8,
    dRes_ID_ZRA2_BCK_ZRA_FH_SPA_WAIT_B_e=0x9,
    dRes_ID_ZRA2_BCK_ZRA_LOOKUP_e=0xA,
    dRes_ID_ZRA2_BCK_ZRA_SPA_TALK_A_e=0xB,
    dRes_ID_ZRA2_BCK_ZRA_SPA_TALK_B_e=0xC,
    dRes_ID_ZRA2_BCK_ZRA_SPA_WAIT_A_e=0xD,
    dRes_ID_ZRA2_BCK_ZRA_SPA_WAIT_B_e=0xE,
    /* BTP  */
    dRes_ID_ZRA2_BTP_ZRA_F_SPA_TALK_B_e=0x11,
    dRes_ID_ZRA2_BTP_ZRA_FH_SPA_WAIT_B_e=0x12,
};

#endif /* !RES_ZRA2_H */