#ifndef RES_ZRCB_H
#define RES_ZRCB_H

enum dRes_INDEX_ZRCB {
    /* BCK  */
    dRes_INDEX_ZRCB_BCK_ZRCB_F_SUFFER_A_e=0x5,
    dRes_INDEX_ZRCB_BCK_ZRCB_F_SUFFER_B_e=0x6,
    dRes_INDEX_ZRCB_BCK_ZRCB_F_WAIT_A_e=0x7,
    dRes_INDEX_ZRCB_BCK_ZRCB_SUFFER_A_e=0x8,
    dRes_INDEX_ZRCB_BCK_ZRCB_SUFFER_B_e=0x9,
    dRes_INDEX_ZRCB_BCK_ZRCB_WAIT_A_e=0xA,
    /* BMDR */
    dRes_INDEX_ZRCB_BMD_ZRCB_e=0xD,
    /* BTP  */
    dRes_INDEX_ZRCB_BTP_ZRCB_F_SUFFER_A_e=0x10,
    dRes_INDEX_ZRCB_BTP_ZRCB_F_SUFFER_B_e=0x11,
    dRes_INDEX_ZRCB_BTP_ZRCB_F_WAIT_A_e=0x12,
};

enum dRes_ID_ZRCB {
    /* BCK  */
    dRes_ID_ZRCB_BCK_ZRCB_F_SUFFER_A_e=0x5,
    dRes_ID_ZRCB_BCK_ZRCB_F_SUFFER_B_e=0x6,
    dRes_ID_ZRCB_BCK_ZRCB_F_WAIT_A_e=0x7,
    dRes_ID_ZRCB_BCK_ZRCB_SUFFER_A_e=0x8,
    dRes_ID_ZRCB_BCK_ZRCB_SUFFER_B_e=0x9,
    dRes_ID_ZRCB_BCK_ZRCB_WAIT_A_e=0xA,
    /* BMDR */
    dRes_ID_ZRCB_BMD_ZRCB_e=0xD,
    /* BTP  */
    dRes_ID_ZRCB_BTP_ZRCB_F_SUFFER_A_e=0x10,
    dRes_ID_ZRCB_BTP_ZRCB_F_SUFFER_B_e=0x11,
    dRes_ID_ZRCB_BTP_ZRCB_F_WAIT_A_e=0x12,
};

enum ZRCB_JNT {
    ZRCB_JNT_CENTER_e=0x0,
    ZRCB_JNT_BED_ROOT_e=0x1,
    ZRCB_JNT_ZRC_CENTER_e=0x2,
    ZRCB_JNT_BACKBONE1_e=0x3,
    ZRCB_JNT_BACKBONE2_e=0x4,
    ZRCB_JNT_NECK_e=0x5,
    ZRCB_JNT_HEAD_e=0x6,
    ZRCB_JNT_H_TAIL1_e=0x7,
    ZRCB_JNT_H_TAIL2_e=0x8,
    ZRCB_JNT_H_TAIL3_e=0x9,
    ZRCB_JNT_CHIN_e=0xA,
    ZRCB_JNT_EARL1_e=0xB,
    ZRCB_JNT_EARL2_e=0xC,
    ZRCB_JNT_EARR1_e=0xD,
    ZRCB_JNT_EARR2_e=0xE,
    ZRCB_JNT_MOUTH_e=0xF,
    ZRCB_JNT_SHOULDERL_e=0x10,
    ZRCB_JNT_ARML1_e=0x11,
    ZRCB_JNT_SHOULDERR_e=0x12,
    ZRCB_JNT_ARMR1_e=0x13,
    ZRCB_JNT_CLOTH_ROOT_e=0x14,
    ZRCB_JNT_CLOTH_e=0x15,
};

#endif /* !RES_ZRCB_H */