#ifndef RES_CHTSOLA_H
#define RES_CHTSOLA_H

enum dRes_INDEX_CHTSOLA {
    /* BCK  */
    dRes_INDEX_CHTSOLA_BCK_SOLA_FEAR_TALK_e=0x5,
    dRes_INDEX_CHTSOLA_BCK_SOLA_FEAR_WAIT_e=0x6,
    dRes_INDEX_CHTSOLA_BCK_SOLA_TALK_A_e=0x7,
    dRes_INDEX_CHTSOLA_BCK_SOLA_TALK_B_e=0x8,
    dRes_INDEX_CHTSOLA_BCK_SOLA_WAIT_e=0x9,
    dRes_INDEX_CHTSOLA_BCK_SOLA_WAIT_A_e=0xA,
    /* BMDR */
    dRes_INDEX_CHTSOLA_BMD_SOLA_SPEAR_e=0xD,
    dRes_INDEX_CHTSOLA_BMD_SOLA_TW_e=0xE,
    /* EVT  */
    dRes_INDEX_CHTSOLA_DAT_EVENT_LIST_e=0x11,
};

enum dRes_ID_CHTSOLA {
    /* BCK  */
    dRes_ID_CHTSOLA_BCK_SOLA_FEAR_TALK_e=0x5,
    dRes_ID_CHTSOLA_BCK_SOLA_FEAR_WAIT_e=0x6,
    dRes_ID_CHTSOLA_BCK_SOLA_TALK_A_e=0x7,
    dRes_ID_CHTSOLA_BCK_SOLA_TALK_B_e=0x8,
    dRes_ID_CHTSOLA_BCK_SOLA_WAIT_e=0x9,
    dRes_ID_CHTSOLA_BCK_SOLA_WAIT_A_e=0xA,
    /* BMDR */
    dRes_ID_CHTSOLA_BMD_SOLA_SPEAR_e=0xD,
    dRes_ID_CHTSOLA_BMD_SOLA_TW_e=0xE,
    /* EVT  */
    dRes_ID_CHTSOLA_DAT_EVENT_LIST_e=0x11,
};

enum SOLA_SPEAR_JNT {
    SOLA_SPEAR_JNT_SOL_SPEAR_e=0x0,
};

enum SOLA_TW_JNT {
    SOLA_TW_JNT_CENTER_e=0x0,
    SOLA_TW_JNT_BACKBONE1_e=0x1,
    SOLA_TW_JNT_BACKBONE2_e=0x2,
    SOLA_TW_JNT_NECK_e=0x3,
    SOLA_TW_JNT_HEAD_e=0x4,
    SOLA_TW_JNT_SHOULDERL_e=0x5,
    SOLA_TW_JNT_ARM1L_e=0x6,
    SOLA_TW_JNT_ARM2L_e=0x7,
    SOLA_TW_JNT_HANDL_e=0x8,
    SOLA_TW_JNT_FINGERL_e=0x9,
    SOLA_TW_JNT_THUMBL_e=0xA,
    SOLA_TW_JNT_SHOULDERR_e=0xB,
    SOLA_TW_JNT_ARM1R_e=0xC,
    SOLA_TW_JNT_ARM2R_e=0xD,
    SOLA_TW_JNT_HANDR_e=0xE,
    SOLA_TW_JNT_FINGERR_e=0xF,
    SOLA_TW_JNT_THUMBR_e=0x10,
    SOLA_TW_JNT_WAIST_e=0x11,
    SOLA_TW_JNT_LEG1L_e=0x12,
    SOLA_TW_JNT_LEG2L_e=0x13,
    SOLA_TW_JNT_FOOTL_e=0x14,
    SOLA_TW_JNT_LEG1R_e=0x15,
    SOLA_TW_JNT_LEG2R_e=0x16,
    SOLA_TW_JNT_FOOTR_e=0x17,
    SOLA_TW_JNT_SAYA_e=0x18,
};

#endif /* !RES_CHTSOLA_H */