#ifndef RES_DOC1_H
#define RES_DOC1_H

enum dRes_INDEX_DOC1 {
    /* BCK  */
    dRes_INDEX_DOC1_BCK_DOC_CONFUSED_A_e=0x5,
    dRes_INDEX_DOC1_BCK_DOC_CONFUSED_B_e=0x6,
    dRes_INDEX_DOC1_BCK_DOC_F_CONFUSED_A_e=0x7,
    dRes_INDEX_DOC1_BCK_DOC_F_CONFUSED_B_e=0x8,
    dRes_INDEX_DOC1_BCK_DOC_F_HISO_TALK_A_e=0x9,
    dRes_INDEX_DOC1_BCK_DOC_F_HISO_TALK_C_e=0xA,
    dRes_INDEX_DOC1_BCK_DOC_F_MOJI_TALK_A_e=0xB,
    dRes_INDEX_DOC1_BCK_DOC_F_MOJI_TALK_C_e=0xC,
    dRes_INDEX_DOC1_BCK_DOC_FH_HISO_TALK_B_e=0xD,
    dRes_INDEX_DOC1_BCK_DOC_FH_MOJI_TALK_B_e=0xE,
    dRes_INDEX_DOC1_BCK_DOC_HISO_TALK_A_e=0xF,
    dRes_INDEX_DOC1_BCK_DOC_HISO_TALK_B_e=0x10,
    dRes_INDEX_DOC1_BCK_DOC_HISO_TALK_C_e=0x11,
    dRes_INDEX_DOC1_BCK_DOC_MOJI_TALK_A_e=0x12,
    dRes_INDEX_DOC1_BCK_DOC_MOJI_TALK_B_e=0x13,
    dRes_INDEX_DOC1_BCK_DOC_MOJI_TALK_C_e=0x14,
    dRes_INDEX_DOC1_BCK_DOC_WALK_A_e=0x15,
    /* BTK  */
    dRes_INDEX_DOC1_BTK_DOC_CONFUSED_A_e=0x18,
    dRes_INDEX_DOC1_BTK_DOC_CONFUSED_B_e=0x19,
    dRes_INDEX_DOC1_BTK_DOC_HISO_TALK_A_e=0x1A,
    dRes_INDEX_DOC1_BTK_DOC_HISO_TALK_B_e=0x1B,
    dRes_INDEX_DOC1_BTK_DOC_HISO_TALK_C_e=0x1C,
    dRes_INDEX_DOC1_BTK_DOC_MOJI_TALK_A_e=0x1D,
    dRes_INDEX_DOC1_BTK_DOC_MOJI_TALK_B_e=0x1E,
    dRes_INDEX_DOC1_BTK_DOC_MOJI_TALK_C_e=0x1F,
    /* BTP  */
    dRes_INDEX_DOC1_BTP_DOC_F_HISO_TALK_A_e=0x22,
    dRes_INDEX_DOC1_BTP_DOC_F_HISO_TALK_C_e=0x23,
    dRes_INDEX_DOC1_BTP_DOC_F_MOJI_TALK_A_e=0x24,
    dRes_INDEX_DOC1_BTP_DOC_F_MOJI_TALK_C_e=0x25,
    dRes_INDEX_DOC1_BTP_DOC_FH_HISO_TALK_B_e=0x26,
    dRes_INDEX_DOC1_BTP_DOC_FH_MOJI_TALK_B_e=0x27,
};

enum dRes_ID_DOC1 {
    /* BCK  */
    dRes_ID_DOC1_BCK_DOC_CONFUSED_A_e=0x5,
    dRes_ID_DOC1_BCK_DOC_CONFUSED_B_e=0x6,
    dRes_ID_DOC1_BCK_DOC_F_CONFUSED_A_e=0x7,
    dRes_ID_DOC1_BCK_DOC_F_CONFUSED_B_e=0x8,
    dRes_ID_DOC1_BCK_DOC_F_HISO_TALK_A_e=0x9,
    dRes_ID_DOC1_BCK_DOC_F_HISO_TALK_C_e=0xA,
    dRes_ID_DOC1_BCK_DOC_F_MOJI_TALK_A_e=0xB,
    dRes_ID_DOC1_BCK_DOC_F_MOJI_TALK_C_e=0xC,
    dRes_ID_DOC1_BCK_DOC_FH_HISO_TALK_B_e=0xD,
    dRes_ID_DOC1_BCK_DOC_FH_MOJI_TALK_B_e=0xE,
    dRes_ID_DOC1_BCK_DOC_HISO_TALK_A_e=0xF,
    dRes_ID_DOC1_BCK_DOC_HISO_TALK_B_e=0x10,
    dRes_ID_DOC1_BCK_DOC_HISO_TALK_C_e=0x11,
    dRes_ID_DOC1_BCK_DOC_MOJI_TALK_A_e=0x12,
    dRes_ID_DOC1_BCK_DOC_MOJI_TALK_B_e=0x13,
    dRes_ID_DOC1_BCK_DOC_MOJI_TALK_C_e=0x14,
    dRes_ID_DOC1_BCK_DOC_WALK_A_e=0x15,
    /* BTK  */
    dRes_ID_DOC1_BTK_DOC_CONFUSED_A_e=0x18,
    dRes_ID_DOC1_BTK_DOC_CONFUSED_B_e=0x19,
    dRes_ID_DOC1_BTK_DOC_HISO_TALK_A_e=0x1A,
    dRes_ID_DOC1_BTK_DOC_HISO_TALK_B_e=0x1B,
    dRes_ID_DOC1_BTK_DOC_HISO_TALK_C_e=0x1C,
    dRes_ID_DOC1_BTK_DOC_MOJI_TALK_A_e=0x1D,
    dRes_ID_DOC1_BTK_DOC_MOJI_TALK_B_e=0x1E,
    dRes_ID_DOC1_BTK_DOC_MOJI_TALK_C_e=0x1F,
    /* BTP  */
    dRes_ID_DOC1_BTP_DOC_F_HISO_TALK_A_e=0x22,
    dRes_ID_DOC1_BTP_DOC_F_HISO_TALK_C_e=0x23,
    dRes_ID_DOC1_BTP_DOC_F_MOJI_TALK_A_e=0x24,
    dRes_ID_DOC1_BTP_DOC_F_MOJI_TALK_C_e=0x25,
    dRes_ID_DOC1_BTP_DOC_FH_HISO_TALK_B_e=0x26,
    dRes_ID_DOC1_BTP_DOC_FH_MOJI_TALK_B_e=0x27,
};

#endif /* !RES_DOC1_H */