#ifndef RES_GRO1_H
#define RES_GRO1_H

enum dRes_INDEX_GRO1 {
    /* BCK  */
    dRes_INDEX_GRO1_BCK_GRO_BOKIN_WAIT_e=0x5,
    dRes_INDEX_GRO1_BCK_GRO_BOW_e=0x6,
    dRes_INDEX_GRO1_BCK_GRO_CALL_e=0x7,
    dRes_INDEX_GRO1_BCK_GRO_CALL_WAIT_e=0x8,
    dRes_INDEX_GRO1_BCK_GRO_F_BOKIN_e=0x9,
    dRes_INDEX_GRO1_BCK_GRO_F_BOW_e=0xA,
    dRes_INDEX_GRO1_BCK_GRO_F_CALL_e=0xB,
    dRes_INDEX_GRO1_BCK_GRO_F_CALL_B_e=0xC,
    dRes_INDEX_GRO1_BCK_GRO_F_SWING_e=0xD,
    dRes_INDEX_GRO1_BCK_GRO_FH_BOKIN_e=0xE,
    dRes_INDEX_GRO1_BCK_GRO_FH_BOW_e=0xF,
    dRes_INDEX_GRO1_BCK_GRO_FH_CALL_WAIT_e=0x10,
    dRes_INDEX_GRO1_BCK_GRO_SWING_e=0x11,
    /* BMDR */
    dRes_INDEX_GRO1_BMD_MARO_BOKIN_e=0x14,
    /* BTP  */
    dRes_INDEX_GRO1_BTP_GRO_F_BOW_e=0x17,
    dRes_INDEX_GRO1_BTP_GRO_F_CALL_e=0x18,
    dRes_INDEX_GRO1_BTP_GRO_F_CALL_B_e=0x19,
    dRes_INDEX_GRO1_BTP_GRO_FH_CALL_WAIT_e=0x1A,
};

enum dRes_ID_GRO1 {
    /* BCK  */
    dRes_ID_GRO1_BCK_GRO_BOKIN_WAIT_e=0x5,
    dRes_ID_GRO1_BCK_GRO_BOW_e=0x6,
    dRes_ID_GRO1_BCK_GRO_CALL_e=0x7,
    dRes_ID_GRO1_BCK_GRO_CALL_WAIT_e=0x8,
    dRes_ID_GRO1_BCK_GRO_F_BOKIN_e=0x9,
    dRes_ID_GRO1_BCK_GRO_F_BOW_e=0xA,
    dRes_ID_GRO1_BCK_GRO_F_CALL_e=0xB,
    dRes_ID_GRO1_BCK_GRO_F_CALL_B_e=0xC,
    dRes_ID_GRO1_BCK_GRO_F_SWING_e=0xD,
    dRes_ID_GRO1_BCK_GRO_FH_BOKIN_e=0xE,
    dRes_ID_GRO1_BCK_GRO_FH_BOW_e=0xF,
    dRes_ID_GRO1_BCK_GRO_FH_CALL_WAIT_e=0x10,
    dRes_ID_GRO1_BCK_GRO_SWING_e=0x11,
    /* BMDR */
    dRes_ID_GRO1_BMD_MARO_BOKIN_e=0x14,
    /* BTP  */
    dRes_ID_GRO1_BTP_GRO_F_BOW_e=0x17,
    dRes_ID_GRO1_BTP_GRO_F_CALL_e=0x18,
    dRes_ID_GRO1_BTP_GRO_F_CALL_B_e=0x19,
    dRes_ID_GRO1_BTP_GRO_FH_CALL_WAIT_e=0x1A,
};

enum MARO_BOKIN_JNT {
    MARO_BOKIN_JNT_MARO_BOKIN_e=0x0,
};

#endif /* !RES_GRO1_H */