#ifndef RES_L4_N_ENTR_H
#define RES_L4_N_ENTR_H

enum dRes_INDEX_L4_N_ENTR {
    /* BMDR */
    dRes_INDEX_L4_N_ENTR_BMD_LV4_NORTHENTRANCE_e=0x4,
    /* DZB  */
    dRes_INDEX_L4_N_ENTR_DZB_LV4_NORTHENTRANCE_e=0x7,
};

enum dRes_ID_L4_N_ENTR {
    /* BMDR */
    dRes_ID_L4_N_ENTR_BMD_LV4_NORTHENTRANCE_e=0x4,
    /* DZB  */
    dRes_ID_L4_N_ENTR_DZB_LV4_NORTHENTRANCE_e=0x7,
};

enum LV4_NORTHENTRANCE_JNT {
    LV4_NORTHENTRANCE_JNT_WORLD_ROOT_e=0x0,
};

#endif /* !RES_L4_N_ENTR_H */