#ifndef RES_LV6GATE_H
#define RES_LV6GATE_H

enum dRes_INDEX_LV6GATE {
    /* BCK  */
    dRes_INDEX_LV6GATE_BCK_FSWMPULL_e=0x8,
    dRes_INDEX_LV6GATE_BCK_FSWMSTICK_e=0x9,
    dRes_INDEX_LV6GATE_BCK_SWMPULL_e=0xA,
    dRes_INDEX_LV6GATE_BCK_SWMSTICK_e=0xB,
    dRes_INDEX_LV6GATE_BCK_SWMWAIT_e=0xC,
    /* BMDR */
    dRes_INDEX_LV6GATE_BMD_A_SMKAIDAN_e=0xF,
    dRes_INDEX_LV6GATE_BMD_A_SMSTGLASS_e=0x10,
    /* BTK  */
    dRes_INDEX_LV6GATE_BTK_A_SMKAIDAN_e=0x13,
    dRes_INDEX_LV6GATE_BTK_A_SMKAIDAN_02_e=0x14,
    dRes_INDEX_LV6GATE_BTK_FSWMSTICK_e=0x15,
    /* BTP  */
    dRes_INDEX_LV6GATE_BTP_FSWMSTICK_e=0x18,
    /* DZB  */
    dRes_INDEX_LV6GATE_DZB_A_SMKAIDAN_e=0x1B,
    dRes_INDEX_LV6GATE_DZB_A_SMSTGLASS_e=0x1C,
    /* EVT  */
    dRes_INDEX_LV6GATE_DAT_EVENT_LIST_e=0x1F,
};

enum dRes_ID_LV6GATE {
    /* BCK  */
    dRes_ID_LV6GATE_BCK_FSWMPULL_e=0x8,
    dRes_ID_LV6GATE_BCK_FSWMSTICK_e=0x9,
    dRes_ID_LV6GATE_BCK_SWMPULL_e=0xA,
    dRes_ID_LV6GATE_BCK_SWMSTICK_e=0xB,
    dRes_ID_LV6GATE_BCK_SWMWAIT_e=0xC,
    /* BMDR */
    dRes_ID_LV6GATE_BMD_A_SMKAIDAN_e=0xF,
    dRes_ID_LV6GATE_BMD_A_SMSTGLASS_e=0x10,
    /* BTK  */
    dRes_ID_LV6GATE_BTK_A_SMKAIDAN_e=0x13,
    dRes_ID_LV6GATE_BTK_A_SMKAIDAN_02_e=0x14,
    dRes_ID_LV6GATE_BTK_FSWMSTICK_e=0x15,
    /* BTP  */
    dRes_ID_LV6GATE_BTP_FSWMSTICK_e=0x18,
    /* DZB  */
    dRes_ID_LV6GATE_DZB_A_SMKAIDAN_e=0x1B,
    dRes_ID_LV6GATE_DZB_A_SMSTGLASS_e=0x1C,
    /* EVT  */
    dRes_ID_LV6GATE_DAT_EVENT_LIST_e=0x1F,
};

enum A_SMKAIDAN_JNT {
    A_SMKAIDAN_JNT_WORLD_ROOT_e=0x0,
};

enum A_SMSTGLASS_JNT {
    A_SMSTGLASS_JNT_WORLD_ROOT_e=0x0,
};

#endif /* !RES_LV6GATE_H */