#ifndef RES_M_VOLCBOM_H
#define RES_M_VOLCBOM_H

enum dRes_INDEX_M_VOLCBOM {
    /* BCK  */
    dRes_INDEX_M_VOLCBOM_BCK_NI_VOLCBOM_EF_e=0x8,
    /* BMDR */
    dRes_INDEX_M_VOLCBOM_BMD_EF_VOLCBOM_e=0xB,
    dRes_INDEX_M_VOLCBOM_BMD_M_VOLCBOM_e=0xC,
    /* BRK  */
    dRes_INDEX_M_VOLCBOM_BRK_EF_VOLCBOM_e=0xF,
    dRes_INDEX_M_VOLCBOM_BRK_M_VOLCBOM_e=0x10,
    /* BTK  */
    dRes_INDEX_M_VOLCBOM_BTK_EF_VOLCBOM_e=0x13,
    dRes_INDEX_M_VOLCBOM_BTK_M_VOLCBOM_e=0x14,
    dRes_INDEX_M_VOLCBOM_BTK_NI_VOLCBOM_EF_e=0x15,
    /* DZB  */
    dRes_INDEX_M_VOLCBOM_DZB_M_VOLCBOM_e=0x18,
    /* EVT  */
    dRes_INDEX_M_VOLCBOM_DAT_EVENT_LIST_e=0x1B,
};

enum dRes_ID_M_VOLCBOM {
    /* BCK  */
    dRes_ID_M_VOLCBOM_BCK_NI_VOLCBOM_EF_e=0x8,
    /* BMDR */
    dRes_ID_M_VOLCBOM_BMD_EF_VOLCBOM_e=0xB,
    dRes_ID_M_VOLCBOM_BMD_M_VOLCBOM_e=0xC,
    /* BRK  */
    dRes_ID_M_VOLCBOM_BRK_EF_VOLCBOM_e=0xF,
    dRes_ID_M_VOLCBOM_BRK_M_VOLCBOM_e=0x10,
    /* BTK  */
    dRes_ID_M_VOLCBOM_BTK_EF_VOLCBOM_e=0x13,
    dRes_ID_M_VOLCBOM_BTK_M_VOLCBOM_e=0x14,
    dRes_ID_M_VOLCBOM_BTK_NI_VOLCBOM_EF_e=0x15,
    /* DZB  */
    dRes_ID_M_VOLCBOM_DZB_M_VOLCBOM_e=0x18,
    /* EVT  */
    dRes_ID_M_VOLCBOM_DAT_EVENT_LIST_e=0x1B,
};

enum EF_VOLCBOM_JNT {
    EF_VOLCBOM_JNT_WORLD_ROOT_e=0x0,
    EF_VOLCBOM_JNT_EF_VOLC00_SARA_e=0x1,
    EF_VOLCBOM_JNT_EF_VOLC01_TAIL_e=0x2,
};

enum M_VOLCBOM_JNT {
    M_VOLCBOM_JNT_NI_VOLCBOM_EF_e=0x0,
    M_VOLCBOM_JNT_EFFECT_P_e=0x1,
};

#endif /* !RES_M_VOLCBOM_H */