#ifndef RES_TOGEROL_H
#define RES_TOGEROL_H

enum dRes_INDEX_TOGEROL {
    /* BMDR */
    dRes_INDEX_TOGEROL_BMD_LV6_OBJ_TOGEROLL_e=0x4,
    /* DZB  */
    dRes_INDEX_TOGEROL_DZB_LV6_OBJ_TOGEROLL_e=0x7,
};

enum dRes_ID_TOGEROL {
    /* BMDR */
    dRes_ID_TOGEROL_BMD_LV6_OBJ_TOGEROLL_e=0x4,
    /* DZB  */
    dRes_ID_TOGEROL_DZB_LV6_OBJ_TOGEROLL_e=0x7,
};

enum LV6_OBJ_TOGEROLL_JNT {
    LV6_OBJ_TOGEROLL_JNT_WORLD_ROOT_e=0x0,
};

#endif /* !RES_TOGEROL_H */