#ifndef RES_KAKASHI_H
#define RES_KAKASHI_H

enum dRes_INDEX_KAKASHI {
    /* BCK  */
    dRes_INDEX_KAKASHI_BCK_KAKASHI_FALL_e=0x5,
    /* BMDR */
    dRes_INDEX_KAKASHI_BMD_BACKETL_e=0x8,
    dRes_INDEX_KAKASHI_BMD_BACKETR_e=0x9,
    dRes_INDEX_KAKASHI_BMD_KAKASHI_e=0xA,
    /* EVT  */
    dRes_INDEX_KAKASHI_DAT_EVENT_LIST_e=0xD,
};

enum dRes_ID_KAKASHI {
    /* BCK  */
    dRes_ID_KAKASHI_BCK_KAKASHI_FALL_e=0x5,
    /* BMDR */
    dRes_ID_KAKASHI_BMD_BACKETL_e=0x8,
    dRes_ID_KAKASHI_BMD_BACKETR_e=0x9,
    dRes_ID_KAKASHI_BMD_KAKASHI_e=0xA,
    /* EVT  */
    dRes_ID_KAKASHI_DAT_EVENT_LIST_e=0xD,
};

enum BACKETL_JNT {
    BACKETL_JNT_BACKETL_MODEL_e=0x0,
};

enum BACKETR_JNT {
    BACKETR_JNT_KAKASHIR_MODEL_e=0x0,
};

enum KAKASHI_JNT {
    KAKASHI_JNT_BODY1_e=0x0,
    KAKASHI_JNT_BODY2_e=0x1,
    KAKASHI_JNT_ARM_e=0x2,
    KAKASHI_JNT_ARMER_e=0x3,
    KAKASHI_JNT_BACKET_NECK_e=0x4,
    KAKASHI_JNT_BUCKET_e=0x5,
    KAKASHI_JNT_HANDLE_e=0x6,
    KAKASHI_JNT_HEAD_e=0x7,
};

#endif /* !RES_KAKASHI_H */