#ifndef RES_LOGOJPWII_H
#define RES_LOGOJPWII_H

enum dRes_INDEX_LOGOJPWII {
    /* DAT  */
    dRes_INDEX_LOGOJPWII_BTI_STRAP_16_9_832X456_JP_e=0x3,
    dRes_INDEX_LOGOJPWII_BTI_STRAP_608X456_JP_e=0x4,
};

enum dRes_ID_LOGOJPWII {
    /* DAT  */
    dRes_ID_LOGOJPWII_BTI_STRAP_16_9_832X456_JP_e=0x3,
    dRes_ID_LOGOJPWII_BTI_STRAP_608X456_JP_e=0x4,
};

#endif /* !RES_LOGOJPWII_H */