#ifndef RES_POUYAA_H
#define RES_POUYAA_H

enum dRes_INDEX_POUYAA {
    /* BCK  */
    dRes_INDEX_POUYAA_BCK_POUYAA_F_FINE_A_e=0x8,
    dRes_INDEX_POUYAA_BCK_POUYAA_F_FINE_TALK_A_e=0x9,
    dRes_INDEX_POUYAA_BCK_POUYAA_F_HATENA_A_e=0xA,
    dRes_INDEX_POUYAA_BCK_POUYAA_F_WAIT_A_e=0xB,
    dRes_INDEX_POUYAA_BCK_POUYAA_FH_HATENA_A_e=0xC,
    dRes_INDEX_POUYAA_BCK_POUYAA_GENKI_A_e=0xD,
    dRes_INDEX_POUYAA_BCK_POUYAA_HATENA_A_e=0xE,
    dRes_INDEX_POUYAA_BCK_POUYAA_HATENA_B_e=0xF,
    dRes_INDEX_POUYAA_BCK_POUYAA_SAIFU_A_e=0x10,
    dRes_INDEX_POUYAA_BCK_POUYAA_SAIFU_B_e=0x11,
    dRes_INDEX_POUYAA_BCK_POUYAA_WAIT_A_e=0x12,
    dRes_INDEX_POUYAA_BCK_POUYAA_WAIT_B_e=0x13,
    dRes_INDEX_POUYAA_BCK_POUYAA_WAIT_C_e=0x14,
    /* BMDE */
    dRes_INDEX_POUYAA_BMD_MIE_e=0x17,
    /* BMDV */
    dRes_INDEX_POUYAA_BMD_POUYAA_e=0x1A,
    /* BRK  */
    dRes_INDEX_POUYAA_BRK_POUYAA_RUPY_EYE_KOUFUN_01_e=0x1D,
    dRes_INDEX_POUYAA_BRK_POUYAA_RUPY_EYE_KOUFUN_02_e=0x1E,
    dRes_INDEX_POUYAA_BRK_POUYAA_RUPY_EYE_NOMAL_e=0x1F,
    dRes_INDEX_POUYAA_BRK_POUYAA_RUPY_EYE_UTTAE_01_e=0x20,
    dRes_INDEX_POUYAA_BRK_POUYAA_RUPY_EYE_UTTAE_02_e=0x21,
    /* BTK  */
    dRes_INDEX_POUYAA_BTK_POUYAA_RUPY_e=0x24,
    /* EVT  */
    dRes_INDEX_POUYAA_DAT_EVENT_LIST_e=0x27,
};

enum dRes_ID_POUYAA {
    /* BCK  */
    dRes_ID_POUYAA_BCK_POUYAA_F_FINE_A_e=0x8,
    dRes_ID_POUYAA_BCK_POUYAA_F_FINE_TALK_A_e=0x9,
    dRes_ID_POUYAA_BCK_POUYAA_F_HATENA_A_e=0xA,
    dRes_ID_POUYAA_BCK_POUYAA_F_WAIT_A_e=0xB,
    dRes_ID_POUYAA_BCK_POUYAA_FH_HATENA_A_e=0xC,
    dRes_ID_POUYAA_BCK_POUYAA_GENKI_A_e=0xD,
    dRes_ID_POUYAA_BCK_POUYAA_HATENA_A_e=0xE,
    dRes_ID_POUYAA_BCK_POUYAA_HATENA_B_e=0xF,
    dRes_ID_POUYAA_BCK_POUYAA_SAIFU_A_e=0x10,
    dRes_ID_POUYAA_BCK_POUYAA_SAIFU_B_e=0x11,
    dRes_ID_POUYAA_BCK_POUYAA_WAIT_A_e=0x12,
    dRes_ID_POUYAA_BCK_POUYAA_WAIT_B_e=0x13,
    dRes_ID_POUYAA_BCK_POUYAA_WAIT_C_e=0x14,
    /* BMDE */
    dRes_ID_POUYAA_BMD_MIE_e=0x17,
    /* BMDV */
    dRes_ID_POUYAA_BMD_POUYAA_e=0x1A,
    /* BRK  */
    dRes_ID_POUYAA_BRK_POUYAA_RUPY_EYE_KOUFUN_01_e=0x1D,
    dRes_ID_POUYAA_BRK_POUYAA_RUPY_EYE_KOUFUN_02_e=0x1E,
    dRes_ID_POUYAA_BRK_POUYAA_RUPY_EYE_NOMAL_e=0x1F,
    dRes_ID_POUYAA_BRK_POUYAA_RUPY_EYE_UTTAE_01_e=0x20,
    dRes_ID_POUYAA_BRK_POUYAA_RUPY_EYE_UTTAE_02_e=0x21,
    /* BTK  */
    dRes_ID_POUYAA_BTK_POUYAA_RUPY_e=0x24,
    /* EVT  */
    dRes_ID_POUYAA_DAT_EVENT_LIST_e=0x27,
};

enum MIE_JNT {
    MIE_JNT_MIE_MODEL_e=0x0,
};

enum POUYAA_JNT {
    POUYAA_JNT_CENTER_e=0x0,
    POUYAA_JNT_BACKBONE1_e=0x1,
    POUYAA_JNT_BACKBONE2_e=0x2,
    POUYAA_JNT_NECK_e=0x3,
    POUYAA_JNT_HEAD_e=0x4,
    POUYAA_JNT_CHIN_e=0x5,
    POUYAA_JNT_MAYUL_e=0x6,
    POUYAA_JNT_MAYUR_e=0x7,
    POUYAA_JNT_MOUTH_e=0x8,
    POUYAA_JNT_SHOULDERL_e=0x9,
    POUYAA_JNT_ARML1_e=0xA,
    POUYAA_JNT_ARML2_e=0xB,
    POUYAA_JNT_HANDL_e=0xC,
    POUYAA_JNT_FINGERL_e=0xD,
    POUYAA_JNT_SHOULDERR_e=0xE,
    POUYAA_JNT_ARMR1_e=0xF,
    POUYAA_JNT_ARMR2_e=0x10,
    POUYAA_JNT_HANDR_e=0x11,
    POUYAA_JNT_FINGERR_e=0x12,
    POUYAA_JNT_WAIST_e=0x13,
    POUYAA_JNT_LEGL1_e=0x14,
    POUYAA_JNT_LEGL2_e=0x15,
    POUYAA_JNT_FOOTL_e=0x16,
    POUYAA_JNT_LEGR1_e=0x17,
    POUYAA_JNT_LEGR2_e=0x18,
    POUYAA_JNT_FOOTR_e=0x19,
};

#endif /* !RES_POUYAA_H */