#ifndef RES_SEIC_H
#define RES_SEIC_H

enum dRes_INDEX_SEIC {
    /* BCK  */
    dRes_INDEX_SEIC_BCK_SEIC_WING_A_e=0x6,
    /* BMDR */
    dRes_INDEX_SEIC_BMD_SEIC_NOMAL_e=0x9,
    /* BRK  */
    dRes_INDEX_SEIC_BRK_SEIC_NOMAL_e=0xC,
    /* BTK  */
    dRes_INDEX_SEIC_BTK_SEIC_NOMAL_e=0xF,
};

enum dRes_ID_SEIC {
    /* BCK  */
    dRes_ID_SEIC_BCK_SEIC_WING_A_e=0x6,
    /* BMDR */
    dRes_ID_SEIC_BMD_SEIC_NOMAL_e=0x9,
    /* BRK  */
    dRes_ID_SEIC_BRK_SEIC_NOMAL_e=0xC,
    /* BTK  */
    dRes_ID_SEIC_BTK_SEIC_NOMAL_e=0xF,
};

enum SEIC_NOMAL_JNT {
    SEIC_NOMAL_JNT_WORLD_ROOT_e=0x0,
    SEIC_NOMAL_JNT_CENTER_e=0x1,
    SEIC_NOMAL_JNT_BACKBORN1_e=0x2,
    SEIC_NOMAL_JNT_BACKBORN2_e=0x3,
    SEIC_NOMAL_JNT_NECK_e=0x4,
    SEIC_NOMAL_JNT_HEAD_e=0x5,
    SEIC_NOMAL_JNT_CHIN_e=0x6,
    SEIC_NOMAL_JNT_MOUTH_e=0x7,
    SEIC_NOMAL_JNT_HIGE_L_e=0x8,
    SEIC_NOMAL_JNT_HIGE_R_e=0x9,
    SEIC_NOMAL_JNT_SHOULDER_L_e=0xA,
    SEIC_NOMAL_JNT_WING_L_1_e=0xB,
    SEIC_NOMAL_JNT_WING_L_2_e=0xC,
    SEIC_NOMAL_JNT_WING_L_3_e=0xD,
    SEIC_NOMAL_JNT_WING_L_4_e=0xE,
    SEIC_NOMAL_JNT_WING_L_5_e=0xF,
    SEIC_NOMAL_JNT_SHOULDER_R_e=0x10,
    SEIC_NOMAL_JNT_WING_R_1_e=0x11,
    SEIC_NOMAL_JNT_WING_R_2_e=0x12,
    SEIC_NOMAL_JNT_WING_R_3_e=0x13,
    SEIC_NOMAL_JNT_WING_R_4_e=0x14,
    SEIC_NOMAL_JNT_WING_R_5_e=0x15,
    SEIC_NOMAL_JNT_WAIST_e=0x16,
    SEIC_NOMAL_JNT_LEG_L_1_e=0x17,
    SEIC_NOMAL_JNT_LEG_L_2_e=0x18,
    SEIC_NOMAL_JNT_FOOT_L_e=0x19,
    SEIC_NOMAL_JNT_FINGER_L_1_e=0x1A,
    SEIC_NOMAL_JNT_THMB_L_e=0x1B,
    SEIC_NOMAL_JNT_LEG_R_1_e=0x1C,
    SEIC_NOMAL_JNT_LEG_R_2_e=0x1D,
    SEIC_NOMAL_JNT_FOOT_R_e=0x1E,
    SEIC_NOMAL_JNT_FINGER_R_1_e=0x1F,
    SEIC_NOMAL_JNT_THMB_R_e=0x20,
    SEIC_NOMAL_JNT_TAIL1_e=0x21,
    SEIC_NOMAL_JNT_TAIL2_e=0x22,
    SEIC_NOMAL_JNT_SIZUKU_e=0x23,
};

#endif /* !RES_SEIC_H */