#ifndef RES_L6LBLOCK_H
#define RES_L6LBLOCK_H

enum dRes_INDEX_L6LBLOCK {
    /* BMDR */
    dRes_INDEX_L6LBLOCK_BMD_LV6_OBJ_632BLOCK_e=0x4,
    /* DZB  */
    dRes_INDEX_L6LBLOCK_DZB_LV6_OBJ_632BLOCK_e=0x7,
};

enum dRes_ID_L6LBLOCK {
    /* BMDR */
    dRes_ID_L6LBLOCK_BMD_LV6_OBJ_632BLOCK_e=0x4,
    /* DZB  */
    dRes_ID_L6LBLOCK_DZB_LV6_OBJ_632BLOCK_e=0x7,
};

enum LV6_OBJ_632BLOCK_JNT {
    LV6_OBJ_632BLOCK_JNT_WORLD_ROOT_e=0x0,
};

#endif /* !RES_L6LBLOCK_H */