#ifndef RES_SEIRA_P1_H
#define RES_SEIRA_P1_H

enum dRes_INDEX_SEIRA_P1 {
    /* BCK  */
    dRes_INDEX_SEIRA_P1_BCK_SERA_F_HAPPYTALK_e=0x5,
    dRes_INDEX_SEIRA_P1_BCK_SERA_F_SAD_e=0x6,
    dRes_INDEX_SEIRA_P1_BCK_SERA_F_SMILE_e=0x7,
    dRes_INDEX_SEIRA_P1_BCK_SERA_F_TALK_A_e=0x8,
    dRes_INDEX_SEIRA_P1_BCK_SERA_F_WORRYTALK_e=0x9,
    dRes_INDEX_SEIRA_P1_BCK_SERA_FH_SAD_e=0xA,
    dRes_INDEX_SEIRA_P1_BCK_SERA_LOOKAROUND_e=0xB,
    dRes_INDEX_SEIRA_P1_BCK_SERA_STEP_e=0xC,
    dRes_INDEX_SEIRA_P1_BCK_SERA_TALK_A_e=0xD,
    dRes_INDEX_SEIRA_P1_BCK_SERA_WAIT_A_e=0xE,
    /* BTK  */
    dRes_INDEX_SEIRA_P1_BTK_SERA_e=0x11,
    /* BTP  */
    dRes_INDEX_SEIRA_P1_BTP_SERA_e=0x14,
    dRes_INDEX_SEIRA_P1_BTP_SERA_F_HAPPYTALK_e=0x15,
    dRes_INDEX_SEIRA_P1_BTP_SERA_F_SAD_e=0x16,
    dRes_INDEX_SEIRA_P1_BTP_SERA_F_SMILE_e=0x17,
    dRes_INDEX_SEIRA_P1_BTP_SERA_F_WORRYTALK_e=0x18,
    dRes_INDEX_SEIRA_P1_BTP_SERA_FH_SAD_e=0x19,
};

enum dRes_ID_SEIRA_P1 {
    /* BCK  */
    dRes_ID_SEIRA_P1_BCK_SERA_F_HAPPYTALK_e=0x5,
    dRes_ID_SEIRA_P1_BCK_SERA_F_SAD_e=0x6,
    dRes_ID_SEIRA_P1_BCK_SERA_F_SMILE_e=0x7,
    dRes_ID_SEIRA_P1_BCK_SERA_F_TALK_A_e=0x8,
    dRes_ID_SEIRA_P1_BCK_SERA_F_WORRYTALK_e=0x9,
    dRes_ID_SEIRA_P1_BCK_SERA_FH_SAD_e=0xA,
    dRes_ID_SEIRA_P1_BCK_SERA_LOOKAROUND_e=0xB,
    dRes_ID_SEIRA_P1_BCK_SERA_STEP_e=0xC,
    dRes_ID_SEIRA_P1_BCK_SERA_TALK_A_e=0xD,
    dRes_ID_SEIRA_P1_BCK_SERA_WAIT_A_e=0xE,
    /* BTK  */
    dRes_ID_SEIRA_P1_BTK_SERA_e=0x11,
    /* BTP  */
    dRes_ID_SEIRA_P1_BTP_SERA_e=0x14,
    dRes_ID_SEIRA_P1_BTP_SERA_F_HAPPYTALK_e=0x15,
    dRes_ID_SEIRA_P1_BTP_SERA_F_SAD_e=0x16,
    dRes_ID_SEIRA_P1_BTP_SERA_F_SMILE_e=0x17,
    dRes_ID_SEIRA_P1_BTP_SERA_F_WORRYTALK_e=0x18,
    dRes_ID_SEIRA_P1_BTP_SERA_FH_SAD_e=0x19,
};

#endif /* !RES_SEIRA_P1_H */