#ifndef RES_YELIA1_H
#define RES_YELIA1_H

enum dRes_INDEX_YELIA1 {
    /* BCK  */
    dRes_INDEX_YELIA1_BCK_YELIA_F_HORSE_LOOKBACK_e=0x5,
    dRes_INDEX_YELIA1_BCK_YELIA_F_HORSE_RETURN_e=0x6,
    dRes_INDEX_YELIA1_BCK_YELIA_HORSE_LOOKBACK_e=0x7,
    dRes_INDEX_YELIA1_BCK_YELIA_HORSE_RETURN_e=0x8,
    dRes_INDEX_YELIA1_BCK_YELIA_HORSE_TALK_A_e=0x9,
    dRes_INDEX_YELIA1_BCK_YELIA_HORSE_WAIT_A_e=0xA,
    dRes_INDEX_YELIA1_BCK_YELIA_HORSE_WAIT_C_e=0xB,
    /* BTK  */
    dRes_INDEX_YELIA1_BTK_YELIA_HORSE_RETURN_e=0xE,
    dRes_INDEX_YELIA1_BTK_YELIA_HORSE_WAIT_A_e=0xF,
    /* BTP  */
    dRes_INDEX_YELIA1_BTP_YELIA_F_HORSE_LOOKBACK_e=0x12,
    dRes_INDEX_YELIA1_BTP_YELIA_F_HORSE_RETURN_e=0x13,
};

enum dRes_ID_YELIA1 {
    /* BCK  */
    dRes_ID_YELIA1_BCK_YELIA_F_HORSE_LOOKBACK_e=0x5,
    dRes_ID_YELIA1_BCK_YELIA_F_HORSE_RETURN_e=0x6,
    dRes_ID_YELIA1_BCK_YELIA_HORSE_LOOKBACK_e=0x7,
    dRes_ID_YELIA1_BCK_YELIA_HORSE_RETURN_e=0x8,
    dRes_ID_YELIA1_BCK_YELIA_HORSE_TALK_A_e=0x9,
    dRes_ID_YELIA1_BCK_YELIA_HORSE_WAIT_A_e=0xA,
    dRes_ID_YELIA1_BCK_YELIA_HORSE_WAIT_C_e=0xB,
    /* BTK  */
    dRes_ID_YELIA1_BTK_YELIA_HORSE_RETURN_e=0xE,
    dRes_ID_YELIA1_BTK_YELIA_HORSE_WAIT_A_e=0xF,
    /* BTP  */
    dRes_ID_YELIA1_BTP_YELIA_F_HORSE_LOOKBACK_e=0x12,
    dRes_ID_YELIA1_BTP_YELIA_F_HORSE_RETURN_e=0x13,
};

#endif /* !RES_YELIA1_H */