#ifndef RES_SCANCRS_H
#define RES_SCANCRS_H

enum dRes_INDEX_SCANCRS {
    /* BCK  */
    dRes_INDEX_SCANCRS_BCK_NI_SKYCANNON_CRASH_EF_e=0x7,
    /* BMDR */
    dRes_INDEX_SCANCRS_BMD_NI_SKYCANNON_CRASH_EF_e=0xA,
    /* BTK  */
    dRes_INDEX_SCANCRS_BTK_NI_SKYCANNON_CRASH_EF_e=0xD,
    /* DZB  */
    dRes_INDEX_SCANCRS_DZB_U_SKYCANNON_CRASH_e=0x10,
    /* EVT  */
    dRes_INDEX_SCANCRS_DAT_EVENT_LIST_e=0x13,
};

enum dRes_ID_SCANCRS {
    /* BCK  */
    dRes_ID_SCANCRS_BCK_NI_SKYCANNON_CRASH_EF_e=0x7,
    /* BMDR */
    dRes_ID_SCANCRS_BMD_NI_SKYCANNON_CRASH_EF_e=0xA,
    /* BTK  */
    dRes_ID_SCANCRS_BTK_NI_SKYCANNON_CRASH_EF_e=0xD,
    /* DZB  */
    dRes_ID_SCANCRS_DZB_U_SKYCANNON_CRASH_e=0x10,
    /* EVT  */
    dRes_ID_SCANCRS_DAT_EVENT_LIST_e=0x13,
};

enum NI_SKYCANNON_CRASH_EF_JNT {
    NI_SKYCANNON_CRASH_EF_JNT_CENTER_e=0x0,
    NI_SKYCANNON_CRASH_EF_JNT_EFFECT_P_e=0x1,
    NI_SKYCANNON_CRASH_EF_JNT_PARTS_A_e=0x2,
    NI_SKYCANNON_CRASH_EF_JNT_PARTS_B_e=0x3,
};

#endif /* !RES_SCANCRS_H */