#ifndef RES_URI1_H
#define RES_URI1_H

enum dRes_INDEX_URI1 {
    /* BCK  */
    dRes_INDEX_URI1_BCK_URI_F_K_RUN_e=0x7,
    dRes_INDEX_URI1_BCK_URI_F_LOOKING_e=0x8,
    dRes_INDEX_URI1_BCK_URI_F_SMILE_e=0x9,
    dRes_INDEX_URI1_BCK_URI_F_TALK_B_e=0xA,
    dRes_INDEX_URI1_BCK_URI_F_TALK_C_e=0xB,
    dRes_INDEX_URI1_BCK_URI_F_TALK_D_e=0xC,
    dRes_INDEX_URI1_BCK_URI_F_THINKING_e=0xD,
    dRes_INDEX_URI1_BCK_URI_FH_SMILE_e=0xE,
    dRes_INDEX_URI1_BCK_URI_FH_TALK_D_e=0xF,
    dRes_INDEX_URI1_BCK_URI_K_HAPPY_TALK_e=0x10,
    dRes_INDEX_URI1_BCK_URI_K_HAPPY_WAIT_e=0x11,
    dRes_INDEX_URI1_BCK_URI_K_RUN_e=0x12,
    dRes_INDEX_URI1_BCK_URI_K_STEP_e=0x13,
    dRes_INDEX_URI1_BCK_URI_K_TALK_A_e=0x14,
    dRes_INDEX_URI1_BCK_URI_K_TALK_B_e=0x15,
    dRes_INDEX_URI1_BCK_URI_K_WAIT_A_e=0x16,
    dRes_INDEX_URI1_BCK_URI_K_WAIT_B_e=0x17,
    dRes_INDEX_URI1_BCK_URI_K_WALK_B_e=0x18,
    dRes_INDEX_URI1_BCK_URI_K_WALK_C_e=0x19,
    dRes_INDEX_URI1_BCK_URI_LOOKING_e=0x1A,
    dRes_INDEX_URI1_BCK_URI_SIT_e=0x1B,
    dRes_INDEX_URI1_BCK_URI_SIT_B_e=0x1C,
    dRes_INDEX_URI1_BCK_URI_THINKING_e=0x1D,
    dRes_INDEX_URI1_BCK_URI_TO_SIT_NORMAL_e=0x1E,
    /* BMDR */
    dRes_INDEX_URI1_BMD_URI_KAGO_e=0x21,
    /* BTK  */
    dRes_INDEX_URI1_BTK_URI_K_RUN_e=0x24,
    dRes_INDEX_URI1_BTK_URI_LOOKING_e=0x25,
    dRes_INDEX_URI1_BTK_URI_THINKING_e=0x26,
    /* BTP  */
    dRes_INDEX_URI1_BTP_URI_F_LOOKING_e=0x29,
    dRes_INDEX_URI1_BTP_URI_F_SMILE_e=0x2A,
    dRes_INDEX_URI1_BTP_URI_F_TALK_B_e=0x2B,
    dRes_INDEX_URI1_BTP_URI_F_TALK_C_e=0x2C,
    dRes_INDEX_URI1_BTP_URI_F_TALK_D_e=0x2D,
    dRes_INDEX_URI1_BTP_URI_F_THINKING_e=0x2E,
    dRes_INDEX_URI1_BTP_URI_FH_SMILE_e=0x2F,
    /* EVT  */
    dRes_INDEX_URI1_DAT_EVENT_LIST_e=0x32,
};

enum dRes_ID_URI1 {
    /* BCK  */
    dRes_ID_URI1_BCK_URI_F_K_RUN_e=0x7,
    dRes_ID_URI1_BCK_URI_F_LOOKING_e=0x8,
    dRes_ID_URI1_BCK_URI_F_SMILE_e=0x9,
    dRes_ID_URI1_BCK_URI_F_TALK_B_e=0xA,
    dRes_ID_URI1_BCK_URI_F_TALK_C_e=0xB,
    dRes_ID_URI1_BCK_URI_F_TALK_D_e=0xC,
    dRes_ID_URI1_BCK_URI_F_THINKING_e=0xD,
    dRes_ID_URI1_BCK_URI_FH_SMILE_e=0xE,
    dRes_ID_URI1_BCK_URI_FH_TALK_D_e=0xF,
    dRes_ID_URI1_BCK_URI_K_HAPPY_TALK_e=0x10,
    dRes_ID_URI1_BCK_URI_K_HAPPY_WAIT_e=0x11,
    dRes_ID_URI1_BCK_URI_K_RUN_e=0x12,
    dRes_ID_URI1_BCK_URI_K_STEP_e=0x13,
    dRes_ID_URI1_BCK_URI_K_TALK_A_e=0x14,
    dRes_ID_URI1_BCK_URI_K_TALK_B_e=0x15,
    dRes_ID_URI1_BCK_URI_K_WAIT_A_e=0x16,
    dRes_ID_URI1_BCK_URI_K_WAIT_B_e=0x17,
    dRes_ID_URI1_BCK_URI_K_WALK_B_e=0x18,
    dRes_ID_URI1_BCK_URI_K_WALK_C_e=0x19,
    dRes_ID_URI1_BCK_URI_LOOKING_e=0x1A,
    dRes_ID_URI1_BCK_URI_SIT_e=0x1B,
    dRes_ID_URI1_BCK_URI_SIT_B_e=0x1C,
    dRes_ID_URI1_BCK_URI_THINKING_e=0x1D,
    dRes_ID_URI1_BCK_URI_TO_SIT_NORMAL_e=0x1E,
    /* BMDR */
    dRes_ID_URI1_BMD_URI_KAGO_e=0x21,
    /* BTK  */
    dRes_ID_URI1_BTK_URI_K_RUN_e=0x24,
    dRes_ID_URI1_BTK_URI_LOOKING_e=0x25,
    dRes_ID_URI1_BTK_URI_THINKING_e=0x26,
    /* BTP  */
    dRes_ID_URI1_BTP_URI_F_LOOKING_e=0x29,
    dRes_ID_URI1_BTP_URI_F_SMILE_e=0x2A,
    dRes_ID_URI1_BTP_URI_F_TALK_B_e=0x2B,
    dRes_ID_URI1_BTP_URI_F_TALK_C_e=0x2C,
    dRes_ID_URI1_BTP_URI_F_TALK_D_e=0x2D,
    dRes_ID_URI1_BTP_URI_F_THINKING_e=0x2E,
    dRes_ID_URI1_BTP_URI_FH_SMILE_e=0x2F,
    /* EVT  */
    dRes_ID_URI1_DAT_EVENT_LIST_e=0x32,
};

enum URI_KAGO_JNT {
    URI_KAGO_JNT_URI_KAGO_e=0x0,
};

#endif /* !RES_URI1_H */