#ifndef RES_V_SHUTTER_H
#define RES_V_SHUTTER_H

enum dRes_INDEX_V_SHUTTER {
    /* BCK  */
    dRes_INDEX_V_SHUTTER_BCK_V_SHUTTER_e=0x5,
    /* BMDR */
    dRes_INDEX_V_SHUTTER_BMD_V_SHUTTER_e=0x8,
    /* DZB  */
    dRes_INDEX_V_SHUTTER_DZB_V_SHUTTER_e=0xB,
};

enum dRes_ID_V_SHUTTER {
    /* BCK  */
    dRes_ID_V_SHUTTER_BCK_V_SHUTTER_e=0x5,
    /* BMDR */
    dRes_ID_V_SHUTTER_BMD_V_SHUTTER_e=0x8,
    /* DZB  */
    dRes_ID_V_SHUTTER_DZB_V_SHUTTER_e=0xB,
};

enum V_SHUTTER_JNT {
    V_SHUTTER_JNT_SHUTTER_G_e=0x0,
    V_SHUTTER_JNT_POLYSURFACE18301_e=0x1,
    V_SHUTTER_JNT_POLYSURFACE18302_e=0x2,
    V_SHUTTER_JNT_POLYSURFACE18624_e=0x3,
    V_SHUTTER_JNT_POLYSURFACE18625_e=0x4,
};

#endif /* !RES_V_SHUTTER_H */