#ifndef RES_CHIN_MDL_H
#define RES_CHIN_MDL_H

enum dRes_INDEX_CHIN_MDL {
    /* BMDR */
    dRes_INDEX_CHIN_MDL_BMD_CHIN_e=0x3,
};

enum dRes_ID_CHIN_MDL {
    /* BMDR */
    dRes_ID_CHIN_MDL_BMD_CHIN_e=0x3,
};

enum CHIN_JNT {
    CHIN_JNT_CENTER_e=0x0,
    CHIN_JNT_BACKBONE1_e=0x1,
    CHIN_JNT_BACKBONE2_e=0x2,
    CHIN_JNT_NECK_e=0x3,
    CHIN_JNT_HEAD_e=0x4,
    CHIN_JNT_CHIN_e=0x5,
    CHIN_JNT_MAYU_L_e=0x6,
    CHIN_JNT_MAYU_R_e=0x7,
    CHIN_JNT_MOUTH_e=0x8,
    CHIN_JNT_SHOULDERL_e=0x9,
    CHIN_JNT_ARML1_e=0xA,
    CHIN_JNT_ARML2_e=0xB,
    CHIN_JNT_HANDL_e=0xC,
    CHIN_JNT_FINGERL1_e=0xD,
    CHIN_JNT_FOREFINGERL_e=0xE,
    CHIN_JNT_THUMBL_e=0xF,
    CHIN_JNT_SHOULDERR_e=0x10,
    CHIN_JNT_ARMR1_e=0x11,
    CHIN_JNT_ARMR2_e=0x12,
    CHIN_JNT_HANDR_e=0x13,
    CHIN_JNT_FINGERR1_e=0x14,
    CHIN_JNT_FOREFINGERR_e=0x15,
    CHIN_JNT_THUMBR_e=0x16,
    CHIN_JNT_WATCH_e=0x17,
    CHIN_JNT_WAIST_e=0x18,
    CHIN_JNT_LEGL1_e=0x19,
    CHIN_JNT_LEGL2_e=0x1A,
    CHIN_JNT_FOOTL_e=0x1B,
    CHIN_JNT_LEGR1_e=0x1C,
    CHIN_JNT_LEGR2_e=0x1D,
    CHIN_JNT_FOOTR_e=0x1E,
};

#endif /* !RES_CHIN_MDL_H */