#ifndef RES_CHTSOLB_H
#define RES_CHTSOLB_H

enum dRes_INDEX_CHTSOLB {
    /* BCK  */
    dRes_INDEX_CHTSOLB_BCK_SOLB_FEAR_WAIT_e=0x4,
    dRes_INDEX_CHTSOLB_BCK_SOLB_TALK_A_e=0x5,
    dRes_INDEX_CHTSOLB_BCK_SOLB_WAIT_e=0x6,
    /* BMDR */
    dRes_INDEX_CHTSOLB_BMD_SOLB_SPEAR_e=0x9,
    dRes_INDEX_CHTSOLB_BMD_SOLB_TW_e=0xA,
};

enum dRes_ID_CHTSOLB {
    /* BCK  */
    dRes_ID_CHTSOLB_BCK_SOLB_FEAR_WAIT_e=0x4,
    dRes_ID_CHTSOLB_BCK_SOLB_TALK_A_e=0x5,
    dRes_ID_CHTSOLB_BCK_SOLB_WAIT_e=0x6,
    /* BMDR */
    dRes_ID_CHTSOLB_BMD_SOLB_SPEAR_e=0x9,
    dRes_ID_CHTSOLB_BMD_SOLB_TW_e=0xA,
};

enum SOLB_SPEAR_JNT {
    SOLB_SPEAR_JNT_SOL_SPEAR_e=0x0,
};

enum SOLB_TW_JNT {
    SOLB_TW_JNT_CENTER_e=0x0,
    SOLB_TW_JNT_BACKBONE1_e=0x1,
    SOLB_TW_JNT_BACKBONE2_e=0x2,
    SOLB_TW_JNT_NECK_e=0x3,
    SOLB_TW_JNT_HEAD_e=0x4,
    SOLB_TW_JNT_SHOULDERL_e=0x5,
    SOLB_TW_JNT_ARM1L_e=0x6,
    SOLB_TW_JNT_ARM2L_e=0x7,
    SOLB_TW_JNT_HANDL_e=0x8,
    SOLB_TW_JNT_FINGERL_e=0x9,
    SOLB_TW_JNT_THUMBL_e=0xA,
    SOLB_TW_JNT_SHOULDERR_e=0xB,
    SOLB_TW_JNT_ARM1R_e=0xC,
    SOLB_TW_JNT_ARM2R_e=0xD,
    SOLB_TW_JNT_HANDR_e=0xE,
    SOLB_TW_JNT_FINGERR_e=0xF,
    SOLB_TW_JNT_THUMBR_e=0x10,
    SOLB_TW_JNT_WAIST_e=0x11,
    SOLB_TW_JNT_LEG1L_e=0x12,
    SOLB_TW_JNT_LEG2L_e=0x13,
    SOLB_TW_JNT_FOOTL_e=0x14,
    SOLB_TW_JNT_LEG1R_e=0x15,
    SOLB_TW_JNT_LEG2R_e=0x16,
    SOLB_TW_JNT_FOOTR_e=0x17,
    SOLB_TW_JNT_SAYA_e=0x18,
};

#endif /* !RES_CHTSOLB_H */