#ifndef RES_GRA_H
#define RES_GRA_H

enum dRes_INDEX_GRA {
    /* BCK  */
    dRes_INDEX_GRA_BCK_GRA_DEFENCE_e=0x6,
    dRes_INDEX_GRA_BCK_GRA_F_DEFENCE_e=0x7,
    dRes_INDEX_GRA_BCK_GRA_F_STEP_FIGHT_e=0x8,
    dRes_INDEX_GRA_BCK_GRA_F_TALK_ORDER_e=0x9,
    dRes_INDEX_GRA_BCK_GRA_F_WAIT_FIGHT_e=0xA,
    dRes_INDEX_GRA_BCK_GRA_STEP_FIGHT_e=0xB,
    dRes_INDEX_GRA_BCK_GRA_STEP_FIGHT_HITL_e=0xC,
    dRes_INDEX_GRA_BCK_GRA_STEP_FIGHT_HITR_e=0xD,
    dRes_INDEX_GRA_BCK_GRA_STEP_FIGHT_WHIFF_e=0xE,
    dRes_INDEX_GRA_BCK_GRA_TALK_ORDER_e=0xF,
    dRes_INDEX_GRA_BCK_GRA_TO_STONE_e=0x10,
    dRes_INDEX_GRA_BCK_GRA_TO_STONE_BACK_e=0x11,
    dRes_INDEX_GRA_BCK_GRA_WAIT_FIGHT_e=0x12,
    /* BTP  */
    dRes_INDEX_GRA_BTP_GRA_F_DEFENSE_e=0x15,
    /* DZB  */
    dRes_INDEX_GRA_DZB_GRA_STONE_COL_e=0x18,
    /* EVT  */
    dRes_INDEX_GRA_DAT_EVENT_LIST_e=0x1B,
};

enum dRes_ID_GRA {
    /* BCK  */
    dRes_ID_GRA_BCK_GRA_DEFENCE_e=0x6,
    dRes_ID_GRA_BCK_GRA_F_DEFENCE_e=0x7,
    dRes_ID_GRA_BCK_GRA_F_STEP_FIGHT_e=0x8,
    dRes_ID_GRA_BCK_GRA_F_TALK_ORDER_e=0x9,
    dRes_ID_GRA_BCK_GRA_F_WAIT_FIGHT_e=0xA,
    dRes_ID_GRA_BCK_GRA_STEP_FIGHT_e=0xB,
    dRes_ID_GRA_BCK_GRA_STEP_FIGHT_HITL_e=0xC,
    dRes_ID_GRA_BCK_GRA_STEP_FIGHT_HITR_e=0xD,
    dRes_ID_GRA_BCK_GRA_STEP_FIGHT_WHIFF_e=0xE,
    dRes_ID_GRA_BCK_GRA_TALK_ORDER_e=0xF,
    dRes_ID_GRA_BCK_GRA_TO_STONE_e=0x10,
    dRes_ID_GRA_BCK_GRA_TO_STONE_BACK_e=0x11,
    dRes_ID_GRA_BCK_GRA_WAIT_FIGHT_e=0x12,
    /* BTP  */
    dRes_ID_GRA_BTP_GRA_F_DEFENSE_e=0x15,
    /* DZB  */
    dRes_ID_GRA_DZB_GRA_STONE_COL_e=0x18,
    /* EVT  */
    dRes_ID_GRA_DAT_EVENT_LIST_e=0x1B,
};

#endif /* !RES_GRA_H */