#ifndef RES_L4SLDWALL_H
#define RES_L4SLDWALL_H

enum dRes_INDEX_L4SLDWALL {
    /* BMDR */
    dRes_INDEX_L4SLDWALL_BMD_LV4_OBJ_SLIDEWALL_e=0x4,
    /* DZB  */
    dRes_INDEX_L4SLDWALL_DZB_LV4_OBJ_SLIDEWALL_e=0x7,
};

enum dRes_ID_L4SLDWALL {
    /* BMDR */
    dRes_ID_L4SLDWALL_BMD_LV4_OBJ_SLIDEWALL_e=0x4,
    /* DZB  */
    dRes_ID_L4SLDWALL_DZB_LV4_OBJ_SLIDEWALL_e=0x7,
};

enum LV4_OBJ_SLIDEWALL_JNT {
    LV4_OBJ_SLIDEWALL_JNT_WORLD_ROOT_e=0x0,
};

#endif /* !RES_L4SLDWALL_H */