#ifndef RES_M_TAKARAD_H
#define RES_M_TAKARAD_H

enum dRes_INDEX_M_TAKARAD {
    /* BMDR */
    dRes_INDEX_M_TAKARAD_BMD_M_TAKARADAI_BASE_e=0x4,
    dRes_INDEX_M_TAKARAD_BMD_M_TAKARADAI_TOP_e=0x5,
    /* DZB  */
    dRes_INDEX_M_TAKARAD_DZB_M_TAKARADAI_BASE_e=0x8,
    dRes_INDEX_M_TAKARAD_DZB_M_TAKARADAI_TOP_e=0x9,
};

enum dRes_ID_M_TAKARAD {
    /* BMDR */
    dRes_ID_M_TAKARAD_BMD_M_TAKARADAI_BASE_e=0x4,
    dRes_ID_M_TAKARAD_BMD_M_TAKARADAI_TOP_e=0x5,
    /* DZB  */
    dRes_ID_M_TAKARAD_DZB_M_TAKARADAI_BASE_e=0x8,
    dRes_ID_M_TAKARAD_DZB_M_TAKARADAI_TOP_e=0x9,
};

enum M_TAKARADAI_BASE_JNT {
    M_TAKARADAI_BASE_JNT_WORLD_ROOT_e=0x0,
};

enum M_TAKARADAI_TOP_JNT {
    M_TAKARADAI_TOP_JNT_WORLD_ROOT_e=0x0,
};

#endif /* !RES_M_TAKARAD_H */