#ifndef RES_MON_A2_TW_H
#define RES_MON_A2_TW_H

enum dRes_INDEX_MON_A2_TW {
    /* BMDR */
    dRes_INDEX_MON_A2_TW_BMD_MON_A2_TW_e=0x4,
    /* BTP  */
    dRes_INDEX_MON_A2_TW_BTP_MON_A2_TW_e=0x7,
};

enum dRes_ID_MON_A2_TW {
    /* BMDR */
    dRes_ID_MON_A2_TW_BMD_MON_A2_TW_e=0x4,
    /* BTP  */
    dRes_ID_MON_A2_TW_BTP_MON_A2_TW_e=0x7,
};

enum MON_A2_TW_JNT {
    MON_A2_TW_JNT_CENTER_e=0x0,
    MON_A2_TW_JNT_BACKBONE_e=0x1,
    MON_A2_TW_JNT_NECK_e=0x2,
    MON_A2_TW_JNT_HEAD_e=0x3,
    MON_A2_TW_JNT_SHOULDERL_e=0x4,
    MON_A2_TW_JNT_ARML1_e=0x5,
    MON_A2_TW_JNT_ARML2_e=0x6,
    MON_A2_TW_JNT_HANDL_e=0x7,
    MON_A2_TW_JNT_SHOULDERR_e=0x8,
    MON_A2_TW_JNT_ARMR1_e=0x9,
    MON_A2_TW_JNT_ARMR2_e=0xA,
    MON_A2_TW_JNT_HANDR_e=0xB,
    MON_A2_TW_JNT_WAIST_e=0xC,
    MON_A2_TW_JNT_LEGL1_e=0xD,
    MON_A2_TW_JNT_LEGL2_e=0xE,
    MON_A2_TW_JNT_FOOTL_e=0xF,
    MON_A2_TW_JNT_LEGR1_e=0x10,
    MON_A2_TW_JNT_LEGR2_e=0x11,
    MON_A2_TW_JNT_FOOTR_e=0x12,
};

#endif /* !RES_MON_A2_TW_H */