#ifndef RES_POST2_H
#define RES_POST2_H

enum dRes_INDEX_POST2 {
    /* BCK  */
    dRes_INDEX_POST2_BCK_POST_F_ANGRY_e=0x6,
    dRes_INDEX_POST2_BCK_POST_F_SAD_e=0x7,
    dRes_INDEX_POST2_BCK_POST_FH_ANGRY_e=0x8,
    dRes_INDEX_POST2_BCK_POST_FH_SAD_e=0x9,
    dRes_INDEX_POST2_BCK_POST_SIT_A_e=0xA,
    dRes_INDEX_POST2_BCK_POST_SIT_NOD_e=0xB,
    dRes_INDEX_POST2_BCK_POST_SIT_TALK_A_e=0xC,
    /* BMDR */
    dRes_INDEX_POST2_BMD_POST_LETTER_B_e=0xF,
    /* BTK  */
    dRes_INDEX_POST2_BTK_POST_SIT_A_e=0x12,
    dRes_INDEX_POST2_BTK_POST_SIT_NOD_e=0x13,
    dRes_INDEX_POST2_BTK_POST_SIT_TALK_A_e=0x14,
    /* BTP  */
    dRes_INDEX_POST2_BTP_POST_F_ANGRY_e=0x17,
    dRes_INDEX_POST2_BTP_POST_F_SAD_e=0x18,
    dRes_INDEX_POST2_BTP_POST_FH_ANGRY_e=0x19,
    dRes_INDEX_POST2_BTP_POST_FH_SAD_e=0x1A,
    dRes_INDEX_POST2_BTP_POST_SIT_NOD_e=0x1B,
};

enum dRes_ID_POST2 {
    /* BCK  */
    dRes_ID_POST2_BCK_POST_F_ANGRY_e=0x6,
    dRes_ID_POST2_BCK_POST_F_SAD_e=0x7,
    dRes_ID_POST2_BCK_POST_FH_ANGRY_e=0x8,
    dRes_ID_POST2_BCK_POST_FH_SAD_e=0x9,
    dRes_ID_POST2_BCK_POST_SIT_A_e=0xA,
    dRes_ID_POST2_BCK_POST_SIT_NOD_e=0xB,
    dRes_ID_POST2_BCK_POST_SIT_TALK_A_e=0xC,
    /* BMDR */
    dRes_ID_POST2_BMD_POST_LETTER_B_e=0xF,
    /* BTK  */
    dRes_ID_POST2_BTK_POST_SIT_A_e=0x12,
    dRes_ID_POST2_BTK_POST_SIT_NOD_e=0x13,
    dRes_ID_POST2_BTK_POST_SIT_TALK_A_e=0x14,
    /* BTP  */
    dRes_ID_POST2_BTP_POST_F_ANGRY_e=0x17,
    dRes_ID_POST2_BTP_POST_F_SAD_e=0x18,
    dRes_ID_POST2_BTP_POST_FH_ANGRY_e=0x19,
    dRes_ID_POST2_BTP_POST_FH_SAD_e=0x1A,
    dRes_ID_POST2_BTP_POST_SIT_NOD_e=0x1B,
};

enum POST_LETTER_B_JNT {
    POST_LETTER_B_JNT_POST_LETTER_B_e=0x0,
};

#endif /* !RES_POST2_H */