#ifndef RES_CHIN_H
#define RES_CHIN_H

enum dRes_INDEX_CHIN {
    /* BCK  */
    dRes_INDEX_CHIN_BCK_CHIN_CHUCKLE_e=0x5,
    dRes_INDEX_CHIN_BCK_CHIN_CHUCKLE_WAIT_e=0x6,
    dRes_INDEX_CHIN_BCK_CHIN_F_CHUCKLE_e=0x7,
    dRes_INDEX_CHIN_BCK_CHIN_F_TALK_A_e=0x8,
    dRes_INDEX_CHIN_BCK_CHIN_FH_CHUCKLE_e=0x9,
    dRes_INDEX_CHIN_BCK_CHIN_WAIT_A_e=0xA,
    /* BTK  */
    dRes_INDEX_CHIN_BTK_CHIN_e=0xD,
    dRes_INDEX_CHIN_BTK_CHIN_CHUCKLE_e=0xE,
    dRes_INDEX_CHIN_BTK_CHIN_CHUCKLE_WAIT_e=0xF,
    /* BTP  */
    dRes_INDEX_CHIN_BTP_CHIN_e=0x12,
    dRes_INDEX_CHIN_BTP_CHIN_F_CHUCKLE_e=0x13,
    dRes_INDEX_CHIN_BTP_CHIN_F_TALK_A_e=0x14,
    dRes_INDEX_CHIN_BTP_CHIN_FH_CHUCKLE_e=0x15,
};

enum dRes_ID_CHIN {
    /* BCK  */
    dRes_ID_CHIN_BCK_CHIN_CHUCKLE_e=0x5,
    dRes_ID_CHIN_BCK_CHIN_CHUCKLE_WAIT_e=0x6,
    dRes_ID_CHIN_BCK_CHIN_F_CHUCKLE_e=0x7,
    dRes_ID_CHIN_BCK_CHIN_F_TALK_A_e=0x8,
    dRes_ID_CHIN_BCK_CHIN_FH_CHUCKLE_e=0x9,
    dRes_ID_CHIN_BCK_CHIN_WAIT_A_e=0xA,
    /* BTK  */
    dRes_ID_CHIN_BTK_CHIN_e=0xD,
    dRes_ID_CHIN_BTK_CHIN_CHUCKLE_e=0xE,
    dRes_ID_CHIN_BTK_CHIN_CHUCKLE_WAIT_e=0xF,
    /* BTP  */
    dRes_ID_CHIN_BTP_CHIN_e=0x12,
    dRes_ID_CHIN_BTP_CHIN_F_CHUCKLE_e=0x13,
    dRes_ID_CHIN_BTP_CHIN_F_TALK_A_e=0x14,
    dRes_ID_CHIN_BTP_CHIN_FH_CHUCKLE_e=0x15,
};

#endif /* !RES_CHIN_H */