#ifndef RES_RAFREL_H
#define RES_RAFREL_H

enum dRes_INDEX_RAFREL {
    /* BCK  */
    dRes_INDEX_RAFREL_BCK_RAF_F_HAPPY_e=0x7,
    dRes_INDEX_RAFREL_BCK_RAF_F_INTENSE_e=0x8,
    dRes_INDEX_RAFREL_BCK_RAF_F_TALK_A_e=0x9,
    dRes_INDEX_RAFREL_BCK_RAF_F_THINK_e=0xA,
    dRes_INDEX_RAFREL_BCK_RAF_FH_HAPPY_e=0xB,
    dRes_INDEX_RAFREL_BCK_RAF_FH_INTENSE_e=0xC,
    dRes_INDEX_RAFREL_BCK_RAF_FH_THINK_e=0xD,
    dRes_INDEX_RAFREL_BCK_RAF_WAIT_A_e=0xE,
    /* BMDR */
    dRes_INDEX_RAFREL_BMD_RAF_e=0x11,
    /* BTK  */
    dRes_INDEX_RAFREL_BTK_RAF_e=0x14,
    /* BTP  */
    dRes_INDEX_RAFREL_BTP_RAF_e=0x17,
    dRes_INDEX_RAFREL_BTP_RAF_F_THINK_e=0x18,
    dRes_INDEX_RAFREL_BTP_RAF_FH_THINK_e=0x19,
    /* EVT  */
    dRes_INDEX_RAFREL_DAT_EVENT_LIST_e=0x1C,
};

enum dRes_ID_RAFREL {
    /* BCK  */
    dRes_ID_RAFREL_BCK_RAF_F_HAPPY_e=0x7,
    dRes_ID_RAFREL_BCK_RAF_F_INTENSE_e=0x8,
    dRes_ID_RAFREL_BCK_RAF_F_TALK_A_e=0x9,
    dRes_ID_RAFREL_BCK_RAF_F_THINK_e=0xA,
    dRes_ID_RAFREL_BCK_RAF_FH_HAPPY_e=0xB,
    dRes_ID_RAFREL_BCK_RAF_FH_INTENSE_e=0xC,
    dRes_ID_RAFREL_BCK_RAF_FH_THINK_e=0xD,
    dRes_ID_RAFREL_BCK_RAF_WAIT_A_e=0xE,
    /* BMDR */
    dRes_ID_RAFREL_BMD_RAF_e=0x11,
    /* BTK  */
    dRes_ID_RAFREL_BTK_RAF_e=0x14,
    /* BTP  */
    dRes_ID_RAFREL_BTP_RAF_e=0x17,
    dRes_ID_RAFREL_BTP_RAF_F_THINK_e=0x18,
    dRes_ID_RAFREL_BTP_RAF_FH_THINK_e=0x19,
    /* EVT  */
    dRes_ID_RAFREL_DAT_EVENT_LIST_e=0x1C,
};

enum RAF_JNT {
    RAF_JNT_CENTER_e=0x0,
    RAF_JNT_BACKBONE1_e=0x1,
    RAF_JNT_BACKBONE2_e=0x2,
    RAF_JNT_NECK_e=0x3,
    RAF_JNT_HEAD_e=0x4,
    RAF_JNT_CHIN_e=0x5,
    RAF_JNT_HOOD_e=0x6,
    RAF_JNT_MAYU_L_e=0x7,
    RAF_JNT_MAYU_R_e=0x8,
    RAF_JNT_MOUTH_e=0x9,
    RAF_JNT_SHOULDERL_e=0xA,
    RAF_JNT_ARML1_e=0xB,
    RAF_JNT_ARML2_e=0xC,
    RAF_JNT_HANDL_e=0xD,
    RAF_JNT_FINGERL1_e=0xE,
    RAF_JNT_THAMBL_e=0xF,
    RAF_JNT_SHOULDERR_e=0x10,
    RAF_JNT_ARMR1_e=0x11,
    RAF_JNT_ARMR2_e=0x12,
    RAF_JNT_HANDR_e=0x13,
    RAF_JNT_FINGERR1_e=0x14,
    RAF_JNT_THAMBR_e=0x15,
    RAF_JNT_WAIST_e=0x16,
    RAF_JNT_LEGL1_e=0x17,
    RAF_JNT_LEGL2_e=0x18,
    RAF_JNT_FOOTL_e=0x19,
    RAF_JNT_LEGR1_e=0x1A,
    RAF_JNT_LEGR2_e=0x1B,
    RAF_JNT_FOOTR_e=0x1C,
};

#endif /* !RES_RAFREL_H */