#ifndef RES_HANJO2_H
#define RES_HANJO2_H

enum dRes_INDEX_HANJO2 {
    /* BCK  */
    dRes_INDEX_HANJO2_BCK_HANJO_F_SURPRISE_e=0x5,
    dRes_INDEX_HANJO2_BCK_HANJO_F_SURPRISE_WAIT_e=0x6,
    dRes_INDEX_HANJO2_BCK_HANJO_SURPRISE_e=0x7,
    dRes_INDEX_HANJO2_BCK_HANJO_SURPRISE_WAIT_e=0x8,
    dRes_INDEX_HANJO2_BCK_HANJO_TAKA_FUE_e=0x9,
    dRes_INDEX_HANJO2_BCK_HANJO_TAKA_MIHARI_e=0xA,
    dRes_INDEX_HANJO2_BCK_HANJO_TAKA_STEP_e=0xB,
    dRes_INDEX_HANJO2_BCK_HANJO_TAKA_WAIT_e=0xC,
    dRes_INDEX_HANJO2_BCK_HANJO_WAIT_D_e=0xD,
    /* BTP  */
    dRes_INDEX_HANJO2_BTP_HANJO_F_SURPRISE_e=0x10,
    dRes_INDEX_HANJO2_BTP_HANJO_F_SURPRISE_WAIT_e=0x11,
    /* EVT  */
    dRes_INDEX_HANJO2_DAT_EVENT_LIST_e=0x14,
};

enum dRes_ID_HANJO2 {
    /* BCK  */
    dRes_ID_HANJO2_BCK_HANJO_F_SURPRISE_e=0x5,
    dRes_ID_HANJO2_BCK_HANJO_F_SURPRISE_WAIT_e=0x6,
    dRes_ID_HANJO2_BCK_HANJO_SURPRISE_e=0x7,
    dRes_ID_HANJO2_BCK_HANJO_SURPRISE_WAIT_e=0x8,
    dRes_ID_HANJO2_BCK_HANJO_TAKA_FUE_e=0x9,
    dRes_ID_HANJO2_BCK_HANJO_TAKA_MIHARI_e=0xA,
    dRes_ID_HANJO2_BCK_HANJO_TAKA_STEP_e=0xB,
    dRes_ID_HANJO2_BCK_HANJO_TAKA_WAIT_e=0xC,
    dRes_ID_HANJO2_BCK_HANJO_WAIT_D_e=0xD,
    /* BTP  */
    dRes_ID_HANJO2_BTP_HANJO_F_SURPRISE_e=0x10,
    dRes_ID_HANJO2_BTP_HANJO_F_SURPRISE_WAIT_e=0x11,
    /* EVT  */
    dRes_ID_HANJO2_DAT_EVENT_LIST_e=0x14,
};

#endif /* !RES_HANJO2_H */