#ifndef RES_WRANPAL_H
#define RES_WRANPAL_H

enum dRes_INDEX_WRANPAL {
    /* DAT  */
    dRes_INDEX_WRANPAL_BTI_STORE_WARNING_PSTART_VER2_e=0x3,
    dRes_INDEX_WRANPAL_BTI_STORE_WARNING_VER2_e=0x4,
    dRes_INDEX_WRANPAL_BTI_STRAP_16_9_832X456_US_e=0x5,
};

enum dRes_ID_WRANPAL {
    /* DAT  */
    dRes_ID_WRANPAL_BTI_STORE_WARNING_PSTART_VER2_e=0x3,
    dRes_ID_WRANPAL_BTI_STORE_WARNING_VER2_e=0x4,
    dRes_ID_WRANPAL_BTI_STRAP_16_9_832X456_US_e=0x5,
};

#endif /* !RES_WRANPAL_H */