//
// Generated By: dol2asm
// Translation Unit: unknown_translation_unit_bss
//

#include "rel/d/a/d_a_crod/unknown_translation_unit_bss.h"
#include "dol2asm.h"
#include "dolphin/types.h"

//
// Forward References:
//

extern "C" extern u8 data_804A4218[4];

//
// External References:
//

//
// Declarations:
//

/* ############################################################################################## */
/* 804A4218-804A421C 0004+00 s=0 e=1 z=0  None .bss       None */
u8 data_804A4218[4];
