#ifndef RES_LOGOPALIT_H
#define RES_LOGOPALIT_H

enum dRes_INDEX_LOGOPALIT {
    /* DAT  */
    dRes_INDEX_LOGOPALIT_BTI_PROGRESSIVE_CHOICE_IT_e=0x3,
    dRes_INDEX_LOGOPALIT_BTI_PROGRESSIVE_INTER_IT_e=0x4,
    dRes_INDEX_LOGOPALIT_BTI_PROGRESSIVE_NO_IT_e=0x5,
    dRes_INDEX_LOGOPALIT_BTI_PROGRESSIVE_PRO_IT_e=0x6,
    dRes_INDEX_LOGOPALIT_BTI_PROGRESSIVE_YES_IT_e=0x7,
    dRes_INDEX_LOGOPALIT_BTI_WARNING_IT_e=0x8,
    dRes_INDEX_LOGOPALIT_BTI_WARNING_PSTART_IT_e=0x9,
};

enum dRes_ID_LOGOPALIT {
    /* DAT  */
    dRes_ID_LOGOPALIT_BTI_PROGRESSIVE_CHOICE_IT_e=0x3,
    dRes_ID_LOGOPALIT_BTI_PROGRESSIVE_INTER_IT_e=0x4,
    dRes_ID_LOGOPALIT_BTI_PROGRESSIVE_NO_IT_e=0x5,
    dRes_ID_LOGOPALIT_BTI_PROGRESSIVE_PRO_IT_e=0x6,
    dRes_ID_LOGOPALIT_BTI_PROGRESSIVE_YES_IT_e=0x7,
    dRes_ID_LOGOPALIT_BTI_WARNING_IT_e=0x8,
    dRes_ID_LOGOPALIT_BTI_WARNING_PSTART_IT_e=0x9,
};

#endif /* !RES_LOGOPALIT_H */