#ifndef RES_SKILLRES_H
#define RES_SKILLRES_H

enum dRes_INDEX_SKILLRES {
    /* SCRN */
    dRes_INDEX_SKILLRES_BLO_ZELDA_COLLECT_SOUBI_DO_ICON_PARTS_e=0x4,
    dRes_INDEX_SKILLRES_BLO_ZELDA_OUGI_INFO_e=0x5,
    dRes_INDEX_SKILLRES_BLO_ZELDA_OUGI_WINDOW_e=0x6,
    /* TIMG */
    dRes_INDEX_SKILLRES_BTI_BOW_LIGHT_e=0x9,
    dRes_INDEX_SKILLRES_BTI_DA32_e=0xA,
    dRes_INDEX_SKILLRES_BTI_DB32_e=0xB,
    dRes_INDEX_SKILLRES_BTI_DBACKNEWCIRCLE32_e=0xC,
    dRes_INDEX_SKILLRES_BTI_DHOMENEWCIRCLE32_e=0xD,
    dRes_INDEX_SKILLRES_BTI_DLB32_e=0xE,
    dRes_INDEX_SKILLRES_BTI_DLS32_e=0xF,
    dRes_INDEX_SKILLRES_BTI_DRB32_e=0x10,
    dRes_INDEX_SKILLRES_BTI_DRS32_e=0x11,
    dRes_INDEX_SKILLRES_BTI_DS32_e=0x12,
    dRes_INDEX_SKILLRES_BTI_DX32_e=0x13,
    dRes_INDEX_SKILLRES_BTI_DY32_e=0x14,
    dRes_INDEX_SKILLRES_BTI_I4_GRA_e=0x15,
    dRes_INDEX_SKILLRES_BTI_NI_ITEM_ICON_MAKIMONO_e=0x16,
    dRes_INDEX_SKILLRES_BTI_TT_BLOCK128_00_e=0x17,
    dRes_INDEX_SKILLRES_BTI_TT_BLOCK8X8_e=0x18,
    dRes_INDEX_SKILLRES_BTI_TT_DO_ICON7_160_174_e=0x19,
    dRes_INDEX_SKILLRES_BTI_TT_GOLD_UZU_LONG2_e=0x1A,
    dRes_INDEX_SKILLRES_BTI_TT_HORIWAKU_TOP_RR_e=0x1B,
    dRes_INDEX_SKILLRES_BTI_TT_I4_GRA_e=0x1C,
    dRes_INDEX_SKILLRES_BTI_TT_KAZARI_KANI_00_e=0x1D,
    dRes_INDEX_SKILLRES_BTI_TT_LINE2_e=0x1E,
    dRes_INDEX_SKILLRES_BTI_TT_YAKUSHIMA_e=0x1F,
    dRes_INDEX_SKILLRES_BTI_TT_ZELDA_BUTTON_AB_MARU_e=0x20,
    dRes_INDEX_SKILLRES_BTI_TT_ZELDA_BUTTON_A_TEXT_e=0x21,
    dRes_INDEX_SKILLRES_BTI_TT_ZELDA_BUTTON_B_TEXT_e=0x22,
};

enum dRes_ID_SKILLRES {
    /* SCRN */
    dRes_ID_SKILLRES_BLO_ZELDA_COLLECT_SOUBI_DO_ICON_PARTS_e=0x4,
    dRes_ID_SKILLRES_BLO_ZELDA_OUGI_INFO_e=0x5,
    dRes_ID_SKILLRES_BLO_ZELDA_OUGI_WINDOW_e=0x6,
    /* TIMG */
    dRes_ID_SKILLRES_BTI_BOW_LIGHT_e=0x9,
    dRes_ID_SKILLRES_BTI_DA32_e=0xA,
    dRes_ID_SKILLRES_BTI_DB32_e=0xB,
    dRes_ID_SKILLRES_BTI_DBACKNEWCIRCLE32_e=0xC,
    dRes_ID_SKILLRES_BTI_DHOMENEWCIRCLE32_e=0xD,
    dRes_ID_SKILLRES_BTI_DLB32_e=0xE,
    dRes_ID_SKILLRES_BTI_DLS32_e=0xF,
    dRes_ID_SKILLRES_BTI_DRB32_e=0x10,
    dRes_ID_SKILLRES_BTI_DRS32_e=0x11,
    dRes_ID_SKILLRES_BTI_DS32_e=0x12,
    dRes_ID_SKILLRES_BTI_DX32_e=0x13,
    dRes_ID_SKILLRES_BTI_DY32_e=0x14,
    dRes_ID_SKILLRES_BTI_I4_GRA_e=0x15,
    dRes_ID_SKILLRES_BTI_NI_ITEM_ICON_MAKIMONO_e=0x16,
    dRes_ID_SKILLRES_BTI_TT_BLOCK128_00_e=0x17,
    dRes_ID_SKILLRES_BTI_TT_BLOCK8X8_e=0x18,
    dRes_ID_SKILLRES_BTI_TT_DO_ICON7_160_174_e=0x19,
    dRes_ID_SKILLRES_BTI_TT_GOLD_UZU_LONG2_e=0x1A,
    dRes_ID_SKILLRES_BTI_TT_HORIWAKU_TOP_RR_e=0x1B,
    dRes_ID_SKILLRES_BTI_TT_I4_GRA_e=0x1C,
    dRes_ID_SKILLRES_BTI_TT_KAZARI_KANI_00_e=0x1D,
    dRes_ID_SKILLRES_BTI_TT_LINE2_e=0x1E,
    dRes_ID_SKILLRES_BTI_TT_YAKUSHIMA_e=0x1F,
    dRes_ID_SKILLRES_BTI_TT_ZELDA_BUTTON_AB_MARU_e=0x20,
    dRes_ID_SKILLRES_BTI_TT_ZELDA_BUTTON_A_TEXT_e=0x21,
    dRes_ID_SKILLRES_BTI_TT_ZELDA_BUTTON_B_TEXT_e=0x22,
};

#endif /* !RES_SKILLRES_H */