#ifndef RES_DOORBOY_H
#define RES_DOORBOY_H

enum dRes_INDEX_DOORBOY {
    /* BMDR */
    dRes_INDEX_DOORBOY_BMD_DOORBOY_e=0x4,
    /* BTP  */
    dRes_INDEX_DOORBOY_BTP_DOORBOY_e=0x7,
};

enum dRes_ID_DOORBOY {
    /* BMDR */
    dRes_ID_DOORBOY_BMD_DOORBOY_e=0x4,
    /* BTP  */
    dRes_ID_DOORBOY_BTP_DOORBOY_e=0x7,
};

enum DOORBOY_JNT {
    DOORBOY_JNT_CENTER_e=0x0,
    DOORBOY_JNT_BACKBONE_e=0x1,
    DOORBOY_JNT_NECK_e=0x2,
    DOORBOY_JNT_HEAD_e=0x3,
    DOORBOY_JNT_SHOULDERL_e=0x4,
    DOORBOY_JNT_ARML1_e=0x5,
    DOORBOY_JNT_ARML2_e=0x6,
    DOORBOY_JNT_HANDL_e=0x7,
    DOORBOY_JNT_SHOULDERR_e=0x8,
    DOORBOY_JNT_ARMR1_e=0x9,
    DOORBOY_JNT_ARMR2_e=0xA,
    DOORBOY_JNT_HANDR_e=0xB,
    DOORBOY_JNT_WAIST_e=0xC,
    DOORBOY_JNT_LEGL1_e=0xD,
    DOORBOY_JNT_LEGL2_e=0xE,
    DOORBOY_JNT_FOOTL_e=0xF,
    DOORBOY_JNT_LEGR1_e=0x10,
    DOORBOY_JNT_LEGR2_e=0x11,
    DOORBOY_JNT_FOOTR_e=0x12,
};

#endif /* !RES_DOORBOY_H */