#ifndef RES_LV8KEKKAI_H
#define RES_LV8KEKKAI_H

enum dRes_INDEX_LV8KEKKAI {
    /* BMDR */
    dRes_INDEX_LV8KEKKAI_BMD_LV8_OBJ_KEKKAI_e=0x4,
    /* DZB  */
    dRes_INDEX_LV8KEKKAI_DZB_LV8_OBJ_KEKKAI_e=0x7,
};

enum dRes_ID_LV8KEKKAI {
    /* BMDR */
    dRes_ID_LV8KEKKAI_BMD_LV8_OBJ_KEKKAI_e=0x4,
    /* DZB  */
    dRes_ID_LV8KEKKAI_DZB_LV8_OBJ_KEKKAI_e=0x7,
};

enum LV8_OBJ_KEKKAI_JNT {
    LV8_OBJ_KEKKAI_JNT_WORLD_ROOT_e=0x0,
};

#endif /* !RES_LV8KEKKAI_H */