#ifndef RES_NPC_KSW_H
#define RES_NPC_KSW_H

enum dRes_INDEX_NPC_KSW {
    /* BCK  */
    dRes_INDEX_NPC_KSW_BCK_SARU_GODOWN_e=0x4,
    dRes_INDEX_NPC_KSW_BCK_SARU_HANGCALL_e=0x5,
    dRes_INDEX_NPC_KSW_BCK_SARU_HANGWAIT_A_e=0x6,
    dRes_INDEX_NPC_KSW_BCK_SARU_HANGWAIT_B_e=0x7,
    dRes_INDEX_NPC_KSW_BCK_SARU_HANGWAIT_C_e=0x8,
    dRes_INDEX_NPC_KSW_BCK_SARU_HUNGING_e=0x9,
    dRes_INDEX_NPC_KSW_BCK_SARU_JUMPRUN_e=0xA,
    dRes_INDEX_NPC_KSW_BCK_SARU_JUMP_S_e=0xB,
    dRes_INDEX_NPC_KSW_BCK_SARU_JUMP_T_e=0xC,
    dRes_INDEX_NPC_KSW_BCK_SARU_SWINGPOSE_e=0xD,
    dRes_INDEX_NPC_KSW_BCK_SARU_WAIT_A_e=0xE,
    /* BMDR */
    dRes_INDEX_NPC_KSW_BMD_SARU_e=0x11,
    dRes_INDEX_NPC_KSW_BMD_SARU_BARA_e=0x12,
};

enum dRes_ID_NPC_KSW {
    /* BCK  */
    dRes_ID_NPC_KSW_BCK_SARU_GODOWN_e=0x4,
    dRes_ID_NPC_KSW_BCK_SARU_HANGCALL_e=0x5,
    dRes_ID_NPC_KSW_BCK_SARU_HANGWAIT_A_e=0x6,
    dRes_ID_NPC_KSW_BCK_SARU_HANGWAIT_B_e=0x7,
    dRes_ID_NPC_KSW_BCK_SARU_HANGWAIT_C_e=0x8,
    dRes_ID_NPC_KSW_BCK_SARU_HUNGING_e=0x9,
    dRes_ID_NPC_KSW_BCK_SARU_JUMPRUN_e=0xA,
    dRes_ID_NPC_KSW_BCK_SARU_JUMP_S_e=0xB,
    dRes_ID_NPC_KSW_BCK_SARU_JUMP_T_e=0xC,
    dRes_ID_NPC_KSW_BCK_SARU_SWINGPOSE_e=0xD,
    dRes_ID_NPC_KSW_BCK_SARU_WAIT_A_e=0xE,
    /* BMDR */
    dRes_ID_NPC_KSW_BMD_SARU_e=0x11,
    dRes_ID_NPC_KSW_BMD_SARU_BARA_e=0x12,
};

enum SARU_JNT {
    SARU_JNT_CENTER_e=0x0,
    SARU_JNT_BACKBONE_1_e=0x1,
    SARU_JNT_BACKBONE_2_e=0x2,
    SARU_JNT_NECK_e=0x3,
    SARU_JNT_HEAD_e=0x4,
    SARU_JNT_CHIN_e=0x5,
    SARU_JNT_MOUTH_e=0x6,
    SARU_JNT_SHOULDER_L_e=0x7,
    SARU_JNT_ARM_L_1_e=0x8,
    SARU_JNT_ARM_L_2_e=0x9,
    SARU_JNT_HAND_L_e=0xA,
    SARU_JNT_SHOULDER_R_e=0xB,
    SARU_JNT_ARM_R_1_e=0xC,
    SARU_JNT_ARM_R_2_e=0xD,
    SARU_JNT_HAND_R_e=0xE,
    SARU_JNT_WAIST_e=0xF,
    SARU_JNT_LEG_L_1_e=0x10,
    SARU_JNT_LEG_L_2_e=0x11,
    SARU_JNT_FOOT_L_e=0x12,
    SARU_JNT_LEG_R_1_e=0x13,
    SARU_JNT_LEG_R_2_e=0x14,
    SARU_JNT_FOOT_R_e=0x15,
};

enum SARU_BARA_JNT {
    SARU_BARA_JNT_SARU_BARA_e=0x0,
};

#endif /* !RES_NPC_KSW_H */