#ifndef RES_KMDL_H
#define RES_KMDL_H

enum dRes_INDEX_KMDL {
    /* BMDE */
    dRes_INDEX_KMDL_BMD_AL_KANTERA_e=0x6,
    /* BMDR */
    dRes_INDEX_KMDL_BMD_EF_KTGLOW_e=0x9,
    /* BMWR */
    dRes_INDEX_KMDL_BMD_AL_e=0xC,
    dRes_INDEX_KMDL_BMD_AL_BOOTSH_e=0xD,
    dRes_INDEX_KMDL_BMD_AL_FACE_e=0xE,
    dRes_INDEX_KMDL_BMD_AL_HANDS_e=0xF,
    dRes_INDEX_KMDL_BMD_AL_HEAD_e=0x10,
    dRes_INDEX_KMDL_BMD_AL_SWB_e=0x11,
    /* BTK  */
    dRes_INDEX_KMDL_BTK_EF_KTGLOW_e=0x14,
};

enum dRes_ID_KMDL {
    /* BMDE */
    dRes_ID_KMDL_BMD_AL_KANTERA_e=0x6,
    /* BMDR */
    dRes_ID_KMDL_BMD_EF_KTGLOW_e=0x9,
    /* BMWR */
    dRes_ID_KMDL_BMD_AL_e=0xC,
    dRes_ID_KMDL_BMD_AL_BOOTSH_e=0xD,
    dRes_ID_KMDL_BMD_AL_FACE_e=0xE,
    dRes_ID_KMDL_BMD_AL_HANDS_e=0xF,
    dRes_ID_KMDL_BMD_AL_HEAD_e=0x10,
    dRes_ID_KMDL_BMD_AL_SWB_e=0x11,
    /* BTK  */
    dRes_ID_KMDL_BTK_EF_KTGLOW_e=0x14,
};

enum AL_KANTERA_JNT {
    AL_KANTERA_JNT_TOTTE_e=0x0,
    AL_KANTERA_JNT_KANTERA_e=0x1,
};

enum EF_KTGLOW_JNT {
    EF_KTGLOW_JNT_PPLANE1_e=0x0,
};

enum AL_JNT {
    AL_JNT_CENTER_e=0x0,
    AL_JNT_BACKBONE1_e=0x1,
    AL_JNT_BACKBONE2_e=0x2,
    AL_JNT_NECK_e=0x3,
    AL_JNT_HEAD_e=0x4,
    AL_JNT_POD_e=0x5,
    AL_JNT_SHOULDERL_e=0x6,
    AL_JNT_ARML1_e=0x7,
    AL_JNT_ARML2_e=0x8,
    AL_JNT_HANDL_e=0x9,
    AL_JNT_WEAPONL_e=0xA,
    AL_JNT_SHOULDERR_e=0xB,
    AL_JNT_ARMR1_e=0xC,
    AL_JNT_ARMR2_e=0xD,
    AL_JNT_HANDR_e=0xE,
    AL_JNT_WEAPONR_e=0xF,
    AL_JNT_WAIST_e=0x10,
    AL_JNT_CLOTCHL_e=0x11,
    AL_JNT_LEGL1_e=0x12,
    AL_JNT_LEGL2_e=0x13,
    AL_JNT_FOOTL_e=0x14,
    AL_JNT_TOEL_e=0x15,
    AL_JNT_CLOTCHR_e=0x16,
    AL_JNT_LEGR1_e=0x17,
    AL_JNT_LEGR2_e=0x18,
    AL_JNT_FOOTR_e=0x19,
    AL_JNT_TOER_e=0x1A,
    AL_JNT_FSKIRTL1_e=0x1B,
    AL_JNT_FSKIRTL2_e=0x1C,
    AL_JNT_FSKIRTR1_e=0x1D,
    AL_JNT_FSKIRTR2_e=0x1E,
    AL_JNT_RSKIRTL1_e=0x1F,
    AL_JNT_RSKIRTL2_e=0x20,
    AL_JNT_RSKIRTR1_e=0x21,
    AL_JNT_RSKIRTR2_e=0x22,
};

enum AL_BOOTSH_JNT {
    AL_BOOTSH_JNT_WORLD_ROOT_e=0x0,
    AL_BOOTSH_JNT_AL_BOOTSHA_e=0x1,
    AL_BOOTSH_JNT_AL_BOOTSHB_e=0x2,
    AL_BOOTSH_JNT_AL_BOOTSHC_e=0x3,
};

enum AL_FACE_JNT {
    AL_FACE_JNT_FACE_ROOT_e=0x0,
    AL_FACE_JNT_CHIN_e=0x1,
    AL_FACE_JNT_MAYUL_e=0x2,
    AL_FACE_JNT_MAYUR_e=0x3,
    AL_FACE_JNT_MOUTH_e=0x4,
};

enum AL_HANDS_JNT {
    AL_HANDS_JNT_WORLD_ROOT_e=0x0,
    AL_HANDS_JNT_AL_HANDSL_e=0x1,
    AL_HANDS_JNT_AL_HANDSR_e=0x2,
};

enum AL_HEAD_JNT {
    AL_HEAD_JNT_HEAD_ROOT_e=0x0,
    AL_HEAD_JNT_HAIRL1_e=0x1,
    AL_HEAD_JNT_HAIRL2_e=0x2,
    AL_HEAD_JNT_HAIRR_e=0x3,
    AL_HEAD_JNT_MOMIL_e=0x4,
    AL_HEAD_JNT_MOMIR_e=0x5,
    AL_HEAD_JNT_Z_CAP1_e=0x6,
    AL_HEAD_JNT_Z_CAP2_e=0x7,
    AL_HEAD_JNT_Z_CAP3_e=0x8,
    AL_HEAD_JNT_Z_CAP4_e=0x9,
};

enum AL_SWB_JNT {
    AL_SWB_JNT_AL_SWB_e=0x0,
};

#endif /* !RES_KMDL_H */