#ifndef RES_YCHANDELR_H
#define RES_YCHANDELR_H

enum dRes_INDEX_YCHANDELR {
    /* BMDR */
    dRes_INDEX_YCHANDELR_BMD_YCHANDELIER_e=0x4,
    dRes_INDEX_YCHANDELR_BMD_YCHANDELIERSHAFT_e=0x5,
    /* DZB  */
    dRes_INDEX_YCHANDELR_DZB_YCHANDELIER_e=0x8,
};

enum dRes_ID_YCHANDELR {
    /* BMDR */
    dRes_ID_YCHANDELR_BMD_YCHANDELIER_e=0x4,
    dRes_ID_YCHANDELR_BMD_YCHANDELIERSHAFT_e=0x5,
    /* DZB  */
    dRes_ID_YCHANDELR_DZB_YCHANDELIER_e=0x8,
};

enum YCHANDELIER_JNT {
    YCHANDELIER_JNT_WORLD_ROOT_e=0x0,
};

enum YCHANDELIERSHAFT_JNT {
    YCHANDELIERSHAFT_JNT_WORLD_ROOT_e=0x0,
};

#endif /* !RES_YCHANDELR_H */