/* 8011243C-80112458 10CD7C 001C+00 1/0 0/0 0/0 .text            getIronBallCenterPos__9daAlink_cFv
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm bool daAlink_c::getIronBallCenterPos() {
    nofralloc
#include "asm/d/a/d_a_alink/getIronBallCenterPos__9daAlink_cFv.s"
}
#pragma pop

/* 80112458-80112474 10CD98 001C+00 1/0 0/0 0/0 .text            getIronBallBgHit__9daAlink_cCFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm bool daAlink_c::getIronBallBgHit() const {
    nofralloc
#include "asm/d/a/d_a_alink/getIronBallBgHit__9daAlink_cCFv.s"
}
#pragma pop

/* 80112474-801124B4 10CDB4 0040+00 0/0 2/2 1/1 .text checkIronBallThrowMode__9daAlink_cCFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::checkIronBallThrowMode() const {
    nofralloc
#include "asm/d/a/d_a_alink/checkIronBallThrowMode__9daAlink_cCFv.s"
}
#pragma pop

/* 801124B4-801124FC 10CDF4 0048+00 0/0 1/1 1/1 .text checkIronBallThrowReturnMode__9daAlink_cCFv
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::checkIronBallThrowReturnMode() const {
    nofralloc
#include "asm/d/a/d_a_alink/checkIronBallThrowReturnMode__9daAlink_cCFv.s"
}
#pragma pop

/* 801124FC-80112524 10CE3C 0028+00 1/0 0/0 0/0 .text            checkIronBallReturn__9daAlink_cCFv
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm bool daAlink_c::checkIronBallReturn() const {
    nofralloc
#include "asm/d/a/d_a_alink/checkIronBallReturn__9daAlink_cCFv.s"
}
#pragma pop

/* 80112524-80112568 10CE64 0044+00 1/0 0/0 0/0 .text checkIronBallGroundStop__9daAlink_cCFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm bool daAlink_c::checkIronBallGroundStop() const {
    nofralloc
#include "asm/d/a/d_a_alink/checkIronBallGroundStop__9daAlink_cCFv.s"
}
#pragma pop

/* 80112568-80112628 10CEA8 00C0+00 5/5 0/0 0/0 .text setIronBallWaitUpperAnime__9daAlink_cFi */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::setIronBallWaitUpperAnime(int param_0) {
    nofralloc
#include "asm/d/a/d_a_alink/setIronBallWaitUpperAnime__9daAlink_cFi.s"
}
#pragma pop

/* 80112628-801126F8 10CF68 00D0+00 1/1 0/0 0/0 .text            checkIronBallDelete__9daAlink_cFv
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::checkIronBallDelete() {
    nofralloc
#include "asm/d/a/d_a_alink/checkIronBallDelete__9daAlink_cFv.s"
}
#pragma pop

/* 801126F8-80112768 10D038 0070+00 2/2 0/0 0/0 .text            setIronBallReturn__9daAlink_cFi */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::setIronBallReturn(int param_0) {
    nofralloc
#include "asm/d/a/d_a_alink/setIronBallReturn__9daAlink_cFi.s"
}
#pragma pop

/* 80112768-801127F0 10D0A8 0088+00 2/2 0/0 0/0 .text            setIronBallBgCheckPos__9daAlink_cFv
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::setIronBallBgCheckPos() {
    nofralloc
#include "asm/d/a/d_a_alink/setIronBallBgCheckPos__9daAlink_cFv.s"
}
#pragma pop

/* 801127F0-80112C80 10D130 0490+00 1/1 0/0 0/0 .text            setIronBallModel__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::setIronBallModel() {
    nofralloc
#include "asm/d/a/d_a_alink/setIronBallModel__9daAlink_cFv.s"
}
#pragma pop

/* 80112C80-80112C84 10D5C0 0004+00 2/2 2/2 0/0 .text            __ct__5csXyzFv */
extern "C" void __ct__5csXyzFv() {
    /* empty function */
}

/* 80112C84-80112E7C 10D5C4 01F8+00 1/1 0/0 0/0 .text
 * setIronBallGroundVec__9daAlink_cFPC4cXyzP4cXyz               */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::setIronBallGroundVec(cXyz const* param_0, cXyz* param_1) {
    nofralloc
#include "asm/d/a/d_a_alink/setIronBallGroundVec__9daAlink_cFPC4cXyzP4cXyz.s"
}
#pragma pop

/* 80112E7C-80113CA0 10D7BC 0E24+00 1/1 0/0 0/0 .text            setIronBallChainPos__9daAlink_cFv
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::setIronBallChainPos() {
    nofralloc
#include "asm/d/a/d_a_alink/setIronBallChainPos__9daAlink_cFv.s"
}
#pragma pop

/* 80113CA0-80113D58 10E5E0 00B8+00 1/1 0/0 0/0 .text checkIronBallReturnChange__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::checkIronBallReturnChange() {
    nofralloc
#include "asm/d/a/d_a_alink/checkIronBallReturnChange__9daAlink_cFv.s"
}
#pragma pop

/* 80113D58-801150E4 10E698 138C+00 1/1 0/0 0/0 .text            setIronBallPos__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::setIronBallPos() {
    nofralloc
#include "asm/d/a/d_a_alink/setIronBallPos__9daAlink_cFv.s"
}
#pragma pop

/* 801150E4-8011510C 10FA24 0028+00 10/10 0/0 0/0 .text            checkIronBallAnime__9daAlink_cCFv
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm BOOL daAlink_c::checkIronBallAnime() const {
    nofralloc
#include "asm/d/a/d_a_alink/checkIronBallAnime__9daAlink_cCFv.s"
}
#pragma pop

/* 8011510C-801151E0 10FA4C 00D4+00 1/1 0/0 0/0 .text            setIronBallReadyAnime__9daAlink_cFv
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::setIronBallReadyAnime() {
    nofralloc
#include "asm/d/a/d_a_alink/setIronBallReadyAnime__9daAlink_cFv.s"
}
#pragma pop

/* 801151E0-80115254 10FB20 0074+00 2/2 0/0 0/0 .text            setIronBallBaseAnime__9daAlink_cFv
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::setIronBallBaseAnime() {
    nofralloc
#include "asm/d/a/d_a_alink/setIronBallBaseAnime__9daAlink_cFv.s"
}
#pragma pop

/* 80115254-801153F8 10FB94 01A4+00 1/1 0/0 0/0 .text checkUpperItemActionIronBall__9daAlink_cFv
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::checkUpperItemActionIronBall() {
    nofralloc
#include "asm/d/a/d_a_alink/checkUpperItemActionIronBall__9daAlink_cFv.s"
}
#pragma pop

/* 801153F8-801154E4 10FD38 00EC+00 2/2 0/0 0/0 .text checkNextActionIronBall__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::checkNextActionIronBall() {
    nofralloc
#include "asm/d/a/d_a_alink/checkNextActionIronBall__9daAlink_cFv.s"
}
#pragma pop

/* 801154E4-80115564 10FE24 0080+00 1/1 0/0 0/0 .text procIronBallSubjectInit__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::procIronBallSubjectInit() {
    nofralloc
#include "asm/d/a/d_a_alink/procIronBallSubjectInit__9daAlink_cFv.s"
}
#pragma pop

/* 80115564-801155EC 10FEA4 0088+00 1/0 0/0 0/0 .text            procIronBallSubject__9daAlink_cFv
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::procIronBallSubject() {
    nofralloc
#include "asm/d/a/d_a_alink/procIronBallSubject__9daAlink_cFv.s"
}
#pragma pop

/* 801155EC-80115674 10FF2C 0088+00 1/1 0/0 0/0 .text            procIronBallMoveInit__9daAlink_cFv
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::procIronBallMoveInit() {
    nofralloc
#include "asm/d/a/d_a_alink/procIronBallMoveInit__9daAlink_cFv.s"
}
#pragma pop

/* 80115674-8011577C 10FFB4 0108+00 1/0 0/0 0/0 .text            procIronBallMove__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::procIronBallMove() {
    nofralloc
#include "asm/d/a/d_a_alink/procIronBallMove__9daAlink_cFv.s"
}
#pragma pop

/* 8011577C-80115860 1100BC 00E4+00 1/1 0/0 0/0 .text            procIronBallThrowInit__9daAlink_cFv
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::procIronBallThrowInit() {
    nofralloc
#include "asm/d/a/d_a_alink/procIronBallThrowInit__9daAlink_cFv.s"
}
#pragma pop

/* 80115860-801159F0 1101A0 0190+00 1/0 0/0 0/0 .text            procIronBallThrow__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::procIronBallThrow() {
    nofralloc
#include "asm/d/a/d_a_alink/procIronBallThrow__9daAlink_cFv.s"
}
#pragma pop

/* 801159F0-80115AA0 110330 00B0+00 2/2 0/0 0/0 .text procIronBallReturnInit__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::procIronBallReturnInit() {
    nofralloc
#include "asm/d/a/d_a_alink/procIronBallReturnInit__9daAlink_cFv.s"
}
#pragma pop

/* 80115AA0-80115C20 1103E0 0180+00 1/0 0/0 0/0 .text            procIronBallReturn__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::procIronBallReturn() {
    nofralloc
#include "asm/d/a/d_a_alink/procIronBallReturn__9daAlink_cFv.s"
}
#pragma pop