/* 800DE64C-800DE740 0D8F8C 00F4+00 1/1 0/0 2/2 .text            getArrowFlyData__9daAlink_cCFPfPfi
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::getArrowFlyData(f32* param_0, f32* param_1, int param_2) const {
    nofralloc
#include "asm/d/a/d_a_alink/getArrowFlyData__9daAlink_cCFPfPfi.s"
}
#pragma pop

/* 800DE740-800DE750 0D9080 0010+00 0/0 0/0 1/1 .text            getArrowIncAtR__9daAlink_cCFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::getArrowIncAtR() const {
    nofralloc
#include "asm/d/a/d_a_alink/getArrowIncAtR__9daAlink_cCFv.s"
}
#pragma pop

/* 800DE750-800DE760 0D9090 0010+00 0/0 0/0 1/1 .text getBombArrowFlyExplodeTime__9daAlink_cCFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::getBombArrowFlyExplodeTime() const {
    nofralloc
#include "asm/d/a/d_a_alink/getBombArrowFlyExplodeTime__9daAlink_cCFv.s"
}
#pragma pop

/* 800DE760-800DE770 0D90A0 0010+00 0/0 0/0 1/1 .text getArrowIncAtMaxStart__9daAlink_cCFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::getArrowIncAtMaxStart() const {
    nofralloc
#include "asm/d/a/d_a_alink/getArrowIncAtMaxStart__9daAlink_cCFv.s"
}
#pragma pop

/* 800DE770-800DE780 0D90B0 0010+00 0/0 0/0 1/1 .text            getArrowIncAtMax__9daAlink_cCFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::getArrowIncAtMax() const {
    nofralloc
#include "asm/d/a/d_a_alink/getArrowIncAtMax__9daAlink_cCFv.s"
}
#pragma pop

/* 800DE780-800DE7D4 0D90C0 0054+00 10/10 0/0 0/0 .text checkBowAndSlingItem__9daAlink_cFi */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm BOOL daAlink_c::checkBowAndSlingItem(int param_0) {
    nofralloc
#include "asm/d/a/d_a_alink/checkBowAndSlingItem__9daAlink_cFi.s"
}
#pragma pop

/* 800DE7D4-800DE884 0D9114 00B0+00 1/1 0/0 0/0 .text            setSlingModel__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::setSlingModel() {
    nofralloc
#include "asm/d/a/d_a_alink/setSlingModel__9daAlink_cFv.s"
}
#pragma pop

/* 800DE884-800DE990 0D91C4 010C+00 0/0 1/1 1/1 .text checkBowCameraArrowPosP__9daAlink_cFPsPs */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::checkBowCameraArrowPosP(s16* param_0, s16* param_1) {
    nofralloc
#include "asm/d/a/d_a_alink/checkBowCameraArrowPosP__9daAlink_cFPsPs.s"
}
#pragma pop

/* 800DE990-800DE9B8 0D92D0 0028+00 1/0 0/0 0/0 .text            checkArrowChargeEnd__9daAlink_cCFv
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm bool daAlink_c::checkArrowChargeEnd() const {
    nofralloc
#include "asm/d/a/d_a_alink/checkArrowChargeEnd__9daAlink_cCFv.s"
}
#pragma pop

/* 800DE9B8-800DE9E8 0D92F8 0030+00 3/3 0/0 0/0 .text            checkBowReadyAnime__9daAlink_cCFv
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::checkBowReadyAnime() const {
    nofralloc
#include "asm/d/a/d_a_alink/checkBowReadyAnime__9daAlink_cCFv.s"
}
#pragma pop

/* 800DE9E8-800DEA3C 0D9328 0054+00 16/16 0/0 0/0 .text            checkBowAnime__9daAlink_cCFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::checkBowAnime() const {
    nofralloc
#include "asm/d/a/d_a_alink/checkBowAnime__9daAlink_cCFv.s"
}
#pragma pop

/* 800DEA3C-800DEAE4 0D937C 00A8+00 2/2 0/0 0/0 .text            makeArrow__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::makeArrow() {
    nofralloc
#include "asm/d/a/d_a_alink/makeArrow__9daAlink_cFv.s"
}
#pragma pop

/* 800DEAE4-800DEB8C 0D9424 00A8+00 3/3 0/0 0/0 .text            deleteArrow__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::deleteArrow() {
    nofralloc
#include "asm/d/a/d_a_alink/deleteArrow__9daAlink_cFv.s"
}
#pragma pop

/* 800DEB8C-800DEBC8 0D94CC 003C+00 6/6 0/0 0/0 .text            setBowOrSlingStatus__9daAlink_cFv
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::setBowOrSlingStatus() {
    nofralloc
#include "asm/d/a/d_a_alink/setBowOrSlingStatus__9daAlink_cFv.s"
}
#pragma pop

/* 800DEBC8-800DED88 0D9508 01C0+00 1/1 0/0 0/0 .text            changeArrowType__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::changeArrowType() {
    nofralloc
#include "asm/d/a/d_a_alink/changeArrowType__9daAlink_cFv.s"
}
#pragma pop

/* 800DED88-800DEE1C 0D96C8 0094+00 1/1 0/0 0/0 .text cancelBowMoveRideNotAtn__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::cancelBowMoveRideNotAtn() {
    nofralloc
#include "asm/d/a/d_a_alink/cancelBowMoveRideNotAtn__9daAlink_cFv.s"
}
#pragma pop

/* 800DEE1C-800DEEDC 0D975C 00C0+00 3/3 0/0 0/0 .text            cancelBowMove__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::cancelBowMove() {
    nofralloc
#include "asm/d/a/d_a_alink/cancelBowMove__9daAlink_cFv.s"
}
#pragma pop

/* 800DEEDC-800DEFB8 0D981C 00DC+00 3/3 0/0 0/0 .text            setBowReadyAnime__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::setBowReadyAnime() {
    nofralloc
#include "asm/d/a/d_a_alink/setBowReadyAnime__9daAlink_cFv.s"
}
#pragma pop

/* 800DEFB8-800DF0BC 0D98F8 0104+00 2/2 0/0 0/0 .text            setBowReloadAnime__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::setBowReloadAnime() {
    nofralloc
#include "asm/d/a/d_a_alink/setBowReloadAnime__9daAlink_cFv.s"
}
#pragma pop

/* 800DF0BC-800DF798 0D99FC 06DC+00 2/2 0/0 0/0 .text checkUpperItemActionBow__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::checkUpperItemActionBow() {
    nofralloc
#include "asm/d/a/d_a_alink/checkUpperItemActionBow__9daAlink_cFv.s"
}
#pragma pop

/* 800DF798-800DF814 0DA0D8 007C+00 1/1 0/0 0/0 .text checkUpperItemActionBowFly__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::checkUpperItemActionBowFly() {
    nofralloc
#include "asm/d/a/d_a_alink/checkUpperItemActionBowFly__9daAlink_cFv.s"
}
#pragma pop

/* 800DF814-800DFAE8 0DA154 02D4+00 4/4 0/0 0/0 .text            checkNextActionBow__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::checkNextActionBow() {
    nofralloc
#include "asm/d/a/d_a_alink/checkNextActionBow__9daAlink_cFv.s"
}
#pragma pop

/* 800DFAE8-800DFBC8 0DA428 00E0+00 1/1 0/0 0/0 .text            setBowModel__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::setBowModel() {
    nofralloc
#include "asm/d/a/d_a_alink/setBowModel__9daAlink_cFv.s"
}
#pragma pop

/* 800DFBC8-800DFC28 0DA508 0060+00 4/4 0/0 0/0 .text            checkBowGrabLeftHand__9daAlink_cCFv
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm bool daAlink_c::checkBowGrabLeftHand() const {
    nofralloc
#include "asm/d/a/d_a_alink/checkBowGrabLeftHand__9daAlink_cCFv.s"
}
#pragma pop

/* 800DFC28-800DFC70 0DA568 0048+00 6/6 0/0 0/0 .text            setBowHangAnime__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::setBowHangAnime() {
    nofralloc
#include "asm/d/a/d_a_alink/setBowHangAnime__9daAlink_cFv.s"
}
#pragma pop

/* 800DFC70-800DFCD8 0DA5B0 0068+00 3/3 0/0 0/0 .text            setBowNormalAnime__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::setBowNormalAnime() {
    nofralloc
#include "asm/d/a/d_a_alink/setBowNormalAnime__9daAlink_cFv.s"
}
#pragma pop

/* 800DFCD8-800DFD6C 0DA618 0094+00 3/3 0/0 0/0 .text            setBowSight__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::setBowSight() {
    nofralloc
#include "asm/d/a/d_a_alink/setBowSight__9daAlink_cFv.s"
}
#pragma pop

/* 800DFD6C-800DFDDC 0DA6AC 0070+00 1/1 0/0 0/0 .text            procBowSubjectInit__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::procBowSubjectInit() {
    nofralloc
#include "asm/d/a/d_a_alink/procBowSubjectInit__9daAlink_cFv.s"
}
#pragma pop

/* 800DFDDC-800DFE3C 0DA71C 0060+00 1/0 0/0 0/0 .text            procBowSubject__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::procBowSubject() {
    nofralloc
#include "asm/d/a/d_a_alink/procBowSubject__9daAlink_cFv.s"
}
#pragma pop

/* 800DFE3C-800DFEC0 0DA77C 0084+00 1/1 0/0 0/0 .text            procBowMoveInit__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::procBowMoveInit() {
    nofralloc
#include "asm/d/a/d_a_alink/procBowMoveInit__9daAlink_cFv.s"
}
#pragma pop

/* 800DFEC0-800DFFE0 0DA800 0120+00 1/0 0/0 0/0 .text            procBowMove__9daAlink_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daAlink_c::procBowMove() {
    nofralloc
#include "asm/d/a/d_a_alink/procBowMove__9daAlink_cFv.s"
}
#pragma pop