// TODO: This isn't a real file, this is a hack to build OK with -sym on
// To properly fix, these symbols need to be compiler generated

/* 80140C80-80140CDC 13B5C0 005C+00 1/0 0/0 0/0 .text            __dt__8dEyeHL_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
// asm dEyeHL_c::~dEyeHL_c() {
extern "C" asm void __dt__8dEyeHL_cFv() {
    nofralloc
#include "asm/d/a/d_a_alink/__dt__8dEyeHL_cFv.s"
}
#pragma pop

/* 80140CDC-80140D24 13B61C 0048+00 0/0 1/0 0/0 .text            __dt__18daPy_sightPacket_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
// asm daPy_sightPacket_c::~daPy_sightPacket_c() {
extern "C" asm void __dt__18daPy_sightPacket_cFv() {
    nofralloc
#include "asm/d/a/d_a_alink/__dt__18daPy_sightPacket_cFv.s"
}
#pragma pop

/* 80140D24-80140D80 13B664 005C+00 3/2 0/0 0/0 .text            __dt__16daPy_frameCtrl_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
// asm daPy_frameCtrl_c::~daPy_frameCtrl_c() {
extern "C" asm void __dt__16daPy_frameCtrl_cFv() {
    nofralloc
#include "asm/d/a/d_a_alink/__dt__16daPy_frameCtrl_cFv.s"
}
#pragma pop

/* 80140D80-80140DCC 13B6C0 004C+00 1/1 0/0 0/0 .text            __ct__16daPy_frameCtrl_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
// asm daPy_frameCtrl_c::daPy_frameCtrl_c() {
extern "C" asm void __ct__16daPy_frameCtrl_cFv() {
    nofralloc
#include "asm/d/a/d_a_alink/__ct__16daPy_frameCtrl_cFv.s"
}
#pragma pop

/* 80140DCC-80140DF0 13B70C 0024+00 1/1 0/0 0/0 .text            __defctor__14daPy_anmHeap_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daPy_anmHeap_c::__defctor() {
    nofralloc
#include "asm/d/a/d_a_alink/__defctor__14daPy_anmHeap_cFv.s"
}
#pragma pop

/* 80140DF0-80140E2C 13B730 003C+00 2/2 0/0 0/0 .text            __dt__19mDoExt_AnmRatioPackFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm mDoExt_AnmRatioPack::~mDoExt_AnmRatioPack() {
    nofralloc
#include "asm/d/a/d_a_alink/__dt__19mDoExt_AnmRatioPackFv.s"
}
#pragma pop

/* 80140E2C-80140E40 13B76C 0014+00 1/1 0/0 0/0 .text            __ct__19mDoExt_AnmRatioPackFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm mDoExt_AnmRatioPack::mDoExt_AnmRatioPack() {
    nofralloc
#include "asm/d/a/d_a_alink/__ct__19mDoExt_AnmRatioPackFv.s"
}
#pragma pop

/* 80140E40-80140EB8 13B780 0078+00 4/3 0/0 0/0 .text            __dt__16dBgS_LinkRoofChkFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
// asm dBgS_LinkRoofChk::~dBgS_LinkRoofChk() {
extern "C" asm void __dt__16dBgS_LinkRoofChkFv() {
    nofralloc
#include "asm/d/a/d_a_alink/__dt__16dBgS_LinkRoofChkFv.s"
}
#pragma pop

/* 80140EB8-80140F30 13B7F8 0078+00 4/3 0/0 0/0 .text            __dt__15dBgS_LinkGndChkFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
// asm dBgS_LinkGndChk::~dBgS_LinkGndChk() {
extern "C" asm void __dt__15dBgS_LinkGndChkFv() {
    nofralloc
#include "asm/d/a/d_a_alink/__dt__15dBgS_LinkGndChkFv.s"
}
#pragma pop

/* 80140F30-80140FA0 13B870 0070+00 3/2 0/0 0/0 .text            __dt__13dBgS_LinkAcchFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
// asm dBgS_LinkAcch::~dBgS_LinkAcch() {
extern "C" asm void __dt__13dBgS_LinkAcchFv() {
    nofralloc
#include "asm/d/a/d_a_alink/__dt__13dBgS_LinkAcchFv.s"
}
#pragma pop

/* 80140FA0-80141020 13B8E0 0080+00 1/1 0/0 0/0 .text            __ct__8dCcD_CpsFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
// asm dCcD_Cps::dCcD_Cps() {
extern "C" asm void __ct__8dCcD_CpsFv() {
    nofralloc
#include "asm/d/a/d_a_alink/__ct__8dCcD_CpsFv.s"
}
#pragma pop

/* 80141020-801410A4 13B960 0084+00 1/1 0/0 0/0 .text            __ct__8dCcD_CylFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
// asm dCcD_Cyl::dCcD_Cyl() {
extern "C" asm void __ct__8dCcD_CylFv() {
    nofralloc
#include "asm/d/a/d_a_alink/__ct__8dCcD_CylFv.s"
}
#pragma pop

/* 801410A4-801410EC 13B9E4 0048+00 0/0 1/0 0/0 .text            __dt__9cCcD_SttsFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
// asm cCcD_Stts::~cCcD_Stts() {
extern "C" asm void __dt__9cCcD_SttsFv() {
    nofralloc
#include "asm/d/a/d_a_alink/__dt__9cCcD_SttsFv.s"
}
#pragma pop

/* 801410EC-8014111C 13BA2C 0030+00 1/1 0/0 0/0 .text            __ct__16daPy_actorKeep_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void __ct__16daPy_actorKeep_cFv() {
    nofralloc
#include "asm/d/a/d_a_alink/__ct__16daPy_actorKeep_cFv.s"
}
#pragma pop

/* 8014111C-8014112C 13BA5C 0010+00 1/1 0/0 0/0 .text
 * onNoResetFlg2__9daPy_py_cFQ29daPy_py_c9daPy_FLG2             */
void daPy_py_c::onNoResetFlg2(daPy_FLG2 pFlag) {
    mNoResetFlg2 |= pFlag;
}

/* 8014112C-8014113C 13BA6C 0010+00 1/1 0/0 0/0 .text
 * offNoResetFlg0__9daPy_py_cFQ29daPy_py_c9daPy_FLG0            */
// weird regalloc
#ifdef NONMATCHING
void daPy_py_c::offNoResetFlg0(daPy_FLG0 pFlag) {
    mNoResetFlg0 &= ~pFlag;
}
#else
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daPy_py_c::offNoResetFlg0(daPy_py_c::daPy_FLG0 param_0) {
    nofralloc
#include "asm/d/a/d_a_alink/offNoResetFlg0__9daPy_py_cFQ29daPy_py_c9daPy_FLG0.s"
}
#pragma pop
#endif

/* 8014113C-80141190 13BA7C 0054+00 1/1 0/0 0/0 .text            mDoAud_seStartLevel__FUlPC3VecUlSc
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
static asm void mDoAud_seStartLevel(u32 param_0, Vec const* param_1, u32 param_2, s8 param_3) {
    nofralloc
#include "asm/d/a/d_a_alink/mDoAud_seStartLevel__FUlPC3VecUlSc.s"
}
#pragma pop

/* 80141190-8014119C 13BAD0 000C+00 1/1 0/0 0/0 .text
 * checkEndResetFlg2__9daPy_py_cCFQ29daPy_py_c11daPy_ERFLG2     */
int daPy_py_c::checkEndResetFlg2(daPy_ERFLG2 pFlag) const {
    return mEndResetFlg2 & pFlag;
}

/* 8014119C-801411B0 13BADC 0014+00 1/1 0/0 0/0 .text            dComIfGp_setBottleStatus__FUcUc */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
static asm void dComIfGp_setBottleStatus(u8 param_0, u8 param_1) {
    nofralloc
#include "asm/d/a/d_a_alink/dComIfGp_setBottleStatus__FUcUc.s"
}
#pragma pop

/* 801411B0-801411D4 13BAF0 0024+00 1/1 0/0 0/0 .text            getSumouMode__9daPy_py_cCFv */
bool daPy_py_c::getSumouMode() const {
    return getSumouCameraMode();
}

/* 801411D4-801411E0 13BB14 000C+00 1/1 0/0 0/0 .text
 * checkNoResetFlg3__9daPy_py_cCFQ29daPy_py_c9daPy_FLG3         */
int daPy_py_c::checkNoResetFlg3(daPy_FLG3 pFlag) const {
    return mNoResetFlg3 & pFlag;
}

/* 801411E0-801411F0 13BB20 0010+00 1/1 0/0 0/0 .text            onCondition__11dEvt_info_cFUs */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void dEvt_info_c::onCondition(u16 param_0) {
    nofralloc
#include "asm/d/a/d_a_alink/onCondition__11dEvt_info_cFUs.s"
}
#pragma pop

/* 801411F0-80141200 13BB30 0010+00 1/1 4/4 0/0 .text            __ct__8cM3dGPlaFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
// asm cM3dGPla::cM3dGPla() {
extern "C" asm void __ct__8cM3dGPlaFv() {
    nofralloc
#include "asm/d/a/d_a_alink/__ct__8cM3dGPlaFv.s"
}
#pragma pop

/* 80141200-80141210 13BB40 0010+00 1/1 0/0 0/0 .text            offCondition__11dEvt_info_cFUs */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void dEvt_info_c::offCondition(u16 param_0) {
    nofralloc
#include "asm/d/a/d_a_alink/offCondition__11dEvt_info_cFUs.s"
}
#pragma pop

/* 80141210-80141230 13BB50 0020+00 1/1 0/0 0/0 .text            checkShieldGet__9daPy_py_cFv */
BOOL daPy_py_c::checkShieldGet() {
    return dComIfGs_getSelectEquipShield() != NO_ITEM;
}

/* 80141230-80141264 13BB70 0034+00 1/1 0/0 0/0 .text            fopAcM_onSwitch__FPC10fopAc_ac_ci
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
static asm void fopAcM_onSwitch__FPC10fopAc_ac_ci(fopAc_ac_c const* param_0, int param_1) {
    nofralloc
#include "asm/d/a/d_a_alink/fopAcM_onSwitch__FPC10fopAc_ac_ci.s"
}
#pragma pop

/* 80141264-80141294 13BBA4 0030+00 1/1 0/0 0/0 .text            dComIfGs_isItemFirstBit__FUc */
int dComIfGs_isItemFirstBit(u8 i_no) {
    return g_dComIfG_gameInfo.info.getPlayer().getGetItem().isFirstBit(i_no);
}

/* 80141294-801412A0 13BBD4 000C+00 1/1 0/0 0/0 .text
 * dStage_stagInfo_GetSaveTbl__FP21stage_stag_info_class        */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
static asm s32 dStage_stagInfo_GetSaveTbl(stage_stag_info_class* param_0) {
    nofralloc
#include "asm/d/a/d_a_alink/dStage_stagInfo_GetSaveTbl__FP21stage_stag_info_class.s"
}
#pragma pop

/* 801412A0-801412B0 13BBE0 0010+00 1/1 0/0 0/0 .text            dComIfGp_getStage__Fv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
static asm dStage_stageDt_c* dComIfGp_getStage() {
    nofralloc
#include "asm/d/a/d_a_alink/dComIfGp_getStage__Fv.s"
}
#pragma pop

/* 801412B0-801412BC 13BBF0 000C+00 1/1 0/0 0/0 .text            checkEquipHeavyBoots__9daPy_py_cCFv
 */
u32 daPy_py_c::checkEquipHeavyBoots() const {
    return i_checkNoResetFlg0(FLG0_EQUIP_HVY_BOOTS);
}

/* 801412BC-801412C4 13BBFC 0008+00 1/1 4/4 0/0 .text            fopAcM_GetName__FPv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
// asm void fopAcM_GetName(void* param_0) {
extern "C" asm void fopAcM_GetName__FPv() {
    nofralloc
#include "asm/d/a/d_a_alink/fopAcM_GetName__FPv.s"
}
#pragma pop

/* 801412C4-801412D4 13BC04 0010+00 1/1 0/0 0/0 .text
 * onNoResetFlg0__9daPy_py_cFQ29daPy_py_c9daPy_FLG0             */
void daPy_py_c::onNoResetFlg0(daPy_FLG0 pFlag) {
    mNoResetFlg0 |= pFlag;
}

/* 801412D4-801412F8 13BC14 0024+00 1/1 0/0 0/0 .text            isOrderOK__14dEvt_control_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm BOOL dEvt_control_c::isOrderOK() {
    nofralloc
#include "asm/d/a/d_a_alink/isOrderOK__14dEvt_control_cFv.s"
}
#pragma pop

/* 801412F8-80141308 13BC38 0010+00 1/1 0/0 0/0 .text            dComIfGp_getEvent__Fv */
static dEvt_control_c& dComIfGp_getEvent() {
    return g_dComIfG_gameInfo.play.getEvent();
}

/* 80141308-80141324 13BC48 001C+00 1/1 0/0 0/0 .text            dComIfGp_checkPlayerStatus0__FiUl
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
static asm u32 dComIfGp_checkPlayerStatus0(int param_0, u32 param_1) {
    nofralloc
#include "asm/d/a/d_a_alink/dComIfGp_checkPlayerStatus0__FiUl.s"
}
#pragma pop

/* 80141324-80141340 13BC64 001C+00 1/1 0/0 0/0 .text            dComIfGp_checkPlayerStatus1__FiUl
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
static asm u32 dComIfGp_checkPlayerStatus1(int param_0, u32 param_1) {
    nofralloc
#include "asm/d/a/d_a_alink/dComIfGp_checkPlayerStatus1__FiUl.s"
}
#pragma pop

/* 80141340-8014134C 13BC80 000C+00 1/1 0/0 0/0 .text
 * checkEndResetFlg1__9daPy_py_cCFQ29daPy_py_c11daPy_ERFLG1     */
u32 daPy_py_c::checkEndResetFlg1(daPy_ERFLG1 pFlag) const {
    return mEndResetFlg1 & pFlag;
}

/* 8014134C-8014135C 13BC8C 0010+00 1/1 0/0 0/0 .text            dComIfGp_getEventManager__Fv */
static dEvent_manager_c& dComIfGp_getEventManager() {
    return g_dComIfG_gameInfo.play.getEvtManager();
}

/* 8014135C-8014136C 13BC9C 0010+00 1/1 0/0 0/0 .text
 * offNoResetFlg1__9daPy_py_cFQ29daPy_py_c9daPy_FLG1            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daPy_py_c::offNoResetFlg1(daPy_py_c::daPy_FLG1 param_0) {
    nofralloc
#include "asm/d/a/d_a_alink/offNoResetFlg1__9daPy_py_cFQ29daPy_py_c9daPy_FLG1.s"
}
#pragma pop

/* 8014136C-8014137C 13BCAC 0010+00 1/1 0/0 0/0 .text
 * offNoResetFlg2__9daPy_py_cFQ29daPy_py_c9daPy_FLG2            */
// regalloc
#ifdef NONMATCHING
void daPy_py_c::offNoResetFlg2(daPy_py_c::daPy_FLG2 param_0) {
    mNoResetFlg2 &= ~param_0;
}
#else
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daPy_py_c::offNoResetFlg2(daPy_py_c::daPy_FLG2 param_0) {
    nofralloc
#include "asm/d/a/d_a_alink/offNoResetFlg2__9daPy_py_cFQ29daPy_py_c9daPy_FLG2.s"
}
#pragma pop
#endif

/* 8014137C-80141388 13BCBC 000C+00 1/1 0/0 0/0 .text            setSpecialDemoType__11daPy_demo_cFv
 */
void daPy_demo_c::setSpecialDemoType() {
    setDemoType(5);
}

/* 80141388-8014139C 13BCC8 0014+00 1/1 0/0 0/0 .text            checkCommandCatch__11dEvt_info_cFv
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm bool dEvt_info_c::checkCommandCatch() {
    nofralloc
#include "asm/d/a/d_a_alink/checkCommandCatch__11dEvt_info_cFv.s"
}
#pragma pop

/* 8014139C-801413CC 13BCDC 0030+00 1/1 1/1 0/0 .text            dComIfGs_isEventBit__FUs */
BOOL dComIfGs_isEventBit(u16 id) {
    return g_dComIfG_gameInfo.info.getEvent().isEventBit(id);
}

/* 801413CC-801413D8 13BD0C 000C+00 1/1 0/0 0/0 .text            checkWolf__9daPy_py_cCFv */
u32 daPy_py_c::checkWolf() const {
    return i_checkNoResetFlg1(FLG1_IS_WOLF);
}

/* 801413D8-801413F8 13BD18 0020+00 1/1 0/0 0/0 .text            checkSwordGet__9daPy_py_cFv */
BOOL daPy_py_c::checkSwordGet() {
    return dComIfGs_getSelectEquipSword() != 0xFF;
}

/* 801413F8-80141404 13BD38 000C+00 1/1 0/0 0/0 .text
 * checkResetFlg0__9daPy_py_cCFQ29daPy_py_c10daPy_RFLG0         */
u32 daPy_py_c::checkResetFlg0(daPy_RFLG0 pFlag) const {
    return mResetFlg0 & pFlag;
}

/* 80141404-80141410 13BD44 000C+00 1/1 0/0 0/0 .text            ChkGroundHit__9dBgS_AcchCFv */
bool dBgS_Acch::ChkGroundHit() const {
    return m_flags & GROUND_HIT;
}

/* 80141410-8014141C 13BD50 000C+00 1/1 0/0 0/0 .text
 * checkNoResetFlg0__9daPy_py_cCFQ29daPy_py_c9daPy_FLG0         */
u32 daPy_py_c::checkNoResetFlg0(daPy_FLG0 pFlag) const {
    return mNoResetFlg0 & pFlag;
}

/* 8014141C-80141438 13BD5C 001C+00 1/1 0/0 0/0 .text            dComIfGp_getPlayerCameraID__Fi */
#ifdef NONMATCHING
static s32 dComIfGp_getPlayerCameraID(int i) {
    return g_dComIfG_gameInfo.play.getPlayerCameraID(i);
}
#else
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
static asm s8 dComIfGp_getPlayerCameraID(int param_0) {
    nofralloc
#include "asm/d/a/d_a_alink/dComIfGp_getPlayerCameraID__Fi.s"
}
#pragma pop
#endif

/* 80141438-80141450 13BD78 0018+00 1/1 0/0 0/0 .text            dComIfGp_event_chkEventFlag__FUs */
static u16 dComIfGp_event_chkEventFlag(u16 flag) {
    return g_dComIfG_gameInfo.play.getEvent().chkEventFlag(flag);
}

/* 80141450-80141464 13BD90 0014+00 1/1 0/0 0/0 .text            checkCommandDoor__11dEvt_info_cFv
 */
BOOL dEvt_info_c::checkCommandDoor() {
    return mCommand == 3;
}

/* 80141464-801414A4 13BDA4 0040+00 1/1 0/0 0/0 .text
 * dComIfGp_evmng_getMyStaffId__FPCcP10fopAc_ac_ci              */
static s32 dComIfGp_evmng_getMyStaffId(char const* param_0, fopAc_ac_c* param_1, int param_2) {
    return dComIfGp_getPEvtManager()->getMyStaffId(param_0, param_1, param_2);
}

/* 801414A4-801414C0 13BDE4 001C+00 1/1 0/0 0/0 .text            dComIfGp_event_runCheck__Fv */
static BOOL dComIfGp_event_runCheck() {
    return g_dComIfG_gameInfo.play.getEvent().runCheck();
}

/* 801414C0-801414CC 13BE00 000C+00 1/1 0/0 0/0 .text
 * checkNoResetFlg2__9daPy_py_cCFQ29daPy_py_c9daPy_FLG2         */
u32 daPy_py_c::checkNoResetFlg2(daPy_FLG2 pFlag) const {
    return mNoResetFlg2 & pFlag;
}

/* 801414CC-801414D8 13BE0C 000C+00 1/1 2/2 0/0 .text            checkMagneBootsOn__9daPy_py_cCFv */
u32 daPy_py_c::checkMagneBootsOn() const {
    return i_checkNoResetFlg0(FLG0_MAGNE_BOOTS_ON);
}

/* 801414D8-801414E8 13BE18 0010+00 1/1 2/2 0/0 .text            dComIfGp_getHorseActor__Fv */
daHorse_c* dComIfGp_getHorseActor() {
    return (daHorse_c*)g_dComIfG_gameInfo.play.getPlayerPtr(1);
}

/* 801414E8-801414F4 13BE28 000C+00 1/1 0/0 0/0 .text checkBoarSingleBattle__9daPy_py_cCFv */
u32 daPy_py_c::checkBoarSingleBattle() const {
    return i_checkNoResetFlg2(FLG2_BOAR_SINGLE_BATTLE);
}

/* 801414F4-80141500 13BE34 000C+00 1/1 0/0 0/0 .text
 * checkEndResetFlg0__9daPy_py_cCFQ29daPy_py_c11daPy_ERFLG0     */
u32 daPy_py_c::checkEndResetFlg0(daPy_ERFLG0 pFlag) const {
    return mEndResetFlg0 & pFlag;
}

/* 80141500-80141508 13BE40 0008+00 1/0 0/0 0/0 .text            getMidnaAtnPos__9daPy_py_cCFv */
extern "C" bool getMidnaAtnPos__9daPy_py_cCFv() {
    // bool daPy_py_c::getMidnaAtnPos() const {
    return false;
}

/* 80141508-8014150C 13BE48 0004+00 1/0 0/0 0/0 .text setMidnaMsgNum__9daPy_py_cFP10fopAc_ac_cUs
 */
void daPy_py_c::setMidnaMsgNum(fopAc_ac_c* param_0, u16 param_1) {
    /* empty function */
}

/* 8014150C-80141514 13BE4C 0008+00 1/0 0/0 0/0 .text            getModelMtx__9daPy_py_cFv */
MtxP daPy_py_c::getModelMtx() {
    return cullMtx;
}

/* 80141514-8014151C 13BE54 0008+00 1/0 0/0 0/0 .text            getInvMtx__9daPy_py_cFv */
MtxP daPy_py_c::getInvMtx() {
    return cullMtx;
}

/* 8014151C-80141524 13BE5C 0008+00 1/0 0/0 0/0 .text            getShadowTalkAtnPos__9daPy_py_cFv
 */
cXyz* daPy_py_c::getShadowTalkAtnPos() {
    return &current.pos;
}

/* 80141524-8014152C 13BE64 0008+00 1/0 0/0 0/0 .text            getLeftItemMatrix__9daPy_py_cFv */
MtxP daPy_py_c::getLeftItemMatrix() {
    return cullMtx;
}

/* 8014152C-80141534 13BE6C 0008+00 1/0 0/0 0/0 .text            getRightItemMatrix__9daPy_py_cFv */
MtxP daPy_py_c::getRightItemMatrix() {
    return cullMtx;
}

/* 80141534-8014153C 13BE74 0008+00 1/0 0/0 0/0 .text            getLeftHandMatrix__9daPy_py_cFv */
MtxP daPy_py_c::getLeftHandMatrix() {
    return cullMtx;
}

/* 8014153C-80141544 13BE7C 0008+00 1/0 0/0 0/0 .text            getRightHandMatrix__9daPy_py_cFv */
MtxP daPy_py_c::getRightHandMatrix() {
    return cullMtx;
}

/* 80141544-8014154C 13BE84 0008+00 1/0 0/0 0/0 .text getLinkBackBone1Matrix__9daPy_py_cFv */
MtxP daPy_py_c::getLinkBackBone1Matrix() {
    return cullMtx;
}

/* 8014154C-80141554 13BE8C 0008+00 1/0 0/0 0/0 .text            getWolfMouthMatrix__9daPy_py_cFv */
MtxP daPy_py_c::getWolfMouthMatrix() {
    return cullMtx;
}

/* 80141554-8014155C 13BE94 0008+00 1/0 0/0 0/0 .text getWolfBackbone2Matrix__9daPy_py_cFv */
MtxP daPy_py_c::getWolfBackbone2Matrix() {
    return cullMtx;
}

/* 8014155C-80141564 13BE9C 0008+00 1/0 0/0 0/0 .text            getBottleMtx__9daPy_py_cFv */
MtxP daPy_py_c::getBottleMtx() {
    return NULL;
}

/* 80141564-8014156C 13BEA4 0008+00 1/0 0/0 0/0 .text            checkPlayerGuard__9daPy_py_cCFv */
BOOL daPy_py_c::checkPlayerGuard() const {
    return false;
}

/* 8014156C-80141574 13BEAC 0008+00 1/0 0/0 0/0 .text            checkAutoJump__9daPy_py_cCFv */
BOOL daPy_py_c::checkAutoJump() const {
    return false;
}

/* 80141574-8014157C 13BEB4 0008+00 1/0 0/0 0/0 .text            checkSideStep__9daPy_py_cCFv */
bool daPy_py_c::checkSideStep() const {
    return false;
}

/* 8014157C-80141584 13BEBC 0008+00 1/0 0/0 0/0 .text            checkWolfTriggerJump__9daPy_py_cCFv
 */
bool daPy_py_c::checkWolfTriggerJump() const {
    return false;
}

/* 80141584-8014158C 13BEC4 0008+00 1/0 0/0 0/0 .text            checkGuardBreakMode__9daPy_py_cCFv
 */
BOOL daPy_py_c::checkGuardBreakMode() const {
    return false;
}

/* 8014158C-80141594 13BECC 0008+00 1/0 0/0 0/0 .text            checkLv3Slide__9daPy_py_cCFv */
bool daPy_py_c::checkLv3Slide() const {
    return false;
}

/* 80141594-8014159C 13BED4 0008+00 1/0 0/0 0/0 .text checkWolfHowlDemoMode__9daPy_py_cCFv */
bool daPy_py_c::checkWolfHowlDemoMode() const {
    return false;
}

/* 8014159C-801415A4 13BEDC 0008+00 1/0 0/0 0/0 .text checkChainBlockPushPull__9daPy_py_cFv */
bool daPy_py_c::checkChainBlockPushPull() {
    return false;
}

/* 801415A4-801415AC 13BEE4 0008+00 1/0 0/0 0/0 .text            checkElecDamage__9daPy_py_cCFv */
BOOL daPy_py_c::checkElecDamage() const {
    return false;
}

/* 801415AC-801415B4 13BEEC 0008+00 1/0 0/0 0/0 .text checkEmptyBottleSwing__9daPy_py_cCFv */
BOOL daPy_py_c::checkEmptyBottleSwing() const {
    return false;
}

/* 801415B4-801415BC 13BEF4 0008+00 1/0 0/0 0/0 .text            checkBottleSwingMode__9daPy_py_cCFv
 */
BOOL daPy_py_c::checkBottleSwingMode() const {
    return false;
}

/* 801415BC-801415C4 13BEFC 0008+00 1/0 0/0 0/0 .text            checkHawkWait__9daPy_py_cCFv */
BOOL daPy_py_c::checkHawkWait() const {
    return false;
}

/* 801415C4-801415CC 13BF04 0008+00 1/0 0/0 0/0 .text            checkGoatThrow__9daPy_py_cCFv */
BOOL daPy_py_c::checkGoatThrow() const {
    return false;
}

/* 801415CC-801415D4 13BF0C 0008+00 1/0 0/0 0/0 .text            checkGoatThrowAfter__9daPy_py_cCFv
 */
BOOL daPy_py_c::checkGoatThrowAfter() const {
    return false;
}

/* 801415D4-801415DC 13BF14 0008+00 1/0 0/0 0/0 .text            checkWolfTagLockJump__9daPy_py_cCFv
 */
BOOL daPy_py_c::checkWolfTagLockJump() const {
    return false;
}

/* 801415DC-801415E4 13BF1C 0008+00 1/0 0/0 0/0 .text checkWolfTagLockJumpLand__9daPy_py_cCFv */
BOOL daPy_py_c::checkWolfTagLockJumpLand() const {
    return false;
}

/* 801415E4-801415EC 13BF24 0008+00 1/0 0/0 0/0 .text            checkWolfRope__9daPy_py_cFv */
BOOL daPy_py_c::checkWolfRope() {
    return false;
}

/* 801415EC-801415F4 13BF2C 0008+00 1/0 0/0 0/0 .text            checkWolfRopeHang__9daPy_py_cCFv */
BOOL daPy_py_c::checkWolfRopeHang() const {
    return false;
}

/* 801415F4-801415FC 13BF34 0008+00 1/0 0/0 0/0 .text            checkRollJump__9daPy_py_cCFv */
BOOL daPy_py_c::checkRollJump() const {
    return false;
}

/* 801415FC-80141604 13BF3C 0008+00 1/0 0/0 0/0 .text            checkGoronRideWait__9daPy_py_cCFv
 */
BOOL daPy_py_c::checkGoronRideWait() const {
    return false;
}

/* 80141604-8014160C 13BF44 0008+00 1/0 0/0 0/0 .text            checkWolfChain__9daPy_py_cCFv */
BOOL daPy_py_c::checkWolfChain() const {
    return false;
}

/* 8014160C-80141614 13BF4C 0008+00 1/0 0/0 0/0 .text            checkWolfWait__9daPy_py_cCFv */
BOOL daPy_py_c::checkWolfWait() const {
    return false;
}

/* 80141614-8014161C 13BF54 0008+00 1/0 0/0 0/0 .text            checkWolfJumpAttack__9daPy_py_cCFv
 */
BOOL daPy_py_c::checkWolfJumpAttack() const {
    return false;
}

/* 8014161C-80141624 13BF5C 0008+00 1/0 0/0 0/0 .text            checkWolfRSit__9daPy_py_cCFv */
BOOL daPy_py_c::checkWolfRSit() const {
    return false;
}

/* 80141624-8014162C 13BF64 0008+00 2/0 0/0 0/0 .text            checkBubbleFly__9daPy_py_cCFv */
bool daPy_py_c::checkBubbleFly() const {
    return false;
}

/* 8014162C-80141634 13BF6C 0008+00 1/0 0/0 0/0 .text            checkBottleDrinkEnd__9daPy_py_cCFv
 */
BOOL daPy_py_c::checkBottleDrinkEnd() const {
    return false;
}

/* 80141634-8014163C 13BF74 0008+00 1/0 0/0 0/0 .text            checkWolfDig__9daPy_py_cCFv */
BOOL daPy_py_c::checkWolfDig() const {
    return false;
}

/* 8014163C-80141644 13BF7C 0008+00 1/0 0/0 0/0 .text            checkCutCharge__9daPy_py_cCFv */
BOOL daPy_py_c::checkCutCharge() const {
    return false;
}

/* 80141644-8014164C 13BF84 0008+00 1/0 0/0 0/0 .text            checkCutTurnCharge__9daPy_py_cCFv
 */
BOOL daPy_py_c::checkCutTurnCharge() const {
    return false;
}

/* 8014164C-80141654 13BF8C 0008+00 1/0 0/0 0/0 .text checkCutLargeJumpCharge__9daPy_py_cCFv */
BOOL daPy_py_c::checkCutLargeJumpCharge() const {
    return false;
}

/* 80141654-8014165C 13BF94 0008+00 2/0 0/0 0/0 .text            getBokoFlamePos__9daPy_py_cFP4cXyz
 */
bool daPy_py_c::getBokoFlamePos(cXyz* param_0) {
    return false;
}

/* 8014165C-80141664 13BF9C 0008+00 1/0 0/0 0/0 .text            checkComboCutTurn__9daPy_py_cCFv */
BOOL daPy_py_c::checkComboCutTurn() const {
    return false;
}

/* 80141664-8014166C 13BFA4 0008+00 1/0 0/0 0/0 .text            checkClimbMove__9daPy_py_cCFv */
BOOL daPy_py_c::checkClimbMove() const {
    return false;
}

/* 8014166C-80141674 13BFAC 0008+00 1/0 0/0 0/0 .text            checkGrassWhistle__9daPy_py_cCFv */
BOOL daPy_py_c::checkGrassWhistle() const {
    return false;
}

/* 80141674-8014167C 13BFB4 0008+00 1/0 0/0 0/0 .text            checkBoarRun__9daPy_py_cCFv */
BOOL daPy_py_c::checkBoarRun() const {
    return false;
}

/* 8014167C-80141684 13BFBC 0008+00 2/0 0/0 0/0 .text            checkFmChainPut__9daPy_py_cCFv */
bool daPy_py_c::checkFmChainPut() const {
    return false;
}

/* 80141684-8014168C 13BFC4 0008+00 2/0 0/0 0/0 .text            checkHorseElecDamage__9daPy_py_cCFv
 */
bool daPy_py_c::checkHorseElecDamage() const {
    return false;
}

/* 8014168C-80141694 13BFCC 0008+00 1/0 0/0 0/0 .text getBaseAnimeFrameRate__9daPy_py_cCFv */
float daPy_py_c::getBaseAnimeFrameRate() const {
    return lit_6040;
}

/* 80141694-8014169C 13BFD4 0008+00 1/0 0/0 0/0 .text            getBaseAnimeFrame__9daPy_py_cCFv */
f32 daPy_py_c::getBaseAnimeFrame() const {
    return FLOAT_LABEL(lit_6108);
}

/* 8014169C-801416A0 13BFDC 0004+00 1/0 0/0 0/0 .text            setAnimeFrame__9daPy_py_cFf */
void daPy_py_c::setAnimeFrame(f32 param_0) {
    /* empty function */
}

/* 801416A0-801416A8 13BFE0 0008+00 1/0 0/0 0/0 .text checkWolfLock__9daPy_py_cCFP10fopAc_ac_c */
bool daPy_py_c::checkWolfLock(fopAc_ac_c* param_0) const {
    return false;
}

/* 801416A8-801416B0 13BFE8 0008+00 1/0 0/0 0/0 .text cancelWolfLock__9daPy_py_cFP10fopAc_ac_c */
bool daPy_py_c::cancelWolfLock(fopAc_ac_c* param_0) {
    return false;
}

/* 801416B0-801416B8 13BFF0 0008+00 1/0 0/0 0/0 .text            getItemID__9daPy_py_cCFv */
s32 daPy_py_c::getItemID() const {
    return -1;
}

/* 801416B8-801416C0 13BFF8 0008+00 1/0 0/0 0/0 .text exchangeGrabActor__9daPy_py_cFP10fopAc_ac_c
 */
bool daPy_py_c::exchangeGrabActor(fopAc_ac_c* param_0) {
    return false;
}

/* 801416C0-801416C8 13C000 0008+00 1/0 0/0 0/0 .text setForceGrab__9daPy_py_cFP10fopAc_ac_cii */
bool daPy_py_c::setForceGrab(fopAc_ac_c* param_0, int param_1, int param_2) {
    return false;
}

/* 801416C8-801416CC 13C008 0004+00 1/0 0/0 0/0 .text            setForcePutPos__9daPy_py_cFRC4cXyz
 */
void daPy_py_c::setForcePutPos(cXyz const& param_0) {
    /* empty function */
}

/* 801416CC-801416D4 13C00C 0008+00 1/0 0/0 0/0 .text            checkPlayerNoDraw__9daPy_py_cFv */
u32 daPy_py_c::checkPlayerNoDraw() {
    return false;
}

/* 801416D4-801416DC 13C014 0008+00 2/0 0/0 0/0 .text            checkRopeTag__9daPy_py_cFv */
bool daPy_py_c::checkRopeTag() {
    return false;
}

/* 801416DC-801416E0 13C01C 0004+00 1/0 0/0 0/0 .text            voiceStart__9daPy_py_cFUl */
void daPy_py_c::voiceStart(u32 param_0) {
    /* empty function */
}

/* 801416E0-801416E4 13C020 0004+00 1/0 0/0 0/0 .text            seStartOnlyReverb__9daPy_py_cFUl */
void daPy_py_c::seStartOnlyReverb(u32 param_0) {
    /* empty function */
}

/* 801416E4-801416E8 13C024 0004+00 1/0 0/0 0/0 .text seStartOnlyReverbLevel__9daPy_py_cFUl */
void daPy_py_c::seStartOnlyReverbLevel(u32 param_0) {
    /* empty function */
}

/* 801416E8-801416EC 13C028 0004+00 1/0 0/0 0/0 .text            setOutPower__9daPy_py_cFfsi */
void daPy_py_c::setOutPower(f32 param_0, s16 param_1, int param_2) {
    /* empty function */
}

/* 801416EC-801416F0 13C02C 0004+00 1/0 0/0 0/0 .text
 * setGrabCollisionOffset__9daPy_py_cFffP13cBgS_PolyInfo        */
void daPy_py_c::setGrabCollisionOffset(f32 param_0, f32 param_1, cBgS_PolyInfo* param_2) {
    /* empty function */
}

/* 801416F0-801416F4 13C030 0004+00 2/0 0/0 0/0 .text            onMagneGrab__9daPy_py_cFff */
void daPy_py_c::onMagneGrab(f32 param_0, f32 param_1) {
    /* empty function */
}

/* 801416F4-801416FC 13C034 0008+00 1/0 0/0 0/0 .text            getModelJointMtx__9daPy_py_cFUs */
MtxP daPy_py_c::getModelJointMtx(u16 param_0) {
    return NULL;
}

/* 801416FC-80141704 13C03C 0008+00 1/0 0/0 0/0 .text            getHeadMtx__9daPy_py_cFv */
MtxP daPy_py_c::getHeadMtx() {
    return NULL;
}

/* 80141704-8014170C 13C044 0008+00 1/0 0/0 0/0 .text setHookshotCarryOffset__9daPy_py_cFUiPC4cXyz
 */
bool daPy_py_c::setHookshotCarryOffset(unsigned int param_0, cXyz const* param_1) {
    return false;
}

/* 8014170C-80141714 13C04C 0008+00 1/0 0/0 0/0 .text            checkIronBallReturn__9daPy_py_cCFv
 */
bool daPy_py_c::checkIronBallReturn() const {
    return false;
}

/* 80141714-8014171C 13C054 0008+00 1/0 0/0 0/0 .text checkIronBallGroundStop__9daPy_py_cCFv */
bool daPy_py_c::checkIronBallGroundStop() const {
    return false;
}

/* 8014171C-80141724 13C05C 0008+00 1/0 0/0 0/0 .text
 * checkSingleBoarBattleSecondBowReady__9daPy_py_cCFv           */
BOOL daPy_py_c::checkSingleBoarBattleSecondBowReady() const {
    return false;
}

/* 80141724-8014172C 13C064 0008+00 2/0 0/0 0/0 .text checkPointSubWindowMode__9daPy_py_cCFv */
bool daPy_py_c::checkPointSubWindowMode() const {
    return false;
}

/* 8014172C-80141730 13C06C 0004+00 1/0 0/0 0/0 .text            setClothesChange__9daPy_py_cFi */
void daPy_py_c::setClothesChange(int param_0) {
    /* empty function */
}

/* 80141730-80141734 13C070 0004+00 1/0 0/0 0/0 .text setPlayerPosAndAngle__9daPy_py_cFPA4_f */
void daPy_py_c::setPlayerPosAndAngle(f32 (*param_0)[4]) {
    /* empty function */
}

/* 80141734-80141738 13C074 0004+00 1/0 0/0 0/0 .text
 * setPlayerPosAndAngle__9daPy_py_cFPC4cXyzPC5csXyz             */
void daPy_py_c::setPlayerPosAndAngle(cXyz const* param_0, csXyz const* param_1) {
    /* empty function */
}

/* 80141738-8014173C 13C078 0004+00 1/0 0/0 0/0 .text setPlayerPosAndAngle__9daPy_py_cFPC4cXyzsi
 */
void daPy_py_c::setPlayerPosAndAngle(cXyz const* param_0, s16 param_1, int param_2) {
    /* empty function */
}

/* 8014173C-80141744 13C07C 0008+00 1/0 0/0 0/0 .text            setThrowDamage__9daPy_py_cFsffiii
 */
bool daPy_py_c::setThrowDamage(s16 param_0, f32 param_1, f32 param_2, int param_3, int param_4,
                               int param_5) {
    return false;
}

/* 80141744-8014174C 13C084 0008+00 1/0 0/0 0/0 .text            checkSetNpcTks__9daPy_py_cFP4cXyzii
 */
bool daPy_py_c::checkSetNpcTks(cXyz* param_0, int param_1, int param_2) {
    return false;
}

/* 8014174C-80141754 13C08C 0008+00 1/0 0/0 0/0 .text            setRollJump__9daPy_py_cFffs */
int daPy_py_c::setRollJump(f32 param_0, f32 param_1, s16 param_2) {
    return 0;
}

/* 80141754-80141758 13C094 0004+00 1/0 0/0 0/0 .text playerStartCollisionSE__9daPy_py_cFUlUl */
void daPy_py_c::playerStartCollisionSE(u32 param_0, u32 param_1) {
    /* empty function */
}

/* 80141758-8014175C 13C098 0004+00 2/0 0/0 0/0 .text changeTextureAnime__9daPy_py_cFUsUsi */
void daPy_py_c::changeTextureAnime(u16 param_0, u16 param_1, int param_2) {
    /* empty function */
}

/* 8014175C-80141760 13C09C 0004+00 2/0 0/0 0/0 .text cancelChangeTextureAnime__9daPy_py_cFv */
void daPy_py_c::cancelChangeTextureAnime() {
    /* empty function */
}

/* 80141760-80141764 13C0A0 0004+00 1/0 0/0 0/0 .text cancelDungeonWarpReadyNeck__9daPy_py_cFv */
void daPy_py_c::cancelDungeonWarpReadyNeck() {
    /* empty function */
}

/* 80141764-80141768 13C0A4 0004+00 1/0 0/0 0/0 .text
 * onSceneChangeArea__9daPy_py_cFUcUcP10fopAc_ac_c              */
void daPy_py_c::onSceneChangeArea(u8 param_0, u8 param_1, fopAc_ac_c* param_2) {
    /* empty function */
}

/* 80141768-8014176C 13C0A8 0004+00 1/0 0/0 0/0 .text
 * onSceneChangeAreaJump__9daPy_py_cFUcUcP10fopAc_ac_c          */
void daPy_py_c::onSceneChangeAreaJump(u8 param_0, u8 param_1, fopAc_ac_c* param_2) {
    /* empty function */
}

/* 8014176C-80141770 13C0AC 0004+00 1/0 0/0 0/0 .text            onSceneChangeDead__9daPy_py_cFUci
 */
void daPy_py_c::onSceneChangeDead(u8 param_0, int param_1) {
    /* empty function */
}

/* 80141770-80141778 13C0B0 0008+00 1/0 0/0 0/0 .text            getSpinnerActor__9daPy_py_cFv */
fopAc_ac_c* daPy_py_c::getSpinnerActor() {
    return NULL;
}

/* 80141778-80141780 13C0B8 0008+00 1/0 0/0 0/0 .text checkHorseRideNotReady__9daPy_py_cCFv */
BOOL daPy_py_c::checkHorseRideNotReady() const {
    return false;
}

/* 80141780-80141788 13C0C0 0008+00 1/0 0/0 0/0 .text            checkArrowChargeEnd__9daPy_py_cCFv
 */
bool daPy_py_c::checkArrowChargeEnd() const {
    return false;
}

/* 80141788-80141790 13C0C8 0008+00 1/0 0/0 0/0 .text            getSearchBallScale__9daPy_py_cCFv
 */
f32 daPy_py_c::getSearchBallScale() const {
    return FLOAT_LABEL(lit_6108);
}

/* 80141790-80141798 13C0D0 0008+00 1/0 0/0 0/0 .text            checkFastShotTime__9daPy_py_cFv */
s16 daPy_py_c::checkFastShotTime() {
    return 0;
}

/* 80141798-801417A0 13C0D8 0008+00 1/0 0/0 0/0 .text            checkNoEquipItem__9daPy_py_cCFv */
bool daPy_py_c::checkNoEquipItem() const {
    return true;
}

/* 801417A0-801417A8 13C0E0 0008+00 2/0 0/0 0/0 .text            checkFireMaterial__9daPy_py_cCFv */
bool daPy_py_c::checkFireMaterial() const {
    return false;
}

/* 801417A8-801417B0 13C0E8 0008+00 1/0 0/0 0/0 .text            checkKandelaarSwing__9daPy_py_cCFi
 */
bool daPy_py_c::checkKandelaarSwing(int param_0) const {
    return false;
}

/* 801417B0-801417B8 13C0F0 0008+00 1/0 0/0 0/0 .text getBoardCutTurnOffsetAngleY__9daPy_py_cCFv
 */
s16 daPy_py_c::getBoardCutTurnOffsetAngleY() const {
    return 0;
}

/* 801417B8-801417C0 13C0F8 0008+00 2/0 0/0 0/0 .text            getMagneHitPos__9daPy_py_cFv */
cXyz* daPy_py_c::getMagneHitPos() {
    return &mSwordTopPos;
}

/* 801417C0-801417C8 13C100 0008+00 1/0 0/0 0/0 .text            getMagneBootsTopVec__9daPy_py_cFv
 */
cXyz* daPy_py_c::getMagneBootsTopVec() {
    return &current.pos;
}

/* 801417C8-801417D0 13C108 0008+00 1/0 0/0 0/0 .text            checkUseKandelaar__9daPy_py_cFi */
bool daPy_py_c::checkUseKandelaar(int param_0) {
    return false;
}

/* 801417D0-801417D4 13C110 0004+00 1/0 0/0 0/0 .text setDkCaught__9daPy_py_cFP10fopAc_ac_c */
void daPy_py_c::setDkCaught(fopAc_ac_c* param_0) {
    /* empty function */
}

/* 801417D4-801417D8 13C114 0004+00 1/0 0/0 0/0 .text onPressedDamage__9daPy_py_cFRC4cXyzs */
void daPy_py_c::onPressedDamage(cXyz const& param_0, s16 param_1) {
    /* empty function */
}

/* 801417D8-801417E0 13C118 0008+00 1/0 0/0 0/0 .text checkPriActorOwn__9daPy_py_cCFPC10fopAc_ac_c
 */
bool daPy_py_c::checkPriActorOwn(fopAc_ac_c const* param_0) const {
    return false;
}

/* 801417E0-801417E8 13C120 0008+00 1/0 0/0 0/0 .text
 * onWolfEnemyBiteAll__9daPy_py_cFP10fopAc_ac_cQ29daPy_py_c9daPy_FLG2 */
bool daPy_py_c::onWolfEnemyBiteAll(fopAc_ac_c* param_0, daPy_py_c::daPy_FLG2 param_1) {
    return false;
}

/* 801417E8-801417F0 13C128 0008+00 1/0 0/0 0/0 .text
 * checkWolfEnemyBiteAllOwn__9daPy_py_cCFPC10fopAc_ac_c         */
bool daPy_py_c::checkWolfEnemyBiteAllOwn(fopAc_ac_c const* param_0) const {
    return false;
}

/* 801417F0-801417F4 13C130 0004+00 1/0 0/0 0/0 .text setWolfEnemyHangBiteAngle__9daPy_py_cFs */
void daPy_py_c::setWolfEnemyHangBiteAngle(s16 param_0) {
    /* empty function */
}

/* 801417F4-801417F8 13C134 0004+00 1/0 0/0 0/0 .text            setKandelaarMtx__9daPy_py_cFPA4_fii
 */
void daPy_py_c::setKandelaarMtx(f32 (*param_0)[4], int param_1, int param_2) {
    /* empty function */
}

/* 801417F8-80141800 13C138 0008+00 1/0 0/0 0/0 .text getStickAngleFromPlayerShape__9daPy_py_cCFPs
 */
bool daPy_py_c::getStickAngleFromPlayerShape(s16* param_0) const {
    return false;
}

/* 80141800-80141808 13C140 0008+00 1/0 0/0 0/0 .text            checkSpinnerPathMove__9daPy_py_cFv
 */
bool daPy_py_c::checkSpinnerPathMove() {
    return false;
}

/* 80141808-80141810 13C148 0008+00 1/0 0/0 0/0 .text checkSpinnerTriggerAttack__9daPy_py_cFv */
bool daPy_py_c::checkSpinnerTriggerAttack() {
    return false;
}

/* 80141810-80141814 13C150 0004+00 1/0 0/0 0/0 .text onSpinnerPathForceRemove__9daPy_py_cFv */
void daPy_py_c::onSpinnerPathForceRemove() {
    /* empty function */
}

/* 80141814-8014181C 13C154 0008+00 1/0 0/0 0/0 .text            getIronBallBgHit__9daPy_py_cCFv */
s16 daPy_py_c::getIronBallBgHit() const {
    return 0;
}

/* 8014181C-80141824 13C15C 0008+00 1/0 0/0 0/0 .text            getIronBallCenterPos__9daPy_py_cFv
 */
cXyz* daPy_py_c::getIronBallCenterPos() {
    return NULL;
}

/* 80141824-8014182C 13C164 0008+00 1/0 0/0 0/0 .text checkCanoeFishingGetLeft__9daPy_py_cCFv */
bool daPy_py_c::checkCanoeFishingGetLeft() const {
    return false;
}

/* 8014182C-80141834 13C16C 0008+00 1/0 0/0 0/0 .text checkCanoeFishingGetRight__9daPy_py_cCFv */
bool daPy_py_c::checkCanoeFishingGetRight() const {
    return false;
}

/* 80141834-8014183C 13C174 0008+00 1/0 0/0 0/0 .text            checkBeeChildDrink__9daPy_py_cCFv
 */
u8 daPy_py_c::checkBeeChildDrink() const {
    return false;
}

/* 8014183C-80141840 13C17C 0004+00 1/0 0/0 0/0 .text            skipPortalObjWarp__9daPy_py_cFv */
void daPy_py_c::skipPortalObjWarp() {
    /* empty function */
}

/* 80141840-80141848 13C180 0008+00 1/0 0/0 0/0 .text checkTreasureRupeeReturn__9daPy_py_cCFi */
BOOL daPy_py_c::checkTreasureRupeeReturn(int param_0) const {
    return false;
}

/* 80141848-8014184C 13C188 0004+00 1/0 0/0 0/0 .text setSumouReady__9daPy_py_cFP10fopAc_ac_c */
void daPy_py_c::setSumouReady(fopAc_ac_c* param_0) {
    /* empty function */
}

/* 8014184C-80141854 13C18C 0008+00 1/0 0/0 0/0 .text checkAcceptDungeonWarpAlink__9daPy_py_cFi */
bool daPy_py_c::checkAcceptDungeonWarpAlink(int param_0) {
    return false;
}

/* 80141854-8014185C 13C194 0008+00 1/0 0/0 0/0 .text            getSumouCounter__9daPy_py_cCFv */
s16 daPy_py_c::getSumouCounter() const {
    return 0;
}

/* 8014185C-80141864 13C19C 0008+00 1/0 0/0 0/0 .text            checkSumouWithstand__9daPy_py_cCFv
 */
s16 daPy_py_c::checkSumouWithstand() const {
    return 0;
}

/* 80141864-80141868 13C1A4 0004+00 1/0 0/0 0/0 .text            cancelGoronThrowEvent__9daPy_py_cFv
 */
void daPy_py_c::cancelGoronThrowEvent() {
    /* empty function */
}

/* 80141868-8014186C 13C1A8 0004+00 1/0 0/0 0/0 .text setSumouGraspCancelCount__9daPy_py_cFi */
void daPy_py_c::setSumouGraspCancelCount(int param_0) {
    /* empty function */
}

/* 8014186C-80141870 13C1AC 0004+00 1/0 0/0 0/0 .text setSumouPushBackDirection__9daPy_py_cFs */
void daPy_py_c::setSumouPushBackDirection(s16 param_0) {
    /* empty function */
}

/* 80141870-80141874 13C1B0 0004+00 1/0 0/0 0/0 .text            setSumouLoseHeadUp__9daPy_py_cFv */
void daPy_py_c::setSumouLoseHeadUp() {
    /* empty function */
}

/* 80141874-8014187C 13C1B4 0008+00 1/0 0/0 0/0 .text getGiantPuzzleAimAngle__9daPy_py_cCFv */
s16 daPy_py_c::getGiantPuzzleAimAngle() const {
    return shape_angle.y;
}

/* 8014187C-80141880 13C1BC 0004+00 1/0 0/0 0/0 .text setGoronSideMove__9daPy_py_cFP10fopAc_ac_c
 */
void daPy_py_c::setGoronSideMove(fopAc_ac_c* param_0) {
    /* empty function */
}

/* 80141880-80141884 13C1C0 0004+00 1/0 0/0 0/0 .text setCargoCarry__9daPy_py_cFP10fopAc_ac_c */
void daPy_py_c::setCargoCarry(fopAc_ac_c* param_0) {
    /* empty function */
}

/* 80141884-8014188C 13C1C4 0008+00 2/0 0/0 0/0 .text            getDpdFarFlg__9daPy_py_cCFv */
bool daPy_py_c::getDpdFarFlg() const {
    return false;
}

/* 8014188C-80141894 13C1CC 0008+00 1/0 0/0 0/0 .text            getHookshotTopPos__9daPy_py_cFv */
cXyz* daPy_py_c::getHookshotTopPos() {
    return NULL;
}

/* 80141894-8014189C 13C1D4 0008+00 1/0 0/0 0/0 .text checkHookshotReturnMode__9daPy_py_cCFv */
bool daPy_py_c::checkHookshotReturnMode() const {
    return false;
}

/* 8014189C-801418A4 13C1DC 0008+00 1/0 0/0 0/0 .text checkHookshotShootReturnMode__9daPy_py_cCFv
 */
bool daPy_py_c::checkHookshotShootReturnMode() const {
    return false;
}

/* 801418A4-801418AC 13C1E4 0008+00 1/0 0/0 0/0 .text            checkOctaIealHang__9daPy_py_cCFv */
bool daPy_py_c::checkOctaIealHang() const {
    return false;
}

/* 801418AC-801418B0 13C1EC 0004+00 1/0 0/0 0/0 .text            cancelOctaIealHang__9daPy_py_cFv */
void daPy_py_c::cancelOctaIealHang() {
    /* empty function */
}

/* 801418B0-801418B4 13C1F0 0004+00 1/0 0/0 0/0 .text cancelDragonHangBackJump__9daPy_py_cFv */
void daPy_py_c::cancelDragonHangBackJump() {
    /* empty function */
}

/* 801418B4-801418B8 13C1F4 0004+00 1/0 0/0 0/0 .text            setOctaIealWildHang__9daPy_py_cFv
 */
void daPy_py_c::setOctaIealWildHang() {
    /* empty function */
}

/* 801418B8-801418C0 13C1F8 0008+00 1/0 0/0 0/0 .text            checkDragonHangRide__9daPy_py_cCFv
 */
bool daPy_py_c::checkDragonHangRide() const {
    return false;
}

/* 801418C0-801418C4 13C200 0004+00 1/0 0/0 0/0 .text changeDragonActor__9daPy_py_cFP10fopAc_ac_c
 */
void daPy_py_c::changeDragonActor(fopAc_ac_c* param_0) {
    /* empty function */
}

/* 801418C4-801418CC 13C204 0008+00 1/0 0/0 0/0 .text getClothesChangeWaitTimer__9daPy_py_cCFv */
u8 daPy_py_c::getClothesChangeWaitTimer() const {
    return 0;
}

/* 801418CC-801418D4 13C20C 0008+00 1/0 0/0 0/0 .text getShieldChangeWaitTimer__9daPy_py_cCFv */
u8 daPy_py_c::getShieldChangeWaitTimer() const {
    return 0;
}

/* 801418D4-801418DC 13C214 0008+00 1/0 0/0 0/0 .text getSwordChangeWaitTimer__9daPy_py_cCFv */
u8 daPy_py_c::getSwordChangeWaitTimer() const {
    return 0;
}

/* 801418DC-801418E4 13C21C 0008+00 1/0 0/0 0/0 .text            checkMetamorphose__9daPy_py_cCFv */
BOOL daPy_py_c::checkMetamorphose() const {
    return false;
}

/* 801418E4-801418EC 13C224 0008+00 1/0 0/0 0/0 .text checkWolfDownAttackPullOut__9daPy_py_cCFv */
BOOL daPy_py_c::checkWolfDownAttackPullOut() const {
    return false;
}

/* 801418EC-801418F4 13C22C 0008+00 1/0 0/0 0/0 .text checkBootsOrArmorHeavy__9daPy_py_cCFv */
BOOL daPy_py_c::checkBootsOrArmorHeavy() const {
    return false;
}

/* 801418F4-801418FC 13C234 0008+00 1/0 0/0 0/0 .text getBottleOpenAppearItem__9daPy_py_cCFv */
s32 daPy_py_c::getBottleOpenAppearItem() const {
    return -1;
}

/* 801418FC-80141904 13C23C 0008+00 1/0 0/0 0/0 .text            checkItemSwordEquip__9daPy_py_cCFv
 */
bool daPy_py_c::checkItemSwordEquip() const {
    return false;
}

/* 80141904-8014190C 13C244 0008+00 1/0 0/0 0/0 .text            getSinkShapeOffset__9daPy_py_cCFv
 */
f32 daPy_py_c::getSinkShapeOffset() const {
    return FLOAT_LABEL(lit_6108);
}

/* 8014190C-80141914 13C24C 0008+00 1/0 0/0 0/0 .text            checkSinkDead__9daPy_py_cCFv */
BOOL daPy_py_c::checkSinkDead() const {
    return false;
}

/* 80141914-8014191C 13C254 0008+00 1/0 0/0 0/0 .text            checkHorseStart__9daPy_py_cFv */
BOOL daPy_py_c::checkHorseStart() {
    return false;
}

/* 8014191C-80141924 13C25C 0008+00 1/0 0/0 0/0 .text            getWolfHowlMgrP__9daPy_py_cFv */
Z2WolfHowlMgr* daPy_py_c::getWolfHowlMgrP() {
    return NULL;
}

/* 80141924-8014192C 13C264 0008+00 1/0 0/0 0/0 .text checkWolfHowlSuccessAnime__9daPy_py_cCFv */
BOOL daPy_py_c::checkWolfHowlSuccessAnime() const {
    return false;
}

/* 8014192C-80141934 13C26C 0008+00 1/0 0/0 0/0 .text            checkCopyRodTopUse__9daPy_py_cFv */
BOOL daPy_py_c::checkCopyRodTopUse() {
    return false;
}

/* 80141934-8014193C 13C274 0008+00 1/0 0/0 0/0 .text            checkCopyRodEquip__9daPy_py_cCFv */
bool daPy_py_c::checkCopyRodEquip() const {
    return false;
}

/* 8014193C-80141944 13C27C 0008+00 1/0 0/0 0/0 .text            checkCutJumpMode__9daPy_py_cCFv */
BOOL daPy_py_c::checkCutJumpMode() const {
    return false;
}

/* 80141944-8014194C 13C284 0008+00 1/1 0/0 0/0 .text            getZeldaActor__9daHorse_cFv */
fopAc_ac_c* daHorse_c::getZeldaActor() {
    return mZeldaActorKeep.getActor();
}

/* 8014194C-8014195C 13C28C 0010+00 1/1 0/0 0/0 .text            dComIfGp_getDoStatus__Fv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
static asm u8 dComIfGp_getDoStatus() {
    nofralloc
#include "asm/d/a/d_a_alink/dComIfGp_getDoStatus__Fv.s"
}
#pragma pop

/* 8014195C-8014196C 13C29C 0010+00 1/1 5/5 0/0 .text            __ct__4cXyzFfff */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void __ct__4cXyzFfff(f32 param_0, f32 param_1, f32 param_2) {
    nofralloc
#include "asm/d/a/d_a_alink/__ct__4cXyzFfff.s"
}
#pragma pop

/* 8014196C-80141988 13C2AC 001C+00 1/1 0/0 0/0 .text            dMeter2Info_offUseButton__Fi */
static void dMeter2Info_offUseButton(int pButton) {
    g_meter2_info.offUseButton(pButton);
}

/* 80141988-80141990 -00001 0008+00 0/0 0/0 0/0 .text            setLinkState__14Z2CreatureLinkFUc
 */
void Z2CreatureLink::setLinkState(u8 pState) {
    mLinkState = pState;
}

/* 80141990-801419A0 13C2D0 0010+00 1/1 0/0 0/0 .text            dComIfGs_getRupee__Fv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm u16 dComIfGs_getRupee() {
    nofralloc
#include "asm/d/a/d_a_alink/dComIfGs_getRupee__Fv.s"
}
#pragma pop

/* 801419A0-801419B8 13C2E0 0018+00 1/1 0/0 0/0 .text            dComIfGp_setItemRupeeCount__Fl */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void dComIfGp_setItemRupeeCount(s32 param_0) {
    nofralloc
#include "asm/d/a/d_a_alink/dComIfGp_setItemRupeeCount__Fl.s"
}
#pragma pop

/* 801419B8-801419F4 13C2F8 003C+00 1/1 0/0 0/0 .text dMeter2Info_setFloatingMessage__FUssb */
static void dMeter2Info_setFloatingMessage(u16 pMessageID, s16 pMessageTimer, bool pWakuVisible) {
    g_meter2_info.setFloatingMessage(pMessageID, pMessageTimer, pWakuVisible);
}

/* 801419F4-80141A04 13C334 0010+00 1/1 0/0 0/0 .text            onForcePanic__9daMidna_cFv */
void daMidna_c::onForcePanic() {
    onEndResetStateFlg0(ERFLG0_FORCE_PANIC);
}

/* 80141A04-80141A10 13C344 000C+00 1/1 0/0 0/0 .text checkForceNormalColor__9daMidna_cCFv */
u32 daMidna_c::checkForceNormalColor() const {
    return checkStateFlg1(FLG1_FORCE_NORMAL_COL);
}

/* 80141A10-80141A1C 13C350 000C+00 1/1 0/0 0/0 .text            checkForceTiredColor__9daMidna_cCFv
 */
u32 daMidna_c::checkForceTiredColor() const {
    return checkStateFlg1(FLG1_FORCE_TIRED_COL);
}

/* 80141A1C-80141A84 13C35C 0068+00 1/1 0/0 0/0 .text            checkMidnaTired__9daMidna_cFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm bool daMidna_c::checkMidnaTired() {
    nofralloc
#include "asm/d/a/d_a_alink/checkMidnaTired__9daMidna_cFv.s"
}
#pragma pop

/* 80141A84-80141A94 13C3C4 0010+00 1/1 0/0 0/0 .text            onNoServiceWait__9daMidna_cFv */
void daMidna_c::onNoServiceWait() {
    onEndResetStateFlg0(ERFLG0_NO_SERVICE_WAIT);
}

/* 80141A94-80141ACC 13C3D4 0038+00 1/1 0/0 0/0 .text            setControllActorData__8daCrod_cFv
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daCrod_c::setControllActorData() {
    nofralloc
#include "asm/d/a/d_a_alink/setControllActorData__8daCrod_cFv.s"
}
#pragma pop

/* 80141ACC-80141AE8 13C40C 001C+00 1/1 0/0 0/0 .text
 * PrmAbstract<Q312daObjMovebox5Act_c5Prm_e>__5daObjFPC10fopAc_ac_cQ312daObjMovebox5Act_c5Prm_eQ312daObjMovebox5Act_c5Prm_e
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void func_80141ACC(void* _this, fopAc_ac_c const* param_0,
                                  daObjMovebox::Act_c::Prm_e param_1,
                                  daObjMovebox::Act_c::Prm_e param_2) {
    nofralloc
#include "asm/d/a/d_a_alink/func_80141ACC.s"
}
#pragma pop

/* 80141AE8-80141B04 13C428 001C+00 1/1 4/4 0/0 .text            cLib_calcTimer<Uc>__FPUc */
extern "C" int func_80141AE8(u8* pTimer) {
    if (*pTimer != 0) {
        *pTimer -= 1;
    }
    return *pTimer;
}

/* ############################################################################################## */
/* 80453344-80453348 001944 0004+00 1/1 0/0 0/0 .sdata2          @77808 */
SECTION_SDATA2 static f32 lit_77808 = 1.2427899837493896f;

/* 80453348-8045334C 001948 0004+00 1/1 0/0 0/0 .sdata2          @77809 */
SECTION_SDATA2 static f32 lit_77809 = 102.00054168701172f;

/* 8045334C-80453350 00194C 0004+00 1/1 0/0 0/0 .sdata2          @77810 */
SECTION_SDATA2 static f32 lit_77810 = -4.248938083648682f;

/* 80453350-80453354 001950 0004+00 1/1 0/0 0/0 .sdata2          @77811 */
SECTION_SDATA2 static f32 lit_77811 = 89.0f;

/* 80453354-80453358 001954 0004+00 1/1 0/0 0/0 .sdata2          @77812 */
SECTION_SDATA2 static f32 lit_77812 = -5.267045021057129f;

/* 80453358-8045335C 001958 0004+00 1/1 0/0 0/0 .sdata2          @77813 */
SECTION_SDATA2 static f32 lit_77813 = 4.313951015472412f;

/* 8045335C-80453360 00195C 0004+00 1/1 0/0 0/0 .sdata2          @77814 */
SECTION_SDATA2 static f32 lit_77814 = 93.9443588256836f;

/* 80453360-80453364 001960 0004+00 1/1 0/0 0/0 .sdata2          @77815 */
SECTION_SDATA2 static f32 lit_77815 = -5.207283020019531f;

/* 80453364-80453368 001964 0004+00 1/1 0/0 0/0 .sdata2          @77816 */
SECTION_SDATA2 static f32 lit_77816 = -4.30098819732666f;

/* 80453368-8045336C 001968 0004+00 1/1 0/0 0/0 .sdata2          @77817 */
SECTION_SDATA2 static f32 lit_77817 = 93.95594787597656f;

/* 8045336C-80453370 00196C 0004+00 1/1 0/0 0/0 .sdata2          @77818 */
SECTION_SDATA2 static f32 lit_77818 = -5.218503952026367f;

/* 80453370-80453374 001970 0004+00 1/1 0/0 0/0 .sdata2          @77819 */
SECTION_SDATA2 static f32 lit_77819 = 225.6999969482422f;

/* 80453374-80453378 001974 0004+00 1/1 0/0 0/0 .sdata2          @77820 */
SECTION_SDATA2 static f32 lit_77820 = 1.809999942779541f;

/* 80453378-8045337C 001978 0004+00 1/1 0/0 0/0 .sdata2          @77821 */
SECTION_SDATA2 static f32 lit_77821 = 186.1699981689453f;

/* 8045337C-80453380 00197C 0004+00 1/1 0/0 0/0 .sdata2          @77822 */
SECTION_SDATA2 static f32 lit_77822 = -20.290000915527344f;

/* 80453380-80453384 001980 0004+00 1/1 0/0 0/0 .sdata2          @77823 */
SECTION_SDATA2 static f32 lit_77823 = -68.208984375f;

/* 80453384-80453388 001984 0004+00 1/1 0/0 0/0 .sdata2          @77824 */
SECTION_SDATA2 static f32 lit_77824 = 41.60992431640625f;

/* 80453388-8045338C 001988 0004+00 1/1 0/0 0/0 .sdata2          @77825 */
SECTION_SDATA2 static f32 lit_77825 = 0.8837890028953552f;

/* 8045338C-80453390 00198C 0004+00 1/1 0/0 0/0 .sdata2          @77826 */
SECTION_SDATA2 static f32 lit_77826 = -72.0f;

/* 80453390-80453394 001990 0004+00 1/1 0/0 0/0 .sdata2          @77827 */
SECTION_SDATA2 static f32 lit_77827 = 88.63934326171875f;

/* 80453394-80453398 001994 0004+00 1/1 0/0 0/0 .sdata2          @77828 */
SECTION_SDATA2 static f32 lit_77828 = -28.49793243408203f;

/* 80453398-8045339C 001998 0004+00 1/1 0/0 0/0 .sdata2          @77829 */
SECTION_SDATA2 static f32 lit_77829 = 0.11516399681568146f;

/* 8045339C-804533A0 00199C 0004+00 1/1 0/0 0/0 .sdata2          @77830 */
SECTION_SDATA2 static f32 lit_77830 = 68.33629608154297f;

/* 804533A0-804533A8 0019A0 0004+04 1/1 0/0 0/0 .sdata2          @77831 */
SECTION_SDATA2 static f32 lit_77831[1 + 1 /* padding */] = {
    -7.667817115783691f,
    /* padding */
    0.0f,
};

/* 80141B04-801446D4 13C444 2BD0+00 0/0 1/0 0/0 .text            __sinit_d_a_alink_cpp */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __sinit_d_a_alink_cpp(){nofralloc
#include "asm/d/a/d_a_alink/__sinit_d_a_alink_cpp.s"
}
#pragma pop

#pragma push
#pragma force_active on
REGISTER_CTORS(0x80141B04, __sinit_d_a_alink_cpp);
#pragma pop

/* 801446D4-801446DC 13F014 0008+00 1/0 0/0 0/0 .text            @36@__dt__12dBgS_ObjAcchFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
static asm void func_801446D4() {
    nofralloc
#include "asm/d/a/d_a_alink/func_801446D4.s"
}
#pragma pop

/* 801446DC-801446E4 13F01C 0008+00 1/0 0/0 0/0 .text            @20@__dt__12dBgS_ObjAcchFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
static asm void func_801446DC() {
    nofralloc
#include "asm/d/a/d_a_alink/func_801446DC.s"
}
#pragma pop

/* 801446E4-801446EC 13F024 0008+00 1/0 0/0 0/0 .text            @36@__dt__13dBgS_LinkAcchFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
static asm void func_801446E4() {
    nofralloc
#include "asm/d/a/d_a_alink/func_801446E4.s"
}
#pragma pop

/* 801446EC-801446F4 13F02C 0008+00 1/0 0/0 0/0 .text            @20@__dt__13dBgS_LinkAcchFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
static asm void func_801446EC() {
    nofralloc
#include "asm/d/a/d_a_alink/func_801446EC.s"
}
#pragma pop

/* 801446F4-801446FC 13F034 0008+00 1/0 0/0 0/0 .text            @20@__dt__15dBgS_LinkGndChkFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
static asm void func_801446F4() {
    nofralloc
#include "asm/d/a/d_a_alink/func_801446F4.s"
}
#pragma pop

/* 801446FC-80144704 13F03C 0008+00 1/0 0/0 0/0 .text            @76@__dt__15dBgS_LinkGndChkFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
static asm void func_801446FC() {
    nofralloc
#include "asm/d/a/d_a_alink/func_801446FC.s"
}
#pragma pop

/* 80144704-8014470C 13F044 0008+00 1/0 0/0 0/0 .text            @60@__dt__15dBgS_LinkGndChkFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
static asm void func_80144704() {
    nofralloc
#include "asm/d/a/d_a_alink/func_80144704.s"
}
#pragma pop

/* 8014470C-80144714 13F04C 0008+00 1/0 0/0 0/0 .text            @16@__dt__16dBgS_LinkRoofChkFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
static asm void func_8014470C() {
    nofralloc
#include "asm/d/a/d_a_alink/func_8014470C.s"
}
#pragma pop

/* 80144714-8014471C 13F054 0008+00 1/0 0/0 0/0 .text            @52@__dt__16dBgS_LinkRoofChkFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
static asm void func_80144714() {
    nofralloc
#include "asm/d/a/d_a_alink/func_80144714.s"
}
#pragma pop

/* 8014471C-80144724 13F05C 0008+00 1/0 0/0 0/0 .text            @36@__dt__16dBgS_LinkRoofChkFv */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
static asm void func_8014471C() {
    nofralloc
#include "asm/d/a/d_a_alink/func_8014471C.s"
}
#pragma pop

/* 80392094-80392094 01E6F4 0000+00 0/0 0/0 0/0 .rodata          @stringBase0 */