#ifndef RES_BANNERICON_H
#define RES_BANNERICON_H

enum dRes_INDEX_BANNERICON {
    /* ROOT */
    dRes_INDEX_BANNERICON_BTI_ZELDA2_GC_BANNER_e=0x0,
    dRes_INDEX_BANNERICON_BTI_ZELDA2_GC_ICON_e=0x1,
    dRes_INDEX_BANNERICON_BTI_ZELDA2_WII_BANNER_e=0x2,
    dRes_INDEX_BANNERICON_BTI_ZELDA2_WII_ICON_e=0x3,
};

enum dRes_ID_BANNERICON {
    /* ROOT */
    dRes_ID_BANNERICON_BTI_ZELDA2_GC_BANNER_e=0x0,
    dRes_ID_BANNERICON_BTI_ZELDA2_GC_ICON_e=0x1,
    dRes_ID_BANNERICON_BTI_ZELDA2_WII_BANNER_e=0x2,
    dRes_ID_BANNERICON_BTI_ZELDA2_WII_ICON_e=0x3,
};

#endif /* !RES_BANNERICON_H */