#ifndef RES_FISHRES_H
#define RES_FISHRES_H

enum dRes_INDEX_FISHRES {
    /* SCRN */
    dRes_INDEX_FISHRES_BLO_ZELDA_COLLECT_SOUBI_DO_ICON_PARTS_e=0x4,
    dRes_INDEX_FISHRES_BLO_ZELDA_FISH_WINDOW_e=0x5,
    /* TIMG */
    dRes_INDEX_FISHRES_BTI_BOW_LIGHT_e=0x8,
    dRes_INDEX_FISHRES_BTI_I4_GRA_e=0x9,
    dRes_INDEX_FISHRES_BTI_TT_BLOCK128_00_e=0xA,
    dRes_INDEX_FISHRES_BTI_TT_BLOCK8X8_e=0xB,
    dRes_INDEX_FISHRES_BTI_TT_DO_ICON7_160_174_e=0xC,
    dRes_INDEX_FISHRES_BTI_TT_GOLD_UZU_LONG2_e=0xD,
    dRes_INDEX_FISHRES_BTI_TT_HORIWAKU_TOP_RR_e=0xE,
    dRes_INDEX_FISHRES_BTI_TT_I4_GRA_e=0xF,
    dRes_INDEX_FISHRES_BTI_TT_LINE2_e=0x10,
    dRes_INDEX_FISHRES_BTI_TT_YAKUSHIMA_e=0x11,
    dRes_INDEX_FISHRES_BTI_TT_ZELDA_BUTTON_AB_MARU_e=0x12,
    dRes_INDEX_FISHRES_BTI_TT_ZELDA_BUTTON_A_TEXT_e=0x13,
    dRes_INDEX_FISHRES_BTI_TT_ZELDA_BUTTON_B_TEXT_e=0x14,
    dRes_INDEX_FISHRES_BTI_YR_ICON_BASS_e=0x15,
    dRes_INDEX_FISHRES_BTI_YR_ICON_BLUEGIL_e=0x16,
    dRes_INDEX_FISHRES_BTI_YR_ICON_CATFISH_e=0x17,
    dRes_INDEX_FISHRES_BTI_YR_ICON_DOJOU_e=0x18,
    dRes_INDEX_FISHRES_BTI_YR_ICON_NIOIMASU_e=0x19,
    dRes_INDEX_FISHRES_BTI_YR_ICON_PIKE_e=0x1A,
};

enum dRes_ID_FISHRES {
    /* SCRN */
    dRes_ID_FISHRES_BLO_ZELDA_COLLECT_SOUBI_DO_ICON_PARTS_e=0x4,
    dRes_ID_FISHRES_BLO_ZELDA_FISH_WINDOW_e=0x5,
    /* TIMG */
    dRes_ID_FISHRES_BTI_BOW_LIGHT_e=0x8,
    dRes_ID_FISHRES_BTI_I4_GRA_e=0x9,
    dRes_ID_FISHRES_BTI_TT_BLOCK128_00_e=0xA,
    dRes_ID_FISHRES_BTI_TT_BLOCK8X8_e=0xB,
    dRes_ID_FISHRES_BTI_TT_DO_ICON7_160_174_e=0xC,
    dRes_ID_FISHRES_BTI_TT_GOLD_UZU_LONG2_e=0xD,
    dRes_ID_FISHRES_BTI_TT_HORIWAKU_TOP_RR_e=0xE,
    dRes_ID_FISHRES_BTI_TT_I4_GRA_e=0xF,
    dRes_ID_FISHRES_BTI_TT_LINE2_e=0x10,
    dRes_ID_FISHRES_BTI_TT_YAKUSHIMA_e=0x11,
    dRes_ID_FISHRES_BTI_TT_ZELDA_BUTTON_AB_MARU_e=0x12,
    dRes_ID_FISHRES_BTI_TT_ZELDA_BUTTON_A_TEXT_e=0x13,
    dRes_ID_FISHRES_BTI_TT_ZELDA_BUTTON_B_TEXT_e=0x14,
    dRes_ID_FISHRES_BTI_YR_ICON_BASS_e=0x15,
    dRes_ID_FISHRES_BTI_YR_ICON_BLUEGIL_e=0x16,
    dRes_ID_FISHRES_BTI_YR_ICON_CATFISH_e=0x17,
    dRes_ID_FISHRES_BTI_YR_ICON_DOJOU_e=0x18,
    dRes_ID_FISHRES_BTI_YR_ICON_NIOIMASU_e=0x19,
    dRes_ID_FISHRES_BTI_YR_ICON_PIKE_e=0x1A,
};

#endif /* !RES_FISHRES_H */