#ifndef RES_ITMINFRES_H
#define RES_ITMINFRES_H

enum dRes_INDEX_ITMINFRES {
    /* SCRN */
    dRes_INDEX_ITMINFRES_BLO_ZELDA_ITEM_SCREEN_INFO_e=0x4,
    dRes_INDEX_ITMINFRES_BLO_ZELDA_KANTERA_ICON_MATER_e=0x5,
    /* TIMG */
    dRes_INDEX_ITMINFRES_BTI_I4_GRA_e=0x8,
    dRes_INDEX_ITMINFRES_BTI_TT_BLOCK8X8_e=0x9,
    dRes_INDEX_ITMINFRES_BTI_TT_GOLD_UZU_LONG2_e=0xA,
    dRes_INDEX_ITMINFRES_BTI_TT_HORIWAKU_TOP_RR_e=0xB,
    dRes_INDEX_ITMINFRES_BTI_TT_I4_GRA_e=0xC,
    dRes_INDEX_ITMINFRES_BTI_TT_IASTAR01_e=0xD,
    dRes_INDEX_ITMINFRES_BTI_TT_KAZARI_KANI_00_e=0xE,
    dRes_INDEX_ITMINFRES_BTI_TT_LINE2_e=0xF,
    dRes_INDEX_ITMINFRES_BTI_TT_MIRROR_SHIELD_00_e=0x10,
    dRes_INDEX_ITMINFRES_BTI_TT_YAKUSHIMA_e=0x11,
};

enum dRes_ID_ITMINFRES {
    /* SCRN */
    dRes_ID_ITMINFRES_BLO_ZELDA_ITEM_SCREEN_INFO_e=0x4,
    dRes_ID_ITMINFRES_BLO_ZELDA_KANTERA_ICON_MATER_e=0x5,
    /* TIMG */
    dRes_ID_ITMINFRES_BTI_I4_GRA_e=0x8,
    dRes_ID_ITMINFRES_BTI_TT_BLOCK8X8_e=0x9,
    dRes_ID_ITMINFRES_BTI_TT_GOLD_UZU_LONG2_e=0xA,
    dRes_ID_ITMINFRES_BTI_TT_HORIWAKU_TOP_RR_e=0xB,
    dRes_ID_ITMINFRES_BTI_TT_I4_GRA_e=0xC,
    dRes_ID_ITMINFRES_BTI_TT_IASTAR01_e=0xD,
    dRes_ID_ITMINFRES_BTI_TT_KAZARI_KANI_00_e=0xE,
    dRes_ID_ITMINFRES_BTI_TT_LINE2_e=0xF,
    dRes_ID_ITMINFRES_BTI_TT_MIRROR_SHIELD_00_e=0x10,
    dRes_ID_ITMINFRES_BTI_TT_YAKUSHIMA_e=0x11,
};

#endif /* !RES_ITMINFRES_H */