#ifndef RES_CSTATUE_H
#define RES_CSTATUE_H

enum dRes_INDEX_CSTATUE {
    /* BCK  */
    dRes_INDEX_CSTATUE_BCK_CS_B_FALL_e=0x7,
    dRes_INDEX_CSTATUE_BCK_CS_B_JUMP_e=0x8,
    dRes_INDEX_CSTATUE_BCK_CS_B_WALK_e=0x9,
    dRes_INDEX_CSTATUE_BCK_CS_FALL_e=0xA,
    dRes_INDEX_CSTATUE_BCK_CS_START_e=0xB,
    dRes_INDEX_CSTATUE_BCK_CS_START_DEMO_e=0xC,
    dRes_INDEX_CSTATUE_BCK_CS_STOP_e=0xD,
    dRes_INDEX_CSTATUE_BCK_CS_SWING_e=0xE,
    dRes_INDEX_CSTATUE_BCK_CS_SWINGRE_e=0xF,
    dRes_INDEX_CSTATUE_BCK_CS_WALK_e=0x10,
    /* BMDR */
    dRes_INDEX_CSTATUE_BMD_CS_e=0x13,
    dRes_INDEX_CSTATUE_BMD_CS_B_e=0x14,
    dRes_INDEX_CSTATUE_BMD_CS_OBJ_e=0x15,
    /* BMDV */
    dRes_INDEX_CSTATUE_BMD_CS_GHOST_e=0x18,
    /* BRK  */
    dRes_INDEX_CSTATUE_BRK_CS_B_START_e=0x1B,
    dRes_INDEX_CSTATUE_BRK_CS_B_STOP_e=0x1C,
    dRes_INDEX_CSTATUE_BRK_CS_GHOST_e=0x1D,
    dRes_INDEX_CSTATUE_BRK_CS_START_e=0x1E,
    dRes_INDEX_CSTATUE_BRK_CS_STOP_e=0x1F,
    /* BTK  */
    dRes_INDEX_CSTATUE_BTK_CS_GHOST_e=0x22,
    dRes_INDEX_CSTATUE_BTK_CS_START_e=0x23,
};

enum dRes_ID_CSTATUE {
    /* BCK  */
    dRes_ID_CSTATUE_BCK_CS_B_FALL_e=0x7,
    dRes_ID_CSTATUE_BCK_CS_B_JUMP_e=0x8,
    dRes_ID_CSTATUE_BCK_CS_B_WALK_e=0x9,
    dRes_ID_CSTATUE_BCK_CS_FALL_e=0xA,
    dRes_ID_CSTATUE_BCK_CS_START_e=0xB,
    dRes_ID_CSTATUE_BCK_CS_START_DEMO_e=0xC,
    dRes_ID_CSTATUE_BCK_CS_STOP_e=0xD,
    dRes_ID_CSTATUE_BCK_CS_SWING_e=0xE,
    dRes_ID_CSTATUE_BCK_CS_SWINGRE_e=0xF,
    dRes_ID_CSTATUE_BCK_CS_WALK_e=0x10,
    /* BMDR */
    dRes_ID_CSTATUE_BMD_CS_e=0x13,
    dRes_ID_CSTATUE_BMD_CS_B_e=0x14,
    dRes_ID_CSTATUE_BMD_CS_OBJ_e=0x15,
    /* BMDV */
    dRes_ID_CSTATUE_BMD_CS_GHOST_e=0x18,
    /* BRK  */
    dRes_ID_CSTATUE_BRK_CS_B_START_e=0x1B,
    dRes_ID_CSTATUE_BRK_CS_B_STOP_e=0x1C,
    dRes_ID_CSTATUE_BRK_CS_GHOST_e=0x1D,
    dRes_ID_CSTATUE_BRK_CS_START_e=0x1E,
    dRes_ID_CSTATUE_BRK_CS_STOP_e=0x1F,
    /* BTK  */
    dRes_ID_CSTATUE_BTK_CS_GHOST_e=0x22,
    dRes_ID_CSTATUE_BTK_CS_START_e=0x23,
};

enum CS_JNT {
    CS_JNT_CENTER_e=0x0,
    CS_JNT_WAIST_e=0x1,
    CS_JNT_ARM_L1_e=0x2,
    CS_JNT_ARM_L2_e=0x3,
    CS_JNT_HAND_L_e=0x4,
    CS_JNT_HAMMER_e=0x5,
    CS_JNT_ARM_R1_e=0x6,
    CS_JNT_ARM_R2_e=0x7,
    CS_JNT_HAND_R_e=0x8,
    CS_JNT_HEAD_e=0x9,
};

enum CS_B_JNT {
    CS_B_JNT_CS_B_MODEL_e=0x0,
};

enum CS_OBJ_JNT {
    CS_OBJ_JNT_CENTER_e=0x0,
    CS_OBJ_JNT_WAIST_e=0x1,
    CS_OBJ_JNT_ARM_L1_e=0x2,
    CS_OBJ_JNT_ARM_L2_e=0x3,
    CS_OBJ_JNT_HAND_L_e=0x4,
    CS_OBJ_JNT_HAMMER_e=0x5,
    CS_OBJ_JNT_ARM_R1_e=0x6,
    CS_OBJ_JNT_ARM_R2_e=0x7,
    CS_OBJ_JNT_HAND_R_e=0x8,
    CS_OBJ_JNT_HEAD_e=0x9,
};

enum CS_GHOST_JNT {
    CS_GHOST_JNT_CENTER_e=0x0,
    CS_GHOST_JNT_WAIST_e=0x1,
    CS_GHOST_JNT_ARM_L1_e=0x2,
    CS_GHOST_JNT_ARM_L2_e=0x3,
    CS_GHOST_JNT_HAND_L_e=0x4,
    CS_GHOST_JNT_HAMMER_e=0x5,
    CS_GHOST_JNT_ARM_R1_e=0x6,
    CS_GHOST_JNT_ARM_R2_e=0x7,
    CS_GHOST_JNT_HAND_R_e=0x8,
    CS_GHOST_JNT_HEAD_e=0x9,
};

#endif /* !RES_CSTATUE_H */