#ifndef RES_HOZ_TW_H
#define RES_HOZ_TW_H

enum dRes_INDEX_HOZ_TW {
    /* BMDR */
    dRes_INDEX_HOZ_TW_BMD_HOZ_TW_MODEL_e=0x3,
};

enum dRes_ID_HOZ_TW {
    /* BMDR */
    dRes_ID_HOZ_TW_BMD_HOZ_TW_MODEL_e=0x3,
};

enum HOZ_TW_MODEL_JNT {
    HOZ_TW_MODEL_JNT_CENTER_e=0x0,
    HOZ_TW_MODEL_JNT_BACKBORN1_e=0x1,
    HOZ_TW_MODEL_JNT_BACKBORN2_e=0x2,
    HOZ_TW_MODEL_JNT_NECK_e=0x3,
    HOZ_TW_MODEL_JNT_HEAD_e=0x4,
    HOZ_TW_MODEL_JNT_CHIN_e=0x5,
    HOZ_TW_MODEL_JNT_HAIR_e=0x6,
    HOZ_TW_MODEL_JNT_MAYU_L_e=0x7,
    HOZ_TW_MODEL_JNT_MAYU_R_e=0x8,
    HOZ_TW_MODEL_JNT_MOUTH_e=0x9,
    HOZ_TW_MODEL_JNT_SHOULDER_L_e=0xA,
    HOZ_TW_MODEL_JNT_ARM1_L_e=0xB,
    HOZ_TW_MODEL_JNT_ARM2_L_e=0xC,
    HOZ_TW_MODEL_JNT_HAND_L_e=0xD,
    HOZ_TW_MODEL_JNT_FINGER_L_e=0xE,
    HOZ_TW_MODEL_JNT_THUMB_L_e=0xF,
    HOZ_TW_MODEL_JNT_SHOULDER_R_e=0x10,
    HOZ_TW_MODEL_JNT_ARM1_R_e=0x11,
    HOZ_TW_MODEL_JNT_ARM2_R_e=0x12,
    HOZ_TW_MODEL_JNT_HAND_R_e=0x13,
    HOZ_TW_MODEL_JNT_FINGER_R_e=0x14,
    HOZ_TW_MODEL_JNT_THUMB_R_e=0x15,
    HOZ_TW_MODEL_JNT_SUSPENDER_e=0x16,
    HOZ_TW_MODEL_JNT_WAIST_e=0x17,
    HOZ_TW_MODEL_JNT_LEG1_L_e=0x18,
    HOZ_TW_MODEL_JNT_LEG2_L_e=0x19,
    HOZ_TW_MODEL_JNT_FOOT_L_e=0x1A,
    HOZ_TW_MODEL_JNT_LEG1_R_e=0x1B,
    HOZ_TW_MODEL_JNT_LEG2_R_e=0x1C,
    HOZ_TW_MODEL_JNT_FOOT_R_e=0x1D,
};

#endif /* !RES_HOZ_TW_H */