#ifndef RES_L9PICTURE_H
#define RES_L9PICTURE_H

enum dRes_INDEX_L9PICTURE {
    /* BMDR */
    dRes_INDEX_L9PICTURE_BMD_L_ROPEST_e=0x5,
    dRes_INDEX_L9PICTURE_BMD_LV9_PICTURE_A_e=0x6,
    dRes_INDEX_L9PICTURE_BMD_LV9_PICTURE_B_e=0x7,
    /* DZB  */
    dRes_INDEX_L9PICTURE_DZB_LV9_PICTURE_e=0xA,
    dRes_INDEX_L9PICTURE_DZB_LV9_ROPEST_e=0xB,
    /* TEX  */
    dRes_INDEX_L9PICTURE_BTI_P_LV9_ROPE_e=0xE,
};

enum dRes_ID_L9PICTURE {
    /* BMDR */
    dRes_ID_L9PICTURE_BMD_L_ROPEST_e=0x5,
    dRes_ID_L9PICTURE_BMD_LV9_PICTURE_A_e=0x6,
    dRes_ID_L9PICTURE_BMD_LV9_PICTURE_B_e=0x7,
    /* DZB  */
    dRes_ID_L9PICTURE_DZB_LV9_PICTURE_e=0xA,
    dRes_ID_L9PICTURE_DZB_LV9_ROPEST_e=0xB,
    /* TEX  */
    dRes_ID_L9PICTURE_BTI_P_LV9_ROPE_e=0xE,
};

enum L_ROPEST_JNT {
    L_ROPEST_JNT_WORLD_ROOT_e=0x0,
};

enum LV9_PICTURE_A_JNT {
    LV9_PICTURE_A_JNT_WORLD_ROOT_e=0x0,
};

enum LV9_PICTURE_B_JNT {
    LV9_PICTURE_B_JNT_WORLD_ROOT_e=0x0,
};

#endif /* !RES_L9PICTURE_H */