#ifndef RES_MIRRORB_H
#define RES_MIRRORB_H

enum dRes_INDEX_MIRRORB {
    /* BCK  */
    dRes_INDEX_MIRRORB_BCK_KAGERI_MIRRER_GET_APPEAR_e=0x5,
    dRes_INDEX_MIRRORB_BCK_KAGERI_MIRRER_GET_SCALEDOWN_e=0x6,
    /* BMDV */
    dRes_INDEX_MIRRORB_BMD_KAGERI_MIRRER_GET_2_e=0x9,
    dRes_INDEX_MIRRORB_BMD_KAGERI_MIRRER_GET_3_e=0xA,
    dRes_INDEX_MIRRORB_BMD_KAGERI_MIRRER_GET_4_e=0xB,
    /* BTK  */
    dRes_INDEX_MIRRORB_BTK_KAGERI_MIRRER_GET_SCALEDOWN_2_e=0xE,
    dRes_INDEX_MIRRORB_BTK_KAGERI_MIRRER_GET_SCALEDOWN_3_e=0xF,
    dRes_INDEX_MIRRORB_BTK_KAGERI_MIRRER_GET_SCALEDOWN_4_e=0x10,
};

enum dRes_ID_MIRRORB {
    /* BCK  */
    dRes_ID_MIRRORB_BCK_KAGERI_MIRRER_GET_APPEAR_e=0x5,
    dRes_ID_MIRRORB_BCK_KAGERI_MIRRER_GET_SCALEDOWN_e=0x6,
    /* BMDV */
    dRes_ID_MIRRORB_BMD_KAGERI_MIRRER_GET_2_e=0x9,
    dRes_ID_MIRRORB_BMD_KAGERI_MIRRER_GET_3_e=0xA,
    dRes_ID_MIRRORB_BMD_KAGERI_MIRRER_GET_4_e=0xB,
    /* BTK  */
    dRes_ID_MIRRORB_BTK_KAGERI_MIRRER_GET_SCALEDOWN_2_e=0xE,
    dRes_ID_MIRRORB_BTK_KAGERI_MIRRER_GET_SCALEDOWN_3_e=0xF,
    dRes_ID_MIRRORB_BTK_KAGERI_MIRRER_GET_SCALEDOWN_4_e=0x10,
};

enum KAGERI_MIRRER_GET_2_JNT {
    KAGERI_MIRRER_GET_2_JNT_MIRRER_2_e=0x0,
};

enum KAGERI_MIRRER_GET_3_JNT {
    KAGERI_MIRRER_GET_3_JNT_MIRRER_3_e=0x0,
};

enum KAGERI_MIRRER_GET_4_JNT {
    KAGERI_MIRRER_GET_4_JNT_MIRRER_4_e=0x0,
};

#endif /* !RES_MIRRORB_H */