#ifndef RES_OBJ_L4BRG_H
#define RES_OBJ_L4BRG_H

enum dRes_INDEX_OBJ_L4BRG {
    /* BMDR */
    dRes_INDEX_OBJ_L4BRG_BMD_LV4R50_BRIDGE_e=0x4,
    /* DZB  */
    dRes_INDEX_OBJ_L4BRG_DZB_LV4R50_BRIDGE_e=0x7,
};

enum dRes_ID_OBJ_L4BRG {
    /* BMDR */
    dRes_ID_OBJ_L4BRG_BMD_LV4R50_BRIDGE_e=0x4,
    /* DZB  */
    dRes_ID_OBJ_L4BRG_DZB_LV4R50_BRIDGE_e=0x7,
};

enum LV4R50_BRIDGE_JNT {
    LV4R50_BRIDGE_JNT_WORLD_ROOT_e=0x0,
};

#endif /* !RES_OBJ_L4BRG_H */