#ifndef RES_K_SPKAI00_H
#define RES_K_SPKAI00_H

enum dRes_INDEX_K_SPKAI00 {
    /* BMDR */
    dRes_INDEX_K_SPKAI00_BMD_K_SPKAIDAN_00_e=0x5,
    dRes_INDEX_K_SPKAI00_BMD_K_SPKAIDAN_01_e=0x6,
    dRes_INDEX_K_SPKAI00_BMD_K_SPKAIDAN_01B_e=0x7,
    /* BTK  */
    dRes_INDEX_K_SPKAI00_BTK_K_SPKAIDAN_01_e=0xA,
    dRes_INDEX_K_SPKAI00_BTK_K_SPKAIDAN_01B_e=0xB,
    /* DZB  */
    dRes_INDEX_K_SPKAI00_DZB_K_SPKAIDAN_00_e=0xE,
    dRes_INDEX_K_SPKAI00_DZB_K_SPKAIDAN_01_e=0xF,
};

enum dRes_ID_K_SPKAI00 {
    /* BMDR */
    dRes_ID_K_SPKAI00_BMD_K_SPKAIDAN_00_e=0x5,
    dRes_ID_K_SPKAI00_BMD_K_SPKAIDAN_01_e=0x6,
    dRes_ID_K_SPKAI00_BMD_K_SPKAIDAN_01B_e=0x7,
    /* BTK  */
    dRes_ID_K_SPKAI00_BTK_K_SPKAIDAN_01_e=0xA,
    dRes_ID_K_SPKAI00_BTK_K_SPKAIDAN_01B_e=0xB,
    /* DZB  */
    dRes_ID_K_SPKAI00_DZB_K_SPKAIDAN_00_e=0xE,
    dRes_ID_K_SPKAI00_DZB_K_SPKAIDAN_01_e=0xF,
};

enum K_SPKAIDAN_00_JNT {
    K_SPKAIDAN_00_JNT_WORLD_ROOT_e=0x0,
};

enum K_SPKAIDAN_01_JNT {
    K_SPKAIDAN_01_JNT_WORLD_ROOT_e=0x0,
};

enum K_SPKAIDAN_01B_JNT {
    K_SPKAIDAN_01B_JNT_WORLD_ROOT_e=0x0,
};

#endif /* !RES_K_SPKAI00_H */