#ifndef RES_RACA_H
#define RES_RACA_H

enum dRes_INDEX_RACA {
    /* BCK  */
    dRes_INDEX_RACA_BCK_RACA_F_BITTERSMILE_e=0x6,
    dRes_INDEX_RACA_BCK_RACA_F_SMILE_e=0x7,
    dRes_INDEX_RACA_BCK_RACA_F_TALK_A_e=0x8,
    dRes_INDEX_RACA_BCK_RACA_F_TALK_B_e=0x9,
    dRes_INDEX_RACA_BCK_RACA_FH_BITTERSMILE_e=0xA,
    dRes_INDEX_RACA_BCK_RACA_FH_SMILE_e=0xB,
    dRes_INDEX_RACA_BCK_RACA_FH_TALK_B_e=0xC,
    dRes_INDEX_RACA_BCK_RACA_GIVEME_e=0xD,
    dRes_INDEX_RACA_BCK_RACA_HI_e=0xE,
    dRes_INDEX_RACA_BCK_RACA_HI_WAIT_e=0xF,
    dRes_INDEX_RACA_BCK_RACA_LISTEN_e=0x10,
    dRes_INDEX_RACA_BCK_RACA_LISTEN_WAIT_e=0x11,
    dRes_INDEX_RACA_BCK_RACA_STEP_e=0x12,
    dRes_INDEX_RACA_BCK_RACA_TALK_A_e=0x13,
    dRes_INDEX_RACA_BCK_RACA_TALK_B_e=0x14,
    dRes_INDEX_RACA_BCK_RACA_WAIT_A_e=0x15,
    dRes_INDEX_RACA_BCK_RACA_WALK_A_e=0x16,
    /* BMDR */
    dRes_INDEX_RACA_BMD_RACA_e=0x19,
    /* BTK  */
    dRes_INDEX_RACA_BTK_RACA_e=0x1C,
    dRes_INDEX_RACA_BTK_RACA_TALK_B_e=0x1D,
    /* BTP  */
    dRes_INDEX_RACA_BTP_RACA_e=0x20,
    dRes_INDEX_RACA_BTP_RACA_F_BITTERSMILE_e=0x21,
    dRes_INDEX_RACA_BTP_RACA_F_SMILE_e=0x22,
    dRes_INDEX_RACA_BTP_RACA_F_TALK_B_e=0x23,
    dRes_INDEX_RACA_BTP_RACA_FH_BITTERSMILE_e=0x24,
    dRes_INDEX_RACA_BTP_RACA_FH_SMILE_e=0x25,
    dRes_INDEX_RACA_BTP_RACA_FH_TALK_B_e=0x26,
};

enum dRes_ID_RACA {
    /* BCK  */
    dRes_ID_RACA_BCK_RACA_F_BITTERSMILE_e=0x6,
    dRes_ID_RACA_BCK_RACA_F_SMILE_e=0x7,
    dRes_ID_RACA_BCK_RACA_F_TALK_A_e=0x8,
    dRes_ID_RACA_BCK_RACA_F_TALK_B_e=0x9,
    dRes_ID_RACA_BCK_RACA_FH_BITTERSMILE_e=0xA,
    dRes_ID_RACA_BCK_RACA_FH_SMILE_e=0xB,
    dRes_ID_RACA_BCK_RACA_FH_TALK_B_e=0xC,
    dRes_ID_RACA_BCK_RACA_GIVEME_e=0xD,
    dRes_ID_RACA_BCK_RACA_HI_e=0xE,
    dRes_ID_RACA_BCK_RACA_HI_WAIT_e=0xF,
    dRes_ID_RACA_BCK_RACA_LISTEN_e=0x10,
    dRes_ID_RACA_BCK_RACA_LISTEN_WAIT_e=0x11,
    dRes_ID_RACA_BCK_RACA_STEP_e=0x12,
    dRes_ID_RACA_BCK_RACA_TALK_A_e=0x13,
    dRes_ID_RACA_BCK_RACA_TALK_B_e=0x14,
    dRes_ID_RACA_BCK_RACA_WAIT_A_e=0x15,
    dRes_ID_RACA_BCK_RACA_WALK_A_e=0x16,
    /* BMDR */
    dRes_ID_RACA_BMD_RACA_e=0x19,
    /* BTK  */
    dRes_ID_RACA_BTK_RACA_e=0x1C,
    dRes_ID_RACA_BTK_RACA_TALK_B_e=0x1D,
    /* BTP  */
    dRes_ID_RACA_BTP_RACA_e=0x20,
    dRes_ID_RACA_BTP_RACA_F_BITTERSMILE_e=0x21,
    dRes_ID_RACA_BTP_RACA_F_SMILE_e=0x22,
    dRes_ID_RACA_BTP_RACA_F_TALK_B_e=0x23,
    dRes_ID_RACA_BTP_RACA_FH_BITTERSMILE_e=0x24,
    dRes_ID_RACA_BTP_RACA_FH_SMILE_e=0x25,
    dRes_ID_RACA_BTP_RACA_FH_TALK_B_e=0x26,
};

enum RACA_JNT {
    RACA_JNT_CENTER_e=0x0,
    RACA_JNT_BACKBONE1_e=0x1,
    RACA_JNT_BACKBONE2_e=0x2,
    RACA_JNT_NECK_e=0x3,
    RACA_JNT_HEAD_e=0x4,
    RACA_JNT_CHIN_e=0x5,
    RACA_JNT_MAYU_L_e=0x6,
    RACA_JNT_MAYU_R_e=0x7,
    RACA_JNT_MOUTH_e=0x8,
    RACA_JNT_SHOULDERL_e=0x9,
    RACA_JNT_ARML1_e=0xA,
    RACA_JNT_ARML2_e=0xB,
    RACA_JNT_HANDL_e=0xC,
    RACA_JNT_FINGERL_e=0xD,
    RACA_JNT_THUMBL_e=0xE,
    RACA_JNT_SHOULDERR_e=0xF,
    RACA_JNT_ARMR1_e=0x10,
    RACA_JNT_ARMR2_e=0x11,
    RACA_JNT_HANDR_e=0x12,
    RACA_JNT_FINGERR_e=0x13,
    RACA_JNT_THUMBR_e=0x14,
    RACA_JNT_WAIST_e=0x15,
    RACA_JNT_LEGL1_e=0x16,
    RACA_JNT_LEGL2_e=0x17,
    RACA_JNT_FOOTL_e=0x18,
    RACA_JNT_LEGR1_e=0x19,
    RACA_JNT_LEGR2_e=0x1A,
    RACA_JNT_FOOTR_e=0x1B,
};

#endif /* !RES_RACA_H */