#ifndef RES_YELIA3_H
#define RES_YELIA3_H

enum dRes_INDEX_YELIA3 {
    /* BCK  */
    dRes_INDEX_YELIA3_BCK_YELIA_F_KAISOU_TALK_e=0x5,
    dRes_INDEX_YELIA3_BCK_YELIA_F_KAISOU_WAIT_A_e=0x6,
    dRes_INDEX_YELIA3_BCK_YELIA_F_KAISOU_WAIT_B_e=0x7,
    dRes_INDEX_YELIA3_BCK_YELIA_FH_KAISOU_TALK_e=0x8,
    dRes_INDEX_YELIA3_BCK_YELIA_KAISOU_TALK_e=0x9,
    dRes_INDEX_YELIA3_BCK_YELIA_KAISOU_WAIT_A_e=0xA,
    dRes_INDEX_YELIA3_BCK_YELIA_KAISOU_WAIT_B_e=0xB,
    /* BTK  */
    dRes_INDEX_YELIA3_BTK_YELIA_KAISOU_TALK_e=0xE,
    dRes_INDEX_YELIA3_BTK_YELIA_KAISOU_WAIT_A_e=0xF,
    dRes_INDEX_YELIA3_BTK_YELIA_KAISOU_WAIT_B_e=0x10,
    /* BTP  */
    dRes_INDEX_YELIA3_BTP_YELIA_F_KAISOU_TALK_e=0x13,
    dRes_INDEX_YELIA3_BTP_YELIA_F_KAISOU_WAIT_A_e=0x14,
};

enum dRes_ID_YELIA3 {
    /* BCK  */
    dRes_ID_YELIA3_BCK_YELIA_F_KAISOU_TALK_e=0x5,
    dRes_ID_YELIA3_BCK_YELIA_F_KAISOU_WAIT_A_e=0x6,
    dRes_ID_YELIA3_BCK_YELIA_F_KAISOU_WAIT_B_e=0x7,
    dRes_ID_YELIA3_BCK_YELIA_FH_KAISOU_TALK_e=0x8,
    dRes_ID_YELIA3_BCK_YELIA_KAISOU_TALK_e=0x9,
    dRes_ID_YELIA3_BCK_YELIA_KAISOU_WAIT_A_e=0xA,
    dRes_ID_YELIA3_BCK_YELIA_KAISOU_WAIT_B_e=0xB,
    /* BTK  */
    dRes_ID_YELIA3_BTK_YELIA_KAISOU_TALK_e=0xE,
    dRes_ID_YELIA3_BTK_YELIA_KAISOU_WAIT_A_e=0xF,
    dRes_ID_YELIA3_BTK_YELIA_KAISOU_WAIT_B_e=0x10,
    /* BTP  */
    dRes_ID_YELIA3_BTP_YELIA_F_KAISOU_TALK_e=0x13,
    dRes_ID_YELIA3_BTP_YELIA_F_KAISOU_WAIT_A_e=0x14,
};

#endif /* !RES_YELIA3_H */