#ifndef RES_YELIA2_H
#define RES_YELIA2_H

enum dRes_INDEX_YELIA2 {
    /* BMDR */
    dRes_INDEX_YELIA2_BMD_YELB_e=0x3,
};

enum dRes_ID_YELIA2 {
    /* BMDR */
    dRes_ID_YELIA2_BMD_YELB_e=0x3,
};

enum YELB_JNT {
    YELB_JNT_CENTER_e=0x0,
    YELB_JNT_BACKBONE1_e=0x1,
    YELB_JNT_BACKBONE2_e=0x2,
    YELB_JNT_NECK_e=0x3,
    YELB_JNT_HEAD_e=0x4,
    YELB_JNT_HAIR1_e=0x5,
    YELB_JNT_JAW_e=0x6,
    YELB_JNT_MAYUL_e=0x7,
    YELB_JNT_MAYUR_e=0x8,
    YELB_JNT_MOUTH_e=0x9,
    YELB_JNT_SHOULDERL_e=0xA,
    YELB_JNT_ARML1_e=0xB,
    YELB_JNT_ARML2_e=0xC,
    YELB_JNT_HANDL_e=0xD,
    YELB_JNT_FINGERL1_e=0xE,
    YELB_JNT_THUMBL_e=0xF,
    YELB_JNT_SHOULDERR_e=0x10,
    YELB_JNT_ARMR1_e=0x11,
    YELB_JNT_ARMR2_e=0x12,
    YELB_JNT_HANDR_e=0x13,
    YELB_JNT_FINGERR1_e=0x14,
    YELB_JNT_THUMBR_e=0x15,
    YELB_JNT_WAIST_e=0x16,
    YELB_JNT_LEGL1_e=0x17,
    YELB_JNT_LEGL2_e=0x18,
    YELB_JNT_FOOTL_e=0x19,
    YELB_JNT_LEGR1_e=0x1A,
    YELB_JNT_LEGR2_e=0x1B,
    YELB_JNT_FOOTR_e=0x1C,
    YELB_JNT_SKIRTBL_e=0x1D,
    YELB_JNT_SKIRTBR_e=0x1E,
    YELB_JNT_SKIRTFL_e=0x1F,
    YELB_JNT_SKIRTFR_e=0x20,
};

#endif /* !RES_YELIA2_H */