#ifndef RES_YKW2_H
#define RES_YKW2_H

enum dRes_INDEX_YKW2 {
    /* BCK  */
    dRes_INDEX_YKW2_BCK_YKW_ASK_e=0x6,
    dRes_INDEX_YKW2_BCK_YKW_DANCE_e=0x7,
    dRes_INDEX_YKW2_BCK_YKW_DENY_e=0x8,
    dRes_INDEX_YKW2_BCK_YKW_F_FUN_e=0x9,
    dRes_INDEX_YKW2_BCK_YKW_F_SAD_e=0xA,
    dRes_INDEX_YKW2_BCK_YKW_FALL_e=0xB,
    dRes_INDEX_YKW2_BCK_YKW_FALLWAIT_e=0xC,
    dRes_INDEX_YKW2_BCK_YKW_FH_FUN_e=0xD,
    dRes_INDEX_YKW2_BCK_YKW_FUNWAIT_e=0xE,
    dRes_INDEX_YKW2_BCK_YKW_JUMP_e=0xF,
    dRes_INDEX_YKW2_BCK_YKW_SB_GOAL_e=0x10,
    dRes_INDEX_YKW2_BCK_YKW_SB_GOAL_WAIT_e=0x11,
    dRes_INDEX_YKW2_BCK_YKW_SB_JUMP_A_e=0x12,
    dRes_INDEX_YKW2_BCK_YKW_SB_JUMP_B_e=0x13,
    dRes_INDEX_YKW2_BCK_YKW_SB_JUMP_C_e=0x14,
    dRes_INDEX_YKW2_BCK_YKW_SB_SPIN_e=0x15,
    dRes_INDEX_YKW2_BCK_YKW_SB_START_e=0x16,
    dRes_INDEX_YKW2_BCK_YKW_SB_TURNL_e=0x17,
    dRes_INDEX_YKW2_BCK_YKW_SB_TURNR_e=0x18,
    dRes_INDEX_YKW2_BCK_YKW_SB_WAIT_e=0x19,
    dRes_INDEX_YKW2_BCK_YKW_SECRET_e=0x1A,
    /* BTK  */
    dRes_INDEX_YKW2_BTK_YKW_SECRET_e=0x1D,
    /* BTP  */
    dRes_INDEX_YKW2_BTP_YKW_F_FUN_e=0x20,
    dRes_INDEX_YKW2_BTP_YKW_F_SAD_e=0x21,
    /* EVT  */
    dRes_INDEX_YKW2_DAT_EVENT_LIST_e=0x24,
};

enum dRes_ID_YKW2 {
    /* BCK  */
    dRes_ID_YKW2_BCK_YKW_ASK_e=0x6,
    dRes_ID_YKW2_BCK_YKW_DANCE_e=0x7,
    dRes_ID_YKW2_BCK_YKW_DENY_e=0x8,
    dRes_ID_YKW2_BCK_YKW_F_FUN_e=0x9,
    dRes_ID_YKW2_BCK_YKW_F_SAD_e=0xA,
    dRes_ID_YKW2_BCK_YKW_FALL_e=0xB,
    dRes_ID_YKW2_BCK_YKW_FALLWAIT_e=0xC,
    dRes_ID_YKW2_BCK_YKW_FH_FUN_e=0xD,
    dRes_ID_YKW2_BCK_YKW_FUNWAIT_e=0xE,
    dRes_ID_YKW2_BCK_YKW_JUMP_e=0xF,
    dRes_ID_YKW2_BCK_YKW_SB_GOAL_e=0x10,
    dRes_ID_YKW2_BCK_YKW_SB_GOAL_WAIT_e=0x11,
    dRes_ID_YKW2_BCK_YKW_SB_JUMP_A_e=0x12,
    dRes_ID_YKW2_BCK_YKW_SB_JUMP_B_e=0x13,
    dRes_ID_YKW2_BCK_YKW_SB_JUMP_C_e=0x14,
    dRes_ID_YKW2_BCK_YKW_SB_SPIN_e=0x15,
    dRes_ID_YKW2_BCK_YKW_SB_START_e=0x16,
    dRes_ID_YKW2_BCK_YKW_SB_TURNL_e=0x17,
    dRes_ID_YKW2_BCK_YKW_SB_TURNR_e=0x18,
    dRes_ID_YKW2_BCK_YKW_SB_WAIT_e=0x19,
    dRes_ID_YKW2_BCK_YKW_SECRET_e=0x1A,
    /* BTK  */
    dRes_ID_YKW2_BTK_YKW_SECRET_e=0x1D,
    /* BTP  */
    dRes_ID_YKW2_BTP_YKW_F_FUN_e=0x20,
    dRes_ID_YKW2_BTP_YKW_F_SAD_e=0x21,
    /* EVT  */
    dRes_ID_YKW2_DAT_EVENT_LIST_e=0x24,
};

#endif /* !RES_YKW2_H */