#ifndef RES_ZELRF_H
#define RES_ZELRF_H

enum dRes_INDEX_ZELRF {
    /* BCK  */
    dRes_INDEX_ZELRF_BCK_ZELRF_F_TALK_A_e=0x6,
    dRes_INDEX_ZELRF_BCK_ZELRF_WAIT_A_e=0x7,
    /* BMDR */
    dRes_INDEX_ZELRF_BMD_ZELRF_e=0xA,
    /* BTK  */
    dRes_INDEX_ZELRF_BTK_ZELRF_e=0xD,
    /* BTP  */
    dRes_INDEX_ZELRF_BTP_ZELRF_e=0x10,
};

enum dRes_ID_ZELRF {
    /* BCK  */
    dRes_ID_ZELRF_BCK_ZELRF_F_TALK_A_e=0x6,
    dRes_ID_ZELRF_BCK_ZELRF_WAIT_A_e=0x7,
    /* BMDR */
    dRes_ID_ZELRF_BMD_ZELRF_e=0xA,
    /* BTK  */
    dRes_ID_ZELRF_BTK_ZELRF_e=0xD,
    /* BTP  */
    dRes_ID_ZELRF_BTP_ZELRF_e=0x10,
};

enum ZELRF_JNT {
    ZELRF_JNT_CENTER_e=0x0,
    ZELRF_JNT_BACKBONE1_e=0x1,
    ZELRF_JNT_BACKBONE2_e=0x2,
    ZELRF_JNT_HEAD_e=0x3,
    ZELRF_JNT_JAW_e=0x4,
    ZELRF_JNT_JOINT2_e=0x5,
    ZELRF_JNT_JOINT4_e=0x6,
    ZELRF_JNT_MANT_01_e=0x7,
    ZELRF_JNT_JOINT1_e=0x8,
    ZELRF_JNT_JOINT3_e=0x9,
    ZELRF_JNT_JOINT5_e=0xA,
    ZELRF_JNT_MAYUL_e=0xB,
    ZELRF_JNT_MAYUR_e=0xC,
    ZELRF_JNT_MOUTH_e=0xD,
    ZELRF_JNT_SHOULDERL_e=0xE,
    ZELRF_JNT_ARML1_e=0xF,
    ZELRF_JNT_ARML2_e=0x10,
    ZELRF_JNT_HANDL_e=0x11,
    ZELRF_JNT_FINGERL1_e=0x12,
    ZELRF_JNT_FINGERL2_e=0x13,
    ZELRF_JNT_THAMBL_e=0x14,
    ZELRF_JNT_SHOULDERR_e=0x15,
    ZELRF_JNT_ARMR1_e=0x16,
    ZELRF_JNT_ARMR2_e=0x17,
    ZELRF_JNT_HANDR_e=0x18,
    ZELRF_JNT_FINGERR1_e=0x19,
    ZELRF_JNT_FINGERR2_e=0x1A,
    ZELRF_JNT_THAMBR_e=0x1B,
    ZELRF_JNT_WAIST_e=0x1C,
};

#endif /* !RES_ZELRF_H */