#ifndef RES_BESU_H
#define RES_BESU_H

enum dRes_INDEX_BESU {
    /* BMDR */
    dRes_INDEX_BESU_BMD_BESU_e=0x3,
};

enum dRes_ID_BESU {
    /* BMDR */
    dRes_ID_BESU_BMD_BESU_e=0x3,
};

enum BESU_JNT {
    BESU_JNT_CENTER_e=0x0,
    BESU_JNT_BACKBONE1_e=0x1,
    BESU_JNT_BACKBONE2_e=0x2,
    BESU_JNT_NECK_e=0x3,
    BESU_JNT_HEAD_e=0x4,
    BESU_JNT_CHIN_e=0x5,
    BESU_JNT_MOUTH_e=0x6,
    BESU_JNT_SHOULDERL_e=0x7,
    BESU_JNT_ARML1_e=0x8,
    BESU_JNT_ARML2_e=0x9,
    BESU_JNT_HANDL_e=0xA,
    BESU_JNT_SHOULDERR_e=0xB,
    BESU_JNT_ARMR1_e=0xC,
    BESU_JNT_ARMR2_e=0xD,
    BESU_JNT_HANDR_e=0xE,
    BESU_JNT_WAIST_e=0xF,
    BESU_JNT_LEGL1_e=0x10,
    BESU_JNT_LEGL2_e=0x11,
    BESU_JNT_FOOTL_e=0x12,
    BESU_JNT_LEGR1_e=0x13,
    BESU_JNT_LEGR2_e=0x14,
    BESU_JNT_FOOTR_e=0x15,
};

#endif /* !RES_BESU_H */