#ifndef RES_E_FM_H
#define RES_E_FM_H

enum dRes_INDEX_E_FM {
    /* BCK  */
    dRes_INDEX_E_FM_BCK_EF_FMATTACK_A_e=0x7,
    dRes_INDEX_E_FM_BCK_EF_FMATTACK_B_e=0x8,
    dRes_INDEX_E_FM_BCK_FM_ANIMAL_e=0x9,
    dRes_INDEX_E_FM_BCK_FM_ANIMAL02_e=0xA,
    dRes_INDEX_E_FM_BCK_FM_ATTACK_e=0xB,
    dRes_INDEX_E_FM_BCK_FM_ATTACK02_e=0xC,
    dRes_INDEX_E_FM_BCK_FM_BREAKCHAINL_e=0xD,
    dRes_INDEX_E_FM_BCK_FM_BREAKCHAINR_e=0xE,
    dRes_INDEX_E_FM_BCK_FM_CHANCE_e=0xF,
    dRes_INDEX_E_FM_BCK_FM_CHANCEDAMAGE_e=0x10,
    dRes_INDEX_E_FM_BCK_FM_DAMAGEWALK_e=0x11,
    dRes_INDEX_E_FM_BCK_FM_DAMAGE_L_e=0x12,
    dRes_INDEX_E_FM_BCK_FM_DAMAGE_R_e=0x13,
    dRes_INDEX_E_FM_BCK_FM_DEAD_e=0x14,
    dRes_INDEX_E_FM_BCK_FM_DEMOEND01_e=0x15,
    dRes_INDEX_E_FM_BCK_FM_DEMOEND02_e=0x16,
    dRes_INDEX_E_FM_BCK_FM_DEMOEND03_e=0x17,
    dRes_INDEX_E_FM_BCK_FM_DOWN_e=0x18,
    dRes_INDEX_E_FM_BCK_FM_DOWN02_e=0x19,
    dRes_INDEX_E_FM_BCK_FM_DOWNDAMAGE_e=0x1A,
    dRes_INDEX_E_FM_BCK_FM_DOWNFR_e=0x1B,
    dRes_INDEX_E_FM_BCK_FM_DOWNWAIT_e=0x1C,
    dRes_INDEX_E_FM_BCK_FM_HANGWAIT_e=0x1D,
    dRes_INDEX_E_FM_BCK_FM_KYORO2_e=0x1E,
    dRes_INDEX_E_FM_BCK_FM_OPDEMO_e=0x1F,
    dRes_INDEX_E_FM_BCK_FM_UP_e=0x20,
    dRes_INDEX_E_FM_BCK_FM_UP02_e=0x21,
    dRes_INDEX_E_FM_BCK_FM_WAIT01_e=0x22,
    dRes_INDEX_E_FM_BCK_FM_WALK_e=0x23,
    dRes_INDEX_E_FM_BCK_FM_WALK02_e=0x24,
    /* BMDE */
    dRes_INDEX_E_FM_BMD_FM_CORE_e=0x27,
    /* BMDR */
    dRes_INDEX_E_FM_BMD_EF_FMATTACK_A_e=0x2A,
    dRes_INDEX_E_FM_BMD_EF_FMATTACK_B_e=0x2B,
    dRes_INDEX_E_FM_BMD_FM_e=0x2C,
    dRes_INDEX_E_FM_BMD_HANDLE_e=0x2D,
    dRes_INDEX_E_FM_BMD_KUSARI_e=0x2E,
    /* BRK  */
    dRes_INDEX_E_FM_BRK_CORE_LIGHTON_e=0x31,
    dRes_INDEX_E_FM_BRK_EF_FMATTACK_B_e=0x32,
    dRes_INDEX_E_FM_BRK_FM_e=0x33,
    dRes_INDEX_E_FM_BRK_FM_ANIMAL02_e=0x34,
    dRes_INDEX_E_FM_BRK_FM_ATTACK_e=0x35,
    dRes_INDEX_E_FM_BRK_FM_DEMOEND01_e=0x36,
    dRes_INDEX_E_FM_BRK_FM_DEMOEND02_e=0x37,
    dRes_INDEX_E_FM_BRK_FM_DEMOEND03_e=0x38,
    dRes_INDEX_E_FM_BRK_FM_HANGWAIT_e=0x39,
    dRes_INDEX_E_FM_BRK_FM_OPDEMO_e=0x3A,
    dRes_INDEX_E_FM_BRK_FM_PUTOUT_e=0x3B,
    dRes_INDEX_E_FM_BRK_FM_PUTOUTWAIT_e=0x3C,
    /* BTK  */
    dRes_INDEX_E_FM_BTK_CORE_BEAT_e=0x3F,
    dRes_INDEX_E_FM_BTK_EF_FMATTACK_A_e=0x40,
    dRes_INDEX_E_FM_BTK_EF_FMATTACK_B_e=0x41,
    dRes_INDEX_E_FM_BTK_FM_e=0x42,
    dRes_INDEX_E_FM_BTK_FM_ANIMAL02_e=0x43,
    dRes_INDEX_E_FM_BTK_FM_ATTACK_e=0x44,
    dRes_INDEX_E_FM_BTK_FM_DEMOEND01_e=0x45,
    dRes_INDEX_E_FM_BTK_FM_DEMOEND02_e=0x46,
    dRes_INDEX_E_FM_BTK_FM_HANGWAIT_e=0x47,
    dRes_INDEX_E_FM_BTK_FM_OPDEMO_e=0x48,
    dRes_INDEX_E_FM_BTK_FM_PUTOUT_e=0x49,
    dRes_INDEX_E_FM_BTK_FM_PUTOUTWAIT_e=0x4A,
};

enum dRes_ID_E_FM {
    /* BCK  */
    dRes_ID_E_FM_BCK_EF_FMATTACK_A_e=0x7,
    dRes_ID_E_FM_BCK_EF_FMATTACK_B_e=0x8,
    dRes_ID_E_FM_BCK_FM_ANIMAL_e=0x9,
    dRes_ID_E_FM_BCK_FM_ANIMAL02_e=0xA,
    dRes_ID_E_FM_BCK_FM_ATTACK_e=0xB,
    dRes_ID_E_FM_BCK_FM_ATTACK02_e=0xC,
    dRes_ID_E_FM_BCK_FM_BREAKCHAINL_e=0xD,
    dRes_ID_E_FM_BCK_FM_BREAKCHAINR_e=0xE,
    dRes_ID_E_FM_BCK_FM_CHANCE_e=0xF,
    dRes_ID_E_FM_BCK_FM_CHANCEDAMAGE_e=0x10,
    dRes_ID_E_FM_BCK_FM_DAMAGEWALK_e=0x11,
    dRes_ID_E_FM_BCK_FM_DAMAGE_L_e=0x12,
    dRes_ID_E_FM_BCK_FM_DAMAGE_R_e=0x13,
    dRes_ID_E_FM_BCK_FM_DEAD_e=0x14,
    dRes_ID_E_FM_BCK_FM_DEMOEND01_e=0x15,
    dRes_ID_E_FM_BCK_FM_DEMOEND02_e=0x16,
    dRes_ID_E_FM_BCK_FM_DEMOEND03_e=0x17,
    dRes_ID_E_FM_BCK_FM_DOWN_e=0x18,
    dRes_ID_E_FM_BCK_FM_DOWN02_e=0x19,
    dRes_ID_E_FM_BCK_FM_DOWNDAMAGE_e=0x1A,
    dRes_ID_E_FM_BCK_FM_DOWNFR_e=0x1B,
    dRes_ID_E_FM_BCK_FM_DOWNWAIT_e=0x1C,
    dRes_ID_E_FM_BCK_FM_HANGWAIT_e=0x1D,
    dRes_ID_E_FM_BCK_FM_KYORO2_e=0x1E,
    dRes_ID_E_FM_BCK_FM_OPDEMO_e=0x1F,
    dRes_ID_E_FM_BCK_FM_UP_e=0x20,
    dRes_ID_E_FM_BCK_FM_UP02_e=0x21,
    dRes_ID_E_FM_BCK_FM_WAIT01_e=0x22,
    dRes_ID_E_FM_BCK_FM_WALK_e=0x23,
    dRes_ID_E_FM_BCK_FM_WALK02_e=0x24,
    /* BMDE */
    dRes_ID_E_FM_BMD_FM_CORE_e=0x27,
    /* BMDR */
    dRes_ID_E_FM_BMD_EF_FMATTACK_A_e=0x2A,
    dRes_ID_E_FM_BMD_EF_FMATTACK_B_e=0x2B,
    dRes_ID_E_FM_BMD_FM_e=0x2C,
    dRes_ID_E_FM_BMD_HANDLE_e=0x2D,
    dRes_ID_E_FM_BMD_KUSARI_e=0x2E,
    /* BRK  */
    dRes_ID_E_FM_BRK_CORE_LIGHTON_e=0x31,
    dRes_ID_E_FM_BRK_EF_FMATTACK_B_e=0x32,
    dRes_ID_E_FM_BRK_FM_e=0x33,
    dRes_ID_E_FM_BRK_FM_ANIMAL02_e=0x34,
    dRes_ID_E_FM_BRK_FM_ATTACK_e=0x35,
    dRes_ID_E_FM_BRK_FM_DEMOEND01_e=0x36,
    dRes_ID_E_FM_BRK_FM_DEMOEND02_e=0x37,
    dRes_ID_E_FM_BRK_FM_DEMOEND03_e=0x38,
    dRes_ID_E_FM_BRK_FM_HANGWAIT_e=0x39,
    dRes_ID_E_FM_BRK_FM_OPDEMO_e=0x3A,
    dRes_ID_E_FM_BRK_FM_PUTOUT_e=0x3B,
    dRes_ID_E_FM_BRK_FM_PUTOUTWAIT_e=0x3C,
    /* BTK  */
    dRes_ID_E_FM_BTK_CORE_BEAT_e=0x3F,
    dRes_ID_E_FM_BTK_EF_FMATTACK_A_e=0x40,
    dRes_ID_E_FM_BTK_EF_FMATTACK_B_e=0x41,
    dRes_ID_E_FM_BTK_FM_e=0x42,
    dRes_ID_E_FM_BTK_FM_ANIMAL02_e=0x43,
    dRes_ID_E_FM_BTK_FM_ATTACK_e=0x44,
    dRes_ID_E_FM_BTK_FM_DEMOEND01_e=0x45,
    dRes_ID_E_FM_BTK_FM_DEMOEND02_e=0x46,
    dRes_ID_E_FM_BTK_FM_HANGWAIT_e=0x47,
    dRes_ID_E_FM_BTK_FM_OPDEMO_e=0x48,
    dRes_ID_E_FM_BTK_FM_PUTOUT_e=0x49,
    dRes_ID_E_FM_BTK_FM_PUTOUTWAIT_e=0x4A,
};

enum FM_CORE_JNT {
    FM_CORE_JNT_CORE_MODEL_e=0x0,
};

enum EF_FMATTACK_A_JNT {
    EF_FMATTACK_A_JNT_J_06_e=0x0,
};

enum EF_FMATTACK_B_JNT {
    EF_FMATTACK_B_JNT_ROOT_e=0x0,
    EF_FMATTACK_B_JNT_J_01_e=0x1,
    EF_FMATTACK_B_JNT_J_02_e=0x2,
    EF_FMATTACK_B_JNT_J_03_e=0x3,
    EF_FMATTACK_B_JNT_J_04_e=0x4,
    EF_FMATTACK_B_JNT_J_05_e=0x5,
};

enum FM_JNT {
    FM_JNT_WORLD_ROOT_e=0x0,
    FM_JNT_BACKBONE_e=0x1,
    FM_JNT_NECK_e=0x2,
    FM_JNT_HEAD_e=0x3,
    FM_JNT_JAW_e=0x4,
    FM_JNT_SHOULDERL_e=0x5,
    FM_JNT_ARML1_e=0x6,
    FM_JNT_ARML2_e=0x7,
    FM_JNT_HANDL_e=0x8,
    FM_JNT_FINGERL1_e=0x9,
    FM_JNT_FINGERL2_e=0xA,
    FM_JNT_FINGERL3_e=0xB,
    FM_JNT_SHOULDERR_e=0xC,
    FM_JNT_ARMR1_e=0xD,
    FM_JNT_ARMR2_e=0xE,
    FM_JNT_HANDR_e=0xF,
    FM_JNT_FINGERR1_e=0x10,
    FM_JNT_FINGERR2_e=0x11,
    FM_JNT_FINGERR3_e=0x12,
    FM_JNT_WAIST_e=0x13,
    FM_JNT_LEGL1_e=0x14,
    FM_JNT_LEGL2_e=0x15,
    FM_JNT_FOOTL_e=0x16,
    FM_JNT_LEGR1_e=0x17,
    FM_JNT_LEGR2_e=0x18,
    FM_JNT_FOOTR_e=0x19,
};

enum HANDLE_JNT {
    HANDLE_JNT_HANDLE_MODEL_e=0x0,
};

enum KUSARI_JNT {
    KUSARI_JNT_KUSARI_MODEL_e=0x0,
};

#endif /* !RES_E_FM_H */