#ifndef RES_GRA_SPA_H
#define RES_GRA_SPA_H

enum dRes_INDEX_GRA_SPA {
    /* BCK  */
    dRes_INDEX_GRA_SPA_BCK_GRA_F_SPA_RELAX_e=0x5,
    dRes_INDEX_GRA_SPA_BCK_GRA_F_SPA_RELAX_B_e=0x6,
    dRes_INDEX_GRA_SPA_BCK_GRA_F_SPA_SIT_e=0x7,
    dRes_INDEX_GRA_SPA_BCK_GRA_F_SPA_SIT_B_e=0x8,
    dRes_INDEX_GRA_SPA_BCK_GRA_SPA_RELAX_e=0x9,
    dRes_INDEX_GRA_SPA_BCK_GRA_SPA_RELAX_B_e=0xA,
    dRes_INDEX_GRA_SPA_BCK_GRA_SPA_SIT_e=0xB,
    dRes_INDEX_GRA_SPA_BCK_GRA_SPA_SIT_B_e=0xC,
    /* BTP  */
    dRes_INDEX_GRA_SPA_BTP_GRA_SPA_RELAX_e=0xF,
    dRes_INDEX_GRA_SPA_BTP_GRA_SPA_RELAX_B_e=0x10,
    dRes_INDEX_GRA_SPA_BTP_GRA_SPA_SIT_e=0x11,
    /* EVT  */
    dRes_INDEX_GRA_SPA_DAT_EVENT_LIST_e=0x14,
};

enum dRes_ID_GRA_SPA {
    /* BCK  */
    dRes_ID_GRA_SPA_BCK_GRA_F_SPA_RELAX_e=0x5,
    dRes_ID_GRA_SPA_BCK_GRA_F_SPA_RELAX_B_e=0x6,
    dRes_ID_GRA_SPA_BCK_GRA_F_SPA_SIT_e=0x7,
    dRes_ID_GRA_SPA_BCK_GRA_F_SPA_SIT_B_e=0x8,
    dRes_ID_GRA_SPA_BCK_GRA_SPA_RELAX_e=0x9,
    dRes_ID_GRA_SPA_BCK_GRA_SPA_RELAX_B_e=0xA,
    dRes_ID_GRA_SPA_BCK_GRA_SPA_SIT_e=0xB,
    dRes_ID_GRA_SPA_BCK_GRA_SPA_SIT_B_e=0xC,
    /* BTP  */
    dRes_ID_GRA_SPA_BTP_GRA_SPA_RELAX_e=0xF,
    dRes_ID_GRA_SPA_BTP_GRA_SPA_RELAX_B_e=0x10,
    dRes_ID_GRA_SPA_BTP_GRA_SPA_SIT_e=0x11,
    /* EVT  */
    dRes_ID_GRA_SPA_DAT_EVENT_LIST_e=0x14,
};

#endif /* !RES_GRA_SPA_H */