#ifndef RES_OBJ_BOARD_H
#define RES_OBJ_BOARD_H

enum dRes_INDEX_OBJ_BOARD {
    /* DZB  */
    dRes_INDEX_OBJ_BOARD_DZB_CLEARB00_e=0x3,
    dRes_INDEX_OBJ_BOARD_DZB_CLEARB01_e=0x4,
    dRes_INDEX_OBJ_BOARD_DZB_CLEARB02_e=0x5,
    dRes_INDEX_OBJ_BOARD_DZB_CLEARB03_e=0x6,
    dRes_INDEX_OBJ_BOARD_DZB_CLEARB04_e=0x7,
};

enum dRes_ID_OBJ_BOARD {
    /* DZB  */
    dRes_ID_OBJ_BOARD_DZB_CLEARB00_e=0x3,
    dRes_ID_OBJ_BOARD_DZB_CLEARB01_e=0x4,
    dRes_ID_OBJ_BOARD_DZB_CLEARB02_e=0x5,
    dRes_ID_OBJ_BOARD_DZB_CLEARB03_e=0x6,
    dRes_ID_OBJ_BOARD_DZB_CLEARB04_e=0x7,
};

#endif /* !RES_OBJ_BOARD_H */