#ifndef RES_PRAYER_H
#define RES_PRAYER_H

enum dRes_INDEX_PRAYER {
    /* BCK  */
    dRes_INDEX_PRAYER_BCK_W_PRAY_e=0x5,
    dRes_INDEX_PRAYER_BCK_W_PRAY_TALK_e=0x6,
    /* BMDR */
    dRes_INDEX_PRAYER_BMD_PRAYER_e=0x9,
    /* EVT  */
    dRes_INDEX_PRAYER_DAT_EVENT_LIST_e=0xC,
};

enum dRes_ID_PRAYER {
    /* BCK  */
    dRes_ID_PRAYER_BCK_W_PRAY_e=0x5,
    dRes_ID_PRAYER_BCK_W_PRAY_TALK_e=0x6,
    /* BMDR */
    dRes_ID_PRAYER_BMD_PRAYER_e=0x9,
    /* EVT  */
    dRes_ID_PRAYER_DAT_EVENT_LIST_e=0xC,
};

enum PRAYER_JNT {
    PRAYER_JNT_CENTER_e=0x0,
    PRAYER_JNT_BACKBONE_e=0x1,
    PRAYER_JNT_NECK_e=0x2,
    PRAYER_JNT_HEAD_e=0x3,
    PRAYER_JNT_SHOULDERL_e=0x4,
    PRAYER_JNT_ARML1_e=0x5,
    PRAYER_JNT_ARML2_e=0x6,
    PRAYER_JNT_HANDL_e=0x7,
    PRAYER_JNT_SHOULDERR_e=0x8,
    PRAYER_JNT_ARMR1_e=0x9,
    PRAYER_JNT_ARMR2_e=0xA,
    PRAYER_JNT_HANDR_e=0xB,
    PRAYER_JNT_WAIST_e=0xC,
    PRAYER_JNT_LEGL1_e=0xD,
    PRAYER_JNT_LEGL2_e=0xE,
    PRAYER_JNT_FOOTL_e=0xF,
    PRAYER_JNT_SKIRTL_e=0x10,
    PRAYER_JNT_LEGR1_e=0x11,
    PRAYER_JNT_LEGR2_e=0x12,
    PRAYER_JNT_FOOTR_e=0x13,
    PRAYER_JNT_SKIRTR_e=0x14,
};

#endif /* !RES_PRAYER_H */