#ifndef RES_L6TOGETP_H
#define RES_L6TOGETP_H

enum dRes_INDEX_L6TOGETP {
    /* BMDR */
    dRes_INDEX_L6TOGETP_BMD_LV6_OBJ_TOGETRAP_e=0x4,
    /* DZB  */
    dRes_INDEX_L6TOGETP_DZB_LV6_OBJ_TOGETRAP_e=0x7,
};

enum dRes_ID_L6TOGETP {
    /* BMDR */
    dRes_ID_L6TOGETP_BMD_LV6_OBJ_TOGETRAP_e=0x4,
    /* DZB  */
    dRes_ID_L6TOGETP_DZB_LV6_OBJ_TOGETRAP_e=0x7,
};

enum LV6_OBJ_TOGETRAP_JNT {
    LV6_OBJ_TOGETRAP_JNT_WORLD_ROOT_e=0x0,
};

#endif /* !RES_L6TOGETP_H */