#ifndef RES_MOIR_H
#define RES_MOIR_H

enum dRes_INDEX_MOIR {
    /* BCK  */
    dRes_INDEX_MOIR_BCK_MOIR_F_HOLD_S_e=0x6,
    dRes_INDEX_MOIR_BCK_MOIR_F_TALK_A_e=0x7,
    dRes_INDEX_MOIR_BCK_MOIR_FH_HOLD_S_e=0x8,
    dRes_INDEX_MOIR_BCK_MOIR_FH_SERIOUS_e=0x9,
    dRes_INDEX_MOIR_BCK_MOIR_STEP_e=0xA,
    dRes_INDEX_MOIR_BCK_MOIR_TALK_A_e=0xB,
    dRes_INDEX_MOIR_BCK_MOIR_WAIT_A_e=0xC,
    /* BMDR */
    dRes_INDEX_MOIR_BMD_MOIR_e=0xF,
    dRes_INDEX_MOIR_BMD_MOIR_HEADGEAR_e=0x10,
    /* BTK  */
    dRes_INDEX_MOIR_BTK_MOIR_e=0x13,
    /* BTP  */
    dRes_INDEX_MOIR_BTP_MOIR_e=0x16,
    dRes_INDEX_MOIR_BTP_MOIR_FH_SERIOUS_e=0x17,
};

enum dRes_ID_MOIR {
    /* BCK  */
    dRes_ID_MOIR_BCK_MOIR_F_HOLD_S_e=0x6,
    dRes_ID_MOIR_BCK_MOIR_F_TALK_A_e=0x7,
    dRes_ID_MOIR_BCK_MOIR_FH_HOLD_S_e=0x8,
    dRes_ID_MOIR_BCK_MOIR_FH_SERIOUS_e=0x9,
    dRes_ID_MOIR_BCK_MOIR_STEP_e=0xA,
    dRes_ID_MOIR_BCK_MOIR_TALK_A_e=0xB,
    dRes_ID_MOIR_BCK_MOIR_WAIT_A_e=0xC,
    /* BMDR */
    dRes_ID_MOIR_BMD_MOIR_e=0xF,
    dRes_ID_MOIR_BMD_MOIR_HEADGEAR_e=0x10,
    /* BTK  */
    dRes_ID_MOIR_BTK_MOIR_e=0x13,
    /* BTP  */
    dRes_ID_MOIR_BTP_MOIR_e=0x16,
    dRes_ID_MOIR_BTP_MOIR_FH_SERIOUS_e=0x17,
};

enum MOIR_JNT {
    MOIR_JNT_CENTER_e=0x0,
    MOIR_JNT_BACKBONE1_e=0x1,
    MOIR_JNT_BACKBONE2_e=0x2,
    MOIR_JNT_NECK_e=0x3,
    MOIR_JNT_HEAD_e=0x4,
    MOIR_JNT_CHIN_e=0x5,
    MOIR_JNT_MAYU_L_e=0x6,
    MOIR_JNT_MAYU_R_e=0x7,
    MOIR_JNT_MOUTH_e=0x8,
    MOIR_JNT_SHOULDERL_e=0x9,
    MOIR_JNT_ARML1_e=0xA,
    MOIR_JNT_ARML2_e=0xB,
    MOIR_JNT_HANDL_e=0xC,
    MOIR_JNT_FINGERL_e=0xD,
    MOIR_JNT_SHOULDERR_e=0xE,
    MOIR_JNT_ARMR1_e=0xF,
    MOIR_JNT_ARMR2_e=0x10,
    MOIR_JNT_HANDR_e=0x11,
    MOIR_JNT_FINGERR_e=0x12,
    MOIR_JNT_WAIST_e=0x13,
    MOIR_JNT_LEGL1_e=0x14,
    MOIR_JNT_LEGL2_e=0x15,
    MOIR_JNT_FOOTL_e=0x16,
    MOIR_JNT_LEGR1_e=0x17,
    MOIR_JNT_LEGR2_e=0x18,
    MOIR_JNT_FOOTR_e=0x19,
};

enum MOIR_HEADGEAR_JNT {
    MOIR_HEADGEAR_JNT_MOI_HEADGEAR_MODEL_e=0x0,
};

#endif /* !RES_MOIR_H */