#ifndef RES_TOBY2_H
#define RES_TOBY2_H

enum dRes_INDEX_TOBY2 {
    /* BCK  */
    dRes_INDEX_TOBY2_BCK_TOBY_F_FEARTALK_e=0x6,
    dRes_INDEX_TOBY2_BCK_TOBY_F_SIGH_e=0x7,
    dRes_INDEX_TOBY2_BCK_TOBY_FH_SIGH_e=0x8,
    dRes_INDEX_TOBY2_BCK_TOBY_FH_SURPRISED_e=0x9,
    dRes_INDEX_TOBY2_BCK_TOBY_SIGH_e=0xA,
    dRes_INDEX_TOBY2_BCK_TOBY_SURPRISED_e=0xB,
    dRes_INDEX_TOBY2_BCK_TOBY_UTUMUKU_WAIT_e=0xC,
    /* BTK  */
    dRes_INDEX_TOBY2_BTK_TOBY_SIGH_e=0xF,
    dRes_INDEX_TOBY2_BTK_TOBY_SURPRISED_e=0x10,
    dRes_INDEX_TOBY2_BTK_TOBY_UTUMUKU_WAIT_e=0x11,
    /* BTP  */
    dRes_INDEX_TOBY2_BTP_TOBY_F_FEARTALK_e=0x14,
    dRes_INDEX_TOBY2_BTP_TOBY_F_SIGH_e=0x15,
    dRes_INDEX_TOBY2_BTP_TOBY_FH_SIGH_e=0x16,
    /* EVT  */
    dRes_INDEX_TOBY2_DAT_EVENT_LIST_e=0x19,
};

enum dRes_ID_TOBY2 {
    /* BCK  */
    dRes_ID_TOBY2_BCK_TOBY_F_FEARTALK_e=0x6,
    dRes_ID_TOBY2_BCK_TOBY_F_SIGH_e=0x7,
    dRes_ID_TOBY2_BCK_TOBY_FH_SIGH_e=0x8,
    dRes_ID_TOBY2_BCK_TOBY_FH_SURPRISED_e=0x9,
    dRes_ID_TOBY2_BCK_TOBY_SIGH_e=0xA,
    dRes_ID_TOBY2_BCK_TOBY_SURPRISED_e=0xB,
    dRes_ID_TOBY2_BCK_TOBY_UTUMUKU_WAIT_e=0xC,
    /* BTK  */
    dRes_ID_TOBY2_BTK_TOBY_SIGH_e=0xF,
    dRes_ID_TOBY2_BTK_TOBY_SURPRISED_e=0x10,
    dRes_ID_TOBY2_BTK_TOBY_UTUMUKU_WAIT_e=0x11,
    /* BTP  */
    dRes_ID_TOBY2_BTP_TOBY_F_FEARTALK_e=0x14,
    dRes_ID_TOBY2_BTP_TOBY_F_SIGH_e=0x15,
    dRes_ID_TOBY2_BTP_TOBY_FH_SIGH_e=0x16,
    /* EVT  */
    dRes_ID_TOBY2_DAT_EVENT_LIST_e=0x19,
};

#endif /* !RES_TOBY2_H */