#ifndef RES_YAMIT_H
#define RES_YAMIT_H

enum dRes_INDEX_YAMIT {
    /* BCK  */
    dRes_INDEX_YAMIT_BCK_YAMIT_F_TALK_A_e=0x6,
    dRes_INDEX_YAMIT_BCK_YAMIT_STEP_e=0x7,
    dRes_INDEX_YAMIT_BCK_YAMIT_TALK_A_e=0x8,
    dRes_INDEX_YAMIT_BCK_YAMIT_WAIT_A_e=0x9,
    /* BMDR */
    dRes_INDEX_YAMIT_BMD_YAMIT_e=0xC,
    /* BTP  */
    dRes_INDEX_YAMIT_BTP_YAMIT_e=0xF,
    /* EVT  */
    dRes_INDEX_YAMIT_DAT_EVENT_LIST_e=0x12,
};

enum dRes_ID_YAMIT {
    /* BCK  */
    dRes_ID_YAMIT_BCK_YAMIT_F_TALK_A_e=0x6,
    dRes_ID_YAMIT_BCK_YAMIT_STEP_e=0x7,
    dRes_ID_YAMIT_BCK_YAMIT_TALK_A_e=0x8,
    dRes_ID_YAMIT_BCK_YAMIT_WAIT_A_e=0x9,
    /* BMDR */
    dRes_ID_YAMIT_BMD_YAMIT_e=0xC,
    /* BTP  */
    dRes_ID_YAMIT_BTP_YAMIT_e=0xF,
    /* EVT  */
    dRes_ID_YAMIT_DAT_EVENT_LIST_e=0x12,
};

enum YAMIT_JNT {
    YAMIT_JNT_CENTER_e=0x0,
    YAMIT_JNT_BACKBONE1_e=0x1,
    YAMIT_JNT_BACKBONE2_e=0x2,
    YAMIT_JNT_NECK_e=0x3,
    YAMIT_JNT_HEAD_e=0x4,
    YAMIT_JNT_CHIN_e=0x5,
    YAMIT_JNT_MOUTH_e=0x6,
    YAMIT_JNT_SHOULDERL_e=0x7,
    YAMIT_JNT_ARML1_e=0x8,
    YAMIT_JNT_ARML2_e=0x9,
    YAMIT_JNT_HANDL_e=0xA,
    YAMIT_JNT_FINGERL_e=0xB,
    YAMIT_JNT_SHOULDERR_e=0xC,
    YAMIT_JNT_ARMR1_e=0xD,
    YAMIT_JNT_ARMR2_e=0xE,
    YAMIT_JNT_HANDR_e=0xF,
    YAMIT_JNT_FINGERR_e=0x10,
    YAMIT_JNT_WAIST_e=0x11,
    YAMIT_JNT_LEGL1_e=0x12,
    YAMIT_JNT_LEGL2_e=0x13,
    YAMIT_JNT_FOOTL_e=0x14,
    YAMIT_JNT_LEGR1_e=0x15,
    YAMIT_JNT_LEGR2_e=0x16,
    YAMIT_JNT_FOOTR_e=0x17,
    YAMIT_JNT_WAIST_END_e=0x18,
};

#endif /* !RES_YAMIT_H */