#ifndef RES_MSGRES02R_H
#define RES_MSGRES02R_H

enum dRes_INDEX_MSGRES02R {
    /* SCRN */
    dRes_INDEX_MSGRES02R_BCK_ZELDA_BOOK_A_BOOK_e=0x4,
    dRes_INDEX_MSGRES02R_BLO_ZELDA_BOOK_A_BOOK_e=0x5,
    dRes_INDEX_MSGRES02R_BPK_ZELDA_BOOK_A_BOOK_e=0x6,
    dRes_INDEX_MSGRES02R_BTK_ZELDA_BOOK_A_BOOK_e=0x7,
    dRes_INDEX_MSGRES02R_BCK_ZELDA_BOOK_A_SPOT_HILIGHT_e=0x8,
    dRes_INDEX_MSGRES02R_BLO_ZELDA_BOOK_A_SPOT_HILIGHT_e=0x9,
    dRes_INDEX_MSGRES02R_BCK_ZELDA_KANBAN_STONE_A_e=0xA,
    dRes_INDEX_MSGRES02R_BLO_ZELDA_KANBAN_STONE_A_e=0xB,
    dRes_INDEX_MSGRES02R_BTK_ZELDA_KANBAN_STONE_A_e=0xC,
    dRes_INDEX_MSGRES02R_BCK_ZELDA_KANBAN_WOOD_A_e=0xD,
    dRes_INDEX_MSGRES02R_BLO_ZELDA_KANBAN_WOOD_A_e=0xE,
    dRes_INDEX_MSGRES02R_BTK_ZELDA_KANBAN_WOOD_A_e=0xF,
    dRes_INDEX_MSGRES02R_BTK_ZELDA_KANBAN_WOOD_A_02_e=0x10,
    /* TIMG */
    dRes_INDEX_MSGRES02R_BTI_AK_KAGEROURR_e=0x13,
    dRes_INDEX_MSGRES02R_BTI_TT_BLACK_32_e=0x14,
    dRes_INDEX_MSGRES02R_BTI_TT_BLACK_40_e=0x15,
    dRes_INDEX_MSGRES02R_BTI_TT_BLACK_MGW_e=0x16,
    dRes_INDEX_MSGRES02R_BTI_TT_BLOCK128_00_e=0x17,
    dRes_INDEX_MSGRES02R_BTI_TT_BLOCK_GRADE_e=0x18,
    dRes_INDEX_MSGRES02R_BTI_TT_GAKUBUCHI_KAZARI_L_e=0x19,
    dRes_INDEX_MSGRES02R_BTI_TT_GOLD_UZU_LONG2_e=0x1A,
    dRes_INDEX_MSGRES02R_BTI_TT_GOLD_WAVE_LEFT2_e=0x1B,
    dRes_INDEX_MSGRES02R_BTI_TT_HORIWAKU_LU_e=0x1C,
    dRes_INDEX_MSGRES02R_BTI_TT_I4_GRA_e=0x1D,
    dRes_INDEX_MSGRES02R_BTI_TT_KAZARI_KANI_00_e=0x1E,
    dRes_INDEX_MSGRES02R_BTI_TT_MARU88_e=0x1F,
    dRes_INDEX_MSGRES02R_BTI_TT_SPOT_e=0x20,
    dRes_INDEX_MSGRES02R_BTI_TT_SPOT_BIG_e=0x21,
    dRes_INDEX_MSGRES02R_BTI_TT_UZUMAKI_00_e=0x22,
    dRes_INDEX_MSGRES02R_BTI_TT_YAKUSHIMA_e=0x23,
};

enum dRes_ID_MSGRES02R {
    /* SCRN */
    dRes_ID_MSGRES02R_BCK_ZELDA_BOOK_A_BOOK_e=0x4,
    dRes_ID_MSGRES02R_BLO_ZELDA_BOOK_A_BOOK_e=0x5,
    dRes_ID_MSGRES02R_BPK_ZELDA_BOOK_A_BOOK_e=0x6,
    dRes_ID_MSGRES02R_BTK_ZELDA_BOOK_A_BOOK_e=0x7,
    dRes_ID_MSGRES02R_BCK_ZELDA_BOOK_A_SPOT_HILIGHT_e=0x8,
    dRes_ID_MSGRES02R_BLO_ZELDA_BOOK_A_SPOT_HILIGHT_e=0x9,
    dRes_ID_MSGRES02R_BCK_ZELDA_KANBAN_STONE_A_e=0xA,
    dRes_ID_MSGRES02R_BLO_ZELDA_KANBAN_STONE_A_e=0xB,
    dRes_ID_MSGRES02R_BTK_ZELDA_KANBAN_STONE_A_e=0xC,
    dRes_ID_MSGRES02R_BCK_ZELDA_KANBAN_WOOD_A_e=0xD,
    dRes_ID_MSGRES02R_BLO_ZELDA_KANBAN_WOOD_A_e=0xE,
    dRes_ID_MSGRES02R_BTK_ZELDA_KANBAN_WOOD_A_e=0xF,
    dRes_ID_MSGRES02R_BTK_ZELDA_KANBAN_WOOD_A_02_e=0x10,
    /* TIMG */
    dRes_ID_MSGRES02R_BTI_AK_KAGEROURR_e=0x13,
    dRes_ID_MSGRES02R_BTI_TT_BLACK_32_e=0x14,
    dRes_ID_MSGRES02R_BTI_TT_BLACK_40_e=0x15,
    dRes_ID_MSGRES02R_BTI_TT_BLACK_MGW_e=0x16,
    dRes_ID_MSGRES02R_BTI_TT_BLOCK128_00_e=0x17,
    dRes_ID_MSGRES02R_BTI_TT_BLOCK_GRADE_e=0x18,
    dRes_ID_MSGRES02R_BTI_TT_GAKUBUCHI_KAZARI_L_e=0x19,
    dRes_ID_MSGRES02R_BTI_TT_GOLD_UZU_LONG2_e=0x1A,
    dRes_ID_MSGRES02R_BTI_TT_GOLD_WAVE_LEFT2_e=0x1B,
    dRes_ID_MSGRES02R_BTI_TT_HORIWAKU_LU_e=0x1C,
    dRes_ID_MSGRES02R_BTI_TT_I4_GRA_e=0x1D,
    dRes_ID_MSGRES02R_BTI_TT_KAZARI_KANI_00_e=0x1E,
    dRes_ID_MSGRES02R_BTI_TT_MARU88_e=0x1F,
    dRes_ID_MSGRES02R_BTI_TT_SPOT_e=0x20,
    dRes_ID_MSGRES02R_BTI_TT_SPOT_BIG_e=0x21,
    dRes_ID_MSGRES02R_BTI_TT_UZUMAKI_00_e=0x22,
    dRes_ID_MSGRES02R_BTI_TT_YAKUSHIMA_e=0x23,
};

#endif /* !RES_MSGRES02R_H */