#ifndef RES_ASHB_H
#define RES_ASHB_H

enum dRes_INDEX_ASHB {
    /* BCK  */
    dRes_INDEX_ASHB_BCK_ASHB_ASK_e=0x7,
    dRes_INDEX_ASHB_BCK_ASHB_EXPLAIN_e=0x8,
    dRes_INDEX_ASHB_BCK_ASHB_F_ASK_e=0x9,
    dRes_INDEX_ASHB_BCK_ASHB_F_GREET_e=0xA,
    dRes_INDEX_ASHB_BCK_ASHB_F_HATE_e=0xB,
    dRes_INDEX_ASHB_BCK_ASHB_F_LOOKBACK_e=0xC,
    dRes_INDEX_ASHB_BCK_ASHB_F_TALK_A_e=0xD,
    dRes_INDEX_ASHB_BCK_ASHB_F_TALK_B_e=0xE,
    dRes_INDEX_ASHB_BCK_ASHB_GREET_e=0xF,
    dRes_INDEX_ASHB_BCK_ASHB_HAND_e=0x10,
    dRes_INDEX_ASHB_BCK_ASHB_HANDWAIT_e=0x11,
    dRes_INDEX_ASHB_BCK_ASHB_HATE_e=0x12,
    dRes_INDEX_ASHB_BCK_ASHB_LOOKBACK_e=0x13,
    dRes_INDEX_ASHB_BCK_ASHB_MASKOFF_e=0x14,
    dRes_INDEX_ASHB_BCK_ASHB_STEP_e=0x15,
    dRes_INDEX_ASHB_BCK_ASHB_STEP_B_e=0x16,
    dRes_INDEX_ASHB_BCK_ASHB_TO_WAIT_B_e=0x17,
    dRes_INDEX_ASHB_BCK_ASHB_WAIT_A_e=0x18,
    dRes_INDEX_ASHB_BCK_ASHB_WAIT_B_e=0x19,
    /* BMDR */
    dRes_INDEX_ASHB_BMD_ASHB_e=0x1C,
    dRes_INDEX_ASHB_BMD_ASHB_MASK_e=0x1D,
    /* BTK  */
    dRes_INDEX_ASHB_BTK_ASHB_e=0x20,
    dRes_INDEX_ASHB_BTK_ASHB_HAND_e=0x21,
    dRes_INDEX_ASHB_BTK_ASHB_HATE_e=0x22,
    dRes_INDEX_ASHB_BTK_ASHB_LOOKBACK_e=0x23,
    /* BTP  */
    dRes_INDEX_ASHB_BTP_ASHB_e=0x26,
    dRes_INDEX_ASHB_BTP_ASHB_F_GREET_e=0x27,
    dRes_INDEX_ASHB_BTP_ASHB_F_HATE_e=0x28,
    dRes_INDEX_ASHB_BTP_ASHB_MASKOFF_e=0x29,
    /* EVT  */
    dRes_INDEX_ASHB_DAT_EVENT_LIST_e=0x2C,
};

enum dRes_ID_ASHB {
    /* BCK  */
    dRes_ID_ASHB_BCK_ASHB_ASK_e=0x7,
    dRes_ID_ASHB_BCK_ASHB_EXPLAIN_e=0x8,
    dRes_ID_ASHB_BCK_ASHB_F_ASK_e=0x9,
    dRes_ID_ASHB_BCK_ASHB_F_GREET_e=0xA,
    dRes_ID_ASHB_BCK_ASHB_F_HATE_e=0xB,
    dRes_ID_ASHB_BCK_ASHB_F_LOOKBACK_e=0xC,
    dRes_ID_ASHB_BCK_ASHB_F_TALK_A_e=0xD,
    dRes_ID_ASHB_BCK_ASHB_F_TALK_B_e=0xE,
    dRes_ID_ASHB_BCK_ASHB_GREET_e=0xF,
    dRes_ID_ASHB_BCK_ASHB_HAND_e=0x10,
    dRes_ID_ASHB_BCK_ASHB_HANDWAIT_e=0x11,
    dRes_ID_ASHB_BCK_ASHB_HATE_e=0x12,
    dRes_ID_ASHB_BCK_ASHB_LOOKBACK_e=0x13,
    dRes_ID_ASHB_BCK_ASHB_MASKOFF_e=0x14,
    dRes_ID_ASHB_BCK_ASHB_STEP_e=0x15,
    dRes_ID_ASHB_BCK_ASHB_STEP_B_e=0x16,
    dRes_ID_ASHB_BCK_ASHB_TO_WAIT_B_e=0x17,
    dRes_ID_ASHB_BCK_ASHB_WAIT_A_e=0x18,
    dRes_ID_ASHB_BCK_ASHB_WAIT_B_e=0x19,
    /* BMDR */
    dRes_ID_ASHB_BMD_ASHB_e=0x1C,
    dRes_ID_ASHB_BMD_ASHB_MASK_e=0x1D,
    /* BTK  */
    dRes_ID_ASHB_BTK_ASHB_e=0x20,
    dRes_ID_ASHB_BTK_ASHB_HAND_e=0x21,
    dRes_ID_ASHB_BTK_ASHB_HATE_e=0x22,
    dRes_ID_ASHB_BTK_ASHB_LOOKBACK_e=0x23,
    /* BTP  */
    dRes_ID_ASHB_BTP_ASHB_e=0x26,
    dRes_ID_ASHB_BTP_ASHB_F_GREET_e=0x27,
    dRes_ID_ASHB_BTP_ASHB_F_HATE_e=0x28,
    dRes_ID_ASHB_BTP_ASHB_MASKOFF_e=0x29,
    /* EVT  */
    dRes_ID_ASHB_DAT_EVENT_LIST_e=0x2C,
};

enum ASHB_JNT {
    ASHB_JNT_CENTER_e=0x0,
    ASHB_JNT_BB1_e=0x1,
    ASHB_JNT_BB2_e=0x2,
    ASHB_JNT_BACKL_e=0x3,
    ASHB_JNT_BACKR_e=0x4,
    ASHB_JNT_FRONTL_e=0x5,
    ASHB_JNT_FRONTL2_e=0x6,
    ASHB_JNT_FRONTR_e=0x7,
    ASHB_JNT_FRONTR2_e=0x8,
    ASHB_JNT_NECK_e=0x9,
    ASHB_JNT_HEAD_e=0xA,
    ASHB_JNT_CHIN_e=0xB,
    ASHB_JNT_HAIRL1_e=0xC,
    ASHB_JNT_HAIRL2_e=0xD,
    ASHB_JNT_HAIRR1_e=0xE,
    ASHB_JNT_HAIRR2_e=0xF,
    ASHB_JNT_MASK_e=0x10,
    ASHB_JNT_MAYUL_e=0x11,
    ASHB_JNT_MAYUR_e=0x12,
    ASHB_JNT_MOUTH_e=0x13,
    ASHB_JNT_SHOULDERL_e=0x14,
    ASHB_JNT_ARML1_e=0x15,
    ASHB_JNT_ARML2_e=0x16,
    ASHB_JNT_HANDL_e=0x17,
    ASHB_JNT_FINGERL_e=0x18,
    ASHB_JNT_THUMBL_e=0x19,
    ASHB_JNT_SHOULDERR_e=0x1A,
    ASHB_JNT_ARMR1_e=0x1B,
    ASHB_JNT_ARMR2_e=0x1C,
    ASHB_JNT_HANDR_e=0x1D,
    ASHB_JNT_FINGERR_e=0x1E,
    ASHB_JNT_THUMBR_e=0x1F,
    ASHB_JNT_WAIST_e=0x20,
    ASHB_JNT_LEGL1_e=0x21,
    ASHB_JNT_LEGL2_e=0x22,
    ASHB_JNT_FOOTL_e=0x23,
    ASHB_JNT_LEGR1_e=0x24,
    ASHB_JNT_LEGR2_e=0x25,
    ASHB_JNT_FOOTR_e=0x26,
    ASHB_JNT_SWORD_e=0x27,
};

enum ASHB_MASK_JNT {
    ASHB_MASK_JNT_MASK_MODEL_e=0x0,
};

#endif /* !RES_ASHB_H */