#ifndef RES_KKRI_TW_H
#define RES_KKRI_TW_H

enum dRes_INDEX_KKRI_TW {
    /* BCK  */
    dRes_INDEX_KKRI_TW_BCK_KKRI_F_FEAR_e=0x7,
    dRes_INDEX_KKRI_TW_BCK_KKRI_F_FEAR_TALK_e=0x8,
    dRes_INDEX_KKRI_TW_BCK_KKRI_F_LOOK_AROUND_e=0x9,
    dRes_INDEX_KKRI_TW_BCK_KKRI_FEAR_e=0xA,
    dRes_INDEX_KKRI_TW_BCK_KKRI_FEAR_TALK_e=0xB,
    dRes_INDEX_KKRI_TW_BCK_KKRI_LOOK_AROUND_e=0xC,
    dRes_INDEX_KKRI_TW_BCK_KKRI_TO_FEAR_TALK_e=0xD,
    dRes_INDEX_KKRI_TW_BCK_KKRI_WORRY_TALK_e=0xE,
    dRes_INDEX_KKRI_TW_BCK_KKRI_WORRY_WAIT_e=0xF,
    /* BMDR */
    dRes_INDEX_KKRI_TW_BMD_KKRI_TW_e=0x12,
    /* BTK  */
    dRes_INDEX_KKRI_TW_BTK_KKRI_FEAR_TALK_e=0x15,
    dRes_INDEX_KKRI_TW_BTK_KKRI_LOOK_AROUND_e=0x16,
    dRes_INDEX_KKRI_TW_BTK_KKRI_WORRY_TALK_e=0x17,
    /* BTP  */
    dRes_INDEX_KKRI_TW_BTP_KKRI_F_FEAR_TALK_e=0x1A,
    dRes_INDEX_KKRI_TW_BTP_KKRI_F_LOOK_AROUND_e=0x1B,
    /* EVT  */
    dRes_INDEX_KKRI_TW_DAT_EVENT_LIST_e=0x1E,
};

enum dRes_ID_KKRI_TW {
    /* BCK  */
    dRes_ID_KKRI_TW_BCK_KKRI_F_FEAR_e=0x7,
    dRes_ID_KKRI_TW_BCK_KKRI_F_FEAR_TALK_e=0x8,
    dRes_ID_KKRI_TW_BCK_KKRI_F_LOOK_AROUND_e=0x9,
    dRes_ID_KKRI_TW_BCK_KKRI_FEAR_e=0xA,
    dRes_ID_KKRI_TW_BCK_KKRI_FEAR_TALK_e=0xB,
    dRes_ID_KKRI_TW_BCK_KKRI_LOOK_AROUND_e=0xC,
    dRes_ID_KKRI_TW_BCK_KKRI_TO_FEAR_TALK_e=0xD,
    dRes_ID_KKRI_TW_BCK_KKRI_WORRY_TALK_e=0xE,
    dRes_ID_KKRI_TW_BCK_KKRI_WORRY_WAIT_e=0xF,
    /* BMDR */
    dRes_ID_KKRI_TW_BMD_KKRI_TW_e=0x12,
    /* BTK  */
    dRes_ID_KKRI_TW_BTK_KKRI_FEAR_TALK_e=0x15,
    dRes_ID_KKRI_TW_BTK_KKRI_LOOK_AROUND_e=0x16,
    dRes_ID_KKRI_TW_BTK_KKRI_WORRY_TALK_e=0x17,
    /* BTP  */
    dRes_ID_KKRI_TW_BTP_KKRI_F_FEAR_TALK_e=0x1A,
    dRes_ID_KKRI_TW_BTP_KKRI_F_LOOK_AROUND_e=0x1B,
    /* EVT  */
    dRes_ID_KKRI_TW_DAT_EVENT_LIST_e=0x1E,
};

enum KKRI_TW_JNT {
    KKRI_TW_JNT_CENTER_e=0x0,
    KKRI_TW_JNT_BACKBONE1_e=0x1,
    KKRI_TW_JNT_BACKBONE2_e=0x2,
    KKRI_TW_JNT_NECK_e=0x3,
    KKRI_TW_JNT_HEAD_e=0x4,
    KKRI_TW_JNT_BD1_e=0x5,
    KKRI_TW_JNT_BD2_e=0x6,
    KKRI_TW_JNT_CHIN_e=0x7,
    KKRI_TW_JNT_MAYU_L_e=0x8,
    KKRI_TW_JNT_MAYU_R_e=0x9,
    KKRI_TW_JNT_MOUTH_e=0xA,
    KKRI_TW_JNT_SHOULDERL_e=0xB,
    KKRI_TW_JNT_ARML1_e=0xC,
    KKRI_TW_JNT_ARML2_e=0xD,
    KKRI_TW_JNT_HANDL_e=0xE,
    KKRI_TW_JNT_FINGERL_e=0xF,
    KKRI_TW_JNT_THUMBL_e=0x10,
    KKRI_TW_JNT_BD3_e=0x11,
    KKRI_TW_JNT_SHOULDERR_e=0x12,
    KKRI_TW_JNT_ARMR1_e=0x13,
    KKRI_TW_JNT_ARMR2_e=0x14,
    KKRI_TW_JNT_HANDR_e=0x15,
    KKRI_TW_JNT_FINGERR_e=0x16,
    KKRI_TW_JNT_THUMBR_e=0x17,
    KKRI_TW_JNT_TUBO1_e=0x18,
    KKRI_TW_JNT_TUBO2_e=0x19,
    KKRI_TW_JNT_WAIST_e=0x1A,
    KKRI_TW_JNT_LEGL1_e=0x1B,
    KKRI_TW_JNT_LEGL2_e=0x1C,
    KKRI_TW_JNT_FOOTL_e=0x1D,
    KKRI_TW_JNT_LEGR1_e=0x1E,
    KKRI_TW_JNT_LEGR2_e=0x1F,
    KKRI_TW_JNT_FOOTR_e=0x20,
};

#endif /* !RES_KKRI_TW_H */