#ifndef RES_MON_A2LTW_H
#define RES_MON_A2LTW_H

enum dRes_INDEX_MON_A2LTW {
    /* BMDR */
    dRes_INDEX_MON_A2LTW_BMD_MON_A2_L_TW_e=0x3,
};

enum dRes_ID_MON_A2LTW {
    /* BMDR */
    dRes_ID_MON_A2LTW_BMD_MON_A2_L_TW_e=0x3,
};

enum MON_A2_L_TW_JNT {
    MON_A2_L_TW_JNT_WORLD_ROOT_e=0x0,
    MON_A2_L_TW_JNT_BACKBONE_e=0x1,
    MON_A2_L_TW_JNT_ARML1_e=0x2,
    MON_A2_L_TW_JNT_ARML2_e=0x3,
    MON_A2_L_TW_JNT_ARMR1_e=0x4,
    MON_A2_L_TW_JNT_ARMR2_e=0x5,
    MON_A2_L_TW_JNT_HEAD_e=0x6,
    MON_A2_L_TW_JNT_WAIST_e=0x7,
    MON_A2_L_TW_JNT_LEGL1_e=0x8,
    MON_A2_L_TW_JNT_LEGL2_e=0x9,
    MON_A2_L_TW_JNT_LEGR1_e=0xA,
    MON_A2_L_TW_JNT_LEGR2_e=0xB,
};

#endif /* !RES_MON_A2LTW_H */