#ifndef RES_MR_CHAIN_H
#define RES_MR_CHAIN_H

enum dRes_INDEX_MR_CHAIN {
    /* BCK  */
    dRes_INDEX_MR_CHAIN_BCK_U_MR_CHAINMONO_DOWN02_e=0x7,
    dRes_INDEX_MR_CHAIN_BCK_U_MR_CHAINMONO_UP01_e=0x8,
    dRes_INDEX_MR_CHAIN_BCK_U_MR_HOLE_e=0x9,
    /* BMDE */
    dRes_INDEX_MR_CHAIN_BMD_U_MR_HOLE_e=0xC,
    /* BMDR */
    dRes_INDEX_MR_CHAIN_BMD_U_MR_CHAINMONO_e=0xF,
    dRes_INDEX_MR_CHAIN_BMD_U_MR_MONOANA_e=0x10,
    /* BRK  */
    dRes_INDEX_MR_CHAIN_BRK_U_MR_CHAINTEV_e=0x13,
    dRes_INDEX_MR_CHAIN_BRK_U_MR_HOLE_e=0x14,
    dRes_INDEX_MR_CHAIN_BRK_U_MR_MONOANA_e=0x15,
    /* DZB  */
    dRes_INDEX_MR_CHAIN_DZB_U_MR_CHAINMONO_01_e=0x18,
    dRes_INDEX_MR_CHAIN_DZB_U_MR_CHAINMONO_02_e=0x19,
    dRes_INDEX_MR_CHAIN_DZB_U_MR_MONOANA_e=0x1A,
};

enum dRes_ID_MR_CHAIN {
    /* BCK  */
    dRes_ID_MR_CHAIN_BCK_U_MR_CHAINMONO_DOWN02_e=0x7,
    dRes_ID_MR_CHAIN_BCK_U_MR_CHAINMONO_UP01_e=0x8,
    dRes_ID_MR_CHAIN_BCK_U_MR_HOLE_e=0x9,
    /* BMDE */
    dRes_ID_MR_CHAIN_BMD_U_MR_HOLE_e=0xC,
    /* BMDR */
    dRes_ID_MR_CHAIN_BMD_U_MR_CHAINMONO_e=0xF,
    dRes_ID_MR_CHAIN_BMD_U_MR_MONOANA_e=0x10,
    /* BRK  */
    dRes_ID_MR_CHAIN_BRK_U_MR_CHAINTEV_e=0x13,
    dRes_ID_MR_CHAIN_BRK_U_MR_HOLE_e=0x14,
    dRes_ID_MR_CHAIN_BRK_U_MR_MONOANA_e=0x15,
    /* DZB  */
    dRes_ID_MR_CHAIN_DZB_U_MR_CHAINMONO_01_e=0x18,
    dRes_ID_MR_CHAIN_DZB_U_MR_CHAINMONO_02_e=0x19,
    dRes_ID_MR_CHAIN_DZB_U_MR_MONOANA_e=0x1A,
};

enum U_MR_HOLE_JNT {
    U_MR_HOLE_JNT_HOLE01_e=0x0,
    U_MR_HOLE_JNT_HOLE02_e=0x1,
    U_MR_HOLE_JNT_HOLE03_e=0x2,
    U_MR_HOLE_JNT_HOLE04_e=0x3,
    U_MR_HOLE_JNT_HOLE05_e=0x4,
    U_MR_HOLE_JNT_HOLE06_e=0x5,
    U_MR_HOLE_JNT_HOLE07_e=0x6,
};

enum U_MR_CHAINMONO_JNT {
    U_MR_CHAINMONO_JNT_POLE_KARI_e=0x0,
    U_MR_CHAINMONO_JNT_MONOLITH_e=0x1,
    U_MR_CHAINMONO_JNT_ACHAIN1_e=0x2,
    U_MR_CHAINMONO_JNT_ACHAIN2_e=0x3,
    U_MR_CHAINMONO_JNT_ACHAIN3_e=0x4,
    U_MR_CHAINMONO_JNT_ACHAIN4_e=0x5,
    U_MR_CHAINMONO_JNT_BCHAIN1_e=0x6,
    U_MR_CHAINMONO_JNT_BCHAIN2_e=0x7,
    U_MR_CHAINMONO_JNT_BCHAIN3_e=0x8,
    U_MR_CHAINMONO_JNT_BCHAIN4_e=0x9,
    U_MR_CHAINMONO_JNT_CCHAIN1_e=0xA,
    U_MR_CHAINMONO_JNT_CCHAIN2_e=0xB,
    U_MR_CHAINMONO_JNT_CCHAIN3_e=0xC,
    U_MR_CHAINMONO_JNT_CCHAIN4_e=0xD,
    U_MR_CHAINMONO_JNT_DCHAIN1_e=0xE,
    U_MR_CHAINMONO_JNT_DCHAIN2_e=0xF,
    U_MR_CHAINMONO_JNT_DCHAIN3_e=0x10,
    U_MR_CHAINMONO_JNT_DCHAIN4_e=0x11,
    U_MR_CHAINMONO_JNT_ECHAIN1_e=0x12,
    U_MR_CHAINMONO_JNT_ECHAIN2_e=0x13,
    U_MR_CHAINMONO_JNT_ECHAIN3_e=0x14,
    U_MR_CHAINMONO_JNT_ECHAIN4_e=0x15,
    U_MR_CHAINMONO_JNT_FCHAIN1_e=0x16,
    U_MR_CHAINMONO_JNT_FCHAIN2_e=0x17,
    U_MR_CHAINMONO_JNT_FCHAIN3_e=0x18,
    U_MR_CHAINMONO_JNT_FCHAIN4_e=0x19,
    U_MR_CHAINMONO_JNT_GCHAIN1_e=0x1A,
    U_MR_CHAINMONO_JNT_GCHAIN2_e=0x1B,
    U_MR_CHAINMONO_JNT_HCHAIN1_e=0x1C,
    U_MR_CHAINMONO_JNT_HCHAIN2_e=0x1D,
};

enum U_MR_MONOANA_JNT {
    U_MR_MONOANA_JNT_WORLD_ROOT_e=0x0,
};

#endif /* !RES_MR_CHAIN_H */