#ifndef RES_BESU0_H
#define RES_BESU0_H

enum dRes_INDEX_BESU0 {
    /* BCK  */
    dRes_INDEX_BESU0_BCK_BESU_BODY_TALK_e=0x5,
    dRes_INDEX_BESU0_BCK_BESU_BODY_WAIT_e=0x6,
    dRes_INDEX_BESU0_BCK_BESU_F_TALK_C_e=0x7,
    dRes_INDEX_BESU0_BCK_BESU_F_YOKERU_e=0x8,
    dRes_INDEX_BESU0_BCK_BESU_FH_BIKKURI_e=0x9,
    dRes_INDEX_BESU0_BCK_BESU_MAD_e=0xA,
    dRes_INDEX_BESU0_BCK_BESU_MAD_WAIT_e=0xB,
    dRes_INDEX_BESU0_BCK_BESU_NORMAL_STEP_e=0xC,
    dRes_INDEX_BESU0_BCK_BESU_NORMAL_TALK_e=0xD,
    dRes_INDEX_BESU0_BCK_BESU_NORMAL_TALK_B_e=0xE,
    dRes_INDEX_BESU0_BCK_BESU_NORMAL_WAIT_e=0xF,
    dRes_INDEX_BESU0_BCK_BESU_STEP_e=0x10,
    dRes_INDEX_BESU0_BCK_BESU_WAIT_A_e=0x11,
    dRes_INDEX_BESU0_BCK_BESU_WAIT_C_e=0x12,
    dRes_INDEX_BESU0_BCK_BESU_YOKERU_e=0x13,
    /* BTK  */
    dRes_INDEX_BESU0_BTK_BESU_e=0x16,
    /* BTP  */
    dRes_INDEX_BESU0_BTP_BESU_e=0x19,
    dRes_INDEX_BESU0_BTP_BESU_F_YOKERU_e=0x1A,
    dRes_INDEX_BESU0_BTP_BESU_FH_BIKKURI_e=0x1B,
};

enum dRes_ID_BESU0 {
    /* BCK  */
    dRes_ID_BESU0_BCK_BESU_BODY_TALK_e=0x5,
    dRes_ID_BESU0_BCK_BESU_BODY_WAIT_e=0x6,
    dRes_ID_BESU0_BCK_BESU_F_TALK_C_e=0x7,
    dRes_ID_BESU0_BCK_BESU_F_YOKERU_e=0x8,
    dRes_ID_BESU0_BCK_BESU_FH_BIKKURI_e=0x9,
    dRes_ID_BESU0_BCK_BESU_MAD_e=0xA,
    dRes_ID_BESU0_BCK_BESU_MAD_WAIT_e=0xB,
    dRes_ID_BESU0_BCK_BESU_NORMAL_STEP_e=0xC,
    dRes_ID_BESU0_BCK_BESU_NORMAL_TALK_e=0xD,
    dRes_ID_BESU0_BCK_BESU_NORMAL_TALK_B_e=0xE,
    dRes_ID_BESU0_BCK_BESU_NORMAL_WAIT_e=0xF,
    dRes_ID_BESU0_BCK_BESU_STEP_e=0x10,
    dRes_ID_BESU0_BCK_BESU_WAIT_A_e=0x11,
    dRes_ID_BESU0_BCK_BESU_WAIT_C_e=0x12,
    dRes_ID_BESU0_BCK_BESU_YOKERU_e=0x13,
    /* BTK  */
    dRes_ID_BESU0_BTK_BESU_e=0x16,
    /* BTP  */
    dRes_ID_BESU0_BTP_BESU_e=0x19,
    dRes_ID_BESU0_BTP_BESU_F_YOKERU_e=0x1A,
    dRes_ID_BESU0_BTP_BESU_FH_BIKKURI_e=0x1B,
};

#endif /* !RES_BESU0_H */