#ifndef RES_LV7GATE_H
#define RES_LV7GATE_H

enum dRes_INDEX_LV7GATE {
    /* BCK  */
    dRes_INDEX_LV7GATE_BCK_DR_FLY_e=0x5,
    dRes_INDEX_LV7GATE_BCK_DR_FLY_TO_GLIDE_e=0x6,
    dRes_INDEX_LV7GATE_BCK_DR_GLIDE_e=0x7,
    dRes_INDEX_LV7GATE_BCK_DR_GLIDE_TO_FLY_e=0x8,
    /* BMDE */
    dRes_INDEX_LV7GATE_BMD_DR_e=0xB,
    /* EVT  */
    dRes_INDEX_LV7GATE_DAT_EVENT_LIST_e=0xE,
};

enum dRes_ID_LV7GATE {
    /* BCK  */
    dRes_ID_LV7GATE_BCK_DR_FLY_e=0x5,
    dRes_ID_LV7GATE_BCK_DR_FLY_TO_GLIDE_e=0x6,
    dRes_ID_LV7GATE_BCK_DR_GLIDE_e=0x7,
    dRes_ID_LV7GATE_BCK_DR_GLIDE_TO_FLY_e=0x8,
    /* BMDE */
    dRes_ID_LV7GATE_BMD_DR_e=0xB,
    /* EVT  */
    dRes_ID_LV7GATE_DAT_EVENT_LIST_e=0xE,
};

enum DR_JNT {
    DR_JNT_WORLD_ROOT_e=0x0,
    DR_JNT_BACK_BONE1_e=0x1,
    DR_JNT_BACK_BONE2_e=0x2,
    DR_JNT_LWING1_e=0x3,
    DR_JNT_LWING2_e=0x4,
    DR_JNT_LWING3_e=0x5,
    DR_JNT_LWING4_e=0x6,
    DR_JNT_LWING5_e=0x7,
    DR_JNT_LWING6_e=0x8,
    DR_JNT_RWING1_e=0x9,
    DR_JNT_RWING2_e=0xA,
    DR_JNT_RWING3_e=0xB,
    DR_JNT_RWING4_e=0xC,
    DR_JNT_RWING5_e=0xD,
    DR_JNT_RWING6_e=0xE,
    DR_JNT_CROW_BACK_LOC_e=0xF,
    DR_JNT_NECK1_e=0x10,
    DR_JNT_NECK2_e=0x11,
    DR_JNT_NECK3_e=0x12,
    DR_JNT_HEAD_e=0x13,
    DR_JNT_JAW_e=0x14,
    DR_JNT_TONGUE1_e=0x15,
    DR_JNT_TONGUE2_e=0x16,
    DR_JNT_TONGUE3_e=0x17,
    DR_JNT_TONGUEL1_e=0x18,
    DR_JNT_TONGUER1_e=0x19,
    DR_JNT_WAIST_e=0x1A,
    DR_JNT_LLEG1_e=0x1B,
    DR_JNT_LLEG2_e=0x1C,
    DR_JNT_LLEG3_e=0x1D,
    DR_JNT_LANKLE_e=0x1E,
    DR_JNT_LFINGERA_e=0x1F,
    DR_JNT_LFINGERB_e=0x20,
    DR_JNT_LFINGERC_e=0x21,
    DR_JNT_LFINGERD_e=0x22,
    DR_JNT_RLEG1_e=0x23,
    DR_JNT_RLEG2_e=0x24,
    DR_JNT_RLEG3_e=0x25,
    DR_JNT_RANKLE_e=0x26,
    DR_JNT_RFINGERA_e=0x27,
    DR_JNT_RFINGERB_e=0x28,
    DR_JNT_RFINGERC_e=0x29,
    DR_JNT_RFINGERD_e=0x2A,
    DR_JNT_TAIL1_e=0x2B,
    DR_JNT_TAIL2_e=0x2C,
    DR_JNT_TAIL3_e=0x2D,
    DR_JNT_TAIL4_e=0x2E,
    DR_JNT_TAIL5_e=0x2F,
    DR_JNT_TAIL6_e=0x30,
    DR_JNT_CROW_TAIL_LOC_e=0x31,
};

#endif /* !RES_LV7GATE_H */