#ifndef RES_SCANTEN_H
#define RES_SCANTEN_H

enum dRes_INDEX_SCANTEN {
    /* BCK  */
    dRes_INDEX_SCANTEN_BCK_U_SKYCANNON_LV7_e=0x6,
    /* BMDR */
    dRes_INDEX_SCANTEN_BMD_U_SKYCANNON_LV7_e=0x9,
    /* DZB  */
    dRes_INDEX_SCANTEN_DZB_U_SKYCANNON_LV7_e=0xC,
    /* EVT  */
    dRes_INDEX_SCANTEN_DAT_EVENT_LIST_e=0xF,
};

enum dRes_ID_SCANTEN {
    /* BCK  */
    dRes_ID_SCANTEN_BCK_U_SKYCANNON_LV7_e=0x6,
    /* BMDR */
    dRes_ID_SCANTEN_BMD_U_SKYCANNON_LV7_e=0x9,
    /* DZB  */
    dRes_ID_SCANTEN_DZB_U_SKYCANNON_LV7_e=0xC,
    /* EVT  */
    dRes_ID_SCANTEN_DAT_EVENT_LIST_e=0xF,
};

enum U_SKYCANNON_LV7_JNT {
    U_SKYCANNON_LV7_JNT_WAIST_e=0x0,
    U_SKYCANNON_LV7_JNT_L_HIPJ_e=0x1,
    U_SKYCANNON_LV7_JNT_L_KNEE_e=0x2,
    U_SKYCANNON_LV7_JNT_L_HEEL_e=0x3,
    U_SKYCANNON_LV7_JNT_LB_FINGER_e=0x4,
    U_SKYCANNON_LV7_JNT_LF_FINGER_e=0x5,
    U_SKYCANNON_LV7_JNT_R_HIPJ_e=0x6,
    U_SKYCANNON_LV7_JNT_R_KNEE_e=0x7,
    U_SKYCANNON_LV7_JNT_R_HEEL_e=0x8,
    U_SKYCANNON_LV7_JNT_RB_FINGER_e=0x9,
    U_SKYCANNON_LV7_JNT_RF_FINGER_e=0xA,
    U_SKYCANNON_LV7_JNT_NECK_e=0xB,
    U_SKYCANNON_LV7_JNT_HEAD_e=0xC,
};

#endif /* !RES_SCANTEN_H */