// 
// Generated By: dol2asm
// Translation Unit: d_a_npc_myna2
// 

#include "dol2asm.h"
#include "dolphin/types.h"
#include "rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2.h"

// 
// Types:
// 

struct request_of_phase_process_class {
};

struct Vec {
};

struct cXyz {
	/* 80266B34 */ void operator-(Vec const&) const;
	/* 80266F48 */ void normalizeZP();
	/* 80A87BBC */ ~cXyz();
	/* 80A87BF8 */ cXyz();
};

struct mDoMtx_stack_c {
	/* 8000CD64 */ void transS(cXyz const&);
};

struct mDoExt_McaMorfCallBack2_c {
};

struct J3DAnmTransform {
};

struct J3DModelData {
};

struct mDoExt_McaMorfCallBack1_c {
};

struct Z2Creature {
	/* 802C0420 */ ~Z2Creature();
	/* 802C0530 */ void init(Vec*, Vec*, u8, u8);
};

struct mDoExt_McaMorfSO {
	/* 800107D0 */ mDoExt_McaMorfSO(J3DModelData*, mDoExt_McaMorfCallBack1_c*, mDoExt_McaMorfCallBack2_c*, J3DAnmTransform*, int, f32, int, int, Z2Creature*, u32, u32);
	/* 80011310 */ void stopZelAnime();
};

struct fopAc_ac_c {
	/* 80018B64 */ fopAc_ac_c();
	/* 80018C8C */ ~fopAc_ac_c();
};

struct daNpc_myna2_c {
	/* 80A83E8C */ daNpc_myna2_c();
	/* 80A840A0 */ ~daNpc_myna2_c();
	/* 80A842C8 */ void create();
	/* 80A845AC */ void CreateHeap();
	/* 80A846E0 */ void Delete();
	/* 80A84714 */ void Execute();
	/* 80A84734 */ void Draw();
	/* 80A847A8 */ void createHeapCallBack(fopAc_ac_c*);
	/* 80A847C8 */ void setParam();
	/* 80A848B4 */ void main();
	/* 80A84B64 */ void setAttnPos();
	/* 80A84DAC */ void setExpressionBtp(int);
	/* 80A84EAC */ void setMotionAnm(int, f32);
	/* 80A84FEC */ void setMotion(int, f32, int);
	/* 80A85030 */ bool drawDbgInfo();
	/* 80A85038 */ void drawOtherMdls();
	/* 80A8503C */ void getTypeFromParam();
	/* 80A85094 */ void isDelete();
	/* 80A85160 */ void reset();
	/* 80A85358 */ void playMotion();
	/* 80A855E8 */ void chkAction(int (daNpc_myna2_c::*)(void*));
	/* 80A85614 */ void setAction(int (daNpc_myna2_c::*)(void*));
	/* 80A856BC */ void selectAction();
	/* 80A857B0 */ void doNormalAction(int);
	/* 80A85894 */ void doEvent();
	/* 80A85BA4 */ void setLookMode(int);
	/* 80A85BC8 */ void wait(void*);
	/* 80A85C60 */ void waitHovering(void*);
	/* 80A86194 */ void waitFailure(void*);
	/* 80A862BC */ void waitGoal(void*);
	/* 80A86400 */ void talk(void*);
	/* 80A865FC */ void test(void*);
	/* 80A866B0 */ void ECut_firstTalk(int);
	/* 80A8684C */ void ECut_gameFailure(int);
	/* 80A86A0C */ void ECut_gameGoal(int);
	/* 80A86BEC */ void ECut_gameGoalSuccess(int);
	/* 80A86E8C */ void calcHovering(int, int);
};

struct daNpc_myna2_Param_c {
	/* 80A883C8 */ ~daNpc_myna2_Param_c();
};

struct _GXColorS10 {
};

struct J3DAnmTexPattern {
};

struct dCcD_GObjInf {
	/* 80083A28 */ dCcD_GObjInf();
	/* 800840E4 */ ~dCcD_GObjInf();
	/* 80084658 */ void ChkCoHit();
};

struct J3DAnmTransformKey {
};

struct dCcD_SrcCyl {
};

struct dCcD_Cyl {
	/* 800848B4 */ void Set(dCcD_SrcCyl const&);
};

struct daNpcF_c {
	struct daNpcF_anmPlayData {
	};

	/* 80152014 */ void execute();
	/* 801522AC */ void draw(int, int, f32, _GXColorS10*, int);
	/* 80152614 */ void tgHitCallBack(fopAc_ac_c*, dCcD_GObjInf*, fopAc_ac_c*, dCcD_GObjInf*);
	/* 8015276C */ void setMtx();
	/* 801527FC */ void setMtx2();
	/* 801528C8 */ void initialize();
	/* 80152B2C */ void getTrnsfrmKeyAnmP(char*, int);
	/* 80152B68 */ void getTexPtrnAnmP(char*, int);
	/* 80152C1C */ void setMcaMorfAnm(J3DAnmTransformKey*, f32, f32, int, int, int);
	/* 80152CC4 */ void setBtpAnm(J3DAnmTexPattern*, J3DModelData*, f32, int);
	/* 80152D84 */ void setEnvTevColor();
	/* 80152DE0 */ void setRoomNo();
	/* 80153264 */ void playMotionAnm(daNpcF_c::daNpcF_anmPlayData***);
	/* 80153578 */ void hitChk2(dCcD_Cyl*, int, int);
	/* 80153718 */ void ctrlMsgAnm(int&, int&, fopAc_ac_c*, int);
	/* 8015387C */ void orderEvent(int, char*, u16, u16, u8, u16);
	/* 80153D1C */ void initTalk(int, fopAc_ac_c**);
	/* 80153D84 */ void talkProc(int*, int, fopAc_ac_c**);
	/* 801540A4 */ void step(s16, int, int, int);
	/* 80A87BFC */ ~daNpcF_c();
	/* 80A87E48 */ daNpcF_c();
	/* 80A881BC */ bool ctrlBtk();
	/* 80A881C4 */ void adjustShapeAngle();
	/* 80A881C8 */ void setCollisions();
	/* 80A881CC */ bool setExpressionAnm(int, bool);
	/* 80A881D4 */ void setExpression(int, f32);
};

struct daNpcF_Lookat_c {
	/* 80151038 */ void initialize();
	/* 80A87AAC */ ~daNpcF_Lookat_c();
};

struct daNpcF_ActorMngr_c {
	/* 801506B0 */ void initialize();
	/* 801506BC */ void entry(fopAc_ac_c*);
	/* 80A87A28 */ ~daNpcF_ActorMngr_c();
	/* 80A87A70 */ daNpcF_ActorMngr_c();
};

struct dSv_info_c {
	/* 80035200 */ void onSwitch(int, int);
	/* 800352B0 */ void offSwitch(int, int);
	/* 80035360 */ void isSwitch(int, int) const;
};

struct dRes_info_c {
};

struct dRes_control_c {
	/* 8003C2EC */ void getRes(char const*, s32, dRes_info_c*, int);
};

struct dMsgFlow_c {
	/* 80249F00 */ dMsgFlow_c();
	/* 80249F48 */ ~dMsgFlow_c();
	/* 8024A528 */ void getEventId(int*);
};

struct dEvt_control_c {
	/* 80042468 */ void reset();
	/* 800436EC */ void setPtI_Id(unsigned int);
};

struct dEvent_manager_c {
	/* 80047A78 */ void endCheck(s16);
	/* 80047B1C */ void getMyStaffId(char const*, fopAc_ac_c*, int);
	/* 80047D4C */ void getIsAddvance(int);
	/* 80047E10 */ void getMyActIdx(int, char const* const*, int, int, int);
	/* 800480EC */ void getMySubstanceP(int, char const*, int);
	/* 8004817C */ void cutEnd(int);
	/* 800487F0 */ void ChkPresentEnd();
};

struct dCcD_Stts {
	/* 80083860 */ void Init(int, int, fopAc_ac_c*);
};

struct dCcD_GStts {
	/* 80083760 */ dCcD_GStts();
	/* 80A880A8 */ ~dCcD_GStts();
};

struct dBgS_PolyPassChk {
	/* 80078E68 */ void SetObj();
};

struct dBgS_ObjAcch {
	/* 80A88104 */ ~dBgS_ObjAcch();
};

struct dBgS_LinChk {
	/* 80077C68 */ dBgS_LinChk();
	/* 80077CDC */ ~dBgS_LinChk();
};

struct dBgS_GndChk {
	/* 8007757C */ dBgS_GndChk();
	/* 800775F0 */ ~dBgS_GndChk();
};

struct dBgS_AcchCir {
	/* 80075EAC */ dBgS_AcchCir();
	/* 80075F40 */ void SetWallR(f32);
	/* 80075F58 */ void SetWall(f32, f32);
	/* 80A88038 */ ~dBgS_AcchCir();
};

struct csXyz {
	/* 80A87B7C */ ~csXyz();
	/* 80A87BB8 */ csXyz();
};

struct dBgS {
};

struct dBgS_Acch {
	/* 80075F94 */ ~dBgS_Acch();
	/* 800760A0 */ dBgS_Acch();
	/* 80076248 */ void Set(cXyz*, cXyz*, fopAc_ac_c*, int, dBgS_AcchCir*, cXyz*, csXyz*, csXyz*);
	/* 80076AAC */ void CrrPos(dBgS&);
};

struct cM3dGCyl {
	/* 8026F1DC */ void SetC(cXyz const&);
	/* 8026F1F8 */ void SetH(f32);
	/* 8026F200 */ void SetR(f32);
	/* 80A84010 */ ~cM3dGCyl();
};

struct cM3dGCir {
	/* 8026EF18 */ ~cM3dGCir();
};

struct cM3dGAab {
	/* 80A84058 */ ~cM3dGAab();
};

struct cCcD_Obj {
};

struct cCcS {
	/* 80264BA8 */ void Set(cCcD_Obj*);
};

struct cCcD_GStts {
	/* 80A881D8 */ ~cCcD_GStts();
};

struct cBgS_PolyInfo {
	/* 802680B0 */ ~cBgS_PolyInfo();
};

struct cBgS_GndChk {
	/* 80267C1C */ cBgS_GndChk();
	/* 80267C94 */ ~cBgS_GndChk();
};

struct Z2CreatureSumomo {
	/* 802C1BE8 */ Z2CreatureSumomo();
	/* 802C1C24 */ void playSumomoBgm(u32);
};

struct J3DFrameCtrl {
	/* 803283FC */ void init(s16);
	/* 80A88174 */ ~J3DFrameCtrl();
};

// 
// Forward References:
// 

static void s_sub(void*, void*);
static void daNpc_myna2_Create(void*);
static void daNpc_myna2_Delete(void*);
static void daNpc_myna2_Execute(void*);
static void daNpc_myna2_Draw(void*);
static bool daNpc_myna2_IsDelete(void*);
static void cLib_calcTimer__template0(int*);
static void cLib_getRndValue__template0(f32, f32);
static void cLib_getRndValue__template1(int, int);
extern "C" extern u8 const lit_4831[32];
extern "C" extern u32 lit_1787[1 + 4 /* padding */];
extern "C" extern void* g_profile_MYNA2[12];
extern "C" extern u8 lit_1107[1 + 3 /* padding */];
extern "C" extern u8 lit_1105[1 + 3 /* padding */];
extern "C" extern u8 lit_1104[1 + 3 /* padding */];
extern "C" extern u8 lit_1099[1 + 3 /* padding */];
extern "C" extern u8 lit_1097[1 + 3 /* padding */];
extern "C" extern u8 lit_1095[1 + 3 /* padding */];
extern "C" extern u8 lit_1094[1 + 3 /* padding */];
extern "C" extern u8 lit_1057[1 + 3 /* padding */];
extern "C" extern u8 lit_1055[1 + 3 /* padding */];
extern "C" extern u8 lit_1053[1 + 3 /* padding */];
extern "C" extern u8 lit_1052[1 + 3 /* padding */];
extern "C" extern u8 lit_1014[1 + 3 /* padding */];
extern "C" extern u8 lit_1012[1 + 3 /* padding */];
extern "C" extern u8 lit_1010[1 + 3 /* padding */];
extern "C" extern u8 lit_1009[1 + 3 /* padding */];
extern "C" extern u8 data_80A88B64[4];
extern "C" extern u8 data_80A88B68[4];
extern "C" extern u8 data_80A88B6C[4];
extern "C" extern u8 data_80A88B70[4];
extern "C" extern u8 data_80A88B74[4];
extern "C" extern u8 data_80A88B78[4];
extern "C" extern u8 data_80A88B7C[4];
extern "C" extern u8 data_80A88B80[4];
extern "C" extern u8 data_80A88B84[4];
extern "C" extern u8 data_80A88B88[4];
extern "C" extern u8 data_80A88B8C[4];
extern "C" extern u8 data_80A88B90[4];
extern "C" extern u8 data_80A88B94[4];
extern "C" extern u8 data_80A88B98[4];
extern "C" extern u8 data_80A88B9C[4];
extern "C" extern u8 data_80A88BA0[4];
extern "C" extern u8 data_80A88BA4[4];
extern "C" extern u8 data_80A88BA8[4];
extern "C" extern u8 data_80A88BAC[4];
extern "C" extern u8 data_80A88BB0[4];
extern "C" extern u8 data_80A88BB4[4];
extern "C" extern u8 data_80A88BB8[4];
extern "C" extern u8 data_80A88BBC[4];
extern "C" extern u8 data_80A88BC0[4];
extern "C" extern u8 data_80A88BC4[4];

extern "C" void __ct__13daNpc_myna2_cFv();
extern "C" void __dt__8cM3dGCylFv();
extern "C" void __dt__8cM3dGAabFv();
extern "C" void __dt__13daNpc_myna2_cFv();
extern "C" void create__13daNpc_myna2_cFv();
extern "C" void CreateHeap__13daNpc_myna2_cFv();
extern "C" void Delete__13daNpc_myna2_cFv();
extern "C" void Execute__13daNpc_myna2_cFv();
extern "C" void Draw__13daNpc_myna2_cFv();
extern "C" void createHeapCallBack__13daNpc_myna2_cFP10fopAc_ac_c();
extern "C" void setParam__13daNpc_myna2_cFv();
extern "C" void main__13daNpc_myna2_cFv();
extern "C" void setAttnPos__13daNpc_myna2_cFv();
extern "C" void setExpressionBtp__13daNpc_myna2_cFi();
extern "C" void setMotionAnm__13daNpc_myna2_cFif();
extern "C" void setMotion__13daNpc_myna2_cFifi();
extern "C" bool drawDbgInfo__13daNpc_myna2_cFv();
extern "C" void drawOtherMdls__13daNpc_myna2_cFv();
extern "C" void getTypeFromParam__13daNpc_myna2_cFv();
extern "C" void isDelete__13daNpc_myna2_cFv();
extern "C" void reset__13daNpc_myna2_cFv();
extern "C" void playMotion__13daNpc_myna2_cFv();
extern "C" void chkAction__13daNpc_myna2_cFM13daNpc_myna2_cFPCvPvPv_i();
extern "C" void setAction__13daNpc_myna2_cFM13daNpc_myna2_cFPCvPvPv_i();
extern "C" void selectAction__13daNpc_myna2_cFv();
extern "C" void doNormalAction__13daNpc_myna2_cFi();
extern "C" void doEvent__13daNpc_myna2_cFv();
extern "C" void setLookMode__13daNpc_myna2_cFi();
extern "C" void wait__13daNpc_myna2_cFPv();
extern "C" void waitHovering__13daNpc_myna2_cFPv();
extern "C" static void s_sub__FPvPv();
extern "C" void waitFailure__13daNpc_myna2_cFPv();
extern "C" void waitGoal__13daNpc_myna2_cFPv();
extern "C" void talk__13daNpc_myna2_cFPv();
extern "C" void test__13daNpc_myna2_cFPv();
extern "C" void ECut_firstTalk__13daNpc_myna2_cFi();
extern "C" void ECut_gameFailure__13daNpc_myna2_cFi();
extern "C" void ECut_gameGoal__13daNpc_myna2_cFi();
extern "C" void ECut_gameGoalSuccess__13daNpc_myna2_cFi();
extern "C" void calcHovering__13daNpc_myna2_cFii();
extern "C" static void daNpc_myna2_Create__FPv();
extern "C" static void daNpc_myna2_Delete__FPv();
extern "C" static void daNpc_myna2_Execute__FPv();
extern "C" static void daNpc_myna2_Draw__FPv();
extern "C" static bool daNpc_myna2_IsDelete__FPv();
extern "C" void __dt__18daNpcF_ActorMngr_cFv();
extern "C" void __ct__18daNpcF_ActorMngr_cFv();
extern "C" void __dt__15daNpcF_Lookat_cFv();
extern "C" void __dt__5csXyzFv();
extern "C" void __ct__5csXyzFv();
extern "C" void __dt__4cXyzFv();
extern "C" void __ct__4cXyzFv();
extern "C" void __dt__8daNpcF_cFv();
extern "C" void __ct__8daNpcF_cFv();
extern "C" void __dt__12dBgS_AcchCirFv();
extern "C" void __dt__10dCcD_GSttsFv();
extern "C" void __dt__12dBgS_ObjAcchFv();
extern "C" void __dt__12J3DFrameCtrlFv();
extern "C" bool ctrlBtk__8daNpcF_cFv();
extern "C" void adjustShapeAngle__8daNpcF_cFv();
extern "C" void setCollisions__8daNpcF_cFv();
extern "C" bool setExpressionAnm__8daNpcF_cFib();
extern "C" void setExpression__8daNpcF_cFif();
extern "C" void __dt__10cCcD_GSttsFv();
extern "C" static void func_80A88220();
extern "C" static void func_80A8823C();
extern "C" static void func_80A88278();
extern "C" void __sinit_d_a_npc_myna2_cpp();
extern "C" void __dt__19daNpc_myna2_Param_cFv();
extern "C" static void func_80A88410();
extern "C" static void func_80A88418();
extern "C" extern u8 const lit_4831[32];
extern "C" extern u32 lit_1787[1 + 4 /* padding */];
extern "C" extern void* g_profile_MYNA2[12];
extern "C" extern u8 lit_1107[1 + 3 /* padding */];
extern "C" extern u8 lit_1105[1 + 3 /* padding */];
extern "C" extern u8 lit_1104[1 + 3 /* padding */];
extern "C" extern u8 lit_1099[1 + 3 /* padding */];
extern "C" extern u8 lit_1097[1 + 3 /* padding */];
extern "C" extern u8 lit_1095[1 + 3 /* padding */];
extern "C" extern u8 lit_1094[1 + 3 /* padding */];
extern "C" extern u8 lit_1057[1 + 3 /* padding */];
extern "C" extern u8 lit_1055[1 + 3 /* padding */];
extern "C" extern u8 lit_1053[1 + 3 /* padding */];
extern "C" extern u8 lit_1052[1 + 3 /* padding */];
extern "C" extern u8 lit_1014[1 + 3 /* padding */];
extern "C" extern u8 lit_1012[1 + 3 /* padding */];
extern "C" extern u8 lit_1010[1 + 3 /* padding */];
extern "C" extern u8 lit_1009[1 + 3 /* padding */];
extern "C" extern u8 data_80A88B64[4];
extern "C" extern u8 data_80A88B68[4];
extern "C" extern u8 data_80A88B6C[4];
extern "C" extern u8 data_80A88B70[4];
extern "C" extern u8 data_80A88B74[4];
extern "C" extern u8 data_80A88B78[4];
extern "C" extern u8 data_80A88B7C[4];
extern "C" extern u8 data_80A88B80[4];
extern "C" extern u8 data_80A88B84[4];
extern "C" extern u8 data_80A88B88[4];
extern "C" extern u8 data_80A88B8C[4];
extern "C" extern u8 data_80A88B90[4];
extern "C" extern u8 data_80A88B94[4];
extern "C" extern u8 data_80A88B98[4];
extern "C" extern u8 data_80A88B9C[4];
extern "C" extern u8 data_80A88BA0[4];
extern "C" extern u8 data_80A88BA4[4];
extern "C" extern u8 data_80A88BA8[4];
extern "C" extern u8 data_80A88BAC[4];
extern "C" extern u8 data_80A88BB0[4];
extern "C" extern u8 data_80A88BB4[4];
extern "C" extern u8 data_80A88BB8[4];
extern "C" extern u8 data_80A88BBC[4];
extern "C" extern u8 data_80A88BC0[4];
extern "C" extern u8 data_80A88BC4[4];

// 
// External References:
// 

void mDoMtx_ZXYrotM(f32 (* )[4], s16, s16, s16);
void fopAc_IsActor(void*);
void fopAcM_delete(fopAc_ac_c*);
void fopAcM_entrySolidHeap(fopAc_ac_c*, int (*)(fopAc_ac_c*), u32);
void fopAcM_setCullSizeBox(fopAc_ac_c*, f32, f32, f32, f32, f32, f32);
void fopAcM_posMoveF(fopAc_ac_c*, cXyz const*);
void fopAcM_searchActorAngleY(fopAc_ac_c const*, fopAc_ac_c const*);
void fopAcM_createItemForPresentDemo(cXyz const*, int, u8, int, int, csXyz const*, cXyz const*);
void fpcEx_Search(void* (*)(void*, void*), void*);
void dStage_changeScene(int, f32, u32, s8, s16, int);
void dComIfG_resLoad(request_of_phase_process_class*, char const*);
void dComIfG_resDelete(request_of_phase_process_class*, char const*);
void dComIfGp_getReverb(int);
void dComIfGs_wolfeye_effect_check();
void daNpcF_getGroundAngle(cBgS_PolyInfo*, s16);
void daNpcF_chkEvtBit(u32);
void daNpcF_onTmpBit(u32);
void daNpcF_offTmpBit(u32);
void dKy_pol_sound_get(cBgS_PolyInfo const*);
void cM_atan2s(f32, f32);
void cM_rndF(f32);
void cLib_addCalcPos2(cXyz*, cXyz const&, f32, f32);
void cLib_addCalcAngleS2(s16*, s16, s16, s16);
void cLib_targetAngleY(Vec const*, Vec const*);
void cLib_targetAngleX(cXyz const*, cXyz const*);
void* operator new(u32);
void operator delete(void*);
extern "C" extern u8 const __ptmf_null[12 + 4 /* padding */];
extern "C" extern void* g_fopAc_Method[8];
extern "C" extern void* g_fpcLf_Method[5 + 1 /* padding */];
extern "C" extern void* __vt__8dCcD_Cyl[36];
extern "C" extern void* __vt__9dCcD_Stts[11];
extern "C" extern u8 mCcDCyl__8daNpcF_c[68];
extern "C" extern void* __vt__8daNpcF_c[18];
extern "C" extern void* __vt__12cCcD_CylAttr[25];
extern "C" extern void* __vt__14cCcD_ShapeAttr[22];
extern "C" extern void* __vt__9cCcD_Stts[8];
extern "C" extern void* __vt__16Z2CreatureSumomo[12];
extern "C" extern u8 now__14mDoMtx_stack_c[48];
extern "C" extern u8 g_dComIfG_gameInfo[122384];
extern "C" extern u8 sincosTable___5JMath[65536];
extern "C" extern u32 __float_nan;

extern "C" void mDoMtx_ZXYrotM__FPA4_fsss();
extern "C" void transS__14mDoMtx_stack_cFRC4cXyz();
extern "C" void __ct__16mDoExt_McaMorfSOFP12J3DModelDataP25mDoExt_McaMorfCallBack1_cP25mDoExt_McaMorfCallBack2_cP15J3DAnmTransformifiiP10Z2CreatureUlUl();
extern "C" void stopZelAnime__16mDoExt_McaMorfSOFv();
extern "C" void __ct__10fopAc_ac_cFv();
extern "C" void __dt__10fopAc_ac_cFv();
extern "C" void fopAc_IsActor__FPv();
extern "C" void fopAcM_delete__FP10fopAc_ac_c();
extern "C" void fopAcM_entrySolidHeap__FP10fopAc_ac_cPFP10fopAc_ac_c_iUl();
extern "C" void fopAcM_setCullSizeBox__FP10fopAc_ac_cffffff();
extern "C" void fopAcM_posMoveF__FP10fopAc_ac_cPC4cXyz();
extern "C" void fopAcM_searchActorAngleY__FPC10fopAc_ac_cPC10fopAc_ac_c();
extern "C" void fopAcM_createItemForPresentDemo__FPC4cXyziUciiPC5csXyzPC4cXyz();
extern "C" void fpcEx_Search__FPFPvPv_PvPv();
extern "C" void dStage_changeScene__FifUlScsi();
extern "C" void dComIfG_resLoad__FP30request_of_phase_process_classPCc();
extern "C" void dComIfG_resDelete__FP30request_of_phase_process_classPCc();
extern "C" void dComIfGp_getReverb__Fi();
extern "C" void dComIfGs_wolfeye_effect_check__Fv();
extern "C" void onSwitch__10dSv_info_cFii();
extern "C" void offSwitch__10dSv_info_cFii();
extern "C" void isSwitch__10dSv_info_cCFii();
extern "C" void getRes__14dRes_control_cFPCclP11dRes_info_ci();
extern "C" void reset__14dEvt_control_cFv();
extern "C" void setPtI_Id__14dEvt_control_cFUi();
extern "C" void endCheck__16dEvent_manager_cFs();
extern "C" void getMyStaffId__16dEvent_manager_cFPCcP10fopAc_ac_ci();
extern "C" void getIsAddvance__16dEvent_manager_cFi();
extern "C" void getMyActIdx__16dEvent_manager_cFiPCPCciii();
extern "C" void getMySubstanceP__16dEvent_manager_cFiPCci();
extern "C" void cutEnd__16dEvent_manager_cFi();
extern "C" void ChkPresentEnd__16dEvent_manager_cFv();
extern "C" void __ct__12dBgS_AcchCirFv();
extern "C" void SetWallR__12dBgS_AcchCirFf();
extern "C" void SetWall__12dBgS_AcchCirFff();
extern "C" void __dt__9dBgS_AcchFv();
extern "C" void __ct__9dBgS_AcchFv();
extern "C" void Set__9dBgS_AcchFP4cXyzP4cXyzP10fopAc_ac_ciP12dBgS_AcchCirP4cXyzP5csXyzP5csXyz();
extern "C" void CrrPos__9dBgS_AcchFR4dBgS();
extern "C" void __ct__11dBgS_GndChkFv();
extern "C" void __dt__11dBgS_GndChkFv();
extern "C" void __ct__11dBgS_LinChkFv();
extern "C" void __dt__11dBgS_LinChkFv();
extern "C" void SetObj__16dBgS_PolyPassChkFv();
extern "C" void __ct__10dCcD_GSttsFv();
extern "C" void Init__9dCcD_SttsFiiP10fopAc_ac_c();
extern "C" void __ct__12dCcD_GObjInfFv();
extern "C" void __dt__12dCcD_GObjInfFv();
extern "C" void ChkCoHit__12dCcD_GObjInfFv();
extern "C" void Set__8dCcD_CylFRC11dCcD_SrcCyl();
extern "C" void initialize__18daNpcF_ActorMngr_cFv();
extern "C" void entry__18daNpcF_ActorMngr_cFP10fopAc_ac_c();
extern "C" void initialize__15daNpcF_Lookat_cFv();
extern "C" void execute__8daNpcF_cFv();
extern "C" void draw__8daNpcF_cFiifP11_GXColorS10i();
extern "C" void tgHitCallBack__8daNpcF_cFP10fopAc_ac_cP12dCcD_GObjInfP10fopAc_ac_cP12dCcD_GObjInf();
extern "C" void setMtx__8daNpcF_cFv();
extern "C" void setMtx2__8daNpcF_cFv();
extern "C" void initialize__8daNpcF_cFv();
extern "C" void getTrnsfrmKeyAnmP__8daNpcF_cFPci();
extern "C" void getTexPtrnAnmP__8daNpcF_cFPci();
extern "C" void setMcaMorfAnm__8daNpcF_cFP18J3DAnmTransformKeyffiii();
extern "C" void setBtpAnm__8daNpcF_cFP16J3DAnmTexPatternP12J3DModelDatafi();
extern "C" void setEnvTevColor__8daNpcF_cFv();
extern "C" void setRoomNo__8daNpcF_cFv();
extern "C" void playMotionAnm__8daNpcF_cFPPPQ28daNpcF_c18daNpcF_anmPlayData();
extern "C" void hitChk2__8daNpcF_cFP8dCcD_Cylii();
extern "C" void ctrlMsgAnm__8daNpcF_cFRiRiP10fopAc_ac_ci();
extern "C" void orderEvent__8daNpcF_cFiPcUsUsUcUs();
extern "C" void initTalk__8daNpcF_cFiPP10fopAc_ac_c();
extern "C" void talkProc__8daNpcF_cFPiiPP10fopAc_ac_c();
extern "C" void step__8daNpcF_cFsiii();
extern "C" void daNpcF_getGroundAngle__FP13cBgS_PolyInfos();
extern "C" void daNpcF_chkEvtBit__FUl();
extern "C" void daNpcF_onTmpBit__FUl();
extern "C" void daNpcF_offTmpBit__FUl();
extern "C" void dKy_pol_sound_get__FPC13cBgS_PolyInfo();
extern "C" void __ct__10dMsgFlow_cFv();
extern "C" void __dt__10dMsgFlow_cFv();
extern "C" void getEventId__10dMsgFlow_cFPi();
extern "C" void Set__4cCcSFP8cCcD_Obj();
extern "C" void __mi__4cXyzCFRC3Vec();
extern "C" void normalizeZP__4cXyzFv();
extern "C" void cM_atan2s__Fff();
extern "C" void cM_rndF__Ff();
extern "C" void __ct__11cBgS_GndChkFv();
extern "C" void __dt__11cBgS_GndChkFv();
extern "C" void __dt__13cBgS_PolyInfoFv();
extern "C" void __dt__8cM3dGCirFv();
extern "C" void SetC__8cM3dGCylFRC4cXyz();
extern "C" void SetH__8cM3dGCylFf();
extern "C" void SetR__8cM3dGCylFf();
extern "C" void cLib_addCalcPos2__FP4cXyzRC4cXyzff();
extern "C" void cLib_addCalcAngleS2__FPssss();
extern "C" void cLib_targetAngleY__FPC3VecPC3Vec();
extern "C" void cLib_targetAngleX__FPC4cXyzPC4cXyz();
extern "C" void __dt__10Z2CreatureFv();
extern "C" void init__10Z2CreatureFP3VecP3VecUcUc();
extern "C" void __ct__16Z2CreatureSumomoFv();
extern "C" void playSumomoBgm__16Z2CreatureSumomoFUl();
extern "C" void* __nw__FUl();
extern "C" void __dl__FPv();
extern "C" void init__12J3DFrameCtrlFs();
extern "C" void PSMTXCopy();
extern "C" void PSMTXMultVec();
extern "C" void PSVECAdd();
extern "C" void PSVECScale();
extern "C" void PSVECSquareMag();
extern "C" void __destroy_arr();
extern "C" void __construct_array();
extern "C" void __ptmf_test();
extern "C" void __ptmf_cmpr();
extern "C" void __ptmf_scall();
extern "C" void __cvt_fp2unsigned();
extern "C" void _savegpr_24();
extern "C" void _savegpr_26();
extern "C" void _savegpr_27();
extern "C" void _savegpr_28();
extern "C" void _savegpr_29();
extern "C" void _restgpr_24();
extern "C" void _restgpr_26();
extern "C" void _restgpr_27();
extern "C" void _restgpr_28();
extern "C" void _restgpr_29();
extern "C" void strcmp();
extern "C" extern u8 const __ptmf_null[12 + 4 /* padding */];
extern "C" extern void* g_fopAc_Method[8];
extern "C" extern void* g_fpcLf_Method[5 + 1 /* padding */];
extern "C" extern void* __vt__8dCcD_Cyl[36];
extern "C" extern void* __vt__9dCcD_Stts[11];
extern "C" extern u8 mCcDCyl__8daNpcF_c[68];
extern "C" extern void* __vt__8daNpcF_c[18];
extern "C" extern void* __vt__12cCcD_CylAttr[25];
extern "C" extern void* __vt__14cCcD_ShapeAttr[22];
extern "C" extern void* __vt__9cCcD_Stts[8];
extern "C" extern void* __vt__16Z2CreatureSumomo[12];
extern "C" extern u8 now__14mDoMtx_stack_c[48];
extern "C" extern u8 g_dComIfG_gameInfo[122384];
extern "C" extern u8 sincosTable___5JMath[65536];
extern "C" extern u32 __float_nan;
extern "C" void __register_global_object();

// 
// Declarations:
// 

/* ############################################################################################## */
/* 80A88434-80A884A8 0074+00 s=14 e=0 z=0  None .rodata    m__19daNpc_myna2_Param_c                                     */
SECTION_RODATA static u8 const m__19daNpc_myna2_Param_c[116] = {
	0x42, 0x70, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3F, 0x80, 0x00, 0x00, 0x44, 0x16, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x42, 0x48, 0x00, 0x00, 0x42, 0x0C, 0x00, 0x00, 0x42, 0x20, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x41, 0x40, 0x00, 0x00, 0x00, 0x03, 0x00, 0x06, 0x00, 0x05, 0x00, 0x06,
	0x43, 0x34, 0x00, 0x00, 0x43, 0xFA, 0x00, 0x00, 0x43, 0x96, 0x00, 0x00, 0xC3, 0x96, 0x00, 0x00,
	0x00, 0x3C, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x44, 0x2F, 0x00, 0x00,
	0x45, 0x1C, 0x40, 0x00,
};

/* 80A884A8-80A884BC 0014+00 s=1 e=0 z=0  None .rodata    heapSize$4340                                                */
SECTION_RODATA static u8 const heapSize[20] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x24, 0x50, 0x00, 0x00, 0x24, 0x40, 0x00, 0x00, 0x24, 0x50,
	0x00, 0x00, 0x00, 0x00,
};

/* 80A884BC-80A884C0 0004+00 s=1 e=0 z=0  None .rodata    @4428                                                        */
SECTION_RODATA static u32 const lit_4428 = 0xC3960000;

/* 80A884C0-80A884C4 0004+00 s=1 e=0 z=0  None .rodata    @4429                                                        */
SECTION_RODATA static u32 const lit_4429 = 0xC2480000;

/* 80A884C4-80A884C8 0004+00 s=1 e=0 z=0  None .rodata    @4430                                                        */
SECTION_RODATA static u32 const lit_4430 = 0x43960000;

/* 80A884C8-80A884CC 0004+00 s=1 e=0 z=0  None .rodata    @4431                                                        */
SECTION_RODATA static u32 const lit_4431 = 0x43E10000;

/* 80A884CC-80A884D0 0004+00 s=5 e=0 z=0  None .rodata    @4462                                                        */
SECTION_RODATA static u32 const lit_4462 = 0x3F800000;

/* 80A884D0-80A884D4 0004+00 s=9 e=0 z=0  None .rodata    @4463                                                        */
SECTION_RODATA static u8 const lit_4463[4] = {
	0x00, 0x00, 0x00, 0x00,
};

/* 80A884D4-80A884D8 0004+00 s=1 e=0 z=0  None .rodata    @4577                                                        */
SECTION_RODATA static u32 const lit_4577 = 0x3E19999A;

/* 80A884D8-80A884DC 0004+00 s=1 e=0 z=0  None .rodata    @4578                                                        */
SECTION_RODATA static u32 const lit_4578 = 0xCE6E6B28;

/* 80A884DC-80A884E0 0004+00 s=1 e=0 z=0  None .rodata    @4644                                                        */
SECTION_RODATA static u32 const lit_4644 = 0x41F00000;

/* 80A884E0-80A884E4 0004+00 s=1 e=0 z=0  None .rodata    @4645                                                        */
SECTION_RODATA static u32 const lit_4645 = 0x41200000;

/* 80A884E4-80A884E8 0004+00 s=1 e=0 z=0  None .rodata    @4806                                                        */
SECTION_RODATA static u32 const lit_4806 = 0x453B8000;

/* 80A884E8-80A884EC 0004+00 s=1 e=0 z=0  None .rodata    @4807                                                        */
SECTION_RODATA static u32 const lit_4807 = 0x44FA0000;

/* 80A884EC-80A884F0 0004+00 s=2 e=0 z=0  None .rodata    @4808                                                        */
SECTION_RODATA static u32 const lit_4808 = 0x42480000;

/* 80A884F0-80A884FC 000C+00 s=1 e=0 z=0  None .rodata    @4812                                                        */
SECTION_RODATA static u8 const lit_4812[12] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80A884FC-80A88500 0004+00 s=1 e=0 z=0  None .rodata    @4813                                                        */
SECTION_RODATA static u8 const lit_4813[4] = {
	0x00, 0x00, 0x00, 0x00,
};

/* 80A88500-80A8850C 000C+00 s=1 e=0 z=0  None .rodata    @4814                                                        */
SECTION_RODATA static u8 const lit_4814[12] = {
	0x00, 0x0C, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80A8850C-80A88510 0004+00 s=1 e=0 z=0  None .rodata    @4815                                                        */
SECTION_RODATA static u8 const lit_4815[4] = {
	0x00, 0x00, 0x00, 0x00,
};

/* 80A88510-80A8851C 000C+00 s=1 e=0 z=0  None .rodata    @4816                                                        */
SECTION_RODATA static u8 const lit_4816[12] = {
	0x00, 0x0D, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80A8851C-80A88520 0004+00 s=1 e=0 z=0  None .rodata    @4817                                                        */
SECTION_RODATA static u8 const lit_4817[4] = {
	0x00, 0x00, 0x00, 0x00,
};

/* 80A88520-80A8852C 000C+00 s=1 e=0 z=0  None .rodata    @4818                                                        */
SECTION_RODATA static u8 const lit_4818[12] = {
	0x00, 0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
};

/* 80A8852C-80A88538 000C+00 s=1 e=0 z=0  None .rodata    @4819                                                        */
SECTION_RODATA static u8 const lit_4819[12] = {
	0x00, 0x0C, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80A88538-80A88540 0008+00 s=1 e=0 z=0  None .rodata    @4820                                                        */
SECTION_RODATA static u8 const lit_4820[8] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80A88540-80A8854C 000C+00 s=1 e=0 z=0  None .rodata    @4821                                                        */
SECTION_RODATA static u8 const lit_4821[12] = {
	0x00, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
};

/* 80A8854C-80A88558 000C+00 s=1 e=0 z=0  None .rodata    @4822                                                        */
SECTION_RODATA static u8 const lit_4822[12] = {
	0x00, 0x0D, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80A88558-80A88560 0008+00 s=1 e=0 z=0  None .rodata    @4823                                                        */
SECTION_RODATA static u8 const lit_4823[8] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80A88560-80A8856C 000C+00 s=1 e=0 z=0  None .rodata    @4824                                                        */
SECTION_RODATA static u8 const lit_4824[12] = {
	0x00, 0x0B, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
};

/* 80A8856C-80A88578 000C+00 s=1 e=0 z=0  None .rodata    @4825                                                        */
SECTION_RODATA static u8 const lit_4825[12] = {
	0x00, 0x0E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80A88578-80A88580 0008+00 s=1 e=0 z=0  None .rodata    @4826                                                        */
SECTION_RODATA static u8 const lit_4826[8] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80A88580-80A8858C 000C+00 s=1 e=0 z=0  None .rodata    @4827                                                        */
SECTION_RODATA static u8 const lit_4827[12] = {
	0x00, 0x0E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80A8858C-80A88590 0004+00 s=1 e=0 z=0  None .rodata    @4828                                                        */
SECTION_RODATA static u8 const lit_4828[4] = {
	0x00, 0x00, 0x00, 0x00,
};

/* 80A88590-80A8859C 000C+00 s=1 e=0 z=0  None .rodata    @4829                                                        */
SECTION_RODATA static u8 const lit_4829[12] = {
	0x00, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80A8859C-80A885A0 0004+00 s=1 e=0 z=0  None .rodata    @4830                                                        */
SECTION_RODATA static u8 const lit_4830[4] = {
	0x00, 0x00, 0x00, 0x00,
};

/* 80A885A0-80A885C0 0020+00 s=0 e=0 z=0  None .rodata    @4831                                                        */
SECTION_RODATA u8 const lit_4831[32] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80A885C0-80A885C4 0004+00 s=6 e=0 z=0  None .rodata    @4982                                                        */
SECTION_RODATA static u32 const lit_4982 = 0xBF800000;

/* 80A885C4-80A885CC 0008+00 s=2 e=0 z=0  None .rodata    @5186                                                        */
SECTION_RODATA static u8 const lit_5186[8] = {
	0x3F, 0xE0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80A885CC-80A885D4 0008+00 s=2 e=0 z=0  None .rodata    @5187                                                        */
SECTION_RODATA static u8 const lit_5187[8] = {
	0x40, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80A885D4-80A885DC 0008+00 s=2 e=0 z=0  None .rodata    @5188                                                        */
SECTION_RODATA static u8 const lit_5188[8] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80A885DC-80A885E0 0004+00 s=2 e=0 z=0  None .rodata    @5189                                                        */
SECTION_RODATA static u32 const lit_5189 = 0x42C80000;

/* 80A885E0-80A885E4 0004+00 s=2 e=0 z=0  None .rodata    @5358                                                        */
SECTION_RODATA static u32 const lit_5358 = 0x43200000;

/* 80A885E4-80A885E8 0004+00 s=3 e=0 z=0  None .rodata    @5391                                                        */
SECTION_RODATA static u32 const lit_5391 = 0x43FA0000;

/* 80A885E8-80A885EC 0004+00 s=1 e=0 z=0  None .rodata    @5440                                                        */
SECTION_RODATA static u32 const lit_5440 = 0x43160000;

/* 80A885EC-80A885F0 0004+00 s=1 e=0 z=0  None .rodata    @5799                                                        */
SECTION_RODATA static u32 const lit_5799 = 0x40A00000;

/* 80A885F0-80A885F4 0004+00 s=1 e=0 z=0  None .rodata    @5800                                                        */
SECTION_RODATA static u32 const lit_5800 = 0x3DCCCCCD;

/* 80A885F4-80A885F8 0004+00 s=1 e=0 z=0  None .rodata    @5801                                                        */
SECTION_RODATA static u32 const lit_5801 = 0x3FC00000;

/* 80A885F8-80A885FC 0004+00 s=1 e=0 z=0  None .rodata    @5802                                                        */
SECTION_RODATA static u32 const lit_5802 = 0xC1C80000;

/* 80A885FC-80A88600 0004+00 s=1 e=0 z=0  None .rodata    @5803                                                        */
SECTION_RODATA static u32 const lit_5803 = 0x3F000000;

/* 80A88600-80A88604 0004+00 s=1 e=0 z=0  None .rodata    @5804                                                        */
SECTION_RODATA static u32 const lit_5804 = 0x42F00000;

/* 80A88604-80A88608 0004+00 s=1 e=0 z=0  None .rodata    @5805                                                        */
SECTION_RODATA static u32 const lit_5805 = 0x3E4CCCCD;

/* 80A88608-80A8860C 0004+00 s=1 e=0 z=0  None .rodata    @5806                                                        */
SECTION_RODATA static u32 const lit_5806 = 0xBE4CCCCD;

/* 80A8860C-80A88610 0004+00 s=1 e=0 z=0  None .rodata    @5807                                                        */
SECTION_RODATA static u32 const lit_5807 = 0x3ECCCCCD;

/* 80A88610-80A88614 0004+00 s=1 e=0 z=0  None .rodata    @5808                                                        */
SECTION_RODATA static u32 const lit_5808 = 0xBFC00000;

/* 80A88614-80A88618 0004+00 s=1 e=0 z=0  None .rodata    @5809                                                        */
SECTION_RODATA static u32 const lit_5809 = 0x40400000;

/* 80A88618-80A8861C 0004+00 s=1 e=0 z=0  None .rodata    @5810                                                        */
SECTION_RODATA static u32 const lit_5810 = 0x42200000;

/* 80A8861C-80A88620 0004+00 s=1 e=0 z=0  None .rodata    @5811                                                        */
SECTION_RODATA static u32 const lit_5811 = 0x41A00000;

/* 80A88620-80A88624 0004+00 s=1 e=0 z=0  None .rodata    @5812                                                        */
SECTION_RODATA static u32 const lit_5812 = 0x428C0000;

/* 80A88624-80A88628 0004+00 s=1 e=0 z=0  None .rodata    @5813                                                        */
SECTION_RODATA static u32 const lit_5813 = 0xBF333333;

/* 80A88628-80A8862C 0004+00 s=1 e=0 z=0  None .rodata    @5814                                                        */
SECTION_RODATA static u32 const lit_5814 = 0x3FB33333;

/* 80A8862C-80A88634 0004+04 s=1 e=0 z=0  None .rodata    @5815                                                        */
SECTION_RODATA static u32 const lit_5815[1 + 1 /* padding */] = {
	0x40000000,
	/* padding */
	0x00000000,
};

/* 80A88634-80A8863C 0008+00 s=1 e=0 z=0  None .rodata    @5816                                                        */
SECTION_RODATA static u8 const lit_5816[8] = {
	0x3F, 0xB9, 0x99, 0x99, 0x99, 0x99, 0x99, 0x9A,
};

/* 80A8863C-80A88640 0004+00 s=1 e=0 z=0  None .rodata    @5817                                                        */
SECTION_RODATA static u32 const lit_5817 = 0x40C00000;

/* 80A88640-80A88644 0004+00 s=1 e=0 z=0  None .rodata    @5818                                                        */
SECTION_RODATA static u32 const lit_5818 = 0x45800000;

/* 80A88644-80A8864C 0004+04 s=1 e=0 z=0  None .rodata    @5819                                                        */
SECTION_RODATA static u32 const lit_5819[1 + 1 /* padding */] = {
	0x45C00000,
	/* padding */
	0x00000000,
};

/* 80A8864C-80A88654 0008+00 s=1 e=0 z=0  None .rodata    @5872                                                        */
SECTION_RODATA static u8 const lit_5872[8] = {
	0x43, 0x30, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00,
};

/* 80A88654-80A8866C 0018+00 s=7 e=0 z=0  None .rodata    None                                                         */
SECTION_RODATA static u8 const struct_80A88654[24] = {
	/* 80A88654 000B stringBase_80A88654 @stringBase0 */
	0x46, 0x49, 0x52, 0x53, 0x54, 0x5F, 0x54, 0x41, 0x4C, 0x4B, 0x00,
	/* 80A8865F 000D data_80A8865F None */
	0x47, 0x41, 0x4D, 0x45, 0x5F, 0x46, 0x41, 0x49, 0x4C, 0x55, 0x52, 0x45, 0x00,
};

/* 80A8866C-80A88688 001C+00 s=2 e=0 z=0  None .rodata    None                                                         */
SECTION_RODATA static u8 const struct_80A8866C[28] = {
	/* 80A8866C 000A data_80A8866C None */
	0x47, 0x41, 0x4D, 0x45, 0x5F, 0x47, 0x4F, 0x41, 0x4C, 0x00,
	/* 80A88676 0012 data_80A88676 None */
	0x47, 0x41, 0x4D, 0x45, 0x5F, 0x47, 0x4F, 0x41, 0x4C, 0x5F, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53,
	0x53, 0x00,
};

/* 80A88688-80A88698 0010+00 s=1 e=0 z=0  None .rodata    None                                                         */
SECTION_RODATA static u8 const struct_80A88688[16] = {
	/* 80A88688 0007 data_80A88688 None */
	0x4D, 0x59, 0x4E, 0x41, 0x5F, 0x62, 0x00,
	/* 80A8868F 0009 data_80A8868F None */
	0x4D, 0x59, 0x4E, 0x41, 0x5F, 0x62, 0x5F, 0x66, 0x00,
};

/* 80A88698-80A886B4 001C+00 s=3 e=0 z=0  None .rodata    None                                                         */
SECTION_RODATA static u8 const struct_80A88698[28] = {
	/* 80A88698 0009 data_80A88698 None */
	0x4D, 0x59, 0x4E, 0x41, 0x5F, 0x62, 0x5F, 0x67, 0x00,
	/* 80A886A1 0006 data_80A886A1 None */
	0x6D, 0x79, 0x6E, 0x61, 0x32, 0x00,
	/* 80A886A7 000D data_80A886A7 None */
	0x00, 0x46, 0x5F, 0x53, 0x50, 0x31, 0x31, 0x35, 0x00, 0x70, 0x72, 0x6D, 0x00,
};

/* 80A886B4-80A886C0 000C+00 s=4 e=0 z=0  None .data      cNullVec__6Z2Calc                                            */
SECTION_DATA static u8 cNullVec__6Z2Calc[12] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80A886C0-80A886D4 0004+10 s=0 e=0 z=0  None .data      @1787                                                        */
SECTION_DATA u32 lit_1787[1 + 4 /* padding */] = {
	0x02000201,
	/* padding */
	0x40080000, 0x00000000, 0x3FE00000, 0x00000000,
};

/* 80A886D4-80A886DC 0008+00 s=1 e=0 z=0  None .data      l_bmdGetParamList                                            */
SECTION_DATA static u8 l_bmdGetParamList[8] = {
	0x00, 0x00, 0x00, 0x17, 0x00, 0x00, 0x00, 0x00,
};

/* 80A886DC-80A88754 0078+00 s=1 e=0 z=0  None .data      l_bckGetParamList                                            */
SECTION_DATA static u8 l_bckGetParamList[120] = {
	0x00, 0x00, 0x00, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0A, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x0B, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x0D, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0C, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0E, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x0F, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x13, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x14, 0x00, 0x00, 0x00, 0x00,
};

/* 80A88754-80A8875C 0008+00 s=1 e=0 z=0  None .data      l_btpGetParamList                                            */
SECTION_DATA static u8 l_btpGetParamList[8] = {
	0x00, 0x00, 0x00, 0x1A, 0x00, 0x00, 0x00, 0x00,
};

/* 80A8875C-80A88784 0028+00 s=1 e=0 z=0  None .data      l_evtGetParamList                                            */
SECTION_DATA static u8 l_evtGetParamList[40] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x02,
	0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x02,
};

/* 80A88784-80A88798 0014+00 s=1 e=0 z=0  None .data      l_evtNames                                                   */
SECTION_DATA static void* l_evtNames[5] = {
	(void*)NULL,
	(void*)(((char*)&struct_80A88654)+0x0) /* @stringBase0 */,
	(void*)(((char*)&struct_80A88654)+0xB) /* None */,
	(void*)(((char*)&struct_80A8866C)+0x0) /* None */,
	(void*)(((char*)&struct_80A8866C)+0xA) /* None */,
};

/* 80A88798-80A887A4 000C+00 s=1 e=0 z=0  None .data      l_loadRes_MYNA2a                                             */
SECTION_DATA static u8 l_loadRes_MYNA2a[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
};

/* 80A887A4-80A887B0 000C+00 s=1 e=0 z=0  None .data      l_loadRes_MYNA2_GAME_FAILURE                                 */
SECTION_DATA static u8 l_loadRes_MYNA2_GAME_FAILURE[12] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0xFF, 0xFF, 0xFF, 0xFF,
};

/* 80A887B0-80A887BC 000C+00 s=1 e=0 z=0  None .data      l_loadRes_MYNA2_GAME_GOAL                                    */
SECTION_DATA static u8 l_loadRes_MYNA2_GAME_GOAL[12] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xFF, 0xFF, 0xFF, 0xFF,
};

/* 80A887BC-80A887C8 000C+00 s=1 e=0 z=0  None .data      l_loadRes_MYNA20                                             */
SECTION_DATA static u8 l_loadRes_MYNA20[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
};

/* 80A887C8-80A887DC 0014+00 s=2 e=0 z=0  None .data      l_loadRes_list                                               */
SECTION_DATA static void* l_loadRes_list[5] = {
	(void*)&l_loadRes_MYNA2a,
	(void*)&l_loadRes_MYNA2a,
	(void*)&l_loadRes_MYNA2_GAME_FAILURE,
	(void*)&l_loadRes_MYNA2_GAME_GOAL,
	(void*)&l_loadRes_MYNA20,
};

/* 80A887DC-80A887E8 000C+00 s=6 e=0 z=0  None .data      l_resNames                                                   */
SECTION_DATA static void* l_resNames[3] = {
	(void*)(((char*)&struct_80A88688)+0x0) /* None */,
	(void*)(((char*)&struct_80A88688)+0x7) /* None */,
	(void*)(((char*)&struct_80A88698)+0x0) /* None */,
};

/* 80A887E8-80A887EC 0004+00 s=1 e=0 z=0  None .data      l_myName                                                     */
SECTION_DATA static void* l_myName = (void*)(((char*)&struct_80A88698)+0x9) /* None */;

/* 80A887EC-80A88800 0014+00 s=1 e=0 z=0  None .data      mEvtCutNameList__13daNpc_myna2_c                             */
SECTION_DATA static void* mEvtCutNameList__13daNpc_myna2_c[5] = {
	(void*)(((char*)&struct_80A88698)+0xF) /* None */,
	(void*)(((char*)&struct_80A88654)+0x0) /* @stringBase0 */,
	(void*)(((char*)&struct_80A88654)+0xB) /* None */,
	(void*)(((char*)&struct_80A8866C)+0x0) /* None */,
	(void*)(((char*)&struct_80A8866C)+0xA) /* None */,
};

/* 80A88800-80A8880C 000C+00 s=1 e=0 z=0  None .data      @4033                                                        */
SECTION_DATA static void* lit_4033[3] = {
	(void*)NULL,
	(void*)0xFFFFFFFF,
	(void*)ECut_firstTalk__13daNpc_myna2_cFi,
};

/* 80A8880C-80A88818 000C+00 s=1 e=0 z=0  None .data      @4034                                                        */
SECTION_DATA static void* lit_4034[3] = {
	(void*)NULL,
	(void*)0xFFFFFFFF,
	(void*)ECut_gameFailure__13daNpc_myna2_cFi,
};

/* 80A88818-80A88824 000C+00 s=1 e=0 z=0  None .data      @4035                                                        */
SECTION_DATA static void* lit_4035[3] = {
	(void*)NULL,
	(void*)0xFFFFFFFF,
	(void*)ECut_gameGoal__13daNpc_myna2_cFi,
};

/* 80A88824-80A88830 000C+00 s=1 e=0 z=0  None .data      @4036                                                        */
SECTION_DATA static void* lit_4036[3] = {
	(void*)NULL,
	(void*)0xFFFFFFFF,
	(void*)ECut_gameGoalSuccess__13daNpc_myna2_cFi,
};

/* 80A88830-80A8886C 003C+00 s=2 e=0 z=0  None .data      mEvtCutList__13daNpc_myna2_c                                 */
SECTION_DATA static u8 mEvtCutList__13daNpc_myna2_c[60] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80A8886C-80A88878 000C+00 s=1 e=0 z=0  None .data      @4477                                                        */
SECTION_DATA static void* lit_4477[3] = {
	(void*)NULL,
	(void*)0xFFFFFFFF,
	(void*)test__13daNpc_myna2_cFPv,
};

/* 80A88878-80A88884 000C+00 s=1 e=0 z=0  None .data      @4868                                                        */
SECTION_DATA static void* lit_4868[3] = {
	(void*)NULL,
	(void*)0xFFFFFFFF,
	(void*)test__13daNpc_myna2_cFPv,
};

/* 80A88884-80A88890 000C+00 s=1 e=0 z=0  None .data      @4872                                                        */
SECTION_DATA static void* lit_4872[3] = {
	(void*)NULL,
	(void*)0xFFFFFFFF,
	(void*)waitHovering__13daNpc_myna2_cFPv,
};

/* 80A88890-80A8889C 000C+00 s=1 e=0 z=0  None .data      @4874                                                        */
SECTION_DATA static void* lit_4874[3] = {
	(void*)NULL,
	(void*)0xFFFFFFFF,
	(void*)waitFailure__13daNpc_myna2_cFPv,
};

/* 80A8889C-80A888A8 000C+00 s=1 e=0 z=0  None .data      @4876                                                        */
SECTION_DATA static void* lit_4876[3] = {
	(void*)NULL,
	(void*)0xFFFFFFFF,
	(void*)waitGoal__13daNpc_myna2_cFPv,
};

/* 80A888A8-80A888B4 000C+00 s=1 e=0 z=0  None .data      @4878                                                        */
SECTION_DATA static void* lit_4878[3] = {
	(void*)NULL,
	(void*)0xFFFFFFFF,
	(void*)wait__13daNpc_myna2_cFPv,
};

/* 80A888B4-80A888C0 000C+00 s=1 e=0 z=0  None .data      @4918                                                        */
SECTION_DATA static void* lit_4918[3] = {
	(void*)NULL,
	(void*)0xFFFFFFFF,
	(void*)talk__13daNpc_myna2_cFPv,
};

/* 80A888C0-80A888CC 000C+00 s=1 e=0 z=0  None .data      @4926                                                        */
SECTION_DATA static void* lit_4926[3] = {
	(void*)NULL,
	(void*)0xFFFFFFFF,
	(void*)talk__13daNpc_myna2_cFPv,
};

/* 80A888CC-80A88948 007C+00 s=1 e=0 z=0  None .data      @5498                                                        */
SECTION_DATA static void* lit_5498[31] = {
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x15C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x190),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x1C4),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x1E4),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x280),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x248),
};

/* 80A88948-80A889C4 007C+00 s=1 e=0 z=0  None .data      @5497                                                        */
SECTION_DATA static void* lit_5497[31] = {
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0xA0),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0xD0),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0xE4),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x12C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
	(void*)(((char*)ECut_gameGoalSuccess__13daNpc_myna2_cFi)+0x13C),
};

/* 80A889C4-80A889E4 0020+00 s=1 e=0 z=0  None .data      daNpc_myna2_MethodTable                                      */
SECTION_DATA static void* daNpc_myna2_MethodTable[8] = {
	(void*)daNpc_myna2_Create__FPv,
	(void*)daNpc_myna2_Delete__FPv,
	(void*)daNpc_myna2_Execute__FPv,
	(void*)daNpc_myna2_IsDelete__FPv,
	(void*)daNpc_myna2_Draw__FPv,
	(void*)NULL,
	(void*)NULL,
	(void*)NULL,
};

/* 80A889E4-80A88A14 0030+00 s=0 e=0 z=1  None .data      g_profile_MYNA2                                              */
SECTION_DATA void* g_profile_MYNA2[12] = {
	(void*)0xFFFFFFFD,
	(void*)0x0007FFFD,
	(void*)0x02860000,
	(void*)&g_fpcLf_Method,
	(void*)0x00000E34,
	(void*)NULL,
	(void*)NULL,
	(void*)&g_fopAc_Method,
	(void*)0x01890000,
	(void*)&daNpc_myna2_MethodTable,
	(void*)0x08044100,
	(void*)0x040E0000,
};

/* 80A88A14-80A88A5C 0048+00 s=2 e=0 z=0  None .data      __vt__13daNpc_myna2_c                                        */
SECTION_DATA static void* __vt__13daNpc_myna2_c[18] = {
	(void*)NULL,
	(void*)NULL,
	(void*)__dt__13daNpc_myna2_cFv,
	(void*)setParam__13daNpc_myna2_cFv,
	(void*)main__13daNpc_myna2_cFv,
	(void*)ctrlBtk__8daNpcF_cFv,
	(void*)adjustShapeAngle__8daNpcF_cFv,
	(void*)setMtx__8daNpcF_cFv,
	(void*)setMtx2__8daNpcF_cFv,
	(void*)setAttnPos__13daNpc_myna2_cFv,
	(void*)setCollisions__8daNpcF_cFv,
	(void*)setExpressionAnm__8daNpcF_cFib,
	(void*)setExpressionBtp__13daNpc_myna2_cFi,
	(void*)setExpression__8daNpcF_cFif,
	(void*)setMotionAnm__13daNpc_myna2_cFif,
	(void*)setMotion__13daNpc_myna2_cFifi,
	(void*)drawDbgInfo__13daNpc_myna2_cFv,
	(void*)drawOtherMdls__13daNpc_myna2_cFv,
};

/* 80A88A5C-80A88A68 000C+00 s=3 e=0 z=0  None .data      __vt__12J3DFrameCtrl                                         */
SECTION_DATA static void* __vt__12J3DFrameCtrl[3] = {
	(void*)NULL,
	(void*)NULL,
	(void*)__dt__12J3DFrameCtrlFv,
};

/* 80A88A68-80A88A8C 0024+00 s=3 e=0 z=0  None .data      __vt__12dBgS_ObjAcch                                         */
SECTION_DATA static void* __vt__12dBgS_ObjAcch[9] = {
	(void*)NULL,
	(void*)NULL,
	(void*)__dt__12dBgS_ObjAcchFv,
	(void*)NULL,
	(void*)NULL,
	(void*)func_80A88418,
	(void*)NULL,
	(void*)NULL,
	(void*)func_80A88410,
};

/* 80A88A8C-80A88A98 000C+00 s=3 e=0 z=0  None .data      __vt__10cCcD_GStts                                           */
SECTION_DATA static void* __vt__10cCcD_GStts[3] = {
	(void*)NULL,
	(void*)NULL,
	(void*)__dt__10cCcD_GSttsFv,
};

/* 80A88A98-80A88AA4 000C+00 s=2 e=0 z=0  None .data      __vt__10dCcD_GStts                                           */
SECTION_DATA static void* __vt__10dCcD_GStts[3] = {
	(void*)NULL,
	(void*)NULL,
	(void*)__dt__10dCcD_GSttsFv,
};

/* 80A88AA4-80A88AB0 000C+00 s=2 e=0 z=0  None .data      __vt__12dBgS_AcchCir                                         */
SECTION_DATA static void* __vt__12dBgS_AcchCir[3] = {
	(void*)NULL,
	(void*)NULL,
	(void*)__dt__12dBgS_AcchCirFv,
};

/* 80A88AB0-80A88ABC 000C+00 s=4 e=0 z=0  None .data      __vt__18daNpcF_ActorMngr_c                                   */
SECTION_DATA static void* __vt__18daNpcF_ActorMngr_c[3] = {
	(void*)NULL,
	(void*)NULL,
	(void*)__dt__18daNpcF_ActorMngr_cFv,
};

/* 80A88ABC-80A88AC8 000C+00 s=3 e=0 z=0  None .data      __vt__8cM3dGCyl                                              */
SECTION_DATA static void* __vt__8cM3dGCyl[3] = {
	(void*)NULL,
	(void*)NULL,
	(void*)__dt__8cM3dGCylFv,
};

/* 80A88AC8-80A88AD4 000C+00 s=3 e=0 z=0  None .data      __vt__8cM3dGAab                                              */
SECTION_DATA static void* __vt__8cM3dGAab[3] = {
	(void*)NULL,
	(void*)NULL,
	(void*)__dt__8cM3dGAabFv,
};

/* 80A88AD4-80A88AE0 000C+00 s=3 e=0 z=0  None .data      __vt__15daNpcF_Lookat_c                                      */
SECTION_DATA static void* __vt__15daNpcF_Lookat_c[3] = {
	(void*)NULL,
	(void*)NULL,
	(void*)__dt__15daNpcF_Lookat_cFv,
};

/* 80A83E8C-80A84010 0184+00 s=1 e=0 z=0  None .text      __ct__13daNpc_myna2_cFv                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm daNpc_myna2_c::daNpc_myna2_c() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/__ct__13daNpc_myna2_cFv.s"
}
#pragma pop


/* 80A84010-80A84058 0048+00 s=1 e=0 z=0  None .text      __dt__8cM3dGCylFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm cM3dGCyl::~cM3dGCyl() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/__dt__8cM3dGCylFv.s"
}
#pragma pop


/* 80A84058-80A840A0 0048+00 s=1 e=0 z=0  None .text      __dt__8cM3dGAabFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm cM3dGAab::~cM3dGAab() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/__dt__8cM3dGAabFv.s"
}
#pragma pop


/* 80A840A0-80A842C8 0228+00 s=1 e=0 z=0  None .text      __dt__13daNpc_myna2_cFv                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm daNpc_myna2_c::~daNpc_myna2_c() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/__dt__13daNpc_myna2_cFv.s"
}
#pragma pop


/* 80A842C8-80A845AC 02E4+00 s=1 e=0 z=0  None .text      create__13daNpc_myna2_cFv                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::create() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/create__13daNpc_myna2_cFv.s"
}
#pragma pop


/* 80A845AC-80A846E0 0134+00 s=1 e=0 z=0  None .text      CreateHeap__13daNpc_myna2_cFv                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::CreateHeap() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/CreateHeap__13daNpc_myna2_cFv.s"
}
#pragma pop


/* 80A846E0-80A84714 0034+00 s=1 e=0 z=0  None .text      Delete__13daNpc_myna2_cFv                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::Delete() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/Delete__13daNpc_myna2_cFv.s"
}
#pragma pop


/* 80A84714-80A84734 0020+00 s=2 e=0 z=0  None .text      Execute__13daNpc_myna2_cFv                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::Execute() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/Execute__13daNpc_myna2_cFv.s"
}
#pragma pop


/* 80A84734-80A847A8 0074+00 s=1 e=0 z=0  None .text      Draw__13daNpc_myna2_cFv                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::Draw() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/Draw__13daNpc_myna2_cFv.s"
}
#pragma pop


/* 80A847A8-80A847C8 0020+00 s=1 e=0 z=0  None .text      createHeapCallBack__13daNpc_myna2_cFP10fopAc_ac_c            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::createHeapCallBack(fopAc_ac_c* param_0) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/createHeapCallBack__13daNpc_myna2_cFP10fopAc_ac_c.s"
}
#pragma pop


/* 80A847C8-80A848B4 00EC+00 s=1 e=0 z=0  None .text      setParam__13daNpc_myna2_cFv                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::setParam() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/setParam__13daNpc_myna2_cFv.s"
}
#pragma pop


/* 80A848B4-80A84B64 02B0+00 s=1 e=0 z=0  None .text      main__13daNpc_myna2_cFv                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::main() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/main__13daNpc_myna2_cFv.s"
}
#pragma pop


/* ############################################################################################## */
/* 80A88AF8-80A88AFC 0001+03 s=1 e=0 z=0  None .bss       @1109                                                        */
static u8 lit_1109[1 + 3 /* padding */];

/* 80A88AFC-80A88B00 0001+03 s=0 e=0 z=0  None .bss       @1107                                                        */
u8 lit_1107[1 + 3 /* padding */];

/* 80A88B00-80A88B04 0001+03 s=0 e=0 z=0  None .bss       @1105                                                        */
u8 lit_1105[1 + 3 /* padding */];

/* 80A88B04-80A88B08 0001+03 s=0 e=0 z=0  None .bss       @1104                                                        */
u8 lit_1104[1 + 3 /* padding */];

/* 80A88B08-80A88B0C 0001+03 s=0 e=0 z=0  None .bss       @1099                                                        */
u8 lit_1099[1 + 3 /* padding */];

/* 80A88B0C-80A88B10 0001+03 s=0 e=0 z=0  None .bss       @1097                                                        */
u8 lit_1097[1 + 3 /* padding */];

/* 80A88B10-80A88B14 0001+03 s=0 e=0 z=0  None .bss       @1095                                                        */
u8 lit_1095[1 + 3 /* padding */];

/* 80A88B14-80A88B18 0001+03 s=0 e=0 z=0  None .bss       @1094                                                        */
u8 lit_1094[1 + 3 /* padding */];

/* 80A88B18-80A88B1C 0001+03 s=0 e=0 z=0  None .bss       @1057                                                        */
u8 lit_1057[1 + 3 /* padding */];

/* 80A88B1C-80A88B20 0001+03 s=0 e=0 z=0  None .bss       @1055                                                        */
u8 lit_1055[1 + 3 /* padding */];

/* 80A88B20-80A88B24 0001+03 s=0 e=0 z=0  None .bss       @1053                                                        */
u8 lit_1053[1 + 3 /* padding */];

/* 80A88B24-80A88B28 0001+03 s=0 e=0 z=0  None .bss       @1052                                                        */
u8 lit_1052[1 + 3 /* padding */];

/* 80A88B28-80A88B2C 0001+03 s=0 e=0 z=0  None .bss       @1014                                                        */
u8 lit_1014[1 + 3 /* padding */];

/* 80A88B2C-80A88B30 0001+03 s=0 e=0 z=0  None .bss       @1012                                                        */
u8 lit_1012[1 + 3 /* padding */];

/* 80A88B30-80A88B34 0001+03 s=0 e=0 z=0  None .bss       @1010                                                        */
u8 lit_1010[1 + 3 /* padding */];

/* 80A88B34-80A88B38 0001+03 s=0 e=0 z=0  None .bss       @1009                                                        */
u8 lit_1009[1 + 3 /* padding */];

/* 80A88B38-80A88B44 000C+00 s=1 e=0 z=0  None .bss       @4032                                                        */
static u8 lit_4032[12];

/* 80A88B44-80A88B48 0004+00 s=1 e=0 z=0  None .bss       l_HIO                                                        */
static u8 l_HIO[4];

/* 80A88B48-80A88B58 000C+04 s=1 e=0 z=0  None .bss       @4583                                                        */
static u8 lit_4583[12 + 4 /* padding */];

/* 80A88B58-80A88B64 000C+00 s=1 e=0 z=0  None .bss       eyeOffset$4582                                               */
static u8 eyeOffset[12];

/* 80A84B64-80A84DAC 0248+00 s=1 e=0 z=0  None .text      setAttnPos__13daNpc_myna2_cFv                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::setAttnPos() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/setAttnPos__13daNpc_myna2_cFv.s"
}
#pragma pop


/* 80A84DAC-80A84EAC 0100+00 s=1 e=0 z=0  None .text      setExpressionBtp__13daNpc_myna2_cFi                          */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::setExpressionBtp(int param_0) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/setExpressionBtp__13daNpc_myna2_cFi.s"
}
#pragma pop


/* 80A84EAC-80A84FEC 0140+00 s=1 e=0 z=0  None .text      setMotionAnm__13daNpc_myna2_cFif                             */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::setMotionAnm(int param_0, f32 param_1) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/setMotionAnm__13daNpc_myna2_cFif.s"
}
#pragma pop


/* 80A84FEC-80A85030 0044+00 s=1 e=0 z=0  None .text      setMotion__13daNpc_myna2_cFifi                               */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::setMotion(int param_0, f32 param_1, int param_2) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/setMotion__13daNpc_myna2_cFifi.s"
}
#pragma pop


/* 80A85030-80A85038 0008+00 s=1 e=0 z=0  None .text      drawDbgInfo__13daNpc_myna2_cFv                               */
bool daNpc_myna2_c::drawDbgInfo() {
	return false;
}


/* 80A85038-80A8503C 0004+00 s=1 e=0 z=0  None .text      drawOtherMdls__13daNpc_myna2_cFv                             */
void daNpc_myna2_c::drawOtherMdls() {
	/* empty function */
}


/* 80A8503C-80A85094 0058+00 s=1 e=0 z=0  None .text      getTypeFromParam__13daNpc_myna2_cFv                          */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::getTypeFromParam() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/getTypeFromParam__13daNpc_myna2_cFv.s"
}
#pragma pop


/* 80A85094-80A85160 00CC+00 s=1 e=0 z=0  None .text      isDelete__13daNpc_myna2_cFv                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::isDelete() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/isDelete__13daNpc_myna2_cFv.s"
}
#pragma pop


/* 80A85160-80A85358 01F8+00 s=1 e=0 z=0  None .text      reset__13daNpc_myna2_cFv                                     */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::reset() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/reset__13daNpc_myna2_cFv.s"
}
#pragma pop


/* 80A85358-80A855E8 0290+00 s=1 e=0 z=0  None .text      playMotion__13daNpc_myna2_cFv                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::playMotion() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/playMotion__13daNpc_myna2_cFv.s"
}
#pragma pop


/* 80A855E8-80A85614 002C+00 s=2 e=0 z=0  None .text      chkAction__13daNpc_myna2_cFM13daNpc_myna2_cFPCvPvPv_i        */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::chkAction(int (daNpc_myna2_c::*)(void*)) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/chkAction__13daNpc_myna2_cFM13daNpc_myna2_cFPCvPvPv_i.s"
}
#pragma pop


/* 80A85614-80A856BC 00A8+00 s=2 e=0 z=0  None .text      setAction__13daNpc_myna2_cFM13daNpc_myna2_cFPCvPvPv_i        */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::setAction(int (daNpc_myna2_c::*)(void*)) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/setAction__13daNpc_myna2_cFM13daNpc_myna2_cFPCvPvPv_i.s"
}
#pragma pop


/* 80A856BC-80A857B0 00F4+00 s=1 e=0 z=0  None .text      selectAction__13daNpc_myna2_cFv                              */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::selectAction() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/selectAction__13daNpc_myna2_cFv.s"
}
#pragma pop


/* 80A857B0-80A85894 00E4+00 s=1 e=0 z=0  None .text      doNormalAction__13daNpc_myna2_cFi                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::doNormalAction(int param_0) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/doNormalAction__13daNpc_myna2_cFi.s"
}
#pragma pop


/* 80A85894-80A85BA4 0310+00 s=1 e=0 z=0  None .text      doEvent__13daNpc_myna2_cFv                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::doEvent() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/doEvent__13daNpc_myna2_cFv.s"
}
#pragma pop


/* 80A85BA4-80A85BC8 0024+00 s=7 e=0 z=0  None .text      setLookMode__13daNpc_myna2_cFi                               */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::setLookMode(int param_0) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/setLookMode__13daNpc_myna2_cFi.s"
}
#pragma pop


/* 80A85BC8-80A85C60 0098+00 s=1 e=0 z=0  None .text      wait__13daNpc_myna2_cFPv                                     */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::wait(void* param_0) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/wait__13daNpc_myna2_cFPv.s"
}
#pragma pop


/* 80A85C60-80A8613C 04DC+00 s=1 e=0 z=0  None .text      waitHovering__13daNpc_myna2_cFPv                             */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::waitHovering(void* param_0) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/waitHovering__13daNpc_myna2_cFPv.s"
}
#pragma pop


/* 80A8613C-80A86194 0058+00 s=1 e=0 z=0  None .text      s_sub__FPvPv                                                 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm static void s_sub(void* param_0, void* param_1) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/s_sub__FPvPv.s"
}
#pragma pop


/* 80A86194-80A862BC 0128+00 s=1 e=0 z=0  None .text      waitFailure__13daNpc_myna2_cFPv                              */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::waitFailure(void* param_0) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/waitFailure__13daNpc_myna2_cFPv.s"
}
#pragma pop


/* 80A862BC-80A86400 0144+00 s=1 e=0 z=0  None .text      waitGoal__13daNpc_myna2_cFPv                                 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::waitGoal(void* param_0) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/waitGoal__13daNpc_myna2_cFPv.s"
}
#pragma pop


/* 80A86400-80A865FC 01FC+00 s=2 e=0 z=0  None .text      talk__13daNpc_myna2_cFPv                                     */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::talk(void* param_0) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/talk__13daNpc_myna2_cFPv.s"
}
#pragma pop


/* 80A865FC-80A866B0 00B4+00 s=2 e=0 z=0  None .text      test__13daNpc_myna2_cFPv                                     */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::test(void* param_0) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/test__13daNpc_myna2_cFPv.s"
}
#pragma pop


/* 80A866B0-80A8684C 019C+00 s=1 e=0 z=0  None .text      ECut_firstTalk__13daNpc_myna2_cFi                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::ECut_firstTalk(int param_0) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/ECut_firstTalk__13daNpc_myna2_cFi.s"
}
#pragma pop


/* 80A8684C-80A86A0C 01C0+00 s=1 e=0 z=0  None .text      ECut_gameFailure__13daNpc_myna2_cFi                          */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::ECut_gameFailure(int param_0) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/ECut_gameFailure__13daNpc_myna2_cFi.s"
}
#pragma pop


/* 80A86A0C-80A86BEC 01E0+00 s=1 e=0 z=0  None .text      ECut_gameGoal__13daNpc_myna2_cFi                             */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::ECut_gameGoal(int param_0) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/ECut_gameGoal__13daNpc_myna2_cFi.s"
}
#pragma pop


/* 80A86BEC-80A86E8C 02A0+00 s=3 e=0 z=0  None .text      ECut_gameGoalSuccess__13daNpc_myna2_cFi                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::ECut_gameGoalSuccess(int param_0) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/ECut_gameGoalSuccess__13daNpc_myna2_cFi.s"
}
#pragma pop


/* 80A86E8C-80A879A0 0B14+00 s=6 e=0 z=0  None .text      calcHovering__13daNpc_myna2_cFii                             */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daNpc_myna2_c::calcHovering(int param_0, int param_1) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/calcHovering__13daNpc_myna2_cFii.s"
}
#pragma pop


/* 80A879A0-80A879C0 0020+00 s=1 e=0 z=0  None .text      daNpc_myna2_Create__FPv                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm static void daNpc_myna2_Create(void* param_0) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/daNpc_myna2_Create__FPv.s"
}
#pragma pop


/* 80A879C0-80A879E0 0020+00 s=1 e=0 z=0  None .text      daNpc_myna2_Delete__FPv                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm static void daNpc_myna2_Delete(void* param_0) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/daNpc_myna2_Delete__FPv.s"
}
#pragma pop


/* 80A879E0-80A87A00 0020+00 s=1 e=0 z=0  None .text      daNpc_myna2_Execute__FPv                                     */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm static void daNpc_myna2_Execute(void* param_0) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/daNpc_myna2_Execute__FPv.s"
}
#pragma pop


/* 80A87A00-80A87A20 0020+00 s=1 e=0 z=0  None .text      daNpc_myna2_Draw__FPv                                        */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm static void daNpc_myna2_Draw(void* param_0) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/daNpc_myna2_Draw__FPv.s"
}
#pragma pop


/* 80A87A20-80A87A28 0008+00 s=1 e=0 z=0  None .text      daNpc_myna2_IsDelete__FPv                                    */
static bool daNpc_myna2_IsDelete(void* param_0) {
	return true;
}


/* 80A87A28-80A87A70 0048+00 s=5 e=0 z=0  None .text      __dt__18daNpcF_ActorMngr_cFv                                 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm daNpcF_ActorMngr_c::~daNpcF_ActorMngr_c() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/__dt__18daNpcF_ActorMngr_cFv.s"
}
#pragma pop


/* 80A87A70-80A87AAC 003C+00 s=2 e=0 z=0  None .text      __ct__18daNpcF_ActorMngr_cFv                                 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm daNpcF_ActorMngr_c::daNpcF_ActorMngr_c() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/__ct__18daNpcF_ActorMngr_cFv.s"
}
#pragma pop


/* 80A87AAC-80A87B7C 00D0+00 s=1 e=0 z=0  None .text      __dt__15daNpcF_Lookat_cFv                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm daNpcF_Lookat_c::~daNpcF_Lookat_c() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/__dt__15daNpcF_Lookat_cFv.s"
}
#pragma pop


/* 80A87B7C-80A87BB8 003C+00 s=5 e=0 z=0  None .text      __dt__5csXyzFv                                               */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm csXyz::~csXyz() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/__dt__5csXyzFv.s"
}
#pragma pop


/* 80A87BB8-80A87BBC 0004+00 s=2 e=0 z=0  None .text      __ct__5csXyzFv                                               */
csXyz::csXyz() {
	/* empty function */
}


/* 80A87BBC-80A87BF8 003C+00 s=6 e=0 z=0  None .text      __dt__4cXyzFv                                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm cXyz::~cXyz() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/__dt__4cXyzFv.s"
}
#pragma pop


/* 80A87BF8-80A87BFC 0004+00 s=2 e=0 z=0  None .text      __ct__4cXyzFv                                                */
cXyz::cXyz() {
	/* empty function */
}


/* 80A87BFC-80A87E48 024C+00 s=1 e=0 z=0  None .text      __dt__8daNpcF_cFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm daNpcF_c::~daNpcF_c() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/__dt__8daNpcF_cFv.s"
}
#pragma pop


/* 80A87E48-80A88038 01F0+00 s=1 e=0 z=0  None .text      __ct__8daNpcF_cFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm daNpcF_c::daNpcF_c() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/__ct__8daNpcF_cFv.s"
}
#pragma pop


/* 80A88038-80A880A8 0070+00 s=1 e=0 z=0  None .text      __dt__12dBgS_AcchCirFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm dBgS_AcchCir::~dBgS_AcchCir() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/__dt__12dBgS_AcchCirFv.s"
}
#pragma pop


/* 80A880A8-80A88104 005C+00 s=1 e=0 z=0  None .text      __dt__10dCcD_GSttsFv                                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm dCcD_GStts::~dCcD_GStts() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/__dt__10dCcD_GSttsFv.s"
}
#pragma pop


/* 80A88104-80A88174 0070+00 s=3 e=0 z=0  None .text      __dt__12dBgS_ObjAcchFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm dBgS_ObjAcch::~dBgS_ObjAcch() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/__dt__12dBgS_ObjAcchFv.s"
}
#pragma pop


/* 80A88174-80A881BC 0048+00 s=1 e=0 z=0  None .text      __dt__12J3DFrameCtrlFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm J3DFrameCtrl::~J3DFrameCtrl() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/__dt__12J3DFrameCtrlFv.s"
}
#pragma pop


/* 80A881BC-80A881C4 0008+00 s=1 e=0 z=0  None .text      ctrlBtk__8daNpcF_cFv                                         */
bool daNpcF_c::ctrlBtk() {
	return false;
}


/* 80A881C4-80A881C8 0004+00 s=1 e=0 z=0  None .text      adjustShapeAngle__8daNpcF_cFv                                */
void daNpcF_c::adjustShapeAngle() {
	/* empty function */
}


/* 80A881C8-80A881CC 0004+00 s=1 e=0 z=0  None .text      setCollisions__8daNpcF_cFv                                   */
void daNpcF_c::setCollisions() {
	/* empty function */
}


/* 80A881CC-80A881D4 0008+00 s=1 e=0 z=0  None .text      setExpressionAnm__8daNpcF_cFib                               */
bool daNpcF_c::setExpressionAnm(int param_0, bool param_1) {
	return true;
}


/* 80A881D4-80A881D8 0004+00 s=1 e=0 z=0  None .text      setExpression__8daNpcF_cFif                                  */
void daNpcF_c::setExpression(int param_0, f32 param_1) {
	/* empty function */
}


/* 80A881D8-80A88220 0048+00 s=1 e=0 z=0  None .text      __dt__10cCcD_GSttsFv                                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm cCcD_GStts::~cCcD_GStts() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/__dt__10cCcD_GSttsFv.s"
}
#pragma pop


/* 80A88220-80A8823C 001C+00 s=1 e=0 z=0  None .text      cLib_calcTimer<i>__FPi                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm static void cLib_calcTimer__template0(int* param_0) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/func_80A88220.s"
}
#pragma pop


/* 80A8823C-80A88278 003C+00 s=1 e=0 z=0  None .text      cLib_getRndValue<f>__Fff                                     */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm static void cLib_getRndValue__template0(f32 param_0, f32 param_1) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/func_80A8823C.s"
}
#pragma pop


/* 80A88278-80A882F4 007C+00 s=1 e=0 z=0  None .text      cLib_getRndValue<i>__Fii                                     */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm static void cLib_getRndValue__template1(int param_0, int param_1) {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/func_80A88278.s"
}
#pragma pop


/* ############################################################################################## */
/* 80A88AE0-80A88AEC 000C+00 s=2 e=0 z=0  None .data      __vt__19daNpc_myna2_Param_c                                  */
SECTION_DATA static void* __vt__19daNpc_myna2_Param_c[3] = {
	(void*)NULL,
	(void*)NULL,
	(void*)__dt__19daNpc_myna2_Param_cFv,
};

/* 80A882F4-80A883C8 00D4+00 s=0 e=1 z=0  None .text      __sinit_d_a_npc_myna2_cpp                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void __sinit_d_a_npc_myna2_cpp() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/__sinit_d_a_npc_myna2_cpp.s"
}
#pragma pop


/* 80A883C8-80A88410 0048+00 s=2 e=0 z=0  None .text      __dt__19daNpc_myna2_Param_cFv                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm daNpc_myna2_Param_c::~daNpc_myna2_Param_c() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/__dt__19daNpc_myna2_Param_cFv.s"
}
#pragma pop


/* 80A88410-80A88418 0008+00 s=1 e=0 z=0  None .text      @36@__dt__12dBgS_ObjAcchFv                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm static void func_80A88410() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/func_80A88410.s"
}
#pragma pop


/* 80A88418-80A88420 0008+00 s=1 e=0 z=0  None .text      @20@__dt__12dBgS_ObjAcchFv                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm static void func_80A88418() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_myna2/d_a_npc_myna2/func_80A88418.s"
}
#pragma pop


/* ############################################################################################## */
/* 80A88B64-80A88B68 0004+00 s=0 e=0 z=0  None .bss       sInstance__40JASGlobalInstance<19JASDefaultBankTable>        */
u8 data_80A88B64[4];

/* 80A88B68-80A88B6C 0004+00 s=0 e=0 z=0  None .bss       sInstance__35JASGlobalInstance<14JASAudioThread>             */
u8 data_80A88B68[4];

/* 80A88B6C-80A88B70 0004+00 s=0 e=0 z=0  None .bss       sInstance__27JASGlobalInstance<7Z2SeMgr>                     */
u8 data_80A88B6C[4];

/* 80A88B70-80A88B74 0004+00 s=0 e=0 z=0  None .bss       sInstance__28JASGlobalInstance<8Z2SeqMgr>                    */
u8 data_80A88B70[4];

/* 80A88B74-80A88B78 0004+00 s=0 e=0 z=0  None .bss       sInstance__31JASGlobalInstance<10Z2SceneMgr>                 */
u8 data_80A88B74[4];

/* 80A88B78-80A88B7C 0004+00 s=0 e=0 z=0  None .bss       sInstance__32JASGlobalInstance<11Z2StatusMgr>                */
u8 data_80A88B78[4];

/* 80A88B7C-80A88B80 0004+00 s=0 e=0 z=0  None .bss       sInstance__31JASGlobalInstance<10Z2DebugSys>                 */
u8 data_80A88B7C[4];

/* 80A88B80-80A88B84 0004+00 s=0 e=0 z=0  None .bss       sInstance__36JASGlobalInstance<15JAISoundStarter>            */
u8 data_80A88B80[4];

/* 80A88B84-80A88B88 0004+00 s=0 e=0 z=0  None .bss       sInstance__35JASGlobalInstance<14Z2SoundStarter>             */
u8 data_80A88B84[4];

/* 80A88B88-80A88B8C 0004+00 s=0 e=0 z=0  None .bss       sInstance__33JASGlobalInstance<12Z2SpeechMgr2>               */
u8 data_80A88B88[4];

/* 80A88B8C-80A88B90 0004+00 s=0 e=0 z=0  None .bss       sInstance__28JASGlobalInstance<8JAISeMgr>                    */
u8 data_80A88B8C[4];

/* 80A88B90-80A88B94 0004+00 s=0 e=0 z=0  None .bss       sInstance__29JASGlobalInstance<9JAISeqMgr>                   */
u8 data_80A88B90[4];

/* 80A88B94-80A88B98 0004+00 s=0 e=0 z=0  None .bss       sInstance__33JASGlobalInstance<12JAIStreamMgr>               */
u8 data_80A88B94[4];

/* 80A88B98-80A88B9C 0004+00 s=0 e=0 z=0  None .bss       sInstance__31JASGlobalInstance<10Z2SoundMgr>                 */
u8 data_80A88B98[4];

/* 80A88B9C-80A88BA0 0004+00 s=0 e=0 z=0  None .bss       sInstance__33JASGlobalInstance<12JAISoundInfo>               */
u8 data_80A88B9C[4];

/* 80A88BA0-80A88BA4 0004+00 s=0 e=0 z=0  None .bss       sInstance__34JASGlobalInstance<13JAUSoundTable>              */
u8 data_80A88BA0[4];

/* 80A88BA4-80A88BA8 0004+00 s=0 e=0 z=0  None .bss       sInstance__38JASGlobalInstance<17JAUSoundNameTable>          */
u8 data_80A88BA4[4];

/* 80A88BA8-80A88BAC 0004+00 s=0 e=0 z=0  None .bss       sInstance__33JASGlobalInstance<12JAUSoundInfo>               */
u8 data_80A88BA8[4];

/* 80A88BAC-80A88BB0 0004+00 s=0 e=0 z=0  None .bss       sInstance__32JASGlobalInstance<11Z2SoundInfo>                */
u8 data_80A88BAC[4];

/* 80A88BB0-80A88BB4 0004+00 s=0 e=0 z=0  None .bss       sInstance__34JASGlobalInstance<13Z2SoundObjMgr>              */
u8 data_80A88BB0[4];

/* 80A88BB4-80A88BB8 0004+00 s=0 e=0 z=0  None .bss       sInstance__31JASGlobalInstance<10Z2Audience>                 */
u8 data_80A88BB4[4];

/* 80A88BB8-80A88BBC 0004+00 s=0 e=0 z=0  None .bss       sInstance__32JASGlobalInstance<11Z2FxLineMgr>                */
u8 data_80A88BB8[4];

/* 80A88BBC-80A88BC0 0004+00 s=0 e=0 z=0  None .bss       sInstance__31JASGlobalInstance<10Z2EnvSeMgr>                 */
u8 data_80A88BBC[4];

/* 80A88BC0-80A88BC4 0004+00 s=0 e=0 z=0  None .bss       sInstance__32JASGlobalInstance<11Z2SpeechMgr>                */
u8 data_80A88BC0[4];

/* 80A88BC4-80A88BC8 0004+00 s=0 e=0 z=0  None .bss       sInstance__34JASGlobalInstance<13Z2WolfHowlMgr>              */
u8 data_80A88BC4[4];

