{
	"SHA_DBG",
	"184 占い師デバッグ", // Fortune teller debugging
	"住吉", // Sumiyoshi
	0xF2FF,
	"F_SP116:城下街", // Castle town
	0x2,
	0xE,
},
{
	"PACHITUTORIAL_INF",
	"115 パチチュ−、ヒット情報", // Slingshot tutorial, hit information
	"住吉", // Sumiyoshi
	0xF3FF,
	"F_SP103:トアル村", // Ordon Village
	0x1,
	0x7,
},
{
	"PACHITUTORIAL_CNT",
	"114 パチチュ−、壊した的の数", // Slingshot tutorial, number of targets broken
	"住吉", // Sumiyoshi
	0xF4FF,
	"F_SP103:トアル村", // Ordon Village
	0x1,
	0x7,
},
{
	"SHA_LOVEFORTUNE_05",
	"106 恋愛運シ−ン切り替え先記憶用", // Love fortune scene change destination
	"住吉", // Sumiyoshi
	0xF5FF,
	"F_SP116:城下街", // Castle town
	0x2,
	0xE,
},
{
	"SHA_LOVEFORTUNE_04",
    "105 恋愛運シ−ン切り替え先記憶用", // Love fortune scene change destination
	"住吉", // Sumiyoshi
	0xF6FF,
	"F_SP116:城下街", // Castle town
	0x2,
	0xE,
},
{
	"SHA_LOVEFORTUNE_03",
    "104 恋愛運シ−ン切り替え先記憶用", // Love fortune scene change destination
	"住吉", // Sumiyoshi
	0xF7FF,
	"F_SP116:城下街", // Castle town
	0x2,
	0xE,
},
{
	"SHA_LOVEFORTUNE_02",
    "103 恋愛運シ−ン切り替え先記憶用", // Love fortune scene change destination
	"住吉", // Sumiyoshi
	0xF8FF,
	"F_SP116:城下街", // Castle town
	0x2,
	0xE,
},
{
	"SHA_LOVEFORTUNE_01",
    "102 恋愛運シ−ン切り替え先記憶用", // Love fortune scene change destination
	"住吉", // Sumiyoshi
	0xF9FF,
	"F_SP116:城下街", // Castle town
	0x2,
	0xE,
},
{
	"SHA_LOVEFORTUNE_00",
    "101 恋愛運シ−ン切り替え先記憶用", // Love fortune scene change destination
	"住吉", // Sumiyoshi
	0xFAFF,
	"F_SP116:城下街", // Castle town
	0x2,
	0xE,
},
{
	"TREG_000",
    "34 キュリ−の会話で使います", // Used in Pergie's conversation
	"住吉", // Sumiyoshi
	0xFBFF,
	"F_SP103:トアル村", // Ordon Village
	0x1,
	0x7,
},
{
	"T_0006",
    "6 戻り先のレイヤ−番号", // Destination layer number
	"住吉", // Sumiyoshi
	0xFCFF,
	"仮デモ", // Temporary demo
	0x3,
	0x14,
},
{
	"T_0005",
    "5 実行デモNo受け渡し", // Executing demo No. receipt
	"住吉", // Sumiyoshi
	0xFDFF,
	"仮デモ", // Temporary demo
	0x3,
	0x14,
},
{
	"T_0003",
    "3 剣チュ−トリアル・斬った回数", // Sword tutorial・number of slashes
	"住吉", // Sumiyoshi
	0xFEFF,
	"F_SP103:トアル村", // Ordon Village
	0x1,
	0x7,
},
{
	"T_0002",
    "2 剣チュ−トリアル・ステップ", // Sword tutorial・step
	"住吉", // Sumiyoshi
	0xFF0F,
	"F_SP103:トアル村", // Ordon Village
	0x1,
	0x7,
},
