{
	"KORO2_ALLCLEAR",
	"821 コロコロゲーム全ステージ(8-8)クリア後", // After all stages (8-8) of roll goal game cleared
	"森田", // Morita
	0x6302,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0820",
	"820 @",
	"京極", // Kyogoku
	0x6304,
	"***",
	0x0,
	0x1,
},
{
	"F_0819",
	"819 @",
	"京極", // Kyogoku
	0x6308,
	"***",
	0x0,
	0x1,
},
{
	"F_0818",
	"818 @",
	"京極", // Kyogoku
	0x6310,
	"***",
	0x0,
	0x1,
},
{
	"F_0817",
	"817 @",
	"京極", // Kyogoku
	0x6320,
	"***",
	0x0,
	0x1,
},
{
	"F_0816",
	"816 @",
	"京極", // Kyogoku
	0x6340,
	"***",
	0x0,
	0x1,
},
{
	"F_0815",
	"815 @",
	"京極", // Kyogoku
	0x6380,
	"***",
	0x0,
	0x1,
},
{
	"F_0814",
	"814 @",
	"京極", // Kyogoku
	0x6201,
	"***",
	0x0,
	0x1,
},
{
	"F_0813",
	"813 @",
	"京極", // Kyogoku
	0x6202,
	"***",
	0x0,
	0x1,
},
{
	"F_0812",
	"812 @",
	"京極", // Kyogoku
	0x6204,
	"***",
	0x0,
	0x1,
},
{
	"F_0811",
	"811 スタアゲーム初挑戦した", // Attempted Star Game for the first time
	"京極", // Kyogoku
	0x6208,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0810",
	"810 ゴーストのにおいを覚えた", // Learned ghost's scent
	"京極", // Kyogoku
	0x6210,
	"D_MN10:LV4ダンジョン", // LV4 Dungeon
	0x9,
	0xa,
},
{
	"F_0809",
	"809 追っかけ３人娘（リンクの追っかけになる初会話）", // 3 groupie girls (first conversation where they become Link's groupies)
	"京極", // Kyogoku
	0x6220,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0808",
	"808 初日のベスと話した", // Talked to Beth on the first day
	"京極", // Kyogoku
	0x6240,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0807",
	"807 初日のコリンと話した", // Talked to Colin on the first day
	"京極", // Kyogoku
	0x6280,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0806",
	"806 初日のハンジョーと話した", // Talked to Hanch on the first day
	"京極", // Kyogoku
	0x6101,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0805",
	"805 マロの雑貨屋の方でハイリアの盾を買った", // Bought Hylian shield from Malo Mart
	"京極", // Kyogoku
	0x6102,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0804",
	"804 オルディンTW突入直後の強制ミドナ会話聞いた", // Heard Midna's forced conversation immediately after plunge into Eldin Twilight
	"京極", // Kyogoku
	0x6104,
	"TW環状フィールド", // Twilight Ring field
	0x1d,
	0x1e,
},
{
	"F_0803",
	"803 天空に行った後でインパル婆さんと話した", // Talked to Old Lady Impaz after going to Sky
	"京極", // Kyogoku
	0x6108,
	"F_SP128:隠れ里", // Hidden Village
	0x18,
	0x19,
},
{
	"F_0802",
	"802 万引きのトリル攻撃開始", // Trill attacks when stealing
	"京極（坂口さん用）", // Kyogoku (used by Sakaguchi)
	0x6110,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0801",
	"801 ニオイマスのにおいを（初めて）覚えた", // First learned Reek Fish scent
	"京極", // Kyogoku
	0x6120,
	"F_SP113:ゾーラの里", // Zora's Domain
	0x13,
	0x14,
},
{
	"F_0800",
	"800 トアルの森に帰還後、影から突然ミドナが出てくるまで（８００がＯＮはミドナ呼べない）", // After returning to Ordon Woods, until Midna comes out of the shadows (If 800 is ON, Midna can't be called)
	"京極", // Kyogoku
	0x6140,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"F_0799",
	"799 倒れているゴロンの嘆きを聞いた（橋開通後）", // Listened to the fallen Goron's complaints (after opening bridge)
	"一角", // Ikkaku
	0x6180,
	"環状フィールド", // Ring field
	0x25,
	0x26,
},
{
	"F_0798",
	"798 トビーからゾーラの話を聞いた", // Heard about Zora from Fyer
	"京極", // Kyogoku
	0x6001,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0797",
	"797 トビー大砲で持込・修理を選んだことがある（用事のない時）", // Have selected "Take Cannon / Repair" at Fyer's cannon (when there's no other business)
	"京極", // Kyogoku
	0x6002,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0796",
	"796 天空文字6", // Sky character 6
	"京極", // Kyogoku
	0x6004,
	"天空文字", // Sky character
	0x29,
	0x2a,
},
{
	"F_0795",
	"795 天空文字5", // Sky character 5
	"京極", // Kyogoku
	0x6008,
	"天空文字", // Sky character
	0x29,
	0x2a,
},
{
	"F_0794",
	"794 天空文字4", // Sky character 4
	"京極", // Kyogoku
	0x6010,
	"天空文字", // Sky character
	0x29,
	0x2a,
},
{
	"F_0793",
	"793 天空文字3", // Sky character 3
	"京極", // Kyogoku
	0x6020,
	"天空文字", // Sky character
	0x29,
	0x2a,
},
{
	"F_0792",
	"792 天空文字2", // Sky character 2
	"京極", // Kyogoku
	0x6040,
	"天空文字", // Sky character
	0x29,
	0x2a,
},
{
	"F_0791",
	"791 天空文字１", // Sky character 1
	"京極", // Kyogoku
	0x6080,
	"天空文字", // Sky character
	0x29,
	0x2a,
},
{
	"F_0790",
	"790 セーラがネコの方を向くようになる(520　ONで会話範囲から外れる)", // Sera faces the cat (outside conversation area when 520 is ON)
	"京極（坂口使用）", // Kyogoku (Sakaguchi's use)
	0x5f01,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0789",
	"789 甘そうなリンゴを１回手に取った", // Grabbed sweet apple 1 time
	"京極", // Kyogoku
	0x5f02,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0788",
	"788 滝のぼりゾーラと話した", // Talked to Zora going up the waterfall
	"京極", // Kyogoku
	0x5f04,
	"F_SP112:ゾーラ川", // Zora's River
	0x12,
	0x13,
},
{
	"F_0787",
	"787 天空砲をワープさせようとしてミドナに止められた「", // Stopped by Midna when trying to warp the sky cannon
	"京極", // Kyogoku
	0x5f08,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0786",
	"786 天空大砲を見たシャッドの強制会話", // Forced conversation with Shad when he sees the sky cannon
	"京極", // Kyogoku
	0x5f10,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0785",
	"785 天空砲ワープさせようとした後、シャッド立ち去る", // Shad leaves after attempting to warp sky cannon
	"京極", // Kyogoku
	0x5f20,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0784",
	"784 教会地下に戻ってきたシャッドと通常会話した", // Had normal conversation with Shad after he returns to church basement
	"京極", // Kyogoku
	0x5f40,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0783",
	"783 インパル婆さんにコピーロッドを見せた", // Showed dominion rod to Impaz
	"京極", // Kyogoku
	0x5f80,
	"F_SP128:隠れ里", // Hidden Village
	0x18,
	0x19,
},
{
	"F_0782",
	"782 LV3攻略後-LV6攻略前の間にレナードと話した", // Spoke to Renado after LV3 complete, before LV6 complete
	"京極", // Kyogoku
	0x5e01,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0781",
	"781 LV6クリアまでに教会でイリアと話した", // Spoke to Ilia in church after clearing LV6
	"京極", // Kyogoku
	0x5e02,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0780",
	"780 記憶復活後のイリアから天空の使者の話を聞いた", // Heard Ilia talk about the messenger from the sky after her memories are restored
	"京極", // Kyogoku
	0x5e04,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0779",
	"779 橋炎上中のミドナヒント１回聞いた", // Heard one hint from Midna while bridge is burning
	"京極", // Kyogoku
	0x5e08,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0778",
	"778 LV1ダンクリア後の精霊の話の後の強制ミドナ会話聞いた", // Heard forced conversation with Midna after story about spirits after clearing LV1 dungeon
	"京極", // Kyogoku
	0x5e10,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0777",
	"777 エポナと話した", // Spoke to Epona
	"京極", // Kyogoku
	0x5e20,
	"その他", // Misc.
	0x20,
	0x21,
},
{
	"F_0776",
	"776 LV8ダンジョンの霧でリンクが初めて狼に変身した", // Link first turned to wolf due to fog in LV8 dungeon
	"京極", // Kyogoku
	0x5e40,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0775",
	"775 初トビー大砲後の強制ミドナ聞いた", // Heard forced conversation with Midna after first Fyer's cannon
	"京極", // Kyogoku
	0x5e80,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0774",
	"774 冷凍ゾーラを見た後のミドナの会話聞いた", // Listened to Midna's conversation after seeing frozen Zora
	"京極", // Kyogoku
	0x5d01,
	"F_SP113:ゾーラの里", // Zora's Domain
	0x13,
	0x14,
},
{
	"F_0773",
	"773 無人販売店：最後の支払いが多かった", // Unmanned Shop : last payment too much
	"京極", // Kyogoku
	0x5d02,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0772",
	"772 無人販売店：最後の支払いが少なかった", // Unmanned Shop : last payment too little
	"京極", // Kyogoku
	0x5d04,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0771",
	"771 無人販売店：最後の支払いドロボーした", // Unmanned Shop : last payment stolen
	"京極", // Kyogoku
	0x5d08,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0770",
	"770 ＴＷ（氷付け）初訪問デモ後の強制会話を聞いた", // Twilight (frozen) Heard forced conversation after first visit cutscene
	"京極", // Kyogoku
	0x5d10,
	"F_SP113:ゾーラの里", // Zora's Domain
	0x13,
	0x14,
},
{
	"F_0769",
	"769 ゾーラ川上流に初到着直後のミドナ強制会話", // Forced conversation with Midna right after first arrival at upper Zora's river
	"京極", // Kyogoku
	0x5d20,
	"F_SP112:ゾーラ川", // Zora's River
	0x12,
	0x13,
},
{
	"F_0768",
	"768 ハイリア湖紹介デモ後のミドナの強制会話聞いた", // Heard forced conversation with Midna after Hylia Lake introduction cutscene
	"京極", // Kyogoku
	0x5d40,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"J_BTN_GUIDE",
	"767 十字ボタンガイド", // X-button guide
	"坂口", // Sakaguchi
	0x5d80,
	"その他", // Misc.
	0x20,
	0x21,
},
{
	"B_BTN_GUIDE",
	"766 Ｂボタンガイド", // B-button guide
	"坂口", // Sakaguchi
	0x5c01,
	"その他", // Misc.
	0x20,
	0x21,
},
{
	"F_0759",
	"759 序盤（３日目）のセーラと初会話", // Opening (3rd day) first conversation with Sera
	"京極", // Kyogoku
	0x5c02,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0758",
	"758 無人販売所で万引きした（※トリル狼会話用。話すとリセット）", // Stole from unmanned shop (For use in Trill wolf conversation. Resets after speaking)
	"京極", // Kyogoku
	0x5c04,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0757",
	"757 トリルと狼会話した", // Had Trill and wolf conversation
	"京極", // Kyogoku
	0x5c08,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0756",
	"756 おばちゃんが仲間になった", // Join with Ooccoo Sr.
	"京極", // Kyogoku
	0x5c10,
	"D_MN07:LV7ダンジョン", // LV7 dungeon
	0x7,
	0x8,
},
{
	"F_0755",
	"755 TWホヅ　闇蟲登場直後の台詞聞いた", // Twilight Heard Iza's line right after shadow bug appears
	"京極", // Kyogoku
	0x5c20,
	"F_SP112:ゾーラ川", // Zora's River
	0x12,
	0x13,
},
{
	"F_0754",
	"754 F1001:ミドナヒント　サルのヒント2聞いた(SAVE72=ON)", // Heard Midna's hint / Monkey hint 2 times (SAVE72=ON)
	"京極", // Kyogoku
	0x5c40,
	"D_MN05:LV1ダンジョン", // LV1 Dungeon
	0x5,
	0x6,
},
{
	"F_0753",
	"753 キコルのまずいスープを始めてすくった", // Scooped Coro's bad soup for the first time
	"京極", // Kyogoku
	0x5c80,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0752",
	"752 ボンニャーズ再び成功", // Beat cat game again
	"京極", // Kyogoku
	0x5b01,
	"F_SP128:隠れ里", // Hidden Village
	0x18,
	0x19,
},
{
	"F_0751",
	"751 コッコ隊長から詳しい説明を初めて聞いた", // Heard detailed explaination from Captain Cucco for the first time
	"京極", // Kyogoku
	0x5b02,
	"F_SP128:隠れ里", // Hidden Village
	0x18,
	0x19,
},
{
	"F_0750",
	"750 ボンニャーズ活動開始後　コッコ隊長と初会話", // First conversation with Captain Cucco after beginning cat game activities
	"京極", // Kyogoku
	0x5b04,
	"F_SP128:隠れ里", // Hidden Village
	0x18,
	0x19,
},
{
	"F_0749",
	"749 ボンニャーズクリア済（ハートのかけらが埋められた。とるかどうかはプレイヤー次第）", // After clearing cat game (Heart piece is buried, whether it is obtained depends on the player)
	"京極", // Kyogoku
	0x5b08,
	"F_SP128:隠れ里", // Hidden Village
	0x18,
	0x19,
},
{
	"F_0748",
	"748 ヒント鷹、初会話", // First conversation with hint hawk
	"一角", // Ikkaku
	0x5b10,
	"環状フィールド", // Ring field
	0x25,
	0x26,
},
{
	"F_0747",
	"747 F0063:コッコBと話した", // Spoke with Cucco B
	"京極", // Kyogoku
	0x5b20,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0746",
	"746 F0062:コッコAと話した", // Spoke with Cucco A
	"京極", // Kyogoku
	0x5b40,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0745",
	"745 F1604:大人ゴロン（ハイリアの盾）と話した", // Spoke with adult Goron (Hylia shield)
	"京極", // Kyogoku
	0x5b80,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0744",
	"744 F1603:大人ゴロン（矢３０本）と話した（ガノンウォール後）", // Spoke with adult Goron (30 arrows) (after Ganon wall)
	"京極", // Kyogoku
	0x5a01,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0743",
	"743 F1603:大人ゴロン（矢３０本）と話した（ガノンウォール前）", // Spoke with adult Goron (30 arrows) (before Ganon wall)
	"京極", // Kyogoku
	0x5a02,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0742",
	"742 F1602:子どもゴロン（赤いクスリ売り）と話した", // Spoke with child Goron (selling red potion)
	"京極", // Kyogoku
	0x5a04,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0741",
	"741 F1601:子どもゴロン（カンテラ油売り）と話した（ガノンウォール後）", // Spoke with child Goron (selling lantern oil) (after Ganon wall)
	"京極", // Kyogoku
	0x5a08,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0740",
	"740 F1601:子どもゴロン（カンテラ油売り）と話した（ガノンウォール前）", // Spoke with child Goron (selling lantern oil) (before Ganon wall)
	"京極", // Kyogoku
	0x5a10,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0739",
	"739 F1137:南−果物屋の客の老人と話した", // South - Spoke with old customer at fruit stand
	"京極", // Kyogoku
	0x5a20,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0738",
	"738 F1136:南−八百屋の客の女性と話した", // South - Spoke with female customer at vegetable stand
	"京極", // Kyogoku
	0x5a40,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0737",
	"737 ウド(猫)初めて会話＠ミドナ瀕死", // First conversation with Udo (cat) during Midna's desperate hour
	"一角", // Ikkaku
	0x5a80,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0736",
	"736 F1001:ミドナヒント　サルのヒント聞いた　", // Heard Midna's hint / monkey hint
	"京極", // Kyogoku
	0x5901,
	"D_MN05:LV1ダンジョン", // LV1 Dungeon
	0x5,
	0x6,
},
{
	"F_0735",
	"735 アヒルと話した", // Spoke with domestic duck
	"京極", // Kyogoku
	0x5902,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0734",
	"734 カモと話した", // Spoke with wild duck
	"京極", // Kyogoku
	0x5904,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0733",
	"733 リズ川下りご褒美のハートのかけらをもらった", // Recieved Heart piece reward from Iza for going down the river
	"京極", // Kyogoku
	0x5908,
	"F_SP112:ゾーラ川", // Zora's River
	0x12,
	0x13,
},
{
	"F_0732",
	"732 コッコと話した（イリア記憶イベント攻略前）", // Spoke with Cucco (After completing Ilia's memory event)
	"京極", // Kyogoku
	0x5910,
	"F_SP128:隠れ里", // Hidden Village
	0x18,
	0x19,
},
{
	"F_0730",
	"730 リズのボートに初めて乗った", // Rode Iza's boat for the first time
	"京極", // Kyogoku
	0x5920,
	"F_SP112:ゾーラ川", // Zora's River
	0x12,
	0x13,
},
{
	"F_0729",
	"729 ポストマン「おォ～い！」直後", // Right after postman's "Hey!"
	"一角", // Ikkaku
	0x5940,
	"環状フィールド", // Ring field
	0x25,
	0x26,
},
{
	"F_0728",
	"728 セレブショップで靴が汚くて入店拒否された", // Refused entry into Chudley's shop because of dirty shoes
	"京極", // Kyogoku
	0x5980,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0727",
	"727 靴磨き少年と初会話", // First conversation with shoe-shine boy
	"京極", // Kyogoku
	0x5801,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0726",
	"726 ホヅ狼対応　話しかけた", // Talk to Iza as wolf
	"京極", // Kyogoku
	0x5802,
	"F_SP112:ゾーラ川", // Zora's River
	0x12,
	0x13,
},
{
	"F_0725",
	"725 シャッド訪問中を告げるレナードと話した", // Speak to Renado who is announcing Shad's visit
	"京極", // Kyogoku
	0x5804,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0724",
	"724 F1133:東−井戸端会議のおばさん２人組と話した", // East - Spoke to two ladies gossiping
	"京極", // Kyogoku
	0x5808,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0723",
	"723 F1132:東−路地裏のおじさんと話した", // East - Spoke to man in the alley
	"京極", // Kyogoku
	0x5810,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0722",
	"722 F1131:東−Ｔ字路のおじさんと話した", // East - Spoke to man at the T-shaped street
	"京極", // Kyogoku
	0x5820,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0721",
	"721 F:1130 - 南 - 果物屋の店主と話した（馬車護衛後）", // South - Spoke to fruit stand vendor (after guarding carriage)
	"京極", // Kyogoku
	0x5840,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0720",
	"720 F:1130 - 南 - 果物屋の店主と話した（馬車護衛前）", // South - Spoke to fruit stand vendor (before guarding carriage)
	"京極", // Kyogoku
	0x5880,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0719",
	"719 F:1129 - 南 - 八百屋の客のばあさんと話した（マロマート時）", // South - Spoke to old lady at the vegetable stand (Malo Mart)
	"京極", // Kyogoku
	0x5701,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0718",
	"718 F:1129 - 南 - 八百屋の客のばあさんと話した（セレブ時）", // South - Spoke to old lady at the vegetable stand (Chudley)
	"京極", // Kyogoku
	0x5702,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0717",
	"717 F:1125 西−犬の飼い主と話した", // Wist - Speak to the dog owner
	"京極", // Kyogoku
	0x5704,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0716",
	"716 F:1509-東の犬と話した", // Speak with dog to the east
	"京極", // Kyogoku
	0x5708,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0715",
	"715 F:1508-西の犬と話した", // Speak with dog to west
	"京極", // Kyogoku
	0x5710,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0709",
	"709 ミドナ瀕死、ステファニー(猫)と初会話", // Midna's desperate hour, first conversation wtih Stephanie (cat)
	"一角", // Ikkaku
	0x5720,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0708",
	"708 魂コンプ後、ハカセ初回会話", // First conversaton with doctor after completing spirit
	"一角", // Ikkaku
	0x5740,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0707",
	"707 ミドナ瀕死、ミー(猫)と初会話", // Midna's desperate hour, first conversation with Mii (cat)
	"一角", // Ikkaku
	0x5780,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0706",
	"706 ミドナ瀕死でトラコ(猫)と初会話", // First conversation wtih Torako (cat) during Midna's desperate hour
	"一角", // Ikkaku
	0x5601,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0705",
	"705 ミドナ瀕死でカヘル(蛙)と初会話", // First conversation with Kaeru (frog) during Midna's desperate hour
	"一角", // Ikkaku
	0x5602,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0704",
	"704 TW水ナシ時のリズの話を聞いた", // Listened to Iza in Twilight before domain is thawed
	"京極", // Kyogoku
	0x5604,
	"F_SP112:ゾーラ川", // Zora's River
	0x12,
	0x13,
},
{
	"F_0703",
	"703 ウキ釣りでニオイマスを初めて釣った", // Caught Reek fish for first time while fishing
	"京極", // Kyogoku
	0x5608,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0702B",
	"702 F1124:南のパン屋店主-少年A2と話した", // South Baker - Spoke with Boy A2
	"京極", // Kyogoku
	0x5610,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0701B",
	"701 F1123:南の八百屋店主-町人D2と話した（馬車護衛後）", // South Vegetable vendor - Spoke with Villager D2 (after guarding carriage)
	"京極", // Kyogoku
	0x5620,
	"***",
	0x0,
	0x1,
},
{
	"F_0700B",
	"700 F1123:南の八百屋店主-町人D2と話した（馬車護衛前）", // South Vegetable vendor - Spoke with Villager D2 (before guarding carriage)
	"京極", // Kyogoku
	0x5640,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0699",
	"699 F1122:南の八百屋前おばさんB1と話した（馬車護衛後）", // Spoke with woman B1 in front of south vegetable stand (after guarding carriage)
	"京極", // Kyogoku
	0x5680,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0698",
	"698 F1122:南の八百屋前おばさんB1と話した（馬車護衛前）", // Spoke with woman B1 in front of south vegetable stand (before guarding carriage)
	"京極", // Kyogoku
	0x5501,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0697",
	"697 F1121:ジョバンニ救出後に聞き込みハイラル兵と話した", // Spoke with inquiring Hyrule guard after saving Jovani
	"京極", // Kyogoku
	0x5502,
	"***",
	0x0,
	0x1,
},
{
	"F_0696",
	"696 F1121:ジョバンニ救出前に聞き込みハイラル兵と話した", // Spoke with inquiring Hyrule guard before saving Jovani
	"京極", // Kyogoku
	0x5504,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0695",
	"695 ヘナと釣り中、初めてカエルのルアーすっぽ抜けた", // First time frog lure slips out
	"京極", // Kyogoku
	0x5508,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0694",
	"694 ゴースト２０個集めてジョバンニと会話", // Conversation with Jovani after collecting 20 ghosts
	"一角", // Ikkaku
	0x5510,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0693",
	"693 人間時、スモモと初会話", // First conversation with Plumm while human
	"一角", // Ikkaku
	0x5520,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0692",
	"692 F1208:馬車護衛後に南路地子ども達と話した", // Spoke with south alley children after guarding carriage
	"京極", // Kyogoku
	0x5540,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0691",
	"691 F1208:馬車護衛前に南路地子ども達と話した", // Spoke with south alley children before guarding carriage
	"京極", // Kyogoku
	0x5580,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0690",
	"690 F:1120 南通り−占い屋前のおばさんA1と話した", // South Road - Spoke with woman A1 in front of fortune teller's shop
	"京極", // Kyogoku
	0x5401,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0689",
	"689 F:1119 南通り肉屋のオヤジ町人C1と話した", // South Road - Spoke with meat shop villager man C1
	"京極", // Kyogoku
	0x5402,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0688",
	"688 F:1118 南通り温泉水屋前(OPEN)町娘D1と話した", // Spoke with town girl D1 in front of south road hot spring shop (OPEN)
	"京極", // Kyogoku
	0x5404,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0687",
	"687 F:1118 南通り温泉水屋前(CLOSE)町娘D1と話した", // Spoke with town girl D1 in front of south road hot spring shop (CLOSED)
	"京極", // Kyogoku
	0x5408,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0686",
	"686 陰呪の結晶（最後の仮面）をとった", // Get fused shadow piece (final mask)
	"京極", // Kyogoku
	0x5410,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0685",
	"685 【デモ32】賢者登場&１つ目の陰りの鏡のかけらをとった", // (Cutscene 32) Sage appears, get first Mirror of Twilight shard
	"京極", // Kyogoku
	0x5420,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"F_0684",
	"684 R00の石像をセンスで見た", // Look at R00 statue using sense
	"京極", // Kyogoku
	0x5440,
	"D_MN06:LV6ダンジョン", // LV6 Dungeon
	0x6,
	0x7,
},
{
	"F_0683",
	"683 1207:中央広場グループB（老婆A1/少年A1/町娘B1）と話した", // Spoke with Group B (Old lady A1, Boy A1, Town girl B1) in central square
	"京極", // Kyogoku
	0x5480,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0682",
	"682 天空人ＳＨＯＰ店員と初会話", // First conversation with Oocca Shopkeeper
	"京極", // Kyogoku
	0x5301,
	"D_MN07:LV7ダンジョン", // LV7 dungeon
	0x7,
	0x8,
},
{
	"F_0681",
	"681 １匹目のゴーストを倒した後のミドナヒントを聞いた", // Heard Midna's hint after defeating first ghost
	"京極", // Kyogoku
	0x5302,
	"D_MN10:LV4ダンジョン", // LV4 Dungeon,
	0x9,
	0xa,
},
{
	"F_0680",
	"680 ゴースト逃亡デモ後のミドナヒントを聞いた", // Heard Midna's hint after cutscene of ghost escaping
	"京極", // Kyogoku
	0x5304,
	"D_MN10:LV4ダンジョン", // LV4 Dungeon,
	0x9,
	0xa,
},
{
	"F_0679",
	"679 コロコロゲームでズルをした", // Cheated during Roll goal game
	"京極", // Kyogoku
	0x5308,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0678",
	"678 F1206:噴水前グループA（町娘C2[、]少年B1[、]町娘D1）と話した", // Spoke with Group A (Town girl C2, Boy B1, Town girl D1) in front of fountain
	"京極", // Kyogoku
	0x5310,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0677",
	"677 F1205:光 - カフェ客B:町人D1&じいさんB1と話した", // Light - Spoke with Cafe customer B: Townsperson D1 and Man B1
	"京極", // Kyogoku
	0x5320,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0676",
	"676 F1204:光 - カフェ客:町人F1（おじさん単品）と話した", // Light - Spoke with Cafe customer: Townsperson F1 (just the man)
	"京極", // Kyogoku
	0x5340,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0675",
	"675 F1203:光 - カフェカウンター:町娘A1（店員）と話した", // Light - cafe counter: Spoke with townsgirl A1 (shop clerk)
	"京極", // Kyogoku
	0x5380,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0674",
	"674 F1202:光 - カフェテーブル:町人A1と話した", // Light - Spoke with cafe table: townsperson A1
	"京極", // Kyogoku
	0x5201,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0673",
	"673 火魔人の弱点のヒントを聞いた(F0215)", // Heard hint about Fyrus's weakness (F0215)
	"京極", // Kyogoku
	0x5202,
	"D_MN04:LV2ダンジョン", // LV2 Dungeon
	0x4,
	0x5,
},
{
	"F_0672",
	"672 マグネゴロンが初めて転がるのを見た", // First time seeing magnet goron tumbling
	"京極", // Kyogoku
	0x5204,
	"D_MN04:LV2ダンジョン", // LV2 Dungeon
	0x4,
	0x5,
},
{
	"F_0671",
	"671 マグネゴロンを一度でも溶岩に投げ入れた", // Through magnet goron into lava once
	"京極", // Kyogoku
	0x5208,
	"D_MN04:LV2ダンジョン", // LV2 Dungeon
	0x4,
	0x5,
},
{
	"F_0670",
	"670 こけた火魔人を殴った", // Hitting knocked-down Fyrus
	"京極", // Kyogoku
	0x5210,
	"D_MN04:LV2ダンジョン", // LV2 Dungeon
	0x4,
	0x5,
},
{
	"F_0669",
	"669 火魔人の鎖を一度でも引っ張った", // Pulled on Fyrus chains at least once
	"京極", // Kyogoku
	0x5220,
	"D_MN04:LV2ダンジョン", // LV2 Dungeon
	0x4,
	0x5,
},
{
	"F_0668",
	"668 ゾーラ一般（汎用）に獣人のスケッチを見せた", // Showed Yeto sketch to Zora civilian (generic)
	"京極", // Kyogoku
	0x5240,
	"F_SP113:ゾーラの里", // Zora's Domain
	0x13,
	0x14,
},
{
	"F_0667",
	"667 ゾーラ兵（汎用）に獣人のスケッチを見せた", // Showed Yeto sketch to average Zora soldier (generic)
	"京極", // Kyogoku
	0x5280,
	"F_SP113:ゾーラの里", // Zora's Domain
	0x13,
	0x14,
},
{
	"F_0666",
	"666 雪山横のゾーラ兵に獣人のスケッチを見せた", // Showed Yeto sketch to Zora soldier next to Snowpeak Mountain
	"京極", // Kyogoku
	0x5101,
	"F_SP113:ゾーラの里", // Zora's Domain
	0x13,
	0x14,
},
{
	"F_0665",
	"665 コロコロゲームに初ズーム", // First zoom in Roll goal game
	"京極", // Kyogoku
	0x5102,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0664",
	"664 コロコロゲームクリア後　初挑戦", // After clearing roll goal game / first attempt
	"京極", // Kyogoku
	0x5104,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0663",
	"663 ピロロちゃんの余計な一言を聞いた", // Listened to Purdy's unnecessary words
	"京極", // Kyogoku
	0x5108,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0662",
	"662 コロコロゲーム１回クリアしたら次からルール省略", // Omit rules after clearing roll goal game once
	"京極", // Kyogoku
	0x5110,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0661",
	"661 TWハイリア湖ゾーラ兵B&Cの話を聞いた", // Twilight Lake Hylia Listened to Zora soldier B&C talk
	"京極", // Kyogoku
	0x5120,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0660",
	"660 TWハイリア湖ゾーラ兵Aの話を聞いた", // Twilight Lake Hylia Listened to Zora soldier A talk
	"京極", // Kyogoku
	0x5140,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0659",
	"659 ＴＷ兵士or地図で、ハイリア湖に精霊の泉がある情報を聞いた", // Hear information about spirit spring in Lake Hylia from Twilight Soldier or map
	"京極", // Kyogoku
	0x5180,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0658",
	"658 アゲハに大きなサイフもらった", // Recieved large wallet from Agitha
	"一角", // Ikkaku
	0x5001,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0657",
	"657 ヘナの目の前でハイラルドジョウを初めて釣った", // Caught Hylian Loach in front of Hena first time
	"京極", // Kyogoku
	0x5002,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0656",
	"656 初めてルアー釣りでつれた（魚なんでも）", // Caught something (any fish) using lure first time
	"京極", // Kyogoku
	0x5004,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0655",
	"655 ウキ釣りで【トアルナマズ】を初めて釣った",  // Caught an Ordon Catfish using bobber first time
	"京極", // Kyogoku
	0x5008,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0654",
	"654 ウキ釣りで【ハイラルドジョウ】を初めて釣った", // Caught Hylian Loach using bobber first time
	"京極", // Kyogoku
	0x5010,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0653",
	"653 ウキ釣りで【ハイリアパイク】を初めて釣った", // Caught Hylian Pike with bobber first time
	"京極", // Kyogoku
	0x5020,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0652",
	"652 ウキ釣りで【ハイラルバス】を初めて釣った", // Caught Hylian Bass with bobber first time
	"京極", // Kyogoku
	0x5040,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0651",
	"651 ウキ釣りで【グリーンギル】を初めて釣った", // Caught Greengill with bobber first time
	"京極", // Kyogoku
	0x5080,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0650",
	"650 0863- リンク写真にズーム時２回目聞いた", // Heard second time zooming in on Link's picture
	"京極", // Kyogoku
	0x4f01,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0649",
	"649 0863- リンク写真にズーム時１回目聞いた", // Heard first time zooming in on Link's picture
	"京極", // Kyogoku
	0x4f02,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0648",
	"648 0837- ヘナ写真①②（番外編）聞いた", // Heard Hena's photo 1,2 (additional story)
	"京極", // Kyogoku
	0x4f04,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0647",
	"647 0836- ヘナ写真②にズーム時１回目聞いた", // Heard second time zooming in on Hena's photo
	"京極", // Kyogoku
	0x4f08,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0646",
	"646 0835- ヘナ写真①にズーム時１回目聞いた", // Heard first time zooming in on Hena's photo
	"京極", // Kyogoku
	0x4f10,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0645",
	"645 0834- ホヅ写真にズーム時１回目聞いた", // Heard First time zoomin in on Iza's photo
	"京極", // Kyogoku
	0x4f20,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0644",
	"644 0833- キコル写真にズーム時１回目聞いた", // Heard first time zooming in on Coro's photo
	"京極", // Kyogoku
	0x4f40,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0643",
	"643 0832- オッサン写真にズーム時１回目聞いた", // Heard first time zooming in on old man's photo
	"京極", // Kyogoku
	0x4f80,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0642",
	"642 0831- 本にズーム時１回目聞いた", // Heard first time zooming in on book
	"京極", // Kyogoku
	0x4e01,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0641",
	"641 0830- 絨毯にズーム時１回目聞いた", // Heard First time zooming in on rug
	"京極", // Kyogoku
	0x4e02,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0640",
	"640 0829 - 壷にズーム時１回目聞いた", // Heard first time zooming in on pot
	"京極", // Kyogoku
	0x4e04,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0639",
	"639 0828 - 帽子にズーム時１回目聞いた", // Heard first time zooming in on hat
	"京極", // Kyogoku
	0x4e08,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0638",
	"638 0826 - カヌーにズーム時１回目聞いた", // Heard first time zooming in on canoe
	"京極", // Kyogoku
	0x4e10,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0637",
	"637 コロコロゲーム全クリア（カエルのルアーGET）", // Cleard all of roll goal game (get frog lure)
	"京極", // Kyogoku
	0x4e20,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0636",
	"636 0825 - カエルのルアーにズーム時１回目聞いた", // Heard first time zooming in on frog lure
	"京極", // Kyogoku
	0x4e40,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0635",
	"635 0824 - ルアーにズーム時（カエル○）聞いた", // Heard zooming in on lure (yes frog)
	"京極", // Kyogoku
	0x4e80,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0634",
	"634 0823 - ルアーにズーム時（カエル×）聞いた", // Heard zooming in on lure (no frog)
	"京極", // Kyogoku
	0x4d01,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0633",
	"633 0820 - 水槽ズーム時②２回目聞いた", // Heard second time zooming in on fish tank (2)
	"京極", // Kyogoku
	0x4d02,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0632",
	"632 0820 - 水槽ズーム時②１回目聞いた", // Heard first time zooming in on fish tank (2)
	"京極", // Kyogoku
	0x4d04,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0631",
	"631 0819 - 水槽ズーム時①聞いた", // Heard when zooming in on fish tank (1)
	"京極", // Kyogoku
	0x4a80,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x1c,
	0x1d,
},
{
	"F_0630",
	"630 【デモ4 - ?】とらわれ直後のリンク（狼）", // (Cutscene 4 - ?) Right after Link is captured (wolf)
	"京極", // Kyogoku
	0x4d08,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"F_0629",
	"629 酒場のジョバンニに話してから、ゲンゴロウと初めての会話", // First conversation iwth Gengle after speaking with Jovani at the bar
	"一角", // Ikkaku
	0x4d10,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0628",
	"628 ゲンゴロウに200ルピーもらった", // Received 200 Rupees from Gengle
	"一角", // Ikkaku
	0x4d20,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0627",
	"627 酒場のジョバンニに話した", // Spoke with Jovani at the bar
	"一角", // Ikkaku
	0x4d40,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0626",
	"626 ジョバンニにハートのかけらもらう", // Received a heart piece from Jovani
	"一角", // Ikkaku
	0x4d80,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0625",
	"625 タロ＆サルを救出", // Saved Talo and a monkey
	"住吉", // Sumiyoshi
	0x4c01,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0624",
	"624 ３日目：ツタに登ってハンジョーに注意された", // 3rd day: Warned by Hanch when climbing vines
	"京極", // Kyogoku
	0x4c02,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0623",
	"623 序盤３日目：蜂に襲われる前のハンジョーと話した", // Opening 3rd day: Spoke to Hanch before being attacked by bees
	"京極", // Kyogoku
	0x4c04,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0622",
	"622 序盤２日目：蜂に襲われる直前のハンジョーと話した", // Opening 2nd day: Spoke to Hanch before being attacked by bees
	"京極", // Kyogoku
	0x4c08,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0621",
	"621 ３日目のハンジョーと初会話（２日目に蜂の巣落とした）", // Spoke to Hanch on 3rd day (knocked down beehive on 2nd day)
	"京極", // Kyogoku
	0x4c10,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0620",
	"620 ニオイマスを初めて釣った", // First caught a Reek Fish
	"京極", // Kyogoku
	0x4c20,
	"F_SP113:ゾーラの里", // Zora's Domain
	0x13,
	0x14,
},
{
	"F_0619",
	"619 F0013:ハイリア湖上ゾーラ兵（大砲の近く）と話した", // Spoke to Zora soldier (near cannon) in Lake Hylia
	"京極", // Kyogoku
	0x4c40,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0618",
	"618 序盤２日目ではちのこをビンにすくった", // Scooped bee larva into bottle on opening 2nd Day 
	"京極（SET梅宮）", // Kyogoku (SET Umemiya)
	0x4c80,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0617",
	"617 F0085:３日目−木刀渡した後のタロ・マロと話した（２回目）", // 3rd Day - Spoke to Talo/Malo after handing over wooden sword (2nd time)
	"京極", // Kyogoku
	0x4b01,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0616",
	"616 F0085:３日目−木刀渡した後のタロ・マロと話した（１回目）", // 3rd Day - Spoke to Talo/Malo after handing over wooden sword (1st time)
	"京極", // Kyogoku
	0x4b02,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0615",
	"615 ラネールの精霊から光を器をもらった", // Recieved vessel of light from Lanayru spirit
	"京極", // Kyogoku
	0x4b04,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0614",
	"614 ２日目−パチチュー直後の強制会話を聞いた", // 2nd Day - Heard forced conversation immediately after the slignshot tutorial
	"京極", // Kyogoku
	0x4b08,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0613",
	"613 0075B:パチンコチュートリアル−かかし頭２個未達成で話した", // Slingshot Tutorial - Spoke before getting 2 scarecrow heards
	"京極", // Kyogoku
	0x4b10,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0612",
	"612 0075A:パチンコチュートリアル−的に当てる前に話した", // Pachinco Tutorial - Spoke before hitting target
	"京極", // Kyogoku
	0x4b20,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0611",
	"611 0074:パチンコチュートリアル−注目してあてた", // Slingshot Tutorial - Hit it using focusing
	"京極", // Kyogoku
	0x4b40,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0610",
	"610 0073:パチンコチュートリアル−注目しないであてた", // Slingshot Tutorial - Hit it without using focus
	"京極", // Kyogoku
	0x4b80,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0609",
	"609 0072:パチンコチュートリアル−かかし胴体初ヒット", // Slingshot Tutorial - First time hitting scarcrow torso
	"京極", // Kyogoku
	0x4a01,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0608",
	"608 パチンコチュートリアル開始した", // Began Slingshot tutorial
	"京極", // Kyogoku
	0x4a02,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0607",
	"607 パチンコチュートリアル中断した", // Quit Slingshot tutorial
	"京極", // Kyogoku
	0x4a04,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0606",
	"606 巨人入れ替わった", // Giants switched places
	"住吉", // Sumiyoshi
	0x4a08,
	"F_SP117:聖なる森", // Sacred Grove
	0x17,
	0x18,
},
{
	"F_0702",
	"605 捕われているタロを確認した", // Confirmed kidnapped Talo
	"住吉", // Sumiyoshi
	0x4a10,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0701",
	"604 リンクの家前庭でタロがサルを発見", // Talo discovers monkey in Link's house garden
	"木村", // Kimura
	0x4a20,
	"***",
	0x0,
	0x1,
},
{
	"F_0700",
	"603 初日終了", // First day ends
	"木村", // Kimura
	0x4a40,
	"***",
	0x0,
	0x1,
},
{
	"F_0601",
	"601 オリに捕まっているタロと話した", // Spoke to imprisoned Talo
	"京極", // Kyogoku
	0x4901,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0600",
	"600 パチンコ購入", // Purchase slingshot
	"京極", // Kyogoku
	0x4902,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0599",
	"599 ２日目−ボウの家に入ろうとした", // 2nd Day - tried to enter Bo's house
	"京極", // Kyogoku
	0x4904,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0598",
	"598 ２日目−ボウと初会話（山羊倒し成功前）", // 2nd Day - First conversation with Bo
	"京極", // Kyogoku
	0x4908,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0597",
	"597 ２日目−ボウと初会話（山羊倒し成功後）", // 2nd Day - First time speaking with Bo (after successfully defeating mountain goat)
	"京極", // Kyogoku
	0x4910,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0596",
	"596 F0003:２日目－コリン剣チュー後～馬拒絶までに会話", // 2nd Day - Conversation with Colin after sword tutorial, before horse rejection
	"京極", // Kyogoku
	0x4920,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0595",
	"595 F0003:２日目−コリン剣チュー後の馬拒絶後に会話", // 2nd Day - Conversation with Colin after sword tutorial and after horse rejection
	"京極", // Kyogoku
	0x4940,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0594",
	"594 F0003:２日目−コリン（キコルからカンテラ入手後に会話）", // 2nd Day - Colin (conversation after receiving lantern from Coro)
	"京極", // Kyogoku
	0x4980,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0593",
	"593 F0049:２日目−ベス−タロ失踪直後に話した", // 2nd Day - Conversation with Beth right after Talo's disappearance
	"京極", // Kyogoku
	0x4801,
	"F_SP104:トアル森", // Ordon Woods
	0xe,
	0xf,
},
{
	"F_0592",
	"592 F0050:２日目−ベス−タロ失踪中（カンテラゲット後）に話した", // 2nd Day - Spoke with Beth during Talo's disappearance (after getting lantern)
	"京極", // Kyogoku
	0x4802,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0591",
	"591 F0060:２日目−マロ−タロ失踪直後に話した", // 2nd Day - Spoke to Malo right after Talo disappears
	"京極", // Kyogoku
	0x4804,
	"F_SP104:トアル森", // Ordon Woods
	0xe,
	0xf,
},
{
	"F_0590",
	"590 F0061:２日目−マロ−タロ失踪中（カンテラゲット後）に話した", // 2nd Day - Spoke to Malo during Talo's disappearance  (after getting lantern)
	"京極", // Kyogoku
	0x4808,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0589",
	"589 F0062:セーラ−１日目に話した", // Sera - spoke on first day
	"京極", // Kyogoku
	0x4810,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0588",
	"588 ３日目−暴走山羊を初めて逃がした", // First time letting rampaging mountain goat escape
	"京極", // Kyogoku
	0x4820,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0587",
	"587 ３日目−暴走山羊倒し成功", // successfully defeated rampaging mountain goat
	"京極（住吉セット）",
	0x4840,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0586",
	"586 ３日目−山羊倒し成功後にボウと話した", // Spoke to Bo after defeating mountain goat
	"京極", // Kyogoku
	0x4880,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0585",
	"585 １日目−ボウと話した", // 1st day - Spoke to Bo
	"京極", // Kyogoku
	0x4701,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0584",
	"584 １日目−モイと話した", // 1st Day - spoke to Rusl
	"京極", // Kyogoku
	0x4702,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0583",
	"583 １日目−イリアと草笛を【吹いた後】に話した", // 1st day - Spoke to Ilia after blowing the reed whistle
	"京極", // Kyogoku
	0x4704,
	"F_SP104:トアル森", // Ordon Woods
	0xe,
	0xf,
},
{
	"F_0582",
	"582 １日目−イリアと草笛を【吹く前】に話した", // 1st Day - spoke to Ilia before blowing the reed whistle
	"京極", // Kyogoku
	0x4708,
	"F_SP104:トアル森", // Ordon Woods
	0xe,
	0xf,
},
{
	"F_0581",
	"581 ２日目−初めてトビ草を吹いてタカを呼んだ", // 2nd Day - First time calling the hawk using the grass whistle
	"京極", // Kyogoku
	0x4710,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0580",
	"580 １日目−トアル泉でエポナの草笛を吹いた", // 1st Day - Blew on Epona's reed whistle at Ordon Spring
	"京極", // Kyogoku
	0x4720,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0579",
	"579 序盤（２日目）蜂に襲われる前のハンジョーと初会話", // Opening (2nd day) First time talking with Hanch before being attacked by bees
	"京極", // Kyogoku
	0x4740,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0578",
	"578 F0084:３日目のベスと話した", // Spoke to Beth on 3rd day
	"京極", // Kyogoku
	0x4780,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0577",
	"577 ２日目−サルからカゴを取り返した（鷹を当てた）", // 2nd Day - Retrieved basket from monkey (hit hawk)
	"京極（森田使用）", // Kyogoku (used by Morita)
	0x4601,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0576",
	"576 ２日目−ファドと話した", // 2nd Day - Spoke with Fado
	"京極", // Kyogoku
	0x4602,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0575",
	"575 １日目−夕方の山羊追いエンド", // 1st Day - End mountain goat chasing in evening
	"京極", // Kyogoku
	0x4604,
	"F_SP00:牧場", // Ranch
	0xc,
	0xd,
},
{
	"F_0574",
	"574 １日目−夕方の山羊追いスタート", // 1st Day - Start mountain goat chasing in evening
	"京極", // Kyogoku
	0x4608,
	"F_SP00:牧場", // Ranch
	0xc,
	0xd,
},
{
	"F_0573",
	"573 １日目−ファドが牧場に移動（リンク家前から消える）", // 1st Day - Fado moves to the farm (disappears from in front of Link's house)
	"京極", // Kyogoku
	0x4610,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0572",
	"572 F0027:３日目タロの願い（木刀くれ）を断った（再）", // Refuse Talo's request (for wooden sword) on 3rd day (again)
	"京極", // Kyogoku
	0x4620,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0571",
	"571 F0027:３日目タロの願い（木刀くれ）を断った（初）", // Refuse Talo's request (for wooden sword) on 3rd day (first time)
	"京極", // Kyogoku
	0x4640,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0570",
	"570 LV8ダンジョンクリア", // Cleared LV8 dungeon
	"京極", // Kyogoku
	0x4680,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0569",
	"569 ホヅに弁償請求され中（払ったらリセット）", // Compensation demands from Iza (resets if paid)
	"京極", // Kyogoku
	0x4501,
	"F_SP112:ゾーラ川", // Zora's River
	0x12,
	0x13,
},
{
	"F_0568",
	"568 ホヅのマトを壊した（初犯）", // Broke Iza's pots (first offence)
	"京極", // Kyogoku
	0x4502,
	"F_SP112:ゾーラ川", // Zora's River
	0x12,
	0x13,
},
{
	"F_0567",
	"567 おばちゃんから手紙来てＯＫ（息子○）", // Letter from Ooccoo Sr. came in OK (yes son)
	"京極", // Kyogoku
	0x4504,
	"おばちゃん関連", // Ooccoo Sr. stuff
	0x1f,
	0x20,
},
{
	"F_0566",
	"566 おばちゃんから手紙来てＯＫ（息子×）", // Letter from Ooccoo Sr. came in OK (no son)
	"京極", // Kyogoku
	0x4508,
	"おばちゃん関連", // Ooccoo Sr. stuff
	0x1f,
	0x20,
},
{
	"F_0565",
	"565 【２日目終了】", // 2nd Day Complete
	"京極", // Kyogoku
	0x4510,
	"***",
	0x0,
	0x1,
},
{
	"F_0564",
	"564 TWテルマの店の兵士の話を聞いた", // Heard story from solder at Telma's shop (during Twilight)
	"京極", // Kyogoku
	0x4520,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0563",
	"563 ゲンゴロウ復活（魂５０ゲット時にプログラムで対応）", // Brought back Gengle (after getting 50 souls, dealt with by program)
	"P",
	0x4540,
	"その他", // Misc.
	0x20,
	0x21,
},
{
	"F_0562",
	"562 ＬＶ８ダンジョン制御用１２", // LV8 Dungeon control use 12
	"京極（酒井さん使用）", // Kyogoku (used by Sakai)
	0x4580,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0561",
	"561 ＬＶ８ダンジョン制御用１１", // LV8 Dungeon control use 11
	"京極（酒井さん使用）", // Kyogoku (used by Sakai)
	0x4401,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0560",
	"560 ＬＶ８ダンジョン制御用１０", // LV8 Dungeon control use 10
	"京極（酒井さん使用）", // Kyogoku (used by Sakai)
	0x4402,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0559",
	"559 ＬＶ８ダンジョン制御用９", // LV8 Dungeon control use 9
	"京極（酒井さん使用）", // Kyogoku (used by Sakai)
	0x4404,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0558",
	"558 ＬＶ８ダンジョン制御用８", // LV8 Dungeon control use 8
	"京極（酒井さん使用）", // Kyogoku (used by Sakai)
	0x4408,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0557",
	"557 ＬＶ８ダンジョン制御用７", // LV8 Dungeon control use 7
	"京極（酒井さん使用）", // Kyogoku (used by Sakai)
	0x4410,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0556",
	"556 ＬＶ８ダンジョン制御用６", // LV8 Dungeon control use 6
	"京極（酒井さん使用）", // Kyogoku (used by Sakai)
	0x4420,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0555",
	"555 ＬＶ８ダンジョン制御用５", // LV8 Dungeon control use 5
	"京極（酒井さん使用）", // Kyogoku (used by Sakai)
	0x4440,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0554",
	"554 ＬＶ８ダンジョン制御用４", // LV8 Dungeon control use 4
	"京極（酒井さん使用）", // Kyogoku (used by Sakai)
	0x4480,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0553",
	"553 ＬＶ８ダンジョン制御用３", // LV8 Dungeon control use 3
	"京極（酒井さん使用）", // Kyogoku (used by Sakai)
	0x4301,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0552",
	"552 ＬＶ８ダンジョン制御用２", // LV8 Dungeon control use 2
	"京極（酒井さん使用）", // Kyogoku (used by Sakai)
	0x4302,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0551",
	"551 ＬＶ８ダンジョン制御用１", // LV8 Dungeon control use 1
	"京極（酒井さん使用）", // Kyogoku (used by Sakai)
	0x4304,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0550",
	"550 センスが使えるようになる", // Gain ability to use sense
	"京極", // Kyogoku
	0x4308,
	"メインイベント", // main event
	0x22,
	0x23,
},
{
	"F_0549",
	"549 おばさんA[、]B[、]兵士セット（水の話）の話を聞いた（水無し時）", // Heard old lady A, B, soldier set (talking about water) (when there's no water)
	"京極", // Kyogoku
	0x4310,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0548",
	"548 序盤３日目−ジャガーと話した", // Opening 3rd day - spoke with Jaggle
	"京極", // Kyogoku
	0x4320,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0547",
	"547 ゴースト４０個集めてジョバンニと会話", // conversation with Jovani after collecting 40 ghosts
	"一角", // Ikkaku
	0x4340,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0546",
	"546 東・門前兵士と光（橋不通時に）話した", // East - Spoke with soldier in front of east gate about light (while bridge is broken)
	"京極", // Kyogoku
	0x4380,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0545",
	"545 おばちゃんと別れのデモ（ＬＶ６後）見た", // Watched cutscene of Ooccoo Sr. parting (after LV6)
	"京極", // Kyogoku
	0x4201,
	"F_SP117:聖なる森", // Sacred Grove
	0x17,
	0x18,
},
{
	"F_0544",
	"544 パペットに襲われて逃げてくるメスザルデモ見た", // Watched cutscene of monkey girl running away after being attacked by puppet
	"京極（森田使用）", // Kyogoku (used by Morita) // Kyogoku (for Morita use)
	0x4202,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0543",
	"543 レジスタンスモイと森で再会した", // Met Resistance Rusl again in the woods
	"京極", // Kyogoku
	0x4204,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0542",
	"542 【デモ】ガノンウォールがなくなる（ミドナ暴走）", // [Cutscene] Ganon wall disappears (Midna goes crazy)
	"京極", // Kyogoku
	0x4208,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"F_0541",
	"541 @",
	"京極（住吉さん使用）", // Kyogoku (for use by Mr. Sumiyoshi)
	0x4210,
	"***",
	0x0,
	0x1,
},
{
	"F_0540",
	"540 初ポータルワープ直後のミドナヒント聞いた", // Heard hint from Midna right after first portal warp
	"京極", // Kyogoku
	0x4220,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0539",
	"539 ファドに山羊追いでハートのかけらもらった", // Receieved heart piece from Fado for mountain goat chase
	"京極", // Kyogoku
	0x4240,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0538",
	"538 LV7ダンクリア後に天空人のおばちゃんと話した", // Spoke with sky person Oocoo Sr. after clearing LV7 dungeon
	"京極", // Kyogoku
	0x4280,
	"D_MN07:LV7ダンジョン", // LV7 dungeon
	0x7,
	0x8,
},
{
	"F_0537",
	"537 キコルと狼会話した", // Had Coro and wolf conversation
	"京極", // Kyogoku
	0x4101,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0536",
	"536 水中ゴロンとお礼もらう前に話した", // Spoke with goron in water before recieving reward
	"京極", // Kyogoku
	0x4102,
	"F_SP113:ゾーラの里", // Zora's Domain
	0x13,
	0x14,
},
{
	"F_0535",
	"535 水中ゴロンとお礼（ボム袋）後に話した", // Spoke with goron in water after recieving reward (bomb bag)
	"京極", // Kyogoku
	0x4104,
	"F_SP113:ゾーラの里", // Zora's Domain
	0x13,
	0x14,
},
{
	"F_0534",
	"534 子ども発見前にファドと話した", // Spoke with Fado before finding children
	"京極", // Kyogoku
	0x4108,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0533",
	"533 子供発見後にファドと話した", // Spoke with Fado after finding children
	"京極", // Kyogoku
	0x4110,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0532",
	"532 キュリーに盾のこと突っ込まれる", // Pergie butts in about a shield
	"京極", // Kyogoku
	0x4120,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0531",
	"531 子どもさらわれ中にキュリーと話した", // Spoke with Pergie while children are kidnapped
	"京極", // Kyogoku
	0x4140,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0530",
	"530 子ども発見後にキュリーと話した", // Spoke with Pergie after finding children
	"京極", // Kyogoku
	0x4180,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0529",
	"529 LV6ダンクリア後のモイと話した", // Spoke with Rusl after clearing LV6 dungion
	"京極", // Kyogoku
	0x4001,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0528",
	"528 レジスタンスモイ、金コッコ召喚した", // Resistance Rusl summoned golden cucco
	"京極", // Kyogoku
	0x4002,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0527",
	"527 レジスタンスモイの頼みを断った", // Refused Resistance Rusl's request
	"京極", // Kyogoku
	0x4004,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0526",
	"526 【デモ : 23】正体を明かすミドナ", // [Cutscene: 23] Midna reveals her true form
	"京極", // Kyogoku
	0x4008,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"F_0525",
	"525 水中爆弾売りゾーラと初会話", // First conversation with underwater Zora bomb seller
	"京極", // Kyogoku
	0x4010,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0524",
	"524 子ども発見後にハンジョーと話した", // Spoke with Hanch after finding children
	"京極", // Kyogoku
	0x4020,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0523",
	"523 子ども発見前にハンジョーと話した", // Spoke with Hanch before finding children
	"京極", // Kyogoku
	0x4040,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0522",
	"522 助けたメスザルに聖なる森の話聞いた", // Heard about Sacred Grove from saved monkey girl
	"京極", // Kyogoku
	0x4080,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0521",
	"521 子ども発見後にセーラとカウンター越しに話した（以降、台詞短縮）", // Spoke with Sera across the counter after finding children (her script is shortened after this)
	"京極", // Kyogoku
	0x3f01,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0520",
	"520 子ども発見後にセーラと話した", // Spoke with Sera after finding children
	"京極", // Kyogoku
	0x3f02,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0519",
	"519 子ども発見後にジャガーと会話した", // Spoke with Juggle after finding children
	"京極", // Kyogoku
	0x3f04,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0518",
	"518 コリン誘拐～寝込み中のウーリからコリンに手紙出した話聞いた", // Colin kidnapped ~ Heard about giving letter to Colin from sleeping Uli
	"京極", // Kyogoku
	0x3f08,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0517",
	"517 子ども発見後（コリン誘拐前）ウーリと通常会話１した", // Had normal conversation 1 with Uli after finding kids (before Colin kidnapped)
	"京極", // Kyogoku
	0x3f10,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0516",
	"516 ウーリに子ども発見のこと自分で伝えた", // Told Uli directly about having found kids
	"京極", // Kyogoku
	0x3f20,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0515",
	"515 イリア・ラルス復活後にコリンと話した", // Spoke with Colin after Ilia and Ralis are revived
	"京極", // Kyogoku
	0x3f40,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0514",
	"514 イリア復活前、ラルス帰還後にコリンと話した", // Spoke with Colin after Ralis is revived but before Ilia is revived
	"京極", // Kyogoku
	0x3f80,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0513",
	"513 イリアもラルスも元気ナシ時にコリンと話した", // Spoke with Colin when neither Ilia nor Ralis are doing well
	"京極", // Kyogoku
	0x3e01,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0510",
	"510 LV7ダンスタートデモを見た", // Watched LV7 dungion start cutscene
	"京極", // Kyogoku
	0x3e02,
	"D_MN07:LV7ダンジョン", // LV7 dungeon
	0x7,
	0x8,
},
{
	"F_0509",
	"509 おばちゃんと２度目の対面", // Met Ooccoo Sr. second time
	"京極", // Kyogoku
	0x3e04,
	"おばちゃん関連", // Ooccoo Sr. stuff
	0x1f,
	0x20,
},
{
	"F_0508",
	"508 おばちゃんに会ったB※OFFにしない（LV1-LV5共通）", // Meb Ooccoo Sr. B - doesnt turn OFF (shared LV1-LV5)
	"京極", // Kyogoku
	0x3e08,
	"おばちゃん関連", // Ooccoo Sr. stuff
	0x1f,
	0x20,
},
{
	"F_0507",
	"507 おばちゃんと初対面のダンジョンで息子にも会った※506はOFFに(LV1-LV5共通)", // Also met the son in dungeon with first Ooccoo Sr. meeting - turns 506 OFF (shared LV1-LV5)
	"京極", // Kyogoku
	0x3e10,
	"***",
	0x0,
	0x1,
},
{
	"F_0506",
	"506 おばちゃんにだけ会った※息子まだ(LV1-LV5共通)", // Only met Ooccoo Sr. - not yet son (shared LV1-LV5)
	"京極", // Kyogoku
	0x3e20,
	"***",
	0x0,
	0x1,
},
{
	"F_0505",
	"505 試練の洞窟−B50初到着（クリア）", // Cave of Ordeals - B50 first arrival (clear)
	"京極", // Kyogoku
	0x3e40,
	"サブダンジョン", // sub-dungeon
	0x21,
	0x22,
},
{
	"F_0504",
	"504 試練の洞窟−B40初到着", // Cave of Ordeals - B40 first arrival
	"京極", // Kyogoku
	0x3e80,
	"サブダンジョン", // sub-dungeon
	0x21,
	0x22,
},
{
	"F_0503",
	"503 試練の洞窟−B30初到着", // Cave of Ordeals - B30 first arrival
	"京極", // Kyogoku
	0x3d01,
	"サブダンジョン", // sub-dungeon
	0x21,
	0x22,
},
{
	"F_0502",
	"502 試練の洞窟−B20初到着", // Cave of Ordeals - B20 first arrival
	"京極", // Kyogoku
	0x3d02,
	"サブダンジョン", // sub-dungeon
	0x21,
	0x22,
},
{
	"F_0501",
	"501 試練の洞窟−B10初到着", // Cave of Ordeals - B10 first arrival
	"京極", // Kyogoku
	0x3d04,
	"サブダンジョン", // sub-dungeon
	0x21,
	0x22,
},
{
	"F_0500",
	"500 子ども発見前にウーリに会ってる（寝てるモイを見てる）", // Met Uli before finding kids (look at sleeping Rusl)
	"京極", // Kyogoku
	0x3d08,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0499",
	"499 溶岩弾ゴロンを救出した", // Saved magma goron
	"京極", // Kyogoku
	0x3d10,
	"F_SP113:ゾーラの里", // Zora's Domain
	0x13,
	0x14,
},
{
	"F_0498",
	"498 ラルス帰還後にベスと話した", // Spoke with Beth after Lalis is revived
	"京極", // Kyogoku
	0x3d20,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0497",
	"497 ゴールドウルフ消去７", // Gold wolf disappearance 7
	"京極", // Kyogoku
	0x3d40,
	"奥義", // Secret techniques
	0x23,
	0x24,
},
{
	"F_0496",
	"496 ゴールドウルフ消去６", // Gold wolf disappearance 6
	"京極", // Kyogoku
	0x3d80,
	"奥義", // Secret techniques
	0x23,
	0x24,
},
{
	"F_0495",
	"495 ゴールドウルフ消去５", // Gold wolf disappearance 5
	"京極", // Kyogoku
	0x3c01,
	"奥義", // Secret techniques
	0x23,
	0x24,
},
{
	"F_0494",
	"494 ゴールドウルフ消去４", // Gold wolf disappearance 4
	"京極", // Kyogoku
	0x3c02,
	"奥義", // Secret techniques
	0x23,
	0x24,
},
{
	"F_0493",
	"493 ゴールドウルフ消去３", // Gold wolf disappearance 3
	"京極", // Kyogoku
	0x3c04,
	"奥義", // Secret techniques
	0x23,
	0x24,
},
{
	"F_0492",
	"492 ゴールドウルフ消去２", // Gold wolf disappearance 2
	"京極", // Kyogoku
	0x3c08,
	"奥義", // Secret techniques
	0x23,
	0x24,
},
{
	"F_0491",
	"491 LV2ダンクリア後に中ボス（マグネゴロン）と話した", // Spoke with mini-boss (magnet goron) after LV2 dungeon clear
	"京極", // Kyogoku
	0x3c10,
	"D_MN04:LV2ダンジョン", // LV2 Dungeon
	0x4,
	0x5,
},
{
	"F_0490",
	"490 コッコAと話した（リンク食った疑惑）", // Spoke with cucco (thinks Link will eat him)
	"京極", // Kyogoku
	0x3c20,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0489",
	"489 ボム屋前ゴロンと会話−爆弾全種登場", // Conversation with goron in front of bomb shop - all bomb types appear
	"京極", // Kyogoku
	0x3c40,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0488",
	"488 ボム屋前ゴロンと会話−水中爆弾登場", // Conversation with goron in front of bomb shop - underwater bomb appears
	"京極", // Kyogoku
	0x3c80,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0487",
	"487 ラルス帰った後にルダと会話", // Spoke with Luda after Ralis returns home
	"京極", // Kyogoku
	0x3b01,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0486",
	"486 ラルス墓参り中にルダと会話した", // Spoke with Luda while Ralis is visiting graveyard
	"京極", // Kyogoku
	0x3b02,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0485",
	"485 トビーから修理の話を１度聞いた", // Heard Fyer talk about repairs 1 time
	"京極", // Kyogoku
	0x3b04,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0484",
	"484 天空大砲修理完了！", // Completed sky canon repairs!
	"京極", // Kyogoku
	0x3b08,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0483",
	"483 雪女にスノボで初めて勝った（ハートのかけら）", // First beat Yeta at snowboard (heart piece)
	"京極", // Kyogoku
	0x3b10,
	"F_SP114:雪山", // Snowpeak mountain
	0x14,
	0x15,
},
{
	"F_0482",
	"482 雪男に勝利後、雪女と頂上で初会話（勝負を挑まれる）", // After beating Yeto, first conversation with Yeta at peack (challanged to a match)
	"京極", // Kyogoku
	0x3b20,
	"***",
	0x0,
	0x1,
},
{
	"F_0481",
	"481 雪男にスノボで初めて勝った", // Beat Yeta at snowboard first time
	"京極", // Kyogoku
	0x3b40,
	"F_SP114:雪山", // Snowpeak mountain
	0x14,
	0x15,
},
{
	"F_0480",
	"480 ラルスから珊瑚の耳飾りもらった", // Received Coral Earrings from Ralis
	"京極", // Kyogoku
	0x3b80,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0479",
	"479 墓前のラルスと初会話", // First conversation with Ralis in front of grave
	"京極", // Kyogoku
	0x3a01,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0478",
	"478 ゾーラの里に戻ったラルスと会話", // Spoke to Ralis who returned to Zora's domain
	"京極", // Kyogoku
	0x3a02,
	"F_SP113:ゾーラの里", // Zora's Domain
	0x13,
	0x14,
},
{
	"F_0477",
	"477 遠吠え完了（奥義７用）", // Distant howling complete (for secret technique 7)
	"京極", // Kyogoku
	0x3a04,
	"奥義", // Secret techniques
	0x23,
	0x24,
},
{
	"F_0476",
	"476 遠吠え完了（奥義６用）", // Distant howling complete (for secret technique 6)
	"京極", // Kyogoku
	0x3a08,
	"奥義", // Secret techniques
	0x23,
	0x24,
},
{
	"F_0475",
	"475 遠吠え完了（奥義５用）", // Distant howling complete (for secret technique 5)
	"京極", // Kyogoku
	0x3a10,
	"奥義", // Secret techniques
	0x23,
	0x24,
},
{
	"F_0474",
	"474 遠吠え完了（奥義４用）", // Distant howling complete (for secret technique 4)
	"京極", // Kyogoku
	0x3a20,
	"奥義", // Secret techniques
	0x23,
	0x24,
},
{
	"F_0473",
	"473 遠吠え完了（奥義３用）", // Distant howling complete (for secret technique 3)
	"京極", // Kyogoku
	0x3a40,
	"奥義", // Secret techniques
	0x23,
	0x24,
},
{
	"F_0472",
	"472 遠吠え完了（奥義２用）", // Distant howling complete (for secret technique 2)
	"京極", // Kyogoku
	0x3a80,
	"奥義", // Secret techniques
	0x23,
	0x24,
},
{
	"F_0471",
	"471 ボウとの相撲２回戦終了", // Finished 2 wrestling matches against Bo
	"京極", // Kyogoku
	0x3901,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0470",
	"470 釣り用予約", // Reserved for fishing
	"京極", // Kyogoku
	0x3902,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0469",
	"469 釣り用予約", // Reserved for fishing
	"京極", // Kyogoku
	0x3904,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0468",
	"468 釣り用予約", // Reserved for fishing
	"京極", // Kyogoku
	0x3908,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0467",
	"467 釣り用予約",
	"京極", // Kyogoku
	0x3910,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0466",
	"466 釣り用予約", // Reserved for fishing
	"京極", // Kyogoku
	0x3920,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0465",
	"465 釣り用予約", // Reserved for fishing
	"京極", // Kyogoku
	0x3940,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0464",
	"464 釣り用予約", // Reserved for fishing
	"京極", // Kyogoku
	0x3980,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0463",
	"463 釣り用予約", // Reserved for fishing
	"京極", // Kyogoku
	0x3801,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0462",
	"462 釣り用予約", // Reserved for fishing
	"京極", // Kyogoku
	0x3802,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0461",
	"461 つりぼりハウスに初めて入店した", // First time entered fishing house
	"京極（森田使用）", // Kyogoku (used by Morita) // Kyogoku (for Morita use)
	0x3804,
	"釣り", // Fishing
	0x28,
	0x29,
},
{
	"F_0460",
	"460 ゴースト５０個集めてゲンゴロウと会話", // Coversation with Gengle after collecting 50 ghosts
	"京極", // Kyogoku
	0x3808,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0459",
	"459 ゴースト４０個集めてゲンゴロウと会話", // Coversation with Gengle after collecting 40 ghosts
	"京極", // Kyogoku
	0x3810,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0458",
	"458 ゴースト６０個集めてジョバンニと会話", // Coversation with Jovani after collecting 60 ghosts
	"京極", // Kyogoku
	0x3820,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0457",
	"457 猫復活", // Revived cat
	"京極", // Kyogoku
	0x3840,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0456",
	"456 ジョバンニと初対面", // First time meeting with Jovani
	"京極", // Kyogoku
	0x3880,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0455",
	"455 募金長老から３個目のカギもらった(205)", // Recieved 3rd key from fundraising elder (205)
	"京極", // Kyogoku
	0x3701,
	"D_MN04:LV2ダンジョン", // LV2 Dungeon
	0x4,
	0x5,
},
{
	"F_0454",
	"454 募金長老から２個目のカギもらった(206)", // Recieved 3rd key from fundraising elder (206)
	"京極", // Kyogoku
	0x3702,
	"D_MN04:LV2ダンジョン", // LV2 Dungeon
	0x4,
	0x5,
},
{
	"F_0453",
	"453 ポストマン初登場", // Postman first appears
	"京極", // Kyogoku
	0x3704,
	"環状フィールド", // Ring field
	0x25,
	0x26,
},
{
	"F_0450",
	"450 Wクローショット屋最終段階初会話", // Double Clawshot shop final stage first conversation
	"京極", // Kyogoku
	0x3708,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0449",
	"449 ドン・レゲーヌと再会話−温泉水親ゴロンと会話後初（募金前）", // Talk with Gor Liggs again - first time after talking iwth Hot spring water parent goron (before fundraising)
	"京極", // Kyogoku
	0x3710,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0448",
	"448 【ビン捕獲中】カゲロウ♀", // [Captured in bottle] Dayfly (F)
	"京極", // Kyogoku
	0x3720,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0447",
	"447 【ビン捕獲中】カゲロウ♂", // [Captured in bottle] Dayfly (M)
	"京極", // Kyogoku
	0x3740,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0446",
	"446 【ビン捕獲中】アリ♀", // [Captured in bottle] Ant (F)
	"京極", // Kyogoku
	0x3780,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0445",
	"445 【ビン捕獲中】アリ♂", // [Captured in bottle] Ant (M)
	"京極", // Kyogoku
	0x3601,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0444",
	"444 【ビン捕獲中】トンボ♀", // [Captured in bottle] Dragonfly (F)
	"京極", // Kyogoku
	0x3602,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0443",
	"443 【ビン捕獲中】トンボ♂", // [Captured in bottle] Dragonfly (M)
	"京極", // Kyogoku
	0x3604,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0442",
	"442 【ビン捕獲中】カタツムリ♀", // [Captured in bottle] Snail (F)
	"京極", // Kyogoku
	0x3608,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0441",
	"441 【ビン捕獲中】カタツムリ♂", // [Captured in bottle] Snail (M)
	"京極", // Kyogoku
	0x3610,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0440",
	"440 【ビン捕獲中】テントウムシ♀", // [Captured in bottle] Ladybug (F)
	"京極", // Kyogoku
	0x3620,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0439",
	"439 【ビン捕獲中】テントウムシ♂", // [Captured in bottle] Ladybug (M)
	"京極", // Kyogoku
	0x3640,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0438",
	"438 【ビン捕獲中】カマキリ♀", // [Captured in bottle] Mantis (F)
	"京極", // Kyogoku
	0x3680,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0437",
	"437 【ビン捕獲中】カマキリ♂", // [Captured in bottle] Mantis (M)
	"京極", // Kyogoku
	0x3501,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0436",
	"436 【ビン捕獲中】ダンゴムシ♀", // [Captured in bottle] Pill bug (F)
	"京極", // Kyogoku
	0x3502,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0435",
	"435 【ビン捕獲中】ダンゴムシ♂", // [Captured in bottle] Pill bug (M)
	"京極", // Kyogoku
	0x3504,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0434",
	"434 【ビン捕獲中】ナナフシ♀", // [Captured in bottle] Phasmid (F)
	"京極", // Kyogoku
	0x3508,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0433",
	"433 【ビン捕獲中】ナナフシ♂", // [Captured in bottle] Phasmid (M)
	"京極", // Kyogoku
	0x3510,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0432",
	"432 【ビン捕獲中】バッタ♀", // [Captured in bottle] Grasshopper (F)
	"京極", // Kyogoku
	0x3520,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0431",
	"431 【ビン捕獲中】バッタ♂", // [Captured in bottle] Grasshopper (M)
	"京極", // Kyogoku
	0x3540,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0430",
	"430 【ビン捕獲中】クワガタ♀", // [Captured in bottle] Stag beetle (F)
	"京極", // Kyogoku
	0x3580,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0429",
	"429 【ビン捕獲中】クワガタ♂", // [Captured in bottle] Stag beetle (M)
	"京極", // Kyogoku
	0x3401,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0428",
	"428 【ビン捕獲中】チョウチョ♀", // [Captured in bottle] Butterfly (F)
	"京極", // Kyogoku
	0x3402,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0427",
	"427 【ビン捕獲中】チョウチョ♂", // [Captured in bottle] Butterfly (M)
	"京極", // Kyogoku
	0x3404,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0426",
	"426 【ビン捕獲中】カブトムシ♀", // [Captured in bottle] Beetle (F)
	"京極", // Kyogoku
	0x3408,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0425",
	"425 【ビン捕獲中】カブトムシ♂", // [Captured in bottle] Beetle (M)
	"京極", // Kyogoku
	0x3410,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0424",
	"424 カゲロウ♀", // Dayfly (F)
	"京極", // Kyogoku
	0x3420,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0423",
	"423 カゲロウ♂", // Dayfly (M)
	"京極", // Kyogoku
	0x3440,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0422",
	"422 アリ♀", // Ant (F)
	"京極", // Kyogoku
	0x3480,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0421",
	"421 アリ♂", // Ant (M)
	"京極", // Kyogoku
	0x3301,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0420",
	"420 トンボ♀", // Dragonfly (F)
	"京極", // Kyogoku
	0x3302,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0419",
	"419 トンボ♂", // Dragonfly (M)
	"京極", // Kyogoku
	0x3304,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0418",
	"418 カタツムリ♀", // Snail (F)
	"京極", // Kyogoku
	0x3308,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0417",
	"417 カタツムリ♂", // Snail (M)
	"京極", // Kyogoku
	0x3310,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0416",
	"416 テントウムシ♀", // Ladybug (F)
	"京極", // Kyogoku
	0x3320,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0415",
	"415 テントウムシ♂", // Ladybug (M)
	"京極", // Kyogoku
	0x3340,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0414",
	"414 カマキリ♀", // Mantis (F)
	"京極", // Kyogoku
	0x3380,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0413",
	"413 カマキリ♂", // Mantis (M)
	"京極", // Kyogoku
	0x3201,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0412",
	"412 ダンゴムシ♀", // Pill bug (F)
	"京極", // Kyogoku
	0x3202,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0411",
	"411 ダンゴムシ♂", // Pill bug (M)
	"京極", // Kyogoku
	0x3204,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0410",
	"410 ナナフシ♀", // Phasmid (F)
	"京極", // Kyogoku
	0x3208,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0409",
	"409 ナナフシ♂", // Phasmid (M)
	"京極", // Kyogoku
	0x3210,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0408",
	"408 バッタ♀", // Grasshopper (F)
	"京極", // Kyogoku
	0x3220,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0407",
	"407 バッタ♂", // Grasshopper (M)
	"京極", // Kyogoku
	0x3240,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0406",
	"406 クワガタ♀", // Stag beetle (F)
	"京極", // Kyogoku
	0x3280,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0405",
	"405 クワガタ♂", // Stag beetle (M)
	"京極", // Kyogoku
	0x3101,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0404",
	"404 チョウチョ♀", // Butterfly (F)
	"京極", // Kyogoku
	0x3102,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0403",
	"403 チョウチョ♂", // Butterfly (M)
	"京極", // Kyogoku
	0x3104,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0402",
	"402 カブトムシ♀", // Beetle (F)
	"京極", // Kyogoku
	0x3108,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0401",
	"401 カブトムシ♂", // Beetle (M)
	"京極", // Kyogoku
	0x3110,
	"黄金虫", // Golden bugs
	0x24,
	0x25,
},
{
	"F_0400",
	"400 天空砲台をハイリア湖にワープした", // Warped sky cannon to Lake Hylia
	"京極", // Kyogoku
	0x3120,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0399",
	"399 ドン・レゲーヌ会話-温泉ゲーム可能", // Conversation with Gor Liggs - hot spring game available
	"京極", // Kyogoku
	0x3140,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0398",
	"398 ドン・レゲーヌ会話シーケンスC", // Gor Liggs conversation sequence C
	"京極", // Kyogoku
	0x3180,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0397",
	"397 ドン・レゲーヌ会話シーケンスB", // Gor Liggs conversation sequence B
	"京極", // Kyogoku
	0x3001,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0396",
	"396 温泉水運び失敗した（長老と話したらリセット）", // Failed to carry hot spring water (speak with elder to reset)
	"京極", // Kyogoku
	0x3002,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0395",
	"395 ドン・レゲーヌとカカリコ村で初会話", // First conversation with Gor Liggs in Kakariko Village
	"京極", // Kyogoku
	0x3004,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0394",
	"394 チビ長老から１個目のカギもらった(204)", // Received first key from chibi elder (204)
	"京極", // Kyogoku
	0x3008,
	"D_MN04:LV2ダンジョン", // LV2 Dungeon
	0x4,
	0x5,
},
{
	"F_0393",
	"393 ポウ屋と初めて会話（汎用ポウ登場）", // First conversation at Poe shop (generic Poe appearance)
	"京極", // Kyogoku
	0x3010,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0392",
	"392 城下町南開通後に穴掘りゴロンと話した", // spoke with goron digging hole after opening caslt town south road
	"京極", // Kyogoku
	0x3020,
	"環状フィールド", // Ring field
	0x25,
	0x26,
},
{
	"F_0391",
	"391 城下町南ゴロンに温泉水渡した", // Gave spring water to goron south of castle town
	"京極", // Kyogoku
	0x3040,
	"環状フィールド", // Ring field
	0x25,
	0x26,
},
{
	"F_0390",
	"390 ジョバンニ救出前に初会話", // First conversation after saving Jovani
	"京極", // Kyogoku
	0x3080,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0389",
	"389 南穴掘りゴロンと初会話", // First conversation with goron digging hole in south
	"京極", // Kyogoku
	0x2f01,
	"環状フィールド", // Ring field
	0x25,
	0x26,
},
{
	"F_0388",
	"388 墓地−シーン切り替え後のラルスと話した（耳飾り入手前）", // Graveyard - Spoke with Ralis after changing scene (before obtaining earrings)
	"京極", // Kyogoku
	0x2f02,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0387",
	"387 薬品のにおいを覚えた", // Learned scent of medicine
	"京極", // Kyogoku
	0x2f04,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0386",
	"386 ポケ虫・地雷発売後にバーンズと会話", // Conversation with Barnes after he starts selling Bomblings and landmines
	"京極", // Kyogoku
	0x2f08,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0385",
	"385 水中爆弾入荷後にバーンズと初会話", // First conversation with Barnes after stocking water bombs
	"京極", // Kyogoku
	0x2f10,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0384",
	"384 温泉水屋　休業中に子ゴロンと話した", // Spring water shop - Spoke with child goron while shop closed
	"京極", // Kyogoku
	0x2f20,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0383",
	"383 温泉水屋オープン後に子どもゴロンと話した", // Spoke with child goron after spring water shop opens
	"京極", // Kyogoku
	0x2f40,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0382",
	"382 倒れているゴロンの嘆きを聞いた（橋壊れ中）", // Listened to laments of fallen goron (while bridge broken)
	"京極", // Kyogoku
	0x2f80,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0381",
	"381 温泉水屋オープン後、親ゴロンと初会話", // First conversation with parent goron after spring water shop opens
	"京極", // Kyogoku
	0x2e01,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0380",
	"380 アゲハと初対面済（虫集め依頼受けた）", // Complete first meeting with Agetha (Recieved bug collection quest)
	"京極", // Kyogoku
	0x2e02,
	"***",
	0x0,
	0x1,
},
{
	"F_0379",
	"379 黄金虫コンプリート完了", // Completed golden bugs
	"京極", // Kyogoku
	0x2e04,
	"***",
	0x0,
	0x1,
},
{
	"F_0378",
	"378 ダルボスが隠れ里の岩壊した", // Darbus destroyed hidden village boulder
	"京極", // Kyogoku
	0x2e08,
	"環状フィールド", // Ring field
	0x25,
	0x26,
},
{
	"F_0377",
	"377 ゴロンの温泉水屋オープン！", // Goron spring water shop open!
	"京極", // Kyogoku
	0x2e10,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0376",
	"376 橋補修費用の募金達成！（プログラムで募金直後にSET）", // Gathered funds for bridge repair! (set by program after raising funds)
	"京極（吉見使用）", // Kyogoku (used by Yoshimi)
	0x2e20,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0375",
	"375 マロマート募金ゴロンと初会話", // First conversation with fundraising goron at Malo Mart
	"京極", // Kyogoku
	0x2e40,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0374",
	"374 ＬＶ２ダンクリア後の相撲部屋でダルボスと会話", // Conversation with Darbus in wrestling room after LV2 dungeon clear
	"京極", // Kyogoku
	0x2e80,
	"F_SP110:デスマウンテン", // Death Mountain
	0x11,
	0x12,
},
{
	"F_0373",
	"373 イリア記憶復活後、ダルボスと会話した", // Coversation with Darbus after Ilia's memories restored
	"京極", // Kyogoku
	0x2d01,
	"F_SP110:デスマウンテン", // Death Mountain
	0x11,
	0x12,
},
{
	"F_0372",
	"372 ネコ救出前にミルクを買おうとした", // Tried to by milk before saving cat
	"京極", // Kyogoku
	0x2d02,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0371",
	"371 ボム屋前ゴロンと初会話した（爆弾のみ販売時）", // First conversation wtih goron in front of bomb shop (while only selling bombs)
	"京極", // Kyogoku
	0x2d04,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0370",
	"370 カカリコ温泉ゴロン（大人）と初会話した", // First converstaion with Karakiko springs goron (adult)
	"京極", // Kyogoku
	0x2d08,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0369",
	"369 見張り小屋前ゴロンと初会話", // First conversation with goron in front of watch tower
	"京極", // Kyogoku
	0x2d10,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0368",
	"368 ホテル前ゴロンと初会話", // First conversation wtih goron in front of hotel
	"京極", // Kyogoku
	0x2d20,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0367",
	"367 LV2ダンクリア後に登山道入り口通せんぼゴロンと話した", // Spoke with goron blocking mountain path after LV2 dungeon clear
	"京極", // Kyogoku
	0x2d40,
	"F_SP110:デスマウンテン", // Death Mountain
	0x11,
	0x12,
},
{
	"F_0366",
	"366 イリア記憶復活後にドン・コローネと話した", // Spoke with Gor Liggs after Ilia's memories restored
	"京極", // Kyogoku
	0x2d80,
	"R_SP110:デスマウンテン(部屋)", // Death Mountain (room)
	0x1b,
	0x1c,
},
{
	"F_0365",
	"365 LV2ダンクリア後にドン・コローネと話した", // Spoke with Gor Liggs after LV dungeon clear
	"京極", // Kyogoku
	0x2c01,
	"R_SP110:デスマウンテン(部屋)", // Death Mountain (room)
	0x1b,
	0x1c,
},
{
	"F_0364",
	"364 TWメスザルの嘆きを聞いた", // Listened to monkey girl's laments (Twilight)
	"京極", // Kyogoku
	0x2c02,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0363",
	"363 夜のトアル村でモイから剣奪った（狼）", // Stole sword from Rusl in Ordon Village at night (wolf)
	"京極", // Kyogoku
	0x2c04,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0362",
	"362 レジスタンスモイとちゃんと再会の会話した（２回目）", // Properly spoke with Resistance Rusl again (2nd time)
	"京極", // Kyogoku
	0x2c08,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0361",
	"361 スピナー柱まわした", // Spun the spinning pillars
	"京極", // Kyogoku
	0x2c10,
	"D_MN10:LV4ダンジョン", // LV4 Dungeon,
	0x9,
	0xa,
},
{
	"F_0360",
	"360 占い師と狼で会話", // Conversation with fortune teller as wolf
	"京極", // Kyogoku
	0x2c20,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0359",
	"359 ラルス看病中のイリアと話した", // Spoke with Ilia while she's watching over Ralis
	"京極", // Kyogoku
	0x2c40,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0358",
	"358 イリアの記憶復活後にテルマと会話した", // Spoke with Telma after Ilia's memories restored
	"京極", // Kyogoku
	0x2c80,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0357",
	"357 帰ってきたテルマ用心棒ゴロンと話した", // Spoke with Telma's guardian goron after she came back
	"京極", // Kyogoku
	0x2b01,
	"F_SP110:デスマウンテン", // Death Mountain
	0x11,
	0x12,
},
{
	"F_0356",
	"356 イリアの記憶復活後に町医者と会話した", // Spoke with village doctor after Ilia's memories restored
	"京極", // Kyogoku
	0x2b02,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0355",
	"355 町医者に木彫りの像を見せた", // Showed wood carving to village doctor
	"京極", // Kyogoku
	0x2b04,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0354",
	"354 【デモ】鏡完成", // [cutscene] Mirror complete
	"京極", // Kyogoku
	0x2b08,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"F_0353",
	"353 セレブショップの文句を言うおばさんと会話（F1094）", // Conversation with lady complaining about Chudley's shop
	"京極", // Kyogoku
	0x2b10,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0352",
	"352 アゲハと２回目の会話（屋外）", // Second conversation with Agetha (outside)
	"京極", // Kyogoku
	0x2b20,
	"環状フィールド", // Ring field
	0x25,
	0x26,
},
{
	"F_0351",
	"351 屋外でアゲハと初対面（屋内でも会ってない）：虫イベント依頼された", // First meeting with Agether outside (haven't met inside yet) : gives bug even quest
	"京極", // Kyogoku
	0x2b40,
	"環状フィールド", // Ring field
	0x25,
	0x26,
},
{
	"F_0350",
	"350 レナードに木彫りの人形を見せた", // Showed wood carving doll to Renado
	"京極", // Kyogoku
	0x2b80,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0349",
	"349 LV3ダン前ゾーラ兵士と会話した（入り口爆破後）", // Spoke with Zora soldier in front of LV3 dungeon (after bombing entrance)
	"京極", // Kyogoku
	0x2a01,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0348",
	"348 LV3ダン前ゾーラ兵士と会話した（入り口爆破前）", // Spoke with Zora soldier in front of LV3 dungeon (before bombing entrance)
	"京極", // Kyogoku
	0x2a02,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0347",
	"347 LV5ダンクリア後にアッシュと話した", // Spoke with Ashei after LV5 dungeon clear 
	"京極", // Kyogoku
	0x2a04,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0346",
	"346 ラフレルの砂漠行きの頼みを断った", // Turned down Auru's request to go to the desert
	"京極", // Kyogoku
	0x2a08,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0345",
	"345 序盤２日目−キコルの鍋に点火した", // Opening 2nd day - lit Coro's pot
	"京極", // Kyogoku
	0x2a10,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0344",
	"344 奥義７習得", // Obtained 7 secret techinques
	"京極", // Kyogoku
	0x2a20,
	"奥義", // Secret techniques
	0x23,
	0x24,
},
{
	"F_0343",
	"343 奥義６習得", // Obtained 6 secret techinques
	"京極", // Kyogoku
	0x2a40,
	"奥義", // Secret techniques
	0x23,
	0x24,
},
{
	"F_0342",
	"342 奥義５習得", // Obtained 5 secret techinques
	"京極", // Kyogoku
	0x2a80,
	"奥義", // Secret techniques
	0x23,
	0x24,
},
{
	"F_0341",
	"341 奥義４習得", // Obtained 4 secret techinques
	"京極", // Kyogoku
	0x2901,
	"奥義", // Secret techniques
	0x23,
	0x24,
},
{
	"F_0340",
	"340 奥義３習得", // Obtained 3 secret techinques
	"京極", // Kyogoku
	0x2902,
	"奥義", // Secret techniques
	0x23,
	0x24,
},
{
	"F_0339",
	"339 奥義２習得", // Obtained 2 secret techinques
	"京極（吉見使用）", // Kyogoku (used by Yoshimi)
	0x2904,
	"奥義", // Secret techniques
	0x23,
	0x24,
},
{
	"F_0338",
	"338 奥義１・盾アタック習得", // Obtained 1 secret techinques - Shield attack
	"京極（吉見使用）", // Kyogoku (used by Yoshimi)
	0x2908,
	"奥義", // Secret techniques
	0x23,
	0x24,
},
{
	"F_0337",
	"337 おばさんＡ・Ｂの話を聞いた（狼/ラルスのヒント FLOW104）", // Listened to old ladies A/B conversation (wolf / Ralis hint FLOW104)
	"京極", // Kyogoku
	0x2910,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0336",
	"336 溶岩弾を爆破した", // Blew up molten rock bomb 
	"京極（吉見使用）", // Kyogoku (used by Yoshimi)
	0x2920,
	"F_SP113:ゾーラの里", // Zora's Domain
	0x13,
	0x14,
},
{
	"F_0335",
	"335 雪山でアッシュから走り書もらった", // Obtained scribble from Ashei at mountain pass
	"京極", // Kyogoku
	0x2940,
	"F_SP114:雪山", // Snowpeak mountain
	0x14,
	0x15,
},
{
	"F_0334",
	"334 マスターソードゲット後にテルマの店でアッシュと話した", // Spoke with Ashei at Telma's shop after getting master sword
	"京極", // Kyogoku
	0x2980,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0333",
	"333 ウーリに剣のこと突っ込まれた", // Uli brings up the sword
	"京極", // Kyogoku
	0x2801,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0332",
	"332 子ども発見前にウーリと再会し、話しかけた（２回目）", // Meet again and talk with Uli after finding kids (2nd time)
	"京極", // Kyogoku
	0x2802,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0331",
	"331 子ども発見前にウーリと再会し、話しかけた（１回目）", // Meet again and talk with Uli after finding kids (1st time)
	"京極", // Kyogoku
	0x2804,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0330",
	"330 ウーリと初めて再会（最初の強制会話）", // Meet again with Uli for the first time (first forced conversation)
	"京極", // Kyogoku
	0x2808,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0329",
	"329 ジャガーに盾のことつっこまれた", // Jaggle brings up shield
	"京極", // Kyogoku
	0x2810,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0328",
	"328 子ども発見前にジャガーと再会して話した", // Talk again with Jaggle after finding kids
	"京極", // Kyogoku
	0x2820,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0327",
	"327 おばちゃんで初ワープした", // First time warped by Ooccoo Sr.
	"京極", // Kyogoku
	0x2840,
	"その他", // Misc.
	0x20,
	0x21,
},
{
	"F_0326",
	"326 LV8中ボス攻略フラグ", // LV8 mini-boss defeated flag
	"京極（梅宮使用）", // Kyogoku (used by Umemiya)
	0x2880,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0325",
	"325 フロー0023ゾーラと溶岩爆破後に会話した", // Flow 0023 Speak with Zora after blowing up magma rock
	"京極", // Kyogoku
	0x2701,
	"F_SP113:ゾーラの里", // Zora's Domain
	0x13,
	0x14,
},
{
	"F_0324",
	"324 フロー0023ゾーラと溶岩爆破前に会話した", // Flow 0023 Speak with Zora before blowing up magma rock
	"京極", // Kyogoku
	0x2702,
	"F_SP113:ゾーラの里", // Zora's Domain
	0x13,
	0x14,
},
{
	"F_0323",
	"323 フロー0020ゾーラと会話した", // Flow 0020 Spoke with Zora
	"京極", // Kyogoku
	0x2704,
	"F_SP113:ゾーラの里", // Zora's Domain
	0x13,
	0x14,
},
{
	"F_0322",
	"322 フロー0010ゾーラとゾーラ服で会話した", // Flow 0010 Spoke with Zora in Zora armor
	"京極", // Kyogoku
	0x2708,
	"F_SP113:ゾーラの里", // Zora's Domain
	0x13,
	0x14,
},
{
	"F_0321",
	"321 町医者に請求書を見せた", // Showed reciept to town doctor
	"京極", // Kyogoku
	0x2710,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0320",
	"320 LV8ダンジョン用10", // LV8 Dungeon use 10
	"京極(梅宮使用)", // Kyogoku (used by Umemiya)
	0x2720,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0319",
	"319 LV8ダンジョン用9", // LV8 Dungeon use 9
	"京極(梅宮使用)", // Kyogoku (used by Umemiya)
	0x2740,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0318",
	"318 LV8ダンジョン用8", // LV8 Dungeon use 8
	"京極(梅宮使用)", // Kyogoku (used by Umemiya)
	0x2780,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0317",
	"317 LV8ダンジョン用7", // LV8 Dungeon use 7
	"京極(梅宮使用)", // Kyogoku (used by Umemiya)
	0x2601,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0316",
	"316 LV8ダンジョン用6", // LV8 Dungeon use 6
	"京極(梅宮使用)", // Kyogoku (used by Umemiya)
	0x2602,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0315",
	"315 LV8ダンジョン用5", // LV8 Dungeon use 5
	"京極(梅宮使用)", // Kyogoku (used by Umemiya)
	0x2604,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0314",
	"314 LV8ダンジョン用4", // LV8 Dungeon use 4
	"京極(梅宮使用)", // Kyogoku (used by Umemiya)
	0x2608,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0313",
	"313 LV8ダンジョン用3", // LV8 Dungeon use 3
	"京極(梅宮使用)", // Kyogoku (used by Umemiya)
	0x2610,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0312",
	"312 LV8ダンジョン用2", // LV8 Dungeon use 2
	"京極(梅宮使用)", // Kyogoku (used by Umemiya)
	0x2620,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0311",
	"311 LV8ダンジョン用1", // LV8 Dungeon use 1
	"京極(梅宮使用)", // Kyogoku (used by Umemiya)
	0x2640,
	"D_MN08:LV8ダンジョン", // LV8 Dungeon
	0x8,
	0x9,
},
{
	"F_0310",
	"310 トビーにラフレルのメモを渡した", // Hand Auru's note to Fyer
	"京極", // Kyogoku
	0x2680,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0309",
	"309 アゲハと屋内で初会話（黄金虫捕獲を依頼された）", // First conversation with Agetha inside (gives golden bug capture quest)
	"京極", // Kyogoku
	0x2501,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0308",
	"308 雪山頂上での雪男と初対面イベント見た（人間）", // Watched first meeting event with Yeto at top of mountain (human)
	"京極", // Kyogoku
	0x2502,
	"F_SP114:雪山", // Snowpeak mountain
	0x14,
	0x15,
},
{
	"F_0307",
	"307 雪山頂上で雪男と狼で会話した", // Spoke with Yeto at top of mountain as wolf
	"京極", // Kyogoku
	0x2504,
	"F_SP114:雪山", // Snowpeak mountain
	0x14,
	0x15,
},
{
	"F_0306",
	"306 トビーの大砲で砂漠に行った", // Used Fyer's cannon to go to desert
	"京極", // Kyogoku
	0x2508,
	"砂漠", // Desert
	0x26,
	0x27,
},
{
	"F_0305",
	"305 ラフレルからトビーの話を聞いた（砂漠大砲ON）", // Heard about Fyer from Auru (desert cannon ON)
	"京極", // Kyogoku
	0x2510,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0304",
	"304 ハイリア湖でラフレルと会話した", // Spoke with Auru at Hylia Lake
	"京極", // Kyogoku
	0x2520,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0303",
	"303 シャッドの呪文２みた", // Saw Shad's spell 2
	"京極", // Kyogoku
	0x2540,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0302",
	"302 カカリコ村地下でシャッドが呪文を唱えるデモ見た", // Saw cutscene of Shad casting spells underneat Kakariko Village
	"京極", // Kyogoku
	0x2580,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0301",
	"301 LV7ダンクリア後、シャッドと会話", // Spoke with Shad after LV7 dungeon clear
	"京極", // Kyogoku
	0x2401,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0300",
	"300 テルマの店でシャッドから天空人の話聞いた", // Heard about Sky People from Shad at Telma's shop
	"京極", // Kyogoku
	0x2402,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0299",
	"299 マスターソードゲット後、シャッドとテルマの店で会話", // Spoke with Shad at Telma's shop after getting master sword
	"京極", // Kyogoku
	0x2404,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0298",
	"298 LV4D攻略後、ラフレルと会話した", // Spoke with Auru after completing LV4 dungeon
	"京極", // Kyogoku
	0x2408,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0297",
	"297 セレブ店員と初めて会話", // First spoke with Chudley store clerk
	"京極", // Kyogoku
	0x2410,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0296",
	"296 テルマの店の窓から侵入で放り出された後、ルイーズと会話した", // Spoke with Louise after kicked being kicked out of Telma's shop
	"京極", // Kyogoku
	0x2420,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0295",
	"295 テルマの店侵入（狼）時のルイーズと対面イベント見た", // Watched meeting Louise event when sneaking into Telma's shop (wolf)
	"京極", // Kyogoku
	0x2440,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0294",
	"294 祈祷師　−　祈りが天に届いた（ハート入手済）", // Shaman - Prayers reached the heavens (heart piece obtained complete)
	"京極", // Kyogoku
	0x2480,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0293",
	"293 ＷクローショットＬＶ２クリア", // Star Game 2 cleared
	"京極", // Kyogoku
	0x2301,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0292",
	"292 Ｗクローショット屋ＬＶ２初体験", // Star Game 2 first experience
	"京極", // Kyogoku
	0x2302,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"M_097",
	"291 魔法使える", // Can use magic
	"坂口", // Sakaguchi
	0x2304,
	"メインイベント", // main event
	0x22,
	0x23,
},
{
	"F_290",
	"290 ＷクローショットゲームＬＶ１クリアした", // Double clawshot game LV1 cleared
	"京極", // Kyogoku
	0x2308,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_289",
	"289 ＷクローショットゲーＬＶ１入場の会話聞いた", // Heard conversation about entering double clawshot game LV1
	"京極", // Kyogoku
	0x2310,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_288",
	"288 【デモ : 】イリアが記憶を取り戻した", // [cutscene: ] Ilia gets her memories back
	"京極", // Kyogoku
	0x2320,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"F_287",
	"287 イリアに木彫りの像を渡した", // Handed wood carving to Ilia
	"京極", // Kyogoku
	0x2340,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_286",
	"286 スモモのアトラクションクリア（ハートかけらゲット）", // Cleared Plumm's attraction (get heart piece)
	"京極", // Kyogoku
	0x2380,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_285",
	"285 スモモと狼で初会話", // First conversation with Plumm as wolf
	"京極", // Kyogoku
	0x2201,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_284",
	"284 スモモのゲームで得点記録したことある", // Already have a score recorded for Plumm's game
	"京極（一角使用）", // Kyogoku (used by Ikkaku)
	0x2202,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_283",
	"283 木彫りの像ゲットした", // Get wood carving
	"京極", // Kyogoku
	0x2204,
	"環状フィールド", // Ring field
	0x25,
	0x26,
},
{
	"F_282",
	"282 LV5ダンクリア後の山頂で雪男と初会話", // First conversation with Yeto at peak after LV5 dungeon clear
	"京極", // Kyogoku
	0x2208,
	"F_SP114:雪山", // Snowpeak mountain
	0x14,
	0x15,
},
{
	"F_0281",
	"281 マロマート城下町店オープン", // Malo Mart opens in Castle Town
	"京極", // Kyogoku
	0x2210,
	"店", // Shop
	0x2a,
	0x2b,
},
{
	"F_0280",
	"280 ポーチでイリアのにおいの回想デモを見た", // Saw cutscene about Ilia's scent from pouch
	"京極", // Kyogoku
	0x2220,
	"環状フィールド", // Ring field
	0x25,
	0x26,
},
{
	"F_0279",
	"279 木刀で子供達のにおいの回想デモを見た", // Saw cutscene about scent of kids from wooden sword
	"京極", // Kyogoku
	0x2240,
	"環状フィールド", // Ring field
	0x25,
	0x26,
},
{
	"F_0278",
	"278 インパル婆さんからペンダントもらった", // Received pendant from Impaz
	"京極", // Kyogoku
	0x2280,
	"F_SP128:隠れ里", // Hidden Village
	0x18,
	0x19,
},
{
	"F_0277",
	"277 ＴＷテルマの店の店内でテルマ＆イリアの会話を聞いた", // Hear conversation between Telma and Ilia in Telma's shop (Twilight)
	"京極", // Kyogoku
	0x2101,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0276",
	"276 ルイーズに木彫りの像が盗まれた話聞いた", // Heard conversation with Louise about stolen wood carving
	"京極", // Kyogoku
	0x2102,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0275",
	"275 シャッドの居場所の地図を見た", // Saw Shad's location on map
	"京極", // Kyogoku
	0x2104,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0274",
	"274 モイの居場所の地図を見た", // Saw Rusl's location on map
	"京極", // Kyogoku
	0x2108,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0273",
	"273 アッシュの居場所の地図を見た", // Saw Ashei's location on map
	"京極", // Kyogoku
	0x2110,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0272",
	"272 ラフレルの居場所の地図を見た", // Saw Auru's location on map
	"京極", // Kyogoku
	0x2120,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0271",
	"271 テルマとマスターソードゲット後会話の後さらに会話した", // Talked with Telma again after the other conversation after getting master sword
	"京極", // Kyogoku
	0x2140,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0270",
	"270 テルマにレナードの手紙を渡した", // Gave Renado's letter to Telma
	"京極", // Kyogoku
	0x2180,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0269",
	"269 マスターソードゲット後にテルマと初会話", // First conversation with Telma after getting master sword
	"京極", // Kyogoku
	0x2001,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0268",
	"268 LV7ダンジョンクリア", // LV7 dungeon clear
	"京極", // Kyogoku
	0x2002,
	"D_MN07:LV7ダンジョン", // LV7 dungeon
	0x7,
	0x8,
},
{
	"F_0267",
	"267 LV6ダンジョンクリア", // LV6 dungeon clear
	"京極", // Kyogoku
	0x2004,
	"D_MN06:LV6ダンジョン", // LV6 Dungeon
	0x6,
	0x7,
},
{
	"F_0266",
	"266 LV5ダンジョンクリア", // LV5 dungeon clear
	"京極", // Kyogoku
	0x2008,
	"D_MN11:LV5ダンジョン", // LV5 Dungeon
	0xa,
	0xb,
},
{
	"F_0265",
	"265 LV4ダンジョンクリア", // LV4 dungeon clear
	"京極", // Kyogoku
	0x2010,
	"D_MN10:LV4ダンジョン", // LV4 Dungeon,
	0x9,
	0xa,
},
{
	"F_0264",
	"264 マスターソードゲット", // get master sword
	"京極", // Kyogoku
	0x2020,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"F_0263",
	"263 レジスタンスのアッシュと初会話③（馬鹿にされる時）", // First conversation with Resistance Ashei (3) (made fun of)
	"京極", // Kyogoku
	0x2040,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0262",
	"262 レジスタンスのシャッドと初会話（馬鹿にされる時）", // First conversation with Resistance Shad (made fun of)
	"京極", // Kyogoku
	0x2080,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0261",
	"261 レジスタンスのラフレルと初会話（馬鹿にされる時）", // First conversation with Resistance Auru (made fun of)
	"京極", // Kyogoku
	0x1f01,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0260",
	"260 レジスタンスのモイに初めて声をかけた", // First time speaking to Resistance Rusl
	"京極", // Kyogoku
	0x1f02,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0259",
	"259 最初の強制ミドナ台詞を聞いた", // Heard first forced dialogue from Midna
	"京極", // Kyogoku
	0x1f04,
	"E3_2006用", // For E3 2006
	0xb,
	0xc,
},
{
	"F_0258",
	"258 ヘビースイッチの真上でヒントを聞いた", // Heard hint right above heavy switch
	"京極", // Kyogoku
	0x1f08,
	"E3_2006用", // For E3 2006
	0xb,
	0xc,
},
{
	"F_0257",
	"257 ボスがこけてる真っ最中のみON（普段はOFFでリアルタイム変化）", // Only ON when boss is in hollow state (normally off, changes in real time)
	"京極", // Kyogoku
	0x1f10,
	"E3_2006用", // For E3 2006
	0xb,
	0xc,
},
{
	"F_0256",
	"256 一度でもボスをダウンさせた", // Knocked down boss at leased once
	"京極（森田使用）", // Kyogoku (used by Morita)
	0x1f20,
	"E3_2006用", // For E3 2006
	0xb,
	0xc,
},
{
	"F_0255",
	"255 ボスがヘロヘロ（鎖つかむ場面）状態の時のみON（普段はOFF）", // Boss exhausted (grabbing chains) only on during state (normally off)
	"京極", // Kyogoku
	0x1f40,
	"E3_2006用", // For E3 2006
	0xb,
	0xc,
},
{
	"F_0254",
	"254 一度でもボスの弱点にヒットさせた", // Hit boss's weak spot at least once
	"京極（森田使用）", // Kyogoku (used by Morita)
	0x1f80,
	"E3_2006用", // For E3 2006
	0xb,
	0xc,
},
{
	"F_0253",
	"253 一度でもマグネリフトに張り付いた", // Stuck to magnet lift at least once
	"京極（梅宮使用）", // Kyogoku (used by Umemiya)
	0x1e01,
	"E3_2006用", // For E3 2006
	0xb,
	0xc,
},
{
	"F_0252",
	"252 子供行方不明中にセーラに話しかけた（店処理に入った）", // Spoke to Sera while kids are missing (dealing with shop)
	"京極", // Kyogoku
	0x1e02,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0251",
	"251 子供発見前にセーラと再会（強制会話）", // Speak again with Sera before finding kids (forced conversation)
	"京極", // Kyogoku
	0x1e04,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0250",
	"250 【デモ : 21】ゼルダ再会・ミドナ復活（ガノンウォール発生）", // [cutscene: 21] reunion with Zelda / Midna revived (Ganon wall appears)
	"京極", // Kyogoku
	0x1e08,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"F_0249",
	"249 ラッカゲーム代金払って出ようとした（初回のみ）", // Try to leave after paying for Flight by Fowl (first time only)
	"京極", // Kyogoku
	0x1e10,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0248",
	"248 森の神殿クリア後、キコルと会話した", // Speak with Coro after clearing Forest Temple
	"京極", // Kyogoku
	0x1e20,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0247",
	"247 マロマート資金援助後、マロと初会話（買い物終了時）", // First conversation with Malo (shopping complete) after helping Malo Mart fundraiser
	"京極", // Kyogoku
	0x1e40,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0246",
	"246 マロマート募金（＆温泉水運び）開始", // Malo Mart fundraiser (and carying spring water) start
	"京極", // Kyogoku
	0x1e80,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"MAP_VISIBLE",
	"245 エリアマップの表示・非表示", // Area map show/hide
	"坂口", // Sakaguchi
	0x1d01,
	"２Ｄマップ", // 2D Map
	0x1e,
	0x1f,
},
{
	"F_0244",
	"244 コリンが汗を拭かれている時にタロと会話した", // Speak to Talo while COlin is wiping sweat
	"京極", // Kyogoku
	0x1d02,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0243",
	"243 コリンの汗を拭くルダと会話した", // Speak with Luda wiping Colin's sweat
	"京極", // Kyogoku
	0x1d04,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0242",
	"242 火魔人戦直後、放心状態の族長ゴロンと会話した", // Spoke with the dazed chief goron after Fyrus battle
	"京極", // Kyogoku
	0x1d08,
	"D_MN04:LV2ダンジョン", // LV2 Dungeon
	0x4,
	0x5,
},
{
	"F_0241",
	"241 ボム屋開店後、バーンズと初会話", // First conversation with Barnes after bomb shop open
	"京極", // Kyogoku
	0x1d10,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0240",
	"240 爆弾制作中のバーンズと話した", // Speak with Barnes while heas making bombs
	"京極", // Kyogoku
	0x1d20,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"T_0239",
	"239 トビーと会話した（闇カーゴ開始）", // Spoke with Fyer (start dark carge)
	"京極", // Kyogoku
	0x1d40,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0238",
	"238 パペットを全滅させた（聖なる森前のメスザルイベント）", // Destroyed all puppets (monkey girl event before sacred grove)
	"京極（森田使用）", // Kyogoku (used by Morita)
	0x1d80,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0237",
	"237 マロの店に入った（マロと喋った）", // Entered Malo Mart (chatted with Malo)
	"京極", // Kyogoku
	0x1c01,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0236",
	"236 カカリコ村前の橋ワープ先間違えてミドナに怒られた", // Make Midna angry after doing wrong destination for Kakariko bridge warp
	"京極", // Kyogoku
	0x1c02,
	"その他", // Misc.
	0x20,
	0x21,
},
{
	"F_0235",
	"235 巨人ゲ−ムクリア", // Giant game clear
	"住吉", // Sumiyoshi
	0x1c04,
	"F_SP117:聖なる森", // Sacred Grove
	0x17,
	0x18,
},
{
	"F_234",
	"234 トリルに襲われた", // Attacked by Trill
	"京極", // Kyogoku
	0x1c08,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0233",
	"233 ボウとの練習試合に勝利（ブーツ入手前）", // Win practice battle with Bo (before getting boots)
	"京極", // Kyogoku
	0x1c10,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0232",
	"232 ボウからアイアンブーツを譲り受けた", // get iron boots from Bo
	"京極", // Kyogoku
	0x1c20,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0231",
	"231 ボウと初めて相撲とった", // Did first wrestle match with Bo
	"京極", // Kyogoku
	0x1c40,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0230",
	"230 トワイライト/ゴロンBのぼやきを聞いた", // Twilight - listened to goron B's complaints
	"京極", // Kyogoku
	0x1c80,
	"F_SP110:デスマウンテン", // Death Mountain
	0x11,
	0x12,
},
{
	"F_0229",
	"229 カンテラ拾わずに（猿返却後）迷い霧の森を出ようとした", // Try to leave the mist woods area without lantern (after returning monkey)
	"京極", // Kyogoku
	0x1b01,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0228",
	"228 トワイライト登山道入り口ゴロンのぼやきを聞いた", // Listened to goron's complaint at the entrance to twilight mountain path
	"京極", // Kyogoku
	0x1b02,
	"F_SP110:デスマウンテン", // Death Mountain
	0x11,
	0x12,
},
{
	"F_0227",
	"227 カンテラとられたまま迷い霧の森を出ようとした", // Try to leave mist woods after lantern taken
	"京極", // Kyogoku
	0x1b04,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0226",
	"226 猿にとられたカンテラを再取得", // Get lantern back from monkey
	"京極/森田さん使用", // Kyoguku/Used by Mr. Morita
	0x1b08,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0225",
	"225 カンテラ誘導猿が２度と出てこない", // Lanter guide monkey doesn't come out a second time
	"京極/森田さん使用", // Kyoguku/Used by Mr. Morita
	0x1b10,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0224",
	"224 カンテラ誘導ザルデモ用フラグ", // Flag for lantern guide monkey cutscene
	"京極/森田さん使用", // Kyoguku/Used by Mr. Morita
	0x1b20,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0223",
	"223 闇蟲倒す前のキコルの台詞聞いた", // Listened to Coro's dialogue before defeating shadow bugs
	"京極", // Kyogoku
	0x1b40,
	"R_SP108:フィローネの森キコリ屋内", // Farron Woods inside woodcutter's shop
	0x1a,
	0x1b,
},
{
	"F_0222",
	"222 キコル点火イベント終了", // Finished Coro ignite event
	"京極", // Kyogoku
	0x1b80,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0221",
	"221 精霊から光の器もらった", // Received vessel of light from spirit
	"京極", // Kyogoku
	0x1a01,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0220",
	"220 初・城の地下にいるＴＷハイラル兵どちらかの話を聞いた", // First time - Talked to one of the Hyrule soldiers underneath castle in Twilight
	"京極", // Kyogoku
	0x1a02,
	"R_SP107:ハイラル城内部", // Inside Hyrule Castle
	0x19,
	0x1a,
},
{
	"F_0219",
	"219 アゲハ「持ってるクセに」聞いた", // Heard Agetha say "but you have some"
	"京極", // Kyogoku
	0x1a04,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0218",
	"218 キコルから油入りビンを購入した", // Bought jar of oil from Coro
	"京極", // Kyogoku
	0x1a08,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0217",
	"217 TW晴らし直後のキコルと再会後　初会話", // First conversation after speaking with Coro again after clearing up twilight
	"京極", // Kyogoku
	0x1a10,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0216",
	"216 夜のトアル村コッコＢ（白）と会話", // Spoke with Ordon village cucco B (white)
	"京極", // Kyogoku
	0x1a20,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0215",
	"215 屋根の上のネコと会話した", // Spoke with cat on roof
	"京極", // Kyogoku
	0x1a40,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0214",
	"214 初めてのミドナＺ常駐ヒントを聞いた", //  First heard Midna's hint about Z
	"京極", // Kyogoku
	0x1a80,
	"R_SP107:ハイラル城内部", // Inside Hyrule Castle
	0x19,
	0x1a,
},
{
	"F_0213",
	"213 カカリコ入り口NS戦後、精霊に呼ばれた", // Called by spirit after NS fight at Kakariko entrance
	"京極", // Kyogoku
	0x1901,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0212",
	"212 トアルの泉ゲート前のコリンと会話", // Conversation wtih Colin in front of Ordon springs gate
	"京極", // Kyogoku
	0x1902,
	"F_SP104:トアル森", // Ordon Woods
	0xe,
	0xf,
},
{
	"F_0211",
	"211 ボウ＆ジャガーの盗み聞き成功", // Successfully eavesdrop on Bo and Jaggle
	"住吉", // Sumiyoshi
	0x1904,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0210",
	"210 F0004:コリン馬止め中に馬に乗ろうとした", // F0004: Try to get on horse when Colin is stopping horse
	"京極", // Kyogoku
	0x1908,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0209",
	"209 ボウ＆ジャガー盗み聞き失敗で逃亡", // Escape after failing to eavesdrop to Bo and Jaggle
	"京極", // Kyogoku
	0x1910,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0208",
	"208 ハンジョ−、狼に驚き飛び込んだ", // Hanch leapt after being startled by wolf
	"住吉", // Sumiyoshi
	0x1920,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0207",
	"207 ハンジョ−、鷹匠デモ見た", // Viewed Hanch, the Hawker cutscene
	"住吉", // Sumiyoshi
	0x1940,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0206",
	"206 闇の結界タグ：剣と盾そろえずに入ろうとした", // Barrier of darkness tag: tried to enter without getting sword and shield
	"京極", // Kyogoku
	0x1980,
	"F_SP104:トアル森", // Ordon Woods
	0xe,
	0xf,
},
{
	"F_0205",
	"205 夜のトアル村でモイ＆ウーリの会話を聞いた", // Heard Rusl and Uli talking in Ordon village at night
	"京極", // Kyogoku
	0x1801,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0204",
	"204 下水道で格子ごしにミドナと会話した", // Talked to Midna from across the bars in the sewer
	"京極", // Kyogoku
	0x1802,
	"R_SP107:ハイラル城内部", // Inside Hyrule Castle
	0x19,
	0x1a,
},
{
	"F_0203",
	"203 無人販売で初めて盗もうとした（賽銭箱チェックしてない）", // First tried to steal from unnmaned shop (Havent checked donation box)
	"京極", // Kyogoku
	0x1804,
	"店", // Shop
	0x2a,
	0x2b,
},
{
	"F_0202",
	"202 モイ/狼剣パクり失敗した", // Rusl / Wolf fails to get sword
	"京極", // Kyogoku
	0x1808,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0097",
	"197 盗み聞きヒント犬と初会話した", // First conversation with dog eavesdrop hint
	"京極", // Kyogoku
	0x1810,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0096",
	"196 体力1の時にボウと会話したことがある", // Have spoken to Bo with 1 health
	"京極", // Kyogoku
	0x1820,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0095",
	"195 山羊暴走前にファドと話した", // Spoke to Fado before mountain goat rampage
	"京極", // Kyogoku
	0x1840,
	"F_SP00:牧場", // Ranch
	0xc,
	0xd,
},
{
	"F_0094",
	"194 タロがサルを追いかけていった", // Talo went after the monkey
	"京極", // Kyogoku
	0x1880,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0093",
	"193 F:1128 - 南 - 八百屋の女店主と話した", // F:1128 - South - Spoke with female clerk at vegetable stand
	"京極", // Kyogoku
	0x1701,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0092",
	"192 F:1127 - 南 - 道案内ハイラル兵と話した", // F:1127 - South - Spoke with the Hyrule soldier guide
	"京極", // Kyogoku
	0x1702,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0091",
	"191 F:1126 - 南 - アゲハのストーカーと話した（屋内でアゲハと会話後）", // F:1126 - South - Spoke with Agetha's stalker (after talking with Agetha inside)
	"京極", // Kyogoku
	0x1704,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0090",
	"190 F:1126 - 南 - アゲハのストーカーと話した（屋内でアゲハと会話前）", // F:1126 - South - Spoke with Agetha's stalker (before talking with Agetha inside)
	"京極", // Kyogoku
	0x1708,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0089",
	"189 村長と初めて話した", // Talked to village chief for first time
	"京極", // Kyogoku
	0x1710,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0088",
	"188 剣チュー中断後にベスと会話した", // Spoke to Beth after quitting sword tutorial
	"京極", // Kyogoku
	0x1720,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0087",
	"187 キュリーと初会話後、サーチ範囲を出た", // Left search area after first conversation with Pergie
	"京極", // Kyogoku
	0x1740,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0086",
	"186 鷹でハチの巣を落とした後ハンジョーと会話した", // Spoke with Hanch after knocking down beehive with hawk
	"京極", // Kyogoku
	0x1780,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0085",
	"184 森の入り口でモイ登場", // Rusl appears at woods entrance
	"住吉", // Sumiyoshi
	0x1601,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0084",
	"183 序盤２＆３日目：パチンコで蜂の巣を落とした", // Opening days 2&3: knocked down a beehive with slingshot
	"京極（森田使用）", // Kyogoku (used by Morita)
	0x1602,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0083",
	"182 アゲハからの手紙が届く", // Deliver letter from Agetha
	"京極", // Kyogoku
	0x1604,
	"手紙", // Letter
	0x27,
	0x28,
},
{
	"F_0082",
	"181 山羊20匹目暴走後にボウと会話済？", // Completed coversation with Bo after 20th mountain goat's rampage
	"京極", // Kyogoku
	0x1608,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0081",
	"180 山羊20匹暴走した", // 20 mountain goats rampaged
	"京極", // Kyogoku
	0x1610,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0080",
	"179 山羊暴走イベント全終了", // Completed all of mountain goat rampage event
	"京極", // Kyogoku
	0x1620,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0079",
	"178 ２日目−暴走山羊倒し成功", // 2nd Day - successful knocked down rampaging mountain goat
	"京極", // Kyogoku
	0x1640,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0078",
	"177 池に飛び込んでたハンジョーが陸に戻った", // Hanch returned to land after jumping into lake
	"京極", // Kyogoku
	0x1680,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0077",
	"176 アゲハと屋内で初会話", // First converstaion with Agetha inside
	"京極", // Kyogoku
	0x1501,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0076",
	"175 池の中にいるハンジョーと喋った", // Spoke to Hanch in lake
	"京極", // Kyogoku
	0x1502,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0075",
	"174 カボチャを割ってジャガーに怒られた", // Angered Jaggle by destroying pumpkin
	"京極", // Kyogoku
	0x1504,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0074",
	"173 ハンジョー、蜂に襲われた", // Hanch attacked by bees
	"京極", // Kyogoku
	0x1508,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0073",
	"172 デカい蜂の巣に突撃して襲われた", // Attacked after charging at large beehive
	"京極", // Kyogoku
	0x1510,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0072",
	"171 鷹でデカい蜂の巣を落とした", // Knocked down large beehive with hawk
	"京極", // Kyogoku
	0x1520,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0071",
	"170 ラネール地方ワープ不可", // Cannot warp to Lanayru
	"京極", // Kyogoku
	0x1540,
	"TW環状フィールド", // Twilight Ring field
	0x1d,
	0x1e,
},
{
	"M_002",
	"169 【デモ : 2】イリアとの出会い（馬を泉につれていく）", // [cutscene: 2] Met with Ilia (brings horse to spring)
	"京極", // Kyogoku
	0x1580,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"F_0070",
	"168 コリン、ハイハイで森の奥へ行った", // Colin went deep into the woods
	"京極", // Kyogoku
	0x1401,
	"F_SP104:トアル森", // Ordon Woods
	0xe,
	0xf,
},
{
	"F_0069",
	"167 F0048:コリンに通せんぼを助けたお礼を言われた", // F0048: Thanked by Colen for clearing path
	"京極", // Kyogoku
	0x1402,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0068",
	"166 @",
	"京極", // Kyogoku
	0x1404,
	"***",
	0x0,
	0x1,
},
{
	"F_0067",
	"165 セーラに牛乳ビン（1/2）もらった", // Recieved milk jar (1/2) from Sera
	"京極", // Kyogoku
	0x1408,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0066",
	"164 登山道(R00) ゴロンデモ を初めて見た", // First saw Goron cutscene on mountain path
	"京極", // Kyogoku
	0x1410,
	"F_SP110:デスマウンテン", // Death Mountain
	0x11,
	0x12,
},
{
	"F_0065",
	"163 雪女に最後の地図印つけてもらった", // Yeta adds last symbol onto map
	"京極", // Kyogoku
	0x1420,
	"D_MN11:LV5ダンジョン", // LV5 Dungeon
	0xa,
	0xb,
},
{
	"F_0064",
	"162 トマトピューレ入手後に雪女と初会話", // first convo with yeta after obtaining tomato puree
	"京極", // Kyogoku
	0x1440,
	"D_MN11:LV5ダンジョン", // LV5 Dungeon
	0xa,
	0xb,
},
{
	"F_0063",
	"161 初めてトビー大砲を使った", // Used Fyer's cannon for first time
	"京極", // Kyogoku
	0x1480,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0062",
	"160 初めてトビー大砲ブッチした", // Abandoned taking Fyer's cannon after paying
	"京極", // Kyogoku
	0x1301,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"F_0061",
	"159 長老ゴロンとの相撲勝利後に温泉ゴロン＆店主の噂話聞いた", // Heard spring goron and shopkeeper rumers after winning wrestling match against elder goron
	"京極", // Kyogoku
	0x1302,
	"F_SP110:デスマウンテン", // Death Mountain
	0x11,
	0x12,
},
{
	"F_0060",
	"158 光の世界でホズと初会話", // First conversation with Hozu in the World of Light
	"京極", // Kyogoku
	0x1304,
	"F_SP112:ゾーラ川", // Zora's River
	0x12,
	0x13,
},
{
	"F_0059",
	"157 精霊と光の雫GET後会話（闇が晴れた）←多分未使用。。。", // Conversation after getting spirit and tears of light (darkness cleared) <- probably unused ...
	"京極", // Kyogoku
	0x1308,
	"+怖いフラグ", // + Scary flag
	0x2,
	0x3,
},
{
	"F_0058",
	"156 テルマの店の扉ごしの声を聞いた", // Listened to voices on other side of door in Telma's shop
	"京極", // Kyogoku
	0x1310,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"F_0057",
	"155 【デモ : 17】子供たちとの別れ", // [cutscene: 17] Part with the children
	"京極", // Kyogoku
	0x1320,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"F_0056",
	"154 長老ゴロンに２回以上負けた", // Lost to elder goron 2+ times
	"京極", // Kyogoku
	0x1340,
	"F_SP110:デスマウンテン", // Death Mountain
	0x11,
	0x12,
},
{
	"F_0055",
	"153 精霊フィローネから光の器もらった", // Received Vessel of Light from Faron spirit
	"京極", // Kyogoku
	0x1380,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0054",
	"152 アイアンブーツを履いて長老ゴロンと相撲して負けた", // Lost wrestling match with elder goron while wearing iron boots
	"京極", // Kyogoku
	0x1201,
	"F_SP110:デスマウンテン", // Death Mountain
	0x11,
	0x12,
},
{
	"F_0053",
	"151 ナイトストーカー出現デモ見た", // Saw night stalker appearance cutscene
	"京極", // Kyogoku
	0x1202,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"F_0052",
	"150 ネコ救出前のセーラと２回目の会話をした", // Had 2nd conversaton with Sera before saving cat
	"京極", // Kyogoku
	0x1204,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0051",
	"149 ネコ救出後、店内でセーラと話した", // Spoke to Sera in the shop after saving cat
	"京極", // Kyogoku
	0x1208,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0050",
	"148 アイアンブーツゲットデモみた", // Saw cutscene for getting iron boots
	"京極", // Kyogoku
	0x1210,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0049",
	"147 ウーリの持ち上げチュートリアル ＜投げて失敗＞", // Uli's pick up tutorial <fail to throw>
	"京極", // Kyogoku
	0x1220,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0048",
	"146 ウーリの持ち上げチュートリアル ＜失敗＞", // Uli's pick-up tutorial <fail>
	"京極", // Kyogoku
	0x1240,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0047",
	"145 トアル村ショップ開店後、初来訪", // First visit after Ordon Village shop opens
	"京極", // Kyogoku
	0x1280,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0046",
	"144 ネコ救出&lt;失敗&gt;後、セーラと話した", // Spoke with Sera after saving(lt;) failing(gt;) cat
	"京極", // Kyogoku
	0x1101,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0045",
	"143 F0080:序盤３日目−ウーリと話した", // Opening 3rd day - spoke with Uli
	"京極", // Kyogoku
	0x1102,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0044",
	"142 剣チュートリアル初めて引き受けた", // Accepted sword tutorial first time
	"京極", // Kyogoku
	0x1104,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0043",
	"141 募金額が２００に減ってから初めて訪れた", // First visit after fundrasing funds drop to 200
	"京極", // Kyogoku
	0x1108,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"F_0042",
	"140 寝室前到着直後に雪女と会話した", // Spoke with Yeta right after arriving at bedroom
	"京極", // Kyogoku
	0x1110,
	"D_MN11:LV5ダンジョン", // LV5 Dungeon
	0xa,
	0xb,
},
{
	"F_0041",
	"139 序盤２日目−これがONになった後でハンジョーが蜂に襲われる", // Opening 2nd day - After this is turned ON Hanch is attacked by bees
	"京極", // Kyogoku
	0x1120,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0040",
	"138 ２日目：草笛吹いた後にジャガーと話した", // 2nd day: Spoke to Jaggle after blowing on whistle
	"京極", // Kyogoku
	0x1140,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0039",
	"137 ２日目にツタに登ったことでハンジョーに注意された", // Warned by Hanch after climbing vines on 2nd day
	"京極", // Kyogoku
	0x1180,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0038",
	"136 序盤（２日目）ネコが家に帰った", // Opening (2nd day) cat returns home
	"京極", // Kyogoku
	0x1001,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0037",
	"135 ジャガー/高台の上で会話したか？", // Jaggle - Spoke on the hill?
	"京極", // Kyogoku
	0x1002,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0036",
	"134 ジャガーにツタに登る前にL注目で話しかけたか？", // Spoke to Jaggle using L-focus before climbing vines?
	"京極", // Kyogoku
	0x1004,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"M_003",
	"133 F0003:馬止め中のコリンと会話（釣竿アリ）", // F0003: Spoke to Colin while he is stopping hors (has fishing rod)
	"京極", // Kyogoku
	0x1008,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"M_001",
	"132 オープニングデモ", // Opening cutscene
	"京極", // Kyogoku
	0x1010,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"F_0035",
	"131 F0003:馬止め中のコリンと会話（釣竿ナシ）", // F0003: Spoke to Colin while he is stopping hors (doesn't have fishing rod)
	"京極", // Kyogoku
	0x1020,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0034",
	"130 モイと初会話", // first conversation wtih Rusl
	"京極", // Kyogoku
	0x1040,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"M_096",
	"129 ３日目：キュリーと話した", // 3rd day: spoke with Pergie
	"京極", // Kyogoku
	0x1080,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"M_095",
	"128 キコルと初対面（カンテラ入手）", // First time meeting Coro (obtain lantern)
	"京極", // Kyogoku
	0xf01,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"M_094",
	"127 バイト完了後、初めてホヅ小屋を訪ねた（強制会話）", // First time visiting Rizu's hut after completing river job (forced conversation)
	"京極", // Kyogoku
	0xf02,
	"F_SP112:ゾーラ川", // Zora's River
	0x12,
	0x13,
},
{
	"M_093",
	"126 砂漠デビュー後に初めてトビーと会話した", // First conversation with Fyer after desert's debut
	"京極", // Kyogoku
	0xf04,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"M_092",
	"125 オルディンの橋をワープで運んだ", // Warped Eldin Bridge
	"京極", // Kyogoku
	0xf08,
	"環状フィールド", // Ring field
	0x25,
	0x26,
},
{
	"M_091",
	"124 買収の募金達成（雑貨屋マロが優しくなる）", // Buy out fundraiser amount (Malo becomes nice)
	"京極", // Kyogoku
	0xf10,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"M_090",
	"123 請求書見せる前に町医者と会話した", // Spoke to town doctor before showing receipt
	"京極", // Kyogoku
	0xf20,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"M_089",
	"122 町医者診療所に初めて入った（強制会話）", // First time entering doctor's office (forced conversation)
	"京極", // Kyogoku
	0xf40,
	"F_SP116:城下町", // Castle Town
	0x16,
	0x17,
},
{
	"M_088",
	"121 牧師から「レナードからの手紙」ゲット", // Get Renado's Letter
	"京極", // Kyogoku
	0xf80,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"M_087",
	"120 イリアの記憶イベントスタート", // Ilia memory event start
	"京極", // Kyogoku
	0xe01,
	"環状フィールド", // Ring field
	0x25,
	0x26,
},
{
	"M_086",
	"119 闇蟲ボスの光の雫をマップに表示", // Show Boss Bug's Tear of Light on the map
	"京極", // Kyogoku
	0xe02,
	"TW環状フィールド", // Twilight Ring field
	0x1d,
	0x1e,
},
{
	"M_085",
	"118 闇蟲ボスの光の雫登場直前のミドナ台詞", // Midna dialogue right before Boss Bug's Tear of Light appears
	"京極", // Kyogoku
	0xe04,
	"TW環状フィールド", // Twilight Ring field
	0x1d,
	0x1e,
},
{
	"M_084",
	"117 雑貨屋マロ初めて買い物シーケンス終了", // Complete sequence of shopping at Malo Mart first time
	"京極", // Kyogoku
	0xe08,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"M_083",
	"116 水復活後にトビーの話を聞いた", // Heard Fyer's talk after water restored
	"京極", // Kyogoku
	0xe10,
	"F_SP115:ハイリア湖", // Lake Hylia
	0x15,
	0x16,
},
{
	"M_082",
	"115 温泉ゴロンAと会話した", // Spoke with spring Goron A
	"京極", // Kyogoku
	0xe20,
	"F_SP110:デスマウンテン", // Death Mountain
	0x11,
	0x12,
},
{
	"M_081",
	"114 上に飛ばしてくれるゴロンと初会話（全員共通）", // First conversation with Goron that shoots you up (shared with everyone)
	"京極", // Kyogoku
	0xe40,
	"F_SP110:デスマウンテン", // Death Mountain
	0x11,
	0x12,
},
{
	"M_080",
	"113 茶色のコッコと会話した", // Spoke with brown cucco
	"京極", // Kyogoku
	0xe80,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"M_079",
	"112 夜のトアル村：キュリー家の中のＺジャンプ台詞聞いた", // Ordon village night: Heard Z Jump dialogie in Pergie's house
	"京極", // Kyogoku
	0xd01,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"M_078",
	"111 カエルＡと会話した", // Spoke with frog A
	"京極", // Kyogoku
	0xd02,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"M_077",
	"110 ★陰呪の結晶ゲット（変身可能になる）", // Get shadow crystal (can now transform)
	"京極", // Kyogoku
	0xd04,
	"メインイベント", // main event
	0x22,
	0x23,
},
{
	"M_076",
	"109 マロマート城下町店で店員と初会話", // First conversation with Castle Town Malo Mart shop clerk
	"京極", // Kyogoku
	0xd08,
	"その他", // Misc.
	0x20,
	0x21,
},
{
	"M_075",
	"108 寝室のカギGET直後に雪女と強制会話した", // Forced conversation with Yeta after getting bedroom key
	"京極", // Kyogoku
	0xd10,
	"D_MN11:LV5ダンジョン", // LV5 Dungeon
	0xa,
	0xb,
},
{
	"M_074",
	"107 馬車護衛後のレナードと話した[0031]", // Spoke with Renado after guarding carriage [0031]
	"京極", // Kyogoku
	0xd20,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"M_073",
	"106 馬車護衛後のレナードと話した[0030]", // Spoke with Renado after guarding carriage [0030]
	"京極", // Kyogoku
	0xd40,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"M_072",
	"105 木彫りの盾ゲット", // Get wooden shield
	"京極", // Kyogoku
	0xd80,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"M_071",
	"104 【デモ : 20】ザント登場（ミドナ瀕死に）", // [cutscene: 20] Zant appears (during Midna's desperate hour)
	"京極", // Kyogoku
	0xc01,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"M_070",
	"103 【デモ : 18】ラネールの精霊復活", // [cutscene: 18] Lanayru spirit restored
	"京極", // Kyogoku
	0xc02,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"M_069",
	"102 子どもゴロン店主と初会話", // First conversation with child goron shop clerk
	"京極", // Kyogoku
	0xc04,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"M_068",
	"101 ★★★OFFの時は狼の背中に剣盾を背負ってる★★★", // when OFF, wolf carries sword and shield on back
	"京極", // Kyogoku
	0xc08,
	"メインイベント", // main event
	0x22,
	0x23,
},
{
	"M_067",
	"100 ★★★　ミドナ乗降(ON == 乗)　★★★", // Midna riding / not riding (ON == riding)
	"京極", // Kyogoku
	0xc10,
	"メインイベント", // main event
	0x22,
	0x23,
},
{
	"M_066",
	"99 @",
	"京極", // Kyogoku
	0xc20,
	"***",
	0x0,
	0x1,
},
{
	"M_065",
	"98 LV1ダンジョンクリア後のフィローネ精霊の話を聞いた", // Spoke with Faron spirit after clearing LV1 dungeon
	"京極", // Kyogoku
	0xc40,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"M_064",
	"97 ハイリア湖の水が戻った（女王ルテラと会話した）", // Water returns to Hylia Lake (spoke with Queen Rutela)
	"京極", // Kyogoku
	0xc80,
	"F_SP113:ゾーラの里", // Zora's Domain
	0x13,
	0x14,
},
{
	"M_063",
	"96 【ホヅ川下り】バイト終了（川下り１回目）", // [Iza river descent] Finish job (First time descending river)
	"京極", // Kyogoku
	0xb01,
	"F_SP112:ゾーラ川", // Zora's River
	0x12,
	0x13,
},
{
	"M_062",
	"95 【ホヅ】ナイトストーカー戦後、礼を言われた", // [Iza] Says thanks after night stalker battle
	"京極", // Kyogoku
	0xb02,
	"F_SP112:ゾーラ川", // Zora's River
	0x12,
	0x13,
},
{
	"M_061",
	"94 【ホヅ川下り】ガレキ撤去の説明を１回受けている", // [Iza river descent] Got explanation for clearing rubble 1 time
	"京極", // Kyogoku
	0xb04,
	"F_SP112:ゾーラ川", // Zora's River
	0x12,
	0x13,
},
{
	"M_060",
	"93 【ホヅ川下り】小屋内のガレキ撤去中に逃亡２回目", // [Iza river descent] // 2nd time running away while clearing rubble in hut
	"京極", // Kyogoku
	0xb08,
	"F_SP112:ゾーラ川", // Zora's River
	0x12,
	0x13,
},
{
	"M_059",
	"92 雪女から地図をもらった", // received map from Yeta
	"京極", // Kyogoku
	0xb10,
	"D_MN11:LV5ダンジョン", // LV5 Dungeon
	0xa,
	0xb,
},
{
	"M_058",
	"91 雪女と初対面（強制会話）", // First time meeting Yeta (forced converation)
	"京極", // Kyogoku
	0xb20,
	"D_MN11:LV5ダンジョン", // LV5 Dungeon
	0xa,
	0xb,
},
{
	"M_057",
	"90 ライダーボスを倒して、猪デモを見た", // View boar cutscene after defeating King Bulblin
	"京極", // Kyogoku
	0xb40,
	"砂漠", // Desert
	0x26,
	0x27,
},
{
	"M_056",
	"89 ホヅの悩みを無視した", // Ignored Iza's concerns
	"京極", // Kyogoku
	0xb80,
	"環状フィールド", // Ring field
	0x25,
	0x26,
},
{
	"M_055",
	"88 一騎討ちで１回でもダメージ与えた", // Did damage at least once during joust/one-on-one battle
	"京極", // Kyogoku
	0xa01,
	"メインイベント", // main event
	0x22,
	0x23,
},
{
	"M_054",
	"87 ★デモ★一騎討ちデモ", // Joust / one-on-one battle cutscene
	"京極", // Kyogoku
	0xa02,
	"メインイベント", // main event
	0x22,
	0x23,
},
{
	"M_053",
	"86 ★デモ★馬上戦デモ", // Horseback battle cutscene
	"京極", // Kyogoku
	0xa04,
	"メインイベント", // main event
	0x22,
	0x23,
},
{
	"M_052",
	"85 ★馬上戦クリア", // Horseback battle clear
	"京極", // Kyogoku
	0xa08,
	"メインイベント", // main event
	0x22,
	0x23,
},
{
	"M_051",
	"84 ★闇カーゴ（大）イベント終了（トビ草が各地に登場）", // Shadow Kargorok (?) (Large) event complete (Horse grass appears in various places)
	"京極", // Kyogoku
	0xa10,
	"メインイベント", // main event
	0x22,
	0x23,
},
{
	"M_050",
	"83 ★一騎うちの橋が消される", // Joust bridge disappears
	"京極", // Kyogoku
	0xa20,
	"メインイベント", // main event
	0x22,
	0x23,
},
{
	"M_049",
	"82 デスマウンテン１匹目の転がりゴロンを投げた", // Threw first rolling goron at death mountain
	"京極（吉見使用）", // Kyogoku (used by Yoshimi)
	0xa40,
	"F_SP110:デスマウンテン", // Death Mountain
	0x11,
	0x12,
},
{
	"M_048",
	"81 小屋内でガレキ撤去作業中に逃亡した", // Ran away while clearing rubble at hut
	"京極", // Kyogoku
	0xa80,
	"F_SP112:ゾーラ川", // Zora's River
	0x12,
	0x13,
},
{
	"M_047",
	"80 ホヅTW - 闇蟲倒した後に話を聞いた", // Iza Twilight - Talked after defeating shadow bugs
	"京極", // Kyogoku
	0x901,
	"F_SP112:ゾーラ川", // Zora's River
	0x12,
	0x13,
},
{
	"M_046",
	"79 【ホヅ川下り】川を塞ぐ岩の相談を受けた", // [Iza river descent] Get advice about boulder blocking river
	"京極", // Kyogoku
	0x902,
	"F_SP112:ゾーラ川", // Zora's River
	0x12,
	0x13,
},
{
	"M_045",
	"78 LV3ダンジョンクリア", // LV3 Dungeon clear
	"京極", // Kyogoku
	0x904,
	"D_MN01:LV3ダンジョン", // LV3 Dungeon
	0x3,
	0x4,
},
{
	"M_044",
	"77 【バーンズ・ボム屋】プレミアムパック購入した", // [Barnes Bomb Shop] Bought premium pack
	"京極", // Kyogoku
	0x908,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"M_043",
	"76 【弓矢ゲ−ム】ホークアイを使って攻略（再挑戦アリ）", // [Bow and Arrow game] Complete using Hawkeye
	"京極", // Kyogoku
	0x910,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"M_042",
	"75 【弓矢ゲ−ム】クリア済み", // [Bow and Arrow game] clear
	"住吉", // Sumiyoshi
	0x920,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"M_041",
	"74 【弓矢ゲ−ム】初体験した", // [Bow and Arrow game] First attempt
	"住吉", // Sumiyoshi
	0x940,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"M_040",
	"73 【弓矢ゲーム】攻略後にタロと話した", // [bow and arrow game] Spoke to Talo after completing
	"京極", // Kyogoku
	0x980,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"M_039",
	"72 【弓矢ゲーム】タロと初会話", // [Bow and arrow game] First time talking to Talo
	"京極", // Kyogoku
	0x801,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"M_038",
	"71 【弓矢ゲーム】ホークアイのヒント聞いた", // [bow and arrow game] listen to hawkeye hint
	"京極", // Kyogoku
	0x802,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"M_037",
	"70 女王ゾーラからゾーラの服をもらった", // Got Zora armor from Zora queen
	"京極", // Kyogoku
	0x804,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"M_036",
	"69 ★馬車護衛再開（一騎打ちリベンジ後）", // Begin carriage guarding (after joust revenge)
	"京極", // Kyogoku
	0x808,
	"メインイベント", // main event
	0x22,
	0x23,
},
{
	"M_035",
	"68 【デモ : 35】馬車護衛イベント後", // [cutscene: 35] after carriage guarding event
	"京極", // Kyogoku
	0x810,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"M_034",
	"67 【デモ : 19】イリアとの再会LV3", // [cutscene: 19] Reunion with Ilia LV3
	"京極", // Kyogoku
	0x820,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"M_033",
	"66 ★馬車護衛ゲーム開始（F:0022）", // Start carriage guarding game
	"京極", // Kyogoku
	0x840,
	"メインイベント", // main event
	0x22,
	0x23,
},
{
	"M_032",
	"65 溶岩でゾーラ川の氷が溶けた", // Melted Zora river ice with magma rock
	"京極", // Kyogoku
	0x880,
	"メインイベント", // main event
	0x22,
	0x23,
},
{
	"M_031",
	"64 LV2ダンジョンクリア", // LV2 dungeon clear
	"京極", // Kyogoku
	0x701,
	"D_MN04:LV2ダンジョン", // LV2 Dungeon
	0x4,
	0x5,
},
{
	"M_030",
	"63 ドン・コローネと初会話", // First conversation with Gor Coron
	"京極", // Kyogoku
	0x702,
	"R_SP110:デスマウンテン(部屋)", // Death Mountain (room)
	0x1b,
	0x1c,
},
{
	"M_029",
	"62 ドン・コローネに相撲勝利", // Win wrestle match against Gor Coron
	"京極", // Kyogoku
	0x704,
	"R_SP110:デスマウンテン(部屋)", // Death Mountain (room)
	0x1b,
	0x1c,
},
{
	"M_028",
	"61 【デモ : 14】山の精霊復活　コリン達との再会", // [cutscene: 14] restore mountain spirit - Reuinion with Colin et al.
	"京極", // Kyogoku
	0x708,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"M_027",
	"60 【デモ : 13】教会にいる子供達（獣の眼）", // [cutscene: 13] kids in the church (beast eyes)
	"京極", // Kyogoku
	0x710,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"M_026",
	"59 ボウと再会した（相撲勝負前のデモを見た）", // Reunion with Bo (Watched cutscene before wrestle match)
	"京極", // Kyogoku
	0x720,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"M_025",
	"58 デブ（長老）ゴロンと初めて相撲勝負した", // First wresting match against fat (elder) goron
	"京極", // Kyogoku
	0x740,
	"R_SP110:デスマウンテン(部屋)", // Death Mountain (room)
	0x1b,
	0x1c,
},
{
	"M_024",
	"57 【デモ : 16】コリン奪還", // [cutscene: 16] take back Colin
	"京極", // Kyogoku
	0x780,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"M_023",
	"56 ★エポナ救出したフラグ", // Epona rescued flag
	"京極", // Kyogoku
	0x601,
	"メインイベント", // main event
	0x22,
	0x23,
},
{
	"M_022",
	"55 ★LV1ダンジョンクリア（ミドナがワープホール出す）★", // LV1 dungeon clear (Midna creates warp hole)
	"京極", // Kyogoku
	0x602,
	"D_MN05:LV1ダンジョン", // LV1 Dungeon
	0x5,
	0x6,
},
{
	"M_021",
	"54 初ポータルワープ", // First portal warp
	"京極", // Kyogoku
	0x604,
	"メインイベント", // main event
	0x22,
	0x23,
},
{
	"M_020",
	"53 【デモ : 　】コリン誘拐 : 見たらON", // [cutscene: ] Colin kidnapped : ON once watched
	"京極", // Kyogoku
	0x608,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"M_019",
	"52 【デモ : 11】森の精霊復活・勇者誕生", // [cutscene: 11] forest spirit revived - Hero's birth
	"京極", // Kyogoku
	0x610,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"M_018",
	"51 ★カカリコ橋を元の場所に運んだ", // Brought Kakariko bridge back to original location
	"京極", // Kyogoku
	0x620,
	"メインイベント", // main event
	0x22,
	0x23,
},
{
	"M_017",
	"50 【デモ : 10】闇のハイラルの森・ミドナ再び", // [cutscene: 10] Dark Hyrule Forest - Midna again
	"京極", // Kyogoku
	0x640,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"M_016",
	"49 【デモ : 9】トアル村の精霊出現", // [cutscene: 9] Ordon village spirit appears
	"京極", // Kyogoku
	0x680,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"M_015",
	"48 ミドナのＢため攻撃使用可能になる", // Can use Midna's B charge attack
	"京極", // Kyogoku
	0x501,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
{
	"M_014",
	"47 【デモ : 8】ミドナによる城からの初ワープ", // [cutscene: 8] First warped from castle by Midna
	"京極", // Kyogoku
	0x502,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"M_013",
	"46 ミドナから初めてトワイライトゲートの話を聞いた", // First heard about Twilight gate from Midna
	"京極", // Kyogoku
	0x504,
	"その他", // Misc.
	0x20,
	0x21,
},
{
	"M_012",
	"45 【デモ : 7】城でゼルダ姫と出会い", // [cutscene: 7] Meet Princess Zelda at castle
	"京極", // Kyogoku
	0x508,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"M_011",
	"44 牢屋でミドナが狼の鎖を外してくれる", // Midna removes wolf's chains in prison
	"京極", // Kyogoku
	0x510,
	"R_SP107:ハイラル城内部", // Inside Hyrule Castle
	0x19,
	0x1a,
},
{
	"M_010",
	"43 【デモ : 6A】牢屋でミドナ登場", // [cutscene: 6A] Midna appears in the prison
	"京極", // Kyogoku
	0x520,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"M_009",
	"42 【デモ : 6B】牢屋脱出 - ミドナが背中に乗る", // [cutscene: 6B] Prison escape - Midna rides on back
	"京極", // Kyogoku
	0x540,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"M_008",
	"41 ★デモ★トアルの泉で魔物に襲われるデモ", // cutscene - attacked by monsters at Ordon spring
	"京極", // Kyogoku
	0x580,
	"*河越デモ", // Kawagoe Cutscene
	0x1,
	0x2,
},
{
	"M_007",
	"40 地下室でシャッドと初会話（解封の言葉の話）", // first conversation with Shad in basement (about the words of opening)
	"京極", // Kyogoku
	0x401,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"M_006",
	"39 ３日目−山羊追いが終わってフリー状態のファドと会話", // 3rd day - finished chasing goats, speak to Fado in free state
	"京極", // Kyogoku
	0x402,
	"F_SP00:牧場", // Ranch
	0xc,
	0xd,
},
{
	"F_0033",
	"38 初日−ウーリと話した", // First day - spoke with Uli
	"京極", // Kyogoku
	0x404,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0032",
	"37 ３日目−ファドと初会話（山羊追い前の強制）", // 3rd day - First convo with fado (before forced goat chase)
	"京極", // Kyogoku
	0x408,
	"F_SP00:牧場", // Ranch
	0xc,
	0xd,
},
{
	"F_0031",
	"36 ２日目−カゴ発見前にウーリと話した？", // 2nd day - Spoke to Uli bfore finding basket
	"京極", // Kyogoku
	0x410,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0030",
	"35 剣チュートリアル前/ベスと初会話", // before sword tutorial - first conversation with Beth
	"京極", // Kyogoku
	0x420,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0029",
	"34 ２日目−剣チューの誘いを断った", // 2nd day - refused sword tutorial
	"京極", // Kyogoku
	0x440,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0028",
	"33 カボチャを持った状態で雪女と話した", // spoke to yeta while holding pumpkin
	"京極", // Kyogoku
	0x480,
	"D_MN11:LV5ダンジョン", // LV5 Dungeon
	0xa,
	0xb,
},
{
	"F_0027",
	"32 ウーリチュートリアル終了（成功/失敗共通）", // Uli tutorial ends (same whether pass or fail)
	"京極", // Kyogoku
	0x301,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0026",
	"31 F0027:タロ−３日目タロに木刀をあげた", // gave wooden sword to talo on 3rd day
	"京極", // Kyogoku
	0x302,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0025",
	"30 ウーリの持ち上げチュートリアル達成", // Pass Uli's pick-up tutorial
	"京極", // Kyogoku
	0x304,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0024",
	"29 F0001:タロ・マロ・ベスと話した（パチンコ入手前）", // Spoke with Talo/Malo/Beth (before obtaining slingshot)
	"京極", // Kyogoku
	0x308,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0023",
	"28 ジャガーに高台の下から呼ばれた", // Called by Jaggle from below hill
	"京極", // Kyogoku
	0x310,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0022",
	"27 １日目の柵越え開始", // Start fence-jump on 1st day
	"京極", // Kyogoku
	0x320,
	"F_SP00:牧場", // Ranch
	0xc,
	0xd,
},
{
	"F_0021",
	"26 ２日目：キュリーと話した", // 2nd day: spoke with Pergie
	"京極", // Kyogoku
	0x340,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"D_0001",
	"25 夜に家の前でリスに呼び止められた",  // Stopped by squirrel in front of house at night
	"京極", // Kyogoku
	0x380,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0020",
	"24 商店休業中にセーラと初会話", // First convo with Sera while shop is closed
	"京極", // Kyogoku
	0x201,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0019",
	"23 泉のイリア（コリンも一緒）と話した", // Spoke with Ilia (Colin is there too) at the spring
	"京極", // Kyogoku
	0x202,
	"F_SP104:トアル森", // Ordon Woods
	0xe,
	0xf,
},
{
	"F_0018",
	"22 ファドに柵越え頼まれた", // Asked by Fado to jump fence
	"京極", // Kyogoku
	0x204,
	"F_SP00:牧場", // Ranch
	0xc,
	0xd,
},
{
	"F_0017",
	"21 剣チュー直後にベスと話した", // Spoke to beth right after sword tutorial
	"京極", // Kyogoku
	0x208,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0016",
	"20 F0048:コリン−３日目通せんぼ時のコリン追跡再開", // On 3rd day, start following Colin who is blocking path
	"京極", // Kyogoku
	0x210,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0015",
	"19 F0076:パチンコチュートリアル終了", // Slingshot tutorial ends
	"京極", // Kyogoku
	0x220,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0014",
	"18 剣チュートリアル終了", // sword tutorial ends
	"京極", // Kyogoku
	0x240,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0013",
	"17 ２日目−暴走山羊を初めて逃がした", // 2nd day - First time rampaging goat escapes
	"京極", // Kyogoku
	0x280,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0012",
	"16 金剛の剣ゲット！", // Get metal sword!
	"京極", // Kyogoku
	0x101,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0011",
	"15 柵越え終了", // Fence jumping complete
	"京極", // Kyogoku
	0x102,
	"F_SP00:牧場", // Ranch
	0xc,
	0xd,
},
{
	"F_0010",
	"14 F0048:コリン−３日目通せんぼ時に初会話（強制）", // First convo with Colin blocking path (forced)
	"京極", // Kyogoku
	0x104,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0009",
	"13 コリンと秘密の入り口前に近づいた", // Approach secret entrance with Colin
	"京極", // Kyogoku
	0x108,
	"F_SP104:トアル森", // Ordon Woods
	0xe,
	0xf,
},
{
	"F_0008",
	"12 １日目のファドと牧場で初会話", // First conversation with Fado at the farm on 1st day
	"京極", // Kyogoku
	0x110,
	"F_SP103:トアル村", // Ordon Village
	0xd,
	0xe,
},
{
	"F_0007",
	"11 チーズを持った状態で雪女と話した", // Spoke to Yeta while holding cheese
	"京極", // Kyogoku
	0x120,
	"D_MN11:LV5ダンジョン", // LV5 Dungeon
	0xa,
	0xb,
},
{
	"F_0006",
	"10 キッチンで雪男と初会話", // First conversation with Yeto in kitchen
	"京極", // Kyogoku
	0x140,
	"D_MN11:LV5ダンジョン", // LV5 Dungeon
	0xa,
	0xb,
},
{
	"F_0005",
	"9 エリア4で光の雫を14個集めた", // Gathered 14 Tears of Light in area 4
	"京極（今井使用）", // Kyogoku (used by Imai)
	0x180,
	"その他", // Misc.
	0x20,
	0x21,
},
{
	"F_0004",
	"8 隠し味の素を渡して、部屋の外に出た", // Handed over secret ingredient and left room
	"京極", // Kyogoku
	0x1,
	"D_MN11:LV5ダンジョン", // LV5 Dungeon
	0xa,
	0xb,
},
{
	"F_0003",
	"7 トマトピューレを渡して、部屋の外に出た", // Handed over tomato puree and left room
	"京極", // Kyogoku
	0x2,
	"D_MN11:LV5ダンジョン", // LV5 Dungeon
	0xa,
	0xb,
},
{
	"F_0002",
	"6 長老ゴロンとの相撲勝負に初めて負けた", // Lost wrestling match to elder goron for first time
	"京極", // Kyogoku
	0x4,
	"R_SP110:デスマウンテン(部屋)", // Death Mountain (room)
	0x1b,
	0x1c,
},
{
	"F_0001",
	"5 コリン復帰後のレナードと話した", // Spoke to Renado after Colin returns
	"京極", // Kyogoku
	0x8,
	"F_SP109:カカリコ村", // Kakariko Village
	0x10,
	0x11,
},
{
	"TEST_004",
	"4 隠し味の素を渡した", // Handed over secret ingredient
	"京極", // Kyogoku
	0x10,
	"D_MN11:LV5ダンジョン", // LV5 Dungeon
	0xa,
	0xb,
},
{
	"TEST_003",
	"3 トマトピューレを渡した", // Handed over tomato puree
	"京極", // Kyogoku
	0x20,
	"D_MN11:LV5ダンジョン", // LV5 Dungeon
	0xa,
	0xb,
},
{
	"TEST_002",
	"2 大溶岩弾ポータルワープヒント", // Big magma stone portal warp hint
	"京極", // Kyogoku
	0x40,
	"F_SP110:デスマウンテン", // Death Mountain
	0x11,
	0x12,
},
{
	"TEST_001",
	"1 カカリコ橋ポータルワープヒント", // Kakariko bridge portal warp hint
	"京極", // Kyogoku
	0x80,
	"F_SP108:フィローネの森", // Faron Woods
	0xf,
	0x10,
},
