{
	"KAKERA_GET_INFO_05",
	"765 ハ−トのかけらゲット情報", // Info about getting heart piece
	"住吉", // Sumiyoshi
	0xebff,
	"その他", // Misc.
	0x3,
	0x21,
},
{
	"KAKERA_GET_INFO_04",
	"764 ハ−トのかけらゲット情報", // Info about getting heart piece
	"住吉", // Sumiyoshi
	0xecff,
	"その他", // Misc.
	0x3,
	0x21,
},
{
	"KAKERA_GET_INFO_03",
	"763 ハ−トのかけらゲット情報", // Info about getting heart piece
	"住吉", // Sumiyoshi
	0xedff,
	"その他", // Misc.
	0x3,
	0x21,
},
{
	"KAKERA_GET_INFO_02",
	"762 ハ−トのかけらゲット情報", // Info about getting heart piece
	"住吉", // Sumiyoshi
	0xeeff,
	"その他", // Misc.
	0x3,
	0x21,
},
{
	"KAKERA_GET_INFO_01",
	"761 ハ−トのかけらゲット情報", // Info about getting heart piece
	"住吉", // Sumiyoshi
	0xefff,
	"その他", // Misc.
	0x3,
	0x21,
},
{
	"KAKERA_GET_INFO_00",
	"760 ハ−トのかけらゲット情報", // Info about getting heart piece
	"住吉", // Sumiyoshi
	0xf0ff,
	"その他", // Misc.
	0x3,
	0x21,
},
{
	"SP_LURE__USE_COUNT",
	"731 沈むルアーで何匹釣ったか(最大31匹）", // Number of fish caught with sinking lure (Max: 31)
	"森田", // Morita
	0xf11f,
	"釣り", // Fishing
	0x4,
	0x29,
},
{
	"CF_RECORD_0",
	"714 つりぼり内水槽用（トアルナマズのサイズ）", // Fishing hut fish tank (Ordon Catfish Size)
	"森田", // Morita
	0xf27f,
	"釣り", // Fishing
	0x4,
	0x29,
},
{
	"NP_RECORD_0",
	"713 つりぼり内水槽用（ハイリアパイクのサイズ）", // Fishing hut fish tank (Hylian Pike Size)
	"森田", // Morita
	0xf37f,
	"釣り", // Fishing
	0x4,
	0x29,
},
{
	"RI_RECORD_0",
	"712 つりぼり内水槽用（ハイラルドジョウのサイズ）", // Fishing hut fish tank (Hylian Loach Size)
	"森田", // Morita
	0xf47f,
	"釣り", // Fishing
	0x4,
	0x29,
},
{
	"LM_RECORD_0",
	"711 つりぼり内水槽用（バスのサイズ）", // Fishing hut fish tank (Bass Size)
	"森田", // Morita
	0xf57f,
	"釣り", // Fishing
	0x4,
	0x29,
},
{
	"KORO2_LEVEL",
	"710 コロコロゲームのレベル記憶用", // Roll goal game level memory use
	"森田", // Morita
	0xf63f,
	"R_SP127:釣堀(屋内)", // Fishing Pond (inside)
	0x2,
	0x1d,
},
{
	"FUND_RAISING_HIGH2",
	"512 お布施上位ビット", // Donations top bit
	"坂口", // Sakaguchi
	0xf7ff,
	"店", // Shop
	0x5,
	0x2b,
},
{
	"FUND_RAISING_LOW2",
	"511 お布施下位ビット", // Donations bottom bit
	"坂口", // Sakaguchi
	0xf8ff,
	"店", // Shop
	0x5,
	0x2b,
},
{
	"FUND_RAISING_HIGH",
	"452 募金額上位ビット", // Fundraising top bit
	"坂口", // Sakaguchi
	0xf9ff,
	"店", // Shop
	0x5,
	0x2b,
},
{
	"FUND_RAISING_LOW",
	"451 募金額下位ビット", // Fundraising bottom bit
	"坂口", // Sakaguchi
	0xfaff,
	"店", // Shop
	0x5,
	0x2b,
},
{
	"TOTAL_PAYMENT_LOW",
	"201 無人販売支払い総額上位ビット", // Unmanned shop payment total top bit (typo maybe? should be bottom bit?)
	"坂口", // Sakaguchi
	0xfbff,
	"店", // Shop
	0x5,
	0x2b,
},
{
	"TOTAL_PAYMENT_HIGH",
	"200 無人販売支払い総額上位ビット", // Unmanned shop payment total top bit
	"坂口", // Sakaguchi
	0xfcff,
	"店", // Shop
	0x5,
	0x2b,
},
{
	"TOTAL_PRICE_LOW",
	"199 無人販売購入総額下位ビット", // Unmanned shop total price bottom bit
	"坂口", // Sakaguchi
	0xfdff,
	"店", // Shop
	0x5,
	0x2b,
},
{
	"TOTAL_PRICE_HIGH",
	"198 無人販売購入総額上位ビット", // unmanned shop total price top bit
	"坂口", // Sakaguchi
	0xfeff,
	"店", // Shop
	0x5,
	0x2b,
},
{
	"EREG_000",
	"185 山羊暴走回数", // Rampaging goats number
	"住吉", // Sumiyoshi
	0xff1f,
	"F_SP00:牧場", // Ranch
	0x1,
	0xd,
},