// 
// Generated By: dol2asm
// Translation Unit: dvdidutils
// 

#include "dol2asm.h"
#include "dolphin/types.h"
#include "dolphin/dvd/dvdidutils.h"

// 
// Forward References:
// 


// False False
extern "C" void DVDCompareDiskID();

// 
// External References:
// 


// False False
extern "C" void strncmp();

// 
// Declarations:
// 

/* 8034BC04-8034BCFC 00F8+00 s=0 e=1 z=0  None .text      DVDCompareDiskID                                             */
//	8034BC44: 80368954 (strncmp)
//	8034BC7C: 80368954 (strncmp)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
// False False
extern "C" asm void DVDCompareDiskID() {
	nofralloc
#include "asm/dolphin/dvd/dvdidutils/DVDCompareDiskID.s"
}
#pragma pop


