{
	"SHA_DBG",
	"184 占い師デバッグ", // Fortune teller debug
	"住吉", // Sumiyoshi
	0xf2ff,
	"F_SP116:城下街", // Castle Town
	0x2,
	0xe,
},
{
	"PACHITUTORIAL_INF",
	"115 パチチュ−、ヒット情報", // Slingshot tutorial, hit information
	"住吉", // Sumiyoshi
	0xf3ff,
	"F_SP103:トアル村", // Ordon Village
	0x1,
	0x7,
},
{
	"PACHITUTORIAL_CNT",
	"114 パチチュ−、壊した的の数", // Slingshot tutorial, number of destroyed targets
	"住吉", // Sumiyoshi
	0xf4ff,
	"F_SP103:トアル村", // Ordon Village
	0x1,
	0x7,
},
{
	"SHA_LOVEFORTUNE_05",
	"106 恋愛運シ−ン切り替え先記憶用", // For memory use after love fortune scene change
	"住吉", // Sumiyoshi
	0xf5ff,
	"F_SP116:城下街", // Castle Town
	0x2,
	0xe,
},
{
	"SHA_LOVEFORTUNE_04",
	"105 恋愛運シ−ン切り替え先記憶用", // For memory use after love fortune scene change
	"住吉", // Sumiyoshi
	0xf6ff,
	"F_SP116:城下街", // Castle Town
	0x2,
	0xe,
},
{
	"SHA_LOVEFORTUNE_03",
	"104 恋愛運シ−ン切り替え先記憶用", // For memory use after love fortune scene change
	"住吉", // Sumiyoshi
	0xf7ff,
	"F_SP116:城下街", // Castle Town
	0x2,
	0xe,
},
{
	"SHA_LOVEFORTUNE_02",
	"103 恋愛運シ−ン切り替え先記憶用", // For memory use after love fortune scene change
	"住吉", // Sumiyoshi
	0xf8ff,
	"F_SP116:城下街", // Castle Town
	0x2,
	0xe,
},
{
	"SHA_LOVEFORTUNE_01",
	"102 恋愛運シ−ン切り替え先記憶用", // For memory use after love fortune scene change
	"住吉", // Sumiyoshi
	0xf9ff,
	"F_SP116:城下街", // Castle Town
	0x2,
	0xe,
},
{
	"SHA_LOVEFORTUNE_00",
	"101 恋愛運シ−ン切り替え先記憶用", // For memory use after love fortune scene change
	"住吉", // Sumiyoshi
	0xfaff,
	"F_SP116:城下街", // Castle Town
	0x2,
	0xe,
},
{
	"TREG_000",
	"34 キュリ−の会話で使います", // Used in conversation with Pergie
	"住吉", // Sumiyoshi
	0xfbff,
	"F_SP103:トアル村", // Ordon Village
	0x1,
	0x7,
},
{
	"T_0006",
	"6 戻り先のレイヤ−番号", // Return layer number
	"住吉", // Sumiyoshi
	0xfcff,
	"仮デモ", // temp cutscene
	0x3,
	0x14,
},
{
	"T_0005",
	"5 実行デモNo受け渡し", // Actual cutscene number delivery
	"住吉", // Sumiyoshi
	0xfdff,
	"仮デモ", // temp cutscene
	0x3,
	0x14,
},
{
	"T_0003",
	"3 剣チュ−トリアル・斬った回数", // Sword tutorial - slice count
	"住吉", // Sumiyoshi
	0xfeff,
	"F_SP103:トアル村", // Ordon Village
	0x1,
	0x7,
},
{
	"T_0002",
	"2 剣チュ−トリアル・ステップ", // Sword tutorial - step
	"住吉", // Sumiyoshi
	0xff0f,
	"F_SP103:トアル村", // Ordon Village
	0x1,
	0x7,
},
