{
	"T_0183",
	"183 @",
	"住吉", // Sumiyoshi
	0x1580,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"T_0182",
	"182 山羊追いⅡ終了した", //  Finished goat hearding Ⅱ
	"住吉", // Sumiyoshi
	0x1401,
	"F_SP00:牧場", // Ranch
	0x5,
	0x6,
},
{
	"T_0181",
	"181 山羊追いⅡ開始した", // Started goat hearding Ⅱ
	"住吉", // Sumiyoshi
	0x1402,
	"F_SP00:牧場", // Ranch
	0x5,
	0x6,
},
{
	"T_0180",
	"180 ３日目−山羊追いゲームEND", // 3rd day - goat hearding END
	"住吉", // Sumiyoshi
	0x1404,
	"F_SP00:牧場", // Ranch
	0x5,
	0x6,
},
{
	"T_0179",
	"179 ３日目−山羊追いゲームＳＴＡＲＴ", // 3rd day - goat hearding START
	"住吉", // Sumiyoshi
	0x1408,
	"F_SP00:牧場", // Ranch
	0x5,
	0x6,
},
{
	"T_0178",
	"178 １日目：柵越え中にファドと話した", // 1st day: Spoke with Fado while jumping over gate
	"京極", // Kyogoku
	0x1410,
	"F_SP00:牧場", // Ranch
	0x5,
	0x6,
},
{
	"T_0177",
	"177 １日目：ファドに柵越えたのまれた", // 1st day : Asked to jump gate by Fado
	"京極", // Kyogoku
	0x1420,
	"F_SP00:牧場", // Ranch
	0x5,
	0x6,
},
{
	"T_0176",
	"176 １日目：ファドの山羊追い終了", // 1st day: finish fado's goat herding
	"京極", // Kyogoku
	0x1440,
	"F_SP00:牧場", // Ranch
	0x5,
	0x6,
},
{
	"T_0175",
	"175 １日目：ファドの山羊追い開始", // 1st day: strt Fado's goat herding
	"京極", // Kyogoku
	0x1480,
	"F_SP00:牧場", // Ranch
	0x5,
	0x6,
},
{
	"NO_TELOP",
	"174 ONなら(シ−ン切り換え時)ステ−ジ名の表示なし", // When on (while changing scenes) stage name is not shown
	"住吉", // Sumiyoshi
	0x1301,
	"汎用", // General use
	0x14,
	0x16,
},
{
	"NODRAW_STAGE_NAME",
	"173 @",
	"住吉", // Sumiyoshi
	0x1302,
	"汎用", // General use
	0x14,
	0x16,
},
{
	"Hanch_CLIMBOUT_POND",
	"172 飛び込んだハンジョ−、池から出た", // Hanch gets out of lake after jumping in
	"住吉", // Sumiyoshi
	0x1304,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"GUARD_URI",
	"171 夜のトアル村、モイがウ−リを守り中", // Rusl is guarding Uli, Ordon village night
	"住吉", // Sumiyoshi
	0x1308,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"CAT_20",
	"170 20",
	"京極", // Kyogoku
	0x1310,
	"ボンニャーズ", // cat game
	0x12,
	0x13,
},
{
	"CAT_19",
	"169 19",
	"京極", // Kyogoku
	0x1320,
	"ボンニャーズ", // cat game
	0x12,
	0x13,
},
{
	"CAT_18",
	"168 初日のセーラ一家との会話用2", // Used in conversation with Sera's household on first day (2) 
	"京極", // Kyogoku
	0x1340,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"CAT_17",
	"167 初日のセーラ一家との会話用１", // Used in conversation with Sera's household on first day (1) 
	"京極", // Kyogoku
	0x1380,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"CAT_16",
	"166 16",
	"京極", // Kyogoku
	0x1201,
	"ボンニャーズ", // cat game
	0x12,
	0x13,
},
{
	"CAT_15",
	"165 15",
	"京極", // Kyogoku
	0x1202,
	"ボンニャーズ", // cat game
	0x12,
	0x13,
},
{
	"CAT_14",
	"164 Jpn06-0118天空人のオバチャン別れイベント用4", // Used in Ooccoo Sr. departure event (4)
	"京極", // Kyogoku
	0x1204,
	"F_SP117:聖なる森", // Sacred Grove
	0xe,
	0xf,
},
{
	"CAT_13",
	"163 Jpn06-0118天空人のオバチャン別れイベント用3", // Used in Ooccoo Sr. departure event (3)
	"京極", // Kyogoku
	0x1208,
	"F_SP117:聖なる森", // Sacred Grove
	0xe,
	0xf,
},
{
	"CAT_12",
	"162 Jpn06-0118天空人のオバチャン別れイベント用2", // Used in Ooccoo Sr. departure event (2)
	"京極", // Kyogoku
	0x1210,
	"F_SP117:聖なる森", // Sacred Grove
	0xe,
	0xf,
},
{
	"CAT_11",
	"161 Jpn06-0118天空人のオバチャン別れイベント用1", // Used in Ooccoo Sr. departure event (1)
	"京極", // Kyogoku
	0x1220,
	"F_SP117:聖なる森", // Sacred Grove
	0xe,
	0xf,
},
{
	"CAT_10",
	"160 10",
	"京極", // Kyogoku
	0x1240,
	"ボンニャーズ", // cat game
	0x12,
	0x13,
},
{
	"CAT_9",
	"159 9",
	"京極", // Kyogoku
	0x1280,
	"ボンニャーズ", // cat game
	0x12,
	0x13,
},
{
	"CAT_8",
	"158 8",
	"京極", // Kyogoku
	0x1101,
	"ボンニャーズ", // cat game
	0x12,
	0x13,
},
{
	"CAT_7",
	"157 7",
	"京極", // Kyogoku
	0x1102,
	"ボンニャーズ", // cat game
	0x12,
	0x13,
},
{
	"CAT_6",
	"156 子ども発見前にウーリの部屋に入った(強制会話時にON)", // Endered Uli's room before finding children (ON during forced conversation)
	"京極", // Kyogoku
	0x1104,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"CAT_5",
	"155 TW迷い霧の森でミドナの忠告聞いた(F:2021)", // Heard Midna's warning in Twilight fog woods
	"京極", // Kyogoku
	0x1108,
	"F_SP108:フィローネの森", // Faron Woods
	0x7,
	0x8,
},
{
	"CAT_4",
	"154 4",
	"京極", // Kyogoku
	0x1110,
	"ボンニャーズ", // cat game
	0x12,
	0x13,
},
{
	"CAT_3",
	"153 ３日目、最初のファドの会話", // 3rd day, Fado's first conversation
	"京極", // Kyogoku
	0x1120,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"CAT_2",
	"152 ３日目：山羊追い後にファドと話した", // 3rd day: Spoke with Fado after herding goats
	"京極", // Kyogoku
	0x1140,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"CAT_1",
	"151 ３日目：山羊追い結果聞いた", // 3rd day: Heard results of goat herding
	"京極", // Kyogoku
	0x1180,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"DUNGEON_150",
	"150 ダンジョン150", // Dungeon 150
	"京極", // Kyogoku
	0x1001,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"DUNGEON_149",
	"149 ダンジョン149", // Dungeon 149
	"京極", // Kyogoku
	0x1002,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"DUNGEON_148",
	"148 ダンジョン148",  // Dungeon 148
	"京極", // Kyogoku
	0x1004,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"DUNGEON_147",
	"147 ダンジョン147",  // Dungeon 147
	"京極", // Kyogoku
	0x1008,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"DUNGEON_146",
	"146 ダンジョン146",  // Dungeon 146
	"京極", // Kyogoku
	0x1010,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"DUNGEON_145",
	"145 ダンジョン145",  // Dungeon 145
	"京極", // Kyogoku
	0x1020,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"DUNGEON_144",
	"144 ダンジョン144", // Dungeon 144
	"京極", // Kyogoku
	0x1040,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"DUNGEON_143",
	"143 ダンジョン143", // Dungeon 143
	"京極", // Kyogoku
	0x1080,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"DUNGEON_142",
	"142 ダンジョン142", // Dungeon 142
	"京極", // Kyogoku
	0xf01,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"DUNGEON_141",
	"141 ダンジョン141", // Dungeon 141
	"京極", // Kyogoku
	0xf02,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"DUNGEON_140",
	"140 ダンジョン140", // Dungeon 140
	"京極", // Kyogoku
	0xf04,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"DUNGEON_139",
	"139 ダンジョン139", // Dungeon 139
	"京極", // Kyogoku
	0xf08,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"DUNGEON_138",
	"138 ダンジョン138", // Dungeon 138
	"京極", // Kyogoku
	0xf10,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"DUNGEON_137",
	"137 ダンジョン137", // Dungeon 137
	"京極", // Kyogoku
	0xf20,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"DUNGEON_136",
	"136 ダンジョン136", // Dungeon 136
	"京極", // Kyogoku
	0xf40,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"DUNGEON_135",
	"135 ダンジョン135", // Dungeon 135
	"京極", // Kyogoku
	0xf80,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"DUNGEON_134",
	"134 ダンジョン134", // Dungeon 134
	"京極", // Kyogoku
	0xe01,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"DUNGEON_133",
	"133 ダンジョン133", // Dungeon 133
	"京極", // Kyogoku
	0xe02,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"DUNGEON_132",
	"132 ダンジョン132", // Dungeon 132
	"京極", // Kyogoku
	0xe04,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"DUNGEON_131",
	"131 ダンジョン131", // Dungeon 131
	"京極", // Kyogoku
	0xe08,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"DUNGEON_130",
	"130 中ボス戦中のミドナヒントを聞いた", // Heard Midna's hint during mini-boss
	"京極", // Kyogoku
	0xe10,
	"D_MN06:LV6ダンジョン", // LV6 Dungeon
	0x2,
	0x3,
},
{
	"T_0125",
	"129 @",
	"京極", // Kyogoku
	0xe20,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"YKW_ATTN",
	"128 スノボレ−ス待機時の雪女、プレイヤ−注視中", // Player focus while Yeta waits for snowboard race
	"住吉", // Sumiyoshi
	0xe40,
	"F_SP114:雪山", // Snowpeak mountain
	0xb,
	0xc,
},
{
	"YKW_TALK",
	"127 雪女が雪男に話しかける", // Yeta talks to Yeto
	"住吉", // Sumiyoshi
	0xe80,
	"F_SP114:雪山", // Snowpeak mountain
	0xb,
	0xc,
},
{
	"YKM_TALK",
	"126 雪男が雪女に話しかける", // Yeto talks to Yeta
	"住吉", // Sumiyoshi
	0xd01,
	"F_SP114:雪山", // Snowpeak mountain
	0xb,
	0xc,
},
{
	"YKM_ATTN",
	"125 スノボレ−ス待機時の雪男、プレイヤ−注視中", // Player focus while Yeto waits for snowboard race
	"住吉", // Sumiyoshi
	0xd02,
	"F_SP114:雪山", // Snowpeak mountain
	0xb,
	0xc,
},
{
	"T_0124",
	"124 大妖精用4", // Fairy use 4
	"京極（高橋使用）", // Kyogoku (used by Takahashi)
	0xd04,
	"プログラム用", // program use
	0x11,
	0x12,
},
{
	"T_0123",
	"123 大妖精用3", // Fairy use 3
	"京極（高橋使用）", // Kyogoku (used by Takahashi)
	0xd08,
	"プログラム用", // program use
	0x11,
	0x12,
},
{
	"T_0122",
	"122 大妖精用2", // Fairy use 2
	"京極（高橋使用）", // Kyogoku (used by Takahashi)
	0xd10,
	"プログラム用", // program use
	0x11,
	0x12,
},
{
	"T_0121",
	"121 大妖精用1", // Fairy use 1
	"京極（高橋使用）", // Kyogoku (used by Takahashi)
	0xd20,
	"プログラム用", // program use
	0x11,
	0x12,
},
{
	"T_0120",
	"120 ヘナのガイドで釣りをした", // Fished something with Hena's guidance
	"京極", // Kyogoku
	0xd40,
	"釣り", // Fishing
	0x13,
	0x15,
},
{
	"T_0119",
	"119 コロコロゲームでズルした直後", // After cheating in Roll goal game
	"京極", // Kyogoku
	0xd80,
	"釣り", // Fishing
	0x13,
	0x15,
},
{
	"MN09_03",
	"118 ラフレルの大砲が着弾したフラグ", // Auru's cannon hits Flag
	"桑島", // Kuwashima
	0xc01,
	"D_MN09:Lv9ダンジョン", // LV9 Dungeon
	0x3,
	0x4,
},
{
	"MN09_02",
	"117 モイがリンクに手を振るフラグ", // Risl waves at Link Flag
	"桑島", // Kuwashima
	0xc02,
	"D_MN09:Lv9ダンジョン", // LV9 Dungeon
	0x3,
	0x4,
},
{
	"WXXTO",
	"116 レジスタンス立ち去るフラグ", // Resistance leaves Flag
	"桑島", // Kuwashima
	0xc04,
	"D_MN09:Lv9ダンジョン", // LV9 Dungeon
	0x3,
	0x4,
},
{
	"T_0113",
	"113 【イベント制御】Jpn04-1063:ルイーズ用7", // (Event control) Jpn04-1063:Luoise Use (7)
	"京極", // Kyogoku
	0xc08,
	"F_SP116:城下街", // Castle Town
	0xd,
	0xe,
},
{
	"T_0112",
	"112 【イベント制御】Jpn04-1063:ルイーズ用6", // (Event control) Jpn04-1063:Luoise Use (6)
	"京極", // Kyogoku
	0xc10,
	"F_SP116:城下街", // Castle Town
	0xd,
	0xe,
},
{
	"T_0111",
	"111 【イベント制御】Jpn04-1063:ルイーズ用5", // (Event control) Jpn04-1063:Luoise Use (5)
	"京極", // Kyogoku
	0xc20,
	"F_SP116:城下街", // Castle Town
	0xd,
	0xe,
},
{
	"T_0110",
	"110 【イベント制御】Jpn04-1063:ルイーズ用4", // (Event control) Jpn04-1063:Luoise Use (4)
	"京極", // Kyogoku
	0xc40,
	"F_SP116:城下街", // Castle Town
	0xd,
	0xe,
},
{
	"T_0109",
	"109 【イベント制御】Jpn04-1063:ルイーズ用3", // (Event control) Jpn04-1063:Luoise Use (3)
	"京極", // Kyogoku
	0xc80,
	"F_SP116:城下街", // Castle Town
	0xd,
	0xe,
},
{
	"T_0108",
	"108 【イベント制御】Jpn04-1063:ルイーズ用2", // (Event control) Jpn04-1063:Luoise Use (2)
	"京極", // Kyogoku
	0xb01,
	"F_SP116:城下街", // Castle Town
	0xd,
	0xe,
},
{
	"T_0107",
	"107 【イベント制御】Jpn04-1063:ルイーズ用1", // (Event control) Jpn04-1063:Luoise Use (1)
	"京極", // Kyogoku
	0xb02,
	"F_SP116:城下街", // Castle Town
	0xd,
	0xe,
},
{
	"T_0100",
	"100 ２日目はじまりデモ、子どもたち注目開始フラグ", // cutscene at start of 2nd day, start focus on kids Flags
	"住吉", // Sumiyoshi
	0xb04,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0099",
	"99 @",
	"京極", // Kyogoku
	0xb08,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"T_0098",
	"98 @",
	"京極", // Kyogoku
	0xb10,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"T_0097",
	"97 ゴールドウルフ識別７", // Gold wolf identification 7
	"京極（今井使用）", // Kyogoku (used by Imai)
	0xb20,
	"勇者の霊", // Hero's spirit
	0x15,
	0x17,
},
{
	"T_0096",
	"96 ゴールドウルフ識別６", // Gold wolf identification 6
	"京極（今井使用）", // Kyogoku (used by Imai)
	0xb40,
	"勇者の霊", // Hero's spirit
	0x15,
	0x17,
},
{
	"T_0095",
	"95 ゴールドウルフ識別５", // Gold wolf identification 5
	"京極（今井使用）", // Kyogoku (used by Imai)
	0xb80,
	"勇者の霊", // Hero's spirit
	0x15,
	0x17,
},
{
	"T_0094",
	"94 ゴールドウルフ識別４", // Gold wolf identification 4
	"京極（今井使用）", // Kyogoku (used by Imai)
	0xa01,
	"勇者の霊", // Hero's spirit
	0x15,
	0x17,
},
{
	"T_0093",
	"93 ゴールドウルフ識別３", // Gold wolf identification 3
	"京極（今井使用）", // Kyogoku (used by Imai)
	0xa02,
	"勇者の霊", // Hero's spirit
	0x15,
	0x17,
},
{
	"T_0092",
	"92 ゴールドウルフ識別２", // Gold wolf identification 2
	"京極（今井使用）", // Kyogoku (used by Imai)
	0xa04,
	"勇者の霊", // Hero's spirit
	0x15,
	0x17,
},
{
	"T_0091",
	"91 後半で山羊追いゲームした（一日チェック用）", // Goat hearding in second half (for day 1 check)
	"京極", // Kyogoku
	0xa08,
	"F_SP00:牧場", // Ranch
	0x5,
	0x6,
},
{
	"T_0090",
	"90 牧場内にエポナがいる（山羊追いゲーム用）", // Epona is at the range (used in goat herding game)
	"京極", // Kyogoku
	0xa10,
	"F_SP00:牧場", // Ranch
	0x5,
	0x6,
},
{
	"T_0089",
	"89 トアル村中心の範囲内にエポナがいる（１日目ボウ用）", // Epona is in the middle of ordon village (used by Bo first day)
	"京極", // Kyogoku
	0xa20,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0088",
	"88 中ボスがダウン中のみON（復帰したらリセット）", // ON only with mini-boss is down (resets when they get up)
	"京極", // Kyogoku
	0xa40,
	"D_MN04:LV4ダンジョン",
	0x1,
	0x2,
},
{
	"T_0087",
	"87 マロマート店内の子供A[、]B用（共通）", // Used by child A,B (both) inside Malo Mart
	"京極", // Kyogoku
	0xa80,
	"F_SP116:城下街", // Castle Town
	0xd,
	0xe,
},
{
	"T_0086",
	"86 雪男/雪女とのレースに勝った", // Won race against Yeto/Yeta
	"京極", // Kyogoku
	0x901,
	"F_SP114:雪山", // Snowpeak mountain
	0xb,
	0xc,
},
{
	"T_0085",
	"85 雪女とレ−ス中", // Racing with Yeta
	"京極", // Kyogoku
	0x902,
	"F_SP114:雪山", // Snowpeak mountain
	0xb,
	0xc,
},
{
	"T_0084",
	"84 雪男とレ−ス中", // Racing with Yeto
	"京極", // Kyogoku
	0x904,
	"F_SP114:雪山", // Snowpeak mountain
	0xb,
	0xc,
},
{
	"T_0083",
	"83 LV5Dクリア後の雪男（女）と雪山頂上で狼会話", // Speak with Yeta at top of mountain as wolf after clearing LV5 dungeon
	"京極", // Kyogoku
	0x908,
	"D_MN11:LV5ダンジョン", // LV5 Dungeon
	0x4,
	0x5,
},
{
	"T_0082",
	"82 温泉ゴロンにかけたのが水だった", // Threw water on spring goron
	"京極", // Kyogoku
	0x910,
	"F_SP116:城下街", // Castle Town
	0xd,
	0xe,
},
{
	"T_0081",
	"81 募金イベント達成デモ用", // For use in fundraiser event completion cutscene
	"京極", // Kyogoku
	0x920,
	"F_SP109:カカリコ村", // Kakariko Village
	0x8,
	0x9,
},
{
	"T_0080",
	"80 募金箱にお金いれた", // Put money in fundraiser box
	"京極", // Kyogoku
	0x940,
	"F_SP109:カカリコ村", // Kakariko Village
	0x8,
	0x9,
},
{
	"T_0079",
	"79 Ｗクローショット屋：自己ベスト更新", // Double clawshot shop: new personal best
	"京極", // Kyogoku
	0x980,
	"F_SP116:城下街", // Castle Town
	0xd,
	0xe,
},
{
	"T_0078",
	"78 Ｗクローショット屋：玉全部取った", // Double clawshot shop : Collected all the spheres
	"京極", // Kyogoku
	0x801,
	"F_SP116:城下街", // Castle Town
	0xd,
	0xe,
},
{
	"T_0077",
	"77 @",
	"京極", // Kyogoku
	0x802,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"T_0076",
	"76 用心棒ゴロンのぼやきを聞いた", // Listened to bodyguard goron's complaints 
	"京極", // Kyogoku
	0x804,
	"F_SP116:城下街", // Castle Town
	0xd,
	0xe,
},
{
	"T_0075",
	"75 スモモのアトラクションで一定の得点に達した", // Got more points than the set amount during Plumm's attraction
	"京極", // Kyogoku
	0x808,
	"F_SP115:ハイリア湖", // Lake Hylia
	0xc,
	0xd,
},
{
	"T_0074",
	"74 (会話後)スモモが画面外に消えたらリセット", // (after conversation) Resets when Plumm goes off-screen
	"京極", // Kyogoku
	0x810,
	"F_SP115:ハイリア湖", // Lake Hylia
	0xc,
	0xd,
},
{
	"T_0073",
	"73 マスターソードゲットイベント用", // For use in master sword obtaining event
	"京極", // Kyogoku
	0x820,
	"F_SP117:聖なる森", // Sacred Grove
	0xe,
	0xf,
},
{
	"T_0072",
	"72 ラッカ小屋のコッコを全部落とした", // Knocked down all the cucco in Falbi's hut
	"京極（住吉使用）", // Kyogoku (used by Sumiyoshi)
	0x840,
	"F_SP115:ハイリア湖", // Lake Hylia
	0xc,
	0xd,
},
{
	"T_0071",
	"71 夜、モイの剣とろうとして失敗（超接近or殴られた）", // Night, fail to take Rusl's sword (too close OR get hit)
	"京極（住吉使用）", // Kyogoku (used by Sumiyoshi)
	0x880,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0070",
	"70 【ホヅ川下り】ボート小屋内のガレキ破壊手伝い中", // [Iza's river descent] Helping to destroy rubble in boat hut
	"京極", // Kyogoku
	0x701,
	"F_SP112:ゾーラ川", // Zora's River
	0xa,
	0xb,
},
{
	"T_0069",
	"69 【水中爆弾屋】１５コ購入選択中", // [water bomb shop] choose to buy 15
	"京極", // Kyogoku
	0x702,
	"F_SP115:ハイリア湖", // Lake Hylia
	0xc,
	0xd,
},
{
	"T_0068",
	"68 【水中爆弾屋】１０コ購入選択中", // [water bomb shop] choose to buy 10
	"京極", // Kyogoku
	0x704,
	"F_SP115:ハイリア湖", // Lake Hylia
	0xc,
	0xd,
},
{
	"T_0067",
	"67 【ホヅ川下り】ボートに乗る", // [Iza's river descent] Get in boat
	"住吉", // Sumiyoshi
	0x708,
	"F_SP112:ゾーラ川", // Zora's River
	0xa,
	0xb,
},
{
	"T_0066",
	"66 【弓矢ゲーム】途中から再開した", // [bow and arrow game] Restart from the middle
	"京極", // Kyogoku
	0x710,
	"F_SP109:カカリコ村", // Kakariko Village
	0x8,
	0x9,
},
{
	"T_0065",
	"65 【弓矢ゲーム】１つ目をフックショットで破壊", // [bow and arrow game] destroy first one with hook shot
	"京極（住吉使用）", // Kyogoku (used by Sumiyoshi)
	0x720,
	"F_SP109:カカリコ村", // Kakariko Village
	0x8,
	0x9,
},
{
	"T_0064",
	"64 【弓矢ゲーム】的当て挑戦中...", // [bow and arrow game]  attempting to hit target...
	"京極（住吉使用）", // Kyogoku (used by Sumiyoshi)
	0x740,
	"F_SP109:カカリコ村", // Kakariko Village
	0x8,
	0x9,
},
{
	"T_0063",
	"63 【弓矢ゲーム】最後の的、惜しい！", // [bow and arrow game] Missed the final target!
	"京極（住吉使用）", // Kyogoku (used by Sumiyoshi)
	0x780,
	"F_SP109:カカリコ村", // Kakariko Village
	0x8,
	0x9,
},
{
	"T_0062",
	"62 馬車護衛直前デモ（イリアと再会）", // cutscene right before carriage guarding mission (reunion with Ilia)
	"京極", // Kyogoku
	0x601,
	"？",
	0x10,
	0x11,
},
{
	"T_0061",
	"61 一騎リベンジ終了（馬車護衛再開）", // Joust revenge complete (restart carriage guarding mission)
	"京極", // Kyogoku
	0x602,
	"？",
	0x10,
	0x11,
},
{
	"T_0060",
	"60 弓矢ゲ−ム中", // during bow and arrow game
	"住吉", // Sumiyoshi
	0x604,
	"F_SP109:カカリコ村", // Kakariko Village
	0x8,
	0x9,
},
{
	"T_0059",
	"59 ルダ＆ベスが交互にコリンに食事をとらせる", // Luda and Beth both taking Colin's food
	"京極", // Kyogoku
	0x608,
	"R_SP109:カカリコ村(室内)", // Kakariko Village (inside)
	0xf,
	0x10,
},
{
	"T_058",
	"58 コリン看病中のレナードと会話", // Conversation with Renado while he is watching over Colin
	"京極", // Kyogoku
	0x610,
	"R_SP109:カカリコ村(室内)", // Kakariko Village (inside)
	0xf,
	0x10,
},
{
	"T_0057",
	"57 バーンズのボム屋＜買い取り＞", // Barnes bomb shop <purchase>
	"京極", // Kyogoku
	0x620,
	"R_SP109:カカリコ村(室内)", // Kakariko Village (inside)
	0xf,
	0x10,
},
{
	"T_0056",
	"56 光の世界に出ようとしてミドナに止められた", // Stopped by Midna when trying to enter the world of light
	"京極", // Kyogoku
	0x640,
	"F_SP108:フィローネの森", // Faron Woods
	0x7,
	0x8,
},
{
	"T_0055",
	"55 汎用一時フラグ（フロー制御用） J", // General use temporary flag (flow control) J
	"京極", // Kyogoku
	0x680,
	"汎用", // General use
	0x14,
	0x16,
},
{
	"T_0054",
	"54 汎用一時フラグ（フロー制御用） I", // General use temporary flag (flow control) I
	"京極", // Kyogoku
	0x501,
	"汎用", // General use
	0x14,
	0x16,
},
{
	"T_0053",
	"53 汎用一時フラグ（フロー制御用） H", // General use temporary flag (flow control) H
	"京極", // Kyogoku
	0x502,
	"汎用", // General use
	0x14,
	0x16,
},
{
	"T_0052",
	"52 汎用一時フラグ（フロー制御用） G", // General use temporary flag (flow control) G
	"京極", // Kyogoku
	0x504,
	"汎用", // General use
	0x14,
	0x16,
},
{
	"T_0051",
	"51 汎用一時フラグ（フロー制御用） F", // General use temporary flag (flow control) F
	"京極", // Kyogoku
	0x508,
	"汎用", // General use
	0x14,
	0x16,
},
{
	"T_0050",
	"50 温泉ゴロンDと店主ゴロンの雑談聞いた(試合前)", // Heard spring goron D and shopkeeper goron's conversation (before match)
	"京極", // Kyogoku
	0x510,
	"F_SP110デスマウンテン", // Death Mountain
	0x9,
	0xa,
},
{
	"T_0049",
	"49 巨人ゲーム中", // During giant game
	"京極", // Kyogoku
	0x520,
	"F_SP117:聖なる森", // Sacred Grove
	0xe,
	0xf,
},
{
	"T_0048",
	"48 ボウとの相撲 - リンク負けた", // Wrestling with Bo - Link loses
	"京極", // Kyogoku
	0x540,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0047",
	"47 ボウとの相撲直後（服着た後の会話接続用）", // Right after wrestling with Bo (Used to connect with conversation after wearing clothes)
	"京極", // Kyogoku
	0x580,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0046",
	"46 ボウとの相撲 - リンクの勝利", // Wrestling with Bo - Link wins
	"京極", // Kyogoku
	0x401,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0045",
	"45 トワイライト/ゴロンCの話聞いた", // Twilight - Talked with Goron C
	"京極", // Kyogoku
	0x402,
	"F_SP110デスマウンテン", // Death Mountain
	0x9,
	0xa,
},
{
	"T_0044",
	"44 剣チュー終了デモ用", // For sword tutorial end cutscene
	"京極", // Kyogoku
	0x404,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0043",
	"43 @",
	"京極", // Kyogoku
	0x408,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"T_0042",
	"42 キコルに夜にカンテラ持たずに話しかけた", // Spoke to Coro at night without lantern
	"京極", // Kyogoku
	0x410,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"T_0041",
	"41 キコルが寝てる時だけONになっている", // Only ON when Coro is sleeping
	"京極", // Kyogoku
	0x420,
	"F_SP108:フィローネの森", // Faron Woods
	0x7,
	0x8,
},
{
	"TEMP_0040",
	"40 @",
	"京極", // Kyogoku
	0x440,
	"*未使用", //unused 
	0x0,
	0x1,
},
{
	"TEMP_0038",
	"39 ハンジョー、鷹匠デモ用一時フラグ", // temporary flag for Hanch the Hawder cutscene
	"京極", // Kyogoku
	0x480,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0036",
	"38 モイの剣失敗カウント_3", // Rusl sword failure count 3
	"京極", // Kyogoku
	0x301,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0035",
	"37 モイの剣失敗カウント_2", // Rusl sword failure count 2
	"京極", // Kyogoku
	0x302,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0034",
	"36 モイの剣失敗カウント_1", // Rusl sword failure count 1
	"京極", // Kyogoku
	0x304,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0033",
	"35 暴走山羊ゲーム中、Aと[3D]↑を押した", // Press A and [3D] ↑ during rampaging goat game, 
	"京極", // Kyogoku
	0x308,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0032",
	"33 モイの剣を返す", // Return Rusl's sword
	"京極", // Kyogoku
	0x310,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0031",
	"32 モイの剣を借りる", // Borrow Rusl's sword
	"京極", // Kyogoku
	0x320,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0030",
	"31 モイ、Ｄｏボタン「とる」", // Rusl, Ｄｏ button "take"
	"住吉", // Sumiyoshi
	0x340,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0029",
	"30 モイの剣パクり成功", // Succeed at taking Rusl's sword
	"京極", // Kyogoku
	0x380,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0028",
	"29 山羊暴走後、間もない", // Right after rampaging goats
	"京極", // Kyogoku
	0x201,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0027",
	"28 山羊暴走終了", // Rampaging goats complete
	"京極", // Kyogoku
	0x202,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0026",
	"27 ジャガーの近くでカボチャを割った（ジャガーに怒られる）", // Destroy pumpkin near Jaggle (Jaggle gets angry)
	"京極", // Kyogoku
	0x204,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0025",
	"26 テーブルの上に乗った（キュリーに怒られる）", // Get on table (Pergie gets mad)
	"京極", // Kyogoku
	0x208,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0024",
	"25 剣チュ−トリアルへ", // To sword tutorial
	"住吉", // Sumiyoshi
	0x210,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0023",
	"24 剣チュ−トリアル直後に、タロ、コリンを呼んだ", // Called Talo, Colin right after sword game
	"住吉", // Sumiyoshi
	0x220,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0022",
	"23 ウーリ/赤ちゃんのカゴ持っている", // Uli - carrying baby basket
	"京極", // Kyogoku
	0x240,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0021",
	"22 リンクの家前でコリンがついてきている", // Colin follows to Link's house
	"京極", // Kyogoku
	0x280,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0020",
	"21 牛追い/時間切れ後〜再開の間までON", // cow herding - ON from `time's up` until `restart`
	"京極", // Kyogoku
	0x101,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0019",
	"20 牛追い/時間切れ", // cow herding - time's up
	"京極", // Kyogoku
	0x102,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0018",
	"19 牛追い/残り時間が少なくなった", // cow herding - time is almost up
	"京極", // Kyogoku
	0x104,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0017",
	"18 牛追い/最初の１匹を小屋に入れた", // cow herding - first one entered the hut
	"京極", // Kyogoku
	0x108,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0016",
	"17 剣チュ−トリアル中に、ベス、タロを一喝", // Scold Beth, Talo during sword tutorial
	"住吉", // Sumiyoshi
	0x110,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0015",
	"16 ジャガ−に呼ばれて、リンクが高台にきた", // Link came up the hill afte being called by Jaggle
	"京極", // Kyogoku
	0x120,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0014",
	"15 汎用一時フラグ（フロー制御用） E", // General use temporary flag (flow control) E
	"京極", // Kyogoku
	0x140,
	"汎用", // General use
	0x14,
	0x16,
},
{
	"T_0013",
	"14 汎用一時フラグ（フロー制御用） D", // General use temporary flag (flow control) D
	"京極", // Kyogoku
	0x180,
	"汎用", // General use
	0x14,
	0x16,
},
{
	"T_0012",
	"13 汎用一時フラグ（フロー制御用） C", // General use temporary flag (flow control) C
	"京極", // Kyogoku
	0x1,
	"汎用", // General use
	0x14,
	0x16,
},
{
	"T_0011",
	"12 汎用一時フラグ（フロー制御用） B", // General use temporary flag (flow control) B
	"京極", // Kyogoku
	0x2,
	"汎用", // General use
	0x14,
	0x16,
},
{
	"T_0010",
	"11 汎用一時フラグ（フロー制御用） A", // General use temporary flag (flow control) A
	"京極", // Kyogoku
	0x4,
	"汎用", // General use
	0x14,
	0x16,
},
{
	"T_0009",
	"10 ウーリの持ち上げチュートリアル、ある程度歩いた", // Walked a bit during Uli's pick-up tutorial
	"京極", // Kyogoku
	0x8,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0008",
	"9 弓矢ゲーム：ホークアイを使って的を射抜いた", // bow and arrow game: shoot target using Hawkeye
	"京極（住吉使用）", // Kyogoku (used by Sumiyoshi)
	0x10,
	"F_SP109:カカリコ村", // Kakariko Village
	0x8,
	0x9,
},
{
	"T_0001",
	"8 バーンズボム屋で連続買取", // Make successive purchased at Barnes bomb shop
	"京極", // Kyogoku
	0x80,
	"R_SP109:カカリコ村(室内)", // Kakariko Village (inside)
	0xf,
	0x10,
},
{
	"T_0007",
	"7 ウーリの持ち上げチュートリアル真っ最中", // During Uli's pick-up tutorial
	"京極", // Kyogoku
	0x20,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},
{
	"T_0004",
	"4 剣チュ−トリアル・成否判定", // sword tutorial - outcome
	"住吉", // Sumiyoshi
	0x40,
	"F_SP103:トアル村", // Ordon Village
	0x6,
	0x7,
},