#ifndef RES_LOGOPALSP_H
#define RES_LOGOPALSP_H

enum dRes_INDEX_LOGOPALSP {
    /* DAT  */
    dRes_INDEX_LOGOPALSP_BTI_50_60_CHOICE_SPA_e=0x3,
    dRes_INDEX_LOGOPALSP_BTI_50_SET_SPA_e=0x4,
    dRes_INDEX_LOGOPALSP_BTI_60_SET_SPA_e=0x5,
    dRes_INDEX_LOGOPALSP_BTI_PROGRESSIVE_INTER_SP_e=0x6,
    dRes_INDEX_LOGOPALSP_BTI_PROGRESSIVE_PRO_SP_e=0x7,
    dRes_INDEX_LOGOPALSP_BTI_WARNING_PSTART_SP_e=0x8,
    dRes_INDEX_LOGOPALSP_BTI_WARNING_SP_e=0x9,
};

enum dRes_ID_LOGOPALSP {
    /* DAT  */
    dRes_ID_LOGOPALSP_BTI_50_60_CHOICE_SPA_e=0x3,
    dRes_ID_LOGOPALSP_BTI_50_SET_SPA_e=0x4,
    dRes_ID_LOGOPALSP_BTI_60_SET_SPA_e=0x5,
    dRes_ID_LOGOPALSP_BTI_PROGRESSIVE_INTER_SP_e=0x6,
    dRes_ID_LOGOPALSP_BTI_PROGRESSIVE_PRO_SP_e=0x7,
    dRes_ID_LOGOPALSP_BTI_WARNING_PSTART_SP_e=0x8,
    dRes_ID_LOGOPALSP_BTI_WARNING_SP_e=0x9,
};

#endif /* !RES_LOGOPALSP_H */