#ifndef RES_LOGOPALUK_H
#define RES_LOGOPALUK_H

enum dRes_INDEX_LOGOPALUK {
    /* DAT  */
    dRes_INDEX_LOGOPALUK_BTI_50_60_CHOICE_ENG_e=0x3,
    dRes_INDEX_LOGOPALUK_BTI_50_SET_ENG_e=0x4,
    dRes_INDEX_LOGOPALUK_BTI_60_SET_ENG_e=0x5,
    dRes_INDEX_LOGOPALUK_BTI_PROGRESSIVE_INTER_e=0x6,
    dRes_INDEX_LOGOPALUK_BTI_PROGRESSIVE_PRO_e=0x7,
    dRes_INDEX_LOGOPALUK_BTI_WARNING_e=0x8,
    dRes_INDEX_LOGOPALUK_BTI_WARNING_PSTART_e=0x9,
};

enum dRes_ID_LOGOPALUK {
    /* DAT  */
    dRes_ID_LOGOPALUK_BTI_50_60_CHOICE_ENG_e=0x3,
    dRes_ID_LOGOPALUK_BTI_50_SET_ENG_e=0x4,
    dRes_ID_LOGOPALUK_BTI_60_SET_ENG_e=0x5,
    dRes_ID_LOGOPALUK_BTI_PROGRESSIVE_INTER_e=0x6,
    dRes_ID_LOGOPALUK_BTI_PROGRESSIVE_PRO_e=0x7,
    dRes_ID_LOGOPALUK_BTI_WARNING_e=0x8,
    dRes_ID_LOGOPALUK_BTI_WARNING_PSTART_e=0x9,
};

#endif /* !RES_LOGOPALUK_H */