#ifndef RES_BDOORTANM_H
#define RES_BDOORTANM_H

enum dRes_INDEX_BDOORTANM {
    /* BCK  */
    dRes_INDEX_BDOORTANM_BCK_MD_OJ_DOOROPF_e=0x3,
    dRes_INDEX_BDOORTANM_BCK_OJ_DOORCLOSEF_e=0x4,
    dRes_INDEX_BDOORTANM_BCK_OJ_DOOROPF_e=0x5,
};

enum dRes_ID_BDOORTANM {
    /* BCK  */
    dRes_ID_BDOORTANM_BCK_MD_OJ_DOOROPF_e=0x3,
    dRes_ID_BDOORTANM_BCK_OJ_DOORCLOSEF_e=0x4,
    dRes_ID_BDOORTANM_BCK_OJ_DOOROPF_e=0x5,
};

#endif /* !RES_BDOORTANM_H */