#ifndef RES_KOLIN_P1_H
#define RES_KOLIN_P1_H

enum dRes_INDEX_KOLIN_P1 {
    /* BCK  */
    dRes_INDEX_KOLIN_P1_BCK_KOLIN_F_HAPPY_TALK_e=0x3,
    dRes_INDEX_KOLIN_P1_BCK_KOLIN_FH_NORMAL_TALK_e=0x4,
    dRes_INDEX_KOLIN_P1_BCK_KOLIN_NORMAL_TALK_e=0x5,
};

enum dRes_ID_KOLIN_P1 {
    /* BCK  */
    dRes_ID_KOLIN_P1_BCK_KOLIN_F_HAPPY_TALK_e=0x3,
    dRes_ID_KOLIN_P1_BCK_KOLIN_FH_NORMAL_TALK_e=0x4,
    dRes_ID_KOLIN_P1_BCK_KOLIN_NORMAL_TALK_e=0x5,
};

#endif /* !RES_KOLIN_P1_H */