#ifndef RES_OBJ_OBRG_H
#define RES_OBJ_OBRG_H

enum dRes_INDEX_OBJ_OBRG {
    /* BCK  */
    dRes_INDEX_OBJ_OBRG_BCK_NI_BAJYOHASIPARTS_e=0x7,
    dRes_INDEX_OBJ_OBRG_BCK_NI_BAJYOHASIPARTS_EF_e=0x8,
    /* BMDR */
    dRes_INDEX_OBJ_OBRG_BMD_NI_BAJYOHASIPARTS_e=0xB,
    dRes_INDEX_OBJ_OBRG_BMD_NI_BAJYOHASIPARTS_EF_e=0xC,
    /* BTK  */
    dRes_INDEX_OBJ_OBRG_BTK_NI_BAJYOHASIPARTS_e=0xF,
    dRes_INDEX_OBJ_OBRG_BTK_NI_BAJYOHASIPARTS_EF_e=0x10,
    /* DZB  */
    dRes_INDEX_OBJ_OBRG_DZB_I_BAJYOHASIPARTS_e=0x13,
    dRes_INDEX_OBJ_OBRG_DZB_I_BAJYOHASIPARTS_EF_e=0x14,
    /* EVT  */
    dRes_INDEX_OBJ_OBRG_DAT_EVENT_LIST_e=0x17,
};

enum dRes_ID_OBJ_OBRG {
    /* BCK  */
    dRes_ID_OBJ_OBRG_BCK_NI_BAJYOHASIPARTS_e=0x7,
    dRes_ID_OBJ_OBRG_BCK_NI_BAJYOHASIPARTS_EF_e=0x8,
    /* BMDR */
    dRes_ID_OBJ_OBRG_BMD_NI_BAJYOHASIPARTS_e=0xB,
    dRes_ID_OBJ_OBRG_BMD_NI_BAJYOHASIPARTS_EF_e=0xC,
    /* BTK  */
    dRes_ID_OBJ_OBRG_BTK_NI_BAJYOHASIPARTS_e=0xF,
    dRes_ID_OBJ_OBRG_BTK_NI_BAJYOHASIPARTS_EF_e=0x10,
    /* DZB  */
    dRes_ID_OBJ_OBRG_DZB_I_BAJYOHASIPARTS_e=0x13,
    dRes_ID_OBJ_OBRG_DZB_I_BAJYOHASIPARTS_EF_e=0x14,
    /* EVT  */
    dRes_ID_OBJ_OBRG_DAT_EVENT_LIST_e=0x17,
};

enum NI_BAJYOHASIPARTS_JNT {
    NI_BAJYOHASIPARTS_JNT_A00_e=0x0,
};

enum NI_BAJYOHASIPARTS_EF_JNT {
    NI_BAJYOHASIPARTS_EF_JNT_BAJYOHASIPARTS_EF_e=0x0,
    NI_BAJYOHASIPARTS_EF_JNT_EFFECT_P_e=0x1,
};

#endif /* !RES_OBJ_OBRG_H */