#ifndef RES_OBJ_LV6BM_H
#define RES_OBJ_LV6BM_H

enum dRes_INDEX_OBJ_LV6BM {
    /* BCK  */
    dRes_INDEX_OBJ_LV6BM_BCK_EF_BIMOBEAM_e=0x7,
    /* BMDE */
    dRes_INDEX_OBJ_LV6BM_BMD_BM6_e=0xA,
    /* BMDR */
    dRes_INDEX_OBJ_LV6BM_BMD_EF_BIMOBEAM_e=0xD,
    dRes_INDEX_OBJ_LV6BM_BMD_K_BIMO00_e=0xE,
    /* BTK  */
    dRes_INDEX_OBJ_LV6BM_BTK_EF_BIMOBEAM_e=0x11,
    dRes_INDEX_OBJ_LV6BM_BTK_EF_BIMOBEAM_OFF_e=0x12,
    dRes_INDEX_OBJ_LV6BM_BTK_EF_BIMOBEAM_ON_e=0x13,
    /* DZB  */
    dRes_INDEX_OBJ_LV6BM_DZB_K_BIMO00_e=0x16,
    dRes_INDEX_OBJ_LV6BM_DZB_LV6_OBJ_BEMOS_e=0x17,
};

enum dRes_ID_OBJ_LV6BM {
    /* BCK  */
    dRes_ID_OBJ_LV6BM_BCK_EF_BIMOBEAM_e=0x7,
    /* BMDE */
    dRes_ID_OBJ_LV6BM_BMD_BM6_e=0xA,
    /* BMDR */
    dRes_ID_OBJ_LV6BM_BMD_EF_BIMOBEAM_e=0xD,
    dRes_ID_OBJ_LV6BM_BMD_K_BIMO00_e=0xE,
    /* BTK  */
    dRes_ID_OBJ_LV6BM_BTK_EF_BIMOBEAM_e=0x11,
    dRes_ID_OBJ_LV6BM_BTK_EF_BIMOBEAM_OFF_e=0x12,
    dRes_ID_OBJ_LV6BM_BTK_EF_BIMOBEAM_ON_e=0x13,
    /* DZB  */
    dRes_ID_OBJ_LV6BM_DZB_K_BIMO00_e=0x16,
    dRes_ID_OBJ_LV6BM_DZB_LV6_OBJ_BEMOS_e=0x17,
};

enum BM6_JNT {
    BM6_JNT_CENTER_e=0x0,
    BM6_JNT_COGRED_e=0x1,
    BM6_JNT_HEAD_e=0x2,
    BM6_JNT_COGBLUE_e=0x3,
    BM6_JNT_COGGREEN_e=0x4,
    BM6_JNT_COGYELLOW_e=0x5,
};

enum EF_BIMOBEAM_JNT {
    EF_BIMOBEAM_JNT_WORLD_ROOT_e=0x0,
    EF_BIMOBEAM_JNT__01CROSS_e=0x1,
    EF_BIMOBEAM_JNT__02TWISTEDPLANE_A_e=0x2,
    EF_BIMOBEAM_JNT__03TWISTEDCYLINDER_e=0x3,
};

enum K_BIMO00_JNT {
    K_BIMO00_JNT_JOINT7_e=0x0,
    K_BIMO00_JNT_JOINT8_e=0x1,
    K_BIMO00_JNT_JOINT10_e=0x2,
};

#endif /* !RES_OBJ_LV6BM_H */