#ifndef RES_LOGODUWII_H
#define RES_LOGODUWII_H

enum dRes_INDEX_LOGODUWII {
    /* DAT  */
    dRes_INDEX_LOGODUWII_BTI_STRAP_16_9_832X456_DUTCH_e=0x3,
    dRes_INDEX_LOGODUWII_BTI_STRAP_608X456_DUTCH_e=0x4,
};

enum dRes_ID_LOGODUWII {
    /* DAT  */
    dRes_ID_LOGODUWII_BTI_STRAP_16_9_832X456_DUTCH_e=0x3,
    dRes_ID_LOGODUWII_BTI_STRAP_608X456_DUTCH_e=0x4,
};

#endif /* !RES_LOGODUWII_H */