#ifndef RES_GRZ1_H
#define RES_GRZ1_H

enum dRes_INDEX_GRZ1 {
    /* BCK  */
    dRes_INDEX_GRZ1_BCK_GRZ_F_GETUP_e=0x5,
    dRes_INDEX_GRZ1_BCK_GRZ_F_LIEDOWN_e=0x6,
    dRes_INDEX_GRZ1_BCK_GRZ_F_WEAK_TALK_e=0x7,
    dRes_INDEX_GRZ1_BCK_GRZ_F_WEAK_TURN_e=0x8,
    dRes_INDEX_GRZ1_BCK_GRZ_F_WEAK_WAIT_e=0x9,
    dRes_INDEX_GRZ1_BCK_GRZ_GETUP_e=0xA,
    dRes_INDEX_GRZ1_BCK_GRZ_LIEDOWN_e=0xB,
    dRes_INDEX_GRZ1_BCK_GRZ_WEAK_STEP_e=0xC,
    dRes_INDEX_GRZ1_BCK_GRZ_WEAK_TURN_e=0xD,
    dRes_INDEX_GRZ1_BCK_GRZ_WEAK_WAIT_e=0xE,
    /* BTK  */
    dRes_INDEX_GRZ1_BTK_GRZ_GETUP_e=0x11,
    /* BTP  */
    dRes_INDEX_GRZ1_BTP_GRZ_F_GETUP_e=0x14,
    dRes_INDEX_GRZ1_BTP_GRZ_F_LIEDOWN_e=0x15,
    dRes_INDEX_GRZ1_BTP_GRZ_F_WEAK_TALK_e=0x16,
    dRes_INDEX_GRZ1_BTP_GRZ_F_WEAK_TURN_e=0x17,
    dRes_INDEX_GRZ1_BTP_GRZ_F_WEAK_WAIT_e=0x18,
};

enum dRes_ID_GRZ1 {
    /* BCK  */
    dRes_ID_GRZ1_BCK_GRZ_F_GETUP_e=0x5,
    dRes_ID_GRZ1_BCK_GRZ_F_LIEDOWN_e=0x6,
    dRes_ID_GRZ1_BCK_GRZ_F_WEAK_TALK_e=0x7,
    dRes_ID_GRZ1_BCK_GRZ_F_WEAK_TURN_e=0x8,
    dRes_ID_GRZ1_BCK_GRZ_F_WEAK_WAIT_e=0x9,
    dRes_ID_GRZ1_BCK_GRZ_GETUP_e=0xA,
    dRes_ID_GRZ1_BCK_GRZ_LIEDOWN_e=0xB,
    dRes_ID_GRZ1_BCK_GRZ_WEAK_STEP_e=0xC,
    dRes_ID_GRZ1_BCK_GRZ_WEAK_TURN_e=0xD,
    dRes_ID_GRZ1_BCK_GRZ_WEAK_WAIT_e=0xE,
    /* BTK  */
    dRes_ID_GRZ1_BTK_GRZ_GETUP_e=0x11,
    /* BTP  */
    dRes_ID_GRZ1_BTP_GRZ_F_GETUP_e=0x14,
    dRes_ID_GRZ1_BTP_GRZ_F_LIEDOWN_e=0x15,
    dRes_ID_GRZ1_BTP_GRZ_F_WEAK_TALK_e=0x16,
    dRes_ID_GRZ1_BTP_GRZ_F_WEAK_TURN_e=0x17,
    dRes_ID_GRZ1_BTP_GRZ_F_WEAK_WAIT_e=0x18,
};

#endif /* !RES_GRZ1_H */