#ifndef RES_MOI2_H
#define RES_MOI2_H

enum dRes_INDEX_MOI2 {
    /* BCK  */
    dRes_INDEX_MOI2_BCK_MOI_F_INJURY_LAYDOWN_e=0x6,
    dRes_INDEX_MOI2_BCK_MOI_F_INJURY_TALK_A_e=0x7,
    dRes_INDEX_MOI2_BCK_MOI_F_S_TALK_A_e=0x8,
    dRes_INDEX_MOI2_BCK_MOI_FH_CLOSEEYE_e=0x9,
    dRes_INDEX_MOI2_BCK_MOI_FH_INJURY_TALK_A_e=0xA,
    dRes_INDEX_MOI2_BCK_MOI_FH_S_TALK_A_e=0xB,
    dRes_INDEX_MOI2_BCK_MOI_INJURY_CHECK_L_e=0xC,
    dRes_INDEX_MOI2_BCK_MOI_INJURY_CHECK_R_e=0xD,
    dRes_INDEX_MOI2_BCK_MOI_INJURY_FALL_e=0xE,
    dRes_INDEX_MOI2_BCK_MOI_INJURY_LAYDOWN_e=0xF,
    dRes_INDEX_MOI2_BCK_MOI_INJURY_LAYING_e=0x10,
    dRes_INDEX_MOI2_BCK_MOI_INJURY_TALK_A_e=0x11,
    dRes_INDEX_MOI2_BCK_MOI_INJURY_TALK_B_e=0x12,
    dRes_INDEX_MOI2_BCK_MOI_INJURY_TALK_C_e=0x13,
    dRes_INDEX_MOI2_BCK_MOI_INJURY_WAIT_e=0x14,
    dRes_INDEX_MOI2_BCK_MOI_INJURY_WALK_e=0x15,
    dRes_INDEX_MOI2_BCK_MOI_S_FIGHT_A_e=0x16,
    dRes_INDEX_MOI2_BCK_MOI_S_PULLOUT_e=0x17,
    dRes_INDEX_MOI2_BCK_MOI_S_SETIN_e=0x18,
    dRes_INDEX_MOI2_BCK_MOI_S_TALK_A_e=0x19,
    dRes_INDEX_MOI2_BCK_MOI_S_WAIT_e=0x1A,
    /* BMDR */
    dRes_INDEX_MOI2_BMD_MOI_HOUTAI_A_e=0x1D,
    dRes_INDEX_MOI2_BMD_MOI_HOUTAI_B_e=0x1E,
    dRes_INDEX_MOI2_BMD_MOI_HOUTAI_C_e=0x1F,
    dRes_INDEX_MOI2_BMD_MOIN_e=0x20,
    dRes_INDEX_MOI2_BMD_TORCH_e=0x21,
    /* BTK  */
    dRes_INDEX_MOI2_BTK_MOIN_e=0x24,
    /* BTP  */
    dRes_INDEX_MOI2_BTP_MOI_F_INJURY_LAYDOWN_e=0x27,
    dRes_INDEX_MOI2_BTP_MOI_F_INJURY_TALK_A_e=0x28,
    dRes_INDEX_MOI2_BTP_MOI_F_S_TALK_A_e=0x29,
    dRes_INDEX_MOI2_BTP_MOI_FH_CLOSEEYE_e=0x2A,
    dRes_INDEX_MOI2_BTP_MOI_FH_INJURY_TALK_A_e=0x2B,
    dRes_INDEX_MOI2_BTP_MOI_FH_S_TALK_A_e=0x2C,
    dRes_INDEX_MOI2_BTP_MOIN_e=0x2D,
};

enum dRes_ID_MOI2 {
    /* BCK  */
    dRes_ID_MOI2_BCK_MOI_F_INJURY_LAYDOWN_e=0x6,
    dRes_ID_MOI2_BCK_MOI_F_INJURY_TALK_A_e=0x7,
    dRes_ID_MOI2_BCK_MOI_F_S_TALK_A_e=0x8,
    dRes_ID_MOI2_BCK_MOI_FH_CLOSEEYE_e=0x9,
    dRes_ID_MOI2_BCK_MOI_FH_INJURY_TALK_A_e=0xA,
    dRes_ID_MOI2_BCK_MOI_FH_S_TALK_A_e=0xB,
    dRes_ID_MOI2_BCK_MOI_INJURY_CHECK_L_e=0xC,
    dRes_ID_MOI2_BCK_MOI_INJURY_CHECK_R_e=0xD,
    dRes_ID_MOI2_BCK_MOI_INJURY_FALL_e=0xE,
    dRes_ID_MOI2_BCK_MOI_INJURY_LAYDOWN_e=0xF,
    dRes_ID_MOI2_BCK_MOI_INJURY_LAYING_e=0x10,
    dRes_ID_MOI2_BCK_MOI_INJURY_TALK_A_e=0x11,
    dRes_ID_MOI2_BCK_MOI_INJURY_TALK_B_e=0x12,
    dRes_ID_MOI2_BCK_MOI_INJURY_TALK_C_e=0x13,
    dRes_ID_MOI2_BCK_MOI_INJURY_WAIT_e=0x14,
    dRes_ID_MOI2_BCK_MOI_INJURY_WALK_e=0x15,
    dRes_ID_MOI2_BCK_MOI_S_FIGHT_A_e=0x16,
    dRes_ID_MOI2_BCK_MOI_S_PULLOUT_e=0x17,
    dRes_ID_MOI2_BCK_MOI_S_SETIN_e=0x18,
    dRes_ID_MOI2_BCK_MOI_S_TALK_A_e=0x19,
    dRes_ID_MOI2_BCK_MOI_S_WAIT_e=0x1A,
    /* BMDR */
    dRes_ID_MOI2_BMD_MOI_HOUTAI_A_e=0x1D,
    dRes_ID_MOI2_BMD_MOI_HOUTAI_B_e=0x1E,
    dRes_ID_MOI2_BMD_MOI_HOUTAI_C_e=0x1F,
    dRes_ID_MOI2_BMD_MOIN_e=0x20,
    dRes_ID_MOI2_BMD_TORCH_e=0x21,
    /* BTK  */
    dRes_ID_MOI2_BTK_MOIN_e=0x24,
    /* BTP  */
    dRes_ID_MOI2_BTP_MOI_F_INJURY_LAYDOWN_e=0x27,
    dRes_ID_MOI2_BTP_MOI_F_INJURY_TALK_A_e=0x28,
    dRes_ID_MOI2_BTP_MOI_F_S_TALK_A_e=0x29,
    dRes_ID_MOI2_BTP_MOI_FH_CLOSEEYE_e=0x2A,
    dRes_ID_MOI2_BTP_MOI_FH_INJURY_TALK_A_e=0x2B,
    dRes_ID_MOI2_BTP_MOI_FH_S_TALK_A_e=0x2C,
    dRes_ID_MOI2_BTP_MOIN_e=0x2D,
};

enum MOI_HOUTAI_A_JNT {
    MOI_HOUTAI_A_JNT_MOI_HOUTAIA_e=0x0,
};

enum MOI_HOUTAI_B_JNT {
    MOI_HOUTAI_B_JNT_MOI_HOUTAIB_e=0x0,
};

enum MOI_HOUTAI_C_JNT {
    MOI_HOUTAI_C_JNT_MOI_HOUTAIC_e=0x0,
};

enum MOIN_JNT {
    MOIN_JNT_CENTER_e=0x0,
    MOIN_JNT_BACKBONE1_e=0x1,
    MOIN_JNT_BACKBONE2_e=0x2,
    MOIN_JNT_NECK_e=0x3,
    MOIN_JNT_HEAD_e=0x4,
    MOIN_JNT_CHIN_e=0x5,
    MOIN_JNT_MAYU_L_e=0x6,
    MOIN_JNT_MAYU_R_e=0x7,
    MOIN_JNT_MOUTH_e=0x8,
    MOIN_JNT_SHOULDERL_e=0x9,
    MOIN_JNT_ARML1_e=0xA,
    MOIN_JNT_ARML2_e=0xB,
    MOIN_JNT_HANDL_e=0xC,
    MOIN_JNT_FINGERL_e=0xD,
    MOIN_JNT_SHOULDERR_e=0xE,
    MOIN_JNT_ARMR1_e=0xF,
    MOIN_JNT_ARMR2_e=0x10,
    MOIN_JNT_HANDR_e=0x11,
    MOIN_JNT_FINGERR_e=0x12,
    MOIN_JNT_WAIST_e=0x13,
    MOIN_JNT_LEGL1_e=0x14,
    MOIN_JNT_LEGL2_e=0x15,
    MOIN_JNT_FOOTL_e=0x16,
    MOIN_JNT_LEGR1_e=0x17,
    MOIN_JNT_LEGR2_e=0x18,
    MOIN_JNT_FOOTR_e=0x19,
};

enum TORCH_JNT {
    TORCH_JNT_TORCH_MODEL_e=0x0,
};

#endif /* !RES_MOI2_H */