#ifndef RES_SEKI_1K_H
#define RES_SEKI_1K_H

enum dRes_INDEX_SEKI_1K {
    /* BMDR */
    dRes_INDEX_SEKI_1K_BMD_SEKIZOA_1K_e=0x3,
    dRes_INDEX_SEKI_1K_BMD_YARIA_1K_e=0x4,
    dRes_INDEX_SEKI_1K_BMD_YARIB_1K_e=0x5,
};

enum dRes_ID_SEKI_1K {
    /* BMDR */
    dRes_ID_SEKI_1K_BMD_SEKIZOA_1K_e=0x3,
    dRes_ID_SEKI_1K_BMD_YARIA_1K_e=0x4,
    dRes_ID_SEKI_1K_BMD_YARIB_1K_e=0x5,
};

enum SEKIZOA_1K_JNT {
    SEKIZOA_1K_JNT_CENTER_e=0x0,
    SEKIZOA_1K_JNT_BACKBONE1_e=0x1,
    SEKIZOA_1K_JNT_BACKBONE2_e=0x2,
    SEKIZOA_1K_JNT_HEAD_e=0x3,
    SEKIZOA_1K_JNT_SHOULDERL_e=0x4,
    SEKIZOA_1K_JNT_ARML1_e=0x5,
    SEKIZOA_1K_JNT_ARML2_e=0x6,
    SEKIZOA_1K_JNT_HANDL_e=0x7,
    SEKIZOA_1K_JNT_FINGERL_e=0x8,
    SEKIZOA_1K_JNT_THUMBL_e=0x9,
    SEKIZOA_1K_JNT_SHOULDERR_e=0xA,
    SEKIZOA_1K_JNT_ARMR1_e=0xB,
    SEKIZOA_1K_JNT_ARMR2_e=0xC,
    SEKIZOA_1K_JNT_HANDR_e=0xD,
    SEKIZOA_1K_JNT_FINGERR_e=0xE,
    SEKIZOA_1K_JNT_THUMBR_e=0xF,
    SEKIZOA_1K_JNT_WAIST_e=0x10,
    SEKIZOA_1K_JNT_LEGL1_e=0x11,
    SEKIZOA_1K_JNT_LEGL2_e=0x12,
    SEKIZOA_1K_JNT_LEGR1_e=0x13,
    SEKIZOA_1K_JNT_LEGR2_e=0x14,
};

enum YARIA_1K_JNT {
    YARIA_1K_JNT_YARI_e=0x0,
    YARIA_1K_JNT_YARI_BOTTOM_e=0x1,
    YARIA_1K_JNT_YARI_TOP_e=0x2,
};

enum YARIB_1K_JNT {
    YARIB_1K_JNT_YARI_e=0x0,
    YARIB_1K_JNT_YARI_BOTTOM_e=0x1,
    YARIB_1K_JNT_YARI_TOP_e=0x2,
};

#endif /* !RES_SEKI_1K_H */