#ifndef RES_TARO5_H
#define RES_TARO5_H

enum dRes_INDEX_TARO5 {
    /* BCK  */
    dRes_INDEX_TARO5_BCK_TARO_CRY_e=0x6,
    dRes_INDEX_TARO5_BCK_TARO_F_CRY_e=0x7,
    dRes_INDEX_TARO5_BCK_TAROB_F_MISERABLE_e=0x8,
    dRes_INDEX_TARO5_BCK_TAROB_F_SAVED_e=0x9,
    dRes_INDEX_TARO5_BCK_TAROB_F_SCARED_e=0xA,
    dRes_INDEX_TARO5_BCK_TAROB_FH_MISERABLE_e=0xB,
    dRes_INDEX_TARO5_BCK_TAROB_FH_SCARED_e=0xC,
    dRes_INDEX_TARO5_BCK_TAROB_SAD_TALK_A_e=0xD,
    dRes_INDEX_TARO5_BCK_TAROB_SAD_UTUMUKI_e=0xE,
    dRes_INDEX_TARO5_BCK_TAROB_SAD_WAIT_e=0xF,
    dRes_INDEX_TARO5_BCK_TAROB_SAD_WALK_e=0x10,
    dRes_INDEX_TARO5_BCK_TAROB_SAVED_e=0x11,
    dRes_INDEX_TARO5_BCK_TAROB_SAVED_WAIT_e=0x12,
    dRes_INDEX_TARO5_BCK_TAROB_SCARED_e=0x13,
    /* BTK  */
    dRes_INDEX_TARO5_BTK_TARO_CRY_e=0x16,
    /* BTP  */
    dRes_INDEX_TARO5_BTP_TARO_F_CRY_e=0x19,
    dRes_INDEX_TARO5_BTP_TAROB_F_MISERABLE_e=0x1A,
    dRes_INDEX_TARO5_BTP_TAROB_F_SAVED_e=0x1B,
    dRes_INDEX_TARO5_BTP_TAROB_F_SCARED_e=0x1C,
    dRes_INDEX_TARO5_BTP_TAROB_FH_MISERABLE_e=0x1D,
    dRes_INDEX_TARO5_BTP_TAROB_FH_SCARED_e=0x1E,
    /* EVT  */
    dRes_INDEX_TARO5_DAT_EVENT_LIST_e=0x21,
};

enum dRes_ID_TARO5 {
    /* BCK  */
    dRes_ID_TARO5_BCK_TARO_CRY_e=0x6,
    dRes_ID_TARO5_BCK_TARO_F_CRY_e=0x7,
    dRes_ID_TARO5_BCK_TAROB_F_MISERABLE_e=0x8,
    dRes_ID_TARO5_BCK_TAROB_F_SAVED_e=0x9,
    dRes_ID_TARO5_BCK_TAROB_F_SCARED_e=0xA,
    dRes_ID_TARO5_BCK_TAROB_FH_MISERABLE_e=0xB,
    dRes_ID_TARO5_BCK_TAROB_FH_SCARED_e=0xC,
    dRes_ID_TARO5_BCK_TAROB_SAD_TALK_A_e=0xD,
    dRes_ID_TARO5_BCK_TAROB_SAD_UTUMUKI_e=0xE,
    dRes_ID_TARO5_BCK_TAROB_SAD_WAIT_e=0xF,
    dRes_ID_TARO5_BCK_TAROB_SAD_WALK_e=0x10,
    dRes_ID_TARO5_BCK_TAROB_SAVED_e=0x11,
    dRes_ID_TARO5_BCK_TAROB_SAVED_WAIT_e=0x12,
    dRes_ID_TARO5_BCK_TAROB_SCARED_e=0x13,
    /* BTK  */
    dRes_ID_TARO5_BTK_TARO_CRY_e=0x16,
    /* BTP  */
    dRes_ID_TARO5_BTP_TARO_F_CRY_e=0x19,
    dRes_ID_TARO5_BTP_TAROB_F_MISERABLE_e=0x1A,
    dRes_ID_TARO5_BTP_TAROB_F_SAVED_e=0x1B,
    dRes_ID_TARO5_BTP_TAROB_F_SCARED_e=0x1C,
    dRes_ID_TARO5_BTP_TAROB_FH_MISERABLE_e=0x1D,
    dRes_ID_TARO5_BTP_TAROB_FH_SCARED_e=0x1E,
    /* EVT  */
    dRes_ID_TARO5_DAT_EVENT_LIST_e=0x21,
};

#endif /* !RES_TARO5_H */