#ifndef RES_URI2_H
#define RES_URI2_H

enum dRes_INDEX_URI2 {
    /* BCK  */
    dRes_INDEX_URI2_BCK_URI_F_FEAR_e=0x6,
    dRes_INDEX_URI2_BCK_URI_F_SURPRISE_e=0x7,
    dRes_INDEX_URI2_BCK_URI_F_TALK_FEAR_B_e=0x8,
    dRes_INDEX_URI2_BCK_URI_FEAR_e=0x9,
    dRes_INDEX_URI2_BCK_URI_FH_FEAR_e=0xA,
    dRes_INDEX_URI2_BCK_URI_FH_SURPRISE_e=0xB,
    dRes_INDEX_URI2_BCK_URI_SURPRISE_e=0xC,
    dRes_INDEX_URI2_BCK_URI_SURPRISE_WAIT_e=0xD,
    dRes_INDEX_URI2_BCK_URI_TALK_FEAR_e=0xE,
    dRes_INDEX_URI2_BCK_URI_TALK_FEAR_B_e=0xF,
    /* BTK  */
    dRes_INDEX_URI2_BTK_URI_FEAR_e=0x12,
    /* BTP  */
    dRes_INDEX_URI2_BTP_URI_F_FEAR_e=0x15,
    dRes_INDEX_URI2_BTP_URI_F_SURPRISE_e=0x16,
    dRes_INDEX_URI2_BTP_URI_F_TALK_FEAR_B_e=0x17,
    /* EVT  */
    dRes_INDEX_URI2_DAT_EVENT_LIST_e=0x1A,
};

enum dRes_ID_URI2 {
    /* BCK  */
    dRes_ID_URI2_BCK_URI_F_FEAR_e=0x6,
    dRes_ID_URI2_BCK_URI_F_SURPRISE_e=0x7,
    dRes_ID_URI2_BCK_URI_F_TALK_FEAR_B_e=0x8,
    dRes_ID_URI2_BCK_URI_FEAR_e=0x9,
    dRes_ID_URI2_BCK_URI_FH_FEAR_e=0xA,
    dRes_ID_URI2_BCK_URI_FH_SURPRISE_e=0xB,
    dRes_ID_URI2_BCK_URI_SURPRISE_e=0xC,
    dRes_ID_URI2_BCK_URI_SURPRISE_WAIT_e=0xD,
    dRes_ID_URI2_BCK_URI_TALK_FEAR_e=0xE,
    dRes_ID_URI2_BCK_URI_TALK_FEAR_B_e=0xF,
    /* BTK  */
    dRes_ID_URI2_BTK_URI_FEAR_e=0x12,
    /* BTP  */
    dRes_ID_URI2_BTP_URI_F_FEAR_e=0x15,
    dRes_ID_URI2_BTP_URI_F_SURPRISE_e=0x16,
    dRes_ID_URI2_BTP_URI_F_TALK_FEAR_B_e=0x17,
    /* EVT  */
    dRes_ID_URI2_DAT_EVENT_LIST_e=0x1A,
};

#endif /* !RES_URI2_H */