#ifndef RES_WRANUS_H
#define RES_WRANUS_H

enum dRes_INDEX_WRANUS {
    /* DAT  */
    dRes_INDEX_WRANUS_BTI_STORE_WARNING_PSTART_VER2_e=0x3,
    dRes_INDEX_WRANUS_BTI_STORE_WARNING_VER2_e=0x4,
    dRes_INDEX_WRANUS_BTI_STRAP_16_9_832X456_US_e=0x5,
    dRes_INDEX_WRANUS_BTI_ZELDA_ESRB_01_e=0x6,
};

enum dRes_ID_WRANUS {
    /* DAT  */
    dRes_ID_WRANUS_BTI_STORE_WARNING_PSTART_VER2_e=0x3,
    dRes_ID_WRANUS_BTI_STORE_WARNING_VER2_e=0x4,
    dRes_ID_WRANUS_BTI_STRAP_16_9_832X456_US_e=0x5,
    dRes_ID_WRANUS_BTI_ZELDA_ESRB_01_e=0x6,
};

#endif /* !RES_WRANUS_H */