#ifndef RES_YKM2_H
#define RES_YKM2_H

enum dRes_INDEX_YKM2 {
    /* BCK  */
    dRes_INDEX_YKM2_BCK_YKM_ASK_e=0x6,
    dRes_INDEX_YKM2_BCK_YKM_LAUGH_e=0x7,
    dRes_INDEX_YKM2_BCK_YKM_REGRET_e=0x8,
    dRes_INDEX_YKM2_BCK_YKM_REGRETWAIT_e=0x9,
    dRes_INDEX_YKM2_BCK_YKM_SB_DAMAGE_e=0xA,
    dRes_INDEX_YKM2_BCK_YKM_SB_GOAL_e=0xB,
    dRes_INDEX_YKM2_BCK_YKM_SB_GOALWAIT_e=0xC,
    dRes_INDEX_YKM2_BCK_YKM_SB_JUMP_A_e=0xD,
    dRes_INDEX_YKM2_BCK_YKM_SB_JUMP_B_e=0xE,
    dRes_INDEX_YKM2_BCK_YKM_SB_JUMP_C_e=0xF,
    dRes_INDEX_YKM2_BCK_YKM_SB_TURNL_e=0x10,
    dRes_INDEX_YKM2_BCK_YKM_SB_TURNR_e=0x11,
    dRes_INDEX_YKM2_BCK_YKM_SB_WAIT_e=0x12,
    /* BMDR */
    dRes_INDEX_YKM2_BMD_YKM_LEAF_e=0x15,
    /* BTK  */
    dRes_INDEX_YKM2_BTK_YKM_REGRET_e=0x18,
    dRes_INDEX_YKM2_BTK_YKM_REGRETWAIT_e=0x19,
    dRes_INDEX_YKM2_BTK_YKM_SB_DAMAGE_e=0x1A,
    /* EVT  */
    dRes_INDEX_YKM2_DAT_EVENT_LIST_e=0x1D,
};

enum dRes_ID_YKM2 {
    /* BCK  */
    dRes_ID_YKM2_BCK_YKM_ASK_e=0x6,
    dRes_ID_YKM2_BCK_YKM_LAUGH_e=0x7,
    dRes_ID_YKM2_BCK_YKM_REGRET_e=0x8,
    dRes_ID_YKM2_BCK_YKM_REGRETWAIT_e=0x9,
    dRes_ID_YKM2_BCK_YKM_SB_DAMAGE_e=0xA,
    dRes_ID_YKM2_BCK_YKM_SB_GOAL_e=0xB,
    dRes_ID_YKM2_BCK_YKM_SB_GOALWAIT_e=0xC,
    dRes_ID_YKM2_BCK_YKM_SB_JUMP_A_e=0xD,
    dRes_ID_YKM2_BCK_YKM_SB_JUMP_B_e=0xE,
    dRes_ID_YKM2_BCK_YKM_SB_JUMP_C_e=0xF,
    dRes_ID_YKM2_BCK_YKM_SB_TURNL_e=0x10,
    dRes_ID_YKM2_BCK_YKM_SB_TURNR_e=0x11,
    dRes_ID_YKM2_BCK_YKM_SB_WAIT_e=0x12,
    /* BMDR */
    dRes_ID_YKM2_BMD_YKM_LEAF_e=0x15,
    /* BTK  */
    dRes_ID_YKM2_BTK_YKM_REGRET_e=0x18,
    dRes_ID_YKM2_BTK_YKM_REGRETWAIT_e=0x19,
    dRes_ID_YKM2_BTK_YKM_SB_DAMAGE_e=0x1A,
    /* EVT  */
    dRes_ID_YKM2_DAT_EVENT_LIST_e=0x1D,
};

enum YKM_LEAF_JNT {
    YKM_LEAF_JNT_YKM_LEAF_e=0x0,
};

#endif /* !RES_YKM2_H */