#ifndef RES_MSGRES00R_H
#define RES_MSGRES00R_H

enum dRes_INDEX_MSGRES00R {
    /* SCRN */
    dRes_INDEX_MSGRES00R_BCK_ZELDA_WINDOW_3MENU_REVO_e=0x4,
    dRes_INDEX_MSGRES00R_BLO_ZELDA_WINDOW_3MENU_REVO_e=0x5,
    dRes_INDEX_MSGRES00R_BPK_ZELDA_WINDOW_3MENU_REVO_e=0x6,
    dRes_INDEX_MSGRES00R_BTK_ZELDA_WINDOW_3MENU_REVO_e=0x7,
    dRes_INDEX_MSGRES00R_BCK_ZELDA_WINDOW_YAJIRUSHI_e=0x8,
    dRes_INDEX_MSGRES00R_BLO_ZELDA_WINDOW_YAJIRUSHI_e=0x9,
    dRes_INDEX_MSGRES00R_BPK_ZELDA_WINDOW_YAJIRUSHI_e=0xA,
    /* TIMG */
    dRes_INDEX_MSGRES00R_BTI_AK_OCARINA_FIRE_01_e=0xD,
    dRes_INDEX_MSGRES00R_BTI_I4_GRA_e=0xE,
    dRes_INDEX_MSGRES00R_BTI_TT_BLOCK8X8_e=0xF,
    dRes_INDEX_MSGRES00R_BTI_TT_BUTTON_BASE0_CENTER_TATE_e=0x10,
    dRes_INDEX_MSGRES00R_BTI_TT_BUTTON_BASE0_SIDE_e=0x11,
    dRes_INDEX_MSGRES00R_BTI_TT_GOLD_YAJI_END2_e=0x12,
    dRes_INDEX_MSGRES00R_BTI_TT_GOLD_YAJI_NEXT_e=0x13,
    dRes_INDEX_MSGRES00R_BTI_TT_IA4YAJI_e=0x14,
    dRes_INDEX_MSGRES00R_BTI_TT_IASTARRR_e=0x15,
    dRes_INDEX_MSGRES00R_BTI_TT_KAZARI_KANI_00_e=0x16,
};

enum dRes_ID_MSGRES00R {
    /* SCRN */
    dRes_ID_MSGRES00R_BCK_ZELDA_WINDOW_3MENU_REVO_e=0x4,
    dRes_ID_MSGRES00R_BLO_ZELDA_WINDOW_3MENU_REVO_e=0x5,
    dRes_ID_MSGRES00R_BPK_ZELDA_WINDOW_3MENU_REVO_e=0x6,
    dRes_ID_MSGRES00R_BTK_ZELDA_WINDOW_3MENU_REVO_e=0x7,
    dRes_ID_MSGRES00R_BCK_ZELDA_WINDOW_YAJIRUSHI_e=0x8,
    dRes_ID_MSGRES00R_BLO_ZELDA_WINDOW_YAJIRUSHI_e=0x9,
    dRes_ID_MSGRES00R_BPK_ZELDA_WINDOW_YAJIRUSHI_e=0xA,
    /* TIMG */
    dRes_ID_MSGRES00R_BTI_AK_OCARINA_FIRE_01_e=0xD,
    dRes_ID_MSGRES00R_BTI_I4_GRA_e=0xE,
    dRes_ID_MSGRES00R_BTI_TT_BLOCK8X8_e=0xF,
    dRes_ID_MSGRES00R_BTI_TT_BUTTON_BASE0_CENTER_TATE_e=0x10,
    dRes_ID_MSGRES00R_BTI_TT_BUTTON_BASE0_SIDE_e=0x11,
    dRes_ID_MSGRES00R_BTI_TT_GOLD_YAJI_END2_e=0x12,
    dRes_ID_MSGRES00R_BTI_TT_GOLD_YAJI_NEXT_e=0x13,
    dRes_ID_MSGRES00R_BTI_TT_IA4YAJI_e=0x14,
    dRes_ID_MSGRES00R_BTI_TT_IASTARRR_e=0x15,
    dRes_ID_MSGRES00R_BTI_TT_KAZARI_KANI_00_e=0x16,
};

#endif /* !RES_MSGRES00R_H */