#ifndef RES_MSGRES01R_H
#define RES_MSGRES01R_H

enum dRes_INDEX_MSGRES01R {
    /* SCRN */
    dRes_INDEX_MSGRES01R_BLO_ZELDA_MESSAGE_WINDOW_NEW_REVO_e=0x4,
    /* TIMG */
    dRes_INDEX_MSGRES01R_BTI_MESSAGE_WINDOW_BASE_112_8I_02_e=0x7,
    dRes_INDEX_MSGRES01R_BTI_MESSAGE_WINDOW_BASE_8_01_e=0x8,
    dRes_INDEX_MSGRES01R_BTI_TT_LINE2_e=0x9,
    dRes_INDEX_MSGRES01R_BTI_TT_MESSAGE_WIN_KADO_216_01_e=0xA,
};

enum dRes_ID_MSGRES01R {
    /* SCRN */
    dRes_ID_MSGRES01R_BLO_ZELDA_MESSAGE_WINDOW_NEW_REVO_e=0x4,
    /* TIMG */
    dRes_ID_MSGRES01R_BTI_MESSAGE_WINDOW_BASE_112_8I_02_e=0x7,
    dRes_ID_MSGRES01R_BTI_MESSAGE_WINDOW_BASE_8_01_e=0x8,
    dRes_ID_MSGRES01R_BTI_TT_LINE2_e=0x9,
    dRes_ID_MSGRES01R_BTI_TT_MESSAGE_WIN_KADO_216_01_e=0xA,
};

#endif /* !RES_MSGRES01R_H */