//
// Generated By: dol2asm
// Translation Unit: d_a_tag_kago_fall
//

#include "rel/d/a/tag/d_a_tag_kago_fall/d_a_tag_kago_fall.h"

#include "d/a/d_a_player.h"
#include "d/com/d_com_inf_game.h"
#include "d/d_procname.h"
#include "d/msg/d_msg_flow.h"
#include "d/msg/d_msg_object.h"
#include "dol2asm.h"
#include "f_op/f_op_actor.h"
#include "f_op/f_op_actor_mng.h"
#include "m_Do/m_Do_graphic.h"

#define NONMATCHING 0

//
// Types:
//

class daTagKagoFall_c : public fopAc_ac_c {
public:
    /* 80D59C58 */ int create();
    /* 80D59DE0 */ int execute();
    /* 80D59E18 */ void setActionMode(u8, u8);
    /* 80D59E24 */ void actionWaitRiver();
    /* 80D5A218 */ void actionWaitFall();
    /* 80D5A67C */ int _delete();

    /* 0x568 */ dMsgFlow_c mMsgFlow;
    /* 0x5b4 */ Mtx mMtx;
    /* 0x5e4 */ cXyz mOriginalEye;
    /* 0x5f0 */ s16 field_0x5f0;
    /* 0x5f2 */ s16 field_0x5f2;
    /* 0x5f4 */ u8 field_0x5f4;
    /* 0x5f5 */ u8 mActionMode;
    /* 0x5f6 */ u8 mActionState;
    /* 0x5f7 */ u8 mExitId;
    /* 0x5f8 */ u8 mStartPoint;
    /* 0x5f9 */ u8 field_0x5f9;

};  // Size: 0x5fc

STATIC_ASSERT(sizeof(daTagKagoFall_c) == 0x5fc);

//
// Forward References:
//

extern "C" void create__15daTagKagoFall_cFv();
extern "C" void execute__15daTagKagoFall_cFv();
extern "C" void setActionMode__15daTagKagoFall_cFUcUc();
extern "C" void actionWaitRiver__15daTagKagoFall_cFv();
extern "C" void actionWaitFall__15daTagKagoFall_cFv();
extern "C" bool _delete__15daTagKagoFall_cFv();
extern "C" static void daTagKagoFall_Execute__FP15daTagKagoFall_c();
extern "C" static void daTagKagoFall_Delete__FP15daTagKagoFall_c();
extern "C" static void daTagKagoFall_Create__FP15daTagKagoFall_c();
extern "C" extern char const* const d_a_tag_kago_fall__stringBase0;
extern "C" extern void* g_profile_Tag_KagoFall[12];

//
// External References:
//

extern "C" void fadeOut__13mDoGph_gInf_cFfR8_GXColor();
extern "C" void mDoMtx_YrotM__FPA4_fs();
extern "C" void __ct__10fopAc_ac_cFv();
extern "C" void fopAcM_orderPotentialEvent__FP10fopAc_ac_cUsUsUs();
extern "C" void dStage_changeScene__FifUlScsi();
extern "C" void getLayerNo__14dComIfG_play_cFi();
extern "C" void dComIfGp_setNextStage__FPCcsScScfUliScsii();
extern "C" void LineCross__4cBgSFP11cBgS_LinChk();
extern "C" void __ct__11dBgS_LinChkFv();
extern "C" void __dt__11dBgS_LinChkFv();
extern "C" void Set__11dBgS_LinChkFPC4cXyzPC4cXyzPC10fopAc_ac_c();
extern "C" void Stop__9dCamera_cFv();
extern "C" void SetTrimSize__9dCamera_cFl();
extern "C" void Set__9dCamera_cF4cXyz4cXyz();
extern "C" void dCam_getBody__Fv();
extern "C" void Eye__9dCamera_cFv();
extern "C" void getSelectCursorPos__12dMsgObject_cFv();
extern "C" void __ct__10dMsgFlow_cFv();
extern "C" void init__10dMsgFlow_cFP10fopAc_ac_ciiPP10fopAc_ac_c();
extern "C" void doFlow__10dMsgFlow_cFP10fopAc_ac_cPP10fopAc_ac_ci();
extern "C" void seStart__7Z2SeMgrF10JAISoundIDPC3VecUlScffffUc();
extern "C" void _savegpr_27();
extern "C" void _savegpr_28();
extern "C" void _restgpr_27();
extern "C" void _restgpr_28();
extern "C" u8 now__14mDoMtx_stack_c[48];
extern "C" u8 mAudioMgrPtr__10Z2AudioMgr[4 + 4 /* padding */];

//
// Declarations:
//

/* ############################################################################################## */
/* 80D5A6EC-80D5A6F0 000000 0004+00 3/3 0/0 0/0 .rodata          @3907 */
#if TRUE  //! NONMATCHING
SECTION_RODATA static f32 const lit_3907 = 75.0f;
COMPILER_STRIP_GATE(0x80D5A6EC, &lit_3907);

/* 80D5A6F0-80D5A6F4 000004 0004+00 1/1 0/0 0/0 .rodata          @3908 */
SECTION_RODATA static f32 const lit_3908 = 150.0f;
COMPILER_STRIP_GATE(0x80D5A6F0, &lit_3908);

/* 80D5A710-80D5A714 000000 0004+00 3/3 0/0 0/0 .data            m_master_id */
SECTION_DATA static u32 m_master_id = 0xFFFFFFFF;
#else
static u32 m_master_id = 0xFFFFFFFF;
#endif

/* 80D59C58-80D59DE0 000078 0188+00 1/1 0/0 0/0 .text            create__15daTagKagoFall_cFv */
#if NONMATCHING
int daTagKagoFall_c::create() {
    fopAcM_SetupActor(this, daTagKagoFall_c);

    if (dComIfG_play_c::getLayerNo(0) == 13) {
        mExitId = 4;

        if (dComIfGp_getStartStagePoint() == 0) {
            mStartPoint = 0;
        } else {
            mStartPoint = 12;
        }
        setActionMode(0, 0);
    } else if (dComIfG_play_c::getLayerNo(0) == 14) {
        mExitId = 2;
        mStartPoint = 0;

        PSMTXTrans(mDoMtx_stack_c::get(), current.pos.x, current.pos.y, current.pos.z);
        mDoMtx_stack_c::YrotM(shape_angle.y);
        PSMTXInverse(mDoMtx_stack_c::get(), mMtx);

        mScale.x *= 75.0f;
        mScale.z *= 75.0f;
        mScale.y *= 150.0f;

        setActionMode(1, 0);
    }

    if (m_master_id == -1) {
        m_master_id = fopAcM_GetID(this);
    }

    return cPhs_COMPLEATE_e;
}
#else
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm int daTagKagoFall_c::create() {
    nofralloc
#include "asm/rel/d/a/tag/d_a_tag_kago_fall/d_a_tag_kago_fall/create__15daTagKagoFall_cFv.s"
}
#pragma pop
#endif

/* 80D59DE0-80D59E18 000200 0038+00 1/1 0/0 0/0 .text            execute__15daTagKagoFall_cFv */
int daTagKagoFall_c::execute() {
    if (mActionMode == 0) {
        actionWaitRiver();
    } else {
        actionWaitFall();
    }

    return TRUE;
}

/* 80D59E18-80D59E24 000238 000C+00 1/1 0/0 0/0 .text setActionMode__15daTagKagoFall_cFUcUc */
void daTagKagoFall_c::setActionMode(u8 mode, u8 state) {
    mActionMode = mode;
    mActionState = state;
}

/* ############################################################################################## */
/* 80D5A6F4-80D5A6F8 000008 0004+00 0/2 0/0 0/0 .rodata          @4022 */
#if !NONMATCHING
#pragma push
#pragma force_active on
SECTION_RODATA static f32 const lit_4022 = 1.0f;
COMPILER_STRIP_GATE(0x80D5A6F4, &lit_4022);
#pragma pop

/* 80D5A6F8-80D5A6FC 00000C 0004+00 0/2 0/0 0/0 .rodata          @4023 */
#pragma push
#pragma force_active on
SECTION_RODATA static f32 const lit_4023 = -1.0f;
COMPILER_STRIP_GATE(0x80D5A6F8, &lit_4023);
#pragma pop

/* 80D5A6FC-80D5A700 000010 0004+00 0/2 0/0 0/0 .rodata          @4024 */
#pragma push
#pragma force_active on
SECTION_RODATA static f32 const lit_4024 = 1.0f / 20.0f;
COMPILER_STRIP_GATE(0x80D5A6FC, &lit_4024);
#pragma pop

/* 80D5A700-80D5A704 000014 0004+00 0/2 0/0 0/0 .rodata          @4025 */
#pragma push
#pragma force_active on
SECTION_RODATA static u8 const lit_4025[4] = {
    0x00,
    0x00,
    0x00,
    0x00,
};
COMPILER_STRIP_GATE(0x80D5A700, &lit_4025);
#pragma pop

/* 80D5A708-80D5A708 00001C 0000+00 0/0 0/0 0/0 .rodata          @stringBase0 */
#pragma push
#pragma force_active on
SECTION_DEAD static char const* const stringBase_80D5A708 = "F_SP112";
#pragma pop
#endif

/* 80D59E24-80D5A218 000244 03F4+00 1/1 0/0 0/0 .text actionWaitRiver__15daTagKagoFall_cFv */
#if NONMATCHING
void daTagKagoFall_c::actionWaitRiver() {
    daPy_py_c* player = daPy_getPlayerActorClass();
    dCamera_c* camera = dCam_getBody();
    if (field_0x5f0) {
        field_0x5f0--;
    }
    if (field_0x5f4) {
        field_0x5f4--;
    }

    switch (mActionState) {
    case 0:
        if (m_master_id == fopAcM_GetID(this)) {
            if (!daPy_getPlayerActorClass()->checkCargoCarry()) {
                field_0x5f2--;

                if (field_0x5f2 == 0) {
                    mActionState = 1;
                    mActionMode = 1;
                    return;
                }
            } else {
                field_0x5f2 = 150;
            }
        }

        if (i_dComIfGp_checkPlayerStatus0(0, 0x100000) && i_dComIfGs_getLife()) {
            if (!mEvtInfo.checkCommandDemoAccrpt()) {
                fopAcM_orderPotentialEvent(this, 1, -1, 3);
                mEvtInfo.i_onCondition(2);
            } else {
                camera->Stop();
                camera->SetTrimSize(3);

                mOriginalEye = dCam_getBody()->Eye();
                mActionState = 1;
                field_0x5f0 = 30;
                player->i_onNoResetFlg0(0x10000);
                field_0x5f4 = 60;
            }
        }
        break;

    case 1:
        if (field_0x5f0 == 1) {
            player->voiceStart(0x10041);
        }
        if (field_0x5f4 == 0) {
            Z2GetAudioMgr()->seStart(0x33, NULL, 0, 0, 1.0f, 1.0f, -1.0f, -1.0f, 0);
            mDoGph_gInf_c::fadeOut(0.05f, static_cast<JUtility::TColor&>(g_blackColor));
            field_0x5f4 = 20;
            mActionState = 2;
        }

        dCam_getBody()->Set(mEyePos, mOriginalEye);
        break;

    case 2:
        if (field_0x5f4 == 0) {
            daPy_getPlayerActorClass()->i_offNoResetFlg0(0x10000);
            mActionState = 3;
            field_0x5f0 = 40;
        }
        dCam_getBody()->Set(mEyePos, mOriginalEye);
        break;

    case 3:
        if (field_0x5f0 == 0) {
            mMsgFlow.init(this, 0x7d4, 0, NULL);
            mActionState = 4;
        }
        break;

    case 4:
        daPy_getPlayerActorClass()->i_offNoResetFlg0(0x10000);

        int msg = mMsgFlow.doFlow(this, NULL, 0);
        if (msg != 0) {
            if (((dMsgObject_c*)msg)->getSelectCursorPos() != 0) {
                dStage_changeScene(mExitId, 0.0f, 0, fopAcM_GetRoomNo(this), 0, -1);
            } else {
                int room = dStage_roomControl_c::mStayNo;
                dComIfGp_setNextStage("F_SP112", mStartPoint, room, dComIfG_play_c::getLayerNo(0),
                                      0.0f, 10, 1, 0, 0, 1, 0);
            }
            mActionState = 5;
        }
        break;

    case 5:
        break;
    }
}
#else
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daTagKagoFall_c::actionWaitRiver() {
    nofralloc
#include "asm/rel/d/a/tag/d_a_tag_kago_fall/d_a_tag_kago_fall/actionWaitRiver__15daTagKagoFall_cFv.s"
}
#pragma pop
#endif

/* ############################################################################################## */
/* 80D5A704-80D5A708 000018 0004+00 0/1 0/0 0/0 .rodata          @4118 */
#pragma push
#pragma force_active on
SECTION_RODATA static f32 const lit_4118 = 3000.0f;
COMPILER_STRIP_GATE(0x80D5A704, &lit_4118);
#pragma pop

/* 80D5A218-80D5A67C 000638 0464+00 1/1 0/0 0/0 .text            actionWaitFall__15daTagKagoFall_cFv
 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daTagKagoFall_c::actionWaitFall() {
    nofralloc
#include "asm/rel/d/a/tag/d_a_tag_kago_fall/d_a_tag_kago_fall/actionWaitFall__15daTagKagoFall_cFv.s"
}
#pragma pop

/* 80D5A67C-80D5A684 000A9C 0008+00 1/1 0/0 0/0 .text            _delete__15daTagKagoFall_cFv */
int daTagKagoFall_c::_delete() {
    return TRUE;
}

/* 80D5A684-80D5A6A4 000AA4 0020+00 1/0 0/0 0/0 .text daTagKagoFall_Execute__FP15daTagKagoFall_c
 */
static int daTagKagoFall_Execute(daTagKagoFall_c* i_this) {
    return i_this->execute();
}

/* 80D5A6A4-80D5A6C4 000AC4 0020+00 1/0 0/0 0/0 .text daTagKagoFall_Delete__FP15daTagKagoFall_c */
static int daTagKagoFall_Delete(daTagKagoFall_c* i_this) {
    return i_this->_delete();
}

/* 80D5A6C4-80D5A6E4 000AE4 0020+00 1/0 0/0 0/0 .text daTagKagoFall_Create__FP15daTagKagoFall_c */
static int daTagKagoFall_Create(daTagKagoFall_c* i_this) {
    return i_this->create();
}

/* ############################################################################################## */
/* 80D5A714-80D5A734 -00001 0020+00 1/0 0/0 0/0 .data            l_daTagKagoFall_Method */
SECTION_DATA static void* l_daTagKagoFall_Method[8] = {
    (void*)daTagKagoFall_Create__FP15daTagKagoFall_c,
    (void*)daTagKagoFall_Delete__FP15daTagKagoFall_c,
    (void*)daTagKagoFall_Execute__FP15daTagKagoFall_c,
    (void*)NULL,
    (void*)NULL,
    (void*)NULL,
    (void*)NULL,
    (void*)NULL,
};

/* 80D5A734-80D5A764 -00001 0030+00 0/0 0/0 1/0 .data            g_profile_Tag_KagoFall */
SECTION_DATA extern void* g_profile_Tag_KagoFall[12] = {
    (void*)0xFFFFFFFD, (void*)0x0007FFFD,
    (void*)0x01810000, (void*)&g_fpcLf_Method,
    (void*)0x000005FC, (void*)NULL,
    (void*)NULL,       (void*)&g_fopAc_Method,
    (void*)0x022D0000, (void*)&l_daTagKagoFall_Method,
    (void*)0x00040000, (void*)0x000E0000,
};

/* 80D5A708-80D5A708 00001C 0000+00 0/0 0/0 0/0 .rodata          @stringBase0 */
