// temp file
#include "dol2asm.h"

extern "C" void nurse__12daNpc_Besu_cFPv();
extern "C" void wait__12daNpc_Besu_cFPv();

/* 8053FBB4-8053FBC0 -00001 000C+00 0/1 0/0 0/0 .data            @5517 */
#pragma push
#pragma force_active on
SECTION_DATA static void* lit_5517[3] = {
    (void*)NULL,
    (void*)0xFFFFFFFF,
    (void*)nurse__12daNpc_Besu_cFPv,
};
#pragma pop

extern "C" void giveHotWater__12daNpc_Besu_cFPv();
/* 8053FBC0-8053FBCC -00001 000C+00 0/1 0/0 0/0 .data            @5519 */
#pragma push
#pragma force_active on
SECTION_DATA static void* lit_5519[3] = {
    (void*)NULL,
    (void*)0xFFFFFFFF,
    (void*)giveHotWater__12daNpc_Besu_cFPv,
};
#pragma pop

/* 8053FBCC-8053FBD8 -00001 000C+00 0/1 0/0 0/0 .data            @5521 */
#pragma push
#pragma force_active on
SECTION_DATA static void* lit_5521[3] = {
    (void*)NULL,
    (void*)0xFFFFFFFF,
    (void*)nurse__12daNpc_Besu_cFPv,
};
#pragma pop

extern "C" void swdTutorial__12daNpc_Besu_cFPv();
/* 8053FBD8-8053FBE4 -00001 000C+00 0/1 0/0 0/0 .data            @5525 */
#pragma push
#pragma force_active on
SECTION_DATA static void* lit_5525[3] = {
    (void*)NULL,
    (void*)0xFFFFFFFF,
    (void*)swdTutorial__12daNpc_Besu_cFPv,
};
#pragma pop

/* 8053FBE4-8053FBF0 -00001 000C+00 0/1 0/0 0/0 .data            @5527 */
#pragma push
#pragma force_active on
SECTION_DATA static void* lit_5527[3] = {
    (void*)NULL,
    (void*)0xFFFFFFFF,
    (void*)wait__12daNpc_Besu_cFPv,
};
#pragma pop

/* 8053FBF0-8053FBFC -00001 000C+00 0/1 0/0 0/0 .data            @5529 */
#pragma push
#pragma force_active on
SECTION_DATA static void* lit_5529[3] = {
    (void*)NULL,
    (void*)0xFFFFFFFF,
    (void*)wait__12daNpc_Besu_cFPv,
};
#pragma pop

extern "C" void cutConversationAboutPachinko__12daNpc_Besu_cFi();
/* 8053FBFC-8053FC54 -00001 0058+00 1/1 0/0 0/0 .data            @5771 */
SECTION_DATA static void* lit_5771[22] = {
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x204),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x20C),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x20C),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x20C),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x20C),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x5F8),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x5F8),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x5F8),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x5F8),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x5F8),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x20C),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x20C),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x20C),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x5F8),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x5F8),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x5F8),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x5F8),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x5F8),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x5F8),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x5F8),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x584),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x5D8),
};

/* 8053FC54-8053FCAC -00001 0058+00 1/1 0/0 0/0 .data            @5770 */
SECTION_DATA static void* lit_5770[22] = {
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x1CC),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x180),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x1CC),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x1CC),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x1CC),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x1CC),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x1CC),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x1CC),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x1CC),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x1CC),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x198),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x1CC),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x1CC),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x1CC),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x1CC),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x1CC),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x1CC),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x1CC),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x1CC),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x1CC),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x1BC),
    (void*)(((char*)cutConversationAboutPachinko__12daNpc_Besu_cFi) + 0x1CC),
};
