// TODO: This isn't a real file, this is a hack to build OK with -sym on
// To properly fix, these symbols need to be compiler generated

/* 80140C80-80140CDC 13B5C0 005C+00 1/0 0/0 0/0 .text            __dt__8dEyeHL_cFv */
// dEyeHL_c::~dEyeHL_c() {
extern "C" void __dt__8dEyeHL_cFv() {
    // NONMATCHING
}

/* 80140CDC-80140D24 13B61C 0048+00 0/0 1/0 0/0 .text            __dt__18daPy_sightPacket_cFv */
// daPy_sightPacket_c::~daPy_sightPacket_c() {
extern "C" void __dt__18daPy_sightPacket_cFv() {
    // NONMATCHING
}

/* 80140D24-80140D80 13B664 005C+00 3/2 0/0 0/0 .text            __dt__16daPy_frameCtrl_cFv */
// daPy_frameCtrl_c::~daPy_frameCtrl_c() {
extern "C" void __dt__16daPy_frameCtrl_cFv() {
    // NONMATCHING
}

/* 80140D80-80140DCC 13B6C0 004C+00 1/1 0/0 0/0 .text            __ct__16daPy_frameCtrl_cFv */
// daPy_frameCtrl_c::daPy_frameCtrl_c() {
extern "C" void __ct__16daPy_frameCtrl_cFv() {
    // NONMATCHING
}

/* 80140DCC-80140DF0 13B70C 0024+00 1/1 0/0 0/0 .text            __defctor__14daPy_anmHeap_cFv */
// void daPy_anmHeap_c::__defctor() {
extern "C" void __defctor__14daPy_anmHeap_cFv() {
    // NONMATCHING
}

/* 80140DF0-80140E2C 13B730 003C+00 2/2 0/0 0/0 .text            __dt__19mDoExt_AnmRatioPackFv */
extern "C" void __dt__19mDoExt_AnmRatioPackFv() {
    // NONMATCHING
}

/* 80140E2C-80140E40 13B76C 0014+00 1/1 0/0 0/0 .text            __ct__19mDoExt_AnmRatioPackFv */
extern "C" void __ct__19mDoExt_AnmRatioPackFv() {
    // NONMATCHING
}

/* 80140E40-80140EB8 13B780 0078+00 4/3 0/0 0/0 .text            __dt__16dBgS_LinkRoofChkFv */
// dBgS_LinkRoofChk::~dBgS_LinkRoofChk() {
extern "C" void __dt__16dBgS_LinkRoofChkFv() {
    // NONMATCHING
}

/* 80140EB8-80140F30 13B7F8 0078+00 4/3 0/0 0/0 .text            __dt__15dBgS_LinkGndChkFv */
// dBgS_LinkGndChk::~dBgS_LinkGndChk() {
extern "C" void __dt__15dBgS_LinkGndChkFv() {
    // NONMATCHING
}

/* 80140F30-80140FA0 13B870 0070+00 3/2 0/0 0/0 .text            __dt__13dBgS_LinkAcchFv */
// dBgS_LinkAcch::~dBgS_LinkAcch() {
extern "C" void __dt__13dBgS_LinkAcchFv() {
    // NONMATCHING
}

/* 80140FA0-80141020 13B8E0 0080+00 1/1 0/0 0/0 .text            __ct__8dCcD_CpsFv */
// dCcD_Cps::dCcD_Cps() {
extern "C" void __ct__8dCcD_CpsFv() {
    // NONMATCHING
}

/* 80141020-801410A4 13B960 0084+00 1/1 0/0 0/0 .text            __ct__8dCcD_CylFv */
// dCcD_Cyl::dCcD_Cyl() {
extern "C" void __ct__8dCcD_CylFv() {
    // NONMATCHING
}

/* 801410A4-801410EC 13B9E4 0048+00 0/0 1/0 0/0 .text            __dt__9cCcD_SttsFv */
// cCcD_Stts::~cCcD_Stts() {
extern "C" void __dt__9cCcD_SttsFv() {
    // NONMATCHING
}

/* 801410EC-8014111C 13BA2C 0030+00 1/1 0/0 0/0 .text            __ct__16daPy_actorKeep_cFv */
extern "C" void __ct__16daPy_actorKeep_cFv() {
    // NONMATCHING
}

/* 8014111C-8014112C 13BA5C 0010+00 1/1 0/0 0/0 .text
 * onNoResetFlg2__9daPy_py_cFQ29daPy_py_c9daPy_FLG2             */
extern "C" void onNoResetFlg2__9daPy_py_cFQ29daPy_py_c9daPy_FLG2(daPy_py_c* this_, daPy_py_c::daPy_FLG2 pFlag) {
    this_->mNoResetFlg2 |= pFlag;
}

/* 8014112C-8014113C 13BA6C 0010+00 1/1 0/0 0/0 .text
 * offNoResetFlg0__9daPy_py_cFQ29daPy_py_c9daPy_FLG0            */
extern "C" void offNoResetFlg0__9daPy_py_cFQ29daPy_py_c9daPy_FLG0() {
    // NONMATCHING
}

/* 8014113C-80141190 13BA7C 0054+00 1/1 0/0 0/0 .text            mDoAud_seStartLevel__FUlPC3VecUlSc
 */
extern "C" void mDoAud_seStartLevel__FUlPC3VecUlSc() {
    // NONMATCHING
}

/* 80141190-8014119C 13BAD0 000C+00 1/1 0/0 0/0 .text
 * checkEndResetFlg2__9daPy_py_cCFQ29daPy_py_c11daPy_ERFLG2     */
extern "C" void checkEndResetFlg2__9daPy_py_cCFQ29daPy_py_c11daPy_ERFLG2() {
    // NONMATCHING
}

/* 8014119C-801411B0 13BADC 0014+00 1/1 0/0 0/0 .text            dComIfGp_setBottleStatus__FUcUc */
static void dComIfGp_setBottleStatus__FUcUc(u8 param_0, u8 param_1) {
    // NONMATCHING
}

/* 801411B0-801411D4 13BAF0 0024+00 1/1 0/0 0/0 .text            getSumouMode__9daPy_py_cCFv */
extern "C" void getSumouMode__9daPy_py_cCFv() {
    // NONMATCHING
}

/* 801411D4-801411E0 13BB14 000C+00 1/1 0/0 0/0 .text
 * checkNoResetFlg3__9daPy_py_cCFQ29daPy_py_c9daPy_FLG3         */
extern "C" void checkNoResetFlg3__9daPy_py_cCFQ29daPy_py_c9daPy_FLG3() {
    // NONMATCHING
}

/* 801411E0-801411F0 13BB20 0010+00 1/1 0/0 0/0 .text            onCondition__11dEvt_info_cFUs */
extern "C" void onCondition__11dEvt_info_cFUs() {
    // NONMATCHING
}

/* 801411F0-80141200 13BB30 0010+00 1/1 4/4 0/0 .text            __ct__8cM3dGPlaFv */
// cM3dGPla::cM3dGPla() {
extern "C" void __ct__8cM3dGPlaFv() {
    // NONMATCHING
}

/* 80141200-80141210 13BB40 0010+00 1/1 0/0 0/0 .text            offCondition__11dEvt_info_cFUs */
extern "C" void offCondition__11dEvt_info_cFUs() {
    // NONMATCHING
}

/* 80141210-80141230 13BB50 0020+00 1/1 0/0 0/0 .text            checkShieldGet__9daPy_py_cFv */
extern "C" BOOL checkShieldGet__9daPy_py_cFv() {
    return dComIfGs_getSelectEquipShield() != NO_ITEM;
}

/* 80141230-80141264 13BB70 0034+00 1/1 0/0 0/0 .text            fopAcM_onSwitch__FPC10fopAc_ac_ci
 */
extern "C" void fopAcM_onSwitch__FPC10fopAc_ac_ci(fopAc_ac_c const* param_0, int param_1) {
    // NONMATCHING
}

/* 80141264-80141294 13BBA4 0030+00 1/1 0/0 0/0 .text            dComIfGs_isItemFirstBit__FUc */
extern "C" int dComIfGs_isItemFirstBit__FUc(u8 i_no) {
    return g_dComIfG_gameInfo.info.getPlayer().getGetItem().isFirstBit(i_no);
}

/* 80141294-801412A0 13BBD4 000C+00 1/1 0/0 0/0 .text
 * dStage_stagInfo_GetSaveTbl__FP21stage_stag_info_class        */
extern "C" void dStage_stagInfo_GetSaveTbl__FP21stage_stag_info_class() {
    // NONMATCHING
}

/* 801412A0-801412B0 13BBE0 0010+00 1/1 0/0 0/0 .text            dComIfGp_getStage__Fv */
extern "C" void dComIfGp_getStage__Fv() {
    // NONMATCHING
}

/* 801412B0-801412BC 13BBF0 000C+00 1/1 0/0 0/0 .text            checkEquipHeavyBoots__9daPy_py_cCFv
 */
extern "C" u32 checkEquipHeavyBoots__9daPy_py_cCFv(daPy_py_c* this_) {
    return this_->checkNoResetFlg0(daPy_py_c::FLG0_EQUIP_HVY_BOOTS);
}

/* 801412BC-801412C4 13BBFC 0008+00 1/1 4/4 0/0 .text            fopAcM_GetName__FPv */
extern "C" void fopAcM_GetName__FPv() {
    // NONMATCHING
}

/* 801412C4-801412D4 13BC04 0010+00 1/1 0/0 0/0 .text
 * onNoResetFlg0__9daPy_py_cFQ29daPy_py_c9daPy_FLG0             */
extern "C" void onNoResetFlg0__9daPy_py_cFQ29daPy_py_c9daPy_FLG0(daPy_py_c* this_, daPy_py_c::daPy_FLG0 pFlag) {
    this_->mNoResetFlg0 |= pFlag;
}

/* 801412D4-801412F8 13BC14 0024+00 1/1 0/0 0/0 .text            isOrderOK__14dEvt_control_cFv */
extern "C" void isOrderOK__14dEvt_control_cFv() {
    // NONMATCHING
}

/* 801412F8-80141308 13BC38 0010+00 1/1 0/0 0/0 .text            dComIfGp_getEvent__Fv */
extern "C" dEvt_control_c& dComIfGp_getEvent__Fv() {
    return g_dComIfG_gameInfo.play.getEvent();
}

/* 80141308-80141324 13BC48 001C+00 1/1 0/0 0/0 .text            dComIfGp_checkPlayerStatus0__FiUl
 */
extern "C" u32 dComIfGp_checkPlayerStatus0__FiUl(int param_0, u32 param_1) {
    // NONMATCHING
}

/* 80141324-80141340 13BC64 001C+00 1/1 0/0 0/0 .text            dComIfGp_checkPlayerStatus1__FiUl
 */
extern "C" u32 dComIfGp_checkPlayerStatus1__FiUl(int param_0, u32 param_1) {
    // NONMATCHING
}

/* 80141340-8014134C 13BC80 000C+00 1/1 0/0 0/0 .text
 * checkEndResetFlg1__9daPy_py_cCFQ29daPy_py_c11daPy_ERFLG1     */
extern "C" u32 checkEndResetFlg1__9daPy_py_cCFQ29daPy_py_c11daPy_ERFLG1(daPy_py_c* this_, daPy_py_c::daPy_ERFLG1 pFlag) {
    return this_->mEndResetFlg1 & pFlag;
}

/* 8014134C-8014135C 13BC8C 0010+00 1/1 0/0 0/0 .text            dComIfGp_getEventManager__Fv */
extern "C" dEvent_manager_c& dComIfGp_getEventManager__Fv() {
    return g_dComIfG_gameInfo.play.getEvtManager();
}

/* 8014135C-8014136C 13BC9C 0010+00 1/1 0/0 0/0 .text
 * offNoResetFlg1__9daPy_py_cFQ29daPy_py_c9daPy_FLG1            */
extern "C" void offNoResetFlg1__9daPy_py_cFQ29daPy_py_c9daPy_FLG1() {
    // NONMATCHING
}

/* 8014136C-8014137C 13BCAC 0010+00 1/1 0/0 0/0 .text
 * offNoResetFlg2__9daPy_py_cFQ29daPy_py_c9daPy_FLG2            */
extern "C" void offNoResetFlg2__9daPy_py_cFQ29daPy_py_c9daPy_FLG2() {
    // NONMATCHING
}

/* 8014137C-80141388 13BCBC 000C+00 1/1 0/0 0/0 .text            setSpecialDemoType__11daPy_demo_cFv
 */
extern "C" void setSpecialDemoType__11daPy_demo_cFv(daPy_demo_c* this_) {
    this_->setDemoType(5);
}

/* 80141388-8014139C 13BCC8 0014+00 1/1 0/0 0/0 .text            checkCommandCatch__11dEvt_info_cFv
 */
extern "C" void checkCommandCatch__11dEvt_info_cFv() {
    // NONMATCHING
}

/* 8014139C-801413CC 13BCDC 0030+00 1/1 1/1 0/0 .text            dComIfGs_isEventBit__FUs */
extern "C" BOOL dComIfGs_isEventBit__FUs(u16 id) {
    return g_dComIfG_gameInfo.info.getEvent().isEventBit(id);
}

/* 801413CC-801413D8 13BD0C 000C+00 1/1 0/0 0/0 .text            checkWolf__9daPy_py_cCFv */
extern "C" u32 checkWolf__9daPy_py_cCFv(daPy_py_c* this_) {
    return this_->checkNoResetFlg1(daPy_py_c::FLG1_IS_WOLF);
}

/* 801413D8-801413F8 13BD18 0020+00 1/1 0/0 0/0 .text            checkSwordGet__9daPy_py_cFv */
extern "C" BOOL checkSwordGet__9daPy_py_cFv() {
    return dComIfGs_getSelectEquipSword() != 0xFF;
}

/* 801413F8-80141404 13BD38 000C+00 1/1 0/0 0/0 .text
 * checkResetFlg0__9daPy_py_cCFQ29daPy_py_c10daPy_RFLG0         */
extern "C" u32 checkResetFlg0__9daPy_py_cCFQ29daPy_py_c10daPy_RFLG0(daPy_py_c* this_, daPy_py_c::daPy_RFLG0 pFlag) {
    return this_->mResetFlg0 & pFlag;
}

/* 80141404-80141410 13BD44 000C+00 1/1 0/0 0/0 .text            ChkGroundHit__9dBgS_AcchCFv */
extern "C" bool ChkGroundHit__9dBgS_AcchCFv(dBgS_Acch* this_) {
    return this_->m_flags & dBgS_Acch::GROUND_HIT;
}

/* 80141410-8014141C 13BD50 000C+00 1/1 0/0 0/0 .text
 * checkNoResetFlg0__9daPy_py_cCFQ29daPy_py_c9daPy_FLG0         */
extern "C" u32 checkNoResetFlg0__9daPy_py_cCFQ29daPy_py_c9daPy_FLG0(daPy_py_c* this_, daPy_py_c::daPy_FLG0 pFlag) {
    return this_->mNoResetFlg0 & pFlag;
}

/* 8014141C-80141438 13BD5C 001C+00 1/1 0/0 0/0 .text            dComIfGp_getPlayerCameraID__Fi */
static int dComIfGp_getPlayerCameraID__Fi(int param_0) {
    // NONMATCHING
}

/* 80141438-80141450 13BD78 0018+00 1/1 0/0 0/0 .text            dComIfGp_event_chkEventFlag__FUs */
extern "C" u16 dComIfGp_event_chkEventFlag__FUs(u16 flag) {
    return g_dComIfG_gameInfo.play.getEvent().chkEventFlag(flag);
}

/* 80141450-80141464 13BD90 0014+00 1/1 0/0 0/0 .text            checkCommandDoor__11dEvt_info_cFv
 */
extern "C" BOOL checkCommandDoor__11dEvt_info_cFv(dEvt_info_c* this_) {
    return this_->mCommand == 3;
}

/* 80141464-801414A4 13BDA4 0040+00 1/1 0/0 0/0 .text
 * dComIfGp_evmng_getMyStaffId__FPCcP10fopAc_ac_ci              */
extern "C" s32 dComIfGp_evmng_getMyStaffId__FPCcP10fopAc_ac_ci(char const* param_0, fopAc_ac_c* param_1, int param_2) {
    return dComIfGp_getPEvtManager()->getMyStaffId(param_0, param_1, param_2);
}

/* 801414A4-801414C0 13BDE4 001C+00 1/1 0/0 0/0 .text            dComIfGp_event_runCheck__Fv */
extern "C" BOOL dComIfGp_event_runCheck__Fv() {
    return g_dComIfG_gameInfo.play.getEvent().runCheck();
}

/* 801414C0-801414CC 13BE00 000C+00 1/1 0/0 0/0 .text
 * checkNoResetFlg2__9daPy_py_cCFQ29daPy_py_c9daPy_FLG2         */
extern "C" u32 checkNoResetFlg2__9daPy_py_cCFQ29daPy_py_c9daPy_FLG2(daPy_py_c* this_, daPy_py_c::daPy_FLG2 pFlag) {
    return this_->mNoResetFlg2 & pFlag;
}

/* 801414CC-801414D8 13BE0C 000C+00 1/1 2/2 0/0 .text            checkMagneBootsOn__9daPy_py_cCFv */
extern "C" u32 checkMagneBootsOn__9daPy_py_cCFv(daPy_py_c* this_) {
    return this_->checkNoResetFlg0(daPy_py_c::FLG0_MAGNE_BOOTS_ON);
}

/* 801414D8-801414E8 13BE18 0010+00 1/1 2/2 0/0 .text            dComIfGp_getHorseActor__Fv */
extern "C" daHorse_c* dComIfGp_getHorseActor__Fv() {
    return (daHorse_c*)g_dComIfG_gameInfo.play.getPlayerPtr(1);
}

/* 801414E8-801414F4 13BE28 000C+00 1/1 0/0 0/0 .text checkBoarSingleBattle__9daPy_py_cCFv */
extern "C" u32 checkBoarSingleBattle__9daPy_py_cCFv(daPy_py_c* this_) {
    return this_->checkNoResetFlg2(daPy_py_c::FLG2_BOAR_SINGLE_BATTLE);
}

/* 801414F4-80141500 13BE34 000C+00 1/1 0/0 0/0 .text
 * checkEndResetFlg0__9daPy_py_cCFQ29daPy_py_c11daPy_ERFLG0     */
extern "C" u32 checkEndResetFlg0__9daPy_py_cCFQ29daPy_py_c11daPy_ERFLG0(daPy_py_c* this_, daPy_py_c::daPy_ERFLG0 pFlag) {
    return this_->mEndResetFlg0 & pFlag;
}

/* 80141500-80141508 13BE40 0008+00 1/0 0/0 0/0 .text            getMidnaAtnPos__9daPy_py_cCFv */
extern "C" bool getMidnaAtnPos__9daPy_py_cCFv() {
    return false;
}

/* 80141508-8014150C 13BE48 0004+00 1/0 0/0 0/0 .text setMidnaMsgNum__9daPy_py_cFP10fopAc_ac_cUs
 */
extern "C" void setMidnaMsgNum__9daPy_py_cFP10fopAc_ac_cUs() {
    /* empty function */
}

/* 8014150C-80141514 13BE4C 0008+00 1/0 0/0 0/0 .text            getModelMtx__9daPy_py_cFv */
extern "C" void getModelMtx__9daPy_py_cFv() {
    // NONMATCHING
}

/* 80141514-8014151C 13BE54 0008+00 1/0 0/0 0/0 .text            getInvMtx__9daPy_py_cFv */
extern "C" void getInvMtx__9daPy_py_cFv() {
    // NONMATCHING
}

/* 8014151C-80141524 13BE5C 0008+00 1/0 0/0 0/0 .text            getShadowTalkAtnPos__9daPy_py_cFv
 */
extern "C" void getShadowTalkAtnPos__9daPy_py_cFv() {
    // NONMATCHING
}

/* 80141524-8014152C 13BE64 0008+00 1/0 0/0 0/0 .text            getLeftItemMatrix__9daPy_py_cFv */
extern "C" void getLeftItemMatrix__9daPy_py_cFv() {
    // NONMATCHING
}

/* 8014152C-80141534 13BE6C 0008+00 1/0 0/0 0/0 .text            getRightItemMatrix__9daPy_py_cFv */
extern "C" void getRightItemMatrix__9daPy_py_cFv() {
    // NONMATCHING
}

/* 80141534-8014153C 13BE74 0008+00 1/0 0/0 0/0 .text            getLeftHandMatrix__9daPy_py_cFv */
extern "C" void getLeftHandMatrix__9daPy_py_cFv() {
    // NONMATCHING
}

/* 8014153C-80141544 13BE7C 0008+00 1/0 0/0 0/0 .text            getRightHandMatrix__9daPy_py_cFv */
extern "C" void getRightHandMatrix__9daPy_py_cFv() {
    // NONMATCHING
}

/* 80141544-8014154C 13BE84 0008+00 1/0 0/0 0/0 .text getLinkBackBone1Matrix__9daPy_py_cFv */
extern "C" void getLinkBackBone1Matrix__9daPy_py_cFv() {
    // NONMATCHING
}

/* 8014154C-80141554 13BE8C 0008+00 1/0 0/0 0/0 .text            getWolfMouthMatrix__9daPy_py_cFv */
extern "C" void getWolfMouthMatrix__9daPy_py_cFv() {
    // NONMATCHING
}

/* 80141554-8014155C 13BE94 0008+00 1/0 0/0 0/0 .text getWolfBackbone2Matrix__9daPy_py_cFv */
extern "C" void getWolfBackbone2Matrix__9daPy_py_cFv() {
    // NONMATCHING
}

/* 8014155C-80141564 13BE9C 0008+00 1/0 0/0 0/0 .text            getBottleMtx__9daPy_py_cFv */
extern "C" bool getBottleMtx__9daPy_py_cFv() {
    return NULL;
}

/* 80141564-8014156C 13BEA4 0008+00 1/0 0/0 0/0 .text            checkPlayerGuard__9daPy_py_cCFv */
extern "C" bool checkPlayerGuard__9daPy_py_cCFv() {
    return false;
}

/* 8014156C-80141574 13BEAC 0008+00 1/0 0/0 0/0 .text            checkAutoJump__9daPy_py_cCFv */
extern "C" bool checkAutoJump__9daPy_py_cCFv() {
    return false;
}

/* 80141574-8014157C 13BEB4 0008+00 1/0 0/0 0/0 .text            checkSideStep__9daPy_py_cCFv */
extern "C" bool checkSideStep__9daPy_py_cCFv() {
    return false;
}

/* 8014157C-80141584 13BEBC 0008+00 1/0 0/0 0/0 .text            checkWolfTriggerJump__9daPy_py_cCFv
 */
extern "C" bool checkWolfTriggerJump__9daPy_py_cCFv() {
    return false;
}

/* 80141584-8014158C 13BEC4 0008+00 1/0 0/0 0/0 .text            checkGuardBreakMode__9daPy_py_cCFv
 */
extern "C" bool checkGuardBreakMode__9daPy_py_cCFv() {
    return false;
}

/* 8014158C-80141594 13BECC 0008+00 1/0 0/0 0/0 .text            checkLv3Slide__9daPy_py_cCFv */
extern "C" bool checkLv3Slide__9daPy_py_cCFv() {
    return false;
}

/* 80141594-8014159C 13BED4 0008+00 1/0 0/0 0/0 .text checkWolfHowlDemoMode__9daPy_py_cCFv */
extern "C" bool checkWolfHowlDemoMode__9daPy_py_cCFv() {
    return false;
}

/* 8014159C-801415A4 13BEDC 0008+00 1/0 0/0 0/0 .text checkChainBlockPushPull__9daPy_py_cFv */
extern "C" bool checkChainBlockPushPull__9daPy_py_cFv() {
    return false;
}

/* 801415A4-801415AC 13BEE4 0008+00 1/0 0/0 0/0 .text            checkElecDamage__9daPy_py_cCFv */
extern "C" bool checkElecDamage__9daPy_py_cCFv() {
    return false;
}

/* 801415AC-801415B4 13BEEC 0008+00 1/0 0/0 0/0 .text checkEmptyBottleSwing__9daPy_py_cCFv */
extern "C" bool checkEmptyBottleSwing__9daPy_py_cCFv() {
    return false;
}

/* 801415B4-801415BC 13BEF4 0008+00 1/0 0/0 0/0 .text            checkBottleSwingMode__9daPy_py_cCFv
 */
extern "C" bool checkBottleSwingMode__9daPy_py_cCFv() {
    return false;
}

/* 801415BC-801415C4 13BEFC 0008+00 1/0 0/0 0/0 .text            checkHawkWait__9daPy_py_cCFv */
extern "C" bool checkHawkWait__9daPy_py_cCFv() {
    return false;
}

/* 801415C4-801415CC 13BF04 0008+00 1/0 0/0 0/0 .text            checkGoatThrow__9daPy_py_cCFv */
extern "C" bool checkGoatThrow__9daPy_py_cCFv() {
    return false;
}

/* 801415CC-801415D4 13BF0C 0008+00 1/0 0/0 0/0 .text            checkGoatThrowAfter__9daPy_py_cCFv
 */
extern "C" bool checkGoatThrowAfter__9daPy_py_cCFv() {
    return false;
}

/* 801415D4-801415DC 13BF14 0008+00 1/0 0/0 0/0 .text            checkWolfTagLockJump__9daPy_py_cCFv
 */
extern "C" bool checkWolfTagLockJump__9daPy_py_cCFv() {
    return false;
}

/* 801415DC-801415E4 13BF1C 0008+00 1/0 0/0 0/0 .text checkWolfTagLockJumpLand__9daPy_py_cCFv */
extern "C" bool checkWolfTagLockJumpLand__9daPy_py_cCFv() {
    return false;
}

/* 801415E4-801415EC 13BF24 0008+00 1/0 0/0 0/0 .text            checkWolfRope__9daPy_py_cFv */
extern "C" bool checkWolfRope__9daPy_py_cFv() {
    return false;
}

/* 801415EC-801415F4 13BF2C 0008+00 1/0 0/0 0/0 .text            checkWolfRopeHang__9daPy_py_cCFv */
extern "C" bool checkWolfRopeHang__9daPy_py_cCFv() {
    return false;
}

/* 801415F4-801415FC 13BF34 0008+00 1/0 0/0 0/0 .text            checkRollJump__9daPy_py_cCFv */
extern "C" bool checkRollJump__9daPy_py_cCFv() {
    return false;
}

/* 801415FC-80141604 13BF3C 0008+00 1/0 0/0 0/0 .text            checkGoronRideWait__9daPy_py_cCFv
 */
extern "C" bool checkGoronRideWait__9daPy_py_cCFv() {
    return false;
}

/* 80141604-8014160C 13BF44 0008+00 1/0 0/0 0/0 .text            checkWolfChain__9daPy_py_cCFv */
extern "C" bool checkWolfChain__9daPy_py_cCFv() {
    return false;
}

/* 8014160C-80141614 13BF4C 0008+00 1/0 0/0 0/0 .text            checkWolfWait__9daPy_py_cCFv */
extern "C" bool checkWolfWait__9daPy_py_cCFv() {
    return false;
}

/* 80141614-8014161C 13BF54 0008+00 1/0 0/0 0/0 .text            checkWolfJumpAttack__9daPy_py_cCFv
 */
extern "C" bool checkWolfJumpAttack__9daPy_py_cCFv() {
    return false;
}

/* 8014161C-80141624 13BF5C 0008+00 1/0 0/0 0/0 .text            checkWolfRSit__9daPy_py_cCFv */
extern "C" bool checkWolfRSit__9daPy_py_cCFv() {
    return false;
}

/* 80141624-8014162C 13BF64 0008+00 2/0 0/0 0/0 .text            checkBubbleFly__9daPy_py_cCFv */
extern "C" bool checkBubbleFly__9daPy_py_cCFv() {
    return false;
}

/* 8014162C-80141634 13BF6C 0008+00 1/0 0/0 0/0 .text            checkBottleDrinkEnd__9daPy_py_cCFv
 */
extern "C" bool checkBottleDrinkEnd__9daPy_py_cCFv() {
    return false;
}

/* 80141634-8014163C 13BF74 0008+00 1/0 0/0 0/0 .text            checkWolfDig__9daPy_py_cCFv */
extern "C" bool checkWolfDig__9daPy_py_cCFv() {
    return false;
}

/* 8014163C-80141644 13BF7C 0008+00 1/0 0/0 0/0 .text            checkCutCharge__9daPy_py_cCFv */
extern "C" bool checkCutCharge__9daPy_py_cCFv() {
    return false;
}

/* 80141644-8014164C 13BF84 0008+00 1/0 0/0 0/0 .text            checkCutTurnCharge__9daPy_py_cCFv
 */
extern "C" bool checkCutTurnCharge__9daPy_py_cCFv() {
    return false;
}

/* 8014164C-80141654 13BF8C 0008+00 1/0 0/0 0/0 .text checkCutLargeJumpCharge__9daPy_py_cCFv */
extern "C" bool checkCutLargeJumpCharge__9daPy_py_cCFv() {
    return false;
}

/* 80141654-8014165C 13BF94 0008+00 2/0 0/0 0/0 .text            getBokoFlamePos__9daPy_py_cFP4cXyz
 */
extern "C" bool getBokoFlamePos__9daPy_py_cFP4cXyz() {
    return false;
}

/* 8014165C-80141664 13BF9C 0008+00 1/0 0/0 0/0 .text            checkComboCutTurn__9daPy_py_cCFv */
extern "C" bool checkComboCutTurn__9daPy_py_cCFv() {
    return false;
}

/* 80141664-8014166C 13BFA4 0008+00 1/0 0/0 0/0 .text            checkClimbMove__9daPy_py_cCFv */
extern "C" bool checkClimbMove__9daPy_py_cCFv() {
    return false;
}

/* 8014166C-80141674 13BFAC 0008+00 1/0 0/0 0/0 .text            checkGrassWhistle__9daPy_py_cCFv */
extern "C" bool checkGrassWhistle__9daPy_py_cCFv() {
    return false;
}

/* 80141674-8014167C 13BFB4 0008+00 1/0 0/0 0/0 .text            checkBoarRun__9daPy_py_cCFv */
extern "C" bool checkBoarRun__9daPy_py_cCFv() {
    return false;
}

/* 8014167C-80141684 13BFBC 0008+00 2/0 0/0 0/0 .text            checkFmChainPut__9daPy_py_cCFv */
extern "C" bool checkFmChainPut__9daPy_py_cCFv() {
    return false;
}

/* 80141684-8014168C 13BFC4 0008+00 2/0 0/0 0/0 .text            checkHorseElecDamage__9daPy_py_cCFv
 */
extern "C" bool checkHorseElecDamage__9daPy_py_cCFv() {
    return false;
}

/* 8014168C-80141694 13BFCC 0008+00 1/0 0/0 0/0 .text getBaseAnimeFrameRate__9daPy_py_cCFv */
extern "C" f32 getBaseAnimeFrameRate__9daPy_py_cCFv() {
    return 1.0f;
}

/* 80141694-8014169C 13BFD4 0008+00 1/0 0/0 0/0 .text            getBaseAnimeFrame__9daPy_py_cCFv */
extern "C" f32 getBaseAnimeFrame__9daPy_py_cCFv() {
    return 0.0f;
}

/* 8014169C-801416A0 13BFDC 0004+00 1/0 0/0 0/0 .text            setAnimeFrame__9daPy_py_cFf */
extern "C" void setAnimeFrame__9daPy_py_cFf() {
    /* empty function */
}

/* 801416A0-801416A8 13BFE0 0008+00 1/0 0/0 0/0 .text checkWolfLock__9daPy_py_cCFP10fopAc_ac_c */
extern "C" bool checkWolfLock__9daPy_py_cCFP10fopAc_ac_c() {
    return false;
}

/* 801416A8-801416B0 13BFE8 0008+00 1/0 0/0 0/0 .text cancelWolfLock__9daPy_py_cFP10fopAc_ac_c */
extern "C" bool cancelWolfLock__9daPy_py_cFP10fopAc_ac_c() {
    return false;
}

/* 801416B0-801416B8 13BFF0 0008+00 1/0 0/0 0/0 .text            getItemID__9daPy_py_cCFv */
extern "C" s32 getItemID__9daPy_py_cCFv() {
    return -1;
}

/* 801416B8-801416C0 13BFF8 0008+00 1/0 0/0 0/0 .text exchangeGrabActor__9daPy_py_cFP10fopAc_ac_c
 */
extern "C" bool exchangeGrabActor__9daPy_py_cFP10fopAc_ac_c() {
    return false;
}

/* 801416C0-801416C8 13C000 0008+00 1/0 0/0 0/0 .text setForceGrab__9daPy_py_cFP10fopAc_ac_cii */
extern "C" bool setForceGrab__9daPy_py_cFP10fopAc_ac_cii() {
    return false;
}

/* 801416C8-801416CC 13C008 0004+00 1/0 0/0 0/0 .text            setForcePutPos__9daPy_py_cFRC4cXyz
 */
extern "C" void setForcePutPos__9daPy_py_cFRC4cXyz() {
    /* empty function */
}

/* 801416CC-801416D4 13C00C 0008+00 1/0 0/0 0/0 .text            checkPlayerNoDraw__9daPy_py_cFv */
extern "C" bool checkPlayerNoDraw__9daPy_py_cFv() {
    return false;
}

/* 801416D4-801416DC 13C014 0008+00 2/0 0/0 0/0 .text            checkRopeTag__9daPy_py_cFv */
extern "C" bool checkRopeTag__9daPy_py_cFv() {
    return false;
}

/* 801416DC-801416E0 13C01C 0004+00 1/0 0/0 0/0 .text            voiceStart__9daPy_py_cFUl */
extern "C" void voiceStart__9daPy_py_cFUl() {
    /* empty function */
}

/* 801416E0-801416E4 13C020 0004+00 1/0 0/0 0/0 .text            seStartOnlyReverb__9daPy_py_cFUl */
extern "C" void seStartOnlyReverb__9daPy_py_cFUl() {
    /* empty function */
}

/* 801416E4-801416E8 13C024 0004+00 1/0 0/0 0/0 .text seStartOnlyReverbLevel__9daPy_py_cFUl */
extern "C" void seStartOnlyReverbLevel__9daPy_py_cFUl() {
    /* empty function */
}

/* 801416E8-801416EC 13C028 0004+00 1/0 0/0 0/0 .text            setOutPower__9daPy_py_cFfsi */
extern "C" void setOutPower__9daPy_py_cFfsi() {
    /* empty function */
}

/* 801416EC-801416F0 13C02C 0004+00 1/0 0/0 0/0 .text
 * setGrabCollisionOffset__9daPy_py_cFffP13cBgS_PolyInfo        */
extern "C" void setGrabCollisionOffset__9daPy_py_cFffP13cBgS_PolyInfo() {
    /* empty function */
}

/* 801416F0-801416F4 13C030 0004+00 2/0 0/0 0/0 .text            onMagneGrab__9daPy_py_cFff */
extern "C" void onMagneGrab__9daPy_py_cFff() {
    /* empty function */
}

/* 801416F4-801416FC 13C034 0008+00 1/0 0/0 0/0 .text            getModelJointMtx__9daPy_py_cFUs */
extern "C" bool getModelJointMtx__9daPy_py_cFUs() {
    return NULL;
}

/* 801416FC-80141704 13C03C 0008+00 1/0 0/0 0/0 .text            getHeadMtx__9daPy_py_cFv */
extern "C" bool getHeadMtx__9daPy_py_cFv() {
    return NULL;
}

/* 80141704-8014170C 13C044 0008+00 1/0 0/0 0/0 .text setHookshotCarryOffset__9daPy_py_cFUiPC4cXyz
 */
extern "C" bool setHookshotCarryOffset__9daPy_py_cFUiPC4cXyz() {
    return false;
}

/* 8014170C-80141714 13C04C 0008+00 1/0 0/0 0/0 .text            checkIronBallReturn__9daPy_py_cCFv
 */
extern "C" bool checkIronBallReturn__9daPy_py_cCFv() {
    return false;
}

/* 80141714-8014171C 13C054 0008+00 1/0 0/0 0/0 .text checkIronBallGroundStop__9daPy_py_cCFv */
extern "C" bool checkIronBallGroundStop__9daPy_py_cCFv() {
    return false;
}

/* 8014171C-80141724 13C05C 0008+00 1/0 0/0 0/0 .text
 * checkSingleBoarBattleSecondBowReady__9daPy_py_cCFv           */
extern "C" bool checkSingleBoarBattleSecondBowReady__9daPy_py_cCFv() {
    return false;
}

/* 80141724-8014172C 13C064 0008+00 2/0 0/0 0/0 .text checkPointSubWindowMode__9daPy_py_cCFv */
extern "C" bool checkPointSubWindowMode__9daPy_py_cCFv() {
    return false;
}

/* 8014172C-80141730 13C06C 0004+00 1/0 0/0 0/0 .text            setClothesChange__9daPy_py_cFi */
extern "C" void setClothesChange__9daPy_py_cFi() {
    /* empty function */
}

/* 80141730-80141734 13C070 0004+00 1/0 0/0 0/0 .text setPlayerPosAndAngle__9daPy_py_cFPA4_f */
extern "C" void setPlayerPosAndAngle__9daPy_py_cFPA4_f() {
    /* empty function */
}

/* 80141734-80141738 13C074 0004+00 1/0 0/0 0/0 .text
 * setPlayerPosAndAngle__9daPy_py_cFPC4cXyzPC5csXyz             */
extern "C" void setPlayerPosAndAngle__9daPy_py_cFPC4cXyzPC5csXyz() {
    /* empty function */
}

/* 80141738-8014173C 13C078 0004+00 1/0 0/0 0/0 .text setPlayerPosAndAngle__9daPy_py_cFPC4cXyzsi
 */
extern "C" void setPlayerPosAndAngle__9daPy_py_cFPC4cXyzsi() {
    /* empty function */
}

/* 8014173C-80141744 13C07C 0008+00 1/0 0/0 0/0 .text            setThrowDamage__9daPy_py_cFsffiii
 */
extern "C" bool setThrowDamage__9daPy_py_cFsffiii() {
    return false;
}

/* 80141744-8014174C 13C084 0008+00 1/0 0/0 0/0 .text            checkSetNpcTks__9daPy_py_cFP4cXyzii
 */
extern "C" bool checkSetNpcTks__9daPy_py_cFP4cXyzii() {
    return false;
}

/* 8014174C-80141754 13C08C 0008+00 1/0 0/0 0/0 .text            setRollJump__9daPy_py_cFffs */
extern "C" bool setRollJump__9daPy_py_cFffs() {
    return 0;
}

/* 80141754-80141758 13C094 0004+00 1/0 0/0 0/0 .text playerStartCollisionSE__9daPy_py_cFUlUl */
extern "C" void playerStartCollisionSE__9daPy_py_cFUlUl() {
    /* empty function */
}

/* 80141758-8014175C 13C098 0004+00 2/0 0/0 0/0 .text changeTextureAnime__9daPy_py_cFUsUsi */
extern "C" void changeTextureAnime__9daPy_py_cFUsUsi() {
    /* empty function */
}

/* 8014175C-80141760 13C09C 0004+00 2/0 0/0 0/0 .text cancelChangeTextureAnime__9daPy_py_cFv */
extern "C" void cancelChangeTextureAnime__9daPy_py_cFv() {
    /* empty function */
}

/* 80141760-80141764 13C0A0 0004+00 1/0 0/0 0/0 .text cancelDungeonWarpReadyNeck__9daPy_py_cFv */
extern "C" void cancelDungeonWarpReadyNeck__9daPy_py_cFv() {
    /* empty function */
}

/* 80141764-80141768 13C0A4 0004+00 1/0 0/0 0/0 .text
 * onSceneChangeArea__9daPy_py_cFUcUcP10fopAc_ac_c              */
extern "C" void onSceneChangeArea__9daPy_py_cFUcUcP10fopAc_ac_c() {
    /* empty function */
}

/* 80141768-8014176C 13C0A8 0004+00 1/0 0/0 0/0 .text
 * onSceneChangeAreaJump__9daPy_py_cFUcUcP10fopAc_ac_c          */
extern "C" void onSceneChangeAreaJump__9daPy_py_cFUcUcP10fopAc_ac_c() {
    /* empty function */
}

/* 8014176C-80141770 13C0AC 0004+00 1/0 0/0 0/0 .text            onSceneChangeDead__9daPy_py_cFUci
 */
extern "C" void onSceneChangeDead__9daPy_py_cFUci() {
    /* empty function */
}

/* 80141770-80141778 13C0B0 0008+00 1/0 0/0 0/0 .text            getSpinnerActor__9daPy_py_cFv */
extern "C" bool getSpinnerActor__9daPy_py_cFv() {
    return NULL;
}

/* 80141778-80141780 13C0B8 0008+00 1/0 0/0 0/0 .text checkHorseRideNotReady__9daPy_py_cCFv */
extern "C" bool checkHorseRideNotReady__9daPy_py_cCFv() {
    return false;
}

/* 80141780-80141788 13C0C0 0008+00 1/0 0/0 0/0 .text            checkArrowChargeEnd__9daPy_py_cCFv
 */
extern "C" bool checkArrowChargeEnd__9daPy_py_cCFv() {
    return false;
}

/* 80141788-80141790 13C0C8 0008+00 1/0 0/0 0/0 .text            getSearchBallScale__9daPy_py_cCFv
 */
extern "C" f32 getSearchBallScale__9daPy_py_cCFv() {
    return 0.0f;
}

/* 80141790-80141798 13C0D0 0008+00 1/0 0/0 0/0 .text            checkFastShotTime__9daPy_py_cFv */
extern "C" bool checkFastShotTime__9daPy_py_cFv() {
    return 0;
}

/* 80141798-801417A0 13C0D8 0008+00 1/0 0/0 0/0 .text            checkNoEquipItem__9daPy_py_cCFv */
extern "C" bool checkNoEquipItem__9daPy_py_cCFv() {
    return true;
}

/* 801417A0-801417A8 13C0E0 0008+00 2/0 0/0 0/0 .text            checkFireMaterial__9daPy_py_cCFv */
extern "C" bool checkFireMaterial__9daPy_py_cCFv() {
    return false;
}

/* 801417A8-801417B0 13C0E8 0008+00 1/0 0/0 0/0 .text            checkKandelaarSwing__9daPy_py_cCFi
 */
extern "C" bool checkKandelaarSwing__9daPy_py_cCFi() {
    return false;
}

/* 801417B0-801417B8 13C0F0 0008+00 1/0 0/0 0/0 .text getBoardCutTurnOffsetAngleY__9daPy_py_cCFv
 */
extern "C" bool getBoardCutTurnOffsetAngleY__9daPy_py_cCFv() {
    return 0;
}

/* 801417B8-801417C0 13C0F8 0008+00 2/0 0/0 0/0 .text            getMagneHitPos__9daPy_py_cFv */
extern "C" cXyz* getMagneHitPos__9daPy_py_cFv(daPy_py_c* this_) {
    return &this_->mSwordTopPos;
}

/* 801417C0-801417C8 13C100 0008+00 1/0 0/0 0/0 .text            getMagneBootsTopVec__9daPy_py_cFv
 */
extern "C" cXyz* getMagneBootsTopVec__9daPy_py_cFv(daPy_py_c* this_) {
    return &this_->current.pos;
}

/* 801417C8-801417D0 13C108 0008+00 1/0 0/0 0/0 .text            checkUseKandelaar__9daPy_py_cFi */
extern "C" bool checkUseKandelaar__9daPy_py_cFi() {
    return false;
}

/* 801417D0-801417D4 13C110 0004+00 1/0 0/0 0/0 .text setDkCaught__9daPy_py_cFP10fopAc_ac_c */
extern "C" void setDkCaught__9daPy_py_cFP10fopAc_ac_c() {
    /* empty function */
}

/* 801417D4-801417D8 13C114 0004+00 1/0 0/0 0/0 .text onPressedDamage__9daPy_py_cFRC4cXyzs */
extern "C" void onPressedDamage__9daPy_py_cFRC4cXyzs() {
    /* empty function */
}

/* 801417D8-801417E0 13C118 0008+00 1/0 0/0 0/0 .text checkPriActorOwn__9daPy_py_cCFPC10fopAc_ac_c
 */
extern "C" bool checkPriActorOwn__9daPy_py_cCFPC10fopAc_ac_c() {
    return false;
}

/* 801417E0-801417E8 13C120 0008+00 1/0 0/0 0/0 .text
 * onWolfEnemyBiteAll__9daPy_py_cFP10fopAc_ac_cQ29daPy_py_c9daPy_FLG2 */
extern "C" bool onWolfEnemyBiteAll__9daPy_py_cFP10fopAc_ac_cQ29daPy_py_c9daPy_FLG2() {
    return false;
}

/* 801417E8-801417F0 13C128 0008+00 1/0 0/0 0/0 .text
 * checkWolfEnemyBiteAllOwn__9daPy_py_cCFPC10fopAc_ac_c         */
extern "C" bool checkWolfEnemyBiteAllOwn__9daPy_py_cCFPC10fopAc_ac_c() {
    return false;
}

/* 801417F0-801417F4 13C130 0004+00 1/0 0/0 0/0 .text setWolfEnemyHangBiteAngle__9daPy_py_cFs */
extern "C" void setWolfEnemyHangBiteAngle__9daPy_py_cFs() {
    /* empty function */
}

/* 801417F4-801417F8 13C134 0004+00 1/0 0/0 0/0 .text            setKandelaarMtx__9daPy_py_cFPA4_fii
 */
extern "C" void setKandelaarMtx__9daPy_py_cFPA4_fii() {
    /* empty function */
}

/* 801417F8-80141800 13C138 0008+00 1/0 0/0 0/0 .text getStickAngleFromPlayerShape__9daPy_py_cCFPs
 */
extern "C" bool getStickAngleFromPlayerShape__9daPy_py_cCFPs() {
    return false;
}

/* 80141800-80141808 13C140 0008+00 1/0 0/0 0/0 .text            checkSpinnerPathMove__9daPy_py_cFv
 */
extern "C" bool checkSpinnerPathMove__9daPy_py_cFv() {
    return false;
}

/* 80141808-80141810 13C148 0008+00 1/0 0/0 0/0 .text checkSpinnerTriggerAttack__9daPy_py_cFv */
extern "C" bool checkSpinnerTriggerAttack__9daPy_py_cFv() {
    return false;
}

/* 80141810-80141814 13C150 0004+00 1/0 0/0 0/0 .text onSpinnerPathForceRemove__9daPy_py_cFv */
extern "C" void onSpinnerPathForceRemove__9daPy_py_cFv() {
    /* empty function */
}

/* 80141814-8014181C 13C154 0008+00 1/0 0/0 0/0 .text            getIronBallBgHit__9daPy_py_cCFv */
extern "C" bool getIronBallBgHit__9daPy_py_cCFv() {
    return 0;
}

/* 8014181C-80141824 13C15C 0008+00 1/0 0/0 0/0 .text            getIronBallCenterPos__9daPy_py_cFv
 */
extern "C" bool getIronBallCenterPos__9daPy_py_cFv() {
    return NULL;
}

/* 80141824-8014182C 13C164 0008+00 1/0 0/0 0/0 .text checkCanoeFishingGetLeft__9daPy_py_cCFv */
extern "C" bool checkCanoeFishingGetLeft__9daPy_py_cCFv() {
    return false;
}

/* 8014182C-80141834 13C16C 0008+00 1/0 0/0 0/0 .text checkCanoeFishingGetRight__9daPy_py_cCFv */
extern "C" bool checkCanoeFishingGetRight__9daPy_py_cCFv() {
    return false;
}

/* 80141834-8014183C 13C174 0008+00 1/0 0/0 0/0 .text            checkBeeChildDrink__9daPy_py_cCFv
 */
extern "C" bool checkBeeChildDrink__9daPy_py_cCFv() {
    return false;
}

/* 8014183C-80141840 13C17C 0004+00 1/0 0/0 0/0 .text            skipPortalObjWarp__9daPy_py_cFv */
extern "C" void skipPortalObjWarp__9daPy_py_cFv() {
    /* empty function */
}

/* 80141840-80141848 13C180 0008+00 1/0 0/0 0/0 .text checkTreasureRupeeReturn__9daPy_py_cCFi */
extern "C" bool checkTreasureRupeeReturn__9daPy_py_cCFi() {
    return false;
}

/* 80141848-8014184C 13C188 0004+00 1/0 0/0 0/0 .text setSumouReady__9daPy_py_cFP10fopAc_ac_c */
extern "C" void setSumouReady__9daPy_py_cFP10fopAc_ac_c() {
    /* empty function */
}

/* 8014184C-80141854 13C18C 0008+00 1/0 0/0 0/0 .text checkAcceptDungeonWarpAlink__9daPy_py_cFi */
extern "C" bool checkAcceptDungeonWarpAlink__9daPy_py_cFi() {
    return false;
}

/* 80141854-8014185C 13C194 0008+00 1/0 0/0 0/0 .text            getSumouCounter__9daPy_py_cCFv */
extern "C" bool getSumouCounter__9daPy_py_cCFv() {
    return 0;
}

/* 8014185C-80141864 13C19C 0008+00 1/0 0/0 0/0 .text            checkSumouWithstand__9daPy_py_cCFv
 */
extern "C" bool checkSumouWithstand__9daPy_py_cCFv() {
    return 0;
}

/* 80141864-80141868 13C1A4 0004+00 1/0 0/0 0/0 .text            cancelGoronThrowEvent__9daPy_py_cFv
 */
extern "C" void cancelGoronThrowEvent__9daPy_py_cFv() {
    /* empty function */
}

/* 80141868-8014186C 13C1A8 0004+00 1/0 0/0 0/0 .text setSumouGraspCancelCount__9daPy_py_cFi */
extern "C" void setSumouGraspCancelCount__9daPy_py_cFi() {
    /* empty function */
}

/* 8014186C-80141870 13C1AC 0004+00 1/0 0/0 0/0 .text setSumouPushBackDirection__9daPy_py_cFs */
extern "C" void setSumouPushBackDirection__9daPy_py_cFs() {
    /* empty function */
}

/* 80141870-80141874 13C1B0 0004+00 1/0 0/0 0/0 .text            setSumouLoseHeadUp__9daPy_py_cFv */
extern "C" void setSumouLoseHeadUp__9daPy_py_cFv() {
    /* empty function */
}

/* 80141874-8014187C 13C1B4 0008+00 1/0 0/0 0/0 .text getGiantPuzzleAimAngle__9daPy_py_cCFv */
extern "C" void getGiantPuzzleAimAngle__9daPy_py_cCFv() {
    // NONMATCHING
}

/* 8014187C-80141880 13C1BC 0004+00 1/0 0/0 0/0 .text setGoronSideMove__9daPy_py_cFP10fopAc_ac_c
 */
extern "C" void setGoronSideMove__9daPy_py_cFP10fopAc_ac_c() {
    /* empty function */
}

/* 80141880-80141884 13C1C0 0004+00 1/0 0/0 0/0 .text setCargoCarry__9daPy_py_cFP10fopAc_ac_c */
extern "C" void setCargoCarry__9daPy_py_cFP10fopAc_ac_c() {
    /* empty function */
}

/* 80141884-8014188C 13C1C4 0008+00 2/0 0/0 0/0 .text            getDpdFarFlg__9daPy_py_cCFv */
extern "C" bool getDpdFarFlg__9daPy_py_cCFv() {
    return false;
}

/* 8014188C-80141894 13C1CC 0008+00 1/0 0/0 0/0 .text            getHookshotTopPos__9daPy_py_cFv */
extern "C" bool getHookshotTopPos__9daPy_py_cFv() {
    return NULL;
}

/* 80141894-8014189C 13C1D4 0008+00 1/0 0/0 0/0 .text checkHookshotReturnMode__9daPy_py_cCFv */
extern "C" bool checkHookshotReturnMode__9daPy_py_cCFv() {
    return false;
}

/* 8014189C-801418A4 13C1DC 0008+00 1/0 0/0 0/0 .text checkHookshotShootReturnMode__9daPy_py_cCFv
 */
extern "C" bool checkHookshotShootReturnMode__9daPy_py_cCFv() {
    return false;
}

/* 801418A4-801418AC 13C1E4 0008+00 1/0 0/0 0/0 .text            checkOctaIealHang__9daPy_py_cCFv */
extern "C" bool checkOctaIealHang__9daPy_py_cCFv() {
    return false;
}

/* 801418AC-801418B0 13C1EC 0004+00 1/0 0/0 0/0 .text            cancelOctaIealHang__9daPy_py_cFv */
extern "C" void cancelOctaIealHang__9daPy_py_cFv() {
    /* empty function */
}

/* 801418B0-801418B4 13C1F0 0004+00 1/0 0/0 0/0 .text cancelDragonHangBackJump__9daPy_py_cFv */
extern "C" void cancelDragonHangBackJump__9daPy_py_cFv() {
    /* empty function */
}

/* 801418B4-801418B8 13C1F4 0004+00 1/0 0/0 0/0 .text            setOctaIealWildHang__9daPy_py_cFv
 */
extern "C" void setOctaIealWildHang__9daPy_py_cFv() {
    /* empty function */
}

/* 801418B8-801418C0 13C1F8 0008+00 1/0 0/0 0/0 .text            checkDragonHangRide__9daPy_py_cCFv
 */
extern "C" bool checkDragonHangRide__9daPy_py_cCFv() {
    return false;
}

/* 801418C0-801418C4 13C200 0004+00 1/0 0/0 0/0 .text changeDragonActor__9daPy_py_cFP10fopAc_ac_c
 */
extern "C" void changeDragonActor__9daPy_py_cFP10fopAc_ac_c() {
    /* empty function */
}

/* 801418C4-801418CC 13C204 0008+00 1/0 0/0 0/0 .text getClothesChangeWaitTimer__9daPy_py_cCFv */
extern "C" bool getClothesChangeWaitTimer__9daPy_py_cCFv() {
    return 0;
}

/* 801418CC-801418D4 13C20C 0008+00 1/0 0/0 0/0 .text getShieldChangeWaitTimer__9daPy_py_cCFv */
extern "C" bool getShieldChangeWaitTimer__9daPy_py_cCFv() {
    return 0;
}

/* 801418D4-801418DC 13C214 0008+00 1/0 0/0 0/0 .text getSwordChangeWaitTimer__9daPy_py_cCFv */
extern "C" bool getSwordChangeWaitTimer__9daPy_py_cCFv() {
    return 0;
}

/* 801418DC-801418E4 13C21C 0008+00 1/0 0/0 0/0 .text            checkMetamorphose__9daPy_py_cCFv */
extern "C" bool checkMetamorphose__9daPy_py_cCFv() {
    return false;
}

/* 801418E4-801418EC 13C224 0008+00 1/0 0/0 0/0 .text checkWolfDownAttackPullOut__9daPy_py_cCFv */
extern "C" bool checkWolfDownAttackPullOut__9daPy_py_cCFv() {
    return false;
}

/* 801418EC-801418F4 13C22C 0008+00 1/0 0/0 0/0 .text checkBootsOrArmorHeavy__9daPy_py_cCFv */
extern "C" bool checkBootsOrArmorHeavy__9daPy_py_cCFv() {
    return false;
}

/* 801418F4-801418FC 13C234 0008+00 1/0 0/0 0/0 .text getBottleOpenAppearItem__9daPy_py_cCFv */
extern "C" s32 getBottleOpenAppearItem__9daPy_py_cCFv() {
    return -1;
}

/* 801418FC-80141904 13C23C 0008+00 1/0 0/0 0/0 .text            checkItemSwordEquip__9daPy_py_cCFv
 */
extern "C" bool checkItemSwordEquip__9daPy_py_cCFv() {
    return false;
}

/* 80141904-8014190C 13C244 0008+00 1/0 0/0 0/0 .text            getSinkShapeOffset__9daPy_py_cCFv
 */
extern "C" f32 getSinkShapeOffset__9daPy_py_cCFv() {
    return 0.0f;
}

/* 8014190C-80141914 13C24C 0008+00 1/0 0/0 0/0 .text            checkSinkDead__9daPy_py_cCFv */
extern "C" bool checkSinkDead__9daPy_py_cCFv() {
    return false;
}

/* 80141914-8014191C 13C254 0008+00 1/0 0/0 0/0 .text            checkHorseStart__9daPy_py_cFv */
extern "C" bool checkHorseStart__9daPy_py_cFv() {
    return false;
}

/* 8014191C-80141924 13C25C 0008+00 1/0 0/0 0/0 .text            getWolfHowlMgrP__9daPy_py_cFv */
extern "C" bool getWolfHowlMgrP__9daPy_py_cFv() {
    return NULL;
}

/* 80141924-8014192C 13C264 0008+00 1/0 0/0 0/0 .text checkWolfHowlSuccessAnime__9daPy_py_cCFv */
extern "C" bool checkWolfHowlSuccessAnime__9daPy_py_cCFv() {
    return false;
}

/* 8014192C-80141934 13C26C 0008+00 1/0 0/0 0/0 .text            checkCopyRodTopUse__9daPy_py_cFv */
extern "C" bool checkCopyRodTopUse__9daPy_py_cFv() {
    return false;
}

/* 80141934-8014193C 13C274 0008+00 1/0 0/0 0/0 .text            checkCopyRodEquip__9daPy_py_cCFv */
extern "C" bool checkCopyRodEquip__9daPy_py_cCFv() {
    return false;
}

/* 8014193C-80141944 13C27C 0008+00 1/0 0/0 0/0 .text            checkCutJumpMode__9daPy_py_cCFv */
extern "C" bool checkCutJumpMode__9daPy_py_cCFv() {
    return false;
}

/* 80141944-8014194C 13C284 0008+00 1/1 0/0 0/0 .text            getZeldaActor__9daHorse_cFv */
extern "C" void getZeldaActor__9daHorse_cFv() {
    // NONMATCHING
}

/* 8014194C-8014195C 13C28C 0010+00 1/1 0/0 0/0 .text            dComIfGp_getDoStatus__Fv */
static u8 dComIfGp_getDoStatus__Fv() {
    // NONMATCHING
}

/* 8014195C-8014196C 13C29C 0010+00 1/1 5/5 0/0 .text            __ct__4cXyzFfff */
extern "C" void __ct__4cXyzFfff(f32 param_0, f32 param_1, f32 param_2) {
    // NONMATCHING
}

/* 8014196C-80141988 13C2AC 001C+00 1/1 0/0 0/0 .text            dMeter2Info_offUseButton__Fi */
extern "C" void dMeter2Info_offUseButton__Fi() {
    // NONMATCHING
}

/* 80141988-80141990 -00001 0008+00 0/0 0/0 0/0 .text            setLinkState__14Z2CreatureLinkFUc
 */
extern "C" void setLinkState__14Z2CreatureLinkFUc(Z2CreatureLink* this_, u8 param_0) {
    *(u8*)(((u8*)this_) + 192) /* this->field_0xc0 */ = (u8)(param_0);
}

/* 80141990-801419A0 13C2D0 0010+00 1/1 0/0 0/0 .text            dComIfGs_getRupee__Fv */
u16 dComIfGs_getRupee__Fv() {
    // NONMATCHING
}

/* 801419A0-801419B8 13C2E0 0018+00 1/1 0/0 0/0 .text            dComIfGp_setItemRupeeCount__Fl */
void dComIfGp_setItemRupeeCount__Fl(s32 param_0) {
    // NONMATCHING
}

/* 801419B8-801419F4 13C2F8 003C+00 1/1 0/0 0/0 .text dMeter2Info_setFloatingMessage__FUssb */
extern "C" void dMeter2Info_setFloatingMessage__FUssb() {
    // NONMATCHING
}

/* 801419F4-80141A04 13C334 0010+00 1/1 0/0 0/0 .text            onForcePanic__9daMidna_cFv */
extern "C" void onForcePanic__9daMidna_cFv() {
    // NONMATCHING
}

/* 80141A04-80141A10 13C344 000C+00 1/1 0/0 0/0 .text checkForceNormalColor__9daMidna_cCFv */
extern "C" void checkForceNormalColor__9daMidna_cCFv() {
    // NONMATCHING
}

/* 80141A10-80141A1C 13C350 000C+00 1/1 0/0 0/0 .text            checkForceTiredColor__9daMidna_cCFv
 */
extern "C" void checkForceTiredColor__9daMidna_cCFv() {
    // NONMATCHING
}

/* 80141A1C-80141A84 13C35C 0068+00 1/1 0/0 0/0 .text            checkMidnaTired__9daMidna_cFv */
extern "C" void checkMidnaTired__9daMidna_cFv() {
    // NONMATCHING
}

/* 80141A84-80141A94 13C3C4 0010+00 1/1 0/0 0/0 .text            onNoServiceWait__9daMidna_cFv */
extern "C" void onNoServiceWait__9daMidna_cFv() {
    // NONMATCHING
}

/* 80141A94-80141ACC 13C3D4 0038+00 1/1 0/0 0/0 .text            setControllActorData__8daCrod_cFv
 */
extern "C" void setControllActorData__8daCrod_cFv() {
    // NONMATCHING
}

/* 80141ACC-80141AE8 13C40C 001C+00 1/1 0/0 0/0 .text
 * PrmAbstract<Q312daObjMovebox5Act_c5Prm_e>__5daObjFPC10fopAc_ac_cQ312daObjMovebox5Act_c5Prm_eQ312daObjMovebox5Act_c5Prm_e
 */
extern "C" void func_80141ACC(void* _this, fopAc_ac_c const* param_0,
                                  daObjMovebox::Act_c::Prm_e param_1,
                                  daObjMovebox::Act_c::Prm_e param_2) {
    // NONMATCHING
}

/* 80141AE8-80141B04 13C428 001C+00 1/1 4/4 0/0 .text            cLib_calcTimer<Uc>__FPUc */
extern "C" u8 func_80141AE8(u8*) {
    // NONMATCHING
}

/* 80141B04-801446D4 13C444 2BD0+00 0/0 1/0 0/0 .text            __sinit_d_a_alink_cpp */
void __sinit_d_a_alink_cpp(){// NONMATCHING
}

#pragma push
#pragma force_active on
REGISTER_CTORS(0x80141B04, __sinit_d_a_alink_cpp);
#pragma pop

/* 801446D4-801446DC 13F014 0008+00 1/0 0/0 0/0 .text            @36@__dt__12dBgS_ObjAcchFv */
static void func_801446D4() {
    // NONMATCHING
}

/* 801446DC-801446E4 13F01C 0008+00 1/0 0/0 0/0 .text            @20@__dt__12dBgS_ObjAcchFv */
static void func_801446DC() {
    // NONMATCHING
}

/* 801446E4-801446EC 13F024 0008+00 1/0 0/0 0/0 .text            @36@__dt__13dBgS_LinkAcchFv */
static void func_801446E4() {
    // NONMATCHING
}

/* 801446EC-801446F4 13F02C 0008+00 1/0 0/0 0/0 .text            @20@__dt__13dBgS_LinkAcchFv */
static void func_801446EC() {
    // NONMATCHING
}

/* 801446F4-801446FC 13F034 0008+00 1/0 0/0 0/0 .text            @20@__dt__15dBgS_LinkGndChkFv */
static void func_801446F4() {
    // NONMATCHING
}

/* 801446FC-80144704 13F03C 0008+00 1/0 0/0 0/0 .text            @76@__dt__15dBgS_LinkGndChkFv */
static void func_801446FC() {
    // NONMATCHING
}

/* 80144704-8014470C 13F044 0008+00 1/0 0/0 0/0 .text            @60@__dt__15dBgS_LinkGndChkFv */
static void func_80144704() {
    // NONMATCHING
}

/* 8014470C-80144714 13F04C 0008+00 1/0 0/0 0/0 .text            @16@__dt__16dBgS_LinkRoofChkFv */
static void func_8014470C() {
    // NONMATCHING
}

/* 80144714-8014471C 13F054 0008+00 1/0 0/0 0/0 .text            @52@__dt__16dBgS_LinkRoofChkFv */
static void func_80144714() {
    // NONMATCHING
}

/* 8014471C-80144724 13F05C 0008+00 1/0 0/0 0/0 .text            @36@__dt__16dBgS_LinkRoofChkFv */
static void func_8014471C() {
    // NONMATCHING
}

/* 80392094-80392094 01E6F4 0000+00 0/0 0/0 0/0 .rodata          @stringBase0 */
