/**
 * d_a_alink_HIO.inc
 * Player HostIO interface handling
 */

#include "d/actor/d_a_alink.h"

/* 80140B88-80140B98 13B4C8 0010+00 1/1 0/0 0/0 .text            __ct__12daAlinkHIO_cFv */
daAlinkHIO_c::daAlinkHIO_c() {}

/* 80140B98-80140BD4 13B4D8 003C+00 1/1 0/0 0/0 .text            __dt__17daAlinkHIO_wolf_cFv */
daAlinkHIO_wolf_c::~daAlinkHIO_wolf_c() {}

/* 80140BD4-80140C10 13B514 003C+00 1/1 0/0 0/0 .text            __dt__16daAlinkHIO_cut_cFv */
daAlinkHIO_cut_c::~daAlinkHIO_cut_c() {}

/* 80140C10-80140C80 13B550 0070+00 1/0 0/0 0/0 .text            __dt__12daAlinkHIO_cFv */
daAlinkHIO_c::~daAlinkHIO_c() {}