name: Assign issue to commenter
on:
  issue_comment:
    types: [created]

jobs:
  assign_to_commenter:
    permissions:
        issues: write
    runs-on: ubuntu-latest
    steps:
    - name: Assign issue to commenter
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const issueComment = context.payload.comment;
          const issue = context.payload.issue;
          if (issueComment.body === "/assign") {
            github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              assignees: [issueComment.user.login]
            });
          }
